
-- Description: sql script in creating Account Payable table
CREATE TABLE `ACCOUNT_PAYABLE` (
  `ACCOUNT_PAYABLE_ID` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `PAYABLE_PROFILE_ID` int(10) unsigned NOT NULL,
  `DATE` date NOT NULL,
  `DUE_DATE` date NOT NULL,
  `PAID_DATE` date DEFAULT NULL,
  `REFERENCE_ID` varchar(20) NOT NULL,
  `DESCRIPTION` varchar(150) NOT NULL,
  `AMOUNT` decimal(10,2) NOT NULL,
  `PAID` tinyint(1) NOT NULL,
  `DELETED` tinyint(1) NOT NULL,
  `CREATED_BY` int(10) unsigned NOT NULL,
  `CREATED_DATE` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_BY` int(10) unsigned NOT NULL,
  `UPDATED_DATE` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  PRIMARY KEY (`ACCOUNT_PAYABLE_ID`),
  KEY `ACCT_PAYABLE_PROFILE_ID` (`PAYABLE_PROFILE_ID`),
  CONSTRAINT `ACCT_PAYABLE_PROFILE_ID` FOREIGN KEY (`PAYABLE_PROFILE_ID`) REFERENCES `PAYABLE_PROFILE` (`PAYABLE_PROFILE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1