
-- Description: sql script in creating Account Receivable table
CREATE TABLE `ACCOUNT_RECEIVABLE` (
  `ACCOUNT_RECEIVABLE_ID` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `DATE` date NOT NULL,
  `REFERENCE_ID` varchar(20) NOT NULL,
  `DESCRIPTION` varchar(150) NOT NULL,
  `PRINCIPAL` decimal(10,2) NOT NULL DEFAULT '0.00',
  `AMOUNT` decimal(10,2) NOT NULL,
  `EARNED_INTEREST` decimal(10,2) NOT NULL,
  `DUE_DATE` date DEFAULT NULL,
  `INTEREST_DATE` date NOT NULL,
  `PAID` tinyint(1) NOT NULL,
  `DELETED` tinyint(1) NOT NULL,
  `CUSTOMER_ID` int(10) unsigned NOT NULL,
  `CREATED_BY` int(10) unsigned NOT NULL,
  `CREATED_DATE` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_BY` int(10) unsigned NOT NULL,
  `UPDATED_DATE` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  PRIMARY KEY (`ACCOUNT_RECEIVABLE_ID`),
  KEY `FK_ACCOUNT_RECEIVABLE_CUSTOMER` (`CUSTOMER_ID`),
  CONSTRAINT `FK_ACCOUNT_RECEIVABLE_CUSTOMER` FOREIGN KEY (`CUSTOMER_ID`) REFERENCES `CUSTOMER` (`CUSTOMER_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 ROW_FORMAT=DYNAMIC

