
-- Description: Create script for EB_OBJECT
DROP TABLE IF EXISTS EB_OBJECT;
CREATE TABLE EB_OBJECT (
       EB_OBJECT_ID int(10) unsigned NOT NULL AUTO_INCREMENT,
       OBJECT_TYPE_ID int(10) unsigned NOT NULL,
       CREATED_BY int(10) unsigned NOT NULL,
       CREATED_DATE timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
       PRIMARY KEY (EB_OBJECT_ID),
       KEY FK_EB_OBJECT_CREATED_BY (CREATED_BY),
       KEY FK_EB_OBJECT_OBJECT_TYPE_ID (OBJECT_TYPE_ID),
       CONSTRAINT FK_EB_OBJECT_CREATED_BY FOREIGN KEY (CREATED_BY) REFERENCES USER (USER_ID),
       CONSTRAINT FK_EB_OBJECT_OBJECT_TYPE_ID FOREIGN KEY (OBJECT_TYPE_ID) REFERENCES OBJECT_TYPE (OBJECT_TYPE_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;