
-- Description: sql script in creating object to object relationship
DROP TABLE IF EXISTS OBJECT_TO_OBJECT;
CREATE TABLE OBJECT_TO_OBJECT (
       OBJECT_TO_OBJECT_ID int(10) unsigned NOT NULL AUTO_INCREMENT,
       FROM_OBJECT_ID int(10) unsigned NOT NULL,
       TO_OBJECT_ID int(10) unsigned NOT NULL,
       OR_TYPE_ID int(10) unsigned NOT NULL,
       CREATED_BY int(10) unsigned NOT NULL,
       CREATED_DATE timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
       PRIMARY KEY (OBJECT_TO_OBJECT_ID),
       KEY FK_OBJECT_TO_OBJECT_FROM_OBJECT_ID (FROM_OBJECT_ID),
       KEY FK_OBJECT_TO_OBJECT_TO_OBJECT_ID (TO_OBJECT_ID),
       KEY FK_OBJECT_TO_OBJECT_OR_TYPE_ID (OR_TYPE_ID),
       KEY FK_OBJECT_TO_OBJECT_CREATED_BY (CREATED_BY),
       CONSTRAINT FK_OBJECT_TO_OBJECT_FROM_OBJECT_ID FOREIGN KEY (FROM_OBJECT_ID) REFERENCES EB_OBJECT (EB_OBJECT_ID),
       CONSTRAINT FK_OBJECT_TO_OBJECT_TO_OBJECT_ID FOREIGN KEY (TO_OBJECT_ID) REFERENCES EB_OBJECT (EB_OBJECT_ID),
       CONSTRAINT FK_OBJECT_TO_OBJECT_OR_TYPE_ID FOREIGN KEY (OR_TYPE_ID) REFERENCES OR_TYPE (OR_TYPE_ID),
       CONSTRAINT FK_OBJECT_TO_CREATED_BY FOREIGN KEY (CREATED_BY) REFERENCES USER (USER_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;