
-- Description: Script for creating payment.
CREATE TABLE `PAYMENT` (
  `PAYMENT_ID` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `DATE` date NOT NULL,
  `DESCRIPTION` varchar(150) NOT NULL,
  `REFERENCE_ID` varchar(20) NOT NULL,
  `AMOUNT` decimal(10,2) NOT NULL,
  `PAYMENT_CHANGE` decimal(10,2) NOT NULL,
  `DELETED` tinyint(1) NOT NULL,
  `CUSTOMER_ID` int(10) unsigned NOT NULL,
  `CREATED_BY` int(10) unsigned NOT NULL,
  `CREATED_DATE` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_BY` int(10) unsigned NOT NULL,
  `UPDATED_DATE` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  PRIMARY KEY (`PAYMENT_ID`),
  KEY `FK_DEBT_PAYMENT_CUSTOMER` (`CUSTOMER_ID`),
  CONSTRAINT `FK_DEBT_PAYMENT_CUSTOMER` FOREIGN KEY (`CUSTOMER_ID`) REFERENCES `CUSTOMER` (`CUSTOMER_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1