
-- Description: Script for creating salary type.

DROP TABLE IF EXISTS SALARY_TYPE;

CREATE TABLE `SALARY_TYPE` (
  `SALARY_TYPE_ID` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `NAME` varchar(20) NOT NULL,
  `ACTIVE` tinyint(1) NOT NULL,
  `EB_OBJECT_ID` int(10) unsigned DEFAULT NULL,
  `CREATED_BY` int(10) unsigned NOT NULL,
  `CREATED_DATE` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_BY` int(10) unsigned NOT NULL,
  `UPDATED_DATE` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  PRIMARY KEY (`SALARY_TYPE_ID`),
  KEY `FK_SALARY_TYPE_EB_OBJECT_ID` (`EB_OBJECT_ID`),
  KEY `FK_SALARY_TYPE_CREATED_BY` (`CREATED_BY`),
  KEY `FK_SALARY_TYPE_UPDATED_BY` (`UPDATED_BY`),
  CONSTRAINT `FK_SALARY_TYPE_EB_OBJECT_ID` FOREIGN KEY (EB_OBJECT_ID) REFERENCES EB_OBJECT (EB_OBJECT_ID),
  CONSTRAINT `FK_SALARY_TYPE_CREATED_BY` FOREIGN KEY (`CREATED_BY`) REFERENCES `USER` (`USER_ID`),
  CONSTRAINT `FK_SALARY_TYPE_UPDATED_BY` FOREIGN KEY (`UPDATED_BY`) REFERENCES `USER` (`USER_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;