
-- Description: sql script in creating AP_LINE table.

DROP TABLE IF EXISTS FORM_WORKFLOW;

CREATE TABLE FORM_WORKFLOW (
       FORM_WORKFLOW_ID int(10) unsigned NOT NULL AUTO_INCREMENT,
       IS_COMPLETE TINYINT(1),
       CURRENT_STATUS_ID INT (10) unsigned NOT NULL,
       PRIMARY KEY (FORM_WORKFLOW_ID),
       KEY FK_FORM_WORKFLOQ_FORM_STATUS (CURRENT_STATUS_ID),
       CONSTRAINT FK_FORM_WORKFLOQ_FORM_STATUS FOREIGN KEY (CURRENT_STATUS_ID) REFERENCES FORM_STATUS (FORM_STATUS_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;