
-- Description: sql script in creating FORM_WORKFLOW_LOG table.

DROP TABLE IF EXISTS FORM_WORKFLOW_LOG;

CREATE TABLE `FORM_WORKFLOW_LOG` (
  `FORM_WORKFLOW_LOG_ID` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `FORM_WORKFLOW_ID` int(10) unsigned NOT NULL,
  `FORM_STATUS_ID` int(10) unsigned NOT NULL,
  `COMMENT` text,
  `CREATED_BY` int(10) unsigned NOT NULL,
  `CREATED_DATE` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`FORM_WORKFLOW_LOG_ID`),
  KEY `FK_FORM_WORKFLOW_LOG_CREATED_BY` (`CREATED_BY`),
  KEY `FK_FORM_STATUS_FORM_STATUS_ID` (`FORM_STATUS_ID`),
  CONSTRAINT `FK_FORM_STATUS_FORM_STATUS_ID` FOREIGN KEY (`FORM_STATUS_ID`) REFERENCES `FORM_STATUS` (`FORM_STATUS_ID`),
  CONSTRAINT `FK_FORM_WORKFLOW_LOG_CREATED_BY` FOREIGN KEY (`CREATED_BY`) REFERENCES `USER` (`USER_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;