
-- Description: sql script in creating PR_OTHER_MATERIALS_ITEM table.

DROP TABLE IF EXISTS PR_OTHER_MATERIALS_ITEM;

CREATE TABLE PR_OTHER_MATERIALS_ITEM (
  PR_OTHER_MATERIALS_ITEM_ID int(10) unsigned NOT NULL AUTO_INCREMENT,
  PROCESSING_REPORT_ID int(10) unsigned NOT NULL,
  WAREHOUSE_ID int(10) unsigned NOT NULL,
  ITEM_ID int(10) unsigned NOT NULL,
  EB_OBJECT_ID int(10) unsigned DEFAULT NULL,
  QUANTITY double NOT NULL,
  UNIT_COST double DEFAULT '0',
  PRIMARY KEY (PR_OTHER_MATERIALS_ITEM_ID),
  KEY FK_PR_OMI_PROCESSING_REPORT_ID (PROCESSING_REPORT_ID),
  KEY FK_PR_OMI_WAREHOUSE_ID (WAREHOUSE_ID),
  KEY FK_PR_OMI_ITEM_ID (ITEM_ID),
  KEY FK_PR_OMI_EB_OBJECT_ID (EB_OBJECT_ID),
  CONSTRAINT FK_PR_OMI_PROCESSING_REPORT_ID FOREIGN KEY (PROCESSING_REPORT_ID) REFERENCES PROCESSING_REPORT (PROCESSING_REPORT_ID),
  CONSTRAINT FK_PR_OMI_WAREHOUSE_ID FOREIGN KEY (WAREHOUSE_ID) REFERENCES WAREHOUSE (WAREHOUSE_ID),
  CONSTRAINT FK_PR_OMI_ITEM_ID FOREIGN KEY (ITEM_ID) REFERENCES ITEM (ITEM_ID),
  CONSTRAINT FK_PR_OMI_EB_OBJECT_ID FOREIGN KEY (EB_OBJECT_ID) REFERENCES EB_OBJECT (EB_OBJECT_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;