
-- Description: sql script in creating PR_OTHER_CHARGE table.

DROP TABLE IF EXISTS PR_OTHER_CHARGE;

CREATE TABLE PR_OTHER_CHARGE (
  PR_OTHER_CHARGE_ID int(10) unsigned NOT NULL AUTO_INCREMENT,
  PROCESSING_REPORT_ID int(10) unsigned NOT NULL,
  AR_LINE_SETUP_ID int(10) unsigned NOT NULL,
  EB_OBJECT_ID int(10) unsigned DEFAULT NULL,
  QUANTITY double DEFAULT '0',
  UNITOFMEASUREMENT_ID int(10) unsigned DEFAULT NULL,
  UP_AMOUNT double DEFAULT '0',
  AMOUNT double DEFAULT '0',
  PRIMARY KEY (PR_OTHER_CHARGE_ID),
  KEY FK_PRAL_LINE_PR_ID (PROCESSING_REPORT_ID),
  KEY FK_PRAL_LINE_SETUP_ID (AR_LINE_SETUP_ID),
  KEY FK_PRAL_LINE_EB_OBJECT_ID (EB_OBJECT_ID),
  CONSTRAINT FK_PRAL_LINE_PR_ID FOREIGN KEY (PROCESSING_REPORT_ID) REFERENCES PROCESSING_REPORT (PROCESSING_REPORT_ID),
  CONSTRAINT FK_PRAL_LINE_SETUP_ID FOREIGN KEY (AR_LINE_SETUP_ID) REFERENCES AR_LINE_SETUP (AR_LINE_SETUP_ID),
  CONSTRAINT FK_PRAL_LINE_EB_OBJECT_ID FOREIGN KEY (EB_OBJECT_ID) REFERENCES EB_OBJECT (EB_OBJECT_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;