
-- Description: sql script in creating PROCESSING_REPORT table.

DROP TABLE IF EXISTS PROCESSING_REPORT;

CREATE TABLE PROCESSING_REPORT (
  PROCESSING_REPORT_ID int(10) unsigned NOT NULL AUTO_INCREMENT,
  PROCESSING_REPORT_TYPE_ID int(10) unsigned DEFAULT '1',
  SEQUENCE_NO int(20) unsigned NOT NULL,
  COMPANY_ID int(10) unsigned NOT NULL,
  DATE date NOT NULL,
  REF_NUMBER varchar(20) DEFAULT NULL,
  REMARKS varchar(200) DEFAULT NULL,
  EB_OBJECT_ID int(10) unsigned DEFAULT NULL,
  FORM_WORKFLOW_ID int(10) unsigned DEFAULT NULL,
  CREATED_BY int(10) unsigned NOT NULL,
  CREATED_DATE timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UPDATED_BY int(10) unsigned NOT NULL,
  UPDATED_DATE timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  PRIMARY KEY (PROCESSING_REPORT_ID),
  KEY FK_MPR_COMPANY_ID (COMPANY_ID),
  KEY FK_MPR_EB_OBJECT_ID (EB_OBJECT_ID),
  KEY FK_MPR_FORM_WORKFLOW_ID (FORM_WORKFLOW_ID),
  KEY FK_MPR_CREATED_BY (CREATED_BY),
  KEY FK_MPR_UPDATED_BY (UPDATED_BY),
  KEY FK_MPR_PROCESSING_TYPE_ID (PROCESSING_REPORT_TYPE_ID),
  CONSTRAINT FK_MPR_COMPANY_ID FOREIGN KEY (COMPANY_ID) REFERENCES COMPANY (COMPANY_ID),
  CONSTRAINT FK_MPR_EB_OBJECT_ID FOREIGN KEY (EB_OBJECT_ID) REFERENCES EB_OBJECT (EB_OBJECT_ID),
  CONSTRAINT FK_MPR_FORM_WORKFLOW_ID FOREIGN KEY (FORM_WORKFLOW_ID) REFERENCES FORM_WORKFLOW (FORM_WORKFLOW_ID),
  CONSTRAINT FK_MPR_PROCESSING_TYPE_ID FOREIGN KEY (PROCESSING_REPORT_TYPE_ID) REFERENCES PROCESSING_REPORT_TYPE (PROCESSING_REPORT_TYPE_ID),
  CONSTRAINT FK_MPR_CREATED_BY FOREIGN KEY (CREATED_BY) REFERENCES USER (USER_ID),
  CONSTRAINT FK_MPR_UPDATED_BY FOREIGN KEY (UPDATED_BY) REFERENCES USER (USER_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;