
-- Description: sql script in creating PROCESSING_REPORT_TYPE table.

DROP TABLE IF EXISTS PROCESSING_REPORT_TYPE;

CREATE TABLE PROCESSING_REPORT_TYPE (
  PROCESSING_REPORT_TYPE_ID int(10) unsigned NOT NULL AUTO_INCREMENT,
  NAME varchar(25) DEFAULT NULL,
  ACTIVE tinyint(1) DEFAULT '1',
  CREATED_BY int(10) unsigned NOT NULL,
  CREATED_DATE timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UPDATED_BY int(10) unsigned NOT NULL,
  UPDATED_DATE timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  PRIMARY KEY (PROCESSING_REPORT_TYPE_ID),
  KEY FK_PRT_CREATED_BY (CREATED_BY),
  KEY FK_PRT_UPDATED_BY (UPDATED_BY),
  CONSTRAINT FK_PRT_CREATED_BY FOREIGN KEY (CREATED_BY) REFERENCES USER (USER_ID),
  CONSTRAINT FK_PRT_UPDATED_BY FOREIGN KEY (UPDATED_BY) REFERENCES USER (USER_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;