
-- Description: sql script in creating UOM_CONVERSION table.

DROP TABLE IF EXISTS UOM_CONVERSION;

CREATE TABLE UOM_CONVERSION (
  UOM_CONVERSION_ID int(10) unsigned NOT NULL AUTO_INCREMENT,
  UOM_FROM int(10) unsigned NOT NULL,
  UOM_TO int(10) unsigned NOT NULL,
  NAME varchar(50) NOT NULL,
  VALUE double NOT NULL,
  ACTIVE tinyint(1) NOT NULL,
  PRIMARY KEY (UOM_CONVERSION_ID),
  KEY FK_UOMC_UNIT_FROM (UOM_FROM),
  KEY FK_UOMC_UNIT_TO (UOM_TO),
  CONSTRAINT FK_UOMC_UNIT_FROM FOREIGN KEY (UOM_FROM) REFERENCES UNIT_MEASUREMENT (UNITOFMEASUREMENT_ID),
  CONSTRAINT FK_UOMC_UNIT_TO FOREIGN KEY (UOM_TO) REFERENCES UNIT_MEASUREMENT (UNITOFMEASUREMENT_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;;