-- Description: mysql views for AR Line Analysis


drop view if exists V_AR_LINE_ANALYSIS;

create view V_AR_LINE_ANALYSIS as
SELECT'AR Transaction' AS SOURCE, 
D.NAME AS DIVISION, D.DIVISION_ID AS DIVISION_ID,
	CONCAT('ART-', SS.SERVICE_SETTING_ID) AS ID,
	1 AS SOURCE_ID,
	ART.SEQUENCE_NO AS SEQ_NO,
	FW.CURRENT_STATUS_ID AS STATUS_ID,
	FS.DESCRIPTION AS STATUS,
	FW.IS_COMPLETE AS COMPLETE,
	ACA.COMPANY_ID AS COMPANY_ID,
	SS.NAME AS SERVICE,
	SS.SERVICE_SETTING_ID AS SERVICE_ID,
	COALESCE(ARS.UNITOFMEASUREMENT_ID, 0)  AS UOM_ID,
	ART.GL_DATE AS MATURITY_DATE,
	ART.TRANSACTION_DATE AS RECEIPT_DATE,
	ART.CUSTOMER_ID AS CUSTOMER_ID,
	ART.CUSTOMER_ACCOUNT_ID AS CUSTOMER_ACCT_ID,
	ART.TRANSACTION_DATE AS REF_DATE,
	ART.TRANSACTION_NUMBER AS REF_NUMBER,
	AC.NAME AS CUSTOMER,
	ACA.NAME AS CUSTOMER_ACCT,
	COALESCE(ARS.QUANTITY, 0) AS QUANTITY,
	COALESCE(ARS.UP_AMOUNT, 0) AS UNIT_PRICE,
	ARS.AMOUNT AS AMOUNT,
	0 AS VAT_AMOUNT FROM SERVICE_SETTING SS
INNER JOIN AR_SERVICE_LINE ARS ON ARS.SERVICE_SETTING_ID = SS.SERVICE_SETTING_ID
INNER JOIN AR_TRANSACTION ART ON ART.AR_TRANSACTION_ID = ARS.AR_TRANSACTION_ID
INNER JOIN DIVISION D ON D.DIVISION_ID= ART.DIVISION_ID
INNER JOIN AR_CUSTOMER AC on AC.AR_CUSTOMER_ID = ART.CUSTOMER_ID
INNER JOIN AR_CUSTOMER_ACCOUNT ACA on ACA.AR_CUSTOMER_ACCOUNT_ID = ART.CUSTOMER_ACCOUNT_ID
INNER JOIN FORM_WORKFLOW FW on FW.FORM_WORKFLOW_ID = ART.FORM_WORKFLOW_ID
INNER JOIN FORM_STATUS FS on FS.FORM_STATUS_ID = FW.CURRENT_STATUS_ID
WHERE FW.CURRENT_STATUS_ID != 4

UNION ALL

SELECT 'Other Receipt' AS SOURCE,
D.NAME AS DIVISION, D.DIVISION_ID AS DIVISION_ID,
	CONCAT('OR-', SS.SERVICE_SETTING_ID) AS ID,
	2 AS SOURCE_ID,
	AM.SEQUENCE_NO AS SEQ_NO,
	FW.CURRENT_STATUS_ID AS STATUS_ID,
	FS.DESCRIPTION AS STATUS,
	FW.IS_COMPLETE AS COMPLETE,
	ACA.COMPANY_ID AS COMPANY_ID,
	SS.NAME AS SERVICE,
	SS.SERVICE_SETTING_ID AS SERVICE_ID,
	COALESCE(AML.UNITOFMEASUREMENT_ID, 0) AS UOM_ID,
	AM.MATURITY_DATE MATURITY_DATE,
	AM.RECEIPT_DATE AS RECEIPT_DATE,
	AM.AR_CUSTOMER_ID AS CUSTOMER_ID,
	AM.AR_CUSTOMER_ACCOUNT_ID AS CUSTOMER_ACCT_ID,
	AM.CREATED_DATE REF_DATE,
	AM.RECEIPT_NUMBER AS REF_NUMBER,
	AC.NAME AS CUSTOMER,
	ACA.NAME AS CUSTOMER_ACCT,
	COALESCE(AML.QUANTITY, 0) AS QUANTITY,
	COALESCE(AML.UP_AMOUNT, 0) AS UNIT_PRICE,
	AML.AMOUNT AS AMOUNT,
	0 AS VAT_AMOUNT FROM SERVICE_SETTING SS
INNER JOIN AR_MISCELLANEOUS_LINE AML ON AML.SERVICE_SETTING_ID = SS.SERVICE_SETTING_ID
INNER JOIN AR_MISCELLANEOUS AM ON AM.AR_MISCELLANEOUS_ID = AML.AR_MISCELLANEOUS_ID
INNER JOIN DIVISION D ON D.DIVISION_ID= AM.DIVISION_ID
INNER JOIN AR_CUSTOMER AC on AC.AR_CUSTOMER_ID = AM.AR_CUSTOMER_ID
INNER JOIN AR_CUSTOMER_ACCOUNT ACA on ACA.AR_CUSTOMER_ACCOUNT_ID = AM.AR_CUSTOMER_ACCOUNT_ID
INNER JOIN FORM_WORKFLOW FW on FW.FORM_WORKFLOW_ID = AM.FORM_WORKFLOW_ID
INNER JOIN FORM_STATUS FS on FS.FORM_STATUS_ID = FW.CURRENT_STATUS_ID
WHERE FW.CURRENT_STATUS_ID != 4

UNION ALL

SELECT 'AR Invoice' AS SOURCE,
D.NAME AS DIVISION, D.DIVISION_ID AS DIVISION_ID,
	CONCAT('ARI-', SS.SERVICE_SETTING_ID) AS ID,
	23 AS SOURCE_ID,
	ARI.SEQUENCE_NO AS SEQ_NO,
	FW.CURRENT_STATUS_ID AS STATUS_ID,
	FS.DESCRIPTION AS STATUS,
	FW.IS_COMPLETE AS COMPLETE,
	ACA.COMPANY_ID AS COMPANY_ID,
	SS.NAME AS SERVICE,
	SS.SERVICE_SETTING_ID AS SERVICE_ID,
	COALESCE(ARL.UNITOFMEASUREMENT_ID, 0) AS UOM_ID,
	ARI.DATE AS MATURITY_DATE,
	ARI.DATE AS RECEIPT_DATE,
	ARI.AR_CUSTOMER_ID AS CUSTOMER_ID,
	ARI.AR_CUSTOMER_ACCOUNT_ID AS CUSTOMER_ACCT_ID,
	ARI.DATE AS REF_DATE,
	ARI.SEQUENCE_NO AS REF_NUMBER,
	AC.NAME AS CUSTOMER,
	ACA.NAME AS CUSTOMER_ACCT,
	COALESCE(ARL.QUANTITY, 0) AS QUANTITY,
	COALESCE(ARL.UP_AMOUNT, 0) AS UNIT_PRICE,
	ARL.AMOUNT AS AMOUNT,
	0 AS VAT_AMOUNT FROM SERVICE_SETTING SS
INNER JOIN AR_INVOICE_LINE ARL ON ARL.SERVICE_SETTING_ID = SS.SERVICE_SETTING_ID
INNER JOIN AR_INVOICE ARI ON ARI.AR_INVOICE_ID = ARL.AR_INVOICE_ID
INNER JOIN DIVISION D ON D.DIVISION_ID= ARI.DIVISION_ID
INNER JOIN AR_CUSTOMER AC on AC.AR_CUSTOMER_ID = ARI.AR_CUSTOMER_ID
INNER JOIN AR_CUSTOMER_ACCOUNT ACA on ACA.AR_CUSTOMER_ACCOUNT_ID = ARI.AR_CUSTOMER_ACCOUNT_ID
INNER JOIN FORM_WORKFLOW FW on FW.FORM_WORKFLOW_ID = ARI.FORM_WORKFLOW_ID
INNER JOIN FORM_STATUS FS on FS.FORM_STATUS_ID = FW.CURRENT_STATUS_ID
WHERE FW.CURRENT_STATUS_ID != 4
ORDER BY REF_DATE, REF_NUMBER, CUSTOMER, CUSTOMER_ACCT