-- Description: mysql views for AR Receipt Register.


drop view if exists V_AR_RECEIPT_REGISTER;

create view V_AR_RECEIPT_REGISTER as
	select 'Account Collection' as SOURCE,
	concat('AC ', ARR.AR_RECEIPT_ID) as ID, 
	1 as SOURCE_ID,
	COALESCE(CONCAT(C.COMPANY_CODE, ' ', ARR.SEQUENCE_NO), ARR.SEQUENCE_NO) as SEQ_NO,
	ARR.COMPANY_ID as COMPANY_ID, 
	ARR.AR_RECEIPT_TYPE_ID as RECEIPT_TYPE_ID, 
	ARR.RECEIPT_METHOD_ID as RECEIPT_METHOD_ID, 
	ARR.AR_CUSTOMER_ID as CUSTOMER_ID, 
	ARR.AR_CUSTOMER_ACCOUNT_ID as CUSTOMER_ACCT_ID,
	D.DIVISION_ID AS DIVISION_ID,
	D.NAME AS DIVISION,
	FW.CURRENT_STATUS_ID as STATUS_ID,
	RT.NAME as RECEIPT_TYPE,
	ARR.RECEIPT_DATE as RECEIPT_DATE,
	ARR.MATURITY_DATE as MATURITY_DATE,
	ARR.RECEIPT_NUMBER as RECEIPT_NO,
	IF (ARR.AR_RECEIPT_TYPE_ID = 1, 'N/A', ARR.REF_NUMBER) as CHECK_NO,
	AC.NAME as CUSTOMER,
	ACA.NAME as CUSTOMER_ACCT,
	RM.NAME as RECEIPT_METHOD,
	IF (FW.CURRENT_STATUS_ID = 4, 0.0, ARR.AMOUNT) as AMOUNT, 
	COALESCE((select sum(AMOUNT) from AR_RECEIPT_TRANSACTION ARRT 
	where ARRT.AR_RECEIPT_ID = ARR.AR_RECEIPT_ID), 0) as PAID_AMOUNT, 0.0 as BALANCE,
	IF (FW.CURRENT_STATUS_ID =4, (SELECT FWL.COMMENT FROM FORM_WORKFLOW_LOG FWL
    WHERE FWL.FORM_WORKFLOW_ID = FW.FORM_WORKFLOW_ID AND FWL.FORM_STATUS_ID = 4), '') AS CANCELLATION_REMARKS ,
	FS.DESCRIPTION as STATUS from AR_RECEIPT ARR
inner join COMPANY C on C.COMPANY_ID = ARR.COMPANY_ID
inner join AR_RECEIPT_TYPE RT on RT.AR_RECEIPT_TYPE_ID = ARR.AR_RECEIPT_TYPE_ID
inner join AR_CUSTOMER AC on AC.AR_CUSTOMER_ID = ARR.AR_CUSTOMER_ID
inner join AR_CUSTOMER_ACCOUNT ACA on ACA.AR_CUSTOMER_ACCOUNT_ID = ARR.AR_CUSTOMER_ACCOUNT_ID
inner join RECEIPT_METHOD RM on RM.RECEIPT_METHOD_ID = ARR.RECEIPT_METHOD_ID
inner join FORM_WORKFLOW FW on FW.FORM_WORKFLOW_ID = ARR.FORM_WORKFLOW_ID
inner join FORM_STATUS FS on FW.CURRENT_STATUS_ID = FS.FORM_STATUS_ID
INNER JOIN DIVISION D ON D.DIVISION_ID = ARR.DIVISION_ID

union all

select 'Other Receipt' as SOURCE,
	concat('ARM ', ARM.AR_MISCELLANEOUS_ID) as ID, 
	2 as SOURCE_ID,
	COALESCE(CONCAT(C.COMPANY_CODE, ' ', ARM.SEQUENCE_NO), ARM.SEQUENCE_NO) as SEQ_NO,
	RM.COMPANY_ID as COMPANY_ID,
	ARM.AR_MISCELLANEOUS_TYPE_ID as RECEIPT_TYPE_ID, 
	ARM.RECEIPT_METHOD_ID as RECEIPT_METHOD_ID,
	ARM.AR_CUSTOMER_ID as CUSTOMER_ID, 
	ARM.AR_CUSTOMER_ACCOUNT_ID as CUSTOMER_ACCT_ID,
	D.DIVISION_ID AS DIVISION_ID,
	D.NAME AS DIVISION,
	FW.CURRENT_STATUS_ID as STATUS_ID,
	MT.NAME as RECEIPT_TYPE, ARM.RECEIPT_DATE as RECEIPT_DATE, 
	ARM.MATURITY_DATE as MATURITY_DATE, ARM.RECEIPT_NUMBER as RECEIPT_NO, 
	IF (ARM.AR_MISCELLANEOUS_TYPE_ID = 1, 'N/A', ARM.REF_NUMBER) as CHECK_NO,
	AC.NAME as CUSTOMER, ACA.NAME as CUSTOMER_ACCT, RM.NAME as RECEIPT_METHOD,
	IF (FW.CURRENT_STATUS_ID = 4, 0.0, ARM.AMOUNT) as AMOUNT, 0.0 as PAID_AMOUNT, 0.0 as BALANCE,
	IF (FW.CURRENT_STATUS_ID =4, (SELECT FWL.COMMENT FROM FORM_WORKFLOW_LOG FWL
	WHERE FWL.FORM_WORKFLOW_ID = FW.FORM_WORKFLOW_ID AND FWL.FORM_STATUS_ID = 4), '') AS CANCELLATION_REMARKS ,
	FS.DESCRIPTION as STATUS from AR_MISCELLANEOUS ARM
inner join AR_MISCELLANEOUS_TYPE MT on MT.AR_MISCELLANEOUS_TYPE_ID = ARM.AR_MISCELLANEOUS_TYPE_ID
inner join AR_CUSTOMER AC on AC.AR_CUSTOMER_ID = ARM.AR_CUSTOMER_ID
inner join AR_CUSTOMER_ACCOUNT ACA on ACA.AR_CUSTOMER_ACCOUNT_ID = ARM.AR_CUSTOMER_ACCOUNT_ID
inner join RECEIPT_METHOD RM on RM.RECEIPT_METHOD_ID = ARM.RECEIPT_METHOD_ID
inner join FORM_WORKFLOW FW on FW.FORM_WORKFLOW_ID = ARM.FORM_WORKFLOW_ID
inner join FORM_STATUS FS on FW.CURRENT_STATUS_ID = FS.FORM_STATUS_ID
inner join COMPANY C on RM.COMPANY_ID = C.COMPANY_ID
INNER JOIN DIVISION D ON D.DIVISION_ID = ARM.DIVISION_ID;