-- Description: mysql views for Customer account history


DROP VIEW IF EXISTS V_CUSTOMER_ACCT_HISTORY;

CREATE VIEW V_CUSTOMER_ACCT_HISTORY AS 

SELECT C.COMPANY_ID,
D.NAME AS DIVISION,
D.DIVISION_ID,
C.NAME AS COMPANY,
AT.DESCRIPTION,
AT.CUSTOMER_ACCOUNT_ID,
AT.CUSTOMER_ID,
CUR.NAME AS CURRENCY,
CUR.CURRENCY_ID AS CURRENCY_ID,
AT.CURRENCY_RATE_VALUE,
'AR Transaction' as SOURCE,
0 AS ADVANCE_PAYMENT,
AT.AR_TRANSACTION_ID as ID,
AT.TRANSACTION_DATE AS DATE,
AT.GL_DATE,
AT.TRANSACTION_NUMBER AS REFERENCE_NUMBER,
CONCAT('ART-', AT.SEQUENCE_NO) as AR_OR_REF_NO,
'' AS PO_PCR_NO,
AT.AMOUNT as TRANSACTION_AMOUNT,
0 as RECEIPT_AMOUNT,
0 AS GAIN_LOSS,
AT.CREATED_DATE,
NULL AS AR_LINE_ID,
F.CURRENT_STATUS_ID as STATUS_ID,
F.IS_COMPLETE,
T.TERM_ID,
T.DAYS as TERM_DAYS,
FS.DESCRIPTION AS STATUS
FROM AR_TRANSACTION AT
INNER JOIN AR_CUSTOMER_ACCOUNT ACA ON ACA.AR_CUSTOMER_ACCOUNT_ID = AT.CUSTOMER_ACCOUNT_ID
INNER JOIN COMPANY C ON C.COMPANY_ID=AT.COMPANY_ID
INNER JOIN DIVISION D ON D.DIVISION_ID=AT.DIVISION_ID
INNER JOIN CURRENCY CUR ON CUR.CURRENCY_ID = AT.CURRENCY_ID
INNER JOIN TERM T ON ACA.TERM_ID = T.TERM_ID
INNER JOIN FORM_WORKFLOW F ON AT.FORM_WORKFLOW_ID = F.FORM_WORKFLOW_ID
INNER JOIN FORM_STATUS FS ON FS.FORM_STATUS_ID = F.CURRENT_STATUS_ID
WHERE F.IS_COMPLETE = 1
AND AT.AR_TRANSACTION_TYPE_ID IN (17, 18, 19, 20, 21, 22)

UNION ALL

SELECT C.COMPANY_ID,
D.NAME AS DIVISION,
D.DIVISION_ID,
C.NAME AS COMPANY,
'' AS DESCRIPTION,
ARI.AR_CUSTOMER_ACCOUNT_ID AS CUSTOMER_ACCOUNT_ID,
ARI.AR_CUSTOMER_ID AS CUSTOMER_ID,
CUR.NAME AS CURRENCY,
CUR.CURRENCY_ID AS CURRENCY_ID,
ARI.CURRENCY_RATE_VALUE,
'AR Invoice' as SOURCE,
0 AS ADVANCE_PAYMENT,
ARI.AR_INVOICE_ID as ID,
ARI.DATE,
ARI.DATE_RECEIVED AS GL_DATE,
CONCAT('DR-', DR.SEQUENCE_NO) AS REFERENCE_NUMBER,
CONCAT('ARI -', ARI.SEQUENCE_NO) as AR_OR_REF_NO,
DR.PO_NUMBER AS PO_PCR_NO,
ARI.AMOUNT + COALESCE(ARI.RECOUPMENT, 0) + COALESCE(ARI.RETENTION, 0) as TRANSACTION_AMOUNT,
0 as RECEIPT_AMOUNT,
0 AS GAIN_LOSS,
ARI.CREATED_DATE,
NULL AS AR_LINE_ID,
F.CURRENT_STATUS_ID as STATUS_ID,
F.IS_COMPLETE,
T.TERM_ID,
T.DAYS as TERM_DAYS,
FS.DESCRIPTION AS STATUS
FROM AR_INVOICE ARI
INNER JOIN AR_CUSTOMER_ACCOUNT ACA ON ACA.AR_CUSTOMER_ACCOUNT_ID = ARI.AR_CUSTOMER_ACCOUNT_ID
INNER JOIN DELIVERY_RECEIPT DR ON FIND_IN_SET(DR.DELIVERY_RECEIPT_ID, (REPLACE(ARI.DR_REFERENCE_IDS, ' ', '')))
INNER JOIN COMPANY C ON C.COMPANY_ID=ARI.COMPANY_ID
INNER JOIN DIVISION D ON D.DIVISION_ID=ARI.DIVISION_ID
INNER JOIN CURRENCY CUR ON CUR.CURRENCY_ID = ARI.CURRENCY_ID
INNER JOIN TERM T ON ACA.TERM_ID = T.TERM_ID
INNER JOIN FORM_WORKFLOW F ON ARI.FORM_WORKFLOW_ID = F.FORM_WORKFLOW_ID
INNER JOIN FORM_STATUS FS ON FS.FORM_STATUS_ID = F.CURRENT_STATUS_ID
WHERE F.IS_COMPLETE = 1

UNION ALL

SELECT C.COMPANY_ID,
D.NAME AS DIVISION,
D.DIVISION_ID,
C.NAME AS COMPANY,
COALESCE((
SELECT TRIM(GROUP_CONCAT(DISTINCT ' ', REF_NO)) FROM (
SELECT ARL.AR_RECEIPT_ID, CONCAT('ARI-', ARI.SEQUENCE_NO) AS REF_NO
FROM AR_RECEIPT_LINE ARL
INNER JOIN OBJECT_TO_OBJECT O2O ON O2O.TO_OBJECT_ID = ARL.EB_OBJECT_ID 
INNER JOIN AR_INVOICE ARI ON ARI.EB_OBJECT_ID = O2O.FROM_OBJECT_ID 
WHERE ARL.AR_RECEIPT_LINE_TYPE_ID = 1
UNION ALL 
SELECT ARL.AR_RECEIPT_ID, CONCAT('ART-', ART.SEQUENCE_NO) AS REF_NO
FROM AR_RECEIPT_LINE ARL
INNER JOIN OBJECT_TO_OBJECT O2O ON O2O.TO_OBJECT_ID = ARL.EB_OBJECT_ID 
INNER JOIN AR_TRANSACTION ART ON ART.EB_OBJECT_ID = O2O.FROM_OBJECT_ID 
WHERE ARL.AR_RECEIPT_LINE_TYPE_ID = 2
UNION ALL 
SELECT ARL.AR_RECEIPT_ID, CONCAT('CAP-', CAP.CAP_NUMBER) AS REF_NO
FROM AR_RECEIPT_LINE ARL
INNER JOIN OBJECT_TO_OBJECT O2O ON O2O.TO_OBJECT_ID = ARL.EB_OBJECT_ID 
INNER JOIN CUSTOMER_ADVANCE_PAYMENT CAP ON CAP.EB_OBJECT_ID = O2O.FROM_OBJECT_ID 
WHERE ARL.AR_RECEIPT_LINE_TYPE_ID = 3
UNION ALL 
SELECT ARL.AR_RECEIPT_ID, CONCAT('RET-', PR.SEQUENCE_NO) AS REF_NO
FROM AR_RECEIPT_LINE ARL
INNER JOIN OBJECT_TO_OBJECT O2O ON O2O.TO_OBJECT_ID = ARL.EB_OBJECT_ID 
INNER JOIN PROJECT_RETENTION PR ON PR.EB_OBJECT_ID = O2O.FROM_OBJECT_ID 
WHERE ARL.AR_RECEIPT_LINE_TYPE_ID = 4) AS TBL
WHERE AR_RECEIPT_ID = AR.AR_RECEIPT_ID), '') AS DESCRIPTION,
AR.AR_CUSTOMER_ACCOUNT_ID AS CUSTOMER_ACCOUNT_ID,
AR.AR_CUSTOMER_ID AS CUSTOMER_ID,
CUR.NAME AS CURRENCY,
CUR.CURRENCY_ID,
AR.CURRENCY_RATE_VALUE,
'Account Collection' AS SOURCE,
0 AS ADVANCE_PAYMENT,
AR.AR_RECEIPT_ID as ID,
AR.RECEIPT_DATE as DATE,
AR.MATURITY_DATE as GL_DATE,
AR.REF_NUMBER AS REFERENCE_NUMBER,
CONCAT('AC-', AR.SEQUENCE_NO, ', ', AR.RECEIPT_NUMBER) as AR_OR_REF_NO,
COALESCE((SELECT GROUP_CONCAT(DISTINCT ' ', DR.PO_NUMBER)
FROM AR_RECEIPT_LINE ARL
INNER JOIN OBJECT_TO_OBJECT O2O ON O2O.TO_OBJECT_ID = ARL.EB_OBJECT_ID 
INNER JOIN AR_INVOICE ARI ON ARI.EB_OBJECT_ID = O2O.FROM_OBJECT_ID
INNER JOIN DELIVERY_RECEIPT DR ON DR.DELIVERY_RECEIPT_ID = ARI.DELIVERY_RECEIPT_ID
WHERE ARL.AR_RECEIPT_LINE_TYPE_ID = 1
AND ARL.AR_RECEIPT_ID = AR.AR_RECEIPT_ID), '') AS PO_PCR_NO,
0 as TRANSACTION_AMOUNT,
(COALESCE((SELECT SUM(ARRL.AMOUNT) FROM AR_RECEIPT_LINE ARRL WHERE ARRL.AR_RECEIPT_ID = AR.AR_RECEIPT_ID), 0)) as RECEIPT_AMOUNT,
((AR.AMOUNT + COALESCE(AR.RECOUPMENT, 0) + COALESCE(AR.RETENTION, 0)) - COALESCE((SELECT SUM(AMOUNT) FROM (
SELECT AR_RECEIPT_ID, AMOUNT FROM AR_RECEIPT_LINE ARL) AS TBL WHERE AR_RECEIPT_ID = AR.AR_RECEIPT_ID), 0)) AS GAIN_LOSS,
AR.CREATED_DATE,
NULL AS AR_LINE_ID,
F.CURRENT_STATUS_ID,
F.IS_COMPLETE,
T.TERM_ID,
T.DAYS as TERM_DAYS,
FS.DESCRIPTION AS STATUS
FROM AR_RECEIPT AR
INNER JOIN FORM_WORKFLOW F ON AR.FORM_WORKFLOW_ID = F.FORM_WORKFLOW_ID
INNER JOIN FORM_STATUS FS ON FS.FORM_STATUS_ID = F.CURRENT_STATUS_ID
INNER JOIN AR_CUSTOMER_ACCOUNT ACA ON ACA.AR_CUSTOMER_ACCOUNT_ID = AR.AR_CUSTOMER_ACCOUNT_ID
INNER JOIN COMPANY C ON C.COMPANY_ID=AR.COMPANY_ID
INNER JOIN DIVISION D ON D.DIVISION_ID=AR.DIVISION_ID
INNER JOIN CURRENCY CUR ON CUR.CURRENCY_ID = AR.CURRENCY_ID
INNER JOIN TERM T ON ACA.TERM_ID = T.TERM_ID
WHERE F.CURRENT_STATUS_ID != 4;
