-- Description View for Delivery Receipt Register


DROP VIEW IF EXISTS V_DELIVERY_RECEIPT_REGISTER;

CREATE VIEW V_DELIVERY_RECEIPT_REGISTER AS

SELECT COM.COMPANY_ID,
D.DIVISION_ID AS DIVISION_ID,
D.NAME AS DIVISION,
SO.SEQUENCE_NO AS SO_NUMBER,
SO.PO_NUMBER AS PO_PCR_NUMBER,
SO.AMOUNT AS SO_AMOUNT,
C.NAME AS CUSTOMER,
DR.AR_CUSTOMER_ID AS CUSTOMER_ID,
CA.NAME AS CUSTOMER_ACCOUNT,
DR.AR_CUSTOMER_ACCOUNT_ID AS CUSTOMER_ACCT_ID,
TRM.NAME AS TERM,
DR.DATE AS DR_DATE,
DR.SEQUENCE_NO AS DR_NUMBER,
DR.DR_REF_NUMBER AS REF_NUMBER,
FS.DESCRIPTION AS DR_STATUS,
FW.CURRENT_STATUS_ID AS DR_STATUS_ID,
DR.REMARKS AS SHIP_TO,
DR.RECEIVER AS DR_RECEIVED_BY,
DR.DATE_RECEIVED AS DR_RECEIVED_DATE,
IF(FW.CURRENT_STATUS_ID = 4, (SELECT FWL.COMMENT FROM FORM_WORKFLOW_LOG FWL
	WHERE FWL.FORM_WORKFLOW_ID = FW.FORM_WORKFLOW_ID AND FWL.FORM_STATUS_ID = 4), '') AS CANCELLATION_REMARKS
FROM DELIVERY_RECEIPT DR
INNER JOIN DIVISION D ON D.DIVISION_ID = DR.DIVISION_ID
INNER JOIN COMPANY COM ON COM.COMPANY_ID = DR.COMPANY_ID
INNER JOIN SALES_ORDER SO ON SO.SALES_ORDER_ID = DR.SALES_ORDER_ID
INNER JOIN AR_CUSTOMER C ON DR.AR_CUSTOMER_ID = C.AR_CUSTOMER_ID
INNER JOIN AR_CUSTOMER_ACCOUNT CA ON DR.AR_CUSTOMER_ACCOUNT_ID = CA.AR_CUSTOMER_ACCOUNT_ID
INNER JOIN TERM TRM ON TRM.TERM_ID = DR.TERM_ID
INNER JOIN FORM_WORKFLOW FW ON FW.FORM_WORKFLOW_ID=DR.FORM_WORKFLOW_ID
INNER JOIN FORM_STATUS FS ON FS.FORM_STATUS_ID = FW.CURRENT_STATUS_ID
WHERE CA.ACTIVE = 1;