-- Description: mysql views that will show the history of all inventory transactions.


DROP VIEW IF EXISTS V_ITEM_HISTORY;

CREATE VIEW V_ITEM_HISTORY AS 
SELECT ITS.COMPANY_ID, API.AP_INVOICE_ID AS ID, RRI.R_RECEIVING_REPORT_ITEM_ID AS FI_ID, 'RR' AS FORM, API.GL_DATE AS DATE, FW.IS_COMPLETE AS IS_COMPLETE, FW.CURRENT_STATUS_ID AS FW_STATUS_ID, RR.WAREHOUSE_ID AS WAREHOUSE_ID, RRI.ITEM_ID AS ITEM_ID, I.STOCK_CODE AS STOCK_CODE,
	I.DESCRIPTION AS DESCRIPTION, I.ITEM_CATEGORY_ID AS CATEGORY_ID, I.ACTIVE AS STATUS_ID, RRI.QUANTITY AS QUANTITY, RRI.UNIT_COST AS UNIT_COST,
	UM.NAME AS UOM, ITS.SRP, API.CREATED_DATE, FWL.CREATED_DATE AS FWL_CD, (RRI.QUANTITY * RRI.UNIT_COST) AS AMOUNT FROM R_RECEIVING_REPORT_ITEM RRI
	INNER JOIN AP_INVOICE API ON RRI.AP_INVOICE_ID = API.AP_INVOICE_ID
	INNER JOIN R_RECEIVING_REPORT RR ON API.AP_INVOICE_ID = RR.AP_INVOICE_ID
	INNER JOIN FORM_WORKFLOW FW ON API.FORM_WORKFLOW_ID = FW.FORM_WORKFLOW_ID
	INNER JOIN FORM_WORKFLOW_LOG FWL ON (FWL.FORM_WORKFLOW_ID = FW.FORM_WORKFLOW_ID AND FW.CURRENT_STATUS_ID = FWL.FORM_STATUS_ID)
	INNER JOIN ITEM I ON RRI.ITEM_ID = I.ITEM_ID
	INNER JOIN ITEM_SRP ITS ON RRI.ITEM_ID = ITS.ITEM_ID
	INNER JOIN UNIT_MEASUREMENT UM ON I.UNIT_MEASUREMENT_ID = UM.UNITOFMEASUREMENT_ID
	WHERE ITS.COMPANY_ID = RR.COMPANY_ID AND ITS.ACTIVE = 1
	GROUP BY FW.FORM_WORKFLOW_ID, RRI.R_RECEIVING_REPORT_ITEM_ID
UNION ALL
SELECT TR.COMPANY_ID, TR.R_TRANSFER_RECEIPT_ID, TRI.R_TRANSFER_RECEIPT_ITEM_ID, 'TR-TO',TR.TR_DATE, FW.IS_COMPLETE, FW.CURRENT_STATUS_ID AS FW_STATUS_ID, TR.WAREHOUSE_TO_ID, TRI.ITEM_ID, I.STOCK_CODE, I.DESCRIPTION, I.ITEM_CATEGORY_ID, I.ACTIVE, TRI.QUANTITY, TRI.UNIT_COST,
	UM.NAME, ITS.SRP, TR.CREATED_DATE, FWL.CREATED_DATE AS FWL_CD, (TRI.QUANTITY * TRI.UNIT_COST) AS AMOUNT 
	FROM R_TRANSFER_RECEIPT_ITEM TRI
	INNER JOIN R_TRANSFER_RECEIPT TR ON TRI.R_TRANSFER_RECEIPT_ID = TR.R_TRANSFER_RECEIPT_ID
	INNER JOIN FORM_WORKFLOW FW ON TR.FORM_WORKFLOW_ID = FW.FORM_WORKFLOW_ID
	INNER JOIN FORM_WORKFLOW_LOG FWL ON (FWL.FORM_WORKFLOW_ID = FW.FORM_WORKFLOW_ID AND FW.CURRENT_STATUS_ID = FWL.FORM_STATUS_ID)
	INNER JOIN ITEM I ON TRI.ITEM_ID = I.ITEM_ID
	INNER JOIN ITEM_SRP ITS ON TRI.ITEM_ID = ITS.ITEM_ID
	INNER JOIN UNIT_MEASUREMENT UM ON I.UNIT_MEASUREMENT_ID = UM.UNITOFMEASUREMENT_ID
	WHERE TR.COMPANY_ID = ITS.COMPANY_ID AND ITS.ACTIVE = 1
	GROUP BY FW.FORM_WORKFLOW_ID, TRI.R_TRANSFER_RECEIPT_ITEM_ID
UNION ALL
SELECT RP.COMPANY_ID, RP.REPACKING_ID, RPI.REPACKING_ITEM_ID, 'RP-TO', RP.R_DATE, FW.IS_COMPLETE, FW.CURRENT_STATUS_ID AS FW_STATUS_ID, RP.WAREHOUSE_ID, RPI.TO_ITEM_ID, I.STOCK_CODE, I.DESCRIPTION, I.ITEM_CATEGORY_ID, I.ACTIVE, RPI.REPACKED_QUANTITY,
	RPI.REPACKED_UNIT_COST, UM.NAME, ITS.SRP, RP.CREATED_DATE AS FWL_CD, FWL.CREATED_DATE, (RPI.QUANTITY * RPI.UNIT_COST) AS AMOUNT 
	FROM REPACKING_ITEM RPI
	INNER JOIN REPACKING RP ON RP.REPACKING_ID = RPI.REPACKING_ID
	INNER JOIN FORM_WORKFLOW FW ON RP.FORM_WORKFLOW_ID = FW.FORM_WORKFLOW_ID
	INNER JOIN FORM_WORKFLOW_LOG FWL ON (FWL.FORM_WORKFLOW_ID = FW.FORM_WORKFLOW_ID AND FW.CURRENT_STATUS_ID = FWL.FORM_STATUS_ID)
	INNER JOIN ITEM I ON RPI.TO_ITEM_ID = I.ITEM_ID
	INNER JOIN ITEM_SRP ITS ON RPI.TO_ITEM_ID = ITS.ITEM_ID
	INNER JOIN UNIT_MEASUREMENT UM ON I.UNIT_MEASUREMENT_ID = UM.UNITOFMEASUREMENT_ID
	WHERE RP.COMPANY_ID = ITS.COMPANY_ID AND ITS.ACTIVE = 1
	GROUP BY FW.FORM_WORKFLOW_ID, RPI.REPACKING_ITEM_ID
UNION ALL
SELECT ITS.COMPANY_ID, ART.AR_TRANSACTION_ID, ASI.ACCOUNT_SALE_ITEM_ID, 'ASR', ART.TRANSACTION_DATE, FW.IS_COMPLETE, FW.CURRENT_STATUS_ID AS FW_STATUS_ID, ASI.WAREHOUSE_ID, ASI.ITEM_ID, I.STOCK_CODE, I.DESCRIPTION, I.ITEM_CATEGORY_ID, I.ACTIVE, -ASI.QUANTITY,
	ASI.UNIT_COST, UM.NAME, ITS.SRP, ART.CREATED_DATE, FWL.CREATED_DATE AS FWL_CD, -(ASI.QUANTITY * ASI.UNIT_COST) AS AMOUNT 
	FROM ACCOUNT_SALE_ITEM ASI
	INNER JOIN AR_TRANSACTION ART ON ASI.AR_TRANSACTION_ID = ART.AR_TRANSACTION_ID
	INNER JOIN FORM_WORKFLOW FW ON ART.FORM_WORKFLOW_ID = FW.FORM_WORKFLOW_ID
	INNER JOIN FORM_WORKFLOW_LOG FWL ON (FWL.FORM_WORKFLOW_ID = FW.FORM_WORKFLOW_ID AND FW.CURRENT_STATUS_ID = FWL.FORM_STATUS_ID)
	INNER JOIN ITEM I ON ASI.ITEM_ID = I.ITEM_ID
	INNER JOIN ITEM_SRP ITS ON ASI.ITEM_ID = ITS.ITEM_ID
	INNER JOIN UNIT_MEASUREMENT UM ON I.UNIT_MEASUREMENT_ID = UM.UNITOFMEASUREMENT_ID
	WHERE ART.AR_TRANSACTION_TYPE_ID = 5 AND ART.COMPANY_ID = ITS.COMPANY_ID AND ITS.ACTIVE = 1
	GROUP BY FW.FORM_WORKFLOW_ID, ASI.ACCOUNT_SALE_ITEM_ID
UNION ALL
SELECT ITS.COMPANY_ID, ART.AR_TRANSACTION_ID, ASI.ACCOUNT_SALE_ITEM_ID, 'ASR-W', ART.TRANSACTION_DATE, FW.IS_COMPLETE, FW.CURRENT_STATUS_ID AS FW_STATUS_ID, ASI.WAREHOUSE_ID, ASI.ITEM_ID, I.STOCK_CODE, I.DESCRIPTION, I.ITEM_CATEGORY_ID, I.ACTIVE, -ASI.QUANTITY,
	ASI.UNIT_COST, UM.NAME, ITS.SRP, ART.CREATED_DATE, FWL.CREATED_DATE AS FWL_CD, -(ASI.QUANTITY * ASI.UNIT_COST) AS AMOUNT 
	FROM ACCOUNT_SALE_ITEM ASI
	INNER JOIN AR_TRANSACTION ART ON ASI.AR_TRANSACTION_ID = ART.AR_TRANSACTION_ID
	INNER JOIN FORM_WORKFLOW FW ON ART.FORM_WORKFLOW_ID = FW.FORM_WORKFLOW_ID
	INNER JOIN FORM_WORKFLOW_LOG FWL ON (FWL.FORM_WORKFLOW_ID = FW.FORM_WORKFLOW_ID AND FW.CURRENT_STATUS_ID = FWL.FORM_STATUS_ID)
	INNER JOIN ITEM I ON ASI.ITEM_ID = I.ITEM_ID
	INNER JOIN ITEM_SRP ITS ON ASI.ITEM_ID = ITS.ITEM_ID
	INNER JOIN UNIT_MEASUREMENT UM ON I.UNIT_MEASUREMENT_ID = UM.UNITOFMEASUREMENT_ID
	WHERE ART.AR_TRANSACTION_TYPE_ID = 9 AND ART.COMPANY_ID = ITS.COMPANY_ID AND ITS.ACTIVE = 1
	GROUP BY FW.FORM_WORKFLOW_ID, ASI.ACCOUNT_SALE_ITEM_ID
UNION ALL
SELECT ITS.COMPANY_ID, ART.AR_TRANSACTION_ID, ASI.ACCOUNT_SALE_ITEM_ID, 'ASR-EB', ART.TRANSACTION_DATE, FW.IS_COMPLETE, FW.CURRENT_STATUS_ID AS FW_STATUS_ID, ASI.WAREHOUSE_ID, ASI.ITEM_ID, I.STOCK_CODE, I.DESCRIPTION, I.ITEM_CATEGORY_ID, I.ACTIVE, ASI.QUANTITY,
	ASI.UNIT_COST, UM.NAME, ITS.SRP, ART.CREATED_DATE, FWL.CREATED_DATE AS FWL_CD, (ASI.QUANTITY * ASI.UNIT_COST) AS AMOUNT 
	FROM ACCOUNT_SALE_ITEM ASI
	INNER JOIN AR_TRANSACTION ART ON ASI.AR_TRANSACTION_ID = ART.AR_TRANSACTION_ID
	INNER JOIN FORM_WORKFLOW FW ON ART.FORM_WORKFLOW_ID = FW.FORM_WORKFLOW_ID
	INNER JOIN FORM_WORKFLOW_LOG FWL ON (FWL.FORM_WORKFLOW_ID = FW.FORM_WORKFLOW_ID AND FW.CURRENT_STATUS_ID = FWL.FORM_STATUS_ID)
	INNER JOIN ITEM I ON ASI.ITEM_ID = I.ITEM_ID
	INNER JOIN ITEM_SRP ITS ON ASI.ITEM_ID = ITS.ITEM_ID
	INNER JOIN UNIT_MEASUREMENT UM ON I.UNIT_MEASUREMENT_ID = UM.UNITOFMEASUREMENT_ID
	WHERE ART.AR_TRANSACTION_TYPE_ID = 7 AND ART.COMPANY_ID = ITS.COMPANY_ID AND ITS.ACTIVE = 1
	GROUP BY FW.FORM_WORKFLOW_ID, ASI.ACCOUNT_SALE_ITEM_ID
UNION ALL
SELECT ITS.COMPANY_ID, ART.AR_TRANSACTION_ID, ASI.ACCOUNT_SALE_ITEM_ID, 'ASR-IS', ART.TRANSACTION_DATE, FW.IS_COMPLETE, FW.CURRENT_STATUS_ID AS FW_STATUS_ID, ASI.WAREHOUSE_ID, ASI.ITEM_ID, I.STOCK_CODE, I.DESCRIPTION, I.ITEM_CATEGORY_ID, I.ACTIVE, -ASI.QUANTITY,
	ASI.UNIT_COST, UM.NAME, ITS.SRP, ART.CREATED_DATE, FWL.CREATED_DATE AS FWL_CD, -(ASI.QUANTITY * ASI.UNIT_COST) AS AMOUNT 
	FROM ACCOUNT_SALE_ITEM ASI
	INNER JOIN AR_TRANSACTION ART ON ASI.AR_TRANSACTION_ID = ART.AR_TRANSACTION_ID
	INNER JOIN FORM_WORKFLOW FW ON ART.FORM_WORKFLOW_ID = FW.FORM_WORKFLOW_ID
	INNER JOIN FORM_WORKFLOW_LOG FWL ON (FWL.FORM_WORKFLOW_ID = FW.FORM_WORKFLOW_ID AND FW.CURRENT_STATUS_ID = FWL.FORM_STATUS_ID)
	INNER JOIN ITEM I ON ASI.ITEM_ID = I.ITEM_ID
	INNER JOIN ITEM_SRP ITS ON ASI.ITEM_ID = ITS.ITEM_ID
	INNER JOIN UNIT_MEASUREMENT UM ON I.UNIT_MEASUREMENT_ID = UM.UNITOFMEASUREMENT_ID
	WHERE ART.AR_TRANSACTION_TYPE_ID = 11 AND ART.COMPANY_ID = ITS.COMPANY_ID AND ITS.ACTIVE = 1
	GROUP BY FW.FORM_WORKFLOW_ID, ASI.ACCOUNT_SALE_ITEM_ID
UNION ALL
SELECT ITS.COMPANY_ID, CSR.CASH_SALE_RETURN_ID, CSRI.CASH_SALE_RETURN_ITEM_ID, 'CSR', CSR.DATE, FW.IS_COMPLETE, FW.CURRENT_STATUS_ID AS FW_STATUS_ID, CSRI.WAREHOUSE_ID, CSRI.ITEM_ID, I.STOCK_CODE, I.DESCRIPTION, I.ITEM_CATEGORY_ID, I.ACTIVE, -CSRI.QUANTITY,
	CSRI.UNIT_COST, UM.NAME, ITS.SRP, CSR.CREATED_DATE, FWL.CREATED_DATE AS FWL_CD, -(CSRI.QUANTITY * CSRI.UNIT_COST) AS AMOUNT 
	FROM CASH_SALE_RETURN_ITEM CSRI
	INNER JOIN CASH_SALE_RETURN CSR ON CSRI.CASH_SALE_RETURN_ID = CSR.CASH_SALE_RETURN_ID
	INNER JOIN FORM_WORKFLOW FW ON CSR.FORM_WORKFLOW_ID = FW.FORM_WORKFLOW_ID
	INNER JOIN FORM_WORKFLOW_LOG FWL ON (FWL.FORM_WORKFLOW_ID = FW.FORM_WORKFLOW_ID AND FW.CURRENT_STATUS_ID = FWL.FORM_STATUS_ID)
	INNER JOIN ITEM I ON CSRI.ITEM_ID = I.ITEM_ID
	INNER JOIN ITEM_SRP ITS ON CSRI.ITEM_ID = ITS.ITEM_ID
	INNER JOIN UNIT_MEASUREMENT UM ON I.UNIT_MEASUREMENT_ID = UM.UNITOFMEASUREMENT_ID
	WHERE CSR.COMPANY_ID = ITS.COMPANY_ID AND ITS.ACTIVE = 1
	 AND CSR.CASH_SALE_TYPE_ID=1
	GROUP BY FW.FORM_WORKFLOW_ID, CSRI.CASH_SALE_RETURN_ITEM_ID
UNION ALL
SELECT ITS.COMPANY_ID, CSR.CASH_SALE_RETURN_ID, CSRI.CASH_SALE_RETURN_ITEM_ID, 'CSR-W', CSR.DATE, FW.IS_COMPLETE, FW.CURRENT_STATUS_ID AS FW_STATUS_ID, CSRI.WAREHOUSE_ID, CSRI.ITEM_ID, I.STOCK_CODE, I.DESCRIPTION, I.ITEM_CATEGORY_ID, I.ACTIVE, -CSRI.QUANTITY,
	CSRI.UNIT_COST, UM.NAME, ITS.SRP, CSR.CREATED_DATE, FWL.CREATED_DATE AS FWL_CD, -(CSRI.QUANTITY * CSRI.UNIT_COST) AS AMOUNT 
	FROM CASH_SALE_RETURN_ITEM CSRI
	INNER JOIN CASH_SALE_RETURN CSR ON CSRI.CASH_SALE_RETURN_ID = CSR.CASH_SALE_RETURN_ID
	INNER JOIN FORM_WORKFLOW FW ON CSR.FORM_WORKFLOW_ID = FW.FORM_WORKFLOW_ID
	INNER JOIN FORM_WORKFLOW_LOG FWL ON (FWL.FORM_WORKFLOW_ID = FW.FORM_WORKFLOW_ID AND FW.CURRENT_STATUS_ID = FWL.FORM_STATUS_ID)
	INNER JOIN ITEM I ON CSRI.ITEM_ID = I.ITEM_ID
	INNER JOIN ITEM_SRP ITS ON CSRI.ITEM_ID = ITS.ITEM_ID
	INNER JOIN UNIT_MEASUREMENT UM ON I.UNIT_MEASUREMENT_ID = UM.UNITOFMEASUREMENT_ID
	WHERE CSR.COMPANY_ID = ITS.COMPANY_ID AND ITS.ACTIVE = 1
	 AND CSR.CASH_SALE_TYPE_ID=2
	GROUP BY FW.FORM_WORKFLOW_ID, CSRI.CASH_SALE_RETURN_ITEM_ID
UNION ALL
SELECT ITS.COMPANY_ID, CSR.CASH_SALE_RETURN_ID, CSRI.CASH_SALE_RETURN_ITEM_ID, 'CSR-IS', CSR.DATE, FW.IS_COMPLETE, FW.CURRENT_STATUS_ID AS FW_STATUS_ID, CSRI.WAREHOUSE_ID, CSRI.ITEM_ID, I.STOCK_CODE, I.DESCRIPTION, I.ITEM_CATEGORY_ID, I.ACTIVE, -CSRI.QUANTITY,
	CSRI.UNIT_COST, UM.NAME, ITS.SRP, CSR.CREATED_DATE, FWL.CREATED_DATE AS FWL_CD, -(CSRI.QUANTITY * CSRI.UNIT_COST) AS AMOUNT 
	FROM CASH_SALE_RETURN_ITEM CSRI
	INNER JOIN CASH_SALE_RETURN CSR ON CSRI.CASH_SALE_RETURN_ID = CSR.CASH_SALE_RETURN_ID
	INNER JOIN FORM_WORKFLOW FW ON CSR.FORM_WORKFLOW_ID = FW.FORM_WORKFLOW_ID
	INNER JOIN FORM_WORKFLOW_LOG FWL ON (FWL.FORM_WORKFLOW_ID = FW.FORM_WORKFLOW_ID AND FW.CURRENT_STATUS_ID = FWL.FORM_STATUS_ID)
	INNER JOIN ITEM I ON CSRI.ITEM_ID = I.ITEM_ID
	INNER JOIN ITEM_SRP ITS ON CSRI.ITEM_ID = ITS.ITEM_ID
	INNER JOIN UNIT_MEASUREMENT UM ON I.UNIT_MEASUREMENT_ID = UM.UNITOFMEASUREMENT_ID
	WHERE CSR.COMPANY_ID = ITS.COMPANY_ID AND ITS.ACTIVE = 1
	 AND CSR.CASH_SALE_TYPE_ID=3
	GROUP BY FW.FORM_WORKFLOW_ID, CSRI.CASH_SALE_RETURN_ITEM_ID
UNION ALL
SELECT ITS.COMPANY_ID, CS.CASH_SALE_ID, CSI.CASH_SALE_ITEM_ID, 'CS', CS.RECEIPT_DATE, FW.IS_COMPLETE, FW.CURRENT_STATUS_ID AS FW_STATUS_ID, CSI.WAREHOUSE_ID, CSI.ITEM_ID, I.STOCK_CODE, I.DESCRIPTION, I.ITEM_CATEGORY_ID, I.ACTIVE, -CSI.QUANTITY,
	CSI.UNIT_COST, UM.NAME, ITS.SRP, CS.CREATED_DATE, FWL.CREATED_DATE AS FWL_CD, -(CSI.QUANTITY * CSI.UNIT_COST) AS AMOUNT 
	FROM CASH_SALE_ITEM CSI
	INNER JOIN CASH_SALE CS ON CSI.CASH_SALE_ID = CS.CASH_SALE_ID
	INNER JOIN FORM_WORKFLOW FW ON CS.FORM_WORKFLOW_ID = FW.FORM_WORKFLOW_ID
	INNER JOIN FORM_WORKFLOW_LOG FWL ON (FWL.FORM_WORKFLOW_ID = FW.FORM_WORKFLOW_ID AND FW.CURRENT_STATUS_ID = FWL.FORM_STATUS_ID)
	INNER JOIN ITEM I ON CSI.ITEM_ID = I.ITEM_ID
	INNER JOIN ITEM_SRP ITS ON CSI.ITEM_ID = ITS.ITEM_ID
	INNER JOIN UNIT_MEASUREMENT UM ON I.UNIT_MEASUREMENT_ID = UM.UNITOFMEASUREMENT_ID
	WHERE CS.COMPANY_ID = ITS.COMPANY_ID AND ITS.ACTIVE = 1
	 AND CS.CASH_SALE_TYPE_ID=1
	GROUP BY FW.FORM_WORKFLOW_ID, CSI.CASH_SALE_ITEM_ID
UNION ALL
SELECT ITS.COMPANY_ID, CS.CASH_SALE_ID, CSI.CASH_SALE_ITEM_ID, 'CS-W', CS.RECEIPT_DATE, FW.IS_COMPLETE, FW.CURRENT_STATUS_ID AS FW_STATUS_ID, CSI.WAREHOUSE_ID, CSI.ITEM_ID, I.STOCK_CODE, I.DESCRIPTION, I.ITEM_CATEGORY_ID, I.ACTIVE, -CSI.QUANTITY,
	CSI.UNIT_COST, UM.NAME, ITS.SRP, CS.CREATED_DATE, FWL.CREATED_DATE AS FWL_CD, -(CSI.QUANTITY * CSI.UNIT_COST) AS AMOUNT 
	FROM CASH_SALE_ITEM CSI
	INNER JOIN CASH_SALE CS ON CSI.CASH_SALE_ID = CS.CASH_SALE_ID
	INNER JOIN FORM_WORKFLOW FW ON CS.FORM_WORKFLOW_ID = FW.FORM_WORKFLOW_ID
	INNER JOIN FORM_WORKFLOW_LOG FWL ON (FWL.FORM_WORKFLOW_ID = FW.FORM_WORKFLOW_ID AND FW.CURRENT_STATUS_ID = FWL.FORM_STATUS_ID)
	INNER JOIN ITEM I ON CSI.ITEM_ID = I.ITEM_ID
	INNER JOIN ITEM_SRP ITS ON CSI.ITEM_ID = ITS.ITEM_ID
	INNER JOIN UNIT_MEASUREMENT UM ON I.UNIT_MEASUREMENT_ID = UM.UNITOFMEASUREMENT_ID
	WHERE CS.COMPANY_ID = ITS.COMPANY_ID AND ITS.ACTIVE = 1
	 AND CS.CASH_SALE_TYPE_ID=2
	GROUP BY FW.FORM_WORKFLOW_ID, CSI.CASH_SALE_ITEM_ID
UNION ALL
SELECT ITS.COMPANY_ID, CS.CASH_SALE_ID, CSI.CASH_SALE_ITEM_ID, 'CS-IS', CS.RECEIPT_DATE, FW.IS_COMPLETE, FW.CURRENT_STATUS_ID AS FW_STATUS_ID, CSI.WAREHOUSE_ID, CSI.ITEM_ID, I.STOCK_CODE, I.DESCRIPTION, I.ITEM_CATEGORY_ID, I.ACTIVE, -CSI.QUANTITY,
	CSI.UNIT_COST, UM.NAME, ITS.SRP, CS.CREATED_DATE, FWL.CREATED_DATE AS FWL_CD, -(CSI.QUANTITY * CSI.UNIT_COST) AS AMOUNT 
	FROM CASH_SALE_ITEM CSI
	INNER JOIN CASH_SALE CS ON CSI.CASH_SALE_ID = CS.CASH_SALE_ID
	INNER JOIN FORM_WORKFLOW FW ON CS.FORM_WORKFLOW_ID = FW.FORM_WORKFLOW_ID
	INNER JOIN FORM_WORKFLOW_LOG FWL ON (FWL.FORM_WORKFLOW_ID = FW.FORM_WORKFLOW_ID AND FW.CURRENT_STATUS_ID = FWL.FORM_STATUS_ID)
	INNER JOIN ITEM I ON CSI.ITEM_ID = I.ITEM_ID
	INNER JOIN ITEM_SRP ITS ON CSI.ITEM_ID = ITS.ITEM_ID
	INNER JOIN UNIT_MEASUREMENT UM ON I.UNIT_MEASUREMENT_ID = UM.UNITOFMEASUREMENT_ID
	WHERE CS.COMPANY_ID = ITS.COMPANY_ID AND ITS.ACTIVE = 1
	 AND CS.CASH_SALE_TYPE_ID=3
	GROUP BY FW.FORM_WORKFLOW_ID, CSI.CASH_SALE_ITEM_ID
UNION ALL
SELECT ITS.COMPANY_ID, API.AP_INVOICE_ID AS ID, RTSI.R_RETURN_TO_SUPPLIER_ITEM_ID, 'RTS', API.GL_DATE, FW.IS_COMPLETE, FW.CURRENT_STATUS_ID AS FW_STATUS_ID, RTS.WAREHOUSE_ID, RTSI.ITEM_ID, I.STOCK_CODE, I.DESCRIPTION, I.ITEM_CATEGORY_ID, I.ACTIVE,
	-RTSI.QUANTITY, RTSI.UNIT_COST, UM.NAME, ITS.SRP, API.CREATED_DATE, FWL.CREATED_DATE AS FWL_CD, -(RTSI.QUANTITY * RTSI.UNIT_COST) AS AMOUNT 
	FROM R_RETURN_TO_SUPPLIER_ITEM RTSI
	INNER JOIN AP_INVOICE API ON RTSI.AP_INVOICE_ID = API.AP_INVOICE_ID
	INNER JOIN R_RETURN_TO_SUPPLIER RTS ON API.AP_INVOICE_ID = RTS.AP_INVOICE_ID
	INNER JOIN FORM_WORKFLOW FW ON API.FORM_WORKFLOW_ID = FW.FORM_WORKFLOW_ID
	INNER JOIN FORM_WORKFLOW_LOG FWL ON (FWL.FORM_WORKFLOW_ID = FW.FORM_WORKFLOW_ID AND FW.CURRENT_STATUS_ID = FWL.FORM_STATUS_ID)
	INNER JOIN ITEM I ON RTSI.ITEM_ID = I.ITEM_ID
	INNER JOIN ITEM_SRP ITS ON RTSI.ITEM_ID = ITS.ITEM_ID
	INNER JOIN UNIT_MEASUREMENT UM ON I.UNIT_MEASUREMENT_ID = UM.UNITOFMEASUREMENT_ID
	WHERE RTS.COMPANY_ID = ITS.COMPANY_ID AND ITS.ACTIVE = 1
	GROUP BY FW.FORM_WORKFLOW_ID, RTSI.R_RETURN_TO_SUPPLIER_ITEM_ID
UNION ALL
SELECT ITS.COMPANY_ID, TR.R_TRANSFER_RECEIPT_ID, TRI.R_TRANSFER_RECEIPT_ITEM_ID, 'TR-FROM', TR.TR_DATE, FW.IS_COMPLETE, FW.CURRENT_STATUS_ID AS FW_STATUS_ID, TR.WAREHOUSE_FROM_ID, TRI.ITEM_ID, I.STOCK_CODE, I.DESCRIPTION, I.ITEM_CATEGORY_ID, I.ACTIVE, -TRI.QUANTITY,
	TRI.UNIT_COST, UM.NAME, ITS.SRP, TR.CREATED_DATE,FWL.CREATED_DATE AS FWL_CD,  -(TRI.QUANTITY * TRI.UNIT_COST) AS AMOUNT
	FROM R_TRANSFER_RECEIPT_ITEM TRI
	INNER JOIN R_TRANSFER_RECEIPT TR ON TRI.R_TRANSFER_RECEIPT_ID = TR.R_TRANSFER_RECEIPT_ID
	INNER JOIN FORM_WORKFLOW FW ON TR.FORM_WORKFLOW_ID = FW.FORM_WORKFLOW_ID
	INNER JOIN FORM_WORKFLOW_LOG FWL ON (FWL.FORM_WORKFLOW_ID = FW.FORM_WORKFLOW_ID AND FW.CURRENT_STATUS_ID = FWL.FORM_STATUS_ID)
	INNER JOIN ITEM I ON TRI.ITEM_ID = I.ITEM_ID
	INNER JOIN ITEM_SRP ITS ON TRI.ITEM_ID = ITS.ITEM_ID
	INNER JOIN UNIT_MEASUREMENT UM ON I.UNIT_MEASUREMENT_ID = UM.UNITOFMEASUREMENT_ID
	WHERE TR.COMPANY_ID = ITS.COMPANY_ID AND ITS.ACTIVE = 1
	GROUP BY FW.FORM_WORKFLOW_ID, TRI.R_TRANSFER_RECEIPT_ITEM_ID
UNION ALL
SELECT ITS.COMPANY_ID, ART.AR_TRANSACTION_ID, ASI.ACCOUNT_SALE_ITEM_ID, 'AS', ART.TRANSACTION_DATE, FW.IS_COMPLETE, FW.CURRENT_STATUS_ID AS FW_STATUS_ID, ASI.WAREHOUSE_ID, ASI.ITEM_ID, I.STOCK_CODE, I.DESCRIPTION, I.ITEM_CATEGORY_ID, I.ACTIVE,
	-ASI.QUANTITY, ASI.UNIT_COST, UM.NAME, ITS.SRP, ART.CREATED_DATE,FWL.CREATED_DATE AS FWL_CD,  -(ASI.QUANTITY * ASI.UNIT_COST) AS AMOUNT
	FROM ACCOUNT_SALE_ITEM ASI
	INNER JOIN AR_TRANSACTION ART ON ASI.AR_TRANSACTION_ID = ART.AR_TRANSACTION_ID
	INNER JOIN FORM_WORKFLOW FW ON ART.FORM_WORKFLOW_ID = FW.FORM_WORKFLOW_ID
	INNER JOIN FORM_WORKFLOW_LOG FWL ON (FWL.FORM_WORKFLOW_ID = FW.FORM_WORKFLOW_ID AND FW.CURRENT_STATUS_ID = FWL.FORM_STATUS_ID)
	INNER JOIN ITEM I ON ASI.ITEM_ID = I.ITEM_ID
	INNER JOIN ITEM_SRP ITS ON ASI.ITEM_ID = ITS.ITEM_ID
	INNER JOIN UNIT_MEASUREMENT UM ON I.UNIT_MEASUREMENT_ID = UM.UNITOFMEASUREMENT_ID
	WHERE ART.AR_TRANSACTION_TYPE_ID = 4 AND ART.COMPANY_ID = ITS.COMPANY_ID AND ITS.ACTIVE = 1
	GROUP BY FW.FORM_WORKFLOW_ID, ASI.ACCOUNT_SALE_ITEM_ID
UNION ALL
SELECT ITS.COMPANY_ID, ART.AR_TRANSACTION_ID, ASI.ACCOUNT_SALE_ITEM_ID, 'AS-W', ART.TRANSACTION_DATE, FW.IS_COMPLETE, FW.CURRENT_STATUS_ID AS FW_STATUS_ID, ASI.WAREHOUSE_ID, ASI.ITEM_ID, I.STOCK_CODE, I.DESCRIPTION, I.ITEM_CATEGORY_ID, I.ACTIVE,
	-ASI.QUANTITY, ASI.UNIT_COST, UM.NAME, ITS.SRP, ART.CREATED_DATE,FWL.CREATED_DATE AS FWL_CD,  -(ASI.QUANTITY * ASI.UNIT_COST) AS AMOUNT
	FROM ACCOUNT_SALE_ITEM ASI
	INNER JOIN AR_TRANSACTION ART ON ASI.AR_TRANSACTION_ID = ART.AR_TRANSACTION_ID
	INNER JOIN FORM_WORKFLOW FW ON ART.FORM_WORKFLOW_ID = FW.FORM_WORKFLOW_ID
	INNER JOIN FORM_WORKFLOW_LOG FWL ON (FWL.FORM_WORKFLOW_ID = FW.FORM_WORKFLOW_ID AND FW.CURRENT_STATUS_ID = FWL.FORM_STATUS_ID)
	INNER JOIN ITEM I ON ASI.ITEM_ID = I.ITEM_ID
	INNER JOIN ITEM_SRP ITS ON ASI.ITEM_ID = ITS.ITEM_ID
	INNER JOIN UNIT_MEASUREMENT UM ON I.UNIT_MEASUREMENT_ID = UM.UNITOFMEASUREMENT_ID
	WHERE ART.AR_TRANSACTION_TYPE_ID = 8 AND ART.COMPANY_ID = ITS.COMPANY_ID AND ITS.ACTIVE = 1
	GROUP BY FW.FORM_WORKFLOW_ID, ASI.ACCOUNT_SALE_ITEM_ID
UNION ALL
SELECT ITS.COMPANY_ID, ART.AR_TRANSACTION_ID, ASI.ACCOUNT_SALE_ITEM_ID, 'AS-IS', ART.TRANSACTION_DATE, FW.IS_COMPLETE, FW.CURRENT_STATUS_ID AS FW_STATUS_ID, ASI.WAREHOUSE_ID, ASI.ITEM_ID, I.STOCK_CODE, I.DESCRIPTION, I.ITEM_CATEGORY_ID, I.ACTIVE,
	-ASI.QUANTITY, ASI.UNIT_COST, UM.NAME, ITS.SRP, ART.CREATED_DATE,FWL.CREATED_DATE AS FWL_CD,  -(ASI.QUANTITY * ASI.UNIT_COST) AS AMOUNT
	FROM ACCOUNT_SALE_ITEM ASI
	INNER JOIN AR_TRANSACTION ART ON ASI.AR_TRANSACTION_ID = ART.AR_TRANSACTION_ID
	INNER JOIN FORM_WORKFLOW FW ON ART.FORM_WORKFLOW_ID = FW.FORM_WORKFLOW_ID
	INNER JOIN FORM_WORKFLOW_LOG FWL ON (FWL.FORM_WORKFLOW_ID = FW.FORM_WORKFLOW_ID AND FW.CURRENT_STATUS_ID = FWL.FORM_STATUS_ID)
	INNER JOIN ITEM I ON ASI.ITEM_ID = I.ITEM_ID
	INNER JOIN ITEM_SRP ITS ON ASI.ITEM_ID = ITS.ITEM_ID
	INNER JOIN UNIT_MEASUREMENT UM ON I.UNIT_MEASUREMENT_ID = UM.UNITOFMEASUREMENT_ID
	WHERE ART.AR_TRANSACTION_TYPE_ID = 10 AND ART.COMPANY_ID = ITS.COMPANY_ID AND ITS.ACTIVE = 1
	GROUP BY FW.FORM_WORKFLOW_ID, ASI.ACCOUNT_SALE_ITEM_ID
UNION ALL
SELECT ITS.COMPANY_ID, RP.REPACKING_ID, RPI.REPACKING_ITEM_ID, 'RP-FROM', RP.R_DATE, FW.IS_COMPLETE, FW.CURRENT_STATUS_ID AS FW_STATUS_ID, RP.WAREHOUSE_ID, RPI.FROM_ITEM_ID, I.STOCK_CODE, I.DESCRIPTION, I.ITEM_CATEGORY_ID, I.ACTIVE,
	-RPI.QUANTITY, RPI.UNIT_COST, UM.NAME, ITS.SRP, RP.CREATED_DATE, FWL.CREATED_DATE AS FWL_CD, -(RPI.QUANTITY * RPI.UNIT_COST) AS AMOUNT
	FROM REPACKING_ITEM RPI
	INNER JOIN REPACKING RP ON RP.REPACKING_ID = RPI.REPACKING_ID
	INNER JOIN FORM_WORKFLOW FW ON RP.FORM_WORKFLOW_ID = FW.FORM_WORKFLOW_ID
	INNER JOIN FORM_WORKFLOW_LOG FWL ON (FWL.FORM_WORKFLOW_ID = FW.FORM_WORKFLOW_ID AND FW.CURRENT_STATUS_ID = FWL.FORM_STATUS_ID)
	INNER JOIN ITEM I ON RPI.FROM_ITEM_ID = I.ITEM_ID
	INNER JOIN ITEM_SRP ITS ON RPI.FROM_ITEM_ID = ITS.ITEM_ID
	INNER JOIN UNIT_MEASUREMENT UM ON I.UNIT_MEASUREMENT_ID = UM.UNITOFMEASUREMENT_ID
	WHERE RP.COMPANY_ID = ITS.COMPANY_ID AND ITS.ACTIVE = 1
	GROUP BY FW.FORM_WORKFLOW_ID, RPI.REPACKING_ITEM_ID
UNION ALL
SELECT ITS.COMPANY_ID, SA.STOCK_ADJUSTMENT_ID, SAI.STOCK_ADJUSTMENT_ITEM_ID, 'SA', SA.SA_DATE, FW.IS_COMPLETE, FW.CURRENT_STATUS_ID AS FW_STATUS_ID, SA.WAREHOUSE_ID, SAI.ITEM_ID, I.STOCK_CODE, I.DESCRIPTION, I.ITEM_CATEGORY_ID, I.ACTIVE, SAI.QUANTITY,
	SAI.UNIT_COST, UM.NAME, ITS.SRP, SA.CREATED_DATE, FWL.CREATED_DATE AS FWL_CD, (SAI.QUANTITY * SAI.UNIT_COST) AS AMOUNT
	FROM STOCK_ADJUSTMENT_ITEM SAI
	INNER JOIN STOCK_ADJUSTMENT SA ON SAI.STOCK_ADJUSTMENT_ID = SA.STOCK_ADJUSTMENT_ID
	INNER JOIN FORM_WORKFLOW FW ON SA.FORM_WORKFLOW_ID = FW.FORM_WORKFLOW_ID
	INNER JOIN FORM_WORKFLOW_LOG FWL ON (FWL.FORM_WORKFLOW_ID = FW.FORM_WORKFLOW_ID AND FW.CURRENT_STATUS_ID = FWL.FORM_STATUS_ID)
	INNER JOIN ITEM I ON SAI.ITEM_ID = I.ITEM_ID
	INNER JOIN ITEM_SRP ITS ON SAI.ITEM_ID = ITS.ITEM_ID
	INNER JOIN UNIT_MEASUREMENT UM ON I.UNIT_MEASUREMENT_ID = UM.UNITOFMEASUREMENT_ID
	WHERE SA.COMPANY_ID = ITS.COMPANY_ID AND ITS.ACTIVE = 1
	GROUP BY FW.FORM_WORKFLOW_ID, SAI.STOCK_ADJUSTMENT_ITEM_ID
UNION ALL
SELECT ITS.COMPANY_ID, CAPD.CAP_DELIVERY_ID, CAPDI.CAP_DELIVERY_ITEM_ID, 'CAPD', CAPD.DELIVERY_DATE, FW.IS_COMPLETE, FW.CURRENT_STATUS_ID AS FW_STATUS_ID, CAPDI.WAREHOUSE_ID, CAPDI.ITEM_ID, I.STOCK_CODE, I.DESCRIPTION, I.ITEM_CATEGORY_ID, I.ACTIVE,
	-CAPDI.QUANTITY, CAPDI.UNIT_COST, UM.NAME, ITS.SRP, CAPD.CREATED_DATE, FWL.CREATED_DATE AS FWL_CD, (CAPDI.QUANTITY * CAPDI.UNIT_COST) AS AMOUNT
	FROM CAP_DELIVERY_ITEM CAPDI
	INNER JOIN CAP_DELIVERY CAPD ON CAPD.CAP_DELIVERY_ID = CAPDI.CAP_DELIVERY_ID
	INNER JOIN FORM_WORKFLOW FW ON CAPD.FORM_WORKFLOW_ID = FW.FORM_WORKFLOW_ID
	INNER JOIN FORM_WORKFLOW_LOG FWL ON (FWL.FORM_WORKFLOW_ID = FW.FORM_WORKFLOW_ID AND FW.CURRENT_STATUS_ID = FWL.FORM_STATUS_ID)
	INNER JOIN ITEM I ON CAPDI.ITEM_ID = I.ITEM_ID
	INNER JOIN ITEM_SRP ITS ON CAPDI.ITEM_ID = ITS.ITEM_ID
	INNER JOIN UNIT_MEASUREMENT UM ON I.UNIT_MEASUREMENT_ID = UM.UNITOFMEASUREMENT_ID
	WHERE CAPD.COMPANY_ID = ITS.COMPANY_ID AND ITS.ACTIVE = 1
	GROUP BY FW.FORM_WORKFLOW_ID, CAPDI.CAP_DELIVERY_ITEM_ID
UNION ALL
SELECT PR.COMPANY_ID, PR.PROCESSING_REPORT_ID, PRRM.PR_RAW_MATERIALS_ITEM_ID, 'PR-RM', PR.DATE, FW.IS_COMPLETE, FW.CURRENT_STATUS_ID AS FW_STATUS_ID, PRRM.WAREHOUSE_ID, PRRM.ITEM_ID, I.STOCK_CODE, I.DESCRIPTION, I.ITEM_CATEGORY_ID, I.ACTIVE,
	-PRRM.QUANTITY, PRRM.UNIT_COST, UM.NAME, COALESCE((SELECT ISRP.SRP FROM ITEM_SRP ISRP WHERE ISRP.ITEM_ID = PRRM.ITEM_ID AND ISRP.COMPANY_ID = PR.COMPANY_ID AND ISRP.ACTIVE = 1), 0) AS SRP, 
	PR.CREATED_DATE, FWL.CREATED_DATE AS FWL_CD, -(PRRM.QUANTITY * PRRM.UNIT_COST) AS AMOUNT
	FROM PR_RAW_MATERIALS_ITEM PRRM
	INNER JOIN PROCESSING_REPORT PR ON PR.PROCESSING_REPORT_ID = PRRM.PROCESSING_REPORT_ID
	INNER JOIN FORM_WORKFLOW FW ON PR.FORM_WORKFLOW_ID = FW.FORM_WORKFLOW_ID
	INNER JOIN FORM_WORKFLOW_LOG FWL ON (FWL.FORM_WORKFLOW_ID = FW.FORM_WORKFLOW_ID AND FW.CURRENT_STATUS_ID = FWL.FORM_STATUS_ID)
	INNER JOIN ITEM I ON PRRM.ITEM_ID = I.ITEM_ID
	INNER JOIN UNIT_MEASUREMENT UM ON I.UNIT_MEASUREMENT_ID = UM.UNITOFMEASUREMENT_ID
	GROUP BY FW.FORM_WORKFLOW_ID, PRRM.PR_RAW_MATERIALS_ITEM_ID
UNION ALL
SELECT PR.COMPANY_ID, PR.PROCESSING_REPORT_ID, PROM.PR_OTHER_MATERIALS_ITEM_ID, 'PR-OM', PR.DATE, FW.IS_COMPLETE, FW.CURRENT_STATUS_ID AS FW_STATUS_ID, PROM.WAREHOUSE_ID, PROM.ITEM_ID, I.STOCK_CODE, I.DESCRIPTION, I.ITEM_CATEGORY_ID, I.ACTIVE,
	-PROM.QUANTITY, PROM.UNIT_COST, UM.NAME, COALESCE((SELECT ISRP.SRP FROM ITEM_SRP ISRP WHERE ISRP.ITEM_ID = PROM.ITEM_ID AND ISRP.COMPANY_ID = PR.COMPANY_ID AND ISRP.ACTIVE = 1), 0) AS SRP, 
	PR.CREATED_DATE, FWL.CREATED_DATE AS FWL_CD, -(PROM.QUANTITY * PROM.UNIT_COST) AS AMOUNT
	FROM PR_OTHER_MATERIALS_ITEM PROM
	INNER JOIN PROCESSING_REPORT PR ON PR.PROCESSING_REPORT_ID = PROM.PROCESSING_REPORT_ID
	INNER JOIN FORM_WORKFLOW FW ON PR.FORM_WORKFLOW_ID = FW.FORM_WORKFLOW_ID
	INNER JOIN FORM_WORKFLOW_LOG FWL ON (FWL.FORM_WORKFLOW_ID = FW.FORM_WORKFLOW_ID AND FW.CURRENT_STATUS_ID = FWL.FORM_STATUS_ID)
	INNER JOIN ITEM I ON PROM.ITEM_ID = I.ITEM_ID
	INNER JOIN UNIT_MEASUREMENT UM ON I.UNIT_MEASUREMENT_ID = UM.UNITOFMEASUREMENT_ID
	GROUP BY FW.FORM_WORKFLOW_ID, PROM.PR_OTHER_MATERIALS_ITEM_ID
UNION ALL
SELECT PR.COMPANY_ID, PR.PROCESSING_REPORT_ID, PRMP.PR_MAIN_PRODUCT_ID, 'PR-MP', PR.DATE, FW.IS_COMPLETE, FW.CURRENT_STATUS_ID AS FW_STATUS_ID, PRMP.WAREHOUSE_ID, PRMP.ITEM_ID, I.STOCK_CODE, I.DESCRIPTION, I.ITEM_CATEGORY_ID, I.ACTIVE,
	PRMP.QUANTITY, PRMP.UNIT_COST, UM.NAME, COALESCE((SELECT ISRP.SRP FROM ITEM_SRP ISRP WHERE ISRP.ITEM_ID = PRMP.ITEM_ID AND ISRP.COMPANY_ID = PR.COMPANY_ID AND ISRP.ACTIVE = 1), 0) AS SRP, 
	PR.CREATED_DATE, FWL.CREATED_DATE AS FWL_CD, (PRMP.QUANTITY * PRMP.UNIT_COST) AS AMOUNT
	FROM PR_MAIN_PRODUCT PRMP
	INNER JOIN PROCESSING_REPORT PR ON PR.PROCESSING_REPORT_ID = PRMP.PROCESSING_REPORT_ID
	INNER JOIN FORM_WORKFLOW FW ON PR.FORM_WORKFLOW_ID = FW.FORM_WORKFLOW_ID
	INNER JOIN FORM_WORKFLOW_LOG FWL ON (FWL.FORM_WORKFLOW_ID = FW.FORM_WORKFLOW_ID AND FW.CURRENT_STATUS_ID = FWL.FORM_STATUS_ID)
	INNER JOIN ITEM I ON PRMP.ITEM_ID = I.ITEM_ID
	INNER JOIN UNIT_MEASUREMENT UM ON I.UNIT_MEASUREMENT_ID = UM.UNITOFMEASUREMENT_ID
	GROUP BY FW.FORM_WORKFLOW_ID, PRMP.PR_MAIN_PRODUCT_ID
UNION ALL
SELECT PR.COMPANY_ID, PR.PROCESSING_REPORT_ID, PRBP.PR_BY_PRODUCT_ID, 'PR-BP', PR.DATE, FW.IS_COMPLETE, FW.CURRENT_STATUS_ID AS FW_STATUS_ID, PRBP.WAREHOUSE_ID, PRBP.ITEM_ID, I.STOCK_CODE, I.DESCRIPTION, I.ITEM_CATEGORY_ID, I.ACTIVE,
	PRBP.QUANTITY, PRBP.UNIT_COST, UM.NAME, COALESCE((SELECT ISRP.SRP FROM ITEM_SRP ISRP WHERE ISRP.ITEM_ID = PRBP.ITEM_ID AND ISRP.COMPANY_ID = PR.COMPANY_ID AND ISRP.ACTIVE = 1), 0) AS SRP, 
	PR.CREATED_DATE, FWL.CREATED_DATE AS FWL_CD, 0 AS AMOUNT
	FROM PR_BY_PRODUCT PRBP
	INNER JOIN PROCESSING_REPORT PR ON PR.PROCESSING_REPORT_ID = PRBP.PROCESSING_REPORT_ID
	INNER JOIN FORM_WORKFLOW FW ON PR.FORM_WORKFLOW_ID = FW.FORM_WORKFLOW_ID
	INNER JOIN FORM_WORKFLOW_LOG FWL ON (FWL.FORM_WORKFLOW_ID = FW.FORM_WORKFLOW_ID AND FW.CURRENT_STATUS_ID = FWL.FORM_STATUS_ID)
	INNER JOIN ITEM I ON PRBP.ITEM_ID = I.ITEM_ID
	INNER JOIN UNIT_MEASUREMENT UM ON I.UNIT_MEASUREMENT_ID = UM.UNITOFMEASUREMENT_ID
	GROUP BY FW.FORM_WORKFLOW_ID, PRBP.PR_BY_PRODUCT_ID;