-- Description: mysql view for statement of accounts with Account Collection reference.


DROP VIEW IF EXISTS V_STATEMENT_OF_ACCOUNT;

CREATE VIEW V_STATEMENT_OF_ACCOUNT AS
	SELECT AT.COMPANY_ID, C.NAME, AT.CUSTOMER_ACCOUNT_ID, AT.CUSTOMER_ID AS CUSTOMER_ID, 'TRANS' as SOURCE, AT.AR_TRANSACTION_ID as ID,
		AT.TRANSACTION_DATE AS DATE, AT.GL_DATE, AT.DUE_DATE AS DUE_DATE, AT.TRANSACTION_NUMBER as REFERENCE_NUMBER,
        DESCRIPTION AS INVOICE_NUMBER, AT.AMOUNT as TRANSACTION_AMOUNT, 
        COALESCE((SELECT SUM(RT.AMOUNT) FROM AR_RECEIPT_TRANSACTION RT
        	INNER JOIN AR_RECEIPT AR ON AR.AR_RECEIPT_ID = RT.AR_RECEIPT_ID
        	INNER JOIN FORM_WORKFLOW F ON AR.FORM_WORKFLOW_ID = F.FORM_WORKFLOW_ID
        	WHERE RT.AR_TRANSACTION_ID=AT.AR_TRANSACTION_ID  AND F.CURRENT_STATUS_ID != 4), 0) as RECEIPT_AMOUNT,
        AT.CREATED_DATE, '' AS AR_LINE_ID, F.CURRENT_STATUS_ID as STATUS_ID, F.IS_COMPLETE as IS_COMPLETE, T.TERM_ID, T.DAYS as TERM_DAYS,
		(SELECT GROUP_CONCAT(CONCAT('AC-', ARR.SEQUENCE_NO) Separator ', ') FROM AR_RECEIPT ARR
			INNER JOIN AR_RECEIPT_TRANSACTION ARRT ON ARRT.AR_RECEIPT_ID = ARR.AR_RECEIPT_ID
			INNER JOIN AR_TRANSACTION AT1 ON AT1.AR_TRANSACTION_ID = ARRT.AR_TRANSACTION_ID
			INNER JOIN FORM_WORKFLOW ARR_FW ON ARR_FW.FORM_WORKFLOW_ID = ARR.FORM_WORKFLOW_ID
			WHERE AT1.AR_TRANSACTION_TYPE_ID <= 3
			AND ARR_FW.CURRENT_STATUS_ID != 4
			AND AT1.AR_TRANSACTION_ID = AT.AR_TRANSACTION_ID) AS AC_REF_NUMBER
    FROM AR_TRANSACTION AT
    INNER JOIN AR_CUSTOMER_ACCOUNT ACA ON ACA.AR_CUSTOMER_ACCOUNT_ID = AT.CUSTOMER_ACCOUNT_ID
    INNER JOIN TERM T ON ACA.TERM_ID = T.TERM_ID
    INNER JOIN FORM_WORKFLOW F ON AT.FORM_WORKFLOW_ID = F.FORM_WORKFLOW_ID
    INNER JOIN AR_CUSTOMER C ON C.AR_CUSTOMER_ID = ACA.AR_CUSTOMER_ID
    WHERE F.CURRENT_STATUS_ID != 4 AND AT.AR_TRANSACTION_TYPE_ID <= 3
    UNION ALL
	SELECT AT.COMPANY_ID, C.NAME, AT.CUSTOMER_ACCOUNT_ID, AT.CUSTOMER_ID, 'AS' as SOURCE, AT.AR_TRANSACTION_ID as ID,
	AT.TRANSACTION_DATE AS DATE, AT.TRANSACTION_DATE, AT.DUE_DATE AS DUE_DATE, AT.TRANSACTION_NUMBER as REFERENCE_NUMBER,
	DESCRIPTION AS INVOICE_NUMBER, AT.AMOUNT as TRANSACTION_AMOUNT, 
	COALESCE((SELECT SUM(RT.AMOUNT) FROM AR_RECEIPT_TRANSACTION RT
			INNER JOIN AR_RECEIPT AR ON AR.AR_RECEIPT_ID = RT.AR_RECEIPT_ID
			INNER JOIN FORM_WORKFLOW F ON AR.FORM_WORKFLOW_ID = F.FORM_WORKFLOW_ID
		WHERE RT.AR_TRANSACTION_ID=AT.AR_TRANSACTION_ID  AND F.CURRENT_STATUS_ID != 4), 0) as RECEIPT_AMOUNT,
		AT.CREATED_DATE, '' AS AR_LINE_ID, F.CURRENT_STATUS_ID, F.IS_COMPLETE, T.TERM_ID, T.DAYS as TERM_DAYS,
		(SELECT GROUP_CONCAT(CONCAT('AC-', ARR.SEQUENCE_NO) Separator ', ') FROM AR_RECEIPT ARR
			INNER JOIN AR_RECEIPT_TRANSACTION ARRT ON ARRT.AR_RECEIPT_ID = ARR.AR_RECEIPT_ID
			INNER JOIN AR_TRANSACTION AT1 ON AT1.AR_TRANSACTION_ID = ARRT.AR_TRANSACTION_ID
			INNER JOIN FORM_WORKFLOW ARR_FW ON ARR_FW.FORM_WORKFLOW_ID = ARR.FORM_WORKFLOW_ID
			WHERE AT1.AR_TRANSACTION_TYPE_ID = 4
			AND ARR_FW.CURRENT_STATUS_ID != 4
			AND AT1.AR_TRANSACTION_ID = AT.AR_TRANSACTION_ID) AS AC_REF_NUMBER
	    FROM AR_TRANSACTION AT
	    INNER JOIN AR_CUSTOMER_ACCOUNT ACA ON ACA.AR_CUSTOMER_ACCOUNT_ID = AT.CUSTOMER_ACCOUNT_ID
	    INNER JOIN TERM T ON ACA.TERM_ID = T.TERM_ID
	    INNER JOIN FORM_WORKFLOW F ON AT.FORM_WORKFLOW_ID = F.FORM_WORKFLOW_ID
	    INNER JOIN AR_CUSTOMER C ON C.AR_CUSTOMER_ID = ACA.AR_CUSTOMER_ID
	    WHERE AT.AR_TRANSACTION_TYPE_ID = 4
	    AND F.CURRENT_STATUS_ID != 4
    UNION ALL
    -- Negate the amount of the Account Sales Return
    SELECT AT.COMPANY_ID, C.NAME, AT.CUSTOMER_ACCOUNT_ID, AT.CUSTOMER_ID, 'ASR' as SOURCE, AT.AR_TRANSACTION_ID as ID,
    AT.TRANSACTION_DATE AS DATE, AT.TRANSACTION_DATE, AT.TRANSACTION_DATE AS DUE_DATE, AT.TRANSACTION_NUMBER as REFERENCE_NUMBER,
        DESCRIPTION AS INVOICE_NUMBER, AT.AMOUNT as TRANSACTION_AMOUNT,
        COALESCE((SELECT SUM(RT.AMOUNT) FROM AR_RECEIPT_TRANSACTION RT
        	INNER JOIN AR_RECEIPT AR ON AR.AR_RECEIPT_ID = RT.AR_RECEIPT_ID
        	INNER JOIN FORM_WORKFLOW F ON AR.FORM_WORKFLOW_ID = F.FORM_WORKFLOW_ID
        	WHERE RT.AR_TRANSACTION_ID=AT.AR_TRANSACTION_ID  AND F.CURRENT_STATUS_ID != 4),0) as RECEIPT_AMOUNT,
        	AT.CREATED_DATE, '' AS AR_LINE_ID, F.CURRENT_STATUS_ID, F.IS_COMPLETE, T.TERM_ID, T.DAYS as TERM_DAYS,
    	(SELECT GROUP_CONCAT(CONCAT('AC-', ARR.SEQUENCE_NO) Separator ', ') FROM AR_RECEIPT ARR
			INNER JOIN AR_RECEIPT_TRANSACTION ARRT ON ARRT.AR_RECEIPT_ID = ARR.AR_RECEIPT_ID
			INNER JOIN AR_TRANSACTION AT1 ON AT1.AR_TRANSACTION_ID = ARRT.AR_TRANSACTION_ID
			INNER JOIN FORM_WORKFLOW ARR_FW ON ARR_FW.FORM_WORKFLOW_ID = ARR.FORM_WORKFLOW_ID
			WHERE AT1.AR_TRANSACTION_TYPE_ID = 5
			AND ARR_FW.CURRENT_STATUS_ID != 4
			AND AT1.AR_TRANSACTION_ID = AT.AR_TRANSACTION_ID) AS AC_REF_NUMBER
        FROM AR_TRANSACTION AT
        INNER JOIN ACCOUNT_SALE_ITEM ASI ON ASI.AR_TRANSACTION_ID = AT.AR_TRANSACTION_ID
        INNER JOIN AR_CUSTOMER_ACCOUNT ACA ON ACA.AR_CUSTOMER_ACCOUNT_ID = AT.CUSTOMER_ACCOUNT_ID
        INNER JOIN TERM T ON ACA.TERM_ID = T.TERM_ID
        INNER JOIN FORM_WORKFLOW F ON AT.FORM_WORKFLOW_ID = F.FORM_WORKFLOW_ID
        INNER JOIN AR_CUSTOMER C ON C.AR_CUSTOMER_ID = ACA.AR_CUSTOMER_ID
        WHERE AT.AR_TRANSACTION_TYPE_ID = 5
        AND F.CURRENT_STATUS_ID != 4
        GROUP BY AT.AR_TRANSACTION_ID
	UNION ALL
		SELECT AT.COMPANY_ID, C.NAME, AT.CUSTOMER_ACCOUNT_ID, AT.CUSTOMER_ID, 'AS-IS' as SOURCE, AT.AR_TRANSACTION_ID as ID,
		AT.TRANSACTION_DATE AS DATE, AT.TRANSACTION_DATE, AT.DUE_DATE AS DUE_DATE, AT.TRANSACTION_NUMBER as REFERENCE_NUMBER,
		DESCRIPTION AS INVOICE_NUMBER, AT.AMOUNT as TRANSACTION_AMOUNT, 
		COALESCE((SELECT SUM(RT.AMOUNT) FROM AR_RECEIPT_TRANSACTION RT
				INNER JOIN AR_RECEIPT AR ON AR.AR_RECEIPT_ID = RT.AR_RECEIPT_ID
				INNER JOIN FORM_WORKFLOW F ON AR.FORM_WORKFLOW_ID = F.FORM_WORKFLOW_ID
			WHERE RT.AR_TRANSACTION_ID=AT.AR_TRANSACTION_ID  AND F.CURRENT_STATUS_ID != 4), 0) as RECEIPT_AMOUNT,  
			AT.CREATED_DATE, '' AS AR_LINE_ID, F.CURRENT_STATUS_ID, F.IS_COMPLETE, T.TERM_ID, T.DAYS as TERM_DAYS,
			(SELECT GROUP_CONCAT(CONCAT('AC-', ARR.SEQUENCE_NO) Separator ', ') FROM AR_RECEIPT ARR
				INNER JOIN AR_RECEIPT_TRANSACTION ARRT ON ARRT.AR_RECEIPT_ID = ARR.AR_RECEIPT_ID
				INNER JOIN AR_TRANSACTION AT1 ON AT1.AR_TRANSACTION_ID = ARRT.AR_TRANSACTION_ID
				INNER JOIN FORM_WORKFLOW ARR_FW ON ARR_FW.FORM_WORKFLOW_ID = ARR.FORM_WORKFLOW_ID
				WHERE AT1.AR_TRANSACTION_TYPE_ID = 10
				AND ARR_FW.CURRENT_STATUS_ID != 4
				AND AT1.AR_TRANSACTION_ID = AT.AR_TRANSACTION_ID) AS AC_REF_NUMBER
			FROM AR_TRANSACTION AT
			INNER JOIN AR_CUSTOMER_ACCOUNT ACA ON ACA.AR_CUSTOMER_ACCOUNT_ID = AT.CUSTOMER_ACCOUNT_ID
			INNER JOIN TERM T ON ACA.TERM_ID = T.TERM_ID
			INNER JOIN FORM_WORKFLOW F ON AT.FORM_WORKFLOW_ID = F.FORM_WORKFLOW_ID
			INNER JOIN AR_CUSTOMER C ON C.AR_CUSTOMER_ID = ACA.AR_CUSTOMER_ID
			WHERE AT.AR_TRANSACTION_TYPE_ID = 10
			AND F.CURRENT_STATUS_ID != 4
	UNION ALL
		-- Negate the amount of the Account Sales Return - IS
	SELECT AT.COMPANY_ID, C.NAME, AT.CUSTOMER_ACCOUNT_ID, AT.CUSTOMER_ID, 'ASR-IS' as SOURCE, AT.AR_TRANSACTION_ID as ID,
	AT.TRANSACTION_DATE AS DATE, AT.TRANSACTION_DATE, AT.TRANSACTION_DATE AS DUE_DATE, AT.TRANSACTION_NUMBER as REFERENCE_NUMBER,
	DESCRIPTION AS INVOICE_NUMBER, SUM(ASI.AMOUNT) as TRANSACTION_AMOUNT, 
		COALESCE((SELECT SUM(RT.AMOUNT) FROM AR_RECEIPT_TRANSACTION RT
			INNER JOIN AR_RECEIPT AR ON AR.AR_RECEIPT_ID = RT.AR_RECEIPT_ID
			INNER JOIN FORM_WORKFLOW F ON AR.FORM_WORKFLOW_ID = F.FORM_WORKFLOW_ID
			WHERE RT.AR_TRANSACTION_ID=AT.AR_TRANSACTION_ID  AND F.CURRENT_STATUS_ID != 4),0) as RECEIPT_AMOUNT,  
			AT.CREATED_DATE, '' AS AR_LINE_ID, F.CURRENT_STATUS_ID, F.IS_COMPLETE, T.TERM_ID, T.DAYS as TERM_DAYS,
		(SELECT GROUP_CONCAT(CONCAT('AC-', ARR.SEQUENCE_NO) Separator ', ') FROM AR_RECEIPT ARR
			INNER JOIN AR_RECEIPT_TRANSACTION ARRT ON ARRT.AR_RECEIPT_ID = ARR.AR_RECEIPT_ID
			INNER JOIN AR_TRANSACTION AT1 ON AT1.AR_TRANSACTION_ID = ARRT.AR_TRANSACTION_ID
			INNER JOIN FORM_WORKFLOW ARR_FW ON ARR_FW.FORM_WORKFLOW_ID = ARR.FORM_WORKFLOW_ID
			WHERE AT1.AR_TRANSACTION_TYPE_ID = 11
			AND ARR_FW.CURRENT_STATUS_ID != 4
			AND AT1.AR_TRANSACTION_ID = AT.AR_TRANSACTION_ID) AS AC_REF_NUMBER
		FROM AR_TRANSACTION AT
		INNER JOIN ACCOUNT_SALE_ITEM ASI ON ASI.AR_TRANSACTION_ID = AT.AR_TRANSACTION_ID
		INNER JOIN AR_CUSTOMER_ACCOUNT ACA ON ACA.AR_CUSTOMER_ACCOUNT_ID = AT.CUSTOMER_ACCOUNT_ID
		INNER JOIN TERM T ON ACA.TERM_ID = T.TERM_ID
		INNER JOIN FORM_WORKFLOW F ON AT.FORM_WORKFLOW_ID = F.FORM_WORKFLOW_ID
		INNER JOIN AR_CUSTOMER C ON C.AR_CUSTOMER_ID = ACA.AR_CUSTOMER_ID
		WHERE AT.AR_TRANSACTION_TYPE_ID = 11
		AND F.CURRENT_STATUS_ID != 4
		GROUP BY AT.AR_TRANSACTION_ID
	UNION ALL
	SELECT AT.COMPANY_ID, C.NAME, AT.CUSTOMER_ACCOUNT_ID, AT.CUSTOMER_ID, 'AS' as SOURCE, AT.AR_TRANSACTION_ID as ID,
	AT.TRANSACTION_DATE AS DATE, AT.TRANSACTION_DATE, AT.DUE_DATE AS DUE_DATE, AT.TRANSACTION_NUMBER as REFERENCE_NUMBER,
	DESCRIPTION AS INVOICE_NUMBER, AT.AMOUNT as TRANSACTION_AMOUNT, 
	COALESCE((SELECT SUM(RT.AMOUNT) FROM AR_RECEIPT_TRANSACTION RT
			INNER JOIN AR_RECEIPT AR ON AR.AR_RECEIPT_ID = RT.AR_RECEIPT_ID
			INNER JOIN FORM_WORKFLOW F ON AR.FORM_WORKFLOW_ID = F.FORM_WORKFLOW_ID
		WHERE RT.AR_TRANSACTION_ID=AT.AR_TRANSACTION_ID  AND F.CURRENT_STATUS_ID != 4), 0) as RECEIPT_AMOUNT,  
		AT.CREATED_DATE, '' AS AR_LINE_ID, F.CURRENT_STATUS_ID, F.IS_COMPLETE, T.TERM_ID, T.DAYS as TERM_DAYS,
		(SELECT GROUP_CONCAT(CONCAT('AC-', ARR.SEQUENCE_NO) Separator ', ') FROM AR_RECEIPT ARR
			INNER JOIN AR_RECEIPT_TRANSACTION ARRT ON ARRT.AR_RECEIPT_ID = ARR.AR_RECEIPT_ID
			INNER JOIN AR_TRANSACTION AT1 ON AT1.AR_TRANSACTION_ID = ARRT.AR_TRANSACTION_ID
			INNER JOIN FORM_WORKFLOW ARR_FW ON ARR_FW.FORM_WORKFLOW_ID = ARR.FORM_WORKFLOW_ID
			WHERE AT1.AR_TRANSACTION_TYPE_ID = 12
			AND ARR_FW.CURRENT_STATUS_ID != 4
			AND AT1.AR_TRANSACTION_ID = AT.AR_TRANSACTION_ID) AS AC_REF_NUMBER
	    FROM AR_TRANSACTION AT
	    INNER JOIN AR_CUSTOMER_ACCOUNT ACA ON ACA.AR_CUSTOMER_ACCOUNT_ID = AT.CUSTOMER_ACCOUNT_ID
	    INNER JOIN TERM T ON ACA.TERM_ID = T.TERM_ID
	    INNER JOIN FORM_WORKFLOW F ON AT.FORM_WORKFLOW_ID = F.FORM_WORKFLOW_ID
	    INNER JOIN AR_CUSTOMER C ON C.AR_CUSTOMER_ID = ACA.AR_CUSTOMER_ID
	    WHERE AT.AR_TRANSACTION_TYPE_ID = 12
	    AND F.CURRENT_STATUS_ID != 4
    UNION ALL
    -- Negate the amount of the Account Sales Return
    SELECT AT.COMPANY_ID, C.NAME, AT.CUSTOMER_ACCOUNT_ID, AT.CUSTOMER_ID, 'ASR' as SOURCE, AT.AR_TRANSACTION_ID as ID,
    AT.TRANSACTION_DATE AS DATE, AT.TRANSACTION_DATE, AT.TRANSACTION_DATE AS DUE_DATE, AT.TRANSACTION_NUMBER as REFERENCE_NUMBER,
        DESCRIPTION AS INVOICE_NUMBER, SUM(ASI.AMOUNT) as TRANSACTION_AMOUNT, 
        COALESCE((SELECT SUM(RT.AMOUNT) FROM AR_RECEIPT_TRANSACTION RT
        	INNER JOIN AR_RECEIPT AR ON AR.AR_RECEIPT_ID = RT.AR_RECEIPT_ID
        	INNER JOIN FORM_WORKFLOW F ON AR.FORM_WORKFLOW_ID = F.FORM_WORKFLOW_ID
        	WHERE RT.AR_TRANSACTION_ID=AT.AR_TRANSACTION_ID  AND F.CURRENT_STATUS_ID != 4),0) as RECEIPT_AMOUNT,  
        	AT.CREATED_DATE, '' AS AR_LINE_ID, F.CURRENT_STATUS_ID, F.IS_COMPLETE, T.TERM_ID, T.DAYS as TERM_DAYS,
        (SELECT GROUP_CONCAT(CONCAT('AC-', ARR.SEQUENCE_NO) Separator ', ') FROM AR_RECEIPT ARR
			INNER JOIN AR_RECEIPT_TRANSACTION ARRT ON ARRT.AR_RECEIPT_ID = ARR.AR_RECEIPT_ID
			INNER JOIN AR_TRANSACTION AT1 ON AT1.AR_TRANSACTION_ID = ARRT.AR_TRANSACTION_ID
			INNER JOIN FORM_WORKFLOW ARR_FW ON ARR_FW.FORM_WORKFLOW_ID = ARR.FORM_WORKFLOW_ID
			WHERE AT1.AR_TRANSACTION_TYPE_ID = 13
			AND ARR_FW.CURRENT_STATUS_ID != 4
			AND AT1.AR_TRANSACTION_ID = AT.AR_TRANSACTION_ID) AS AC_REF_NUMBER
        FROM AR_TRANSACTION AT
        INNER JOIN ACCOUNT_SALE_ITEM ASI ON ASI.AR_TRANSACTION_ID = AT.AR_TRANSACTION_ID
        INNER JOIN AR_CUSTOMER_ACCOUNT ACA ON ACA.AR_CUSTOMER_ACCOUNT_ID = AT.CUSTOMER_ACCOUNT_ID
        INNER JOIN TERM T ON ACA.TERM_ID = T.TERM_ID
        INNER JOIN FORM_WORKFLOW F ON AT.FORM_WORKFLOW_ID = F.FORM_WORKFLOW_ID
        INNER JOIN AR_CUSTOMER C ON C.AR_CUSTOMER_ID = ACA.AR_CUSTOMER_ID
        WHERE AT.AR_TRANSACTION_TYPE_ID = 13
        AND F.CURRENT_STATUS_ID != 4
        GROUP BY AT.AR_TRANSACTION_ID
    UNION ALL
	SELECT AT.COMPANY_ID, C.NAME, AT.CUSTOMER_ACCOUNT_ID, AT.CUSTOMER_ID, 'AS' as SOURCE, AT.AR_TRANSACTION_ID as ID,
	AT.TRANSACTION_DATE AS DATE, AT.TRANSACTION_DATE, AT.DUE_DATE AS DUE_DATE, AT.TRANSACTION_NUMBER as REFERENCE_NUMBER,
	DESCRIPTION AS INVOICE_NUMBER, AT.AMOUNT as TRANSACTION_AMOUNT,
	(COALESCE((SELECT SUM(RT.AMOUNT) FROM AR_RECEIPT_TRANSACTION RT
		INNER JOIN AR_RECEIPT AR ON AR.AR_RECEIPT_ID = RT.AR_RECEIPT_ID
		INNER JOIN FORM_WORKFLOW F ON AR.FORM_WORKFLOW_ID = F.FORM_WORKFLOW_ID
		WHERE RT.AR_TRANSACTION_ID = AT.AR_TRANSACTION_ID  AND F.CURRENT_STATUS_ID != 4), 0)) as RECEIPT_AMOUNT,
		AT.CREATED_DATE, '' AS AR_LINE_ID, F.CURRENT_STATUS_ID, F.IS_COMPLETE, T.TERM_ID, T.DAYS as TERM_DAYS,
		(SELECT GROUP_CONCAT(CONCAT('AC-', ARR.SEQUENCE_NO) Separator ', ') FROM AR_RECEIPT ARR
			INNER JOIN AR_RECEIPT_TRANSACTION ARRT ON ARRT.AR_RECEIPT_ID = ARR.AR_RECEIPT_ID
			INNER JOIN AR_TRANSACTION AT1 ON AT1.AR_TRANSACTION_ID = ARRT.AR_TRANSACTION_ID
			INNER JOIN FORM_WORKFLOW ARR_FW ON ARR_FW.FORM_WORKFLOW_ID = ARR.FORM_WORKFLOW_ID
			WHERE AT1.AR_TRANSACTION_TYPE_ID = 14
			AND ARR_FW.CURRENT_STATUS_ID != 4
			AND AT1.AR_TRANSACTION_ID = AT.AR_TRANSACTION_ID) AS AC_REF_NUMBER
	    FROM AR_TRANSACTION AT
	    INNER JOIN AR_CUSTOMER_ACCOUNT ACA ON ACA.AR_CUSTOMER_ACCOUNT_ID = AT.CUSTOMER_ACCOUNT_ID
	    INNER JOIN TERM T ON ACA.TERM_ID = T.TERM_ID
	    INNER JOIN FORM_WORKFLOW F ON AT.FORM_WORKFLOW_ID = F.FORM_WORKFLOW_ID
	    INNER JOIN AR_CUSTOMER C ON C.AR_CUSTOMER_ID = ACA.AR_CUSTOMER_ID
	    WHERE AT.AR_TRANSACTION_TYPE_ID = 14
	    AND F.CURRENT_STATUS_ID != 4
    UNION ALL
	SELECT AC.COMPANY_ID, C.NAME, AC.AR_CUSTOMER_ACCOUNT_ID, AC.AR_CUSTOMER_ID, 'AC' AS SOURCE, AC.AR_RECEIPT_ID AS ID,
		AC.MATURITY_DATE AS DATE, AC.RECEIPT_DATE, NULL AS DUE_DATE, CONCAT('AC-', AC.SEQUENCE_NO) AS REFERENCE_NUMBER,
		IF(AC.REF_NUMBER != '', CONCAT(AC.RECEIPT_NUMBER, ', ', AC.REF_NUMBER), AC.RECEIPT_NUMBER) AS INVOICE_NUMBER, 0 AS TRANSACTION_AMOUNT,
		AC.AMOUNT AS RECEIPT_AMOUNT, AC.CREATED_DATE, '' AS AR_LINE_ID, F.CURRENT_STATUS_ID, F.IS_COMPLETE, 1, 0 as TERM_DAYS, AC.SEQUENCE_NO AS AC_REF_NUMBER
		FROM AR_RECEIPT AC
		INNER JOIN FORM_WORKFLOW F ON AC.FORM_WORKFLOW_ID = F.FORM_WORKFLOW_ID
		INNER JOIN AR_CUSTOMER C ON C.AR_CUSTOMER_ID = AC.AR_CUSTOMER_ID
		WHERE F.CURRENT_STATUS_ID != 4 AND AC.AR_RECEIPT_ID NOT IN (
			SELECT ART.AR_RECEIPT_ID
			FROM AR_RECEIPT_TRANSACTION ART
			INNER JOIN AR_RECEIPT AR ON AR.AR_RECEIPT_ID = ART.AR_RECEIPT_ID
			INNER JOIN FORM_WORKFLOW F ON AR.FORM_WORKFLOW_ID = F.FORM_WORKFLOW_ID
			WHERE F.CURRENT_STATUS_ID != 4)
	UNION ALL
		SELECT AT.COMPANY_ID, C.NAME, AT.CUSTOMER_ACCOUNT_ID, AT.CUSTOMER_ID AS CUSTOMER_ID, 'TRANS' as SOURCE, AT.AR_TRANSACTION_ID as ID,
		AT.TRANSACTION_DATE AS DATE, AT.GL_DATE, AT.DUE_DATE AS DUE_DATE, AT.TRANSACTION_NUMBER as REFERENCE_NUMBER,
		DESCRIPTION AS INVOICE_NUMBER, AT.AMOUNT as TRANSACTION_AMOUNT, 
		COALESCE((SELECT SUM(RT.AMOUNT) FROM AR_RECEIPT_TRANSACTION RT
			INNER JOIN AR_RECEIPT AR ON AR.AR_RECEIPT_ID = RT.AR_RECEIPT_ID
			INNER JOIN FORM_WORKFLOW F ON AR.FORM_WORKFLOW_ID = F.FORM_WORKFLOW_ID
			WHERE RT.AR_TRANSACTION_ID=AT.AR_TRANSACTION_ID  AND F.CURRENT_STATUS_ID != 4), 0) as RECEIPT_AMOUNT,
		AT.CREATED_DATE, '' AS AR_LINE_ID, F.CURRENT_STATUS_ID as STATUS_ID, F.IS_COMPLETE as IS_COMPLETE, T.TERM_ID, T.DAYS as TERM_DAYS,
		(SELECT GROUP_CONCAT(CONCAT('AC-', ARR.SEQUENCE_NO) Separator ', ') FROM AR_RECEIPT ARR
			INNER JOIN AR_RECEIPT_TRANSACTION ARRT ON ARRT.AR_RECEIPT_ID = ARR.AR_RECEIPT_ID
			INNER JOIN AR_TRANSACTION AT1 ON AT1.AR_TRANSACTION_ID = ARRT.AR_TRANSACTION_ID
			INNER JOIN FORM_WORKFLOW ARR_FW ON ARR_FW.FORM_WORKFLOW_ID = ARR.FORM_WORKFLOW_ID
			WHERE AT1.AR_TRANSACTION_TYPE_ID = 17
			AND ARR_FW.CURRENT_STATUS_ID != 4
			AND AT1.AR_TRANSACTION_ID = AT.AR_TRANSACTION_ID) AS AC_REF_NUMBER
	FROM AR_TRANSACTION AT
	INNER JOIN AR_CUSTOMER_ACCOUNT ACA ON ACA.AR_CUSTOMER_ACCOUNT_ID = AT.CUSTOMER_ACCOUNT_ID
	INNER JOIN TERM T ON ACA.TERM_ID = T.TERM_ID
	INNER JOIN FORM_WORKFLOW F ON AT.FORM_WORKFLOW_ID = F.FORM_WORKFLOW_ID
	INNER JOIN AR_CUSTOMER C ON C.AR_CUSTOMER_ID = ACA.AR_CUSTOMER_ID
	WHERE F.CURRENT_STATUS_ID != 4 AND AT.AR_TRANSACTION_TYPE_ID = 17
	UNION ALL
		SELECT AT.COMPANY_ID, C.NAME, AT.CUSTOMER_ACCOUNT_ID, AT.CUSTOMER_ID AS CUSTOMER_ID, 'TRANS' as SOURCE, AT.AR_TRANSACTION_ID as ID,
		AT.TRANSACTION_DATE AS DATE, AT.GL_DATE, AT.DUE_DATE AS DUE_DATE, AT.TRANSACTION_NUMBER as REFERENCE_NUMBER,
		DESCRIPTION AS INVOICE_NUMBER, AT.AMOUNT as TRANSACTION_AMOUNT, 
		COALESCE((SELECT SUM(RT.AMOUNT) FROM AR_RECEIPT_TRANSACTION RT
			INNER JOIN AR_RECEIPT AR ON AR.AR_RECEIPT_ID = RT.AR_RECEIPT_ID
			INNER JOIN FORM_WORKFLOW F ON AR.FORM_WORKFLOW_ID = F.FORM_WORKFLOW_ID
			WHERE RT.AR_TRANSACTION_ID=AT.AR_TRANSACTION_ID  AND F.CURRENT_STATUS_ID != 4), 0) as RECEIPT_AMOUNT,
		AT.CREATED_DATE, '' AS AR_LINE_ID, F.CURRENT_STATUS_ID as STATUS_ID, F.IS_COMPLETE as IS_COMPLETE, T.TERM_ID, T.DAYS as TERM_DAYS,
		(SELECT GROUP_CONCAT(CONCAT('AC-', ARR.SEQUENCE_NO) Separator ', ') FROM AR_RECEIPT ARR
			INNER JOIN AR_RECEIPT_TRANSACTION ARRT ON ARRT.AR_RECEIPT_ID = ARR.AR_RECEIPT_ID
			INNER JOIN AR_TRANSACTION AT1 ON AT1.AR_TRANSACTION_ID = ARRT.AR_TRANSACTION_ID
			INNER JOIN FORM_WORKFLOW ARR_FW ON ARR_FW.FORM_WORKFLOW_ID = ARR.FORM_WORKFLOW_ID
			WHERE AT1.AR_TRANSACTION_TYPE_ID = 18
			AND ARR_FW.CURRENT_STATUS_ID != 4
			AND AT1.AR_TRANSACTION_ID = AT.AR_TRANSACTION_ID) AS AC_REF_NUMBER
	FROM AR_TRANSACTION AT
	INNER JOIN AR_CUSTOMER_ACCOUNT ACA ON ACA.AR_CUSTOMER_ACCOUNT_ID = AT.CUSTOMER_ACCOUNT_ID
	INNER JOIN TERM T ON ACA.TERM_ID = T.TERM_ID
	INNER JOIN FORM_WORKFLOW F ON AT.FORM_WORKFLOW_ID = F.FORM_WORKFLOW_ID
	INNER JOIN AR_CUSTOMER C ON C.AR_CUSTOMER_ID = ACA.AR_CUSTOMER_ID
	WHERE F.CURRENT_STATUS_ID != 4 AND AT.AR_TRANSACTION_TYPE_ID = 18;