-- Description View for transaction history


DROP VIEW IF EXISTS V_TRANSACTION_HISTORY;

CREATE VIEW V_TRANSACTION_HISTORY AS

-- Unpaid AR transaction/s
SELECT COM.COMPANY_ID, D.NAME AS DIVISION, D.DIVISION_ID,
(CASE WHEN T.TRANSACTION_CLASSIFICATION_ID = 1 THEN 'REG'
	WHEN T.TRANSACTION_CLASSIFICATION_ID = 2 THEN 'DM'
	WHEN T.TRANSACTION_CLASSIFICATION_ID = 3 THEN 'CM'
	WHEN T.TRANSACTION_CLASSIFICATION_ID = 4 THEN 'ARI' END) AS TYPE,
COM.NAME AS COMPANY_NAME, C.NAME AS CUSTOMER_NAME, CA.NAME AS CUSTOMER_ACCOUNT,
CONCAT(T.TRANSACTION_NUMBER, IF(T.DESCRIPTION IS NOT NULL AND T.DESCRIPTION != '', CONCAT(', ', T.DESCRIPTION), '')) AS TRANSACTION_NUMBER,
T.TRANSACTION_NUMBER AS TRANS_NUMBER, T.SEQUENCE_NO, (CASE WHEN T.TRANSACTION_CLASSIFICATION_ID = 7 THEN -T.AMOUNT ELSE T.AMOUNT END) AMOUNT,
0 AS PAID_AMOUNT, TRM.NAME AS TERM, (CASE WHEN T.DUE_DATE IS NULL THEN T.TRANSACTION_DATE ELSE T.DUE_DATE END) AS DUE_DATE,
T.TRANSACTION_DATE, (CASE WHEN T.GL_DATE IS NULL THEN T.TRANSACTION_DATE ELSE T.GL_DATE END) AS GL_DATE,
TRM.TERM_ID, T.AR_TRANSACTION_ID, T.TRANSACTION_CLASSIFICATION_ID, CA.AR_CUSTOMER_ACCOUNT_ID, C.AR_CUSTOMER_ID,
0 AS TOTAL_PAYMENT, FW.CURRENT_STATUS_ID, FS.DESCRIPTION AS STATUS, FW.IS_COMPLETE AS IS_POSTED,
IF(FW.CURRENT_STATUS_ID = 4, (SELECT FWL.COMMENT FROM FORM_WORKFLOW_LOG FWL WHERE FWL.FORM_WORKFLOW_ID = FW.FORM_WORKFLOW_ID AND FWL.FORM_STATUS_ID = 4) , '') AS CANCELLATION_REMARKS,
CONCAT('ART ', T.SEQUENCE_NO) AS FORMATTED_SEQUENCE_NO
FROM AR_TRANSACTION T
INNER JOIN AR_CUSTOMER C ON C.AR_CUSTOMER_ID=T.CUSTOMER_ID
INNER JOIN AR_CUSTOMER_ACCOUNT CA ON CA.AR_CUSTOMER_ACCOUNT_ID=T.CUSTOMER_ACCOUNT_ID
INNER JOIN TERM TRM ON TRM.TERM_ID=T.TERM_ID
INNER JOIN COMPANY COM ON COM.COMPANY_ID=T.COMPANY_ID
INNER JOIN DIVISION D ON D.DIVISION_ID=T.DIVISION_ID
INNER JOIN FORM_WORKFLOW FW ON FW.FORM_WORKFLOW_ID=T.FORM_WORKFLOW_ID
INNER JOIN FORM_STATUS FS ON FS.FORM_STATUS_ID=FW.CURRENT_STATUS_ID
WHERE T.AR_TRANSACTION_TYPE_ID IN (17, 18, 19, 20, 21, 22)
AND T.EB_OBJECT_ID NOT IN (
	SELECT OTO.FROM_OBJECT_ID FROM AR_RECEIPT_LINE ARL
	INNER JOIN OBJECT_TO_OBJECT OTO ON OTO.TO_OBJECT_ID = ARL.EB_OBJECT_ID
	INNER JOIN AR_RECEIPT ARR ON ARR.AR_RECEIPT_ID = ARL.AR_RECEIPT_ID
	INNER JOIN FORM_WORKFLOW FW ON FW.FORM_WORKFLOW_ID = ARR.FORM_WORKFLOW_ID
	WHERE FW.CURRENT_STATUS_ID != 4
)

UNION ALL

-- Partially and fully collected AR transaction/s
SELECT COM.COMPANY_ID, D.NAME AS DIVISION, D.DIVISION_ID,
(CASE WHEN T.TRANSACTION_CLASSIFICATION_ID = 1 THEN 'REG'
	WHEN T.TRANSACTION_CLASSIFICATION_ID = 2 THEN 'DM'
	WHEN T.TRANSACTION_CLASSIFICATION_ID = 3 THEN 'CM'
	WHEN T.TRANSACTION_CLASSIFICATION_ID = 4 THEN  'ARI' END) AS TYPE,
COM.NAME AS COMPANY_NAME,C.NAME AS CUSTOMER_NAME, CA.NAME AS CUSTOMER_ACCOUNT,
CONCAT(T.TRANSACTION_NUMBER, IF(T.DESCRIPTION IS NOT NULL AND T.DESCRIPTION != '', CONCAT(', ', T.DESCRIPTION), '')) AS TRANSACTION_NUMBER,
T.TRANSACTION_NUMBER AS TRANS_NUMBER, T.SEQUENCE_NO, T.AMOUNT, SUM(IF(ARR_FW.IS_COMPLETE = 1, ARL.AMOUNT, 0)) AS PAID_AMOUNT,
TRM.NAME AS TERM, (CASE WHEN T.DUE_DATE IS NULL THEN T.TRANSACTION_DATE ELSE T.DUE_DATE END) AS DUE_DATE,
T.TRANSACTION_DATE, (CASE WHEN T.GL_DATE IS NULL THEN T.TRANSACTION_DATE ELSE T.GL_DATE END) AS GL_DATE,
TRM.TERM_ID AS TERM_ID, T.AR_TRANSACTION_ID, T.TRANSACTION_CLASSIFICATION_ID, CA.AR_CUSTOMER_ACCOUNT_ID,
C.AR_CUSTOMER_ID, 0 AS TOTAL_PAYMENT, FW.CURRENT_STATUS_ID, FS.DESCRIPTION AS STATUS, FW.IS_COMPLETE AS IS_POSTED,
IF(FW.CURRENT_STATUS_ID = 4, (SELECT FWL.COMMENT FROM FORM_WORKFLOW_LOG FWL
	WHERE FWL.FORM_WORKFLOW_ID = FW.FORM_WORKFLOW_ID AND FWL.FORM_STATUS_ID = 4), '') AS CANCELLATION_REMARKS,
CONCAT('ART ', T.SEQUENCE_NO) AS FORMATTED_SEQUENCE_NO
FROM AR_TRANSACTION T
INNER JOIN AR_CUSTOMER C ON C.AR_CUSTOMER_ID=T.CUSTOMER_ID
INNER JOIN AR_CUSTOMER_ACCOUNT CA ON CA.AR_CUSTOMER_ACCOUNT_ID=T.CUSTOMER_ACCOUNT_ID
INNER JOIN TERM TRM ON TRM.TERM_ID=T.TERM_ID
INNER JOIN COMPANY COM ON COM.COMPANY_ID=T.COMPANY_ID
INNER JOIN DIVISION D ON D.DIVISION_ID=T.DIVISION_ID
INNER JOIN FORM_WORKFLOW FW ON FW.FORM_WORKFLOW_ID=T.FORM_WORKFLOW_ID
INNER JOIN FORM_STATUS FS ON FS.FORM_STATUS_ID=FW.CURRENT_STATUS_ID
INNER JOIN OBJECT_TO_OBJECT OTO ON OTO.FROM_OBJECT_ID = T.EB_OBJECT_ID
INNER JOIN AR_RECEIPT_LINE ARL ON ARL.EB_OBJECT_ID = OTO.TO_OBJECT_ID
INNER JOIN AR_RECEIPT ARR ON ARR.AR_RECEIPT_ID = ARL.AR_RECEIPT_ID
INNER JOIN FORM_WORKFLOW ARR_FW ON ARR_FW.FORM_WORKFLOW_ID = ARR.FORM_WORKFLOW_ID
WHERE ARR_FW.CURRENT_STATUS_ID != 4
AND OTO.OR_TYPE_ID = 24006
GROUP BY T.AR_TRANSACTION_ID

UNION ALL

-- Unpaid AR invoice/s
SELECT ARI.COMPANY_ID, D.NAME AS DIVISION, ARI.DIVISION_ID AS DIVISION_ID, 'ARI' AS TYPE, COM.NAME AS COMPANY_NAME,
C.NAME AS CUSTOMER_NAME, CA.NAME AS CUSTOMER_ACCOUNT, '' AS TRANSACTION_NUMBER, '' AS TRANS_NUMBER, ARI.SEQUENCE_NO,
ARI.AMOUNT, 0 AS PAID_AMOUNT, TRM.NAME AS TERM, ARI.DUE_DATE, ARI.DATE AS TRANSACTION_DATE,
IF(FW.IS_COMPLETE = 1, ARI.DATE_RECEIVED, ARI.DATE) AS GL_DATE, ARI.TERM_ID, ARI.AR_INVOICE_ID AS AR_TRANSACTION_ID,
4 AS TRANSACTION_CLASSIFICATION_ID, ARI.AR_CUSTOMER_ACCOUNT_ID, ARI.AR_CUSTOMER_ID, 0 AS TOTAL_PAYMENT,
FW.CURRENT_STATUS_ID, FS.DESCRIPTION AS STATUS, FW.IS_COMPLETE AS IS_POSTED,
IF(FW.CURRENT_STATUS_ID = 4, (SELECT FWL.COMMENT FROM FORM_WORKFLOW_LOG FWL WHERE FWL.FORM_WORKFLOW_ID = FW.FORM_WORKFLOW_ID AND FWL.FORM_STATUS_ID = 4) , '') AS CANCELLATION_REMARKS,
CONCAT('ARI ', ARI.SEQUENCE_NO) AS FORMATTED_SEQUENCE_NO
FROM AR_INVOICE ARI
INNER JOIN AR_CUSTOMER C ON C.AR_CUSTOMER_ID=ARI.AR_CUSTOMER_ID
INNER JOIN AR_CUSTOMER_ACCOUNT CA ON CA.AR_CUSTOMER_ACCOUNT_ID=ARI.AR_CUSTOMER_ACCOUNT_ID
INNER JOIN TERM TRM ON TRM.TERM_ID=ARI.TERM_ID
INNER JOIN COMPANY COM ON COM.COMPANY_ID=ARI.COMPANY_ID
INNER JOIN DIVISION D ON D.DIVISION_ID=ARI.DIVISION_ID
INNER JOIN FORM_WORKFLOW FW ON FW.FORM_WORKFLOW_ID=ARI.FORM_WORKFLOW_ID
INNER JOIN FORM_STATUS FS ON FS.FORM_STATUS_ID=FW.CURRENT_STATUS_ID
WHERE ARI.AMOUNT != 0
AND ARI.EB_OBJECT_ID NOT IN (
	SELECT OTO.FROM_OBJECT_ID FROM AR_RECEIPT_LINE ARL
	INNER JOIN OBJECT_TO_OBJECT OTO ON OTO.TO_OBJECT_ID = ARL.EB_OBJECT_ID
	INNER JOIN AR_RECEIPT ARR ON ARR.AR_RECEIPT_ID = ARL.AR_RECEIPT_ID
	INNER JOIN FORM_WORKFLOW ARR_FW ON ARR_FW.FORM_WORKFLOW_ID = ARR.FORM_WORKFLOW_ID
	WHERE ARR_FW.CURRENT_STATUS_ID != 4
)

UNION ALL

-- Partially and fully collected AR invoice/s
SELECT ARI.COMPANY_ID, D.NAME AS DIVISION, ARI.DIVISION_ID, 'ARI' AS TYPE, COM.NAME AS COMPANY_NAME,
C.NAME AS CUSTOMER_NAME, CA.NAME AS CUSTOMER_ACCOUNT, '' AS TRANSACTION_NUMBER, '' AS TRANS_NUMBER, ARI.SEQUENCE_NO,
ARI.AMOUNT, SUM(IF(ARR_FW.IS_COMPLETE = 1, ARL.AMOUNT, 0)) AS PAID_AMOUNT, TRM.NAME AS TERM, ARI.DUE_DATE,
ARI.DATE AS TRANSACTION_DATE, IF(FW.IS_COMPLETE = 1, ARI.DATE_RECEIVED, ARI.DATE) AS GL_DATE, ARI.TERM_ID,
ARI.AR_INVOICE_ID AS AR_TRANSACTION_ID, 4 AS TRANSACTION_CLASSIFICATION_ID, ARI.AR_CUSTOMER_ACCOUNT_ID,
ARI.AR_CUSTOMER_ID, 0 AS TOTAL_PAYMENT, FW.CURRENT_STATUS_ID, FS.DESCRIPTION AS STATUS, FW.IS_COMPLETE AS IS_POSTED,
IF(FW.CURRENT_STATUS_ID = 4, (SELECT FWL.COMMENT FROM FORM_WORKFLOW_LOG FWL WHERE FWL.FORM_WORKFLOW_ID = FW.FORM_WORKFLOW_ID AND FWL.FORM_STATUS_ID = 4) , '') AS CANCELLATION_REMARKS,
CONCAT('ARI ', ARI.SEQUENCE_NO) AS FORMATTED_SEQUENCE_NO
FROM AR_INVOICE ARI
INNER JOIN AR_CUSTOMER C ON C.AR_CUSTOMER_ID=ARI.AR_CUSTOMER_ID
INNER JOIN AR_CUSTOMER_ACCOUNT CA ON CA.AR_CUSTOMER_ACCOUNT_ID=ARI.AR_CUSTOMER_ACCOUNT_ID
INNER JOIN TERM TRM ON TRM.TERM_ID=ARI.TERM_ID
INNER JOIN COMPANY COM ON COM.COMPANY_ID=ARI.COMPANY_ID
INNER JOIN DIVISION D ON D.DIVISION_ID=ARI.DIVISION_ID
INNER JOIN FORM_WORKFLOW FW ON FW.FORM_WORKFLOW_ID=ARI.FORM_WORKFLOW_ID
INNER JOIN FORM_STATUS FS ON FS.FORM_STATUS_ID=FW.CURRENT_STATUS_ID
INNER JOIN OBJECT_TO_OBJECT OTO ON OTO.FROM_OBJECT_ID = ARI.EB_OBJECT_ID
INNER JOIN AR_RECEIPT_LINE ARL ON ARL.EB_OBJECT_ID = OTO.TO_OBJECT_ID
INNER JOIN AR_RECEIPT ARR ON ARR.AR_RECEIPT_ID = ARL.AR_RECEIPT_ID
INNER JOIN FORM_WORKFLOW ARR_FW ON ARR_FW.FORM_WORKFLOW_ID = ARR.FORM_WORKFLOW_ID
WHERE ARI.AMOUNT != 0
AND ARR_FW.CURRENT_STATUS_ID != 4
AND OTO.OR_TYPE_ID = 24006
GROUP BY ARI.AR_INVOICE_ID