

-- Description: sql update scripts for setting all monetary fields to DECIMAL(10,2) datatype.
ALTER TABLE `CBS`.`ACCOUNT_RECEIVABLE` CHANGE COLUMN `PRINCIPAL` `PRINCIPAL` DECIMAL(10,2) NOT NULL DEFAULT '0.00'  , CHANGE COLUMN `AMOUNT` `AMOUNT` DECIMAL(10,2) NOT NULL  , CHANGE COLUMN `EARNED_INTEREST` `EARNED_INTEREST` DECIMAL(10,2) NOT NULL;
ALTER TABLE `CBS`.`PAID_RECEIVABLE` CHANGE COLUMN `PAID_PRINCIPAL` `PAID_PRINCIPAL` DECIMAL(10,2) NOT NULL  , CHANGE COLUMN `PAID_INTEREST` `PAID_INTEREST` DECIMAL(10,2) NOT NULL;
ALTER TABLE `CBS`.`PAYMENT` CHANGE COLUMN `AMOUNT` `AMOUNT` DECIMAL(10,2) NOT NULL  , CHANGE COLUMN `PAYMENT_CHANGE` `PAYMENT_CHANGE` DECIMAL(10,2) NOT NULL;
ALTER TABLE `CBS`.`ACCOUNT_PAYABLE` CHANGE COLUMN `AMOUNT` `AMOUNT` DECIMAL(10,2) NOT NULL;
ALTER TABLE `CBS`.`CUSTOMER_ACCT_SETTING` CHANGE COLUMN `MAX_AMOUNT` `MAX_AMOUNT` DECIMAL(10,2) NOT NULL;
ALTER TABLE `CBS`.`EXPENSE` CHANGE COLUMN `AMOUNT` `AMOUNT` DECIMAL(10,2) NOT NULL;
ALTER TABLE `CBS`.`INVENTORY_STOCK` CHANGE COLUMN `UNIT_PRICE` `UNIT_PRICE` DECIMAL(10,2) NOT NULL;
ALTER TABLE `CBS`.`INV_ITEM_SP` CHANGE COLUMN `SELLING_PRICE` `SELLING_PRICE` DECIMAL(10,2) NOT NULL;

-- Description: sql update script for updating the function EARNED_INTEREST.
USE `CBS`;
DROP function IF EXISTS `EARNED_INTEREST`;

DELIMITER $$
USE `CBS`$$
CREATE DEFINER=`cmsadmin`@`%` FUNCTION `EARNED_INTEREST`(amount DOUBLE, interestRate DOUBLE, currentDate Date, dueDate Date) RETURNS double
BEGIN
		DECLARE earnedInterest DOUBLE;
		DECLARE multiplier DOUBLE;
		DECLARE dateDiff INT;
		SET multiplier = interestRate /100/365;
		IF dueDate >= currentDate THEN SET dateDiff = 0;
		ELSE SET dateDiff = DATEDIFF(currentDate,dueDate);
		END IF;
		SET earnedInterest = amount * multiplier * dateDiff;
		RETURN REPLACE(FORMAT(earnedInterest, 3), ',', '');
END$$

DELIMITER ;