

-- Description: sql script for adding DELETED column on EXPENSE_TYPE table.
ALTER TABLE `CBS`.`EXPENSE_TYPE` ADD COLUMN `DELETED` TINYINT(1) NOT NULL  AFTER `DESCRIPTION` ;

-- Description: sql script for adding foreign key constraints on EXPENSE table.
ALTER TABLE `CBS`.`EXPENSE` 
  ADD CONSTRAINT `FK_EXPENSE_COMPANY_ID`
  FOREIGN KEY (`COMPANY_ID` )
  REFERENCES `CBS`.`COMPANY` (`COMPANY_ID` )
  ON DELETE NO ACTION
  ON UPDATE NO ACTION, 
  ADD CONSTRAINT `FK_EXPENSE_EXPENSE_TYPE_ID`
  FOREIGN KEY (`EXPENSE_TYPE_ID` )
  REFERENCES `CBS`.`EXPENSE_TYPE` (`EXPENSE_TYPE_ID` )
  ON DELETE NO ACTION
  ON UPDATE NO ACTION
, ADD INDEX `FK_EXPENSE_COMPANY_ID` (`COMPANY_ID` ASC) 
, ADD INDEX `FK_EXPENSE_EXPENSE_TYPE_ID` (`EXPENSE_TYPE_ID` ASC) ;

