

-- Description: sql script in creating INVENTORY_SUPPLIER table
CREATE TABLE `INVENTORY_SUPPLIER` (
  `INVENTORY_SUPPLIER_ID` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `COMPANY_ID` int(10) unsigned NOT NULL,
  `NAME` varchar(50) NOT NULL,
  `ADDRESS` varchar(150) NOT NULL,
  `CONTACT_NUMBER` varchar(20) NOT NULL,
  `EMAIL_ADDRESS` varchar(50) NOT NULL,
  `ACTIVE` tinyint(1) NOT NULL,
  `DELETED` tinyint(1) NOT NULL,
  `CREATED_BY` int(10) unsigned NOT NULL,
  `CREATED_DATE` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_BY` int(10) unsigned NOT NULL,
  `UPDATED_DATE` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  PRIMARY KEY (`INVENTORY_SUPPLIER_ID`),
  KEY `FK_SUPPLIER_COMPANY_ID` (`COMPANY_ID`),
  CONSTRAINT `FK_SUPPLIER_COMPANY_ID` FOREIGN KEY (`COMPANY_ID`) REFERENCES `COMPANY` (`COMPANY_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=7 DEFAULT CHARSET=latin1