--
-- Get the monthly unpaid account receivable total amount per company.
--
delimiter //
CREATE DEFINER=`cmsadmin`@`%` PROCEDURE `getMonthlyUnpaidAcctReceivable`(IN companyId int,  IN month int, IN year int )
BEGIN
	DECLARE startDate DATE;
	DECLARE endDate DATE;
	DECLARE maxDay INTEGER;

	SELECT DAY(LAST_DAY(CONCAT(year,'-',month,'-01'))) INTO maxDay;

	SET startDate = CONCAT(year,'-',month,'-01');
	SET endDate = CONCAT(year,'-',month,'-',maxDay);

	SELECT COALESCE(SUM(EARNED_INTEREST(AR.AMOUNT, CAS.INTEREST_RATE, NOW(), AR.INTEREST_DATE) + 
	AR.AMOUNT + AR.EARNED_INTEREST),0)  FROM (SELECT * FROM CUSTOMER WHERE DELETED = 0) C LEFT JOIN 
	(SELECT * FROM ACCOUNT_RECEIVABLE WHERE DELETED = 0 AND PAID = 0) AR ON AR.CUSTOMER_ID = C.CUSTOMER_ID 
	LEFT JOIN (SELECT CUSTOMER_ID, INTEREST_RATE FROM CUSTOMER_ACCT_SETTING) CAS ON CAS.CUSTOMER_ID = C.CUSTOMER_ID 
	WHERE C.COMPANY_ID = companyId AND DATE BETWEEN startDate AND endDate ORDER BY C.NAME;
END //

--
-- Get the yearly unpaid account receivable total amount per company.
--
CREATE DEFINER=`cmsadmin`@`%` PROCEDURE `getYearlyUnpaidAcctReceivable`(IN companyId int,  IN year int)
BEGIN
	SELECT COALESCE(SUM(EARNED_INTEREST(AR.AMOUNT, CAS.INTEREST_RATE, NOW(), AR.INTEREST_DATE) + 
	AR.AMOUNT + AR.EARNED_INTEREST),0)  FROM (SELECT * FROM CUSTOMER WHERE DELETED = 0) C LEFT JOIN 
	(SELECT * FROM ACCOUNT_RECEIVABLE WHERE DELETED = 0 AND PAID = 0) AR ON AR.CUSTOMER_ID = C.CUSTOMER_ID 
	LEFT JOIN (SELECT CUSTOMER_ID, INTEREST_RATE FROM CUSTOMER_ACCT_SETTING) CAS ON CAS.CUSTOMER_ID = C.CUSTOMER_ID 
	WHERE C.COMPANY_ID = companyId AND YEAR(DUE_DATE) = year ORDER BY C.NAME;
END //

--
-- Get the unpaid account receivable total amount per company by date range.
--
CREATE DEFINER=`cmsadmin`@`%` PROCEDURE `getTotalUnpaidAcctReceivable`(IN companyId int,  IN startDate date, IN endDate date)
BEGIN

	IF (startDate IS NOT NULL) && (endDate IS NOT NULL) THEN
		SELECT COALESCE(SUM(EARNED_INTEREST(AR.AMOUNT, CAS.INTEREST_RATE, NOW(), AR.INTEREST_DATE) + 
		AR.AMOUNT + AR.EARNED_INTEREST),0)  FROM (SELECT * FROM CUSTOMER WHERE DELETED = 0) C LEFT JOIN 
		(SELECT * FROM ACCOUNT_RECEIVABLE WHERE DELETED = 0 AND PAID = 0) AR ON AR.CUSTOMER_ID = C.CUSTOMER_ID 
		LEFT JOIN (SELECT CUSTOMER_ID, INTEREST_RATE FROM CUSTOMER_ACCT_SETTING) CAS ON CAS.CUSTOMER_ID = C.CUSTOMER_ID 
		WHERE C.COMPANY_ID = companyId AND DATE BETWEEN startDate AND endDate ORDER BY C.NAME;
	ELSEIF (startDate IS NULL) THEN
		SELECT COALESCE(SUM(EARNED_INTEREST(AR.AMOUNT, CAS.INTEREST_RATE, NOW(), AR.INTEREST_DATE) + 
		AR.AMOUNT + AR.EARNED_INTEREST),0)  FROM (SELECT * FROM CUSTOMER WHERE DELETED = 0) C LEFT JOIN 
		(SELECT * FROM ACCOUNT_RECEIVABLE WHERE DELETED = 0 AND PAID = 0) AR ON AR.CUSTOMER_ID = C.CUSTOMER_ID 
		LEFT JOIN (SELECT CUSTOMER_ID, INTEREST_RATE FROM CUSTOMER_ACCT_SETTING) CAS ON CAS.CUSTOMER_ID = C.CUSTOMER_ID 
		WHERE C.COMPANY_ID = companyId AND DATE = endDate ORDER BY C.NAME;
	ELSEIF (endDate IS NULL) THEN
		SELECT COALESCE(SUM(EARNED_INTEREST(AR.AMOUNT, CAS.INTEREST_RATE, NOW(), AR.INTEREST_DATE) + 
		AR.AMOUNT + AR.EARNED_INTEREST),0)  FROM (SELECT * FROM CUSTOMER WHERE DELETED = 0) C LEFT JOIN 
		(SELECT * FROM ACCOUNT_RECEIVABLE WHERE DELETED = 0 AND PAID = 0) AR ON AR.CUSTOMER_ID = C.CUSTOMER_ID 
		LEFT JOIN (SELECT CUSTOMER_ID, INTEREST_RATE FROM CUSTOMER_ACCT_SETTING) CAS ON CAS.CUSTOMER_ID = C.CUSTOMER_ID 
		WHERE C.COMPANY_ID = companyId AND DATE = startDate ORDER BY C.NAME;
	END IF;
END //