
-- Description: sql update script for workflow data of ECT.

-- Delete the negotiable logs.
DELETE FROM FORM_WORKFLOW_LOG WHERE FORM_STATUS_ID = 15 AND 
FORM_WORKFLOW_ID IN (SELECT FORM_WORKFLOW_ID FROM AR_RECEIPT);

-- Set negotiable to received.
UPDATE FORM_WORKFLOW SET CURRENT_STATUS_ID = 7 WHERE CURRENT_STATUS_ID = 15 
AND FORM_WORKFLOW_ID IN (SELECT FORM_WORKFLOW_ID FROM AR_RECEIPT);