
-- Description: sql script in creating Inventory Item Selling Price table.
CREATE TABLE `INV_ITEM_SP` (
  `INV_ITEM_SP_ID` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `INVENTORY_ITEM_ID` int(10) unsigned NOT NULL,
  `SELLING_PRICE` double NOT NULL,
  `CREATED_BY` int(10) unsigned NOT NULL,
  `CREATED_DATE` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_BY` int(10) unsigned NOT NULL,
  `UPDATED_DATE` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  PRIMARY KEY (`INV_ITEM_SP_ID`),
  KEY `FK_INVENTORY_ITEM_ID` (`INVENTORY_ITEM_ID`),
  KEY `FK_IISP_CB_USER_ID` (`CREATED_BY`),
  KEY `FK_IISP_UB_USER_ID` (`UPDATED_BY`),  
  CONSTRAINT `FK_INVENTORY_ITEM_ID` FOREIGN KEY (`INVENTORY_ITEM_ID`) REFERENCES `INVENTORY_ITEM` (`INVENTORY_ITEM_ID`),
  CONSTRAINT `FK_IISP_CB_USER_ID` FOREIGN KEY (`CREATED_BY`) REFERENCES `USER` (`USER_ID`),
  CONSTRAINT `FK_IISP_UB_USER_ID` FOREIGN KEY (`UPDATED_BY`) REFERENCES `USER` (`USER_ID`)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1