
-- Description: update script for user company add user company head id.

ALTER TABLE USER_COMPANY ADD USER_COMPANY_HEAD_ID int(10) unsigned DEFAULT NULL AFTER COMPANY_ID,
 ADD  KEY `FK_USER_COMPANY_USER_COMPANY_HEAD_ID` (`USER_COMPANY_HEAD_ID`),
 ADD CONSTRAINT `FK_USER_COMPANY_USER_COMPANY_HEAD_ID` FOREIGN KEY (`USER_COMPANY_HEAD_ID`) 
    REFERENCES `USER_COMPANY_HEAD` (`USER_COMPANY_HEAD_ID`);