

-- Description: sql script in creating INVENTORY_ITEM table.
CREATE TABLE `INVENTORY_ITEM` (
  `INVENTORY_ITEM_ID` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `ITEM_CODE` varchar(50) NOT NULL,
  `COMPANY_ID` int(10) unsigned NOT NULL DEFAULT '1',
  `NAME` varchar(50) NOT NULL,
  `DESCRIPTION` varchar(250) NOT NULL,
  `ACTIVE` tinyint(1) NOT NULL,
  `DELETED` tinyint(1) NOT NULL,
  `CREATED_BY` int(10) unsigned NOT NULL,
  `CREATED_DATE` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_BY` int(10) unsigned NOT NULL,
  `UPDATED_DATE` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  PRIMARY KEY (`INVENTORY_ITEM_ID`),
  KEY `FK_ITEM_COMPANY_ID` (`COMPANY_ID`),
  CONSTRAINT `FK_ITEM_COMPANY_ID` FOREIGN KEY (`COMPANY_ID`) REFERENCES `COMPANY` (`COMPANY_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=30 DEFAULT CHARSET=latin1