
-- Description: Add DIVISION_ID in EMPLOYEE_LEAVE_CREDIT table.

ALTER TABLE EMPLOYEE_LEAVE_CREDIT ADD DIVISION_ID int(10) unsigned NOT NULL AFTER COMPANY_ID,
ADD CONSTRAINT FK_ELC_DIVISION_ID FOREIGN KEY (DIVISION_ID) REFERENCES DIVISION (DIVISION_ID);
