-- Description: Stored proceedure that will check if there is duplicate in the cash sale items.

Delimiter //
DROP procedure if exists CHECK_HAS_DUPLICATE;//
CREATE procedure CHECK_HAS_DUPLICATE (IN IN_CASH_SALE_ID INT)
BEGIN
	
DECLARE DISTINCT_COUNT INT;
DECLARE CSI_COUNT INT;
DECLARE GT_DISTINCT_COUNT INT;
DECLARE CASH_PAID DOUBLE;
DECLARE TOTAL_AMOUNT DOUBLE;
DECLARE GE_TOTAL_AMOUNT INT;
	
SELECT COUNT(DISTINCT ITEM_ID, WAREHOUSE_ID, QUANTITY, COALESCE (UNIT_COST, 0)) INTO DISTINCT_COUNT FROM CASH_SALE_ITEM WHERE CASH_SALE_ID = IN_CASH_SALE_ID;
SELECT COUNT(*) INTO CSI_COUNT FROM CASH_SALE_ITEM WHERE CASH_SALE_ID = IN_CASH_SALE_ID;

IF CSI_COUNT > DISTINCT_COUNT THEN
	SELECT 1 INTO GT_DISTINCT_COUNT;
ELSE
	SELECT 0 INTO GT_DISTINCT_COUNT;
END IF;

SELECT CASH INTO CASH_PAID FROM CASH_SALE WHERE CASH_SALE_ID = IN_CASH_SALE_ID;
SELECT SUM(AMOUNT) INTO TOTAL_AMOUNT FROM CASH_SALE_ITEM WHERE CASH_SALE_ID = IN_CASH_SALE_ID;

IF CASH_PAID >= TOTAL_AMOUNT THEN
	SELECT 0 INTO GE_TOTAL_AMOUNT;
ELSE
	SELECT 1 INTO GE_TOTAL_AMOUNT;
END IF;
 
IF GT_DISTINCT_COUNT = 1 AND GE_TOTAL_AMOUNT = 1 THEN
	SELECT 1;
ELSE
	SELECT 0;
END IF;

END//
