-- Description: Stored procedure that will get the petty cash voucher liquidation register

Delimiter //
DROP PROCEDURE IF EXISTS GET_PETTY_CASH_LIQUIDATION_REGISTER;
CREATE PROCEDURE GET_PETTY_CASH_LIQUIDATION_REGISTER(IN IN_COMPANY_ID INT, IN IN_DIVISION_ID INT, IN IN_CUSTODIAN_ID INT,
IN IN_REQUESTOR_NAME TEXT, IN IN_DATE_FROM DATE, IN IN_DATE_TO DATE, IN IN_TRANSACTION_STATUS INT,
IN IN_LIMIT_FROM INT, IN IN_LIMIT_TO INT )

BEGIN
SELECT PCVL_DATE, DIVISION, PCV, PCVLI , CUSTODIAN, REQUESTOR, REFERENCE, AMOUNT, CASH_RETURNED, DESCRIPTION, CANCELLATION_REMARKS FROM (

SELECT PCVL_DATE, D.NAME AS DIVISION, PCV.SEQUENCE_NO AS PCV, PCVL.SEQUENCE_NO AS PCVLI,
CA.CUSTODIAN_NAME AS CUSTODIAN, PCVL.REQUESTOR, PCVL.REFERENCE_NO AS REFERENCE, PCVL.AMOUNT,
PCVL.CASH_RETURNED, FS.DESCRIPTION, FW.CURRENT_STATUS_ID,
IF(FW.CURRENT_STATUS_ID = 4, (SELECT FWL.COMMENT FROM FORM_WORKFLOW_LOG FWL
WHERE FWL.FORM_WORKFLOW_ID = FW.FORM_WORKFLOW_ID AND FWL.FORM_STATUS_ID = 4) , '') AS CANCELLATION_REMARKS
FROM PETTY_CASH_VOUCHER_LIQUIDATION PCVL
INNER JOIN PETTY_CASH_VOUCHER PCV ON PCV.PETTY_CASH_VOUCHER_ID = PCVL.PETTY_CASH_VOUCHER_ID
INNER JOIN DIVISION D ON PCVL.DIVISION_ID = D.DIVISION_ID
INNER JOIN USER_CUSTODIAN UC ON PCVL.USER_CUSTODIAN_ID = UC.USER_CUSTODIAN_ID
INNER JOIN CUSTODIAN_ACCOUNT CA ON CA.CUSTODIAN_ACCOUNT_ID = UC.CUSTODIAN_ACCOUNT_ID
INNER JOIN FORM_WORKFLOW FW ON PCVL.FORM_WORKFLOW_ID = FW.FORM_WORKFLOW_ID
INNER JOIN FORM_STATUS FS ON FW.CURRENT_STATUS_ID = FS.FORM_STATUS_ID
WHERE PCVL.COMPANY_ID = IN_COMPANY_ID
AND IF(IN_DIVISION_ID != -1, PCVL.DIVISION_ID = IN_DIVISION_ID, PCVL.DIVISION_ID != IN_DIVISION_ID)
AND PCVL.PCVL_DATE BETWEEN IN_DATE_FROM AND IN_DATE_TO
AND IF(IN_CUSTODIAN_ID != -1, CA.CUSTODIAN_ACCOUNT_ID = IN_CUSTODIAN_ID, CA.CUSTODIAN_ACCOUNT_ID != IN_CUSTODIAN_ID)
AND IF(IN_TRANSACTION_STATUS != -1, FW.CURRENT_STATUS_ID = IN_TRANSACTION_STATUS, FW.CURRENT_STATUS_ID != IN_TRANSACTION_STATUS)
AND PCVL.REQUESTOR LIKE IN_REQUESTOR_NAME

) AS TBL_PCVL_REGISTER;
END //