-- Description: Stored proceedure for coc tax withheld at source by filters.


DELIMITER //
DROP PROCEDURE IF EXISTS GET_COC_TAXWITHELD_AT_SOURCE;//
CREATE PROCEDURE GET_COC_TAXWITHELD_AT_SOURCE (IN IN_COMPANY_ID INT, IN IN_DIVISION_ID INT,
IN IN_DATE_FROM DATE, IN IN_DATE_TO DATE)
BEGIN

SELECT DATE, CUSTOMER, ATC_CODE, NATURE_OF_PAYMENT, TAX_BASE, TAX_RATE, TAX_AMOUNT FROM (

SELECT ARI.DATE_RECEIVED AS DATE, ARI.COMPANY_ID, ARI.DIVISION_ID, ARC.NAME AS CUSTOMER,
BA.DESCRIPTION AS NATURE_OF_PAYMENT, BA.NAME AS ATC_CODE,
COALESCE((SELECT SUM(SI.AMOUNT) FROM SERIAL_ITEM SI INNER JOIN OBJECT_TO_OBJECT OTO ON OTO.TO_OBJECT_ID = SI.EB_OBJECT_ID
	WHERE OTO.FROM_OBJECT_ID = ARI.EB_OBJECT_ID AND OTO.OR_TYPE_ID = 12006 AND SI.ACTIVE = 1), 0)
+ COALESCE((SELECT SUM(ARII.AMOUNT) FROM AR_INVOICE_ITEM ARII WHERE ARII.AR_INVOICE_ID = ARI.AR_INVOICE_ID), 0)
+ COALESCE((SELECT SUM(ARIL.AMOUNT) FROM AR_INVOICE_LINE ARIL WHERE ARIL.AR_INVOICE_ID = ARI.AR_INVOICE_ID), 0) AS TAX_BASE,
WAS.VALUE AS TAX_RATE, ARI.WT_AMOUNT AS TAX_AMOUNT
FROM AR_INVOICE ARI
INNER JOIN FORM_WORKFLOW FW ON FW.FORM_WORKFLOW_ID = ARI.FORM_WORKFLOW_ID
INNER JOIN WT_ACCOUNT_SETTING WAS ON WAS.WT_ACCOUNT_SETTING_ID = ARI.WT_ACCOUNT_SETTING_ID
INNER JOIN AR_CUSTOMER ARC ON ARC.AR_CUSTOMER_ID = ARI.AR_CUSTOMER_ID
INNER JOIN BIR_ATC BA ON BA.BIR_ATC_ID = WAS.BIR_ATC_ID
WHERE FW.IS_COMPLETE = 1
AND WAS.WT_TYPE_ID = 0
AND IF(IN_COMPANY_ID != -1, ARI.COMPANY_ID = IN_COMPANY_ID, ARI.COMPANY_ID != IN_COMPANY_ID)
AND IF(IN_DIVISION_ID != -1, ARI.DIVISION_ID = IN_DIVISION_ID, ARI.DIVISION_ID != IN_DIVISION_ID)
AND IF(IN_DATE_FROM IS NOT NULL AND IN_DATE_TO IS NOT NULL, ARI.DATE_RECEIVED BETWEEN IN_DATE_FROM AND IN_DATE_TO, ARI.DATE_RECEIVED IS NOT NULL)
GROUP BY ARI.AR_INVOICE_ID

UNION ALL

SELECT ART.TRANSACTION_DATE AS DATE, ART.COMPANY_ID, ART.DIVISION_ID, ARC.NAME AS CUSTOMER,
BA.DESCRIPTION AS NATURE_OF_PAYMENT, BA.NAME AS ATC_CODE, SUM(ASL.AMOUNT) AS TAX_BASE,
WAS.VALUE AS TAX_RATE, ART.WT_AMOUNT AS TAX_AMOUNT
FROM AR_SERVICE_LINE ASL
INNER JOIN AR_TRANSACTION ART ON ART.AR_TRANSACTION_ID = ASL.AR_TRANSACTION_ID
INNER JOIN FORM_WORKFLOW FW ON FW.FORM_WORKFLOW_ID = ART.FORM_WORKFLOW_ID
INNER JOIN WT_ACCOUNT_SETTING WAS ON WAS.WT_ACCOUNT_SETTING_ID = ART.WT_ACCOUNT_SETTING_ID
INNER JOIN AR_CUSTOMER ARC ON ARC.AR_CUSTOMER_ID = ART.CUSTOMER_ID
INNER JOIN BIR_ATC BA ON BA.BIR_ATC_ID = WAS.BIR_ATC_ID
WHERE FW.IS_COMPLETE = 1
AND WAS.WT_TYPE_ID = 0
AND IF(IN_COMPANY_ID != -1, ART.COMPANY_ID = IN_COMPANY_ID, ART.COMPANY_ID != IN_COMPANY_ID)
AND IF(IN_DIVISION_ID != -1, ART.DIVISION_ID = IN_DIVISION_ID, ART.DIVISION_ID != IN_DIVISION_ID)
AND IF(IN_DATE_FROM IS NOT NULL AND IN_DATE_TO IS NOT NULL, ART.GL_DATE BETWEEN IN_DATE_FROM AND IN_DATE_TO, ART.GL_DATE IS NOT NULL)
GROUP BY ART.AR_TRANSACTION_ID

UNION ALL

SELECT AM.RECEIPT_DATE AS DATE, AM.COMPANY_ID, AM.DIVISION_ID, AC.NAME AS CUSTOMER,
BA.DESCRIPTION AS NATURE_OF_PAYMENT, BA.NAME AS ATC_CODE, SUM(AML.AMOUNT) AS TAX_BASE,
WAS.VALUE AS TAX_RATE, AM.WT_AMOUNT AS TAX_AMOUNT
FROM AR_MISCELLANEOUS_LINE AML
INNER JOIN AR_MISCELLANEOUS AM ON AML.AR_MISCELLANEOUS_ID = AM.AR_MISCELLANEOUS_ID
INNER JOIN AR_CUSTOMER AC ON AC.AR_CUSTOMER_ID = AM.AR_CUSTOMER_ID
INNER JOIN WT_ACCOUNT_SETTING WAS ON WAS.WT_ACCOUNT_SETTING_ID = AM.WT_ACCOUNT_SETTING_ID
INNER JOIN BIR_ATC BA ON BA.BIR_ATC_ID = WAS.BIR_ATC_ID
INNER JOIN FORM_WORKFLOW FW ON FW.FORM_WORKFLOW_ID = AM.FORM_WORKFLOW_ID
WHERE FW.IS_COMPLETE
AND WAS.WT_TYPE_ID = 0
AND IF(IN_COMPANY_ID != -1, AM.COMPANY_ID = IN_COMPANY_ID, AM.COMPANY_ID != IN_COMPANY_ID)
AND IF(IN_DIVISION_ID != -1, AM.DIVISION_ID = IN_DIVISION_ID, AM.DIVISION_ID != IN_DIVISION_ID)
AND IF(IN_DATE_FROM IS NOT NULL AND IN_DATE_TO IS NOT NULL, AM.MATURITY_DATE BETWEEN IN_DATE_FROM AND IN_DATE_TO, AM.MATURITY_DATE IS NOT NULL)
GROUP BY AM.AR_MISCELLANEOUS_ID

) AS COC_TAX_WITHHELD ORDER BY DATE;
END//
