-- Description: Stored proceedure that will the sales delivery efficiency by filters. 

DELIMITER //
DROP procedure IF EXISTS GET_SALES_DELIVERY_EFFICIENCY;//
CREATE procedure GET_SALES_DELIVERY_EFFICIENCY (IN IN_COMPANY_ID INT, IN IN_DIVISION_ID INT, IN IN_CUSTOMER_ID INT, IN IN_DATE_FROM DATE, IN IN_DATE_TO DATE)
BEGIN

SELECT TBL.DIVISION_ID, TBL.DIVISION_NAME, TBL.AR_CUSTOMER_ID, TBL.AR_CUSTOMER_NAME, TBL.STOCK_CODE, TBL.DESCRIPTION, TBL.PO_NUMBER, TBL.DR_REF_NUMBER,
TBL.QUANTITY, TBL.DELIVERY_STATUS, TBL.DELIVERY_DATE, TBL.DATE_RECEIVED, TBL.DELIVERY_RECEIPT_ID FROM (

SELECT D.DIVISION_ID, D.NAME AS DIVISION_NAME, AC.AR_CUSTOMER_ID, AC.NAME AS AR_CUSTOMER_NAME, I.STOCK_CODE, I.DESCRIPTION,
SO.PO_NUMBER, DR.DR_REF_NUMBER, SI.QUANTITY, 'Full Delivery' AS DELIVERY_STATUS, SO.DELIVERY_DATE, DR.DATE_RECEIVED, DR.DELIVERY_RECEIPT_ID
FROM SERIAL_ITEM SI
INNER JOIN OBJECT_TO_OBJECT OTO ON OTO.TO_OBJECT_ID = SI.EB_OBJECT_ID
INNER JOIN DELIVERY_RECEIPT DR ON DR.EB_OBJECT_ID = OTO.FROM_OBJECT_ID
INNER JOIN SALES_ORDER SO ON SO.SALES_ORDER_ID = DR.SALES_ORDER_ID
INNER JOIN SALES_ORDER_ITEM SOI ON SOI.SALES_ORDER_ID = SO.SALES_ORDER_ID
INNER JOIN ITEM I ON I.ITEM_ID = SI.ITEM_ID
INNER JOIN DIVISION D ON D.DIVISION_ID = SO.DIVISION_ID
INNER JOIN AR_CUSTOMER AC ON AC.AR_CUSTOMER_ID = SO.AR_CUSTOMER_ID
INNER JOIN FORM_WORKFLOW FW ON FW.FORM_WORKFLOW_ID = DR.FORM_WORKFLOW_ID
WHERE FW.IS_COMPLETE
AND IF(IN_COMPANY_ID != -1, DR.COMPANY_ID = IN_COMPANY_ID, DR.COMPANY_ID != IN_COMPANY_ID)
AND IF(IN_DIVISION_ID != -1, DR.DIVISION_ID = IN_DIVISION_ID, DR.DIVISION_ID != IN_DIVISION_ID)
AND IF(IN_CUSTOMER_ID != -1, DR.AR_CUSTOMER_ID = IN_CUSTOMER_ID, DR.AR_CUSTOMER_ID != IN_CUSTOMER_ID)
AND (DR.DATE_RECEIVED BETWEEN IN_DATE_FROM AND IN_DATE_TO)
GROUP BY SI.SERIAL_ITEM_ID, DR.DELIVERY_RECEIPT_ID

UNION ALL

SELECT D.DIVISION_ID, D.NAME AS DIVISION_NAME, AC.AR_CUSTOMER_ID, AC.NAME AS AR_CUSTOMER_NAME, I.STOCK_CODE, I.DESCRIPTION,
SO.PO_NUMBER, DR.DR_REF_NUMBER, DRI.QUANTITY,
IF(SOI.QUANTITY = (SELECT SUM(DRI2.QUANTITY) FROM DELIVERY_RECEIPT_ITEM DRI2
INNER JOIN DELIVERY_RECEIPT DR2 ON DR2.DELIVERY_RECEIPT_ID = DRI2.DELIVERY_RECEIPT_ID
INNER JOIN FORM_WORKFLOW FW2 ON FW2.FORM_WORKFLOW_ID = DR2.FORM_WORKFLOW_ID
WHERE IS_COMPLETE AND DR2.SALES_ORDER_ID = SO.SALES_ORDER_ID AND DRI2.ITEM_ID = DRI.ITEM_ID AND DR2.DELIVERY_RECEIPT_ID <= DR.DELIVERY_RECEIPT_ID),
 'Full Delivery', 'Partial Delivery') AS DELIVERY_STATUS, SO.DELIVERY_DATE, DR.DATE_RECEIVED, DR.DELIVERY_RECEIPT_ID
FROM DELIVERY_RECEIPT_ITEM DRI
INNER JOIN DELIVERY_RECEIPT DR ON DR.DELIVERY_RECEIPT_ID = DRI.DELIVERY_RECEIPT_ID
INNER JOIN SALES_ORDER SO ON SO.SALES_ORDER_ID = DR.SALES_ORDER_ID
INNER JOIN SALES_ORDER_ITEM SOI ON SOI.SALES_ORDER_ID = SO.SALES_ORDER_ID
INNER JOIN ITEM I ON I.ITEM_ID = DRI.ITEM_ID
INNER JOIN DIVISION D ON D.DIVISION_ID = SO.DIVISION_ID
INNER JOIN AR_CUSTOMER AC ON AC.AR_CUSTOMER_ID = SO.AR_CUSTOMER_ID
INNER JOIN FORM_WORKFLOW FW ON FW.FORM_WORKFLOW_ID = DR.FORM_WORKFLOW_ID
WHERE FW.IS_COMPLETE
AND SOI.ITEM_ID NOT IN(SELECT ITEM_ID FROM SERIAL_ITEM_SETUP WHERE SERIALIZED_ITEM = 1)
AND IF(IN_COMPANY_ID != -1, DR.COMPANY_ID = IN_COMPANY_ID, DR.COMPANY_ID != IN_COMPANY_ID)
AND IF(IN_DIVISION_ID != -1, DR.DIVISION_ID = IN_DIVISION_ID, DR.DIVISION_ID != IN_DIVISION_ID)
AND IF(IN_CUSTOMER_ID != -1, DR.AR_CUSTOMER_ID = IN_CUSTOMER_ID, DR.AR_CUSTOMER_ID != IN_CUSTOMER_ID)
AND (DR.DATE_RECEIVED BETWEEN IN_DATE_FROM AND IN_DATE_TO)
GROUP BY DRI.DELIVERY_RECEIPT_ITEM_ID, DR.DELIVERY_RECEIPT_ID

UNION ALL

SELECT D.DIVISION_ID, D.NAME AS DIVISION_NAME, AC.AR_CUSTOMER_ID, AC.NAME AS AR_CUSTOMER_NAME, SS.NAME, DRL.DESCRIPTION,
SO.PO_NUMBER, DR.DR_REF_NUMBER, DRL.QUANTITY,
IF(SOL.QUANTITY = (SELECT SUM(DRL2.QUANTITY) FROM DELIVERY_RECEIPT_LINE DRL2
INNER JOIN DELIVERY_RECEIPT DR2 ON DR2.DELIVERY_RECEIPT_ID = DRL2.DELIVERY_RECEIPT_ID
INNER JOIN FORM_WORKFLOW FW2 ON FW2.FORM_WORKFLOW_ID = DR2.FORM_WORKFLOW_ID
WHERE IS_COMPLETE AND DR2.SALES_ORDER_ID = SO.SALES_ORDER_ID AND DRL2.SERVICE_SETTING_ID = DRL.SERVICE_SETTING_ID AND DR2.DELIVERY_RECEIPT_ID <= DR.DELIVERY_RECEIPT_ID),
 'Full Delivery', 'Partial Delivery') AS DELIVERY_STATUS, SO.DELIVERY_DATE, DR.DATE_RECEIVED, DR.DELIVERY_RECEIPT_ID
FROM DELIVERY_RECEIPT_LINE DRL
INNER JOIN DELIVERY_RECEIPT DR ON DR.DELIVERY_RECEIPT_ID = DRL.DELIVERY_RECEIPT_ID
INNER JOIN SERVICE_SETTING SS ON SS.SERVICE_SETTING_ID = DRL.SERVICE_SETTING_ID
INNER JOIN SALES_ORDER SO ON SO.SALES_ORDER_ID = DR.SALES_ORDER_ID
INNER JOIN SALES_ORDER_LINE SOL ON SOL.SALES_ORDER_ID = DR.SALES_ORDER_ID
INNER JOIN DIVISION D ON D.DIVISION_ID = SO.DIVISION_ID
INNER JOIN AR_CUSTOMER AC ON AC.AR_CUSTOMER_ID = SO.AR_CUSTOMER_ID
INNER JOIN FORM_WORKFLOW FW ON FW.FORM_WORKFLOW_ID = DR.FORM_WORKFLOW_ID
WHERE FW.IS_COMPLETE
AND IF(IN_COMPANY_ID != -1, DR.COMPANY_ID = IN_COMPANY_ID, DR.COMPANY_ID != IN_COMPANY_ID)
AND IF(IN_DIVISION_ID != -1, DR.DIVISION_ID = IN_DIVISION_ID, DR.DIVISION_ID != IN_DIVISION_ID)
AND IF(IN_CUSTOMER_ID != -1, DR.AR_CUSTOMER_ID = IN_CUSTOMER_ID, DR.AR_CUSTOMER_ID != IN_CUSTOMER_ID)
AND (DR.DATE_RECEIVED BETWEEN IN_DATE_FROM AND IN_DATE_TO)
GROUP BY DRL.DELIVERY_RECEIPT_LINE_ID, DR.DELIVERY_RECEIPT_ID

) as TBL ORDER BY TBL.DIVISION_NAME, TBL.DATE_RECEIVED, TBL.DELIVERY_RECEIPT_ID;
END//
