-- Description View for daily petty cash fund report


Delimiter //
DROP PROCEDURE IF EXISTS GET_DAILY_PETTY_CASH_FUND_REPORT; //

CREATE PROCEDURE GET_DAILY_PETTY_CASH_FUND_REPORT(IN IN_COMPANY_ID INT, IN_DIVISION_ID INT,IN_USER_CUSTODIAN_ACCOUNT_ID INT, IN IN_PCV_DATE DATE,
IN IN_CURRENT_STATUS_ID INT, IN IN_LIMIT_FROM INT, IN IN_LIMIT_TO INT)

BEGIN

SELECT DIVISION, CUSTODIAN_NAME, PCV_NUMBER, REQUESTOR, REFERENCE_NO, DESCRIPTION, AMOUNT, STATUS, TOTAL_LIQUIDATION FROM (

SELECT PCV.PETTY_CASH_VOUCHER_ID, C.COMPANY_ID, C.NAME AS COMPANY, D.DIVISION_ID, D.NAME AS DIVISION,
CA.CUSTODIAN_ACCOUNT_ID, CA.CUSTODIAN_NAME, PCV.SEQUENCE_NO AS PCV_NUMBER, PCV.REQUESTOR,
PCV.REFERENCE_NO, PCV.DESCRIPTION, PCV.AMOUNT, FW.CURRENT_STATUS_ID, FS.DESCRIPTION AS STATUS,
PCV.PCV_DATE, COALESCE((SELECT SUM(PCVL.AMOUNT - PCVL.CASH_RETURNED) FROM PETTY_CASH_VOUCHER_LIQUIDATION PCVL
INNER JOIN FORM_WORKFLOW PCVL_FW ON PCVL_FW.FORM_WORKFLOW_ID = PCVL.FORM_WORKFLOW_ID
WHERE PCVL_FW.IS_COMPLETE = 1 AND PCVL.PETTY_CASH_VOUCHER_ID = PCV.PETTY_CASH_VOUCHER_ID), 0) AS TOTAL_LIQUIDATION
FROM PETTY_CASH_VOUCHER PCV
INNER JOIN COMPANY C ON C.COMPANY_ID = PCV.COMPANY_ID
INNER JOIN DIVISION D ON D.DIVISION_ID = PCV.DIVISION_ID
INNER JOIN USER_CUSTODIAN UC ON UC.USER_CUSTODIAN_ID = PCV.USER_CUSTODIAN_ID
INNER JOIN CUSTODIAN_ACCOUNT CA ON CA.CUSTODIAN_ACCOUNT_ID = UC.CUSTODIAN_ACCOUNT_ID
INNER JOIN FORM_WORKFLOW FW ON FW.FORM_WORKFLOW_ID = PCV.FORM_WORKFLOW_ID
INNER JOIN FORM_STATUS FS ON FS.FORM_STATUS_ID = FW.CURRENT_STATUS_ID
WHERE FW.CURRENT_STATUS_ID != 4
AND C.COMPANY_ID = IN_COMPANY_ID
AND PCV.PCV_DATE = IN_PCV_DATE
AND (CASE WHEN IN_DIVISION_ID != -1 THEN PCV.DIVISION_ID = IN_DIVISION_ID ELSE PCV.DIVISION_ID != IN_DIVISION_ID END)
AND (CASE WHEN IN_USER_CUSTODIAN_ACCOUNT_ID != -1 THEN UC.USER_CUSTODIAN_ID = IN_USER_CUSTODIAN_ACCOUNT_ID ELSE UC.USER_CUSTODIAN_ID != IN_USER_CUSTODIAN_ACCOUNT_ID END)
AND (CASE WHEN IN_CURRENT_STATUS_ID != -1 THEN FW.CURRENT_STATUS_ID = IN_CURRENT_STATUS_ID ELSE FW.CURRENT_STATUS_ID != IN_CURRENT_STATUS_ID END)

) AS TBL;
END //