-- Description: Stored proceedure that will get the contra account.

Delimiter //
DROP procedure IF EXISTS GET_CONTRA_ACCOUNT;//
CREATE procedure GET_CONTRA_ACCOUNT (IN IN_COMPANY_ID INT, IN IN_ACCOUNT_ID INT, 
IN IN_FROM_GL_DATE DATE, IN IN_TO_GL_DATE DATE)
BEGIN 
-- General Ledger
-- Debit and credit of GL
SELECT A.ACCOUNT_ID, A.ACCOUNT_NAME, sum(DEBIT) as DEBIT, sum(CREDIT) as CREDIT FROM (
SELECT AC.ACCOUNT_ID, ACCT.ACCOUNT_NAME, SUM(GLE.AMOUNT) as DEBIT, 0 as CREDIT
FROM GL_ENTRY GLE
INNER JOIN GENERAL_LEDGER GL ON GL.GENERAL_LEDGER_ID = GLE.GENERAL_LEDGER_ID
INNER JOIN ACCOUNT_COMBINATION AC ON AC.ACCOUNT_COMBINATION_ID = GLE.ACCOUNT_COMBINATION_ID
INNER JOIN ACCOUNT ACCT ON ACCT.ACCOUNT_ID = AC.ACCOUNT_ID
INNER JOIN FORM_WORKFLOW FW ON FW.FORM_WORKFLOW_ID = GL.FORM_WORKFLOW_ID
INNER JOIN FORM_WORKFLOW_LOG FWL ON FWL.FORM_WORKFLOW_ID = FW.FORM_WORKFLOW_ID
WHERE FW.CURRENT_STATUS_ID !=4 
AND FWL.FORM_STATUS_ID=6
AND IS_DEBIT = 1
AND AC.COMPANY_ID = IN_COMPANY_ID
AND ACCT.RELATED_ACCOUNT_ID = IN_ACCOUNT_ID
-- AND ACCT.RELATED_ACCOUNT_ID IS NOT NULL
AND GL.GL_DATE BETWEEN IN_FROM_GL_DATE and IN_TO_GL_DATE 
GROUP BY AC.ACCOUNT_ID

UNION ALL

SELECT AC.ACCOUNT_ID, ACCT.ACCOUNT_NAME, 0 as DEBIT, SUM(GLE.AMOUNT) as CREDIT
FROM GL_ENTRY GLE
INNER JOIN GENERAL_LEDGER GL ON GL.GENERAL_LEDGER_ID = GLE.GENERAL_LEDGER_ID
INNER JOIN ACCOUNT_COMBINATION AC ON AC.ACCOUNT_COMBINATION_ID = GLE.ACCOUNT_COMBINATION_ID
INNER JOIN ACCOUNT ACCT ON ACCT.ACCOUNT_ID = AC.ACCOUNT_ID
INNER JOIN FORM_WORKFLOW FW ON GL.FORM_WORKFLOW_ID = FW.FORM_WORKFLOW_ID
INNER JOIN FORM_WORKFLOW_LOG FWL ON FW.FORM_WORKFLOW_ID = FWL.FORM_WORKFLOW_ID
WHERE FW.CURRENT_STATUS_ID != 4
AND FWL.FORM_STATUS_ID = 6
AND IS_DEBIT = 0
AND AC.COMPANY_ID = IN_COMPANY_ID
AND ACCT.RELATED_ACCOUNT_ID = IN_ACCOUNT_ID
-- AND ACCT.RELATED_ACCOUNT_ID IS NOT NULL
AND GL.GL_DATE BETWEEN IN_FROM_GL_DATE and IN_TO_GL_DATE 
GROUP BY AC.ACCOUNT_ID
UNION ALL
-- AP Invoice DEBIT and CREDIT
SELECT AC.ACCOUNT_ID, ACCT.ACCOUNT_NAME, 0 as DEBIT, SUM(AI.AMOUNT) as CREDIT
FROM AP_INVOICE AI 
INNER JOIN SUPPLIER_ACCOUNT SA ON SA.SUPPLIER_ACCOUNT_ID = AI.SUPPLIER_ACCOUNT_ID
INNER JOIN ACCOUNT_COMBINATION AC ON AC.ACCOUNT_COMBINATION_ID = SA.DEFAULT_CREDIT_AC_ID
INNER JOIN ACCOUNT ACCT ON ACCT.ACCOUNT_ID = AC.ACCOUNT_ID
INNER JOIN FORM_WORKFLOW FW ON AI.FORM_WORKFLOW_ID = FW.FORM_WORKFLOW_ID
INNER JOIN FORM_WORKFLOW_LOG FWL ON FW.FORM_WORKFLOW_ID = FWL.FORM_WORKFLOW_ID
WHERE FW.CURRENT_STATUS_ID != 4
AND FWL.FORM_STATUS_ID = 3
AND AI.AMOUNT >= 0
AND AC.COMPANY_ID = IN_COMPANY_ID
AND ACCT.RELATED_ACCOUNT_ID = IN_ACCOUNT_ID
AND AI.GL_DATE BETWEEN IN_FROM_GL_DATE and IN_TO_GL_DATE 
GROUP BY AC.ACCOUNT_ID
UNION ALL

SELECT AC.ACCOUNT_ID, ACCT.ACCOUNT_NAME, SUM(-AI.AMOUNT) as DEBIT, 0 as CREDIT
FROM AP_INVOICE AI 
INNER JOIN SUPPLIER_ACCOUNT SA ON SA.SUPPLIER_ACCOUNT_ID = AI.SUPPLIER_ACCOUNT_ID
INNER JOIN ACCOUNT_COMBINATION AC ON AC.ACCOUNT_COMBINATION_ID = SA.DEFAULT_CREDIT_AC_ID
INNER JOIN ACCOUNT ACCT ON ACCT.ACCOUNT_ID = AC.ACCOUNT_ID
INNER JOIN FORM_WORKFLOW FW ON AI.FORM_WORKFLOW_ID = FW.FORM_WORKFLOW_ID
INNER JOIN FORM_WORKFLOW_LOG FWL ON FW.FORM_WORKFLOW_ID = FWL.FORM_WORKFLOW_ID
WHERE FW.CURRENT_STATUS_ID != 4
AND FWL.FORM_STATUS_ID = 3
AND AI.AMOUNT < 0
AND AC.COMPANY_ID = IN_COMPANY_ID
AND ACCT.RELATED_ACCOUNT_ID = IN_ACCOUNT_ID
AND AI.GL_DATE BETWEEN IN_FROM_GL_DATE and IN_TO_GL_DATE 
GROUP BY AC.ACCOUNT_ID
UNION ALL

-- AP LINE Debit and CREDIT

SELECT AC.ACCOUNT_ID, ACCT.ACCOUNT_NAME, SUM(AL.AMOUNT) AS DEBIT, 0 as CREDIT 
FROM AP_LINE AL
INNER JOIN AP_INVOICE AI ON AI.AP_INVOICE_ID = AL.AP_INVOICE_ID
INNER JOIN ACCOUNT_COMBINATION AC ON AC.ACCOUNT_COMBINATION_ID = AL.ACCOUNT_COMBINATION_ID
INNER JOIN ACCOUNT ACCT ON ACCT.ACCOUNT_ID = AC.ACCOUNT_ID
INNER JOIN FORM_WORKFLOW FW ON AI.FORM_WORKFLOW_ID = FW.FORM_WORKFLOW_ID
INNER JOIN FORM_WORKFLOW_LOG FWL ON FW.FORM_WORKFLOW_ID = FWL.FORM_WORKFLOW_ID
WHERE FW.CURRENT_STATUS_ID != 4
AND FWL.FORM_STATUS_ID = 3
AND AL.AMOUNT >= 0
AND AC.COMPANY_ID = IN_COMPANY_ID
AND ACCT.RELATED_ACCOUNT_ID = IN_ACCOUNT_ID
AND AI.GL_DATE BETWEEN IN_FROM_GL_DATE and IN_TO_GL_DATE 
GROUP BY AC.ACCOUNT_ID
UNION ALL 

SELECT AC.ACCOUNT_ID, ACCT.ACCOUNT_NAME, 0 AS DEBIT, SUM(-AL.AMOUNT) as CREDIT 
FROM AP_LINE AL
INNER JOIN AP_INVOICE AI ON AI.AP_INVOICE_ID = AL.AP_INVOICE_ID
INNER JOIN ACCOUNT_COMBINATION AC ON AC.ACCOUNT_COMBINATION_ID = AL.ACCOUNT_COMBINATION_ID
INNER JOIN ACCOUNT ACCT ON ACCT.ACCOUNT_ID = AC.ACCOUNT_ID
INNER JOIN FORM_WORKFLOW FW ON AI.FORM_WORKFLOW_ID = FW.FORM_WORKFLOW_ID
INNER JOIN FORM_WORKFLOW_LOG FWL ON FW.FORM_WORKFLOW_ID = FWL.FORM_WORKFLOW_ID
WHERE FW.CURRENT_STATUS_ID != 4
AND FWL.FORM_STATUS_ID = 3
AND AL.AMOUNT < 0
AND AC.COMPANY_ID = IN_COMPANY_ID
AND ACCT.RELATED_ACCOUNT_ID = IN_ACCOUNT_ID
AND AI.GL_DATE BETWEEN IN_FROM_GL_DATE and IN_TO_GL_DATE 
GROUP BY AC.ACCOUNT_ID
UNION ALL
-- AP Payment
-- Credit
SELECT AC.ACCOUNT_ID, ACCT.ACCOUNT_NAME, 0 AS DEBIT, SUM(AP.AMOUNT) as CREDIT 
FROM AP_PAYMENT AP
INNER JOIN BANK_ACCOUNT BA ON BA.BANK_ACCOUNT_ID=AP.BANK_ACCOUNT_ID
INNER JOIN ACCOUNT_COMBINATION AC ON AC.ACCOUNT_COMBINATION_ID = BA.CASH_IN_BANK_ACCT_ID
INNER JOIN ACCOUNT ACCT ON ACCT.ACCOUNT_ID = AC.ACCOUNT_ID
INNER JOIN FORM_WORKFLOW FW ON AP.FORM_WORKFLOW_ID = FW.FORM_WORKFLOW_ID
WHERE FW.CURRENT_STATUS_ID != 4
AND AP.AMOUNT != 0
AND AC.COMPANY_ID = IN_COMPANY_ID
AND ACCT.RELATED_ACCOUNT_ID = IN_ACCOUNT_ID
AND AP.CHECK_DATE BETWEEN IN_FROM_GL_DATE and IN_TO_GL_DATE 
GROUP BY AC.ACCOUNT_ID
UNION ALL
-- Credit - AP INVOICE
SELECT AC.ACCOUNT_ID, ACCT.ACCOUNT_NAME, 0 AS DEBIT, SUM(-AI.PAID_AMOUNT) as CREDIT
FROM AP_PAYMENT_INVOICE AI
INNER JOIN AP_PAYMENT AP ON AP.AP_PAYMENT_ID = AI.AP_PAYMENT_ID
INNER JOIN SUPPLIER_ACCOUNT SA ON SA.SUPPLIER_ACCOUNT_ID = AP.SUPPLIER_ACCOUNT_ID
INNER JOIN ACCOUNT_COMBINATION AC ON AC.ACCOUNT_COMBINATION_ID = SA.DEFAULT_CREDIT_AC_ID
INNER JOIN ACCOUNT ACCT ON ACCT.ACCOUNT_ID = AC.ACCOUNT_ID
INNER JOIN FORM_WORKFLOW FW ON AP.FORM_WORKFLOW_ID = FW.FORM_WORKFLOW_ID
WHERE FW.CURRENT_STATUS_ID != 4
AND AI.PAID_AMOUNT < 0
AND AC.COMPANY_ID = IN_COMPANY_ID
AND ACCT.RELATED_ACCOUNT_ID = IN_ACCOUNT_ID
AND AP.CHECK_DATE BETWEEN IN_FROM_GL_DATE and IN_TO_GL_DATE 
GROUP BY AC.ACCOUNT_ID
UNION ALL

-- Debit
SELECT AC.ACCOUNT_ID, ACCT.ACCOUNT_NAME, SUM(AI.PAID_AMOUNT) AS DEBIT, 0 as CREDIT
FROM AP_PAYMENT_INVOICE AI
INNER JOIN AP_PAYMENT AP ON AP.AP_PAYMENT_ID = AI.AP_PAYMENT_ID
INNER JOIN SUPPLIER_ACCOUNT SA ON SA.SUPPLIER_ACCOUNT_ID = AP.SUPPLIER_ACCOUNT_ID
INNER JOIN ACCOUNT_COMBINATION AC ON AC.ACCOUNT_COMBINATION_ID = SA.DEFAULT_CREDIT_AC_ID
INNER JOIN ACCOUNT ACCT ON ACCT.ACCOUNT_ID = AC.ACCOUNT_ID
INNER JOIN FORM_WORKFLOW FW ON AP.FORM_WORKFLOW_ID = FW.FORM_WORKFLOW_ID
WHERE FW.CURRENT_STATUS_ID != 4
AND AI.PAID_AMOUNT >= 0
AND AC.COMPANY_ID = IN_COMPANY_ID
AND ACCT.RELATED_ACCOUNT_ID = IN_ACCOUNT_ID
AND AP.CHECK_DATE BETWEEN IN_FROM_GL_DATE and IN_TO_GL_DATE 
GROUP BY AC.ACCOUNT_ID
UNION ALL
-- AR MISCELLANEOUS
-- Debit debit account combination
SELECT AC.ACCOUNT_ID, ACCT.ACCOUNT_NAME, SUM(AM.AMOUNT) AS DEBIT, 0 as CREDIT
FROM AR_MISCELLANEOUS AM
INNER JOIN RECEIPT_METHOD RM ON RM.RECEIPT_METHOD_ID = AM.RECEIPT_METHOD_ID
INNER JOIN ACCOUNT_COMBINATION AC ON AC.ACCOUNT_COMBINATION_ID = RM.DEBIT_ACCOUNT_COMBINATION_ID
INNER JOIN ACCOUNT ACCT ON ACCT.ACCOUNT_ID = AC.ACCOUNT_ID
INNER JOIN FORM_WORKFLOW FW ON AM.FORM_WORKFLOW_ID = FW.FORM_WORKFLOW_ID
WHERE FW.CURRENT_STATUS_ID != 4
AND RM.DEBIT_ACCOUNT_COMBINATION_ID IS NOT NULL
AND AC.COMPANY_ID = IN_COMPANY_ID
AND ACCT.RELATED_ACCOUNT_ID = IN_ACCOUNT_ID
AND AM.MATURITY_DATE BETWEEN IN_FROM_GL_DATE and IN_TO_GL_DATE 
GROUP BY AC.ACCOUNT_ID
-- Debit, bank account
UNION ALL 
SELECT AC.ACCOUNT_ID, ACCT.ACCOUNT_NAME, SUM(AM.AMOUNT) AS DEBIT, 0 as CREDIT
FROM AR_MISCELLANEOUS AM
INNER JOIN RECEIPT_METHOD RM ON RM.RECEIPT_METHOD_ID = AM.RECEIPT_METHOD_ID
INNER JOIN BANK_ACCOUNT BA ON BA.BANK_ACCOUNT_ID = RM.BANK_ACCOUNT_ID
INNER JOIN ACCOUNT_COMBINATION AC ON AC.ACCOUNT_COMBINATION_ID = BA.CASH_IN_BANK_ACCT_ID
INNER JOIN ACCOUNT ACCT ON ACCT.ACCOUNT_ID = AC.ACCOUNT_ID
INNER JOIN FORM_WORKFLOW FW ON AM.FORM_WORKFLOW_ID = FW.FORM_WORKFLOW_ID
WHERE FW.CURRENT_STATUS_ID != 4
AND RM.BANK_ACCOUNT_ID IS NOT NULL
AND AC.COMPANY_ID = IN_COMPANY_ID
AND ACCT.RELATED_ACCOUNT_ID = IN_ACCOUNT_ID
AND AM.MATURITY_DATE BETWEEN IN_FROM_GL_DATE and IN_TO_GL_DATE 
GROUP BY AC.ACCOUNT_ID
UNION ALL
-- Debit
SELECT AC.ACCOUNT_ID, ACCT.ACCOUNT_NAME, SUM(-AML.AMOUNT) AS DEBIT, 0 as CREDIT
FROM AR_MISCELLANEOUS_LINE AML
INNER JOIN AR_MISCELLANEOUS AM ON AM.AR_MISCELLANEOUS_ID = AML.AR_MISCELLANEOUS_ID
INNER JOIN AR_LINE_SETUP ALS ON ALS.AR_LINE_SETUP_ID = AML.AR_LINE_SETUP_ID
INNER JOIN ACCOUNT_COMBINATION AC ON AC.ACCOUNT_COMBINATION_ID = ALS.ACCOUNT_COMBINATION_ID
INNER JOIN ACCOUNT ACCT ON ACCT.ACCOUNT_ID = AC.ACCOUNT_ID
INNER JOIN FORM_WORKFLOW FW ON AM.FORM_WORKFLOW_ID = FW.FORM_WORKFLOW_ID
WHERE FW.CURRENT_STATUS_ID != 4
AND AML.AMOUNT < 0
AND AC.COMPANY_ID = IN_COMPANY_ID
AND ACCT.RELATED_ACCOUNT_ID = IN_ACCOUNT_ID
AND AM.MATURITY_DATE BETWEEN IN_FROM_GL_DATE and IN_TO_GL_DATE 
GROUP BY AC.ACCOUNT_ID
UNION ALL
-- Credit
SELECT AC.ACCOUNT_ID, ACCT.ACCOUNT_NAME, 0 AS DEBIT, SUM(AML.AMOUNT) as CREDIT
FROM AR_MISCELLANEOUS_LINE AML
INNER JOIN AR_MISCELLANEOUS AM ON AM.AR_MISCELLANEOUS_ID = AML.AR_MISCELLANEOUS_ID
INNER JOIN AR_LINE_SETUP ALS ON ALS.AR_LINE_SETUP_ID = AML.AR_LINE_SETUP_ID
INNER JOIN ACCOUNT_COMBINATION AC ON AC.ACCOUNT_COMBINATION_ID = ALS.ACCOUNT_COMBINATION_ID
INNER JOIN ACCOUNT ACCT ON ACCT.ACCOUNT_ID = AC.ACCOUNT_ID
INNER JOIN FORM_WORKFLOW FW ON AM.FORM_WORKFLOW_ID = FW.FORM_WORKFLOW_ID
WHERE FW.CURRENT_STATUS_ID != 4
AND AML.AMOUNT >= 0
AND AC.COMPANY_ID = IN_COMPANY_ID
AND ACCT.RELATED_ACCOUNT_ID = IN_ACCOUNT_ID
AND AM.MATURITY_DATE BETWEEN IN_FROM_GL_DATE and IN_TO_GL_DATE 
GROUP BY AC.ACCOUNT_ID
UNION ALL
-- AR Transaction
-- Debit
SELECT AC.ACCOUNT_ID, ACCT.ACCOUNT_NAME, SUM(AT.AMOUNT) AS DEBIT, 0 as CREDIT
FROM AR_TRANSACTION AT
INNER JOIN AR_CUSTOMER_ACCOUNT ACA ON ACA.AR_CUSTOMER_ACCOUNT_ID = AT.CUSTOMER_ACCOUNT_ID
INNER JOIN ACCOUNT_COMBINATION AC ON AC.ACCOUNT_COMBINATION_ID = ACA.DEFAULT_DEBIT_AC_ID
INNER JOIN ACCOUNT ACCT ON ACCT.ACCOUNT_ID = AC.ACCOUNT_ID
INNER JOIN FORM_WORKFLOW FW ON AT.FORM_WORKFLOW_ID = FW.FORM_WORKFLOW_ID
WHERE FW.CURRENT_STATUS_ID = 17
AND AT.AMOUNT >= 0
AND AC.COMPANY_ID = IN_COMPANY_ID
AND ACCT.RELATED_ACCOUNT_ID = IN_ACCOUNT_ID
AND AT.GL_DATE BETWEEN IN_FROM_GL_DATE and IN_TO_GL_DATE 
GROUP BY AC.ACCOUNT_ID
UNION ALL
-- Credit
SELECT AC.ACCOUNT_ID, ACCT.ACCOUNT_NAME, 0 AS DEBIT, SUM(-AT.AMOUNT) as CREDIT
FROM AR_TRANSACTION AT
INNER JOIN AR_CUSTOMER_ACCOUNT ACA ON ACA.AR_CUSTOMER_ACCOUNT_ID = AT.CUSTOMER_ACCOUNT_ID
INNER JOIN ACCOUNT_COMBINATION AC ON AC.ACCOUNT_COMBINATION_ID = ACA.DEFAULT_DEBIT_AC_ID
INNER JOIN ACCOUNT ACCT ON ACCT.ACCOUNT_ID = AC.ACCOUNT_ID
INNER JOIN FORM_WORKFLOW FW ON AT.FORM_WORKFLOW_ID = FW.FORM_WORKFLOW_ID
WHERE FW.CURRENT_STATUS_ID = 17
AND AT.AMOUNT < 0
AND AC.COMPANY_ID = IN_COMPANY_ID
AND ACCT.RELATED_ACCOUNT_ID = IN_ACCOUNT_ID
AND AT.GL_DATE BETWEEN IN_FROM_GL_DATE and IN_TO_GL_DATE 
GROUP BY AC.ACCOUNT_ID
UNION ALL
-- AR LINE
-- Credit
SELECT AC.ACCOUNT_ID, ACCT.ACCOUNT_NAME, 0 AS DEBIT, SUM(AL.AMOUNT) as CREDIT
FROM AR_LINE AL
INNER JOIN AR_TRANSACTION AT ON AT.AR_TRANSACTION_ID=AL.AR_TRANSACTION_ID
INNER JOIN AR_LINE_SETUP ALS ON ALS.AR_LINE_SETUP_ID = AL.AR_LINE_SETUP_ID
INNER JOIN ACCOUNT_COMBINATION AC ON AC.ACCOUNT_COMBINATION_ID = ALS.ACCOUNT_COMBINATION_ID
INNER JOIN ACCOUNT ACCT ON ACCT.ACCOUNT_ID = AC.ACCOUNT_ID
INNER JOIN FORM_WORKFLOW FW ON AT.FORM_WORKFLOW_ID = FW.FORM_WORKFLOW_ID
WHERE FW.CURRENT_STATUS_ID = 17
AND AL.AMOUNT >= 0
AND AC.COMPANY_ID = IN_COMPANY_ID
AND ACCT.RELATED_ACCOUNT_ID = IN_ACCOUNT_ID
AND AT.GL_DATE BETWEEN IN_FROM_GL_DATE and IN_TO_GL_DATE 
GROUP BY AC.ACCOUNT_ID
UNION ALL
-- Debit
SELECT AC.ACCOUNT_ID, ACCT.ACCOUNT_NAME, SUM(-AL.AMOUNT) AS DEBIT, 0 as CREDIT
FROM AR_LINE AL
INNER JOIN AR_TRANSACTION AT ON AT.AR_TRANSACTION_ID=AL.AR_TRANSACTION_ID
INNER JOIN AR_LINE_SETUP ALS ON ALS.AR_LINE_SETUP_ID = AL.AR_LINE_SETUP_ID
INNER JOIN ACCOUNT_COMBINATION AC ON AC.ACCOUNT_COMBINATION_ID = ALS.ACCOUNT_COMBINATION_ID
INNER JOIN ACCOUNT ACCT ON ACCT.ACCOUNT_ID = AC.ACCOUNT_ID
INNER JOIN FORM_WORKFLOW FW ON AT.FORM_WORKFLOW_ID = FW.FORM_WORKFLOW_ID
WHERE FW.CURRENT_STATUS_ID = 17
AND AL.AMOUNT < 0
AND AC.COMPANY_ID = IN_COMPANY_ID
AND ACCT.RELATED_ACCOUNT_ID = IN_ACCOUNT_ID
AND AT.GL_DATE BETWEEN IN_FROM_GL_DATE and IN_TO_GL_DATE 
GROUP BY AC.ACCOUNT_ID
UNION ALL
-- AR Receipt - not cancelled and  Maturity Date

-- Debit
-- RECEIPT_ID
-- RECEIPT_METHOD
-- Either from DEBIT_ACCOUNT_COMBINATION_ID or BANK_ACCOUNT_ID
SELECT AC.ACCOUNT_ID, ACCT.ACCOUNT_NAME, SUM(AR.AMOUNT) AS DEBIT, 0 as CREDIT
FROM AR_RECEIPT AR
INNER JOIN RECEIPT_METHOD RM ON RM.RECEIPT_METHOD_ID = AR.RECEIPT_METHOD_ID
INNER JOIN ACCOUNT_COMBINATION AC ON AC.ACCOUNT_COMBINATION_ID = RM.DEBIT_ACCOUNT_COMBINATION_ID
INNER JOIN ACCOUNT ACCT ON ACCT.ACCOUNT_ID = AC.ACCOUNT_ID
INNER JOIN FORM_WORKFLOW FW ON AR.FORM_WORKFLOW_ID = FW.FORM_WORKFLOW_ID
WHERE FW.CURRENT_STATUS_ID != 4
AND AR.AMOUNT != 0
AND RM.DEBIT_ACCOUNT_COMBINATION_ID IS NOT NULL
AND AC.COMPANY_ID = IN_COMPANY_ID
AND ACCT.RELATED_ACCOUNT_ID = IN_ACCOUNT_ID
AND AR.MATURITY_DATE BETWEEN IN_FROM_GL_DATE and IN_TO_GL_DATE 
GROUP BY AC.ACCOUNT_ID
-- Debit Bank account
UNION ALL
SELECT AC.ACCOUNT_ID, ACCT.ACCOUNT_NAME, SUM(AR.AMOUNT) AS DEBIT, 0 as CREDIT
FROM AR_RECEIPT AR
INNER JOIN RECEIPT_METHOD RM ON RM.RECEIPT_METHOD_ID = AR.RECEIPT_METHOD_ID
INNER JOIN BANK_ACCOUNT BA ON BA.BANK_ACCOUNT_ID = RM.BANK_ACCOUNT_ID
INNER JOIN ACCOUNT_COMBINATION AC ON AC.ACCOUNT_COMBINATION_ID = BA.CASH_IN_BANK_ACCT_ID
INNER JOIN ACCOUNT ACCT ON ACCT.ACCOUNT_ID = AC.ACCOUNT_ID
INNER JOIN FORM_WORKFLOW FW ON AR.FORM_WORKFLOW_ID = FW.FORM_WORKFLOW_ID
WHERE FW.CURRENT_STATUS_ID != 4
AND AR.AMOUNT != 0
AND RM.BANK_ACCOUNT_ID IS NOT NULL
AND AC.COMPANY_ID = IN_COMPANY_ID
AND ACCT.RELATED_ACCOUNT_ID = IN_ACCOUNT_ID
AND AR.MATURITY_DATE BETWEEN IN_FROM_GL_DATE and IN_TO_GL_DATE 
GROUP BY AC.ACCOUNT_ID
UNION ALL
-- Credit
-- RECEIPT_ID
-- RECEIPT_METHOD
-- CREDIT_ACCOUNT_COMBINATION_ID
SELECT AC.ACCOUNT_ID, ACCT.ACCOUNT_NAME, 0 AS DEBIT, SUM(AR.AMOUNT) as CREDIT
FROM AR_RECEIPT AR
INNER JOIN RECEIPT_METHOD RM ON RM.RECEIPT_METHOD_ID = AR.RECEIPT_METHOD_ID
INNER JOIN ACCOUNT_COMBINATION AC ON AC.ACCOUNT_COMBINATION_ID = RM.CREDIT_ACCOUNT_COMBINATION_ID
INNER JOIN ACCOUNT ACCT ON ACCT.ACCOUNT_ID = AC.ACCOUNT_ID
INNER JOIN FORM_WORKFLOW FW ON AR.FORM_WORKFLOW_ID = FW.FORM_WORKFLOW_ID
WHERE FW.CURRENT_STATUS_ID != 4
AND AR.AMOUNT != 0
AND AC.COMPANY_ID = IN_COMPANY_ID
AND ACCT.RELATED_ACCOUNT_ID = IN_ACCOUNT_ID
AND AR.MATURITY_DATE BETWEEN IN_FROM_GL_DATE and IN_TO_GL_DATE 
GROUP BY AC.ACCOUNT_ID
UNION ALL
-- AR Transaction
-- if amount is positive
-- Debit
-- AR_RECEIPT_TRANSACTION.AR_RECEIPT_ID->AR_RECEIPT.RECEIPT_ID->RECEIPT_METHOD.CREDIT_ACCOUNT_COMBINATION_ID
SELECT AC.ACCOUNT_ID, ACCT.ACCOUNT_NAME, SUM(ART.AMOUNT) AS DEBIT, 0 as CREDIT
FROM AR_RECEIPT_TRANSACTION ART
INNER JOIN AR_RECEIPT AR ON AR.AR_RECEIPT_ID = ART.AR_RECEIPT_ID
INNER JOIN RECEIPT_METHOD RM ON RM.RECEIPT_METHOD_ID = AR.RECEIPT_METHOD_ID
INNER JOIN ACCOUNT_COMBINATION AC ON AC.ACCOUNT_COMBINATION_ID = RM.CREDIT_ACCOUNT_COMBINATION_ID
INNER JOIN ACCOUNT ACCT ON ACCT.ACCOUNT_ID = AC.ACCOUNT_ID
INNER JOIN FORM_WORKFLOW FW ON AR.FORM_WORKFLOW_ID = FW.FORM_WORKFLOW_ID
WHERE FW.CURRENT_STATUS_ID != 4
AND ART.AMOUNT >= 0
AND AC.COMPANY_ID = IN_COMPANY_ID
AND ACCT.RELATED_ACCOUNT_ID = IN_ACCOUNT_ID
AND AR.MATURITY_DATE BETWEEN IN_FROM_GL_DATE and IN_TO_GL_DATE 
GROUP BY AC.ACCOUNT_ID
UNION ALL

SELECT AC.ACCOUNT_ID, ACCT.ACCOUNT_NAME, 0 AS DEBIT, SUM(-ART.AMOUNT) as CREDIT
FROM AR_RECEIPT_TRANSACTION ART
INNER JOIN AR_RECEIPT AR ON AR.AR_RECEIPT_ID = ART.AR_RECEIPT_ID
INNER JOIN RECEIPT_METHOD RM ON RM.RECEIPT_METHOD_ID = AR.RECEIPT_METHOD_ID
INNER JOIN ACCOUNT_COMBINATION AC ON AC.ACCOUNT_COMBINATION_ID = RM.CREDIT_ACCOUNT_COMBINATION_ID
INNER JOIN ACCOUNT ACCT ON ACCT.ACCOUNT_ID = AC.ACCOUNT_ID
INNER JOIN FORM_WORKFLOW FW ON AR.FORM_WORKFLOW_ID = FW.FORM_WORKFLOW_ID
WHERE FW.CURRENT_STATUS_ID != 4
AND ART.AMOUNT < 0
AND AC.COMPANY_ID = IN_COMPANY_ID
AND ACCT.RELATED_ACCOUNT_ID = IN_ACCOUNT_ID
AND AR.MATURITY_DATE BETWEEN IN_FROM_GL_DATE and IN_TO_GL_DATE 
GROUP BY AC.ACCOUNT_ID
UNION ALL

-- Credit
-- AR_RECEIPT_TRANSACTION.AR_RECEIPT_ID->AR_RECEIPT.AR_CUSTOMER_ACCOUNT_ID->AR_CUSTOMER_ACCOUNT.DEFAULT_DEBIT_AC_ID
-- if negative, reverse the debit and credit.
SELECT AC.ACCOUNT_ID, ACCT.ACCOUNT_NAME, 0 AS DEBIT, SUM(ART.AMOUNT) as CREDIT
FROM AR_RECEIPT_TRANSACTION ART
INNER JOIN AR_RECEIPT AR ON AR.AR_RECEIPT_ID = ART.AR_RECEIPT_ID
INNER JOIN AR_CUSTOMER_ACCOUNT ACA ON ACA.AR_CUSTOMER_ACCOUNT_ID = AR.AR_CUSTOMER_ACCOUNT_ID
INNER JOIN ACCOUNT_COMBINATION AC ON AC.ACCOUNT_COMBINATION_ID = ACA.DEFAULT_DEBIT_AC_ID
INNER JOIN ACCOUNT ACCT ON ACCT.ACCOUNT_ID = AC.ACCOUNT_ID
INNER JOIN FORM_WORKFLOW FW ON AR.FORM_WORKFLOW_ID = FW.FORM_WORKFLOW_ID
WHERE FW.CURRENT_STATUS_ID != 4
AND ART.AMOUNT >= 0
AND AC.COMPANY_ID = IN_COMPANY_ID
AND ACCT.RELATED_ACCOUNT_ID = IN_ACCOUNT_ID
AND AR.MATURITY_DATE BETWEEN IN_FROM_GL_DATE and IN_TO_GL_DATE 
GROUP BY AC.ACCOUNT_ID
UNION ALL

SELECT AC.ACCOUNT_ID, ACCT.ACCOUNT_NAME, SUM(-ART.AMOUNT) AS DEBIT, 0 as CREDIT
FROM AR_RECEIPT_TRANSACTION ART
INNER JOIN AR_RECEIPT AR ON AR.AR_RECEIPT_ID = ART.AR_RECEIPT_ID
INNER JOIN AR_CUSTOMER_ACCOUNT ACA ON ACA.AR_CUSTOMER_ACCOUNT_ID = AR.AR_CUSTOMER_ACCOUNT_ID
INNER JOIN ACCOUNT_COMBINATION AC ON AC.ACCOUNT_COMBINATION_ID = ACA.DEFAULT_DEBIT_AC_ID
INNER JOIN ACCOUNT ACCT ON ACCT.ACCOUNT_ID = AC.ACCOUNT_ID
INNER JOIN FORM_WORKFLOW FW ON AR.FORM_WORKFLOW_ID = FW.FORM_WORKFLOW_ID
WHERE FW.CURRENT_STATUS_ID != 4
AND ART.AMOUNT < 0
AND AC.COMPANY_ID = IN_COMPANY_ID
AND ACCT.RELATED_ACCOUNT_ID = IN_ACCOUNT_ID
AND AR.MATURITY_DATE BETWEEN IN_FROM_GL_DATE and IN_TO_GL_DATE 
GROUP BY AC.ACCOUNT_ID
) as ACCOUNT_BALANCES 
INNER JOIN ACCOUNT A ON A.ACCOUNT_ID = ACCOUNT_BALANCES.ACCOUNT_ID
GROUP BY ACCOUNT_BALANCES.ACCOUNT_ID 
ORDER BY A.NUMBER;
END//
