-- Description: Stored procedure for getting the summary list of purchases


Delimiter //
DROP PROCEDURE IF EXISTS GET_SUMMARY_LIST_OF_PURCHASES; //
CREATE PROCEDURE GET_SUMMARY_LIST_OF_PURCHASES (IN IN_COMPANY_ID INT, IN IN_DIVISION_ID INT, IN IN_YEAR INT, IN IN_MONTH INT)
BEGIN

SELECT LAST_DAY(DATE) AS MONTH_END, TIN, BUSINESS_CLASSIFICATION_ID, TRADE_NAME, FIRST_NAME, MIDDLE_NAME, LAST_NAME, (SUM(GROSS_PURCHASES) - SUM(INPUT_VAT)) AS GROSS,
SUM(EXEMPT_PURCHASES) AS EXEMPT_PURCHASES, (SUM(GROSS_PURCHASES) - SUM(EXEMPT_PURCHASES) - SUM(ZERO_RATED_PURCHASES) - SUM(INPUT_VAT)) AS GROSS_PURCHASES,
SUM(ZERO_RATED_PURCHASES) AS ZERO_RATED_PURCHASES, SUM(SERVICE_PURCHASES) AS SERVICE_PURCHASES, SUM(CAPITAL_PURCHASES) AS CAPITAL_PURCHASES,
SUM(GOODS_PURCHASES) AS GOODS_PURCHASES, SUM(INPUT_VAT) AS INPUT_VAT, SUPPLIER_ID, STREET_BRGY, CITY_PROVINCE
FROM (
	SELECT ID, DATE, TIN, BUSINESS_CLASSIFICATION_ID, TRADE_NAME, COALESCE(FIRST_NAME, '') AS FIRST_NAME, COALESCE(MIDDLE_NAME, '') AS MIDDLE_NAME, COALESCE(LAST_NAME, '') AS LAST_NAME,
	GROSS_PURCHASES, (EXEMPT_PURCHASES_NS + EXEMPT_PURCHASES_SERVICE + EXEMPT_PURCHASES_APL + EXEMPT_PURCHASES_SI + EXEMPT_PURCHASES_RTSI) AS EXEMPT_PURCHASES,
	(ZERO_RATED_PURCHASES_NS + ZERO_RATED_PURCHASES_SERVICE + ZERO_RATED_PURCHASES_APL + ZERO_RATED_PURCHASES_SI + ZERO_RATED_PURCHASES_RTSI) AS ZERO_RATED_PURCHASES,
	(SERVICE_PURCHASES_NS + SERVICE_PURCHASES_SERVICE + SERVICE_PURCHASES_APL + SERVICE_PURCHASES_SI + SERVICE_PURCHASES_RTSI) AS SERVICE_PURCHASES,
	(CAPITAL_PURCHASES_NS + CAPITAL_PURCHASES_SERVICE + CAPITAL_PURCHASES_APL + CAPITAL_PURCHASES_SI + CAPITAL_PURCHASES_RTSI) AS CAPITAL_PURCHASES,
	(GOODS_PURCHASES_NS + GOODS_PURCHASES_SERVICE + GOODS_PURCHASES_APL + GOODS_PURCHASES_SI + GOODS_PURCHASES_RTSI) AS GOODS_PURCHASES,
	(INPUT_VAT_NS + INPUT_VAT_SERVICES + INPUT_VAT_APL + INPUT_VAT_RTSI + INPUT_VAT_SI) AS INPUT_VAT, SUPPLIER_ID, STREET_BRGY, CITY_PROVINCE
	FROM (
		SELECT API.AP_INVOICE_ID AS ID, API.GL_DATE AS DATE, S.TIN, S.BUSINESS_CLASSIFICATION_ID, S.NAME AS TRADE_NAME, S.FIRST_NAME, S.MIDDLE_NAME, S.LAST_NAME,
		IF(API.INVOICE_TYPE_ID IN (31, 32, 33, 34, 35, 36),
			-(COALESCE((SELECT SUM(RTSI.AMOUNT + COALESCE(RTSI.VAT_AMOUNT, 0)) FROM R_RETURN_TO_SUPPLIER_ITEM RTSI
				WHERE RTSI.TAX_TYPE_ID IS NOT NULL AND RTSI.AP_INVOICE_ID = API.AP_INVOICE_ID), 0)
			+ COALESCE((SELECT SUM(SI.AMOUNT)
				FROM SERIAL_ITEM SI
				INNER JOIN OBJECT_TO_OBJECT OTO ON OTO.TO_OBJECT_ID = SI.EB_OBJECT_ID
				WHERE SI.TAX_TYPE_ID IS NOT NULL AND OTO.FROM_OBJECT_ID = API.EB_OBJECT_ID
				AND SI.ACTIVE = 1 AND OTO.OR_TYPE_ID = 105), 0)),
			(COALESCE((SELECT SUM(APL.AMOUNT + COALESCE(APL.VAT_AMOUNT, 0)) FROM AP_LINE APL
				WHERE APL.TAX_TYPE_ID IS NOT NULL AND APL.AP_INVOICE_ID = API.AP_INVOICE_ID), 0)
			+ COALESCE((SELECT SUM(APIG.AMOUNT + COALESCE(APIG.VAT_AMOUNT, 0)) FROM AP_INVOICE_GOODS APIG
				WHERE APIG.TAX_TYPE_ID IS NOT NULL AND APIG.AP_INVOICE_ID = API.AP_INVOICE_ID), 0)
			+ COALESCE((SELECT SUM(APIL.AMOUNT + COALESCE(APIL.VAT_AMOUNT, 0)) FROM AP_INVOICE_LINE APIL
				WHERE APIL.TAX_TYPE_ID IS NOT NULL AND APIL.AP_INVOICE_ID = API.AP_INVOICE_ID), 0)
			+ COALESCE((SELECT SUM(SI.AMOUNT + COALESCE(SI.VAT_AMOUNT, 0)) FROM SERIAL_ITEM SI
				INNER JOIN OBJECT_TO_OBJECT OTO ON OTO.TO_OBJECT_ID = SI.EB_OBJECT_ID
				WHERE SI.TAX_TYPE_ID IS NOT NULL AND OTO.FROM_OBJECT_ID = API.EB_OBJECT_ID
				AND SI.ACTIVE = 1 AND OTO.OR_TYPE_ID = 24001), 0))) AS GROSS_PURCHASES,
		S.SUPPLIER_ID, S.STREET_BRGY, S.CITY_PROVINCE,
		-- VAT-EXEMPTED
		COALESCE((SELECT SUM(APIG.AMOUNT) FROM AP_INVOICE_GOODS APIG WHERE APIG.TAX_TYPE_ID = 2 AND APIG.AP_INVOICE_ID = API.AP_INVOICE_ID), 0) AS EXEMPT_PURCHASES_NS,
		COALESCE((SELECT SUM(IF(API.INVOICE_TYPE_ID IN (31, 32, 33, 34, 35, 36), -APIL.AMOUNT, APIL.AMOUNT)) FROM AP_INVOICE_LINE APIL WHERE APIL.TAX_TYPE_ID = 2
			AND APIL.AP_INVOICE_ID = API.AP_INVOICE_ID), 0) AS EXEMPT_PURCHASES_SERVICE,
		COALESCE((SELECT SUM(APL.AMOUNT) FROM AP_LINE APL WHERE APL.TAX_TYPE_ID = 2 AND APL.AP_INVOICE_ID = API.AP_INVOICE_ID), 0) AS EXEMPT_PURCHASES_APL,
		COALESCE((SELECT SUM(-RTSI.AMOUNT) FROM R_RETURN_TO_SUPPLIER_ITEM RTSI WHERE RTSI.TAX_TYPE_ID = 2 AND RTSI.AP_INVOICE_ID = API.AP_INVOICE_ID), 0) AS EXEMPT_PURCHASES_RTSI,
		COALESCE((SELECT SUM(IF(API.INVOICE_TYPE_ID IN (31, 32, 33, 34, 35, 36), -SI.AMOUNT, SI.AMOUNT))
			FROM SERIAL_ITEM SI INNER JOIN OBJECT_TO_OBJECT OTO ON OTO.TO_OBJECT_ID = SI.EB_OBJECT_ID
			WHERE SI.TAX_TYPE_ID = 2 AND OTO.FROM_OBJECT_ID = API.EB_OBJECT_ID AND SI.ACTIVE = 1
			AND OTO.OR_TYPE_ID = IF(API.INVOICE_TYPE_ID IN (31, 32, 33, 34, 35, 36), 105, 24001)), 0) AS EXEMPT_PURCHASES_SI,
		-- ZERO RATED
		COALESCE((SELECT SUM(APIG.AMOUNT) FROM AP_INVOICE_GOODS APIG WHERE APIG.TAX_TYPE_ID = 3 AND APIG.AP_INVOICE_ID = API.AP_INVOICE_ID), 0) AS ZERO_RATED_PURCHASES_NS,
		COALESCE((SELECT SUM(IF(API.INVOICE_TYPE_ID IN (31, 32, 33, 34, 35, 36), -APIL.AMOUNT, APIL.AMOUNT)) FROM AP_INVOICE_LINE APIL WHERE APIL.TAX_TYPE_ID = 3
			AND APIL.AP_INVOICE_ID = API.AP_INVOICE_ID), 0) AS ZERO_RATED_PURCHASES_SERVICE,
		COALESCE((SELECT SUM(APL.AMOUNT) FROM AP_LINE APL WHERE APL.TAX_TYPE_ID = 3 AND APL.AP_INVOICE_ID = API.AP_INVOICE_ID), 0) AS ZERO_RATED_PURCHASES_APL,
		COALESCE((SELECT SUM(-RTSI.AMOUNT) FROM R_RETURN_TO_SUPPLIER_ITEM RTSI WHERE RTSI.TAX_TYPE_ID = 3 AND RTSI.AP_INVOICE_ID = API.AP_INVOICE_ID), 0) AS ZERO_RATED_PURCHASES_RTSI,
		COALESCE((SELECT SUM(IF(API.INVOICE_TYPE_ID IN (31, 32, 33, 34, 35, 36), -SI.AMOUNT, SI.AMOUNT))
			FROM SERIAL_ITEM SI INNER JOIN OBJECT_TO_OBJECT OTO ON OTO.TO_OBJECT_ID = SI.EB_OBJECT_ID
			WHERE SI.TAX_TYPE_ID = 3 AND OTO.FROM_OBJECT_ID = API.EB_OBJECT_ID AND SI.ACTIVE = 1
			AND OTO.OR_TYPE_ID = IF(API.INVOICE_TYPE_ID IN (31, 32, 33, 34, 35, 36), 105, 24001)), 0) AS ZERO_RATED_PURCHASES_SI,
		-- SERVICES
		COALESCE((SELECT SUM(APIG.AMOUNT) FROM AP_INVOICE_GOODS APIG WHERE APIG.TAX_TYPE_ID = 5 AND APIG.AP_INVOICE_ID = API.AP_INVOICE_ID), 0) AS SERVICE_PURCHASES_NS,
		COALESCE((SELECT SUM(IF(API.INVOICE_TYPE_ID IN (31, 32, 33, 34, 35, 36), -APIL.AMOUNT, APIL.AMOUNT)) FROM AP_INVOICE_LINE APIL WHERE APIL.TAX_TYPE_ID = 5
			AND APIL.AP_INVOICE_ID = API.AP_INVOICE_ID), 0) AS SERVICE_PURCHASES_SERVICE,
		COALESCE((SELECT SUM(APL.AMOUNT) FROM AP_LINE APL WHERE APL.TAX_TYPE_ID = 5 AND APL.AP_INVOICE_ID = API.AP_INVOICE_ID), 0) AS SERVICE_PURCHASES_APL,
		COALESCE((SELECT SUM(-RTSI.AMOUNT) FROM R_RETURN_TO_SUPPLIER_ITEM RTSI WHERE RTSI.TAX_TYPE_ID = 5 AND RTSI.AP_INVOICE_ID = API.AP_INVOICE_ID), 0) AS SERVICE_PURCHASES_RTSI,
		COALESCE((SELECT SUM(IF(API.INVOICE_TYPE_ID IN (31, 32, 33, 34, 35, 36), -SI.AMOUNT, SI.AMOUNT))
			FROM SERIAL_ITEM SI INNER JOIN OBJECT_TO_OBJECT OTO ON OTO.TO_OBJECT_ID = SI.EB_OBJECT_ID
			WHERE SI.TAX_TYPE_ID = 5 AND OTO.FROM_OBJECT_ID = API.EB_OBJECT_ID AND SI.ACTIVE = 1), 0) AS SERVICE_PURCHASES_SI,
		-- CAPITAL GOODS
		COALESCE((SELECT SUM(APIG.AMOUNT) FROM AP_INVOICE_GOODS APIG WHERE APIG.TAX_TYPE_ID = 6 AND APIG.AP_INVOICE_ID = API.AP_INVOICE_ID), 0) AS CAPITAL_PURCHASES_NS,
		COALESCE((SELECT SUM(IF(API.INVOICE_TYPE_ID IN (31, 32, 33, 34, 35, 36), -APIL.AMOUNT, APIL.AMOUNT)) FROM AP_INVOICE_LINE APIL WHERE APIL.TAX_TYPE_ID = 6
			AND APIL.AP_INVOICE_ID = API.AP_INVOICE_ID), 0) AS CAPITAL_PURCHASES_SERVICE,
		COALESCE((SELECT SUM(APL.AMOUNT) FROM AP_LINE APL WHERE APL.TAX_TYPE_ID = 6 AND APL.AP_INVOICE_ID = API.AP_INVOICE_ID), 0) AS CAPITAL_PURCHASES_APL,
		COALESCE((SELECT SUM(-RTSI.AMOUNT) FROM R_RETURN_TO_SUPPLIER_ITEM RTSI WHERE RTSI.TAX_TYPE_ID = 6 AND RTSI.AP_INVOICE_ID = API.AP_INVOICE_ID), 0) AS CAPITAL_PURCHASES_RTSI,
		COALESCE((SELECT SUM(IF(API.INVOICE_TYPE_ID IN (31, 32, 33, 34, 35, 36), -SI.AMOUNT, SI.AMOUNT))
			FROM SERIAL_ITEM SI INNER JOIN OBJECT_TO_OBJECT OTO ON OTO.TO_OBJECT_ID = SI.EB_OBJECT_ID
			WHERE SI.TAX_TYPE_ID = 6 AND OTO.FROM_OBJECT_ID = API.EB_OBJECT_ID AND SI.ACTIVE = 1
			AND OTO.OR_TYPE_ID = IF(API.INVOICE_TYPE_ID IN (31, 32, 33, 34, 35, 36), 105, 24001)), 0) AS CAPITAL_PURCHASES_SI,
		-- GOODS
		COALESCE((SELECT SUM(APIG.AMOUNT) FROM AP_INVOICE_GOODS APIG WHERE APIG.TAX_TYPE_ID = 4 AND APIG.AP_INVOICE_ID = API.AP_INVOICE_ID), 0) AS GOODS_PURCHASES_NS,
		COALESCE((SELECT SUM(IF(API.INVOICE_TYPE_ID IN (31, 32, 33, 34, 35, 36), -APIL.AMOUNT, APIL.AMOUNT)) FROM AP_INVOICE_LINE APIL WHERE APIL.TAX_TYPE_ID = 4
			AND APIL.AP_INVOICE_ID = API.AP_INVOICE_ID), 0) AS GOODS_PURCHASES_SERVICE,
		COALESCE((SELECT SUM(APL.AMOUNT) FROM AP_LINE APL WHERE APL.TAX_TYPE_ID = 4 AND APL.AP_INVOICE_ID = API.AP_INVOICE_ID), 0) AS GOODS_PURCHASES_APL,
		COALESCE((SELECT SUM(-RTSI.AMOUNT) FROM R_RETURN_TO_SUPPLIER_ITEM RTSI
			WHERE RTSI.TAX_TYPE_ID = 4 AND RTSI.AP_INVOICE_ID = API.AP_INVOICE_ID), 0) AS GOODS_PURCHASES_RTSI,
		COALESCE((SELECT SUM(IF(API.INVOICE_TYPE_ID IN (31, 32, 33, 34, 35, 36), -SI.AMOUNT, SI.AMOUNT))
			FROM SERIAL_ITEM SI INNER JOIN OBJECT_TO_OBJECT OTO ON OTO.TO_OBJECT_ID = SI.EB_OBJECT_ID
			WHERE SI.TAX_TYPE_ID = 4 AND OTO.FROM_OBJECT_ID = API.EB_OBJECT_ID AND SI.ACTIVE = 1
			AND OTO.OR_TYPE_ID = IF(API.INVOICE_TYPE_ID IN (31, 32, 33, 34, 35, 36), 105, 24001)), 0) AS GOODS_PURCHASES_SI,
		-- INPUT VAT
		COALESCE((SELECT SUM(COALESCE(APIG.VAT_AMOUNT, 0)) FROM AP_INVOICE_GOODS APIG WHERE APIG.AP_INVOICE_ID = API.AP_INVOICE_ID
			AND APIG.TAX_TYPE_ID IN (2, 3, 4, 5, 6)), 0) AS INPUT_VAT_NS,
		COALESCE((SELECT SUM(IF(API.INVOICE_TYPE_ID IN (31, 32, 33, 34, 35, 36), -COALESCE(APIL.VAT_AMOUNT, 0), COALESCE(APIL.VAT_AMOUNT, 0)))
			FROM AP_INVOICE_LINE APIL WHERE APIL.AP_INVOICE_ID = API.AP_INVOICE_ID AND APIL.TAX_TYPE_ID IN (2, 3, 4, 5, 6)), 0) AS INPUT_VAT_SERVICES,
		COALESCE((SELECT SUM(COALESCE(APL.VAT_AMOUNT, 0)) FROM AP_LINE APL WHERE APL.AP_INVOICE_ID = API.AP_INVOICE_ID
			AND APL.TAX_TYPE_ID IN (2, 3, 4, 5, 6)), 0) AS INPUT_VAT_APL,
		COALESCE((SELECT SUM(-COALESCE(RTSI.VAT_AMOUNT, 0)) FROM R_RETURN_TO_SUPPLIER_ITEM RTSI WHERE RTSI.AP_INVOICE_ID = API.AP_INVOICE_ID
			AND RTSI.TAX_TYPE_ID IN (2, 3, 4, 5, 6)), 0) AS INPUT_VAT_RTSI,
		COALESCE((SELECT SUM(IF(API.INVOICE_TYPE_ID IN (31, 32, 33, 34, 35, 36), -COALESCE(SI.VAT_AMOUNT, 0), COALESCE(SI.VAT_AMOUNT, 0)))
			FROM SERIAL_ITEM SI INNER JOIN OBJECT_TO_OBJECT OTO ON OTO.TO_OBJECT_ID = SI.EB_OBJECT_ID
			WHERE OTO.FROM_OBJECT_ID = API.EB_OBJECT_ID AND SI.ACTIVE = 1 AND SI.TAX_TYPE_ID IN (2, 3, 4, 5, 6)
			AND OTO.OR_TYPE_ID = IF(API.INVOICE_TYPE_ID IN (31, 32, 33, 34, 35, 36), 105, 24001)), 0) AS INPUT_VAT_SI
		FROM AP_INVOICE API
		INNER JOIN SUPPLIER S ON S.SUPPLIER_ID = API.SUPPLIER_ID
		INNER JOIN FORM_WORKFLOW FW ON FW.FORM_WORKFLOW_ID = API.FORM_WORKFLOW_ID 
		WHERE FW.IS_COMPLETE = 1
		AND API.COMPANY_ID=IN_COMPANY_ID
		AND IF(IN_DIVISION_ID != -1, API.DIVISION_ID = IN_DIVISION_ID, API.DIVISION_ID != IN_DIVISION_ID)
		AND YEAR(API.GL_DATE) = IN_YEAR
		AND MONTH(API.GL_DATE) = IN_MONTH
		-- Excluded RR, API Importation, and petty cash liquidation
		AND API.INVOICE_TYPE_ID NOT IN (13, 14, 15, 16, 17, 18, 43, 44, 45, 46, 47, 48, 55, 56, 57, 58, 59, 60)
	) AS SLP

	UNION ALL

	SELECT ID, DATE, TIN, BUSINESS_CLASSIFICATION_ID, TRADE_NAME, COALESCE(FIRST_NAME, '') AS FIRST_NAME, COALESCE(MIDDLE_NAME, '') AS MIDDLE_NAME, COALESCE(LAST_NAME, '') AS LAST_NAME,
	SUM(PCVL_UP_AMOUNT) AS GROSS_PURCHASES, SUM(EXEMPT_PURCHASES) AS EXEMPT_PURCHASES, SUM(ZERO_RATED_PURCHASES) AS ZERO_RATED_PURCHASES, SUM(SERVICE_PURCHASES) AS SERVICE_PURCHASES,
	SUM(CAPITAL_PURCHASES) AS CAPITAL_PURCHASES, SUM(GOODS_PURCHASES) AS GOODS_PURCHASES, SUM(INPUT_VAT) AS INPUT_VAT, SUPPLIER_ID, STREET_BRGY, CITY_PROVINCE FROM (
		SELECT API.AP_INVOICE_ID AS ID, API.GL_DATE AS DATE, S.TIN, S.BUSINESS_CLASSIFICATION_ID, S.NAME AS TRADE_NAME, S.FIRST_NAME, S.MIDDLE_NAME, S.LAST_NAME,
		PCVL.UP_AMOUNT AS PCVL_UP_AMOUNT, IF(PCVL.TAX_TYPE_ID = 2, PCVL.AMOUNT, 0) AS EXEMPT_PURCHASES, IF(PCVL.TAX_TYPE_ID = 3, PCVL.AMOUNT, 0) AS ZERO_RATED_PURCHASES,
		IF(PCVL.TAX_TYPE_ID = 5, PCVL.AMOUNT, 0) AS SERVICE_PURCHASES, IF(PCVL.TAX_TYPE_ID = 6, PCVL.AMOUNT, 0) AS CAPITAL_PURCHASES,
		IF(PCVL.TAX_TYPE_ID = 4, PCVL.AMOUNT, 0) AS GOODS_PURCHASES, COALESCE(PCVL.VAT_AMOUNT, 0) AS INPUT_VAT, S.SUPPLIER_ID, 
		S.STREET_BRGY, S.CITY_PROVINCE
		FROM PETTY_CASH_VOUCHER_LIQUIDATION_LINE PCVL
		INNER JOIN OBJECT_TO_OBJECT OTO ON OTO.FROM_OBJECT_ID = PCVL.EB_OBJECT_ID
		INNER JOIN PETTY_CASH_REPLENISHMENT_LINE PCRL ON PCRL.EB_OBJECT_ID = OTO.TO_OBJECT_ID
		INNER JOIN AP_INVOICE API ON API.AP_INVOICE_ID = PCRL.AP_INVOICE_ID
		INNER JOIN SUPPLIER S ON S.SUPPLIER_ID = PCVL.SUPPLIER_ID
		INNER JOIN FORM_WORKFLOW FW ON FW.FORM_WORKFLOW_ID = API.FORM_WORKFLOW_ID
		WHERE FW.IS_COMPLETE = 1 
		AND API.COMPANY_ID = IN_COMPANY_ID
		AND IF(IN_DIVISION_ID != -1, API.DIVISION_ID = IN_DIVISION_ID, API.DIVISION_ID != IN_DIVISION_ID)
		AND YEAR(API.GL_DATE) = IN_YEAR
		AND MONTH(API.GL_DATE) = IN_MONTH
		AND PCVL.TAX_TYPE_ID IN (2, 3, 4, 5, 6)
		AND API.INVOICE_TYPE_ID IN (55, 56, 57, 58, 59, 60)
	) AS PCVL_TBL GROUP BY SUPPLIER_ID
) AS MAIN_SLP 
WHERE EXEMPT_PURCHASES != 0
OR ZERO_RATED_PURCHASES != 0
OR SERVICE_PURCHASES != 0
OR CAPITAL_PURCHASES != 0
OR GOODS_PURCHASES != 0
GROUP BY SUPPLIER_ID
HAVING GROSS NOT BETWEEN -0.009 AND 0.009
ORDER BY DATE, TRADE_NAME, FIRST_NAME, MIDDLE_NAME, LAST_NAME;

END;//