-- Description: Stored procedure that will get the petty cash replenishment register

Delimiter //
DROP PROCEDURE IF EXISTS GET_PC_REPLENISHMENT_REGISTER;
CREATE PROCEDURE GET_PC_REPLENISHMENT_REGISTER(IN IN_COMPANY_ID INT, IN IN_DIVISION_ID INT,
IN IN_CUSTODIAN_ID INT,IN IN_PCR_NO INT, IN IN_DATE_FROM DATE, IN IN_DATE_TO DATE, IN IN_STATUS_ID INT, IN IN_LIMIT_FROM INT, IN IN_LIMIT_TO INT)

BEGIN

SELECT DIVISION, PCR_DATE, PCR_NO, CUSTODIAN, PCVL_DATE, PCVL_NO, BMS_NUMBER, SI, REQUESTOR, SUPPLIER, TIN, STREET,
CITY, DESCRIPTION, ACCOUNT, GROSS_AMOUNT, STATUS, AP_INVOICE_ID, CANCELLATION_REMARKS FROM (

SELECT D.NAME AS DIVISION, AP.INVOICE_DATE AS PCR_DATE, AP.SEQUENCE_NO AS PCR_NO, CA.CUSTODIAN_NAME AS CUSTODIAN,
PCVL.SEQUENCE_NO AS PCVL_NO, PCVL.PCVL_DATE, PCVLL.BMS_NUMBER, PCVLL.OR_NUMBER AS SI,
PCVL.REQUESTOR, S.NAME AS SUPPLIER, S.TIN, S.STREET_BRGY AS STREET, S.CITY_PROVINCE AS CITY, PCVLL.DESCRIPTION,
A.ACCOUNT_NAME AS ACCOUNT, (PCVLL.AMOUNT + COALESCE(PCVLL.VAT_AMOUNT, 0)) AS GROSS_AMOUNT,
IF(FW.IS_COMPLETE,'POSTED','UNPOSTED') AS STATUS, AP.AP_INVOICE_ID, IF(FW.CURRENT_STATUS_ID = 4, (SELECT FWL.COMMENT FROM FORM_WORKFLOW_LOG FWL
WHERE FWL.FORM_WORKFLOW_ID = FW.FORM_WORKFLOW_ID AND FWL.FORM_STATUS_ID = 4) , '') AS CANCELLATION_REMARKS
FROM AP_INVOICE AP
INNER JOIN DIVISION D ON AP.DIVISION_ID = D.DIVISION_ID
INNER JOIN PETTY_CASH_REPLENISHMENT_LINE PCRL ON AP.AP_INVOICE_ID = PCRL.AP_INVOICE_ID
INNER JOIN USER_CUSTODIAN UC ON AP.USER_CUSTODIAN_ID = UC.USER_CUSTODIAN_ID
INNER JOIN CUSTODIAN_ACCOUNT CA ON UC.CUSTODIAN_ACCOUNT_ID = CA.CUSTODIAN_ACCOUNT_ID
INNER JOIN OBJECT_TO_OBJECT OTO ON PCRL.EB_OBJECT_ID = OTO.TO_OBJECT_ID
INNER JOIN PETTY_CASH_VOUCHER_LIQUIDATION_LINE PCVLL ON OTO.FROM_OBJECT_ID = PCVLL.EB_OBJECT_ID
INNER JOIN PETTY_CASH_VOUCHER_LIQUIDATION PCVL ON PCVLL.PETTY_CASH_VOUCHER_LIQUIDATION_ID = PCVL.PETTY_CASH_VOUCHER_LIQUIDATION_ID
INNER JOIN SUPPLIER S ON PCVLL.SUPPLIER_ID = S.SUPPLIER_ID
INNER JOIN ACCOUNT_COMBINATION AC ON PCRL.ACCOUNT_COMBINATION_ID = AC.ACCOUNT_COMBINATION_ID
INNER JOIN ACCOUNT A ON AC.ACCOUNT_ID = A.ACCOUNT_ID
INNER JOIN FORM_WORKFLOW FW ON AP.FORM_WORKFLOW_ID = FW.FORM_WORKFLOW_ID
WHERE AP.COMPANY_ID = IN_COMPANY_ID
AND IF(IN_DIVISION_ID != -1, AP.DIVISION_ID = IN_DIVISION_ID, AP.DIVISION_ID != IN_DIVISION_ID)
AND IF(IN_CUSTODIAN_ID != -1, CA.CUSTODIAN_ACCOUNT_ID = IN_CUSTODIAN_ID, CA.CUSTODIAN_ACCOUNT_ID != IN_CUSTODIAN_ID)
AND IF(IN_STATUS_ID != -1, FW.CURRENT_STATUS_ID = IN_STATUS_ID, FW.CURRENT_STATUS_ID != IN_STATUS_ID)
AND IF(IN_PCR_NO != -1, AP.SEQUENCE_NO = IN_PCR_NO, AP.SEQUENCE_NO != IN_PCR_NO)
AND AP.INVOICE_DATE BETWEEN IN_DATE_FROM AND IN_DATE_TO
AND AP.INVOICE_TYPE_ID IN (55, 56, 57, 58, 59, 60)

) AS PC_REPLENISHMENT;
END//
