
-- Description	: Stored procedure that will retrieve all the available serialized items

Delimiter //
DROP PROCEDURE IF EXISTS GET_AVAILABLE_SERIAL_NUMBER;
CREATE PROCEDURE GET_AVAILABLE_SERIAL_NUMBER(IN IN_ITEM_ID INT, IN IN_WAREHOUSE_ID INT, IN IN_SERIAL_NUMBER VARCHAR(50),
	IN IN_IS_EXACT BOOLEAN, IN IN_REF_OBJECT_ID INT)
BEGIN
SELECT SERIAL_NUMBER, UNIT_COST, EB_OBJECT_ID FROM (

SELECT 'TR' AS SOURCE, SERIAL_NUMBER, UNIT_COST, SI.EB_OBJECT_ID FROM SERIAL_ITEM SI 
INNER JOIN OBJECT_TO_OBJECT OTO ON OTO.TO_OBJECT_ID = SI.EB_OBJECT_ID
INNER JOIN R_TRANSFER_RECEIPT TR ON TR.EB_OBJECT_ID = OTO.FROM_OBJECT_ID
INNER JOIN FORM_WORKFLOW FW ON FW.FORM_WORKFLOW_ID = TR.FORM_WORKFLOW_ID
WHERE SI.ACTIVE = 1
AND IF(IN_REF_OBJECT_ID IS NOT NULL, (FW.IS_COMPLETE = 1 OR OTO.FROM_OBJECT_ID = IN_REF_OBJECT_ID), FW.IS_COMPLETE = 1)
AND OTO.OR_TYPE_ID = 104
AND SI.ITEM_ID = IN_ITEM_ID
AND TR.WAREHOUSE_TO_ID = IN_WAREHOUSE_ID
AND IF(IN_IS_EXACT = 1, SI.SERIAL_NUMBER = IN_SERIAL_NUMBER, SI.SERIAL_NUMBER LIKE IN_SERIAL_NUMBER)
AND SI.SERIAL_NUMBER NOT IN (SELECT S.SERIAL_NUMBER FROM SERIAL_ITEM S
	INNER JOIN OBJECT_TO_OBJECT OTO ON OTO.TO_OBJECT_ID = S.EB_OBJECT_ID
	WHERE IF(IN_IS_EXACT = 1, S.SERIAL_NUMBER = IN_SERIAL_NUMBER, S.SERIAL_NUMBER LIKE IN_SERIAL_NUMBER)
	AND S.ITEM_ID = SI.ITEM_ID
	AND S.WAREHOUSE_ID = IN_WAREHOUSE_ID
	AND IF(IN_REF_OBJECT_ID IS NOT NULL,
		S.SERIAL_ITEM_ID NOT IN (
			SELECT I.SERIAL_ITEM_ID FROM SERIAL_ITEM I 
			INNER JOIN OBJECT_TO_OBJECT OTO ON OTO.TO_OBJECT_ID = I.EB_OBJECT_ID
			WHERE OTO.FROM_OBJECT_ID = IN_REF_OBJECT_ID AND I.ACTIVE = 1),
		S.SERIAL_ITEM_ID = S.SERIAL_ITEM_ID)
	AND OTO.OR_TYPE_ID != 104
	AND S.ACTIVE = 1
	AND S.SERIAL_NUMBER NOT IN (SELECT S1.SERIAL_NUMBER FROM SERIAL_ITEM S1
	INNER JOIN OBJECT_TO_OBJECT OTO ON OTO.TO_OBJECT_ID = S1.EB_OBJECT_ID 
	INNER JOIN AP_INVOICE API ON API.EB_OBJECT_ID = OTO.FROM_OBJECT_ID 
	INNER JOIN EB_OBJECT EO ON EO.EB_OBJECT_ID = API.EB_OBJECT_ID
	INNER JOIN FORM_WORKFLOW FW ON API.FORM_WORKFLOW_ID = FW.FORM_WORKFLOW_ID
	WHERE EO.OBJECT_TYPE_ID = 24002
	AND S1.ACTIVE = 1
	AND S1.ITEM_ID = S.ITEM_ID
    AND S1.SERIAL_ITEM_ID = S.SERIAL_ITEM_ID
	AND FW.CURRENT_STATUS_ID != 4
	AND OTO.OR_TYPE_ID = 24001)
	)

UNION ALL

SELECT 'SA-IN' AS SOURCE, SERIAL_NUMBER, UNIT_COST, SI.EB_OBJECT_ID FROM SERIAL_ITEM SI 
INNER JOIN OBJECT_TO_OBJECT OTO ON OTO.TO_OBJECT_ID = SI.EB_OBJECT_ID
INNER JOIN STOCK_ADJUSTMENT SA ON SA.EB_OBJECT_ID = OTO.FROM_OBJECT_ID
INNER JOIN FORM_WORKFLOW FW ON FW.FORM_WORKFLOW_ID = SA.FORM_WORKFLOW_ID
WHERE FW.IS_COMPLETE = 1
AND SI.ACTIVE = 1
AND OTO.OR_TYPE_ID = 56
AND SI.ITEM_ID = IN_ITEM_ID
AND SA.WAREHOUSE_ID = IN_WAREHOUSE_ID
AND IF(IN_IS_EXACT = 1, SI.SERIAL_NUMBER = IN_SERIAL_NUMBER, SI.SERIAL_NUMBER LIKE IN_SERIAL_NUMBER)
AND SI.SERIAL_NUMBER NOT IN (SELECT S.SERIAL_NUMBER FROM SERIAL_ITEM S
	WHERE S.SERIAL_ITEM_ID != SI.SERIAL_ITEM_ID
	AND S.ITEM_ID = SI.ITEM_ID
	AND IF(IN_REF_OBJECT_ID IS NOT NULL,
		S.SERIAL_ITEM_ID NOT IN (
			SELECT I.SERIAL_ITEM_ID FROM SERIAL_ITEM I 
			INNER JOIN OBJECT_TO_OBJECT OTO ON OTO.TO_OBJECT_ID = I.EB_OBJECT_ID
			WHERE OTO.FROM_OBJECT_ID = IN_REF_OBJECT_ID AND I.ACTIVE = 1),
		S.SERIAL_ITEM_ID = S.SERIAL_ITEM_ID)
	AND S.ACTIVE = 1
	AND S.SERIAL_NUMBER NOT IN (SELECT S1.SERIAL_NUMBER FROM SERIAL_ITEM S1
	INNER JOIN OBJECT_TO_OBJECT OTO ON OTO.TO_OBJECT_ID = S1.EB_OBJECT_ID 
	INNER JOIN AP_INVOICE API ON API.EB_OBJECT_ID = OTO.FROM_OBJECT_ID 
	INNER JOIN EB_OBJECT EO ON EO.EB_OBJECT_ID = API.EB_OBJECT_ID
	INNER JOIN FORM_WORKFLOW FW ON API.FORM_WORKFLOW_ID = FW.FORM_WORKFLOW_ID
	WHERE EO.OBJECT_TYPE_ID = 24002
	AND S1.ACTIVE = 1
	AND S1.ITEM_ID = S.ITEM_ID
    AND S1.SERIAL_ITEM_ID = S.SERIAL_ITEM_ID
	AND FW.CURRENT_STATUS_ID != 4
	AND OTO.OR_TYPE_ID = 24001)
	)

UNION ALL

SELECT 'RR' AS SOURCE, SERIAL_NUMBER, UNIT_COST, SI.EB_OBJECT_ID 
FROM SERIAL_ITEM SI 
INNER JOIN OBJECT_TO_OBJECT OTO ON OTO.TO_OBJECT_ID = SI.EB_OBJECT_ID 
INNER JOIN AP_INVOICE API ON API.EB_OBJECT_ID = OTO.FROM_OBJECT_ID 
INNER JOIN R_RECEIVING_REPORT RR ON RR.AP_INVOICE_ID = API.AP_INVOICE_ID 
INNER JOIN FORM_WORKFLOW FW ON API.FORM_WORKFLOW_ID = FW.FORM_WORKFLOW_ID
WHERE FW.IS_COMPLETE = 1
AND SI.ACTIVE = 1
AND OTO.OR_TYPE_ID = 64
AND SI.ITEM_ID = IN_ITEM_ID
AND RR.WAREHOUSE_ID = IN_WAREHOUSE_ID
AND IF(IN_IS_EXACT = 1, SI.SERIAL_NUMBER = IN_SERIAL_NUMBER, SI.SERIAL_NUMBER LIKE IN_SERIAL_NUMBER)
AND SI.SERIAL_NUMBER NOT IN (SELECT S.SERIAL_NUMBER FROM SERIAL_ITEM S
	WHERE S.SERIAL_ITEM_ID != SI.SERIAL_ITEM_ID
	AND S.ITEM_ID = SI.ITEM_ID
	AND IF(IN_REF_OBJECT_ID IS NOT NULL, S.SERIAL_ITEM_ID NOT IN (
			SELECT I.SERIAL_ITEM_ID FROM SERIAL_ITEM I
			INNER JOIN OBJECT_TO_OBJECT OTO ON OTO.TO_OBJECT_ID = I.EB_OBJECT_ID
			WHERE OTO.FROM_OBJECT_ID = IN_REF_OBJECT_ID AND I.ACTIVE = 1),
		S.SERIAL_ITEM_ID = S.SERIAL_ITEM_ID)
	AND S.ACTIVE = 1
	AND S.SERIAL_NUMBER NOT IN (SELECT S1.SERIAL_NUMBER FROM SERIAL_ITEM S1
	INNER JOIN OBJECT_TO_OBJECT OTO ON OTO.TO_OBJECT_ID = S1.EB_OBJECT_ID 
	INNER JOIN AP_INVOICE API ON API.EB_OBJECT_ID = OTO.FROM_OBJECT_ID 
	INNER JOIN EB_OBJECT EO ON EO.EB_OBJECT_ID = API.EB_OBJECT_ID
	INNER JOIN FORM_WORKFLOW FW ON API.FORM_WORKFLOW_ID = FW.FORM_WORKFLOW_ID
	WHERE EO.OBJECT_TYPE_ID = 24002
	AND S1.ACTIVE = 1
	AND S1.ITEM_ID = S.ITEM_ID
    AND S1.SERIAL_ITEM_ID = S.SERIAL_ITEM_ID
	AND FW.CURRENT_STATUS_ID != 4
	AND OTO.OR_TYPE_ID = 24001)
	)

UNION ALL

SELECT 'CSR' AS SOURCE, SERIAL_NUMBER, UNIT_COST, SI.EB_OBJECT_ID FROM SERIAL_ITEM SI
INNER JOIN OBJECT_TO_OBJECT OTO ON OTO.TO_OBJECT_ID = SI.EB_OBJECT_ID
INNER JOIN CASH_SALE_RETURN CSR ON CSR.EB_OBJECT_ID = OTO.FROM_OBJECT_ID
INNER JOIN FORM_WORKFLOW FW ON FW.FORM_WORKFLOW_ID = CSR.FORM_WORKFLOW_ID
WHERE FW.IS_COMPLETE = 1
AND SI.ACTIVE = 1
AND OTO.OR_TYPE_ID = 68
AND SI.ITEM_ID = IN_ITEM_ID
AND SI.WAREHOUSE_ID = IN_WAREHOUSE_ID
AND IF(IN_IS_EXACT = 1, SI.SERIAL_NUMBER = IN_SERIAL_NUMBER, SI.SERIAL_NUMBER LIKE IN_SERIAL_NUMBER)
AND SI.SERIAL_NUMBER NOT IN (SELECT S.SERIAL_NUMBER FROM SERIAL_ITEM S
	WHERE S.SERIAL_ITEM_ID != SI.SERIAL_ITEM_ID
	AND S.ITEM_ID = SI.ITEM_ID
	AND IF(IN_REF_OBJECT_ID IS NOT NULL,
		S.SERIAL_ITEM_ID NOT IN (
			SELECT I.SERIAL_ITEM_ID FROM SERIAL_ITEM I 
			INNER JOIN OBJECT_TO_OBJECT OTO ON OTO.TO_OBJECT_ID = I.EB_OBJECT_ID
			WHERE OTO.FROM_OBJECT_ID = IN_REF_OBJECT_ID AND I.ACTIVE = 1
			AND I.UPDATED_DATE > SI.UPDATED_DATE),
		S.SERIAL_ITEM_ID = S.SERIAL_ITEM_ID
		AND S.UPDATED_DATE > SI.UPDATED_DATE)
	AND S.ACTIVE = 1
	AND S.SERIAL_NUMBER NOT IN (SELECT S1.SERIAL_NUMBER FROM SERIAL_ITEM S1
	INNER JOIN OBJECT_TO_OBJECT OTO ON OTO.TO_OBJECT_ID = S1.EB_OBJECT_ID 
	INNER JOIN AP_INVOICE API ON API.EB_OBJECT_ID = OTO.FROM_OBJECT_ID 
	INNER JOIN EB_OBJECT EO ON EO.EB_OBJECT_ID = API.EB_OBJECT_ID
	INNER JOIN FORM_WORKFLOW FW ON API.FORM_WORKFLOW_ID = FW.FORM_WORKFLOW_ID
	WHERE EO.OBJECT_TYPE_ID = 24002
	AND S1.ACTIVE = 1
	AND S1.ITEM_ID = S.ITEM_ID
    AND S1.SERIAL_ITEM_ID = S.SERIAL_ITEM_ID
	AND FW.CURRENT_STATUS_ID != 4
	AND OTO.OR_TYPE_ID = 24001)
	)

UNION ALL

SELECT 'PR' AS SOURCE, SI.SERIAL_NUMBER, SI.UNIT_COST, SI.EB_OBJECT_ID FROM SERIAL_ITEM SI 
INNER JOIN OBJECT_TO_OBJECT OTO ON OTO.TO_OBJECT_ID = SI.EB_OBJECT_ID
INNER JOIN PROCESSING_REPORT PR ON PR.EB_OBJECT_ID = OTO.FROM_OBJECT_ID
INNER JOIN FORM_WORKFLOW FW ON FW.FORM_WORKFLOW_ID = PR.FORM_WORKFLOW_ID
WHERE FW.IS_COMPLETE = 1
AND SI.ACTIVE = 1
AND OTO.OR_TYPE_ID = 76
AND SI.ITEM_ID = IN_ITEM_ID
AND SI.WAREHOUSE_ID = IN_WAREHOUSE_ID
AND IF(IN_IS_EXACT = 1, SI.SERIAL_NUMBER = IN_SERIAL_NUMBER, SI.SERIAL_NUMBER LIKE IN_SERIAL_NUMBER)
AND SI.SERIAL_NUMBER NOT IN (SELECT S.SERIAL_NUMBER FROM SERIAL_ITEM S
	WHERE S.SERIAL_ITEM_ID != SI.SERIAL_ITEM_ID
	AND S.ITEM_ID = SI.ITEM_ID
	AND IF(IN_REF_OBJECT_ID IS NOT NULL,
		S.SERIAL_ITEM_ID NOT IN (
			SELECT I.SERIAL_ITEM_ID FROM SERIAL_ITEM I 
			INNER JOIN OBJECT_TO_OBJECT OTO ON OTO.TO_OBJECT_ID = I.EB_OBJECT_ID
			WHERE OTO.FROM_OBJECT_ID = IN_REF_OBJECT_ID AND I.ACTIVE = 1),
		S.SERIAL_ITEM_ID = S.SERIAL_ITEM_ID)
	AND S.ACTIVE = 1
	AND S.SERIAL_NUMBER NOT IN (SELECT S1.SERIAL_NUMBER FROM SERIAL_ITEM S1
	INNER JOIN OBJECT_TO_OBJECT OTO ON OTO.TO_OBJECT_ID = S1.EB_OBJECT_ID 
	INNER JOIN AP_INVOICE API ON API.EB_OBJECT_ID = OTO.FROM_OBJECT_ID 
	INNER JOIN EB_OBJECT EO ON EO.EB_OBJECT_ID = API.EB_OBJECT_ID
	INNER JOIN FORM_WORKFLOW FW ON API.FORM_WORKFLOW_ID = FW.FORM_WORKFLOW_ID
	WHERE EO.OBJECT_TYPE_ID = 24002
	AND S1.ACTIVE = 1
	AND S1.ITEM_ID = S.ITEM_ID
    AND S1.SERIAL_ITEM_ID = S.SERIAL_ITEM_ID
	AND FW.CURRENT_STATUS_ID != 4
	AND OTO.OR_TYPE_ID = 24001)
	)

UNION ALL

SELECT 'ASR' AS SOURCE, SERIAL_NUMBER, UNIT_COST, SI.EB_OBJECT_ID FROM SERIAL_ITEM SI
INNER JOIN OBJECT_TO_OBJECT OTO ON OTO.TO_OBJECT_ID = SI.EB_OBJECT_ID
INNER JOIN AR_TRANSACTION AT ON AT.EB_OBJECT_ID = OTO.FROM_OBJECT_ID
INNER JOIN FORM_WORKFLOW FW ON FW.FORM_WORKFLOW_ID = AT.FORM_WORKFLOW_ID
WHERE FW.IS_COMPLETE = 1
AND SI.ACTIVE = 1
AND OTO.OR_TYPE_ID = 103
AND SI.ITEM_ID = IN_ITEM_ID
AND SI.WAREHOUSE_ID = IN_WAREHOUSE_ID
AND SI.QUANTITY < 0
AND IF(IN_IS_EXACT = 1, SI.SERIAL_NUMBER = IN_SERIAL_NUMBER, SI.SERIAL_NUMBER LIKE IN_SERIAL_NUMBER)
AND SI.SERIAL_NUMBER NOT IN (SELECT S.SERIAL_NUMBER FROM SERIAL_ITEM S
	WHERE S.SERIAL_ITEM_ID != SI.SERIAL_ITEM_ID
	AND S.ITEM_ID = SI.ITEM_ID
	AND IF(IN_REF_OBJECT_ID IS NOT NULL,
		S.SERIAL_ITEM_ID NOT IN (
			SELECT I.SERIAL_ITEM_ID FROM SERIAL_ITEM I 
			INNER JOIN OBJECT_TO_OBJECT OTO ON OTO.TO_OBJECT_ID = I.EB_OBJECT_ID
			WHERE OTO.FROM_OBJECT_ID = IN_REF_OBJECT_ID AND I.ACTIVE = 1
			AND I.UPDATED_DATE > SI.UPDATED_DATE),
		S.SERIAL_ITEM_ID = S.SERIAL_ITEM_ID
		AND S.UPDATED_DATE > SI.UPDATED_DATE)
	AND S.ACTIVE = 1
	AND S.SERIAL_NUMBER NOT IN (SELECT S1.SERIAL_NUMBER FROM SERIAL_ITEM S1
	INNER JOIN OBJECT_TO_OBJECT OTO ON OTO.TO_OBJECT_ID = S1.EB_OBJECT_ID 
	INNER JOIN AP_INVOICE API ON API.EB_OBJECT_ID = OTO.FROM_OBJECT_ID 
	INNER JOIN EB_OBJECT EO ON EO.EB_OBJECT_ID = API.EB_OBJECT_ID
	INNER JOIN FORM_WORKFLOW FW ON API.FORM_WORKFLOW_ID = FW.FORM_WORKFLOW_ID
	WHERE EO.OBJECT_TYPE_ID = 24002
	AND S1.ACTIVE = 1
	AND S1.ITEM_ID = S.ITEM_ID
    AND S1.SERIAL_ITEM_ID = S.SERIAL_ITEM_ID
	AND FW.CURRENT_STATUS_ID != 4
	AND OTO.OR_TYPE_ID = 24001)
	)
	
UNION ALL

SELECT 'DR' AS SOURCE, SERIAL_NUMBER, UNIT_COST, SI.EB_OBJECT_ID FROM SERIAL_ITEM SI
INNER JOIN OBJECT_TO_OBJECT OTO ON OTO.TO_OBJECT_ID = SI.EB_OBJECT_ID
INNER JOIN DELIVERY_RECEIPT DR ON DR.EB_OBJECT_ID = OTO.FROM_OBJECT_ID
INNER JOIN FORM_WORKFLOW FW ON FW.FORM_WORKFLOW_ID = DR.FORM_WORKFLOW_ID
WHERE FW.IS_COMPLETE = 1
AND SI.ACTIVE = 1
AND OTO.OR_TYPE_ID = 12004
AND SI.ITEM_ID = IN_ITEM_ID
AND SI.WAREHOUSE_ID = IN_WAREHOUSE_ID
AND SI.QUANTITY < 0
AND IF(IN_IS_EXACT = 1, SI.SERIAL_NUMBER = IN_SERIAL_NUMBER, SI.SERIAL_NUMBER LIKE IN_SERIAL_NUMBER)
AND SI.SERIAL_NUMBER NOT IN (SELECT S.SERIAL_NUMBER FROM SERIAL_ITEM S
	WHERE S.SERIAL_ITEM_ID != SI.SERIAL_ITEM_ID
	AND S.ITEM_ID = SI.ITEM_ID
	AND IF(IN_REF_OBJECT_ID IS NOT NULL,
		S.SERIAL_ITEM_ID NOT IN (
			SELECT I.SERIAL_ITEM_ID FROM SERIAL_ITEM I 
			INNER JOIN OBJECT_TO_OBJECT OTO ON OTO.TO_OBJECT_ID = I.EB_OBJECT_ID
			WHERE OTO.FROM_OBJECT_ID = IN_REF_OBJECT_ID AND I.ACTIVE = 1
			AND I.UPDATED_DATE > SI.UPDATED_DATE),
		S.SERIAL_ITEM_ID = S.SERIAL_ITEM_ID
		AND S.UPDATED_DATE > SI.UPDATED_DATE)
	AND S.ACTIVE = 1
	AND S.SERIAL_NUMBER NOT IN (SELECT S1.SERIAL_NUMBER FROM SERIAL_ITEM S1
	INNER JOIN OBJECT_TO_OBJECT OTO ON OTO.TO_OBJECT_ID = S1.EB_OBJECT_ID 
	INNER JOIN AP_INVOICE API ON API.EB_OBJECT_ID = OTO.FROM_OBJECT_ID 
	INNER JOIN EB_OBJECT EO ON EO.EB_OBJECT_ID = API.EB_OBJECT_ID
	INNER JOIN FORM_WORKFLOW FW ON API.FORM_WORKFLOW_ID = FW.FORM_WORKFLOW_ID
	WHERE EO.OBJECT_TYPE_ID = 24002
	AND S1.ACTIVE = 1
	AND S1.ITEM_ID = S.ITEM_ID
    AND S1.SERIAL_ITEM_ID = S.SERIAL_ITEM_ID
	AND FW.CURRENT_STATUS_ID != 4
	AND OTO.OR_TYPE_ID = 24001)
	)
) as AVAILABLE_SERIAL_NUMBER;
END //