-- Description: Stored procedure that will get the daily cash collection.


Delimiter //
DROP PROCEDURE IF EXISTS GET_DAILY_CASH_COLLECTION;//
CREATE PROCEDURE GET_DAILY_CASH_COLLECTION (IN IN_COMPANY_ID INT, IN IN_USER_ID INT, IN IN_DATE DATE, 
IN IN_ORDER_BY VARCHAR(15), IN IN_STATUS INT)
BEGIN

IF IN_ORDER_BY = 'REFERENCE_NO' THEN

SELECT CURRENT_STATUS_ID, TIME, REFERENCE_NO, INVOICE_NO, CUSTOMER_NAME, AMOUNT, DATE, CREATED_DATE, ORIG_CREATED_DATE FROM (

-- Cash Sale 
SELECT FW.CURRENT_STATUS_ID, TIME(CS.CREATED_DATE) AS TIME, CONCAT('CS ', LEFT(C.NAME , 1), ' ', CS_NUMBER) AS REFERENCE_NO,
CS.SALE_INVOICE_NO AS INVOICE_NO, CUST.NAME AS CUSTOMER_NAME, (SUM(CSI.AMOUNT + COALESCE(CSI.VAT_AMOUNT, 0))
+ COALESCE((SELECT SUM(AMOUNT + COALESCE(AL.VAT_AMOUNT, 0)) FROM CASH_SALE_AR_LINE AL
WHERE AL.CASH_SALE_ID = CSI.CASH_SALE_ID GROUP BY CS.CASH_SALE_ID), 0)) - COALESCE(WT_AMOUNT, 0) AS AMOUNT,
RECEIPT_DATE AS DATE, FWL.CREATED_DATE, CS.CREATED_DATE AS ORIG_CREATED_DATE
FROM CASH_SALE_ITEM CSI
INNER JOIN CASH_SALE CS ON CS.CASH_SALE_ID = CSI.CASH_SALE_ID
INNER JOIN COMPANY C ON C.COMPANY_ID = CS.COMPANY_ID
INNER JOIN AR_CUSTOMER CUST ON CUST.AR_CUSTOMER_ID = CS.AR_CUSTOMER_ID
INNER JOIN FORM_WORKFLOW FW ON FW.FORM_WORKFLOW_ID = CS.FORM_WORKFLOW_ID
INNER JOIN (SELECT FORM_WORKFLOW_ID, FORM_STATUS_ID, CREATED_BY, CREATED_DATE 
FROM FORM_WORKFLOW_LOG GROUP BY FORM_WORKFLOW_ID, FORM_STATUS_ID) FWL 
ON FWL.FORM_WORKFLOW_ID = FW.FORM_WORKFLOW_ID
WHERE IF (IN_STATUS = -1, FW.CURRENT_STATUS_ID = 4 OR IS_COMPLETE = 1, FW.CURRENT_STATUS_ID != 4 AND IS_COMPLETE = 1)
AND FWL.FORM_STATUS_ID = FW.CURRENT_STATUS_ID
AND FWL.CREATED_BY = IN_USER_ID
AND RECEIPT_DATE = IN_DATE
AND CS.COMPANY_ID = IN_COMPANY_ID
AND CS.CASH_SALE_TYPE_ID=1
GROUP BY CS.CASH_SALE_ID

UNION ALL

-- Cash Sale - CT
SELECT FW.CURRENT_STATUS_ID, TIME(CS.CREATED_DATE) AS TIME, CONCAT('CS ', LEFT(C.NAME , 1), ' ', CS_NUMBER) AS REFERENCE_NO,
CS.SALE_INVOICE_NO AS INVOICE_NO, CUST.NAME AS CUSTOMER_NAME,
SUM(AMOUNT) + COALESCE((SELECT SUM(AMOUNT) FROM CASH_SALE_AR_LINE AL
WHERE AL.CASH_SALE_ID = CSI.CASH_SALE_ID
GROUP BY CS.CASH_SALE_ID), 0) AS AMOUNT,
RECEIPT_DATE AS DATE, FWL.CREATED_DATE, CS.CREATED_DATE AS ORIG_CREATED_DATE
FROM CASH_SALE_ITEM CSI
INNER JOIN CASH_SALE CS ON CS.CASH_SALE_ID = CSI.CASH_SALE_ID
INNER JOIN COMPANY C ON C.COMPANY_ID = CS.COMPANY_ID
INNER JOIN AR_CUSTOMER CUST ON CUST.AR_CUSTOMER_ID = CS.AR_CUSTOMER_ID
INNER JOIN FORM_WORKFLOW FW ON FW.FORM_WORKFLOW_ID = CS.FORM_WORKFLOW_ID
INNER JOIN (SELECT FORM_WORKFLOW_ID, FORM_STATUS_ID, CREATED_BY, CREATED_DATE
FROM FORM_WORKFLOW_LOG GROUP BY FORM_WORKFLOW_ID, FORM_STATUS_ID) FWL
ON FWL.FORM_WORKFLOW_ID = FW.FORM_WORKFLOW_ID
WHERE
IF (IN_STATUS = -1, FW.CURRENT_STATUS_ID = 4 OR IS_COMPLETE = 1,
FW.CURRENT_STATUS_ID != 4 AND IS_COMPLETE = 1)
AND FWL.FORM_STATUS_ID = FW.CURRENT_STATUS_ID
AND FWL.CREATED_BY = IN_USER_ID
AND RECEIPT_DATE = IN_DATE
AND CS.COMPANY_ID = IN_COMPANY_ID
AND CS.CASH_SALE_TYPE_ID=5
GROUP BY CS.CASH_SALE_ID

UNION ALL

SELECT FW.CURRENT_STATUS_ID, TIME(CS.CREATED_DATE) AS TIME, CONCAT('CS-W ', LEFT(C.NAME , 1), ' ', CS_NUMBER) AS REFERENCE_NO, 
CS.SALE_INVOICE_NO AS INVOICE_NO, CUST.NAME AS CUSTOMER_NAME,
SUM(AMOUNT) + COALESCE ((SELECT SUM(AMOUNT) FROM CASH_SALE_AR_LINE AL
WHERE AL.CASH_SALE_ID = CSI.CASH_SALE_ID
GROUP BY CS.CASH_SALE_ID), 0) AS AMOUNT,
RECEIPT_DATE AS DATE, FWL.CREATED_DATE, CS.CREATED_DATE AS ORIG_CREATED_DATE
FROM CASH_SALE_ITEM CSI
INNER JOIN CASH_SALE CS ON CS.CASH_SALE_ID = CSI.CASH_SALE_ID
INNER JOIN COMPANY C ON C.COMPANY_ID = CS.COMPANY_ID
INNER JOIN AR_CUSTOMER CUST ON CUST.AR_CUSTOMER_ID = CS.AR_CUSTOMER_ID
INNER JOIN FORM_WORKFLOW FW ON FW.FORM_WORKFLOW_ID = CS.FORM_WORKFLOW_ID
INNER JOIN (SELECT FORM_WORKFLOW_ID, FORM_STATUS_ID, CREATED_BY, CREATED_DATE 
FROM FORM_WORKFLOW_LOG GROUP BY FORM_WORKFLOW_ID, FORM_STATUS_ID) FWL 
ON FWL.FORM_WORKFLOW_ID = FW.FORM_WORKFLOW_ID
WHERE
IF (IN_STATUS = -1, FW.CURRENT_STATUS_ID = 4 OR IS_COMPLETE = 1, 
FW.CURRENT_STATUS_ID != 4 AND IS_COMPLETE = 1)
AND FWL.FORM_STATUS_ID = FW.CURRENT_STATUS_ID
AND FWL.CREATED_BY = IN_USER_ID
AND RECEIPT_DATE = IN_DATE
AND CS.COMPANY_ID = IN_COMPANY_ID
AND CS.CASH_SALE_TYPE_ID=2
GROUP BY CS.CASH_SALE_ID

UNION ALL

SELECT FW.CURRENT_STATUS_ID, TIME(CS.CREATED_DATE) AS TIME, CONCAT('CS-IS ', LEFT(C.NAME , 1), ' ', CS_NUMBER) AS REFERENCE_NO,
CS.SALE_INVOICE_NO AS INVOICE_NO, CUST.NAME AS CUSTOMER_NAME,
SUM(AMOUNT) + COALESCE ((SELECT SUM(AMOUNT) FROM CASH_SALE_AR_LINE AL
WHERE AL.CASH_SALE_ID = CSI.CASH_SALE_ID
GROUP BY CS.CASH_SALE_ID), 0) AS AMOUNT,
RECEIPT_DATE AS DATE, FWL.CREATED_DATE, CS.CREATED_DATE AS ORIG_CREATED_DATE
FROM CASH_SALE_ITEM CSI
INNER JOIN CASH_SALE CS ON CS.CASH_SALE_ID = CSI.CASH_SALE_ID
INNER JOIN COMPANY C ON C.COMPANY_ID = CS.COMPANY_ID
INNER JOIN AR_CUSTOMER CUST ON CUST.AR_CUSTOMER_ID = CS.AR_CUSTOMER_ID
INNER JOIN FORM_WORKFLOW FW ON FW.FORM_WORKFLOW_ID = CS.FORM_WORKFLOW_ID
INNER JOIN (SELECT FORM_WORKFLOW_ID, FORM_STATUS_ID, CREATED_BY, CREATED_DATE
FROM FORM_WORKFLOW_LOG GROUP BY FORM_WORKFLOW_ID, FORM_STATUS_ID) FWL 
ON FWL.FORM_WORKFLOW_ID = FW.FORM_WORKFLOW_ID
WHERE
IF (IN_STATUS = -1, FW.CURRENT_STATUS_ID = 4 OR IS_COMPLETE = 1, 
FW.CURRENT_STATUS_ID != 4 AND IS_COMPLETE = 1)
AND FWL.FORM_STATUS_ID = FW.CURRENT_STATUS_ID
AND FWL.CREATED_BY = IN_USER_ID
AND RECEIPT_DATE = IN_DATE
AND CS.COMPANY_ID = IN_COMPANY_ID
AND CS.CASH_SALE_TYPE_ID=3
GROUP BY CS.CASH_SALE_ID

UNION ALL

SELECT FW.CURRENT_STATUS_ID, TIME(CS.CREATED_DATE) AS TIME, CONCAT('CS-CPOS ', LEFT(C.NAME , 1), ' ', CS_NUMBER) AS REFERENCE_NO,
CS.SALE_INVOICE_NO AS INVOICE_NO, CUST.NAME AS CUSTOMER_NAME,
SUM(AMOUNT) + COALESCE ((SELECT SUM(AMOUNT) FROM CASH_SALE_AR_LINE AL
WHERE AL.CASH_SALE_ID = CSI.CASH_SALE_ID
GROUP BY CS.CASH_SALE_ID), 0) AS AMOUNT,
RECEIPT_DATE AS DATE, FWL.CREATED_DATE, CS.CREATED_DATE AS ORIG_CREATED_DATE
FROM CASH_SALE_ITEM CSI
INNER JOIN CASH_SALE CS ON CS.CASH_SALE_ID = CSI.CASH_SALE_ID
INNER JOIN COMPANY C ON C.COMPANY_ID = CS.COMPANY_ID
INNER JOIN AR_CUSTOMER CUST ON CUST.AR_CUSTOMER_ID = CS.AR_CUSTOMER_ID
INNER JOIN FORM_WORKFLOW FW ON FW.FORM_WORKFLOW_ID = CS.FORM_WORKFLOW_ID
INNER JOIN (SELECT FORM_WORKFLOW_ID, FORM_STATUS_ID, CREATED_BY, CREATED_DATE
FROM FORM_WORKFLOW_LOG GROUP BY FORM_WORKFLOW_ID, FORM_STATUS_ID) FWL 
ON FWL.FORM_WORKFLOW_ID = FW.FORM_WORKFLOW_ID
WHERE
IF (IN_STATUS = -1, FW.CURRENT_STATUS_ID = 4 OR IS_COMPLETE = 1, 
FW.CURRENT_STATUS_ID != 4 AND IS_COMPLETE = 1)
AND FWL.FORM_STATUS_ID = FW.CURRENT_STATUS_ID
AND FWL.CREATED_BY = IN_USER_ID
AND RECEIPT_DATE = IN_DATE
AND CS.COMPANY_ID = IN_COMPANY_ID
AND CS.CASH_SALE_TYPE_ID=4
GROUP BY CS.CASH_SALE_ID

UNION ALL

SELECT FW.CURRENT_STATUS_ID, TIME(CS.CREATED_DATE) AS TIME, CONCAT('CS-P ', LEFT(C.NAME , 1), ' ', CS_NUMBER) AS REFERENCE_NO,
CS.SALE_INVOICE_NO AS INVOICE_NO, CUST.NAME AS CUSTOMER_NAME,
SUM(AMOUNT) + COALESCE ((SELECT SUM(AMOUNT) FROM CASH_SALE_AR_LINE AL
WHERE AL.CASH_SALE_ID = CSI.CASH_SALE_ID
GROUP BY CS.CASH_SALE_ID), 0) AS AMOUNT,
RECEIPT_DATE AS DATE, FWL.CREATED_DATE, CS.CREATED_DATE AS ORIG_CREATED_DATE
FROM CASH_SALE_ITEM CSI
INNER JOIN CASH_SALE CS ON CS.CASH_SALE_ID = CSI.CASH_SALE_ID
INNER JOIN COMPANY C ON C.COMPANY_ID = CS.COMPANY_ID
INNER JOIN AR_CUSTOMER CUST ON CUST.AR_CUSTOMER_ID = CS.AR_CUSTOMER_ID
INNER JOIN FORM_WORKFLOW FW ON FW.FORM_WORKFLOW_ID = CS.FORM_WORKFLOW_ID
INNER JOIN (SELECT FORM_WORKFLOW_ID, FORM_STATUS_ID, CREATED_BY, CREATED_DATE
FROM FORM_WORKFLOW_LOG GROUP BY FORM_WORKFLOW_ID, FORM_STATUS_ID) FWL 
ON FWL.FORM_WORKFLOW_ID = FW.FORM_WORKFLOW_ID
WHERE
IF (IN_STATUS = -1, FW.CURRENT_STATUS_ID = 4 OR IS_COMPLETE = 1, 
FW.CURRENT_STATUS_ID != 4 AND IS_COMPLETE = 1)
AND FWL.FORM_STATUS_ID = FW.CURRENT_STATUS_ID
AND FWL.CREATED_BY = IN_USER_ID
AND RECEIPT_DATE = IN_DATE
AND CS.COMPANY_ID = IN_COMPANY_ID
AND CS.CASH_SALE_TYPE_ID = 6
GROUP BY CS.CASH_SALE_ID

UNION ALL

SELECT FW.CURRENT_STATUS_ID, TIME(CSR.CREATED_DATE) AS TIME, CONCAT('CSR ', LEFT(C.NAME , 1), ' ', CSR_NUMBER) AS REFERENCE_NO,
CSR.SALE_INVOICE_NO AS INVOICE_NO, CUST.NAME AS CUSTOMER_NAME, SUM(CSRI.AMOUNT + COALESCE(CSRI.VAT_AMOUNT, 0)) - COALESCE(WT_AMOUNT, 0) AS AMOUNT,
DATE, FWL.CREATED_DATE, CSR.CREATED_DATE AS ORIG_CREATED_DATE
FROM CASH_SALE_RETURN_ITEM CSRI
INNER JOIN CASH_SALE_RETURN CSR ON CSR.CASH_SALE_RETURN_ID = CSRI.CASH_SALE_RETURN_ID
INNER JOIN COMPANY C ON C.COMPANY_ID = CSR.COMPANY_ID
INNER JOIN AR_CUSTOMER CUST ON CUST.AR_CUSTOMER_ID = CSR.AR_CUSTOMER_ID
INNER JOIN FORM_WORKFLOW FW ON FW.FORM_WORKFLOW_ID = CSR.FORM_WORKFLOW_ID
INNER JOIN (SELECT FORM_WORKFLOW_ID, FORM_STATUS_ID, CREATED_BY, CREATED_DATE
FROM FORM_WORKFLOW_LOG GROUP BY FORM_WORKFLOW_ID, FORM_STATUS_ID) FWL 
ON FWL.FORM_WORKFLOW_ID = FW.FORM_WORKFLOW_ID
WHERE IF (IN_STATUS = -1, (FW.CURRENT_STATUS_ID = 4 OR IS_COMPLETE = 1), (FW.CURRENT_STATUS_ID != 4 AND IS_COMPLETE = 1))
AND FWL.FORM_STATUS_ID = FW.CURRENT_STATUS_ID
AND FWL.CREATED_BY = IN_USER_ID
AND C.COMPANY_ID = IN_COMPANY_ID
AND DATE = IN_DATE
AND CSR.CASH_SALE_TYPE_ID=1
GROUP BY CSR.CASH_SALE_RETURN_ID

UNION ALL 

SELECT FW.CURRENT_STATUS_ID, TIME(CSR.CREATED_DATE) AS TIME, CONCAT('CSR W ', LEFT(C.NAME , 1), ' ', CSR_NUMBER) AS REFERENCE_NO,
CSR.SALE_INVOICE_NO AS INVOICE_NO, CUST.NAME AS CUSTOMER_NAME, SUM(AMOUNT) AS AMOUNT,
DATE, FWL.CREATED_DATE, CSR.CREATED_DATE AS ORIG_CREATED_DATE
FROM CASH_SALE_RETURN_ITEM CSRI
INNER JOIN CASH_SALE_RETURN CSR ON CSR.CASH_SALE_RETURN_ID = CSRI.CASH_SALE_RETURN_ID
INNER JOIN COMPANY C ON C.COMPANY_ID = CSR.COMPANY_ID
INNER JOIN AR_CUSTOMER CUST ON CUST.AR_CUSTOMER_ID = CSR.AR_CUSTOMER_ID
INNER JOIN FORM_WORKFLOW FW ON FW.FORM_WORKFLOW_ID = CSR.FORM_WORKFLOW_ID
INNER JOIN (SELECT FORM_WORKFLOW_ID, FORM_STATUS_ID, CREATED_BY, CREATED_DATE
FROM FORM_WORKFLOW_LOG GROUP BY FORM_WORKFLOW_ID, FORM_STATUS_ID) FWL
ON FWL.FORM_WORKFLOW_ID = FW.FORM_WORKFLOW_ID
WHERE
IF (IN_STATUS = -1, FW.CURRENT_STATUS_ID = 4 OR IS_COMPLETE = 1, 
FW.CURRENT_STATUS_ID != 4 AND IS_COMPLETE = 1)
AND FWL.FORM_STATUS_ID = FW.CURRENT_STATUS_ID
AND FWL.CREATED_BY = IN_USER_ID
AND C.COMPANY_ID = IN_COMPANY_ID
AND DATE = IN_DATE
AND CSR.CASH_SALE_TYPE_ID=2
GROUP BY CSR.CASH_SALE_RETURN_ID

UNION ALL

SELECT FW.CURRENT_STATUS_ID, TIME(CSR.CREATED_DATE) AS TIME, CONCAT('CSR-IS ', LEFT(C.NAME , 1), ' ', CSR_NUMBER) AS REFERENCE_NO,
CSR.SALE_INVOICE_NO AS INVOICE_NO, CUST.NAME AS CUSTOMER_NAME, SUM(AMOUNT) AS AMOUNT,
DATE, FWL.CREATED_DATE, CSR.CREATED_DATE AS ORIG_CREATED_DATE
FROM CASH_SALE_RETURN_ITEM CSRI
INNER JOIN CASH_SALE_RETURN CSR ON CSR.CASH_SALE_RETURN_ID = CSRI.CASH_SALE_RETURN_ID
INNER JOIN COMPANY C ON C.COMPANY_ID = CSR.COMPANY_ID
INNER JOIN AR_CUSTOMER CUST ON CUST.AR_CUSTOMER_ID = CSR.AR_CUSTOMER_ID
INNER JOIN FORM_WORKFLOW FW ON FW.FORM_WORKFLOW_ID = CSR.FORM_WORKFLOW_ID
INNER JOIN (SELECT FORM_WORKFLOW_ID, FORM_STATUS_ID, CREATED_BY, CREATED_DATE
FROM FORM_WORKFLOW_LOG GROUP BY FORM_WORKFLOW_ID, FORM_STATUS_ID) FWL 
ON FWL.FORM_WORKFLOW_ID = FW.FORM_WORKFLOW_ID
WHERE
IF (IN_STATUS = -1, FW.CURRENT_STATUS_ID = 4 OR IS_COMPLETE = 1, 
FW.CURRENT_STATUS_ID != 4 AND IS_COMPLETE = 1)
AND FWL.FORM_STATUS_ID = FW.CURRENT_STATUS_ID
AND FWL.CREATED_BY = IN_USER_ID
AND C.COMPANY_ID = IN_COMPANY_ID
AND DATE = IN_DATE
AND CSR.CASH_SALE_TYPE_ID=3
GROUP BY CSR.CASH_SALE_RETURN_ID

UNION ALL

SELECT FW.CURRENT_STATUS_ID, TIME(CSR.CREATED_DATE) AS TIME, CONCAT('CSR-CPOS ', LEFT(C.NAME , 1), ' ', CSR_NUMBER) AS REFERENCE_NO,
CSR.SALE_INVOICE_NO AS INVOICE_NO, CUST.NAME AS CUSTOMER_NAME, SUM(AMOUNT) AS AMOUNT,
DATE, FWL.CREATED_DATE, CSR.CREATED_DATE AS ORIG_CREATED_DATE
FROM CASH_SALE_RETURN_ITEM CSRI
INNER JOIN CASH_SALE_RETURN CSR ON CSR.CASH_SALE_RETURN_ID = CSRI.CASH_SALE_RETURN_ID
INNER JOIN COMPANY C ON C.COMPANY_ID = CSR.COMPANY_ID
INNER JOIN AR_CUSTOMER CUST ON CUST.AR_CUSTOMER_ID = CSR.AR_CUSTOMER_ID
INNER JOIN FORM_WORKFLOW FW ON FW.FORM_WORKFLOW_ID = CSR.FORM_WORKFLOW_ID
INNER JOIN (SELECT FORM_WORKFLOW_ID, FORM_STATUS_ID, CREATED_BY, CREATED_DATE
FROM FORM_WORKFLOW_LOG GROUP BY FORM_WORKFLOW_ID, FORM_STATUS_ID) FWL 
ON FWL.FORM_WORKFLOW_ID = FW.FORM_WORKFLOW_ID
WHERE
IF (IN_STATUS = -1, FW.CURRENT_STATUS_ID = 4 OR IS_COMPLETE = 1, 
FW.CURRENT_STATUS_ID != 4 AND IS_COMPLETE = 1)
AND FWL.FORM_STATUS_ID = FW.CURRENT_STATUS_ID
AND FWL.CREATED_BY = IN_USER_ID
AND C.COMPANY_ID = IN_COMPANY_ID
AND DATE = IN_DATE
AND CSR.CASH_SALE_TYPE_ID=4
GROUP BY CSR.CASH_SALE_RETURN_ID

UNION ALL

SELECT FW.CURRENT_STATUS_ID, TIME(CSR.CREATED_DATE) AS TIME, CONCAT('CSR ', LEFT(C.NAME , 1), ' ', CSR_NUMBER) AS REFERENCE_NO,
CSR.SALE_INVOICE_NO AS INVOICE_NO, CUST.NAME AS CUSTOMER_NAME, SUM(AMOUNT) AS AMOUNT,
DATE, FWL.CREATED_DATE, CSR.CREATED_DATE AS ORIG_CREATED_DATE
FROM CASH_SALE_RETURN_ITEM CSRI
INNER JOIN CASH_SALE_RETURN CSR ON CSR.CASH_SALE_RETURN_ID = CSRI.CASH_SALE_RETURN_ID
INNER JOIN COMPANY C ON C.COMPANY_ID = CSR.COMPANY_ID
INNER JOIN AR_CUSTOMER CUST ON CUST.AR_CUSTOMER_ID = CSR.AR_CUSTOMER_ID
INNER JOIN FORM_WORKFLOW FW ON FW.FORM_WORKFLOW_ID = CSR.FORM_WORKFLOW_ID
INNER JOIN (SELECT FORM_WORKFLOW_ID, FORM_STATUS_ID, CREATED_BY, CREATED_DATE
FROM FORM_WORKFLOW_LOG GROUP BY FORM_WORKFLOW_ID, FORM_STATUS_ID) FWL 
ON FWL.FORM_WORKFLOW_ID = FW.FORM_WORKFLOW_ID
WHERE
IF (IN_STATUS = -1, FW.CURRENT_STATUS_ID = 4 OR IS_COMPLETE = 1, 
FW.CURRENT_STATUS_ID != 4 AND IS_COMPLETE = 1)
AND FWL.FORM_STATUS_ID = FW.CURRENT_STATUS_ID
AND FWL.CREATED_BY = IN_USER_ID
AND C.COMPANY_ID = IN_COMPANY_ID
AND DATE = IN_DATE
AND CSR.CASH_SALE_TYPE_ID=5
GROUP BY CSR.CASH_SALE_RETURN_ID

UNION ALL

SELECT FW.CURRENT_STATUS_ID, TIME(AR.CREATED_DATE) AS TIME, CONCAT('AC ', LEFT(C.NAME , 1), ' ', SEQUENCE_NO) AS REFERENCE_NO,
AR.RECEIPT_NUMBER AS INVOICE_NO, CUST.NAME AS CUSTOMER_NAME,  SUM(AMOUNT) AS AMOUNT,
RECEIPT_DATE AS DATE, FWL.CREATED_DATE, AR.CREATED_DATE AS ORIG_CREATED_DATE
FROM AR_RECEIPT AR 
INNER JOIN COMPANY C ON C.COMPANY_ID = AR.COMPANY_ID
INNER JOIN AR_CUSTOMER CUST ON CUST.AR_CUSTOMER_ID = AR.AR_CUSTOMER_ID
INNER JOIN FORM_WORKFLOW FW ON FW.FORM_WORKFLOW_ID = AR.FORM_WORKFLOW_ID
INNER JOIN (SELECT FORM_WORKFLOW_ID, FORM_STATUS_ID, CREATED_BY, CREATED_DATE
FROM FORM_WORKFLOW_LOG GROUP BY FORM_WORKFLOW_ID, FORM_STATUS_ID) FWL 
ON FWL.FORM_WORKFLOW_ID = FW.FORM_WORKFLOW_ID
WHERE
IF (IN_STATUS = -1, FW.CURRENT_STATUS_ID = 4 OR FW.CURRENT_STATUS_ID != 4, 
FW.CURRENT_STATUS_ID != 4)
AND FWL.FORM_STATUS_ID = FW.CURRENT_STATUS_ID
AND FWL.CREATED_BY = IN_USER_ID
AND RECEIPT_DATE = IN_DATE
AND C.COMPANY_ID = IN_COMPANY_ID
GROUP BY AR_RECEIPT_ID

UNION ALL

SELECT FW.CURRENT_STATUS_ID, TIME(CAP.CREATED_DATE) AS TIME, CONCAT('CAP ', LEFT(C.NAME , 1), ' ', CAP_NUMBER) AS REFERENCE_NO, 
CAP.SALE_INVOICE_NO AS INVOICE_NO, CUST.NAME AS CUSTOMER_NAME, 
SUM(AMOUNT) + COALESCE ((SELECT SUM(AMOUNT) FROM CAP_AR_LINE AL
WHERE AL.CUSTOMER_ADVANCE_PAYMENT_ID = CAPI.CUSTOMER_ADVANCE_PAYMENT_ID
GROUP BY CAP.CUSTOMER_ADVANCE_PAYMENT_ID), 0) AS AMOUNT,
RECEIPT_DATE AS DATE, FWL.CREATED_DATE, CAP.CREATED_DATE AS ORIG_CREATED_DATE 
FROM CUSTOMER_ADVANCE_PAYMENT_ITEM CAPI
INNER JOIN CUSTOMER_ADVANCE_PAYMENT CAP ON CAP.CUSTOMER_ADVANCE_PAYMENT_ID = CAPI.CUSTOMER_ADVANCE_PAYMENT_ID
INNER JOIN COMPANY C ON C.COMPANY_ID = CAP.COMPANY_ID
INNER JOIN AR_CUSTOMER CUST ON CUST.AR_CUSTOMER_ID = CAP.AR_CUSTOMER_ID
INNER JOIN FORM_WORKFLOW FW ON FW.FORM_WORKFLOW_ID = CAP.FORM_WORKFLOW_ID
INNER JOIN (SELECT FORM_WORKFLOW_ID, FORM_STATUS_ID, CREATED_BY, CREATED_DATE 
FROM FORM_WORKFLOW_LOG GROUP BY FORM_WORKFLOW_ID, FORM_STATUS_ID) FWL 
ON FWL.FORM_WORKFLOW_ID = FW.FORM_WORKFLOW_ID
WHERE 
IF (IN_STATUS = -1, FW.CURRENT_STATUS_ID = 4 OR FW.CURRENT_STATUS_ID != 4 AND FW.CURRENT_STATUS_ID != 1, 
FW.CURRENT_STATUS_ID != 1 AND FW.CURRENT_STATUS_ID != 4)
AND FWL.FORM_STATUS_ID = FW.CURRENT_STATUS_ID
AND FWL.CREATED_BY = IN_USER_ID
AND RECEIPT_DATE = IN_DATE
AND C.COMPANY_ID = IN_COMPANY_ID
GROUP BY CAP.CUSTOMER_ADVANCE_PAYMENT_ID

) AS DCC ORDER BY REFERENCE_NO;

ELSEIF IN_ORDER_BY = 'INVOICE_NO' THEN

SELECT CURRENT_STATUS_ID, TIME, REFERENCE_NO, INVOICE_NO, CUSTOMER_NAME, AMOUNT, DATE, CREATED_DATE, ORIG_CREATED_DATE  FROM (

-- Cash Sale 
SELECT  FW.CURRENT_STATUS_ID, TIME(CS.CREATED_DATE) AS TIME, CONCAT('CS ', LEFT(C.NAME , 1), ' ', CS_NUMBER) AS REFERENCE_NO, 
CS.SALE_INVOICE_NO AS INVOICE_NO, CUST.NAME AS CUSTOMER_NAME, (SUM(CSI.AMOUNT + COALESCE(CSI.VAT_AMOUNT, 0))
+ COALESCE((SELECT SUM(AMOUNT + (COALESCE(AL.QUANTITY, 0) * COALESCE(AL.VAT_AMOUNT, 0))) FROM CASH_SALE_AR_LINE AL
WHERE AL.CASH_SALE_ID = CSI.CASH_SALE_ID GROUP BY CS.CASH_SALE_ID), 0)) - COALESCE(WT_AMOUNT, 0) AS AMOUNT,
RECEIPT_DATE AS DATE, FWL.CREATED_DATE, CS.CREATED_DATE AS ORIG_CREATED_DATE
FROM CASH_SALE_ITEM CSI
INNER JOIN CASH_SALE CS ON CS.CASH_SALE_ID = CSI.CASH_SALE_ID
INNER JOIN COMPANY C ON C.COMPANY_ID = CS.COMPANY_ID
INNER JOIN AR_CUSTOMER CUST ON CUST.AR_CUSTOMER_ID = CS.AR_CUSTOMER_ID
INNER JOIN FORM_WORKFLOW FW ON FW.FORM_WORKFLOW_ID = CS.FORM_WORKFLOW_ID
INNER JOIN (SELECT FORM_WORKFLOW_ID, FORM_STATUS_ID, CREATED_BY, CREATED_DATE 
FROM FORM_WORKFLOW_LOG GROUP BY FORM_WORKFLOW_ID, FORM_STATUS_ID) FWL 
ON FWL.FORM_WORKFLOW_ID = FW.FORM_WORKFLOW_ID
WHERE IF (IN_STATUS = -1, FW.CURRENT_STATUS_ID = 4 OR IS_COMPLETE = 1, FW.CURRENT_STATUS_ID != 4 AND IS_COMPLETE = 1)
AND FWL.FORM_STATUS_ID = FW.CURRENT_STATUS_ID
AND FWL.CREATED_BY = IN_USER_ID
AND RECEIPT_DATE = IN_DATE
AND CS.COMPANY_ID = IN_COMPANY_ID
AND CS.CASH_SALE_TYPE_ID=1
GROUP BY CS.CASH_SALE_ID

UNION ALL 

SELECT FW.CURRENT_STATUS_ID, TIME(CS.CREATED_DATE) AS TIME, CONCAT('CS-W ', LEFT(C.NAME , 1), ' ', CS_NUMBER) AS REFERENCE_NO, 
CS.SALE_INVOICE_NO AS INVOICE_NO, 
CUST.NAME AS CUSTOMER_NAME,
SUM(AMOUNT) + COALESCE ((SELECT SUM(AMOUNT) FROM CASH_SALE_AR_LINE AL
WHERE AL.CASH_SALE_ID = CSI.CASH_SALE_ID
GROUP BY CS.CASH_SALE_ID), 0) AS AMOUNT,
RECEIPT_DATE AS DATE, FWL.CREATED_DATE, CS.CREATED_DATE AS ORIG_CREATED_DATE
FROM CASH_SALE_ITEM CSI
INNER JOIN CASH_SALE CS ON CS.CASH_SALE_ID = CSI.CASH_SALE_ID
INNER JOIN COMPANY C ON C.COMPANY_ID = CS.COMPANY_ID
INNER JOIN AR_CUSTOMER CUST ON CUST.AR_CUSTOMER_ID = CS.AR_CUSTOMER_ID
INNER JOIN FORM_WORKFLOW FW ON FW.FORM_WORKFLOW_ID = CS.FORM_WORKFLOW_ID
INNER JOIN (SELECT FORM_WORKFLOW_ID, FORM_STATUS_ID, CREATED_BY, CREATED_DATE 
FROM FORM_WORKFLOW_LOG GROUP BY FORM_WORKFLOW_ID, FORM_STATUS_ID) FWL 
ON FWL.FORM_WORKFLOW_ID = FW.FORM_WORKFLOW_ID
WHERE
IF (IN_STATUS = -1, FW.CURRENT_STATUS_ID = 4 OR IS_COMPLETE = 1, 
FW.CURRENT_STATUS_ID != 4 AND IS_COMPLETE = 1)
AND FWL.FORM_STATUS_ID = FW.CURRENT_STATUS_ID
AND FWL.CREATED_BY = IN_USER_ID
AND RECEIPT_DATE = IN_DATE
AND CS.COMPANY_ID = IN_COMPANY_ID
AND CS.CASH_SALE_TYPE_ID=2
GROUP BY CS.CASH_SALE_ID

UNION ALL

SELECT FW.CURRENT_STATUS_ID, TIME(CS.CREATED_DATE) AS TIME, CONCAT('CS-IS ', LEFT(C.NAME , 1), ' ', CS_NUMBER) AS REFERENCE_NO,
CS.SALE_INVOICE_NO AS INVOICE_NO, 
CUST.NAME AS CUSTOMER_NAME,
SUM(AMOUNT) + COALESCE ((SELECT SUM(AMOUNT) FROM CASH_SALE_AR_LINE AL
WHERE AL.CASH_SALE_ID = CSI.CASH_SALE_ID
GROUP BY CS.CASH_SALE_ID), 0) AS AMOUNT,
RECEIPT_DATE AS DATE, FWL.CREATED_DATE, CS.CREATED_DATE AS ORIG_CREATED_DATE
FROM CASH_SALE_ITEM CSI
INNER JOIN CASH_SALE CS ON CS.CASH_SALE_ID = CSI.CASH_SALE_ID
INNER JOIN COMPANY C ON C.COMPANY_ID = CS.COMPANY_ID
INNER JOIN AR_CUSTOMER CUST ON CUST.AR_CUSTOMER_ID = CS.AR_CUSTOMER_ID
INNER JOIN FORM_WORKFLOW FW ON FW.FORM_WORKFLOW_ID = CS.FORM_WORKFLOW_ID
INNER JOIN (SELECT FORM_WORKFLOW_ID, FORM_STATUS_ID, CREATED_BY, CREATED_DATE
FROM FORM_WORKFLOW_LOG GROUP BY FORM_WORKFLOW_ID, FORM_STATUS_ID) FWL 
ON FWL.FORM_WORKFLOW_ID = FW.FORM_WORKFLOW_ID
WHERE
IF (IN_STATUS = -1, FW.CURRENT_STATUS_ID = 4 OR IS_COMPLETE = 1, 
FW.CURRENT_STATUS_ID != 4 AND IS_COMPLETE = 1)
AND FWL.FORM_STATUS_ID = FW.CURRENT_STATUS_ID
AND FWL.CREATED_BY = IN_USER_ID
AND RECEIPT_DATE = IN_DATE
AND CS.COMPANY_ID = IN_COMPANY_ID
AND CS.CASH_SALE_TYPE_ID=3
GROUP BY CS.CASH_SALE_ID

UNION ALL 

SELECT FW.CURRENT_STATUS_ID, TIME(CS.CREATED_DATE) AS TIME, CONCAT('CS-CPOS ', LEFT(C.NAME , 1), ' ', CS_NUMBER) AS REFERENCE_NO, 
CS.SALE_INVOICE_NO AS INVOICE_NO, 
CUST.NAME AS CUSTOMER_NAME,
SUM(AMOUNT) + COALESCE ((SELECT SUM(AMOUNT) FROM CASH_SALE_AR_LINE AL
WHERE AL.CASH_SALE_ID = CSI.CASH_SALE_ID
GROUP BY CS.CASH_SALE_ID), 0) AS AMOUNT,
RECEIPT_DATE AS DATE, FWL.CREATED_DATE, CS.CREATED_DATE AS ORIG_CREATED_DATE
FROM CASH_SALE_ITEM CSI
INNER JOIN CASH_SALE CS ON CS.CASH_SALE_ID = CSI.CASH_SALE_ID
INNER JOIN COMPANY C ON C.COMPANY_ID = CS.COMPANY_ID
INNER JOIN AR_CUSTOMER CUST ON CUST.AR_CUSTOMER_ID = CS.AR_CUSTOMER_ID
INNER JOIN FORM_WORKFLOW FW ON FW.FORM_WORKFLOW_ID = CS.FORM_WORKFLOW_ID
INNER JOIN (SELECT FORM_WORKFLOW_ID, FORM_STATUS_ID, CREATED_BY, CREATED_DATE 
FROM FORM_WORKFLOW_LOG GROUP BY FORM_WORKFLOW_ID, FORM_STATUS_ID) FWL 
ON FWL.FORM_WORKFLOW_ID = FW.FORM_WORKFLOW_ID
WHERE
IF (IN_STATUS = -1, FW.CURRENT_STATUS_ID = 4 OR IS_COMPLETE = 1, 
FW.CURRENT_STATUS_ID != 4 AND IS_COMPLETE = 1)
AND FWL.FORM_STATUS_ID = FW.CURRENT_STATUS_ID
AND FWL.CREATED_BY = IN_USER_ID
AND RECEIPT_DATE = IN_DATE
AND CS.COMPANY_ID = IN_COMPANY_ID
AND CS.CASH_SALE_TYPE_ID=4
GROUP BY CS.CASH_SALE_ID

UNION ALL

SELECT FW.CURRENT_STATUS_ID, TIME(CS.CREATED_DATE) AS TIME, CONCAT('CS-P ', LEFT(C.NAME , 1), ' ', CS_NUMBER) AS REFERENCE_NO,
CS.SALE_INVOICE_NO AS INVOICE_NO, CUST.NAME AS CUSTOMER_NAME,
SUM(AMOUNT) + COALESCE ((SELECT SUM(AMOUNT) FROM CASH_SALE_AR_LINE AL
WHERE AL.CASH_SALE_ID = CSI.CASH_SALE_ID
GROUP BY CS.CASH_SALE_ID), 0) AS AMOUNT,
RECEIPT_DATE AS DATE, FWL.CREATED_DATE, CS.CREATED_DATE AS ORIG_CREATED_DATE
FROM CASH_SALE_ITEM CSI
INNER JOIN CASH_SALE CS ON CS.CASH_SALE_ID = CSI.CASH_SALE_ID
INNER JOIN COMPANY C ON C.COMPANY_ID = CS.COMPANY_ID
INNER JOIN AR_CUSTOMER CUST ON CUST.AR_CUSTOMER_ID = CS.AR_CUSTOMER_ID
INNER JOIN FORM_WORKFLOW FW ON FW.FORM_WORKFLOW_ID = CS.FORM_WORKFLOW_ID
INNER JOIN (SELECT FORM_WORKFLOW_ID, FORM_STATUS_ID, CREATED_BY, CREATED_DATE
FROM FORM_WORKFLOW_LOG GROUP BY FORM_WORKFLOW_ID, FORM_STATUS_ID) FWL 
ON FWL.FORM_WORKFLOW_ID = FW.FORM_WORKFLOW_ID
WHERE
IF (IN_STATUS = -1, FW.CURRENT_STATUS_ID = 4 OR IS_COMPLETE = 1, 
FW.CURRENT_STATUS_ID != 4 AND IS_COMPLETE = 1)
AND FWL.FORM_STATUS_ID = FW.CURRENT_STATUS_ID
AND FWL.CREATED_BY = IN_USER_ID
AND RECEIPT_DATE = IN_DATE
AND CS.COMPANY_ID = IN_COMPANY_ID
AND CS.CASH_SALE_TYPE_ID = 6
GROUP BY CS.CASH_SALE_ID

UNION ALL

SELECT FW.CURRENT_STATUS_ID, TIME(CSR.CREATED_DATE) AS TIME, CONCAT('CSR ', LEFT(C.NAME , 1), ' ', CSR_NUMBER) AS REFERENCE_NO,
CSR.SALE_INVOICE_NO AS INVOICE_NO,  CUST.NAME AS CUSTOMER_NAME, SUM(CSRI.AMOUNT + COALESCE(CSRI.VAT_AMOUNT, 0)) - COALESCE(WT_AMOUNT, 0) AS AMOUNT,
DATE, FWL.CREATED_DATE, CSR.CREATED_DATE AS ORIG_CREATED_DATE
FROM CASH_SALE_RETURN_ITEM CSRI
INNER JOIN CASH_SALE_RETURN CSR ON CSR.CASH_SALE_RETURN_ID = CSRI.CASH_SALE_RETURN_ID
INNER JOIN COMPANY C ON C.COMPANY_ID = CSR.COMPANY_ID
INNER JOIN AR_CUSTOMER CUST ON CUST.AR_CUSTOMER_ID = CSR.AR_CUSTOMER_ID
INNER JOIN FORM_WORKFLOW FW ON FW.FORM_WORKFLOW_ID = CSR.FORM_WORKFLOW_ID
INNER JOIN (SELECT FORM_WORKFLOW_ID, FORM_STATUS_ID, CREATED_BY, CREATED_DATE
FROM FORM_WORKFLOW_LOG GROUP BY FORM_WORKFLOW_ID, FORM_STATUS_ID) FWL 
ON FWL.FORM_WORKFLOW_ID = FW.FORM_WORKFLOW_ID
WHERE IF (IN_STATUS = -1, (FW.CURRENT_STATUS_ID = 4 OR IS_COMPLETE = 1), (FW.CURRENT_STATUS_ID != 4 AND IS_COMPLETE = 1))
AND FWL.FORM_STATUS_ID = FW.CURRENT_STATUS_ID
AND FWL.CREATED_BY = IN_USER_ID
AND C.COMPANY_ID = IN_COMPANY_ID
AND DATE = IN_DATE
AND CSR.CASH_SALE_TYPE_ID=1
GROUP BY CSR.CASH_SALE_RETURN_ID

UNION ALL 

SELECT FW.CURRENT_STATUS_ID, TIME(CSR.CREATED_DATE) AS TIME, CONCAT('CSR W ', LEFT(C.NAME , 1), ' ', CSR_NUMBER) AS REFERENCE_NO,
CSR.SALE_INVOICE_NO AS INVOICE_NO, 
CUST.NAME AS CUSTOMER_NAME, SUM(AMOUNT) AS AMOUNT,
DATE, FWL.CREATED_DATE, CSR.CREATED_DATE AS ORIG_CREATED_DATE
FROM CASH_SALE_RETURN_ITEM CSRI
INNER JOIN CASH_SALE_RETURN CSR ON CSR.CASH_SALE_RETURN_ID = CSRI.CASH_SALE_RETURN_ID
INNER JOIN COMPANY C ON C.COMPANY_ID = CSR.COMPANY_ID
INNER JOIN AR_CUSTOMER CUST ON CUST.AR_CUSTOMER_ID = CSR.AR_CUSTOMER_ID
INNER JOIN FORM_WORKFLOW FW ON FW.FORM_WORKFLOW_ID = CSR.FORM_WORKFLOW_ID
INNER JOIN (SELECT FORM_WORKFLOW_ID, FORM_STATUS_ID, CREATED_BY, CREATED_DATE
FROM FORM_WORKFLOW_LOG GROUP BY FORM_WORKFLOW_ID, FORM_STATUS_ID) FWL
ON FWL.FORM_WORKFLOW_ID = FW.FORM_WORKFLOW_ID
WHERE
IF (IN_STATUS = -1, FW.CURRENT_STATUS_ID = 4 OR IS_COMPLETE = 1, 
FW.CURRENT_STATUS_ID != 4 AND IS_COMPLETE = 1)
AND FWL.FORM_STATUS_ID = FW.CURRENT_STATUS_ID
AND FWL.CREATED_BY = IN_USER_ID
AND C.COMPANY_ID = IN_COMPANY_ID
AND DATE = IN_DATE
AND CSR.CASH_SALE_TYPE_ID=2
GROUP BY CSR.CASH_SALE_RETURN_ID

UNION ALL

SELECT FW.CURRENT_STATUS_ID, TIME(CSR.CREATED_DATE) AS TIME, CONCAT('CSR-IS ', LEFT(C.NAME , 1), ' ', CSR_NUMBER) AS REFERENCE_NO,
CSR.SALE_INVOICE_NO AS INVOICE_NO,  
CUST.NAME AS CUSTOMER_NAME, SUM(AMOUNT) AS AMOUNT,
DATE, FWL.CREATED_DATE, CSR.CREATED_DATE AS ORIG_CREATED_DATE
FROM CASH_SALE_RETURN_ITEM CSRI
INNER JOIN CASH_SALE_RETURN CSR ON CSR.CASH_SALE_RETURN_ID = CSRI.CASH_SALE_RETURN_ID
INNER JOIN COMPANY C ON C.COMPANY_ID = CSR.COMPANY_ID
INNER JOIN AR_CUSTOMER CUST ON CUST.AR_CUSTOMER_ID = CSR.AR_CUSTOMER_ID
INNER JOIN FORM_WORKFLOW FW ON FW.FORM_WORKFLOW_ID = CSR.FORM_WORKFLOW_ID
INNER JOIN (SELECT FORM_WORKFLOW_ID, FORM_STATUS_ID, CREATED_BY, CREATED_DATE
FROM FORM_WORKFLOW_LOG GROUP BY FORM_WORKFLOW_ID, FORM_STATUS_ID) FWL 
ON FWL.FORM_WORKFLOW_ID = FW.FORM_WORKFLOW_ID
WHERE
IF (IN_STATUS = -1, FW.CURRENT_STATUS_ID = 4 OR IS_COMPLETE = 1, 
FW.CURRENT_STATUS_ID != 4 AND IS_COMPLETE = 1)
AND FWL.FORM_STATUS_ID = FW.CURRENT_STATUS_ID
AND FWL.CREATED_BY = IN_USER_ID
AND C.COMPANY_ID = IN_COMPANY_ID
AND DATE = IN_DATE
AND CSR.CASH_SALE_TYPE_ID=3
GROUP BY CSR.CASH_SALE_RETURN_ID

UNION ALL

SELECT FW.CURRENT_STATUS_ID, TIME(CSR.CREATED_DATE) AS TIME, CONCAT('CSR-CPOS ', LEFT(C.NAME , 1), ' ', CSR_NUMBER) AS REFERENCE_NO,
CSR.SALE_INVOICE_NO AS INVOICE_NO,  
CUST.NAME AS CUSTOMER_NAME, SUM(AMOUNT) AS AMOUNT,
DATE, FWL.CREATED_DATE, CSR.CREATED_DATE AS ORIG_CREATED_DATE
FROM CASH_SALE_RETURN_ITEM CSRI
INNER JOIN CASH_SALE_RETURN CSR ON CSR.CASH_SALE_RETURN_ID = CSRI.CASH_SALE_RETURN_ID
INNER JOIN COMPANY C ON C.COMPANY_ID = CSR.COMPANY_ID
INNER JOIN AR_CUSTOMER CUST ON CUST.AR_CUSTOMER_ID = CSR.AR_CUSTOMER_ID
INNER JOIN FORM_WORKFLOW FW ON FW.FORM_WORKFLOW_ID = CSR.FORM_WORKFLOW_ID
INNER JOIN (SELECT FORM_WORKFLOW_ID, FORM_STATUS_ID, CREATED_BY, CREATED_DATE
FROM FORM_WORKFLOW_LOG GROUP BY FORM_WORKFLOW_ID, FORM_STATUS_ID) FWL 
ON FWL.FORM_WORKFLOW_ID = FW.FORM_WORKFLOW_ID
WHERE
IF (IN_STATUS = -1, FW.CURRENT_STATUS_ID = 4 OR IS_COMPLETE = 1, 
FW.CURRENT_STATUS_ID != 4 AND IS_COMPLETE = 1)
AND FWL.FORM_STATUS_ID = FW.CURRENT_STATUS_ID
AND FWL.CREATED_BY = IN_USER_ID
AND C.COMPANY_ID = IN_COMPANY_ID
AND DATE = IN_DATE
AND CSR.CASH_SALE_TYPE_ID=4
GROUP BY CSR.CASH_SALE_RETURN_ID

UNION ALL

SELECT FW.CURRENT_STATUS_ID, TIME(AR.CREATED_DATE) AS TIME, CONCAT('AC ', LEFT(C.NAME , 1), ' ', SEQUENCE_NO) AS REFERENCE_NO,
AR.RECEIPT_NUMBER AS INVOICE_NO, 
CUST.NAME AS CUSTOMER_NAME,  SUM(AMOUNT) AS AMOUNT,
RECEIPT_DATE AS DATE, FWL.CREATED_DATE, AR.CREATED_DATE AS ORIG_CREATED_DATE
FROM AR_RECEIPT AR 
INNER JOIN COMPANY C ON C.COMPANY_ID = AR.COMPANY_ID
INNER JOIN AR_CUSTOMER CUST ON CUST.AR_CUSTOMER_ID = AR.AR_CUSTOMER_ID
INNER JOIN FORM_WORKFLOW FW ON FW.FORM_WORKFLOW_ID = AR.FORM_WORKFLOW_ID
INNER JOIN (SELECT FORM_WORKFLOW_ID, FORM_STATUS_ID, CREATED_BY, CREATED_DATE
FROM FORM_WORKFLOW_LOG GROUP BY FORM_WORKFLOW_ID, FORM_STATUS_ID) FWL 
ON FWL.FORM_WORKFLOW_ID = FW.FORM_WORKFLOW_ID
WHERE
IF (IN_STATUS = -1, FW.CURRENT_STATUS_ID = 4 OR FW.CURRENT_STATUS_ID != 4, 
FW.CURRENT_STATUS_ID != 4)
AND FWL.FORM_STATUS_ID = FW.CURRENT_STATUS_ID
AND FWL.CREATED_BY = IN_USER_ID
AND RECEIPT_DATE = IN_DATE
AND C.COMPANY_ID = IN_COMPANY_ID
GROUP BY AR_RECEIPT_ID

UNION ALL

SELECT FW.CURRENT_STATUS_ID, TIME(CAP.CREATED_DATE) AS TIME, CONCAT('CAP ', LEFT(C.NAME , 1), ' ', CAP_NUMBER) AS REFERENCE_NO, 
CAP.SALE_INVOICE_NO AS INVOICE_NO, CUST.NAME AS CUSTOMER_NAME, 
SUM(AMOUNT) + COALESCE ((SELECT SUM(AMOUNT) FROM CAP_AR_LINE AL
WHERE AL.CUSTOMER_ADVANCE_PAYMENT_ID = CAPI.CUSTOMER_ADVANCE_PAYMENT_ID
GROUP BY CAP.CUSTOMER_ADVANCE_PAYMENT_ID), 0) AS AMOUNT,
RECEIPT_DATE AS DATE, FWL.CREATED_DATE, CAP.CREATED_DATE AS ORIG_CREATED_DATE 
FROM CUSTOMER_ADVANCE_PAYMENT_ITEM CAPI
INNER JOIN CUSTOMER_ADVANCE_PAYMENT CAP ON CAP.CUSTOMER_ADVANCE_PAYMENT_ID = CAPI.CUSTOMER_ADVANCE_PAYMENT_ID
INNER JOIN COMPANY C ON C.COMPANY_ID = CAP.COMPANY_ID
INNER JOIN AR_CUSTOMER CUST ON CUST.AR_CUSTOMER_ID = CAP.AR_CUSTOMER_ID
INNER JOIN FORM_WORKFLOW FW ON FW.FORM_WORKFLOW_ID = CAP.FORM_WORKFLOW_ID
INNER JOIN (SELECT FORM_WORKFLOW_ID, FORM_STATUS_ID, CREATED_BY, CREATED_DATE 
FROM FORM_WORKFLOW_LOG GROUP BY FORM_WORKFLOW_ID, FORM_STATUS_ID) FWL 
ON FWL.FORM_WORKFLOW_ID = FW.FORM_WORKFLOW_ID
WHERE
IF (IN_STATUS = -1, FW.CURRENT_STATUS_ID = 4 OR FW.CURRENT_STATUS_ID != 4 AND FW.CURRENT_STATUS_ID != 1, 
FW.CURRENT_STATUS_ID != 1 AND FW.CURRENT_STATUS_ID != 4)
AND FWL.FORM_STATUS_ID = FW.CURRENT_STATUS_ID
AND FWL.CREATED_BY = IN_USER_ID
AND RECEIPT_DATE = IN_DATE
AND C.COMPANY_ID = IN_COMPANY_ID
GROUP BY CAP.CUSTOMER_ADVANCE_PAYMENT_ID

) AS DCC ORDER BY INVOICE_NO+00,INVOICE_NO+0 DESC, INVOICE_NO;
END IF;
END//