-- Description: Stored proceedure that will get the account balances


Delimiter //
DROP procedure IF EXISTS GET_ACCOUNT_BALANCES;//
CREATE procedure GET_ACCOUNT_BALANCES (IN IN_COMPANY_ID INT, IN IN_AS_OF_DATE DATE)
BEGIN 
-- General Ledger
-- Debit and credit of GL
SELECT A.ACCOUNT_ID, sum(DEBIT) as DEBIT, sum(CREDIT) as CREDIT FROM (
SELECT 'GL' as SOURCE, AC.ACCOUNT_ID, SUM(GLE.AMOUNT) as DEBIT, 0 as CREDIT
FROM GL_ENTRY GLE
INNER JOIN GENERAL_LEDGER GL ON GL.GENERAL_LEDGER_ID = GLE.GENERAL_LEDGER_ID
INNER JOIN ACCOUNT_COMBINATION AC ON AC.ACCOUNT_COMBINATION_ID = GLE.ACCOUNT_COMBINATION_ID 
INNER JOIN FORM_WORKFLOW FW ON FW.FORM_WORKFLOW_ID = GL.FORM_WORKFLOW_ID
INNER JOIN FORM_WORKFLOW_LOG FWL ON FWL.FORM_WORKFLOW_ID = FW.FORM_WORKFLOW_ID
WHERE FW.CURRENT_STATUS_ID !=4 
AND FWL.FORM_STATUS_ID=6
AND IS_DEBIT = 1
AND AC.COMPANY_ID = IN_COMPANY_ID
AND GL.GL_DATE <= IN_AS_OF_DATE
GROUP BY AC.ACCOUNT_ID
UNION ALL 
SELECT 'GL' as SOURCE, AC.ACCOUNT_ID, 0 as DEBIT, SUM(GLE.AMOUNT) as CREDIT
FROM GL_ENTRY GLE
INNER JOIN GENERAL_LEDGER GL ON GL.GENERAL_LEDGER_ID = GLE.GENERAL_LEDGER_ID
INNER JOIN ACCOUNT_COMBINATION AC ON AC.ACCOUNT_COMBINATION_ID = GLE.ACCOUNT_COMBINATION_ID
INNER JOIN FORM_WORKFLOW FW ON GL.FORM_WORKFLOW_ID = FW.FORM_WORKFLOW_ID
INNER JOIN FORM_WORKFLOW_LOG FWL ON FW.FORM_WORKFLOW_ID = FWL.FORM_WORKFLOW_ID
WHERE FW.CURRENT_STATUS_ID != 4
AND FWL.FORM_STATUS_ID = 6
AND IS_DEBIT = 0
AND AC.COMPANY_ID = IN_COMPANY_ID
AND GL.GL_DATE <= IN_AS_OF_DATE
GROUP BY AC.ACCOUNT_ID
UNION ALL
-- AP Invoice DEBIT and CREDIT
SELECT 'AP INVOICE' as SOURCE, AC.ACCOUNT_ID,  0 as DEBIT, SUM(AI.AMOUNT) as CREDIT
FROM AP_INVOICE AI 
INNER JOIN SUPPLIER_ACCOUNT SA ON SA.SUPPLIER_ACCOUNT_ID = AI.SUPPLIER_ACCOUNT_ID
INNER JOIN ACCOUNT_COMBINATION AC ON AC.ACCOUNT_COMBINATION_ID = SA.DEFAULT_CREDIT_AC_ID
INNER JOIN FORM_WORKFLOW FW ON AI.FORM_WORKFLOW_ID = FW.FORM_WORKFLOW_ID
INNER JOIN FORM_WORKFLOW_LOG FWL ON FW.FORM_WORKFLOW_ID = FWL.FORM_WORKFLOW_ID
WHERE FW.CURRENT_STATUS_ID != 4
AND FWL.FORM_STATUS_ID = 3
AND AI.AMOUNT >= 0
AND AC.COMPANY_ID = IN_COMPANY_ID
AND AI.GL_DATE <= IN_AS_OF_DATE
AND AI.INVOICE_TYPE_ID != 5 AND AI.INVOICE_TYPE_ID != 6
GROUP BY AC.ACCOUNT_ID
UNION ALL

SELECT 'AP INVOICE' as SOURCE, AC.ACCOUNT_ID, SUM(-AI.AMOUNT) as DEBIT, 0 as CREDIT
FROM AP_INVOICE AI 
INNER JOIN SUPPLIER_ACCOUNT SA ON SA.SUPPLIER_ACCOUNT_ID = AI.SUPPLIER_ACCOUNT_ID
INNER JOIN ACCOUNT_COMBINATION AC ON AC.ACCOUNT_COMBINATION_ID = SA.DEFAULT_CREDIT_AC_ID
INNER JOIN FORM_WORKFLOW FW ON AI.FORM_WORKFLOW_ID = FW.FORM_WORKFLOW_ID
INNER JOIN FORM_WORKFLOW_LOG FWL ON FW.FORM_WORKFLOW_ID = FWL.FORM_WORKFLOW_ID
WHERE FW.CURRENT_STATUS_ID != 4
AND FWL.FORM_STATUS_ID = 3
AND AI.AMOUNT < 0
AND AC.COMPANY_ID = IN_COMPANY_ID
AND AI.GL_DATE <= IN_AS_OF_DATE
AND AI.INVOICE_TYPE_ID != 5 AND AI.INVOICE_TYPE_ID != 6
GROUP BY AC.ACCOUNT_ID
UNION ALL

-- AP LINE Debit and CREDIT

SELECT 'AP INVOICE' as SOURCE, AC.ACCOUNT_ID, SUM(AL.AMOUNT) AS DEBIT, 0 as CREDIT 
FROM AP_LINE AL
INNER JOIN AP_INVOICE AI ON AI.AP_INVOICE_ID = AL.AP_INVOICE_ID
INNER JOIN ACCOUNT_COMBINATION AC ON AC.ACCOUNT_COMBINATION_ID = AL.ACCOUNT_COMBINATION_ID
INNER JOIN FORM_WORKFLOW FW ON AI.FORM_WORKFLOW_ID = FW.FORM_WORKFLOW_ID
INNER JOIN FORM_WORKFLOW_LOG FWL ON FW.FORM_WORKFLOW_ID = FWL.FORM_WORKFLOW_ID
WHERE FW.CURRENT_STATUS_ID != 4
AND FWL.FORM_STATUS_ID = 3
AND AL.AMOUNT >= 0
AND AC.COMPANY_ID = IN_COMPANY_ID
AND AI.GL_DATE <= IN_AS_OF_DATE
AND AI.INVOICE_TYPE_ID != 5 AND AI.INVOICE_TYPE_ID != 6
GROUP BY AC.ACCOUNT_ID
UNION ALL 

SELECT 'AP INVOICE' as SOURCE, AC.ACCOUNT_ID, 0 AS DEBIT, SUM(-AL.AMOUNT) as CREDIT 
FROM AP_LINE AL
INNER JOIN AP_INVOICE AI ON AI.AP_INVOICE_ID = AL.AP_INVOICE_ID
INNER JOIN ACCOUNT_COMBINATION AC ON AC.ACCOUNT_COMBINATION_ID = AL.ACCOUNT_COMBINATION_ID
INNER JOIN FORM_WORKFLOW FW ON AI.FORM_WORKFLOW_ID = FW.FORM_WORKFLOW_ID
INNER JOIN FORM_WORKFLOW_LOG FWL ON FW.FORM_WORKFLOW_ID = FWL.FORM_WORKFLOW_ID
WHERE FW.CURRENT_STATUS_ID != 4
AND FWL.FORM_STATUS_ID = 3
AND AL.AMOUNT < 0
AND AC.COMPANY_ID = IN_COMPANY_ID
AND AI.GL_DATE <= IN_AS_OF_DATE
AND AI.INVOICE_TYPE_ID != 5 AND AI.INVOICE_TYPE_ID != 6
GROUP BY AC.ACCOUNT_ID
UNION ALL
-- AP Payment
-- Credit
SELECT 'AP PAYMENT' as SOURCE, AC.ACCOUNT_ID, 0 AS DEBIT, SUM(AP.AMOUNT) as CREDIT 
FROM AP_PAYMENT AP
INNER JOIN BANK_ACCOUNT BA ON BA.BANK_ACCOUNT_ID=AP.BANK_ACCOUNT_ID
INNER JOIN ACCOUNT_COMBINATION AC ON AC.ACCOUNT_COMBINATION_ID = BA.CASH_IN_BANK_ACCT_ID
INNER JOIN FORM_WORKFLOW FW ON AP.FORM_WORKFLOW_ID = FW.FORM_WORKFLOW_ID
WHERE FW.CURRENT_STATUS_ID != 4
AND AP.AMOUNT != 0
AND AC.COMPANY_ID = IN_COMPANY_ID
AND AP.CHECK_DATE <= IN_AS_OF_DATE
GROUP BY AC.ACCOUNT_ID
UNION ALL
-- Credit - AP INVOICE
SELECT 'AP PAYMENT' as SOURCE, AC.ACCOUNT_ID, 0 AS DEBIT, SUM(-AI.PAID_AMOUNT) as CREDIT
FROM AP_PAYMENT_INVOICE AI
INNER JOIN AP_PAYMENT AP ON AP.AP_PAYMENT_ID = AI.AP_PAYMENT_ID
INNER JOIN SUPPLIER_ACCOUNT SA ON SA.SUPPLIER_ACCOUNT_ID = AP.SUPPLIER_ACCOUNT_ID
INNER JOIN ACCOUNT_COMBINATION AC ON AC.ACCOUNT_COMBINATION_ID = SA.DEFAULT_CREDIT_AC_ID
INNER JOIN FORM_WORKFLOW FW ON AP.FORM_WORKFLOW_ID = FW.FORM_WORKFLOW_ID
WHERE FW.CURRENT_STATUS_ID != 4
AND AI.PAID_AMOUNT < 0
AND AC.COMPANY_ID = IN_COMPANY_ID
AND AP.CHECK_DATE <= IN_AS_OF_DATE
GROUP BY AC.ACCOUNT_ID
UNION ALL

-- Debit
SELECT 'AP PAYMENT' as SOURCE, AC.ACCOUNT_ID, SUM(AI.PAID_AMOUNT) AS DEBIT, 0 as CREDIT
FROM AP_PAYMENT_INVOICE AI
INNER JOIN AP_PAYMENT AP ON AP.AP_PAYMENT_ID = AI.AP_PAYMENT_ID
INNER JOIN SUPPLIER_ACCOUNT SA ON SA.SUPPLIER_ACCOUNT_ID = AP.SUPPLIER_ACCOUNT_ID
INNER JOIN ACCOUNT_COMBINATION AC ON AC.ACCOUNT_COMBINATION_ID = SA.DEFAULT_CREDIT_AC_ID
INNER JOIN FORM_WORKFLOW FW ON AP.FORM_WORKFLOW_ID = FW.FORM_WORKFLOW_ID
WHERE FW.CURRENT_STATUS_ID != 4
AND AI.PAID_AMOUNT >= 0
AND AC.COMPANY_ID = IN_COMPANY_ID
AND AP.CHECK_DATE <= IN_AS_OF_DATE
GROUP BY AC.ACCOUNT_ID
UNION ALL
-- AR MISCELLANEOUS
-- Debit debit account combination
SELECT 'AR MISCELLANEOUS' as SOURCE, AC.ACCOUNT_ID, SUM(AM.AMOUNT) AS DEBIT, 0 as CREDIT
FROM AR_MISCELLANEOUS AM
INNER JOIN RECEIPT_METHOD RM ON RM.RECEIPT_METHOD_ID = AM.RECEIPT_METHOD_ID
INNER JOIN ACCOUNT_COMBINATION AC ON AC.ACCOUNT_COMBINATION_ID = RM.DEBIT_ACCOUNT_COMBINATION_ID
INNER JOIN FORM_WORKFLOW FW ON AM.FORM_WORKFLOW_ID = FW.FORM_WORKFLOW_ID
WHERE FW.CURRENT_STATUS_ID != 4
AND RM.DEBIT_ACCOUNT_COMBINATION_ID IS NOT NULL
AND AC.COMPANY_ID = IN_COMPANY_ID
AND AM.MATURITY_DATE <= IN_AS_OF_DATE
GROUP BY AC.ACCOUNT_ID
-- Debit, bank account
UNION ALL 
SELECT 'AR MISCELLANEOUS' as SOURCE, AC.ACCOUNT_ID, SUM(AM.AMOUNT) AS DEBIT, 0 as CREDIT
FROM AR_MISCELLANEOUS AM
INNER JOIN RECEIPT_METHOD RM ON RM.RECEIPT_METHOD_ID = AM.RECEIPT_METHOD_ID
INNER JOIN BANK_ACCOUNT BA ON BA.BANK_ACCOUNT_ID = RM.BANK_ACCOUNT_ID
INNER JOIN ACCOUNT_COMBINATION AC ON AC.ACCOUNT_COMBINATION_ID = BA.CASH_IN_BANK_ACCT_ID
INNER JOIN FORM_WORKFLOW FW ON AM.FORM_WORKFLOW_ID = FW.FORM_WORKFLOW_ID
WHERE FW.CURRENT_STATUS_ID != 4
AND RM.BANK_ACCOUNT_ID IS NOT NULL
AND AC.COMPANY_ID = IN_COMPANY_ID
AND AM.MATURITY_DATE <= IN_AS_OF_DATE
GROUP BY AC.ACCOUNT_ID
UNION ALL
-- Debit
SELECT 'AR MISCELLANEOUS' as SOURCE, AC.ACCOUNT_ID, SUM(-AML.AMOUNT) AS DEBIT, 0 as CREDIT
FROM AR_MISCELLANEOUS_LINE AML
INNER JOIN AR_MISCELLANEOUS AM ON AM.AR_MISCELLANEOUS_ID = AML.AR_MISCELLANEOUS_ID
INNER JOIN AR_LINE_SETUP ALS ON ALS.AR_LINE_SETUP_ID = AML.AR_LINE_SETUP_ID
INNER JOIN ACCOUNT_COMBINATION AC ON AC.ACCOUNT_COMBINATION_ID = ALS.ACCOUNT_COMBINATION_ID
INNER JOIN FORM_WORKFLOW FW ON AM.FORM_WORKFLOW_ID = FW.FORM_WORKFLOW_ID
WHERE FW.CURRENT_STATUS_ID != 4
AND AML.AMOUNT < 0
AND AC.COMPANY_ID = IN_COMPANY_ID
AND AM.MATURITY_DATE <= IN_AS_OF_DATE
GROUP BY AC.ACCOUNT_ID
UNION ALL
-- Credit
SELECT 'AR MISCELLANEOUS' as SOURCE, AC.ACCOUNT_ID, 0 AS DEBIT, SUM(AML.AMOUNT) as CREDIT
FROM AR_MISCELLANEOUS_LINE AML
INNER JOIN AR_MISCELLANEOUS AM ON AM.AR_MISCELLANEOUS_ID = AML.AR_MISCELLANEOUS_ID
INNER JOIN AR_LINE_SETUP ALS ON ALS.AR_LINE_SETUP_ID = AML.AR_LINE_SETUP_ID
INNER JOIN ACCOUNT_COMBINATION AC ON AC.ACCOUNT_COMBINATION_ID = ALS.ACCOUNT_COMBINATION_ID
INNER JOIN FORM_WORKFLOW FW ON AM.FORM_WORKFLOW_ID = FW.FORM_WORKFLOW_ID
WHERE FW.CURRENT_STATUS_ID != 4
AND AML.AMOUNT >= 0
AND AC.COMPANY_ID = IN_COMPANY_ID
AND AM.MATURITY_DATE <= IN_AS_OF_DATE
GROUP BY AC.ACCOUNT_ID
UNION ALL
-- AR Transaction
-- Debit
SELECT 'AR TRANSACTION' as SOURCE, AC.ACCOUNT_ID, SUM(AT.AMOUNT) AS DEBIT, 0 as CREDIT
FROM AR_TRANSACTION AT
INNER JOIN AR_CUSTOMER_ACCOUNT ACA ON ACA.AR_CUSTOMER_ACCOUNT_ID = AT.CUSTOMER_ACCOUNT_ID
INNER JOIN ACCOUNT_COMBINATION AC ON AC.ACCOUNT_COMBINATION_ID = ACA.DEFAULT_DEBIT_AC_ID
INNER JOIN FORM_WORKFLOW FW ON AT.FORM_WORKFLOW_ID = FW.FORM_WORKFLOW_ID
WHERE FW.CURRENT_STATUS_ID = 17
AND AT.AMOUNT >= 0
AND AC.COMPANY_ID = IN_COMPANY_ID
AND AT.GL_DATE <= IN_AS_OF_DATE
AND AT.AR_TRANSACTION_TYPE_ID != 4 AND AT.AR_TRANSACTION_TYPE_ID != 5
GROUP BY AC.ACCOUNT_ID
UNION ALL
-- Credit
SELECT 'AR TRANSACTION' as SOURCE, AC.ACCOUNT_ID, 0 AS DEBIT, SUM(-AT.AMOUNT) as CREDIT
FROM AR_TRANSACTION AT
INNER JOIN AR_CUSTOMER_ACCOUNT ACA ON ACA.AR_CUSTOMER_ACCOUNT_ID = AT.CUSTOMER_ACCOUNT_ID
INNER JOIN ACCOUNT_COMBINATION AC ON AC.ACCOUNT_COMBINATION_ID = ACA.DEFAULT_DEBIT_AC_ID
INNER JOIN FORM_WORKFLOW FW ON AT.FORM_WORKFLOW_ID = FW.FORM_WORKFLOW_ID
WHERE FW.CURRENT_STATUS_ID = 17
AND AT.AMOUNT < 0
AND AC.COMPANY_ID = IN_COMPANY_ID
AND AT.GL_DATE <= IN_AS_OF_DATE
AND AT.AR_TRANSACTION_TYPE_ID != 4 AND AT.AR_TRANSACTION_TYPE_ID != 5
GROUP BY AC.ACCOUNT_ID
UNION ALL
-- AR LINE
-- Credit
SELECT 'AR TRANSACTION' as SOURCE, AC.ACCOUNT_ID, 0 AS DEBIT, SUM(AL.AMOUNT) as CREDIT
FROM AR_LINE AL
INNER JOIN AR_TRANSACTION AT ON AT.AR_TRANSACTION_ID=AL.AR_TRANSACTION_ID
INNER JOIN AR_LINE_SETUP ALS ON ALS.AR_LINE_SETUP_ID = AL.AR_LINE_SETUP_ID
INNER JOIN ACCOUNT_COMBINATION AC ON AC.ACCOUNT_COMBINATION_ID = ALS.ACCOUNT_COMBINATION_ID
INNER JOIN FORM_WORKFLOW FW ON AT.FORM_WORKFLOW_ID = FW.FORM_WORKFLOW_ID
WHERE FW.CURRENT_STATUS_ID = 17
AND AL.AMOUNT >= 0
AND AC.COMPANY_ID = IN_COMPANY_ID
AND AT.GL_DATE <= IN_AS_OF_DATE
AND AT.AR_TRANSACTION_TYPE_ID != 4 AND AT.AR_TRANSACTION_TYPE_ID != 5
GROUP BY AC.ACCOUNT_ID
UNION ALL
-- Debit
SELECT 'AR TRANSACTION' as SOURCE, AC.ACCOUNT_ID, SUM(-AL.AMOUNT) AS DEBIT, 0 as CREDIT
FROM AR_LINE AL
INNER JOIN AR_TRANSACTION AT ON AT.AR_TRANSACTION_ID=AL.AR_TRANSACTION_ID
INNER JOIN AR_LINE_SETUP ALS ON ALS.AR_LINE_SETUP_ID = AL.AR_LINE_SETUP_ID
INNER JOIN ACCOUNT_COMBINATION AC ON AC.ACCOUNT_COMBINATION_ID = ALS.ACCOUNT_COMBINATION_ID
INNER JOIN FORM_WORKFLOW FW ON AT.FORM_WORKFLOW_ID = FW.FORM_WORKFLOW_ID
WHERE FW.CURRENT_STATUS_ID = 17
AND AL.AMOUNT < 0
AND AC.COMPANY_ID = IN_COMPANY_ID
AND AT.GL_DATE <= IN_AS_OF_DATE
AND AT.AR_TRANSACTION_TYPE_ID != 4 AND AT.AR_TRANSACTION_TYPE_ID != 5
GROUP BY AC.ACCOUNT_ID
UNION ALL
-- AR Receipt - not cancelled and  Maturity Date

-- Debit
-- RECEIPT_ID
-- RECEIPT_METHOD
-- Either from DEBIT_ACCOUNT_COMBINATION_ID or BANK_ACCOUNT_ID
SELECT 'AR RECEIPT' as SOURCE, AC.ACCOUNT_ID, SUM(AR.AMOUNT) AS DEBIT, 0 as CREDIT
FROM AR_RECEIPT AR
INNER JOIN RECEIPT_METHOD RM ON RM.RECEIPT_METHOD_ID = AR.RECEIPT_METHOD_ID
INNER JOIN ACCOUNT_COMBINATION AC ON AC.ACCOUNT_COMBINATION_ID = RM.DEBIT_ACCOUNT_COMBINATION_ID
INNER JOIN FORM_WORKFLOW FW ON AR.FORM_WORKFLOW_ID = FW.FORM_WORKFLOW_ID
WHERE FW.CURRENT_STATUS_ID != 4
AND AR.AMOUNT != 0
AND RM.DEBIT_ACCOUNT_COMBINATION_ID IS NOT NULL
AND AC.COMPANY_ID = IN_COMPANY_ID
AND AR.MATURITY_DATE <= IN_AS_OF_DATE
GROUP BY AC.ACCOUNT_ID
-- Debit Bank account
UNION ALL
SELECT 'AR RECEIPT' as SOURCE, AC.ACCOUNT_ID, SUM(AR.AMOUNT) AS DEBIT, 0 as CREDIT
FROM AR_RECEIPT AR
INNER JOIN RECEIPT_METHOD RM ON RM.RECEIPT_METHOD_ID = AR.RECEIPT_METHOD_ID
INNER JOIN BANK_ACCOUNT BA ON BA.BANK_ACCOUNT_ID = RM.BANK_ACCOUNT_ID
INNER JOIN ACCOUNT_COMBINATION AC ON AC.ACCOUNT_COMBINATION_ID = BA.CASH_IN_BANK_ACCT_ID
INNER JOIN FORM_WORKFLOW FW ON AR.FORM_WORKFLOW_ID = FW.FORM_WORKFLOW_ID
WHERE FW.CURRENT_STATUS_ID != 4
AND AR.AMOUNT != 0
AND RM.BANK_ACCOUNT_ID IS NOT NULL
AND AC.COMPANY_ID = IN_COMPANY_ID
AND AR.MATURITY_DATE <= IN_AS_OF_DATE
GROUP BY AC.ACCOUNT_ID
UNION ALL
-- Credit
-- RECEIPT_ID
-- RECEIPT_METHOD
-- CREDIT_ACCOUNT_COMBINATION_ID
SELECT 'AR RECEIPT' as SOURCE, AC.ACCOUNT_ID, 0 AS DEBIT, SUM(AR.AMOUNT) as CREDIT
FROM AR_RECEIPT AR
INNER JOIN RECEIPT_METHOD RM ON RM.RECEIPT_METHOD_ID = AR.RECEIPT_METHOD_ID
INNER JOIN ACCOUNT_COMBINATION AC ON AC.ACCOUNT_COMBINATION_ID = RM.CREDIT_ACCOUNT_COMBINATION_ID
INNER JOIN FORM_WORKFLOW FW ON AR.FORM_WORKFLOW_ID = FW.FORM_WORKFLOW_ID
WHERE FW.CURRENT_STATUS_ID != 4
AND AR.AMOUNT != 0
AND AC.COMPANY_ID = IN_COMPANY_ID
AND AR.MATURITY_DATE <= IN_AS_OF_DATE
GROUP BY AC.ACCOUNT_ID
UNION ALL
-- AR Transaction
-- if amount is positive
-- Debit
-- AR_RECEIPT_TRANSACTION.AR_RECEIPT_ID->AR_RECEIPT.RECEIPT_ID->RECEIPT_METHOD.CREDIT_ACCOUNT_COMBINATION_ID
SELECT 'AR RECEIPT' as SOURCE, AC.ACCOUNT_ID, SUM(ART.AMOUNT) AS DEBIT, 0 as CREDIT
FROM AR_RECEIPT_TRANSACTION ART
INNER JOIN AR_RECEIPT AR ON AR.AR_RECEIPT_ID = ART.AR_RECEIPT_ID
INNER JOIN RECEIPT_METHOD RM ON RM.RECEIPT_METHOD_ID = AR.RECEIPT_METHOD_ID
INNER JOIN ACCOUNT_COMBINATION AC ON AC.ACCOUNT_COMBINATION_ID = RM.CREDIT_ACCOUNT_COMBINATION_ID
INNER JOIN FORM_WORKFLOW FW ON AR.FORM_WORKFLOW_ID = FW.FORM_WORKFLOW_ID
WHERE FW.CURRENT_STATUS_ID != 4
AND ART.AMOUNT >= 0
AND AC.COMPANY_ID = IN_COMPANY_ID
AND AR.MATURITY_DATE <= IN_AS_OF_DATE
GROUP BY AC.ACCOUNT_ID
UNION ALL

SELECT 'AR RECEIPT' as SOURCE, AC.ACCOUNT_ID, 0 AS DEBIT, SUM(-ART.AMOUNT) as CREDIT
FROM AR_RECEIPT_TRANSACTION ART
INNER JOIN AR_RECEIPT AR ON AR.AR_RECEIPT_ID = ART.AR_RECEIPT_ID
INNER JOIN RECEIPT_METHOD RM ON RM.RECEIPT_METHOD_ID = AR.RECEIPT_METHOD_ID
INNER JOIN ACCOUNT_COMBINATION AC ON AC.ACCOUNT_COMBINATION_ID = RM.CREDIT_ACCOUNT_COMBINATION_ID
INNER JOIN FORM_WORKFLOW FW ON AR.FORM_WORKFLOW_ID = FW.FORM_WORKFLOW_ID
WHERE FW.CURRENT_STATUS_ID != 4
AND ART.AMOUNT < 0
AND AC.COMPANY_ID = IN_COMPANY_ID
AND AR.MATURITY_DATE <= IN_AS_OF_DATE
GROUP BY AC.ACCOUNT_ID
UNION ALL

-- Credit
-- AR_RECEIPT_TRANSACTION.AR_RECEIPT_ID->AR_RECEIPT.AR_CUSTOMER_ACCOUNT_ID->AR_CUSTOMER_ACCOUNT.DEFAULT_DEBIT_AC_ID
-- if negative, reverse the debit and credit.
SELECT 'AR RECEIPT' as SOURCE, AC.ACCOUNT_ID, 0 AS DEBIT, SUM(ART.AMOUNT) as CREDIT
FROM AR_RECEIPT_TRANSACTION ART
INNER JOIN AR_RECEIPT AR ON AR.AR_RECEIPT_ID = ART.AR_RECEIPT_ID
INNER JOIN AR_CUSTOMER_ACCOUNT ACA ON ACA.AR_CUSTOMER_ACCOUNT_ID = AR.AR_CUSTOMER_ACCOUNT_ID
INNER JOIN ACCOUNT_COMBINATION AC ON AC.ACCOUNT_COMBINATION_ID = ACA.DEFAULT_DEBIT_AC_ID
INNER JOIN FORM_WORKFLOW FW ON AR.FORM_WORKFLOW_ID = FW.FORM_WORKFLOW_ID
WHERE FW.CURRENT_STATUS_ID != 4
AND ART.AMOUNT >= 0
AND AC.COMPANY_ID = IN_COMPANY_ID
AND AR.MATURITY_DATE <= IN_AS_OF_DATE
GROUP BY AC.ACCOUNT_ID
UNION ALL

SELECT 'AR RECEIPT' as SOURCE, AC.ACCOUNT_ID, SUM(-ART.AMOUNT) AS DEBIT, 0 as CREDIT
FROM AR_RECEIPT_TRANSACTION ART
INNER JOIN AR_RECEIPT AR ON AR.AR_RECEIPT_ID = ART.AR_RECEIPT_ID
INNER JOIN AR_CUSTOMER_ACCOUNT ACA ON ACA.AR_CUSTOMER_ACCOUNT_ID = AR.AR_CUSTOMER_ACCOUNT_ID
INNER JOIN ACCOUNT_COMBINATION AC ON AC.ACCOUNT_COMBINATION_ID = ACA.DEFAULT_DEBIT_AC_ID
INNER JOIN FORM_WORKFLOW FW ON AR.FORM_WORKFLOW_ID = FW.FORM_WORKFLOW_ID
WHERE FW.CURRENT_STATUS_ID != 4
AND ART.AMOUNT < 0
AND AC.COMPANY_ID = IN_COMPANY_ID
AND AR.MATURITY_DATE <= IN_AS_OF_DATE
GROUP BY AC.ACCOUNT_ID

UNION ALL

-- Cash Sales - Cost Account
SELECT 'CASH SALES' as SOURCE, AC.ACCOUNT_ID, SUM(COALESCE(UNIT_COST, 0) * QUANTITY) as DEBIT, 0 as CREDIT
FROM CASH_SALE_ITEM CSI
INNER JOIN CASH_SALE CS ON CS.CASH_SALE_ID = CSI.CASH_SALE_ID
INNER JOIN AR_CUSTOMER_ACCOUNT ACA ON ACA.AR_CUSTOMER_ACCOUNT_ID = CS.AR_CUSTOMER_ACCOUNT_ID
INNER JOIN ITEM I ON I.ITEM_ID = CSI.ITEM_ID
INNER JOIN ITEM_CATEGORY_ACCOUNT_SETUP ICAS ON I.ITEM_CATEGORY_ID = ICAS.ITEM_CATEGORY_ID
INNER JOIN ACCOUNT_COMBINATION AC ON AC.ACCOUNT_COMBINATION_ID = ICAS.COST_ACCOUNT
INNER JOIN FORM_WORKFLOW FW ON CS.FORM_WORKFLOW_ID = FW.FORM_WORKFLOW_ID
WHERE FW.IS_COMPLETE = 1
AND ICAS.ACTIVE = 1
AND ICAS.COMPANY_ID = IN_COMPANY_ID
AND CS.COMPANY_ID = IN_COMPANY_ID
AND CS.RECEIPT_DATE <= IN_AS_OF_DATE
GROUP BY AC.ACCOUNT_ID

UNION ALL

-- Cash Sales - Inventory Account
SELECT 'CASH SALES' as SOURCE, AC.ACCOUNT_ID, 0 as DEBIT, SUM(COALESCE(UNIT_COST, 0) * QUANTITY) as CREDIT
FROM CASH_SALE_ITEM CSI
INNER JOIN CASH_SALE CS ON CS.CASH_SALE_ID = CSI.CASH_SALE_ID
INNER JOIN AR_CUSTOMER_ACCOUNT ACA ON ACA.AR_CUSTOMER_ACCOUNT_ID = CS.AR_CUSTOMER_ACCOUNT_ID
INNER JOIN ITEM I ON I.ITEM_ID = CSI.ITEM_ID
INNER JOIN ITEM_CATEGORY_ACCOUNT_SETUP ICAS ON I.ITEM_CATEGORY_ID = ICAS.ITEM_CATEGORY_ID
INNER JOIN ACCOUNT_COMBINATION AC ON AC.ACCOUNT_COMBINATION_ID = ICAS.INVENTORY_ACCOUNT
INNER JOIN FORM_WORKFLOW FW ON CS.FORM_WORKFLOW_ID = FW.FORM_WORKFLOW_ID
WHERE FW.IS_COMPLETE = 1
AND ICAS.ACTIVE = 1
AND ICAS.COMPANY_ID = IN_COMPANY_ID
AND CS.COMPANY_ID = IN_COMPANY_ID
AND CS.RECEIPT_DATE <= IN_AS_OF_DATE
GROUP BY AC.ACCOUNT_ID

UNION ALL

-- Cash Sales - Sales Account
SELECT 'CASH SALES' as SOURCE, AC.ACCOUNT_ID, 0 AS DEBIT, SUM(QUANTITY * SRP) as CREDIT
FROM CASH_SALE_ITEM CSI
INNER JOIN CASH_SALE CS ON CS.CASH_SALE_ID = CSI.CASH_SALE_ID
INNER JOIN AR_CUSTOMER_ACCOUNT ACA ON ACA.AR_CUSTOMER_ACCOUNT_ID = CS.AR_CUSTOMER_ACCOUNT_ID
INNER JOIN ITEM I ON I.ITEM_ID = CSI.ITEM_ID
INNER JOIN ITEM_CATEGORY_ACCOUNT_SETUP ICAS ON I.ITEM_CATEGORY_ID = ICAS.ITEM_CATEGORY_ID
INNER JOIN ACCOUNT_COMBINATION AC ON AC.ACCOUNT_COMBINATION_ID = ICAS.SALES_ACCOUNT
INNER JOIN FORM_WORKFLOW FW ON CS.FORM_WORKFLOW_ID = FW.FORM_WORKFLOW_ID
WHERE FW.IS_COMPLETE = 1
AND ICAS.ACTIVE = 1
AND ICAS.COMPANY_ID = IN_COMPANY_ID
AND CS.COMPANY_ID = IN_COMPANY_ID
AND CS.RECEIPT_DATE <= IN_AS_OF_DATE
GROUP BY AC.ACCOUNT_ID

UNION ALL

-- Cash Sales - Sales Discount Account
SELECT 'CASH SALES' as SOURCE, AC.ACCOUNT_ID, 0 AS DEBIT, SUM(-COALESCE(DISCOUNT, 0)) as CREDIT
FROM CASH_SALE_ITEM CSI
INNER JOIN CASH_SALE CS ON CS.CASH_SALE_ID = CSI.CASH_SALE_ID
INNER JOIN AR_CUSTOMER_ACCOUNT ACA ON ACA.AR_CUSTOMER_ACCOUNT_ID = CS.AR_CUSTOMER_ACCOUNT_ID
INNER JOIN ITEM I ON I.ITEM_ID = CSI.ITEM_ID
INNER JOIN ITEM_CATEGORY_ACCOUNT_SETUP ICAS ON I.ITEM_CATEGORY_ID = ICAS.ITEM_CATEGORY_ID
INNER JOIN ACCOUNT_COMBINATION AC ON AC.ACCOUNT_COMBINATION_ID = ICAS.SALES_DISCOUNT_ACCOUNT
INNER JOIN FORM_WORKFLOW FW ON CS.FORM_WORKFLOW_ID = FW.FORM_WORKFLOW_ID
WHERE FW.IS_COMPLETE = 1
AND ICAS.ACTIVE = 1
AND ICAS.COMPANY_ID = IN_COMPANY_ID
AND CS.COMPANY_ID = IN_COMPANY_ID
AND CS.RECEIPT_DATE <= IN_AS_OF_DATE
GROUP BY AC.ACCOUNT_ID

UNION ALL

-- Cash Sales - Receipt Method - Default Debit
SELECT 'CASH SALES' as SOURCE, AC.ACCOUNT_ID, SUM(CSI.AMOUNT) + COALESCE ((SELECT SUM(AMOUNT) FROM CASH_SALE_AR_LINE AL
WHERE AL.CASH_SALE_ID = CSI.CASH_SALE_ID
GROUP BY CS.CASH_SALE_ID), 0) AS DEBIT, 0 as CREDIT
FROM CASH_SALE_ITEM CSI
INNER JOIN CASH_SALE CS ON CS.CASH_SALE_ID = CSI.CASH_SALE_ID
INNER JOIN INVENTORY_ACCOUNT IA ON IA.COMPANY_ID = CS.COMPANY_ID
INNER JOIN RECEIPT_METHOD RM ON RM.RECEIPT_METHOD_ID = IA.CASH_SALES_RM_ID
INNER JOIN ACCOUNT_COMBINATION AC ON AC.ACCOUNT_COMBINATION_ID = RM.DEBIT_ACCOUNT_COMBINATION_ID
INNER JOIN FORM_WORKFLOW FW ON CS.FORM_WORKFLOW_ID = FW.FORM_WORKFLOW_ID
WHERE FW.IS_COMPLETE = 1
AND CS.COMPANY_ID = IN_COMPANY_ID
AND CS.RECEIPT_DATE <= IN_AS_OF_DATE
GROUP BY AC.ACCOUNT_ID

UNION ALL

-- Cash Sales - Receipt Method - Bank Account
SELECT 'CASH SALES' as SOURCE, AC.ACCOUNT_ID, SUM(AMOUNT) AS DEBIT, 0 as CREDIT
FROM CASH_SALE_ITEM CSI
INNER JOIN CASH_SALE CS ON CS.CASH_SALE_ID = CSI.CASH_SALE_ID
INNER JOIN INVENTORY_ACCOUNT IA ON IA.COMPANY_ID = CS.COMPANY_ID
INNER JOIN RECEIPT_METHOD RM ON RM.RECEIPT_METHOD_ID = IA.CASH_SALES_RM_ID
INNER JOIN BANK_ACCOUNT BA ON BA.BANK_ACCOUNT_ID = RM.BANK_ACCOUNT_ID
INNER JOIN ACCOUNT_COMBINATION AC ON AC.ACCOUNT_COMBINATION_ID = BA.CASH_IN_BANK_ACCT_ID
INNER JOIN FORM_WORKFLOW FW ON CS.FORM_WORKFLOW_ID = FW.FORM_WORKFLOW_ID
WHERE FW.IS_COMPLETE = 1
AND CS.COMPANY_ID = IN_COMPANY_ID
AND CS.RECEIPT_DATE <= IN_AS_OF_DATE
GROUP BY AC.ACCOUNT_ID

UNION ALL

-- Cash Sales - Other Charges
SELECT 'CASH SALES' as SOURCE, AC.ACCOUNT_ID, 0 AS DEBIT, SUM(AL.AMOUNT) as CREDIT
FROM CASH_SALE_AR_LINE AL
INNER JOIN CASH_SALE CS ON CS.CASH_SALE_ID = AL.CASH_SALE_ID
INNER JOIN AR_LINE_SETUP ALS ON ALS.AR_LINE_SETUP_ID = AL.AR_LINE_SETUP_ID
INNER JOIN ACCOUNT_COMBINATION AC ON AC.ACCOUNT_COMBINATION_ID = ALS.ACCOUNT_COMBINATION_ID
INNER JOIN FORM_WORKFLOW FW ON CS.FORM_WORKFLOW_ID = FW.FORM_WORKFLOW_ID
WHERE FW.IS_COMPLETE = 1
AND CS.COMPANY_ID = IN_COMPANY_ID
AND CS.RECEIPT_DATE <= IN_AS_OF_DATE
GROUP BY AC.ACCOUNT_ID

UNION ALL 

-- Account Sales - Cost Account
SELECT 'ACCOUNT SALES' as SOURCE, AC.ACCOUNT_ID, SUM(COALESCE(UNIT_COST, 0) * QUANTITY) as DEBIT, 0 as CREDIT
FROM ACCOUNT_SALE_ITEM ASI
INNER JOIN AR_TRANSACTION ART ON ART.AR_TRANSACTION_ID = ASI.AR_TRANSACTION_ID
INNER JOIN AR_CUSTOMER_ACCOUNT ACA ON ACA.AR_CUSTOMER_ACCOUNT_ID = ART.CUSTOMER_ACCOUNT_ID
INNER JOIN ITEM I ON I.ITEM_ID = ASI.ITEM_ID
INNER JOIN ITEM_CATEGORY_ACCOUNT_SETUP ICAS ON I.ITEM_CATEGORY_ID = ICAS.ITEM_CATEGORY_ID
INNER JOIN ACCOUNT_COMBINATION AC ON AC.ACCOUNT_COMBINATION_ID = ICAS.COST_ACCOUNT
INNER JOIN FORM_WORKFLOW FW ON ART.FORM_WORKFLOW_ID = FW.FORM_WORKFLOW_ID
WHERE FW.IS_COMPLETE = 1
AND ICAS.ACTIVE = 1
AND ICAS.COMPANY_ID = IN_COMPANY_ID
AND ART.COMPANY_ID = IN_COMPANY_ID
AND ART.TRANSACTION_DATE <= IN_AS_OF_DATE
AND ART.AR_TRANSACTION_TYPE_ID = 4
GROUP BY AC.ACCOUNT_ID

UNION ALL 

-- Account Sales - Inventory Account
SELECT 'ACCOUNT SALES' as SOURCE, AC.ACCOUNT_ID, 0 as DEBIT, SUM(COALESCE(UNIT_COST, 0) * QUANTITY) as CREDIT
FROM ACCOUNT_SALE_ITEM ASI
INNER JOIN AR_TRANSACTION ART ON ART.AR_TRANSACTION_ID = ASI.AR_TRANSACTION_ID
INNER JOIN AR_CUSTOMER_ACCOUNT ACA ON ACA.AR_CUSTOMER_ACCOUNT_ID = ART.CUSTOMER_ACCOUNT_ID
INNER JOIN ITEM I ON I.ITEM_ID = ASI.ITEM_ID
INNER JOIN ITEM_CATEGORY_ACCOUNT_SETUP ICAS ON I.ITEM_CATEGORY_ID = ICAS.ITEM_CATEGORY_ID
INNER JOIN ACCOUNT_COMBINATION AC ON AC.ACCOUNT_COMBINATION_ID = ICAS.INVENTORY_ACCOUNT
INNER JOIN FORM_WORKFLOW FW ON ART.FORM_WORKFLOW_ID = FW.FORM_WORKFLOW_ID
WHERE FW.IS_COMPLETE = 1
AND ICAS.ACTIVE = 1
AND ICAS.COMPANY_ID = IN_COMPANY_ID
AND ART.COMPANY_ID = IN_COMPANY_ID
AND ART.TRANSACTION_DATE <= IN_AS_OF_DATE
AND ART.AR_TRANSACTION_TYPE_ID = 4
GROUP BY AC.ACCOUNT_ID

UNION ALL

-- Account Sales - Sales Account
SELECT 'ACCOUNT SALES' as SOURCE, AC.ACCOUNT_ID, 0 as DEBIT, SUM(QUANTITY * SRP) as CREDIT
FROM ACCOUNT_SALE_ITEM ASI
INNER JOIN AR_TRANSACTION ART ON ART.AR_TRANSACTION_ID = ASI.AR_TRANSACTION_ID
INNER JOIN AR_CUSTOMER_ACCOUNT ACA ON ACA.AR_CUSTOMER_ACCOUNT_ID = ART.CUSTOMER_ACCOUNT_ID
INNER JOIN ITEM I ON I.ITEM_ID = ASI.ITEM_ID
INNER JOIN ITEM_CATEGORY_ACCOUNT_SETUP ICAS ON I.ITEM_CATEGORY_ID = ICAS.ITEM_CATEGORY_ID
INNER JOIN ACCOUNT_COMBINATION AC ON AC.ACCOUNT_COMBINATION_ID = ICAS.SALES_ACCOUNT
INNER JOIN FORM_WORKFLOW FW ON ART.FORM_WORKFLOW_ID = FW.FORM_WORKFLOW_ID
WHERE FW.IS_COMPLETE = 1
AND ICAS.ACTIVE = 1
AND ICAS.COMPANY_ID = IN_COMPANY_ID
AND ART.COMPANY_ID = IN_COMPANY_ID
AND ART.TRANSACTION_DATE <= IN_AS_OF_DATE
AND ART.AR_TRANSACTION_TYPE_ID = 4
GROUP BY AC.ACCOUNT_ID

UNION ALL

-- Account Sales - Sales Discount Account
SELECT 'ACCOUNT SALES' as SOURCE, AC.ACCOUNT_ID, 0 as DEBIT, SUM(-COALESCE(DISCOUNT, 0)) as CREDIT
FROM ACCOUNT_SALE_ITEM ASI
INNER JOIN AR_TRANSACTION ART ON ART.AR_TRANSACTION_ID = ASI.AR_TRANSACTION_ID
INNER JOIN AR_CUSTOMER_ACCOUNT ACA ON ACA.AR_CUSTOMER_ACCOUNT_ID = ART.CUSTOMER_ACCOUNT_ID
INNER JOIN ITEM I ON I.ITEM_ID = ASI.ITEM_ID
INNER JOIN ITEM_CATEGORY_ACCOUNT_SETUP ICAS ON I.ITEM_CATEGORY_ID = ICAS.ITEM_CATEGORY_ID
INNER JOIN ACCOUNT_COMBINATION AC ON AC.ACCOUNT_COMBINATION_ID = ICAS.SALES_DISCOUNT_ACCOUNT
INNER JOIN FORM_WORKFLOW FW ON ART.FORM_WORKFLOW_ID = FW.FORM_WORKFLOW_ID
WHERE FW.IS_COMPLETE = 1
AND ICAS.ACTIVE = 1
AND ICAS.COMPANY_ID = IN_COMPANY_ID
AND ART.COMPANY_ID = IN_COMPANY_ID
AND ART.TRANSACTION_DATE <= IN_AS_OF_DATE
AND ART.AR_TRANSACTION_TYPE_ID = 4
GROUP BY AC.ACCOUNT_ID

UNION ALL

-- Account Sales - Customer Account Setup
SELECT 'ACCOUNT SALES' as SOURCE, AC.ACCOUNT_ID, SUM(ASI.AMOUNT) + COALESCE((SELECT SUM(AMOUNT) FROM AR_LINE AL
WHERE AL.AR_TRANSACTION_ID = ART.AR_TRANSACTION_ID
GROUP BY ART.AR_TRANSACTION_ID), 0) AS DEBIT, 0 as CREDIT
FROM ACCOUNT_SALE_ITEM ASI
INNER JOIN AR_TRANSACTION ART ON ART.AR_TRANSACTION_ID = ASI.AR_TRANSACTION_ID
INNER JOIN AR_CUSTOMER_ACCOUNT ACA ON ACA.AR_CUSTOMER_ACCOUNT_ID = ART.CUSTOMER_ACCOUNT_ID
INNER JOIN ACCOUNT_COMBINATION AC ON AC.ACCOUNT_COMBINATION_ID = ACA.DEFAULT_DEBIT_AC_ID
INNER JOIN FORM_WORKFLOW FW ON ART.FORM_WORKFLOW_ID = FW.FORM_WORKFLOW_ID
WHERE FW.IS_COMPLETE = 1
AND ART.COMPANY_ID = IN_COMPANY_ID
AND ART.TRANSACTION_DATE <= IN_AS_OF_DATE
AND ART.AR_TRANSACTION_TYPE_ID = 4
GROUP BY AC.ACCOUNT_ID

UNION ALL

-- Account Sales - Other charges
SELECT 'ACCOUNT SALES' as SOURCE, AC.ACCOUNT_ID, 0 as DEBIT, SUM(AL.AMOUNT) as CREDIT
FROM AR_LINE AL
INNER JOIN AR_TRANSACTION ART ON ART.AR_TRANSACTION_ID = AL.AR_TRANSACTION_ID
INNER JOIN AR_LINE_SETUP ALS ON ALS.AR_LINE_SETUP_ID = AL.AR_LINE_SETUP_ID
INNER JOIN ACCOUNT_COMBINATION AC ON AC.ACCOUNT_COMBINATION_ID = ALS.ACCOUNT_COMBINATION_ID
INNER JOIN FORM_WORKFLOW FW ON ART.FORM_WORKFLOW_ID = FW.FORM_WORKFLOW_ID
WHERE FW.IS_COMPLETE = 1
AND ART.COMPANY_ID = IN_COMPANY_ID
AND ART.TRANSACTION_DATE <= IN_AS_OF_DATE
AND ART.AR_TRANSACTION_TYPE_ID = 4
GROUP BY AC.ACCOUNT_ID

UNION ALL

-- Receiving Report - Debit
SELECT 'RECEIVING REPORT' as SOURCE, AC.ACCOUNT_ID, SUM(COALESCE(UNIT_COST, 0) * QUANTITY) as DEBIT, 0 as CREDIT
FROM R_RECEIVING_REPORT_ITEM RRI
INNER JOIN R_RECEIVING_REPORT RR ON RR.AP_INVOICE_ID = RRI.AP_INVOICE_ID
INNER JOIN AP_INVOICE AI ON AI.AP_INVOICE_ID = RRI.AP_INVOICE_ID
INNER JOIN ITEM I ON I.ITEM_ID = RRI.ITEM_ID
INNER JOIN ITEM_CATEGORY_ACCOUNT_SETUP ICAS ON I.ITEM_CATEGORY_ID = ICAS.ITEM_CATEGORY_ID
INNER JOIN ACCOUNT_COMBINATION AC ON AC.ACCOUNT_COMBINATION_ID = ICAS.INVENTORY_ACCOUNT
INNER JOIN FORM_WORKFLOW FW ON AI.FORM_WORKFLOW_ID = FW.FORM_WORKFLOW_ID
WHERE FW.IS_COMPLETE = 1
AND ICAS.ACTIVE = 1
AND ICAS.COMPANY_ID = IN_COMPANY_ID
AND RR.COMPANY_ID = IN_COMPANY_ID
AND AI.GL_DATE <= IN_AS_OF_DATE
AND AI.INVOICE_TYPE_ID = 5
GROUP BY AC.ACCOUNT_ID

UNION ALL 

-- Receiving Report - Credit
SELECT 'RECEIVING REPORT' as SOURCE, AC.ACCOUNT_ID, 0 as DEBIT, SUM(COALESCE(UNIT_COST, 0) * QUANTITY) as CREDIT
FROM R_RECEIVING_REPORT_ITEM RRI
INNER JOIN R_RECEIVING_REPORT RR ON RR.AP_INVOICE_ID = RRI.AP_INVOICE_ID
INNER JOIN AP_INVOICE AI ON AI.AP_INVOICE_ID = RR.AP_INVOICE_ID
INNER JOIN SUPPLIER_ACCOUNT SPA ON SPA.SUPPLIER_ACCOUNT_ID = AI.SUPPLIER_ACCOUNT_ID
INNER JOIN ACCOUNT_COMBINATION AC ON AC.ACCOUNT_COMBINATION_ID = SPA.DEFAULT_CREDIT_AC_ID
INNER JOIN FORM_WORKFLOW FW ON AI.FORM_WORKFLOW_ID = FW.FORM_WORKFLOW_ID
WHERE FW.IS_COMPLETE = 1
AND RR.COMPANY_ID = IN_COMPANY_ID
AND AI.GL_DATE <= IN_AS_OF_DATE
AND AI.INVOICE_TYPE_ID = 5
GROUP BY AC.ACCOUNT_ID

UNION ALL

-- Return To Supplier - Credit
SELECT 'RETURN TO SUPPLIER' as SOURCE, AC.ACCOUNT_ID, 0 as DEBIT, SUM(COALESCE(UNIT_COST, 0) * QUANTITY) as CREDIT
FROM R_RETURN_TO_SUPPLIER_ITEM RTSI
INNER JOIN R_RETURN_TO_SUPPLIER RTS ON RTS.AP_INVOICE_ID = RTSI.AP_INVOICE_ID
INNER JOIN AP_INVOICE AI ON AI.AP_INVOICE_ID = RTS.AP_INVOICE_ID
INNER JOIN ITEM I ON I.ITEM_ID = RTSI.ITEM_ID
INNER JOIN ITEM_CATEGORY_ACCOUNT_SETUP ICAS ON I.ITEM_CATEGORY_ID = ICAS.ITEM_CATEGORY_ID
INNER JOIN ACCOUNT_COMBINATION AC ON AC.ACCOUNT_COMBINATION_ID = ICAS.INVENTORY_ACCOUNT
INNER JOIN FORM_WORKFLOW FW ON AI.FORM_WORKFLOW_ID = FW.FORM_WORKFLOW_ID
WHERE FW.IS_COMPLETE = 1
AND ICAS.ACTIVE = 1
AND ICAS.COMPANY_ID = IN_COMPANY_ID
AND RTS.COMPANY_ID = IN_COMPANY_ID
AND AI.GL_DATE <= IN_AS_OF_DATE
AND AI.INVOICE_TYPE_ID = 6
GROUP BY AC.ACCOUNT_ID

UNION ALL

-- Return To Supplier - Debit
SELECT 'RETURN TO SUPPLIER' as SOURCE, AC.ACCOUNT_ID, SUM(COALESCE(UNIT_COST, 0) * QUANTITY) as DEBIT, 0 as CREDIT
FROM R_RETURN_TO_SUPPLIER_ITEM RTSI
INNER JOIN R_RETURN_TO_SUPPLIER RTS ON RTS.AP_INVOICE_ID = RTSI.AP_INVOICE_ID
INNER JOIN AP_INVOICE AI ON AI.AP_INVOICE_ID = RTS.AP_INVOICE_ID
INNER JOIN SUPPLIER_ACCOUNT SPA ON SPA.SUPPLIER_ACCOUNT_ID = AI.SUPPLIER_ACCOUNT_ID
INNER JOIN ACCOUNT_COMBINATION AC ON AC.ACCOUNT_COMBINATION_ID = SPA.DEFAULT_CREDIT_AC_ID
INNER JOIN FORM_WORKFLOW FW ON AI.FORM_WORKFLOW_ID = FW.FORM_WORKFLOW_ID
WHERE FW.IS_COMPLETE = 1
AND RTS.COMPANY_ID = IN_COMPANY_ID
AND AI.GL_DATE <= IN_AS_OF_DATE
AND AI.INVOICE_TYPE_ID = 6
GROUP BY AC.ACCOUNT_ID

UNION ALL

-- Cash Sales Return - Cost Account - Return Items
SELECT 'CASH SALES RETURN' as SOURCE, AC.ACCOUNT_ID, SUM(COALESCE(UNIT_COST, 0) * QUANTITY) as DEBIT, 0 as CREDIT
FROM CASH_SALE_RETURN_ITEM CSRI
INNER JOIN CASH_SALE_RETURN CSR ON CSR.CASH_SALE_RETURN_ID = CSRI.CASH_SALE_RETURN_ID
INNER JOIN AR_CUSTOMER_ACCOUNT ACA ON ACA.AR_CUSTOMER_ACCOUNT_ID = CSR.AR_CUSTOMER_ACCOUNT_ID
INNER JOIN ITEM I ON I.ITEM_ID = CSRI.ITEM_ID
INNER JOIN ITEM_CATEGORY_ACCOUNT_SETUP ICAS ON I.ITEM_CATEGORY_ID = ICAS.ITEM_CATEGORY_ID
INNER JOIN ACCOUNT_COMBINATION AC ON AC.ACCOUNT_COMBINATION_ID = ICAS.COST_ACCOUNT
INNER JOIN FORM_WORKFLOW FW ON CSR.FORM_WORKFLOW_ID = FW.FORM_WORKFLOW_ID
WHERE FW.IS_COMPLETE = 1
AND ICAS.ACTIVE = 1
AND ICAS.COMPANY_ID = IN_COMPANY_ID
AND CSR.COMPANY_ID = IN_COMPANY_ID
AND CSR.DATE <= IN_AS_OF_DATE
GROUP BY AC.ACCOUNT_ID

UNION ALL

-- Cash Sales Return - Inventory Account - Return
SELECT 'CASH SALES RETURN' as SOURCE, AC.ACCOUNT_ID, 0 as DEBIT, SUM(COALESCE(UNIT_COST, 0) * QUANTITY) as CREDIT
FROM CASH_SALE_RETURN_ITEM CSRI
INNER JOIN CASH_SALE_RETURN CSR ON CSR.CASH_SALE_RETURN_ID = CSRI.CASH_SALE_RETURN_ID
INNER JOIN AR_CUSTOMER_ACCOUNT ACA ON ACA.AR_CUSTOMER_ACCOUNT_ID = CSR.AR_CUSTOMER_ACCOUNT_ID
INNER JOIN ITEM I ON I.ITEM_ID = CSRI.ITEM_ID
INNER JOIN ITEM_CATEGORY_ACCOUNT_SETUP ICAS ON I.ITEM_CATEGORY_ID = ICAS.ITEM_CATEGORY_ID
INNER JOIN ACCOUNT_COMBINATION AC ON AC.ACCOUNT_COMBINATION_ID = ICAS.INVENTORY_ACCOUNT
INNER JOIN FORM_WORKFLOW FW ON CSR.FORM_WORKFLOW_ID = FW.FORM_WORKFLOW_ID
WHERE FW.IS_COMPLETE = 1
AND ICAS.ACTIVE = 1
AND ICAS.COMPANY_ID = IN_COMPANY_ID
AND QUANTITY < 0
AND CSR.COMPANY_ID = IN_COMPANY_ID
AND CSR.DATE <= IN_AS_OF_DATE
GROUP BY AC.ACCOUNT_ID

UNION ALL

-- Cash Sales Return - Inventory Account - Exchange
SELECT 'CASH SALES RETURN' as SOURCE, AC.ACCOUNT_ID, 0 as DEBIT, SUM((COALESCE(UNIT_COST, 0) * QUANTITY)) as CREDIT
FROM CASH_SALE_RETURN_ITEM CSRI
INNER JOIN CASH_SALE_RETURN CSR ON CSR.CASH_SALE_RETURN_ID = CSRI.CASH_SALE_RETURN_ID
INNER JOIN AR_CUSTOMER_ACCOUNT ACA ON ACA.AR_CUSTOMER_ACCOUNT_ID = CSR.AR_CUSTOMER_ACCOUNT_ID
INNER JOIN ITEM I ON I.ITEM_ID = CSRI.ITEM_ID
INNER JOIN ITEM_CATEGORY_ACCOUNT_SETUP ICAS ON I.ITEM_CATEGORY_ID = ICAS.ITEM_CATEGORY_ID
INNER JOIN ACCOUNT_COMBINATION AC ON AC.ACCOUNT_COMBINATION_ID = ICAS.INVENTORY_ACCOUNT
INNER JOIN FORM_WORKFLOW FW ON CSR.FORM_WORKFLOW_ID = FW.FORM_WORKFLOW_ID
WHERE FW.IS_COMPLETE = 1
AND ICAS.ACTIVE = 1
AND ICAS.COMPANY_ID = IN_COMPANY_ID
AND QUANTITY > 0
AND CSR.COMPANY_ID = IN_COMPANY_ID
AND CSR.DATE <= IN_AS_OF_DATE
GROUP BY AC.ACCOUNT_ID

UNION ALL

-- Cash Sales Return - Sales Return Account
SELECT 'CASH SALES RETURN' as SOURCE, AC.ACCOUNT_ID, 0 as DEBIT, SUM((QUANTITY * SRP)) as CREDIT
FROM CASH_SALE_RETURN_ITEM CSRI
INNER JOIN CASH_SALE_RETURN CSR ON CSR.CASH_SALE_RETURN_ID = CSRI.CASH_SALE_RETURN_ID
INNER JOIN AR_CUSTOMER_ACCOUNT ACA ON ACA.AR_CUSTOMER_ACCOUNT_ID = CSR.AR_CUSTOMER_ACCOUNT_ID
INNER JOIN ITEM I ON I.ITEM_ID = CSRI.ITEM_ID
INNER JOIN ITEM_CATEGORY_ACCOUNT_SETUP ICAS ON I.ITEM_CATEGORY_ID = ICAS.ITEM_CATEGORY_ID
INNER JOIN ACCOUNT_COMBINATION AC ON AC.ACCOUNT_COMBINATION_ID = ICAS.SALES_RETURN_ACCOUNT
INNER JOIN FORM_WORKFLOW FW ON CSR.FORM_WORKFLOW_ID = FW.FORM_WORKFLOW_ID
WHERE FW.IS_COMPLETE = 1
AND ICAS.ACTIVE = 1
AND ICAS.COMPANY_ID = IN_COMPANY_ID
AND CSR.COMPANY_ID = IN_COMPANY_ID
AND CSR.DATE <= IN_AS_OF_DATE
GROUP BY AC.ACCOUNT_ID

UNION ALL

-- Cash Return Sales - Sales Discount Account
SELECT 'CASH SALES RETURN' as SOURCE, AC.ACCOUNT_ID, 0 AS DEBIT, SUM(COALESCE(DISCOUNT, 0)) as CREDIT
FROM CASH_SALE_RETURN_ITEM CSRI
INNER JOIN CASH_SALE_RETURN CSR ON CSR.CASH_SALE_RETURN_ID = CSRI.CASH_SALE_RETURN_ID
INNER JOIN AR_CUSTOMER_ACCOUNT ACA ON ACA.AR_CUSTOMER_ACCOUNT_ID = CSR.AR_CUSTOMER_ACCOUNT_ID
INNER JOIN ITEM I ON I.ITEM_ID = CSRI.ITEM_ID
INNER JOIN ITEM_CATEGORY_ACCOUNT_SETUP ICAS ON I.ITEM_CATEGORY_ID = ICAS.ITEM_CATEGORY_ID
INNER JOIN ACCOUNT_COMBINATION AC ON AC.ACCOUNT_COMBINATION_ID = ICAS.SALES_DISCOUNT_ACCOUNT
INNER JOIN FORM_WORKFLOW FW ON CSR.FORM_WORKFLOW_ID = FW.FORM_WORKFLOW_ID
WHERE FW.IS_COMPLETE = 1
AND ICAS.ACTIVE = 1
AND ICAS.COMPANY_ID = IN_COMPANY_ID
AND CSR.COMPANY_ID = IN_COMPANY_ID
AND CSR.DATE <= IN_AS_OF_DATE
GROUP BY AC.ACCOUNT_ID

UNION ALL

-- Cash Sales Return - Receipt Method - Default Debit
SELECT 'CASH SALES RETURN' as SOURCE, AC.ACCOUNT_ID,  SUM(AMOUNT) as DEBIT, 0 as CREDIT
FROM CASH_SALE_RETURN_ITEM CSRI
INNER JOIN CASH_SALE_RETURN CSR ON CSR.CASH_SALE_RETURN_ID = CSRI.CASH_SALE_RETURN_ID
INNER JOIN CASH_SALE CS ON CS.CASH_SALE_ID = CSR.CASH_SALE_ID
INNER JOIN INVENTORY_ACCOUNT IA ON IA.COMPANY_ID = CSR.COMPANY_ID
INNER JOIN RECEIPT_METHOD RM ON RM.RECEIPT_METHOD_ID = IA.CASH_SALES_RM_ID
INNER JOIN ACCOUNT_COMBINATION AC ON AC.ACCOUNT_COMBINATION_ID = RM.DEBIT_ACCOUNT_COMBINATION_ID
INNER JOIN FORM_WORKFLOW FW ON CSR.FORM_WORKFLOW_ID = FW.FORM_WORKFLOW_ID
WHERE FW.IS_COMPLETE = 1
AND CSR.COMPANY_ID = IN_COMPANY_ID
AND CSR.DATE <= IN_AS_OF_DATE
GROUP BY AC.ACCOUNT_ID

UNION ALL

-- Cash Sales Return - Receipt Method - Bank Account
SELECT 'CASH SALES RETURN' as SOURCE, AC.ACCOUNT_ID, SUM(AMOUNT) as DEBIT, 0 as CREDIT
FROM CASH_SALE_RETURN_ITEM CSRI
INNER JOIN CASH_SALE_RETURN CSR ON CSR.CASH_SALE_RETURN_ID = CSRI.CASH_SALE_RETURN_ID
INNER JOIN CASH_SALE CS ON CS.CASH_SALE_ID = CSR.CASH_SALE_ID
INNER JOIN INVENTORY_ACCOUNT IA ON IA.COMPANY_ID = CSR.COMPANY_ID
INNER JOIN RECEIPT_METHOD RM ON RM.RECEIPT_METHOD_ID = IA.CASH_SALES_RM_ID
INNER JOIN BANK_ACCOUNT BA ON BA.BANK_ACCOUNT_ID = RM.BANK_ACCOUNT_ID
INNER JOIN ACCOUNT_COMBINATION AC ON AC.ACCOUNT_COMBINATION_ID = BA.CASH_IN_BANK_ACCT_ID
INNER JOIN FORM_WORKFLOW FW ON CSR.FORM_WORKFLOW_ID = FW.FORM_WORKFLOW_ID
WHERE FW.IS_COMPLETE = 1
AND CSR.COMPANY_ID = IN_COMPANY_ID
AND CSR.DATE <= IN_AS_OF_DATE
GROUP BY AC.ACCOUNT_ID

UNION ALL

-- Cash Sales Return - Other Charges
SELECT 'CASH SALES RETURN' as SOURCE, AC.ACCOUNT_ID, SUM(AL.AMOUNT) AS DEBIT, 0 as CREDIT
FROM CASH_SALE_RETURN_AR_LINE AL
INNER JOIN CASH_SALE_RETURN CSR ON CSR.CASH_SALE_RETURN_ID = AL.CASH_SALE_RETURN_ID
INNER JOIN AR_LINE_SETUP ALS ON ALS.AR_LINE_SETUP_ID = AL.AR_LINE_SETUP_ID
INNER JOIN ACCOUNT_COMBINATION AC ON AC.ACCOUNT_COMBINATION_ID = ALS.ACCOUNT_COMBINATION_ID
INNER JOIN FORM_WORKFLOW FW ON CSR.FORM_WORKFLOW_ID = FW.FORM_WORKFLOW_ID
WHERE FW.IS_COMPLETE = 1
AND CSR.COMPANY_ID = IN_COMPANY_ID
AND CSR.RECEIPT_DATE <= IN_AS_OF_DATE
GROUP BY AC.ACCOUNT_ID

UNION ALL

-- Account Sales Return - Cost Account
SELECT 'ACCOUNT SALES RETURN' as SOURCE, AC.ACCOUNT_ID, SUM(COALESCE(UNIT_COST, 0) * QUANTITY) as DEBIT, 0 as CREDIT
FROM ACCOUNT_SALE_ITEM ASI
INNER JOIN AR_TRANSACTION ART ON ART.AR_TRANSACTION_ID = ASI.AR_TRANSACTION_ID
INNER JOIN AR_CUSTOMER_ACCOUNT ACA ON ACA.AR_CUSTOMER_ACCOUNT_ID = ART.CUSTOMER_ACCOUNT_ID
INNER JOIN ITEM I ON I.ITEM_ID = ASI.ITEM_ID
INNER JOIN ITEM_CATEGORY_ACCOUNT_SETUP ICAS ON I.ITEM_CATEGORY_ID = ICAS.ITEM_CATEGORY_ID
INNER JOIN ACCOUNT_COMBINATION AC ON AC.ACCOUNT_COMBINATION_ID = ICAS.COST_ACCOUNT
INNER JOIN FORM_WORKFLOW FW ON ART.FORM_WORKFLOW_ID = FW.FORM_WORKFLOW_ID
WHERE FW.IS_COMPLETE = 1
AND ICAS.ACTIVE = 1
AND ICAS.COMPANY_ID = IN_COMPANY_ID
AND ART.COMPANY_ID = IN_COMPANY_ID
AND ART.TRANSACTION_DATE <= IN_AS_OF_DATE
AND ART.AR_TRANSACTION_TYPE_ID = 5
GROUP BY AC.ACCOUNT_ID

UNION ALL

-- Account Sales Return - Inventory Account - Return
SELECT 'ACCOUNT SALES RETURN' as SOURCE, AC.ACCOUNT_ID, 0 as DEBIT, SUM(COALESCE(UNIT_COST, 0) * QUANTITY) as CREDIT
FROM ACCOUNT_SALE_ITEM ASI
INNER JOIN AR_TRANSACTION ART ON ART.AR_TRANSACTION_ID = ASI.AR_TRANSACTION_ID
INNER JOIN AR_CUSTOMER_ACCOUNT ACA ON ACA.AR_CUSTOMER_ACCOUNT_ID = ART.CUSTOMER_ACCOUNT_ID
INNER JOIN ITEM I ON I.ITEM_ID = ASI.ITEM_ID
INNER JOIN ITEM_CATEGORY_ACCOUNT_SETUP ICAS ON I.ITEM_CATEGORY_ID = ICAS.ITEM_CATEGORY_ID
INNER JOIN ACCOUNT_COMBINATION AC ON AC.ACCOUNT_COMBINATION_ID = ICAS.INVENTORY_ACCOUNT
INNER JOIN FORM_WORKFLOW FW ON ART.FORM_WORKFLOW_ID = FW.FORM_WORKFLOW_ID
WHERE FW.IS_COMPLETE = 1
AND ICAS.ACTIVE = 1
AND ICAS.COMPANY_ID = IN_COMPANY_ID
AND ART.COMPANY_ID = IN_COMPANY_ID
AND ART.TRANSACTION_DATE <= IN_AS_OF_DATE
AND ASI.QUANTITY < 0
AND ART.AR_TRANSACTION_TYPE_ID = 5
GROUP BY AC.ACCOUNT_ID

UNION ALL

-- Account Sales Return - Inventory Account - Exchange
SELECT 'ACCOUNT SALES RETURN' as SOURCE, AC.ACCOUNT_ID, 0 as DEBIT, SUM((COALESCE(UNIT_COST, 0) * QUANTITY)) as CREDIT
FROM ACCOUNT_SALE_ITEM ASI
INNER JOIN AR_TRANSACTION ART ON ART.AR_TRANSACTION_ID = ASI.AR_TRANSACTION_ID
INNER JOIN AR_CUSTOMER_ACCOUNT ACA ON ACA.AR_CUSTOMER_ACCOUNT_ID = ART.CUSTOMER_ACCOUNT_ID
INNER JOIN ITEM I ON I.ITEM_ID = ASI.ITEM_ID
INNER JOIN ITEM_CATEGORY_ACCOUNT_SETUP ICAS ON I.ITEM_CATEGORY_ID = ICAS.ITEM_CATEGORY_ID
INNER JOIN ACCOUNT_COMBINATION AC ON AC.ACCOUNT_COMBINATION_ID = ICAS.INVENTORY_ACCOUNT
INNER JOIN FORM_WORKFLOW FW ON ART.FORM_WORKFLOW_ID = FW.FORM_WORKFLOW_ID
WHERE FW.IS_COMPLETE = 1
AND ICAS.ACTIVE = 1
AND ICAS.COMPANY_ID = IN_COMPANY_ID
AND ART.COMPANY_ID = IN_COMPANY_ID
AND ART.TRANSACTION_DATE <= IN_AS_OF_DATE
AND ART.AR_TRANSACTION_TYPE_ID = 5
AND ASI.QUANTITY > 0
GROUP BY AC.ACCOUNT_ID

UNION ALL

-- Account Sales Return - Sale Return Account
SELECT 'ACCOUNT SALES RETURN' as SOURCE, AC.ACCOUNT_ID, 0 as DEBIT, SUM((QUANTITY * SRP)) as CREDIT
FROM ACCOUNT_SALE_ITEM ASI
INNER JOIN AR_TRANSACTION ART ON ART.AR_TRANSACTION_ID = ASI.AR_TRANSACTION_ID
INNER JOIN AR_CUSTOMER_ACCOUNT ACA ON ACA.AR_CUSTOMER_ACCOUNT_ID = ART.CUSTOMER_ACCOUNT_ID
INNER JOIN ITEM I ON I.ITEM_ID = ASI.ITEM_ID
INNER JOIN ITEM_CATEGORY_ACCOUNT_SETUP ICAS ON I.ITEM_CATEGORY_ID = ICAS.ITEM_CATEGORY_ID
INNER JOIN ACCOUNT_COMBINATION AC ON AC.ACCOUNT_COMBINATION_ID = ICAS.SALES_RETURN_ACCOUNT
INNER JOIN FORM_WORKFLOW FW ON ART.FORM_WORKFLOW_ID = FW.FORM_WORKFLOW_ID
WHERE FW.IS_COMPLETE = 1
AND ICAS.ACTIVE = 1
AND ICAS.COMPANY_ID = IN_COMPANY_ID
AND ART.COMPANY_ID = IN_COMPANY_ID
AND ART.TRANSACTION_DATE <= IN_AS_OF_DATE
AND ART.AR_TRANSACTION_TYPE_ID = 5
GROUP BY AC.ACCOUNT_ID

UNION ALL

-- Account Sales Return - Sales Discount Account
SELECT 'ACCOUNT SALES RETURN' as SOURCE, AC.ACCOUNT_ID,  0 as DEBIT, SUM(COALESCE(DISCOUNT, 0)) as CREDIT
FROM ACCOUNT_SALE_ITEM ASI
INNER JOIN AR_TRANSACTION ART ON ART.AR_TRANSACTION_ID = ASI.AR_TRANSACTION_ID
INNER JOIN AR_CUSTOMER_ACCOUNT ACA ON ACA.AR_CUSTOMER_ACCOUNT_ID = ART.CUSTOMER_ACCOUNT_ID
INNER JOIN ITEM I ON I.ITEM_ID = ASI.ITEM_ID
INNER JOIN ITEM_CATEGORY_ACCOUNT_SETUP ICAS ON I.ITEM_CATEGORY_ID = ICAS.ITEM_CATEGORY_ID
INNER JOIN ACCOUNT_COMBINATION AC ON AC.ACCOUNT_COMBINATION_ID = ICAS.SALES_DISCOUNT_ACCOUNT
INNER JOIN FORM_WORKFLOW FW ON ART.FORM_WORKFLOW_ID = FW.FORM_WORKFLOW_ID
WHERE FW.IS_COMPLETE = 1
AND ICAS.ACTIVE = 1
AND ICAS.COMPANY_ID = IN_COMPANY_ID
AND ART.COMPANY_ID = IN_COMPANY_ID
AND ART.TRANSACTION_DATE <= IN_AS_OF_DATE
AND ART.AR_TRANSACTION_TYPE_ID = 5
GROUP BY AC.ACCOUNT_ID

UNION ALL

-- Account Sales Return - Customer Account Setup
SELECT 'ACCOUNT SALES RETURN' as SOURCE, AC.ACCOUNT_ID, SUM(ASI.AMOUNT) as DEBIT, 0 as CREDIT
FROM ACCOUNT_SALE_ITEM ASI
INNER JOIN AR_TRANSACTION ART ON ART.AR_TRANSACTION_ID = ASI.AR_TRANSACTION_ID
INNER JOIN AR_CUSTOMER_ACCOUNT ACA ON ACA.AR_CUSTOMER_ACCOUNT_ID = ART.CUSTOMER_ACCOUNT_ID
INNER JOIN ACCOUNT_COMBINATION AC ON AC.ACCOUNT_COMBINATION_ID = ACA.DEFAULT_DEBIT_AC_ID
INNER JOIN FORM_WORKFLOW FW ON ART.FORM_WORKFLOW_ID = FW.FORM_WORKFLOW_ID
WHERE FW.IS_COMPLETE = 1
AND ART.COMPANY_ID = IN_COMPANY_ID
AND ART.TRANSACTION_DATE <= IN_AS_OF_DATE
AND ART.AR_TRANSACTION_TYPE_ID = 5
GROUP BY AC.ACCOUNT_ID

UNION ALL 

-- Customer Advance Payment - Receipt Method Debit - Default Debit
SELECT 'CUSTOMER ADVANCE PAYMENT' as SOURCE, AC.ACCOUNT_ID, SUM(AMOUNT) as DEBIT, 0 as CREDIT
FROM CUSTOMER_ADVANCE_PAYMENT_ITEM CAPI
INNER JOIN CUSTOMER_ADVANCE_PAYMENT CAP ON CAP.CUSTOMER_ADVANCE_PAYMENT_ID = CAPI.CUSTOMER_ADVANCE_PAYMENT_ID
INNER JOIN INVENTORY_ACCOUNT IA ON IA.COMPANY_ID = CAP.COMPANY_ID
INNER JOIN RECEIPT_METHOD RM ON RM.RECEIPT_METHOD_ID = IA.CUSTOMER_ADV_PAYMENT_RM_ID
INNER JOIN ACCOUNT_COMBINATION AC ON AC.ACCOUNT_COMBINATION_ID = RM.DEBIT_ACCOUNT_COMBINATION_ID
INNER JOIN FORM_WORKFLOW FW ON CAP.FORM_WORKFLOW_ID = FW.FORM_WORKFLOW_ID
WHERE FW.IS_COMPLETE = 1
AND CAP.COMPANY_ID = IN_COMPANY_ID
AND CAP.RECEIPT_DATE <= IN_AS_OF_DATE
GROUP BY AC.ACCOUNT_ID

UNION ALL 

-- Customer Advance Payment - Receipt Method Debit - Bank Account
SELECT 'CUSTOMER ADVANCE PAYMENT' as SOURCE, AC.ACCOUNT_ID, SUM(AMOUNT) as DEBIT, 0 as CREDIT
FROM CUSTOMER_ADVANCE_PAYMENT_ITEM CAPI
INNER JOIN CUSTOMER_ADVANCE_PAYMENT CAP ON CAP.CUSTOMER_ADVANCE_PAYMENT_ID = CAPI.CUSTOMER_ADVANCE_PAYMENT_ID
INNER JOIN INVENTORY_ACCOUNT IA ON IA.COMPANY_ID = CAP.COMPANY_ID
INNER JOIN RECEIPT_METHOD RM ON RM.RECEIPT_METHOD_ID = IA.CUSTOMER_ADV_PAYMENT_RM_ID
INNER JOIN BANK_ACCOUNT BA ON BA.BANK_ACCOUNT_ID = RM.BANK_ACCOUNT_ID
INNER JOIN ACCOUNT_COMBINATION AC ON AC.ACCOUNT_COMBINATION_ID = BA.CASH_IN_BANK_ACCT_ID
INNER JOIN FORM_WORKFLOW FW ON CAP.FORM_WORKFLOW_ID = FW.FORM_WORKFLOW_ID
WHERE FW.IS_COMPLETE = 1
AND CAP.COMPANY_ID = IN_COMPANY_ID
AND CAP.RECEIPT_DATE <= IN_AS_OF_DATE
GROUP BY AC.ACCOUNT_ID

UNION ALL 

-- Customer Advance Payment - Receipt Method Credit
SELECT 'CUSTOMER ADVANCE PAYMENT' as SOURCE, AC.ACCOUNT_ID, 0 as DEBIT, SUM(AMOUNT) as CREDIT
FROM CUSTOMER_ADVANCE_PAYMENT_ITEM CAPI
INNER JOIN CUSTOMER_ADVANCE_PAYMENT CAP ON CAP.CUSTOMER_ADVANCE_PAYMENT_ID = CAPI.CUSTOMER_ADVANCE_PAYMENT_ID
INNER JOIN INVENTORY_ACCOUNT IA ON IA.COMPANY_ID = CAP.COMPANY_ID
INNER JOIN RECEIPT_METHOD RM ON RM.RECEIPT_METHOD_ID = IA.CUSTOMER_ADV_PAYMENT_RM_ID
INNER JOIN ACCOUNT_COMBINATION AC ON AC.ACCOUNT_COMBINATION_ID = RM.CREDIT_ACCOUNT_COMBINATION_ID
INNER JOIN FORM_WORKFLOW FW ON CAP.FORM_WORKFLOW_ID = FW.FORM_WORKFLOW_ID
WHERE FW.IS_COMPLETE = 1
AND CAP.COMPANY_ID = IN_COMPANY_ID
AND CAP.RECEIPT_DATE <= IN_AS_OF_DATE
GROUP BY AC.ACCOUNT_ID

UNION ALL

-- Stock Adjustment In - Receipt Method Debit
SELECT 'STOCK ADJUSTMENT IN' as SOURCE, AC.ACCOUNT_ID, SUM(COALESCE(UNIT_COST, 0) * QUANTITY) as DEBIT, 0 as CREDIT
FROM STOCK_ADJUSTMENT_ITEM SAI
INNER JOIN STOCK_ADJUSTMENT SA ON SA.STOCK_ADJUSTMENT_ID = SAI.STOCK_ADJUSTMENT_ID
INNER JOIN STOCK_ADJUSTMENT_TYPE SAT ON SAT.STOCK_ADJUSTMENT_TYPE_ID = SA.STOCK_ADJUSTMENT_TYPE_ID
INNER JOIN ITEM I ON I.ITEM_ID = SAI.ITEM_ID
INNER JOIN ITEM_CATEGORY_ACCOUNT_SETUP ICAS ON I.ITEM_CATEGORY_ID = ICAS.ITEM_CATEGORY_ID
INNER JOIN ACCOUNT_COMBINATION AC ON AC.ACCOUNT_COMBINATION_ID = ICAS.INVENTORY_ACCOUNT
INNER JOIN FORM_WORKFLOW FW ON SA.FORM_WORKFLOW_ID = FW.FORM_WORKFLOW_ID
WHERE FW.IS_COMPLETE = 1
AND SA.COMPANY_ID = IN_COMPANY_ID
AND SA.SA_DATE <= IN_AS_OF_DATE
AND QUANTITY > 0
GROUP BY AC.ACCOUNT_ID

UNION ALL

-- Stock Adjustment In - Receipt Method Credit
SELECT 'STOCK ADJUSTMENT IN' as SOURCE, AC.ACCOUNT_ID, 0 as DEBIT, SUM(COALESCE(UNIT_COST, 0) * QUANTITY) as CREDIT
FROM STOCK_ADJUSTMENT_ITEM SAI
INNER JOIN STOCK_ADJUSTMENT SA ON SA.STOCK_ADJUSTMENT_ID = SAI.STOCK_ADJUSTMENT_ID
INNER JOIN STOCK_ADJUSTMENT_TYPE SAT ON SAT.STOCK_ADJUSTMENT_TYPE_ID = SA.STOCK_ADJUSTMENT_TYPE_ID
INNER JOIN ACCOUNT_COMBINATION AC ON AC.ACCOUNT_COMBINATION_ID = SAT.ACCOUNT_COMBINATION_ID
INNER JOIN FORM_WORKFLOW FW ON SA.FORM_WORKFLOW_ID = FW.FORM_WORKFLOW_ID
WHERE FW.IS_COMPLETE = 1
AND SA.COMPANY_ID = IN_COMPANY_ID
AND SA.SA_DATE <= IN_AS_OF_DATE
AND QUANTITY > 0
GROUP BY AC.ACCOUNT_ID

UNION ALL 

-- Stock Adjustment Out - Receipt Method Debit
SELECT 'STOCK ADJUSTMENT OUT' as SOURCE, AC.ACCOUNT_ID, SUM(COALESCE(UNIT_COST, 0) * -QUANTITY) as DEBIT, 0 as CREDIT
FROM STOCK_ADJUSTMENT_ITEM SAI
INNER JOIN STOCK_ADJUSTMENT SA ON SA.STOCK_ADJUSTMENT_ID = SAI.STOCK_ADJUSTMENT_ID
INNER JOIN STOCK_ADJUSTMENT_TYPE SAT ON SAT.STOCK_ADJUSTMENT_TYPE_ID = SA.STOCK_ADJUSTMENT_TYPE_ID
INNER JOIN ACCOUNT_COMBINATION AC ON AC.ACCOUNT_COMBINATION_ID = SAT.ACCOUNT_COMBINATION_ID
INNER JOIN FORM_WORKFLOW FW ON SA.FORM_WORKFLOW_ID = FW.FORM_WORKFLOW_ID
WHERE FW.IS_COMPLETE = 1
AND SA.COMPANY_ID = IN_COMPANY_ID
AND SA.SA_DATE <= IN_AS_OF_DATE
AND QUANTITY < 0
GROUP BY AC.ACCOUNT_ID

UNION ALL

-- Stock Adjustment Out - Receipt Method Credit
SELECT 'STOCK ADJUSTMENT OUT' as SOURCE, AC.ACCOUNT_ID, 0 as DEBIT, SUM(COALESCE(UNIT_COST, 0) * -QUANTITY) as CREDIT
FROM STOCK_ADJUSTMENT_ITEM SAI
INNER JOIN STOCK_ADJUSTMENT SA ON SA.STOCK_ADJUSTMENT_ID = SAI.STOCK_ADJUSTMENT_ID
INNER JOIN STOCK_ADJUSTMENT_TYPE SAT ON SAT.STOCK_ADJUSTMENT_TYPE_ID = SA.STOCK_ADJUSTMENT_TYPE_ID
INNER JOIN ITEM I ON I.ITEM_ID = SAI.ITEM_ID
INNER JOIN ITEM_CATEGORY_ACCOUNT_SETUP ICAS ON I.ITEM_CATEGORY_ID = ICAS.ITEM_CATEGORY_ID
INNER JOIN ACCOUNT_COMBINATION AC ON AC.ACCOUNT_COMBINATION_ID = ICAS.INVENTORY_ACCOUNT
INNER JOIN FORM_WORKFLOW FW ON SA.FORM_WORKFLOW_ID = FW.FORM_WORKFLOW_ID
WHERE FW.IS_COMPLETE = 1
AND SA.COMPANY_ID = IN_COMPANY_ID
AND SA.SA_DATE <= IN_AS_OF_DATE
AND QUANTITY < 0
GROUP BY AC.ACCOUNT_ID

) as ACCOUNT_BALANCES 
INNER JOIN ACCOUNT A ON A.ACCOUNT_ID = ACCOUNT_BALANCES.ACCOUNT_ID
GROUP BY ACCOUNT_BALANCES.ACCOUNT_ID 
ORDER BY A.NUMBER;
END//
