-- Description: Stored proceedure that will get the vat declarations.

Delimiter //
DROP procedure if exists GET_VAT_DECLARATION;
CREATE PROCEDURE GET_VAT_DECLARATION(IN IN_COMPANY_ID INT, IN IN_DIVISION_ID INT, IN IN_YEAR INT,
	IN IN_QUARTER INT, IN IN_MONTH INT)

BEGIN

SELECT NAME, SUM(TAX_BASE) AS TAX_BASE, SUM(VAT_AMOUNT) AS VAT_AMOUNT FROM (

SELECT (CASE WHEN APL.TAX_TYPE_ID IN (2,3) THEN "Purchases not qualified for Input Tax"
	WHEN APL.TAX_TYPE_ID = 4  THEN "Purchases - Domestic Goods other than Capital Goods"
	WHEN APL.TAX_TYPE_ID = 5  THEN "Purchases - Domestic Services"
	WHEN APL.TAX_TYPE_ID = 10 THEN "Purchases - Importation of Goods other than Capital Goods"
	WHEN APL.TAX_TYPE_ID = 6 THEN "Purchases - Capital Goods"
	WHEN APL.TAX_TYPE_ID = 7 THEN "Purchases - Nonresident services" END) AS NAME,
APL.AMOUNT AS TAX_BASE, COALESCE(APL.VAT_AMOUNT, 0) AS VAT_AMOUNT
FROM AP_LINE APL
INNER JOIN AP_INVOICE AI ON AI.AP_INVOICE_ID = APL.AP_INVOICE_ID
INNER JOIN FORM_WORKFLOW FW ON FW.FORM_WORKFLOW_ID = AI.FORM_WORKFLOW_ID
WHERE AI.COMPANY_ID = IN_COMPANY_ID
AND FW.IS_COMPLETE = 1
AND APL.TAX_TYPE_ID IN (2, 3, 4, 5, 6, 7, 10)
AND AI.INVOICE_TYPE_ID NOT IN (13, 14, 15, 16, 17, 18, 55, 56, 57, 58, 59, 60, 43, 44, 45, 46, 47, 48)
AND (CASE WHEN IN_DIVISION_ID != -1 THEN AI.DIVISION_ID = IN_DIVISION_ID ELSE AI.DIVISION_ID != IN_DIVISION_ID END)
AND (CASE WHEN IN_QUARTER != -1 THEN QUARTER(AI.GL_DATE) = IN_QUARTER ELSE QUARTER(AI.GL_DATE) != IN_QUARTER END)
AND (CASE WHEN IN_YEAR != -1 THEN YEAR(AI.GL_DATE) = IN_YEAR ELSE YEAR(AI.GL_DATE) != IN_YEAR END)
AND (CASE WHEN IN_MONTH != -1 THEN MONTH(AI.GL_DATE) = IN_MONTH ELSE MONTH(AI.GL_DATE) != IN_MONTH END)

UNION ALL

SELECT (CASE WHEN APL.TAX_TYPE_ID IN (2,3) THEN "Purchases not qualified for Input Tax"
	WHEN APL.TAX_TYPE_ID = 4  THEN "Purchases - Domestic Goods other than Capital Goods"
	WHEN APL.TAX_TYPE_ID = 5  THEN "Purchases - Domestic Services"
	WHEN APL.TAX_TYPE_ID = 10 THEN "Purchases - Importation of Goods other than Capital Goods"
	WHEN APL.TAX_TYPE_ID = 6 THEN "Purchases - Capital Goods"
	WHEN APL.TAX_TYPE_ID = 7 THEN "Purchases - Nonresident services" END) AS NAME,
IID.TAXABLE_IMPORT AS TAX_BASE, COALESCE(APL.VAT_AMOUNT, 0) AS VAT_AMOUNT
FROM AP_LINE APL
INNER JOIN AP_INVOICE AI ON AI.AP_INVOICE_ID = APL.AP_INVOICE_ID
INNER JOIN INVOICE_IMPORTATION_DETAILS IID ON IID.AP_INVOICE_ID = AI.AP_INVOICE_ID
INNER JOIN FORM_WORKFLOW FW ON FW.FORM_WORKFLOW_ID = AI.FORM_WORKFLOW_ID
WHERE AI.COMPANY_ID = IN_COMPANY_ID
AND FW.IS_COMPLETE = 1
AND APL.TAX_TYPE_ID IN (2, 3, 4, 5, 6, 7, 10)
AND AI.INVOICE_TYPE_ID IN (43, 44, 45, 46, 47, 48)
AND (CASE WHEN IN_DIVISION_ID != -1 THEN AI.DIVISION_ID = IN_DIVISION_ID ELSE AI.DIVISION_ID != IN_DIVISION_ID END)
AND (CASE WHEN IN_QUARTER != -1 THEN QUARTER(AI.GL_DATE) = IN_QUARTER ELSE QUARTER(AI.GL_DATE) != IN_QUARTER END)
AND (CASE WHEN IN_YEAR != -1 THEN YEAR(AI.GL_DATE) = IN_YEAR ELSE YEAR(AI.GL_DATE) != IN_YEAR END)
AND (CASE WHEN IN_MONTH != -1 THEN MONTH(AI.GL_DATE) = IN_MONTH ELSE MONTH(AI.GL_DATE) != IN_MONTH END)


UNION ALL

SELECT (CASE WHEN APIL.TAX_TYPE_ID IN (2,3) THEN "Purchases not qualified for Input Tax"
	WHEN APIL.TAX_TYPE_ID = 4  THEN "Purchases - Domestic Goods other than Capital Goods"
	WHEN APIL.TAX_TYPE_ID = 5  THEN "Purchases - Domestic Services"
	WHEN APIL.TAX_TYPE_ID = 10 THEN "Purchases - Importation of Goods other than Capital Goods"
	WHEN APIL.TAX_TYPE_ID = 6 THEN "Purchases - Capital Goods"
	WHEN APIL.TAX_TYPE_ID = 7 THEN "Purchases - Nonresident services" END) AS NAME,
APIL.AMOUNT AS TAX_BASE, COALESCE(APIL.VAT_AMOUNT, 0) AS VAT_AMOUNT
FROM AP_INVOICE_LINE APIL
INNER JOIN AP_INVOICE AI ON AI.AP_INVOICE_ID = APIL.AP_INVOICE_ID
INNER JOIN FORM_WORKFLOW FW ON FW.FORM_WORKFLOW_ID = AI.FORM_WORKFLOW_ID
WHERE AI.COMPANY_ID = IN_COMPANY_ID
AND FW.IS_COMPLETE = 1
AND APIL.TAX_TYPE_ID IN (2, 3, 4, 5, 10, 6, 7)
AND AI.INVOICE_TYPE_ID NOT IN (13, 14, 15, 16, 17, 18, 31, 32, 33, 34, 35, 36)
AND (CASE WHEN IN_DIVISION_ID != -1 THEN AI.DIVISION_ID = IN_DIVISION_ID ELSE AI.DIVISION_ID != IN_DIVISION_ID END)
AND (CASE WHEN IN_QUARTER != -1 THEN QUARTER(AI.GL_DATE) = IN_QUARTER ELSE QUARTER(AI.GL_DATE)!= IN_QUARTER END)
AND (CASE WHEN IN_YEAR != -1 THEN YEAR(AI.GL_DATE) = IN_YEAR ELSE YEAR(AI.GL_DATE) != IN_YEAR END)
AND (CASE WHEN IN_MONTH != -1 THEN MONTH(AI.GL_DATE) = IN_MONTH ELSE MONTH(AI.GL_DATE) != IN_MONTH END)

UNION ALL

SELECT (CASE WHEN APG.TAX_TYPE_ID IN (2,3) THEN "Purchases not qualified for Input Tax"
	WHEN APG.TAX_TYPE_ID = 4  THEN "Purchases - Domestic Goods other than Capital Goods"
	WHEN APG.TAX_TYPE_ID = 5  THEN "Purchases - Domestic Services"
	WHEN APG.TAX_TYPE_ID = 10 THEN "Purchases - Importation of Goods other than Capital Goods"
	WHEN APG.TAX_TYPE_ID = 6 THEN "Purchases - Capital Goods"
	WHEN APG.TAX_TYPE_ID = 7 THEN "Purchases - Nonresident services" END) AS NAME,
APG.AMOUNT AS TAX_BASE, COALESCE(APG.VAT_AMOUNT, 0) AS VAT_AMOUNT
FROM AP_INVOICE_GOODS APG
INNER JOIN AP_INVOICE AP ON AP.AP_INVOICE_ID = APG.AP_INVOICE_ID
INNER JOIN FORM_WORKFLOW FW ON FW.FORM_WORKFLOW_ID = AP.FORM_WORKFLOW_ID
WHERE FW.IS_COMPLETE = 1
AND APG.TAX_TYPE_ID IN (2, 3, 4, 5, 10, 6, 7)
AND AP.INVOICE_TYPE_ID NOT IN (13, 14, 15, 16, 17, 18)
AND AP.COMPANY_ID = IN_COMPANY_ID
AND (CASE WHEN IN_DIVISION_ID != -1 THEN AP.DIVISION_ID = IN_DIVISION_ID ELSE AP.DIVISION_ID != IN_DIVISION_ID END)
AND (CASE WHEN IN_QUARTER != -1 THEN QUARTER(AP.GL_DATE) = IN_QUARTER ELSE QUARTER(AP.GL_DATE)!= IN_QUARTER END)
AND (CASE WHEN IN_YEAR != -1 THEN YEAR(AP.GL_DATE) = IN_YEAR ELSE YEAR(AP.GL_DATE) != IN_YEAR END)
AND (CASE WHEN IN_MONTH != -1 THEN MONTH(AP.GL_DATE) = IN_MONTH ELSE MONTH(AP.GL_DATE) != IN_MONTH END)

UNION ALL

SELECT (CASE WHEN SI.TAX_TYPE_ID IN (2,3) THEN "Purchases not qualified for Input Tax"
	WHEN SI.TAX_TYPE_ID = 4  THEN "Purchases - Domestic Goods other than Capital Goods"
	WHEN SI.TAX_TYPE_ID = 5  THEN "Purchases - Domestic Services"
	WHEN SI.TAX_TYPE_ID = 10 THEN "Purchases - Importation of Goods other than Capital Goods"
	WHEN SI.TAX_TYPE_ID = 6 THEN "Purchases - Capital Goods"
	WHEN SI.TAX_TYPE_ID = 7 THEN "Purchases - Nonresident services" END) AS NAME,
SI.AMOUNT AS TAX_BASE, COALESCE(SI.VAT_AMOUNT, 0) AS VAT_AMOUNT
FROM SERIAL_ITEM SI
INNER JOIN OBJECT_TO_OBJECT O2O ON (O2O.TO_OBJECT_ID = SI.EB_OBJECT_ID AND O2O.OR_TYPE_ID=24001)
INNER JOIN AP_INVOICE API ON API.EB_OBJECT_ID = O2O.FROM_OBJECT_ID
INNER JOIN FORM_WORKFLOW FW ON FW.FORM_WORKFLOW_ID = API.FORM_WORKFLOW_ID
WHERE FW.IS_COMPLETE = 1
AND O2O.OR_TYPE_ID = 24001
AND SI.ACTIVE = 1
AND API.COMPANY_ID = IN_COMPANY_ID
AND SI.TAX_TYPE_ID IN (2, 3, 4, 5, 10, 6, 7)
AND API.INVOICE_TYPE_ID NOT IN (13, 14, 15, 16, 17, 18, 31, 32, 33, 34, 35, 36)
AND (CASE WHEN IN_DIVISION_ID != -1 THEN API.DIVISION_ID = IN_DIVISION_ID ELSE API.DIVISION_ID != IN_DIVISION_ID END)
AND (CASE WHEN IN_YEAR != -1 THEN YEAR(API.GL_DATE) = IN_YEAR ELSE YEAR(API.GL_DATE) != IN_YEAR END)
AND (CASE WHEN IN_QUARTER != -1 THEN QUARTER(API.GL_DATE) = IN_QUARTER ELSE QUARTER(API.GL_DATE)!= IN_QUARTER END)
AND (CASE WHEN IN_MONTH != -1 THEN MONTH(API.GL_DATE) = IN_MONTH ELSE MONTH(API.GL_DATE) != IN_MONTH END)

UNION ALL

SELECT (CASE WHEN SI.TAX_TYPE_ID IN (2,3) THEN "Purchases not qualified for Input Tax"
	WHEN SI.TAX_TYPE_ID = 4  THEN "Purchases - Domestic Goods other than Capital Goods"
	WHEN SI.TAX_TYPE_ID = 5  THEN "Purchases - Domestic Services"
	WHEN SI.TAX_TYPE_ID = 10 THEN "Purchases - Importation of Goods other than Capital Goods"
	WHEN SI.TAX_TYPE_ID = 6 THEN "Purchases - Capital Goods"
	WHEN SI.TAX_TYPE_ID = 7 THEN "Purchases - Nonresident services" END) AS NAME,
-SI.AMOUNT AS TAX_BASE, -COALESCE(SI.VAT_AMOUNT, 0) AS VAT_AMOUNT
FROM SERIAL_ITEM SI
INNER JOIN OBJECT_TO_OBJECT O2O ON (O2O.TO_OBJECT_ID = SI.EB_OBJECT_ID AND O2O.OR_TYPE_ID = 105)
INNER JOIN AP_INVOICE API ON API.EB_OBJECT_ID = O2O.FROM_OBJECT_ID
INNER JOIN FORM_WORKFLOW FW ON FW.FORM_WORKFLOW_ID = API.FORM_WORKFLOW_ID
WHERE FW.IS_COMPLETE = 1
AND O2O.OR_TYPE_ID = 105
AND SI.ACTIVE = 1
AND API.COMPANY_ID = IN_COMPANY_ID
AND SI.TAX_TYPE_ID IN (2, 3, 4, 5, 10, 6, 7)
AND API.INVOICE_TYPE_ID IN (31, 32, 33, 34, 35, 36)
AND (CASE WHEN IN_DIVISION_ID != -1 THEN API.DIVISION_ID = IN_DIVISION_ID ELSE API.DIVISION_ID != IN_DIVISION_ID END)
AND (CASE WHEN IN_YEAR != -1 THEN YEAR(API.GL_DATE) = IN_YEAR ELSE YEAR(API.GL_DATE) != IN_YEAR END)
AND (CASE WHEN IN_QUARTER != -1 THEN QUARTER(API.GL_DATE) = IN_QUARTER ELSE QUARTER(API.GL_DATE) != IN_QUARTER END)
AND (CASE WHEN IN_MONTH != -1 THEN MONTH(API.GL_DATE) = IN_MONTH ELSE MONTH(API.GL_DATE) != IN_MONTH END)

UNION ALL

SELECT (CASE WHEN RTSI.TAX_TYPE_ID IN (2,3) THEN "Purchases not qualified for Input Tax"
	WHEN RTSI.TAX_TYPE_ID = 4  THEN "Purchases - Domestic Goods other than Capital Goods"
	WHEN RTSI.TAX_TYPE_ID = 5  THEN "Purchases - Domestic Services"
	WHEN RTSI.TAX_TYPE_ID = 10 THEN "Purchases - Importation of Goods other than Capital Goods"
	WHEN RTSI.TAX_TYPE_ID = 6 THEN "Purchases - Capital Goods"
	WHEN RTSI.TAX_TYPE_ID = 7 THEN "Purchases - Nonresident services" END) AS NAME,
-RTSI.AMOUNT AS TAX_BASE, -COALESCE(RTSI.VAT_AMOUNT, 0) AS VAT_AMOUNT
FROM R_RETURN_TO_SUPPLIER_ITEM RTSI
INNER JOIN AP_INVOICE API ON API.AP_INVOICE_ID = RTSI.AP_INVOICE_ID
INNER JOIN FORM_WORKFLOW FW ON FW.FORM_WORKFLOW_ID = API.FORM_WORKFLOW_ID
WHERE FW.IS_COMPLETE = 1
AND API.COMPANY_ID = IN_COMPANY_ID
AND RTSI.TAX_TYPE_ID IN (2, 3, 4, 5, 10, 6, 7)
AND API.INVOICE_TYPE_ID IN (31, 32, 33, 34, 35, 36)
AND (CASE WHEN IN_DIVISION_ID != -1 THEN API.DIVISION_ID = IN_DIVISION_ID ELSE API.DIVISION_ID != IN_DIVISION_ID END)
AND (CASE WHEN IN_YEAR != -1 THEN YEAR(API.GL_DATE) = IN_YEAR ELSE YEAR(API.GL_DATE) != IN_YEAR END)
AND (CASE WHEN IN_QUARTER != -1 THEN QUARTER(API.GL_DATE) = IN_QUARTER ELSE QUARTER(API.GL_DATE) != IN_QUARTER END)
AND (CASE WHEN IN_MONTH != -1 THEN MONTH(API.GL_DATE) = IN_MONTH ELSE MONTH(API.GL_DATE) != IN_MONTH END)

UNION ALL

SELECT (CASE WHEN RTSI.TAX_TYPE_ID IN (2,3) THEN "Purchases not qualified for Input Tax"
	WHEN RTSI.TAX_TYPE_ID = 4  THEN "Purchases - Domestic Goods other than Capital Goods"
	WHEN RTSI.TAX_TYPE_ID = 5  THEN "Purchases - Domestic Services"
	WHEN RTSI.TAX_TYPE_ID = 10 THEN "Purchases - Importation of Goods other than Capital Goods"
	WHEN RTSI.TAX_TYPE_ID = 6 THEN "Purchases - Capital Goods"
	WHEN RTSI.TAX_TYPE_ID = 7 THEN "Purchases - Nonresident services" END) AS NAME,
-RTSI.AMOUNT AS TAX_BASE, -COALESCE(RTSI.VAT_AMOUNT, 0) AS VAT_AMOUNT
FROM AP_INVOICE_LINE RTSI
INNER JOIN AP_INVOICE API ON API.AP_INVOICE_ID = RTSI.AP_INVOICE_ID
INNER JOIN FORM_WORKFLOW FW ON FW.FORM_WORKFLOW_ID = API.FORM_WORKFLOW_ID
WHERE FW.IS_COMPLETE = 1
AND API.COMPANY_ID = IN_COMPANY_ID
AND RTSI.TAX_TYPE_ID IN (2, 3, 4, 5, 10, 6, 7)
AND API.INVOICE_TYPE_ID IN (31, 32, 33, 34, 35, 36)
AND (CASE WHEN IN_DIVISION_ID != -1 THEN API.DIVISION_ID = IN_DIVISION_ID ELSE API.DIVISION_ID != IN_DIVISION_ID END)
AND (CASE WHEN IN_YEAR != -1 THEN YEAR(API.GL_DATE) = IN_YEAR ELSE YEAR(API.GL_DATE) != IN_YEAR END)
AND (CASE WHEN IN_QUARTER != -1 THEN QUARTER(API.GL_DATE) = IN_QUARTER ELSE QUARTER(API.GL_DATE) != IN_QUARTER END)
AND (CASE WHEN IN_MONTH != -1 THEN MONTH(API.GL_DATE) = IN_MONTH ELSE MONTH(API.GL_DATE) != IN_MONTH END)

UNION ALL

SELECT (CASE WHEN PCVL.TAX_TYPE_ID IN (2,3) THEN "Purchases not qualified for Input Tax"
WHEN PCVL.TAX_TYPE_ID = 4  THEN "Purchases - Domestic Goods other than Capital Goods"
WHEN PCVL.TAX_TYPE_ID = 5  THEN "Purchases - Domestic Services"
WHEN PCVL.TAX_TYPE_ID = 10 THEN "Purchases - Importation of Goods other than Capital Goods"
WHEN PCVL.TAX_TYPE_ID = 6 THEN "Purchases - Capital Goods"
WHEN PCVL.TAX_TYPE_ID = 7 THEN "Purchases - Nonresident services" END) AS NAME,
PCVL.UP_AMOUNT - COALESCE(PCVL.VAT_AMOUNT, 0) AS TAX_BASE, COALESCE(PCVL.VAT_AMOUNT, 0) AS VAT_AMOUNT
FROM PETTY_CASH_VOUCHER_LIQUIDATION_LINE PCVL
INNER JOIN OBJECT_TO_OBJECT OTO ON OTO.FROM_OBJECT_ID = PCVL.EB_OBJECT_ID
INNER JOIN PETTY_CASH_REPLENISHMENT_LINE PCRL ON PCRL.EB_OBJECT_ID = OTO.TO_OBJECT_ID
INNER JOIN AP_INVOICE API ON API.AP_INVOICE_ID = PCRL.AP_INVOICE_ID
INNER JOIN FORM_WORKFLOW FW ON FW.FORM_WORKFLOW_ID = API.FORM_WORKFLOW_ID
WHERE FW.IS_COMPLETE = 1
AND API.COMPANY_ID = IN_COMPANY_ID
AND PCVL.TAX_TYPE_ID IN (2, 3, 4, 5, 10, 6, 7)
AND API.INVOICE_TYPE_ID IN (55, 56, 57, 58, 59, 60)
AND (CASE WHEN IN_DIVISION_ID != -1 THEN API.DIVISION_ID = IN_DIVISION_ID ELSE API.DIVISION_ID != IN_DIVISION_ID END)
AND (CASE WHEN IN_YEAR != -1 THEN YEAR(API.GL_DATE) = IN_YEAR ELSE YEAR(API.GL_DATE) != IN_YEAR END)
AND (CASE WHEN IN_QUARTER != -1 THEN QUARTER(API.GL_DATE) = IN_QUARTER ELSE QUARTER(API.GL_DATE) != IN_QUARTER END)
AND (CASE WHEN IN_MONTH != -1 THEN MONTH(API.GL_DATE) = IN_MONTH ELSE MONTH(API.GL_DATE) != IN_MONTH END)

UNION ALL

SELECT (CASE WHEN TAX_TYPE_ID IN (2,3) THEN "Purchases not qualified for Input Tax"
	WHEN TAX_TYPE_ID = 4  THEN "Purchases - Domestic Goods other than Capital Goods"
	WHEN TAX_TYPE_ID = 5  THEN "Purchases - Domestic Services"
	WHEN TAX_TYPE_ID = 10 THEN "Purchases - Importation of Goods other than Capital Goods"
	WHEN TAX_TYPE_ID = 6 THEN "Purchases - Capital Goods"
	WHEN TAX_TYPE_ID = 7 THEN "Purchases - Nonresident services" END) AS NAME, 0 AS TAX_BASE, 0 AS VAT_AMOUNT
FROM TAX_TYPE WHERE TAX_TYPE_ID IN (2, 3, 4, 5, 6, 7, 10)

) AS TBL
GROUP BY NAME;

END