
-- Description: Stored procedure that will retrieve forms by serial number

Delimiter //
DROP PROCEDURE IF EXISTS GET_REF_FORM_BY_SERIAL_NUMBER;
CREATE PROCEDURE GET_REF_FORM_BY_SERIAL_NUMBER(IN IN_SERIAL_NUMBER VARCHAR(50), IN IN_WAREHOUSE_ID INT, IN IN_SERIAL_ITEM_ID INT)
BEGIN

SELECT SOURCE, SERIAL_NUMBER FROM (

SELECT CONCAT('TR ', TR.TR_NUMBER) AS SOURCE, SI.SERIAL_NUMBER
FROM SERIAL_ITEM SI
INNER JOIN OBJECT_TO_OBJECT OTO ON OTO.TO_OBJECT_ID = SI.EB_OBJECT_ID
INNER JOIN R_TRANSFER_RECEIPT TR ON TR.EB_OBJECT_ID = OTO.FROM_OBJECT_ID
INNER JOIN FORM_WORKFLOW FW ON FW.FORM_WORKFLOW_ID = TR.FORM_WORKFLOW_ID
WHERE FW.CURRENT_STATUS_ID != 4
AND SI.ACTIVE = 1
AND OTO.OR_TYPE_ID = 55
AND TR.WAREHOUSE_FROM_ID = IN_WAREHOUSE_ID
AND SI.SERIAL_NUMBER = IN_SERIAL_NUMBER
AND SI.SERIAL_ITEM_ID != IN_SERIAL_ITEM_ID

UNION ALL

SELECT CONCAT('SAO ', SA.SA_NUMBER) AS SOURCE, SI.SERIAL_NUMBER
FROM SERIAL_ITEM SI
INNER JOIN OBJECT_TO_OBJECT OTO ON OTO.TO_OBJECT_ID = SI.EB_OBJECT_ID
INNER JOIN STOCK_ADJUSTMENT SA ON SA.EB_OBJECT_ID = OTO.FROM_OBJECT_ID
INNER JOIN FORM_WORKFLOW FW ON FW.FORM_WORKFLOW_ID = SA.FORM_WORKFLOW_ID
WHERE FW.CURRENT_STATUS_ID != 4
AND SI.ACTIVE = 1
AND OTO.OR_TYPE_ID = 63
AND SA.WAREHOUSE_ID = IN_WAREHOUSE_ID
AND SI.SERIAL_NUMBER = IN_SERIAL_NUMBER
AND SI.SERIAL_ITEM_ID != IN_SERIAL_ITEM_ID

UNION ALL

SELECT CONCAT('CS ', CS.CS_NUMBER) AS SOURCE, SI.SERIAL_NUMBER
FROM SERIAL_ITEM SI
INNER JOIN OBJECT_TO_OBJECT OTO ON OTO.TO_OBJECT_ID = SI.EB_OBJECT_ID
INNER JOIN CASH_SALE CS ON CS.EB_OBJECT_ID = OTO.FROM_OBJECT_ID
INNER JOIN FORM_WORKFLOW FW ON FW.FORM_WORKFLOW_ID = CS.FORM_WORKFLOW_ID
WHERE FW.CURRENT_STATUS_ID != 4
AND SI.ACTIVE = 1
AND OTO.OR_TYPE_ID = 67
AND SI.WAREHOUSE_ID = IN_WAREHOUSE_ID
AND SI.SERIAL_NUMBER = IN_SERIAL_NUMBER
AND SI.SERIAL_ITEM_ID != IN_SERIAL_ITEM_ID

UNION ALL

SELECT CONCAT('CSR ', CSR.CSR_NUMBER) AS SOURCE, SI.SERIAL_NUMBER
FROM SERIAL_ITEM SI
INNER JOIN OBJECT_TO_OBJECT OTO ON OTO.TO_OBJECT_ID = SI.EB_OBJECT_ID
INNER JOIN CASH_SALE_RETURN CSR ON CSR.EB_OBJECT_ID = OTO.FROM_OBJECT_ID
INNER JOIN FORM_WORKFLOW FW ON FW.FORM_WORKFLOW_ID = CSR.FORM_WORKFLOW_ID
WHERE FW.CURRENT_STATUS_ID != 4
AND SI.ACTIVE = 1
AND OTO.OR_TYPE_ID = 68
AND SI.WAREHOUSE_ID = IN_WAREHOUSE_ID
AND SI.SERIAL_NUMBER = IN_SERIAL_NUMBER
AND SI.SERIAL_ITEM_ID != IN_SERIAL_ITEM_ID

UNION ALL

SELECT CONCAT('PR ', PR.SEQUENCE_NO) AS SOURCE, SI.SERIAL_NUMBER
FROM SERIAL_ITEM SI
INNER JOIN OBJECT_TO_OBJECT OTO ON OTO.TO_OBJECT_ID = SI.EB_OBJECT_ID
INNER JOIN PROCESSING_REPORT PR ON PR.EB_OBJECT_ID = OTO.FROM_OBJECT_ID
INNER JOIN FORM_WORKFLOW FW ON FW.FORM_WORKFLOW_ID = PR.FORM_WORKFLOW_ID
WHERE FW.CURRENT_STATUS_ID != 4
AND SI.ACTIVE = 1
AND OTO.OR_TYPE_ID = 75
AND SI.WAREHOUSE_ID = IN_WAREHOUSE_ID
AND SI.SERIAL_NUMBER = IN_SERIAL_NUMBER
AND SI.SERIAL_ITEM_ID != IN_SERIAL_ITEM_ID

UNION ALL

SELECT CONCAT('AS ', ART.SEQUENCE_NO) AS SOURCE, SI.SERIAL_NUMBER
FROM SERIAL_ITEM SI
INNER JOIN OBJECT_TO_OBJECT OTO ON OTO.TO_OBJECT_ID = SI.EB_OBJECT_ID
INNER JOIN AR_TRANSACTION ART ON ART.EB_OBJECT_ID = OTO.FROM_OBJECT_ID
INNER JOIN FORM_WORKFLOW FW ON FW.FORM_WORKFLOW_ID = ART.FORM_WORKFLOW_ID
WHERE FW.CURRENT_STATUS_ID != 4
AND SI.ACTIVE = 1
AND OTO.OR_TYPE_ID = 102
AND SI.WAREHOUSE_ID = IN_WAREHOUSE_ID
AND SI.SERIAL_NUMBER = IN_SERIAL_NUMBER
AND SI.SERIAL_ITEM_ID != IN_SERIAL_ITEM_ID

UNION ALL

SELECT CONCAT('ASR ', ART.SEQUENCE_NO) AS SOURCE, SI.SERIAL_NUMBER
FROM SERIAL_ITEM SI
INNER JOIN OBJECT_TO_OBJECT OTO ON OTO.TO_OBJECT_ID = SI.EB_OBJECT_ID
INNER JOIN AR_TRANSACTION ART ON ART.EB_OBJECT_ID = OTO.FROM_OBJECT_ID
INNER JOIN FORM_WORKFLOW FW ON FW.FORM_WORKFLOW_ID = ART.FORM_WORKFLOW_ID
WHERE FW.CURRENT_STATUS_ID != 4
AND SI.ACTIVE = 1
AND OTO.OR_TYPE_ID = 103
AND SI.QUANTITY > 0
AND SI.WAREHOUSE_ID = IN_WAREHOUSE_ID
AND SI.SERIAL_NUMBER = IN_SERIAL_NUMBER
AND SI.SERIAL_ITEM_ID != IN_SERIAL_ITEM_ID

) AS FORM_TBL;
END //