-- Description: Stored proceedure that will the Quarterly Alphalist of Payees by filters. 

DELIMITER //
DROP PROCEDURE IF EXISTS GET_QUARTERLY_ALPHALIST_OF_PAYEES;//
CREATE PROCEDURE GET_QUARTERLY_ALPHALIST_OF_PAYEES (IN IN_COMPANY_ID INT, IN IN_DIVISION_ID INT, IN IN_MONTH INT, IN IN_YEAR INT, IN IN_WT_TYPE_ID VARCHAR(10))
BEGIN
DECLARE FIRST_MONTH INT; 
DECLARE SECOND_MONTH INT;
DECLARE THIRD_MONTH INT;

SET FIRST_MONTH = IN_MONTH;
SET SECOND_MONTH = IN_MONTH + 1;
SET THIRD_MONTH = IN_MONTH + 2;

SELECT TBL.SUPPLIER_ID, TBL.TIN, TBL.CORPORATE_NAME, TBL.NAME, TBL.LAST_NAME, TBL.FIRST_NAME, TBL.MIDDLE_NAME, TBL.ATC_CODE, TBL.DESCRIPTION,
SUM(TBL.FIRST_AMOUNT) AS FIRST_AMOUNT, GROUP_CONCAT(DISTINCT TBL.FIRST_TAX_RATE SEPARATOR ',') AS FIRST_TAX_RATE, SUM(TBL.FIRST_WT_AMOUNT) AS FIRST_WT_AMOUNT,
SUM(TBL.SECOND_AMOUNT) AS SECOND_AMOUNT, GROUP_CONCAT(DISTINCT TBL.SECOND_TAX_RATE SEPARATOR ',') AS SECOND_TAX_RATE, SUM(TBL.SECOND_WT_AMOUNT) AS SECOND_WT_AMOUNT,
SUM(TBL.THIRD_AMOUNT) AS THIRD_AMOUNT, GROUP_CONCAT(DISTINCT TBL.THIRD_TAX_RATE SEPARATOR ',') AS THIRD_TAX_RATE, SUM(TBL.THIRD_WT_AMOUNT) AS THIRD_WT_AMOUNT,
TBL.INVOICE_TYPE_ID, TBL.AP_INVOICE_ID FROM (

SELECT S.SUPPLIER_ID, AI.AP_INVOICE_ID, AI.INVOICE_TYPE_ID, S.TIN, IF(S.BUSINESS_CLASSIFICATION_ID = 2, S.NAME, '') AS CORPORATE_NAME,
IF(S.BUSINESS_CLASSIFICATION_ID = 1, CONCAT(S.LAST_NAME,', ', S.FIRST_NAME, ' ', S.MIDDLE_NAME), '') AS NAME, BA.NAME AS ATC_CODE, BA.DESCRIPTION,
S.LAST_NAME, S.FIRST_NAME, S.MIDDLE_NAME, COALESCE((SELECT SUM(AL.AMOUNT) FROM AP_LINE AL WHERE AL.AP_INVOICE_ID = AI.AP_INVOICE_ID), 0)
+ COALESCE((SELECT SUM(AIL.AMOUNT) FROM AP_INVOICE_LINE AIL WHERE AIL.AP_INVOICE_ID = AI.AP_INVOICE_ID), 0)
+ COALESCE((SELECT SUM(AIG.QUANTITY * COALESCE(AIG.UNIT_COST, 0)) FROM AP_INVOICE_GOODS AIG WHERE AIG.AP_INVOICE_ID = AI.AP_INVOICE_ID), 0)
+ COALESCE((SELECT SUM(SI.UNIT_COST) FROM SERIAL_ITEM SI INNER JOIN OBJECT_TO_OBJECT OTO ON OTO.TO_OBJECT_ID = SI.EB_OBJECT_ID
	WHERE OTO.FROM_OBJECT_ID = AI.EB_OBJECT_ID AND OTO.OR_TYPE_ID = 24001 AND SI.ACTIVE = 1), 0) AS FIRST_AMOUNT,
WAS.VALUE AS FIRST_TAX_RATE, AI.WT_AMOUNT AS FIRST_WT_AMOUNT, 0 AS SECOND_AMOUNT, 0 AS SECOND_TAX_RATE, 0 AS SECOND_WT_AMOUNT,
0 AS THIRD_AMOUNT, 0 AS THIRD_TAX_RATE, 0 AS THIRD_WT_AMOUNT
FROM AP_INVOICE AI
INNER JOIN SUPPLIER S ON S.SUPPLIER_ID = AI.SUPPLIER_ID
INNER JOIN WT_ACCOUNT_SETTING WAS ON WAS.WT_ACCOUNT_SETTING_ID = AI.WT_ACCOUNT_SETTING_ID
INNER JOIN BIR_ATC BA ON BA.BIR_ATC_ID = WAS.BIR_ATC_ID
INNER JOIN FORM_WORKFLOW FW ON FW.FORM_WORKFLOW_ID = AI.FORM_WORKFLOW_ID
WHERE FW.IS_COMPLETE = 1
AND AI.INVOICE_TYPE_ID IN (19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 37, 38, 39, 40, 41, 42, 49, 50, 51, 52, 53, 54)
AND IF(IN_COMPANY_ID != -1, AI.COMPANY_ID = IN_COMPANY_ID, AI.COMPANY_ID != IN_COMPANY_ID)
AND IF(IN_DIVISION_ID != -1, AI.DIVISION_ID = IN_DIVISION_ID, AI.DIVISION_ID != IN_DIVISION_ID)
AND YEAR(AI.GL_DATE) = IN_YEAR
AND MONTH(AI.GL_DATE) = FIRST_MONTH
AND AI.WT_ACCOUNT_SETTING_ID IS NOT NULL
AND FIND_IN_SET(WAS.WT_TYPE_ID, IN_WT_TYPE_ID) > 0

UNION ALL

SELECT S.SUPPLIER_ID, AI.AP_INVOICE_ID, AI.INVOICE_TYPE_ID, S.TIN, IF(S.BUSINESS_CLASSIFICATION_ID = 2, S.NAME, '') AS CORPORATE_NAME,
IF(S.BUSINESS_CLASSIFICATION_ID = 1, CONCAT(S.LAST_NAME,', ', S.FIRST_NAME, ' ', S.MIDDLE_NAME), '') AS NAME, BA.NAME AS ATC_CODE, BA.DESCRIPTION,
S.LAST_NAME, S.FIRST_NAME, S.MIDDLE_NAME, 0 AS FIRST_AMOUNT, 0 AS FIRST_TAX_RATE, 0 AS FIRST_WT_AMOUNT,
COALESCE((SELECT SUM(AL.AMOUNT) FROM AP_LINE AL WHERE AL.AP_INVOICE_ID = AI.AP_INVOICE_ID), 0)
+ COALESCE((SELECT SUM(AIL.AMOUNT) FROM AP_INVOICE_LINE AIL WHERE AIL.AP_INVOICE_ID = AI.AP_INVOICE_ID), 0)
+ COALESCE((SELECT SUM(AIG.QUANTITY * COALESCE(AIG.UNIT_COST, 0)) FROM AP_INVOICE_GOODS AIG WHERE AIG.AP_INVOICE_ID = AI.AP_INVOICE_ID), 0)
+ COALESCE((SELECT SUM(SI.UNIT_COST) FROM SERIAL_ITEM SI INNER JOIN OBJECT_TO_OBJECT OTO ON OTO.TO_OBJECT_ID = SI.EB_OBJECT_ID
	WHERE OTO.FROM_OBJECT_ID = AI.EB_OBJECT_ID AND OTO.OR_TYPE_ID = 24001 AND SI.ACTIVE = 1), 0) AS SECOND_AMOUNT,
WAS.VALUE AS SECOND_TAX_RATE, AI.WT_AMOUNT AS SECOND_WT_AMOUNT, 0 AS THIRD_AMOUNT, 0 AS THIRD_TAX_RATE, 0 AS THIRD_WT_AMOUNT
FROM AP_INVOICE AI
INNER JOIN SUPPLIER S ON S.SUPPLIER_ID = AI.SUPPLIER_ID
INNER JOIN WT_ACCOUNT_SETTING WAS ON WAS.WT_ACCOUNT_SETTING_ID = AI.WT_ACCOUNT_SETTING_ID
INNER JOIN BIR_ATC BA ON BA.BIR_ATC_ID = WAS.BIR_ATC_ID
INNER JOIN FORM_WORKFLOW FW ON FW.FORM_WORKFLOW_ID = AI.FORM_WORKFLOW_ID
WHERE FW.IS_COMPLETE = 1
AND AI.INVOICE_TYPE_ID IN (19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 37, 38, 39, 40, 41, 42, 49, 50, 51, 52, 53, 54)
AND IF(IN_COMPANY_ID != -1, AI.COMPANY_ID = IN_COMPANY_ID, AI.COMPANY_ID != IN_COMPANY_ID)
AND IF(IN_DIVISION_ID != -1, AI.DIVISION_ID = IN_DIVISION_ID, AI.DIVISION_ID != IN_DIVISION_ID)
AND YEAR(AI.GL_DATE) = IN_YEAR
AND MONTH(AI.GL_DATE) = SECOND_MONTH
AND AI.WT_ACCOUNT_SETTING_ID IS NOT NULL
AND FIND_IN_SET(WAS.WT_TYPE_ID, IN_WT_TYPE_ID) > 0

UNION ALL

SELECT AI.SUPPLIER_ID, AI.AP_INVOICE_ID, AI.INVOICE_TYPE_ID, S.TIN, IF(S.BUSINESS_CLASSIFICATION_ID = 2, S.NAME, '') AS CORPORATE_NAME,
IF(S.BUSINESS_CLASSIFICATION_ID = 1, CONCAT(S.LAST_NAME,', ', S.FIRST_NAME, ' ', S.MIDDLE_NAME), '') AS NAME, BA.NAME AS ATC_CODE, BA.DESCRIPTION,
S.LAST_NAME, S.FIRST_NAME, S.MIDDLE_NAME, 0 AS FIRST_AMOUNT, 0 AS FIRST_TAX_RATE, 0 AS FIRST_WT_AMOUNT, 0 AS SECOND_AMOUNT, 0 AS SECOND_TAX_RATE, 0 AS SECOND_WT_AMOUNT,
COALESCE((SELECT SUM(AL.AMOUNT) FROM AP_LINE AL WHERE AL.AP_INVOICE_ID = AI.AP_INVOICE_ID), 0)
+ COALESCE((SELECT SUM(AIL.AMOUNT) FROM AP_INVOICE_LINE AIL WHERE AIL.AP_INVOICE_ID = AI.AP_INVOICE_ID), 0)
+ COALESCE((SELECT SUM(AIG.QUANTITY * COALESCE(AIG.UNIT_COST, 0)) FROM AP_INVOICE_GOODS AIG WHERE AIG.AP_INVOICE_ID = AI.AP_INVOICE_ID), 0)
+ COALESCE((SELECT SUM(SI.UNIT_COST) FROM SERIAL_ITEM SI INNER JOIN OBJECT_TO_OBJECT OTO ON OTO.TO_OBJECT_ID = SI.EB_OBJECT_ID
	WHERE OTO.FROM_OBJECT_ID = AI.EB_OBJECT_ID AND OTO.OR_TYPE_ID = 24001 AND SI.ACTIVE = 1), 0) AS THIRD_AMOUNT, WAS.VALUE AS THIRD_TAX_RATE,
AI.WT_AMOUNT AS THIRD_WT_AMOUNT
FROM AP_INVOICE AI
INNER JOIN SUPPLIER S ON S.SUPPLIER_ID = AI.SUPPLIER_ID
INNER JOIN WT_ACCOUNT_SETTING WAS ON WAS.WT_ACCOUNT_SETTING_ID = AI.WT_ACCOUNT_SETTING_ID
INNER JOIN BIR_ATC BA ON BA.BIR_ATC_ID = WAS.BIR_ATC_ID
INNER JOIN FORM_WORKFLOW FW ON FW.FORM_WORKFLOW_ID = AI.FORM_WORKFLOW_ID
WHERE FW.IS_COMPLETE = 1
AND AI.INVOICE_TYPE_ID IN (19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 37, 38, 39, 40, 41, 42, 49, 50, 51, 52, 53, 54)
AND IF(IN_COMPANY_ID != -1, AI.COMPANY_ID = IN_COMPANY_ID, AI.COMPANY_ID != IN_COMPANY_ID)
AND IF(IN_DIVISION_ID != -1, AI.DIVISION_ID = IN_DIVISION_ID, AI.DIVISION_ID != IN_DIVISION_ID)
AND YEAR(AI.GL_DATE) = IN_YEAR
AND MONTH(AI.GL_DATE) = THIRD_MONTH
AND AI.WT_ACCOUNT_SETTING_ID IS NOT NULL
AND FIND_IN_SET(WAS.WT_TYPE_ID, IN_WT_TYPE_ID) > 0

UNION ALL

SELECT AI.SUPPLIER_ID, AI.AP_INVOICE_ID, AI.INVOICE_TYPE_ID, S.TIN, IF(S.BUSINESS_CLASSIFICATION_ID = 2, S.NAME, '') AS CORPORATE_NAME,
IF(S.BUSINESS_CLASSIFICATION_ID = 1, CONCAT(S.LAST_NAME,', ', S.FIRST_NAME, ' ', S.MIDDLE_NAME), '') AS NAME, BA.NAME AS ATC_CODE, BA.DESCRIPTION,
S.LAST_NAME, S.FIRST_NAME, S.MIDDLE_NAME, -(COALESCE((SELECT SUM(AIL.AMOUNT) FROM AP_INVOICE_LINE AIL WHERE AIL.AP_INVOICE_ID = AI.AP_INVOICE_ID), 0)
+ COALESCE((SELECT SUM(SI.UNIT_COST) FROM SERIAL_ITEM SI INNER JOIN OBJECT_TO_OBJECT OTO ON OTO.TO_OBJECT_ID = SI.EB_OBJECT_ID
	WHERE OTO.FROM_OBJECT_ID = AI.EB_OBJECT_ID AND OTO.OR_TYPE_ID = 105 AND SI.ACTIVE = 1), 0)
+ COALESCE((SELECT SUM((RTSI.QUANTITY * COALESCE(RTSI.UNIT_COST, 0))) FROM R_RETURN_TO_SUPPLIER_ITEM RTSI
	WHERE RTSI.AP_INVOICE_ID = AI.AP_INVOICE_ID), 0)) AS FIRST_AMOUNT, 0 AS FIRST_TAX_RATE, -AI.WT_AMOUNT AS FIRST_WT_AMOUNT,
0 AS SECOND_AMOUNT, 0 AS SECOND_TAX_RATE, 0 AS SECOND_WT_AMOUNT, 0 AS THIRD_AMOUNT, 0 AS THIRD_TAX_RATE, 0 AS THIRD_WT_AMOUNT
FROM AP_INVOICE AI
INNER JOIN SUPPLIER S ON S.SUPPLIER_ID = AI.SUPPLIER_ID
INNER JOIN WT_ACCOUNT_SETTING WAS ON WAS.WT_ACCOUNT_SETTING_ID = AI.WT_ACCOUNT_SETTING_ID
INNER JOIN BIR_ATC BA ON BA.BIR_ATC_ID = WAS.BIR_ATC_ID
INNER JOIN FORM_WORKFLOW FW ON FW.FORM_WORKFLOW_ID = AI.FORM_WORKFLOW_ID
WHERE FW.IS_COMPLETE
AND AI.INVOICE_TYPE_ID IN (31, 32, 33, 34, 35, 36)
AND IF(IN_COMPANY_ID != -1, AI.COMPANY_ID = IN_COMPANY_ID, AI.COMPANY_ID != IN_COMPANY_ID)
AND IF(IN_DIVISION_ID != -1, AI.DIVISION_ID = IN_DIVISION_ID, AI.DIVISION_ID != IN_DIVISION_ID)
AND YEAR(AI.GL_DATE) = IN_YEAR
AND MONTH(AI.GL_DATE) = FIRST_MONTH
AND AI.WT_ACCOUNT_SETTING_ID IS NOT NULL
AND FIND_IN_SET(WAS.WT_TYPE_ID, IN_WT_TYPE_ID) > 0

UNION ALL

SELECT AI.SUPPLIER_ID, AI.AP_INVOICE_ID, AI.INVOICE_TYPE_ID, S.TIN, IF(S.BUSINESS_CLASSIFICATION_ID = 2, S.NAME, '') AS CORPORATE_NAME,
IF(S.BUSINESS_CLASSIFICATION_ID = 1, CONCAT(S.LAST_NAME,', ', S.FIRST_NAME, ' ', S.MIDDLE_NAME), '') AS NAME, BA.NAME AS ATC_CODE,
BA.DESCRIPTION, S.LAST_NAME, S.FIRST_NAME, S.MIDDLE_NAME, 0 AS FIRST_AMOUNT, 0 AS FIRST_TAX_RATE, 0 AS FIRST_WT_AMOUNT,
-(COALESCE((SELECT SUM(AIL.AMOUNT) FROM AP_INVOICE_LINE AIL WHERE AIL.AP_INVOICE_ID = AI.AP_INVOICE_ID), 0)
+ COALESCE((SELECT SUM(SI.UNIT_COST) FROM SERIAL_ITEM SI INNER JOIN OBJECT_TO_OBJECT OTO ON OTO.TO_OBJECT_ID = SI.EB_OBJECT_ID
	WHERE OTO.FROM_OBJECT_ID = AI.EB_OBJECT_ID AND OTO.OR_TYPE_ID = 105 AND SI.ACTIVE = 1), 0)
+ COALESCE((SELECT SUM((RTSI.QUANTITY * COALESCE(RTSI.UNIT_COST, 0))) FROM R_RETURN_TO_SUPPLIER_ITEM RTSI
	WHERE RTSI.AP_INVOICE_ID = AI.AP_INVOICE_ID), 0)) AS SECOND_AMOUNT, 0 AS SECOND_TAX_RATE, -AI.WT_AMOUNT AS SECOND_WT_AMOUNT,
0 AS THIRD_AMOUNT, 0 AS THIRD_TAX_RATE, 0 AS THIRD_WT_AMOUNT
FROM AP_INVOICE AI
INNER JOIN SUPPLIER S ON S.SUPPLIER_ID = AI.SUPPLIER_ID
INNER JOIN WT_ACCOUNT_SETTING WAS ON WAS.WT_ACCOUNT_SETTING_ID = AI.WT_ACCOUNT_SETTING_ID
INNER JOIN BIR_ATC BA ON BA.BIR_ATC_ID = WAS.BIR_ATC_ID
INNER JOIN FORM_WORKFLOW FW ON FW.FORM_WORKFLOW_ID = AI.FORM_WORKFLOW_ID
WHERE FW.IS_COMPLETE = 1
AND AI.INVOICE_TYPE_ID IN (31, 32, 33, 34, 35, 36)
AND IF(IN_COMPANY_ID != -1, AI.COMPANY_ID = IN_COMPANY_ID, AI.COMPANY_ID != IN_COMPANY_ID)
AND IF(IN_DIVISION_ID != -1, AI.DIVISION_ID = IN_DIVISION_ID, AI.DIVISION_ID != IN_DIVISION_ID)
AND YEAR(AI.GL_DATE) = IN_YEAR
AND MONTH(AI.GL_DATE) = SECOND_MONTH
AND AI.WT_ACCOUNT_SETTING_ID IS NOT NULL
AND FIND_IN_SET(WAS.WT_TYPE_ID, IN_WT_TYPE_ID) > 0

UNION ALL

SELECT AI.SUPPLIER_ID, AI.AP_INVOICE_ID, AI.INVOICE_TYPE_ID, S.TIN, IF(S.BUSINESS_CLASSIFICATION_ID = 2, S.NAME, '') AS CORPORATE_NAME,
IF(S.BUSINESS_CLASSIFICATION_ID = 1, CONCAT(S.LAST_NAME, ', ', S.FIRST_NAME, ' ', S.MIDDLE_NAME), '') AS NAME, BA.NAME AS ATC_CODE, BA.DESCRIPTION,
S.LAST_NAME, S.FIRST_NAME, S.MIDDLE_NAME, 0 AS FIRST_AMOUNT, 0 AS FIRST_TAX_RATE,0 AS FIRST_WT_AMOUNT, 0 AS SECOND_AMOUNT, 0 AS SECOND_TAX_RATE, 0 AS SECOND_WT_AMOUNT,
-(COALESCE((SELECT SUM(AIL.AMOUNT) FROM AP_INVOICE_LINE AIL WHERE AIL.AP_INVOICE_ID = AI.AP_INVOICE_ID), 0)
+ COALESCE((SELECT SUM(SI.UNIT_COST) FROM SERIAL_ITEM SI INNER JOIN OBJECT_TO_OBJECT OTO ON OTO.TO_OBJECT_ID = SI.EB_OBJECT_ID
	WHERE OTO.FROM_OBJECT_ID = AI.EB_OBJECT_ID AND OTO.OR_TYPE_ID = 105 AND SI.ACTIVE = 1), 0)
+ COALESCE((SELECT SUM((RTSI.QUANTITY * COALESCE(RTSI.UNIT_COST, 0))) FROM R_RETURN_TO_SUPPLIER_ITEM RTSI
	WHERE RTSI.AP_INVOICE_ID = AI.AP_INVOICE_ID), 0)) AS THIRD_AMOUNT, 0 AS THIRD_TAX_RATE, -AI.WT_AMOUNT AS THIRD_WT_AMOUNT
FROM AP_INVOICE AI
INNER JOIN SUPPLIER S ON S.SUPPLIER_ID = AI.SUPPLIER_ID
INNER JOIN WT_ACCOUNT_SETTING WAS ON WAS.WT_ACCOUNT_SETTING_ID = AI.WT_ACCOUNT_SETTING_ID
INNER JOIN BIR_ATC BA ON BA.BIR_ATC_ID = WAS.BIR_ATC_ID
INNER JOIN FORM_WORKFLOW FW ON FW.FORM_WORKFLOW_ID = AI.FORM_WORKFLOW_ID
WHERE FW.IS_COMPLETE = 1
AND AI.INVOICE_TYPE_ID IN (31, 32, 33, 34, 35, 36)
AND IF(IN_COMPANY_ID != -1, AI.COMPANY_ID = IN_COMPANY_ID, AI.COMPANY_ID != IN_COMPANY_ID)
AND IF(IN_DIVISION_ID != -1, AI.DIVISION_ID = IN_DIVISION_ID, AI.DIVISION_ID != IN_DIVISION_ID)
AND YEAR(AI.GL_DATE) = IN_YEAR
AND MONTH(AI.GL_DATE) = THIRD_MONTH
AND AI.WT_ACCOUNT_SETTING_ID IS NOT NULL
AND FIND_IN_SET(WAS.WT_TYPE_ID, IN_WT_TYPE_ID) > 0

) AS TBL GROUP BY TBL.SUPPLIER_ID, TBL.ATC_CODE
HAVING (FIRST_AMOUNT + SECOND_AMOUNT + THIRD_AMOUNT) NOT BETWEEN -0.009 AND 0.009
ORDER BY TBL.CORPORATE_NAME, TBL.NAME;
END//