-- Description: Stored procedure that will get the daily item sales.


Delimiter //
DROP PROCEDURE IF EXISTS GET_DAILY_ITEM_SALE_DETAIL;//
CREATE PROCEDURE GET_DAILY_ITEM_SALE_DETAIL (IN IN_COMPANY_ID INT, IN IN_STOCK_CODE VARCHAR(50), 
IN IN_INVOICE_NO VARCHAR(100), IN IN_DATE_FROM DATE, IN IN_DATE_TO DATE, IN IN_ITEM_CATEGORY_ID INT, IN IN_WAREHOUSE_ID INT)
BEGIN
	
SELECT SOURCE, SEQUENCE_NO, INVOICE_NO, QUANTITY, AMOUNT FROM (
-- Cash Sale
 SELECT 'CASH SALES' AS SOURCE, CONCAT('CS ', CS.CS_NUMBER) AS SEQUENCE_NO,
  CS.SALE_INVOICE_NO AS INVOICE_NO, QUANTITY, (CSI.AMOUNT + COALESCE(CSI.VAT_AMOUNT, 0)) AS AMOUNT
 FROM CASH_SALE_ITEM CSI
  INNER JOIN ITEM I ON I.ITEM_ID = CSI.ITEM_ID
  INNER JOIN CASH_SALE CS ON CS.CASH_SALE_ID = CSI.CASH_SALE_ID
  INNER JOIN COMPANY C ON C.COMPANY_ID = CS.COMPANY_ID
  INNER JOIN FORM_WORKFLOW FW ON FW.FORM_WORKFLOW_ID = CS.FORM_WORKFLOW_ID
  INNER JOIN WAREHOUSE W ON CSI.WAREHOUSE_ID = W.WAREHOUSE_ID
 WHERE IS_COMPLETE = 1
  AND C.COMPANY_ID = IN_COMPANY_ID
  AND I.STOCK_CODE = IN_STOCK_CODE
  AND CS.SALE_INVOICE_NO LIKE CONCAT('%', IN_INVOICE_NO, '%')
  AND (RECEIPT_DATE BETWEEN IN_DATE_FROM AND IN_DATE_TO)
  AND (CASE WHEN IN_ITEM_CATEGORY_ID != -1 THEN I.ITEM_CATEGORY_ID = IN_ITEM_CATEGORY_ID
   ELSE I.ITEM_CATEGORY_ID = I.ITEM_CATEGORY_ID END)
  AND (CASE WHEN IN_WAREHOUSE_ID != -1 THEN CSI.WAREHOUSE_ID = IN_WAREHOUSE_ID
  ELSE CSI.WAREHOUSE_ID = CSI.WAREHOUSE_ID END)
  AND CS.CASH_SALE_TYPE_ID=1

 UNION ALL

 -- Cash Sale - Customer Type
 SELECT 'CASH SALES' AS SOURCE, CONCAT('CS ', CS.CS_NUMBER) AS SEQUENCE_NO,
  CS.SALE_INVOICE_NO AS INVOICE_NO, QUANTITY,  AMOUNT
 FROM CASH_SALE_ITEM CSI
  INNER JOIN ITEM I ON I.ITEM_ID = CSI.ITEM_ID
  INNER JOIN CASH_SALE CS ON CS.CASH_SALE_ID = CSI.CASH_SALE_ID
  INNER JOIN COMPANY C ON C.COMPANY_ID = CS.COMPANY_ID
  INNER JOIN FORM_WORKFLOW FW ON FW.FORM_WORKFLOW_ID = CS.FORM_WORKFLOW_ID
  INNER JOIN WAREHOUSE W ON CSI.WAREHOUSE_ID = W.WAREHOUSE_ID
 WHERE IS_COMPLETE = 1
  AND C.COMPANY_ID = IN_COMPANY_ID
  AND I.STOCK_CODE = IN_STOCK_CODE
  AND CS.SALE_INVOICE_NO LIKE CONCAT('%', IN_INVOICE_NO, '%')
  AND (RECEIPT_DATE BETWEEN IN_DATE_FROM AND IN_DATE_TO)
  AND (CASE WHEN IN_ITEM_CATEGORY_ID != -1 THEN I.ITEM_CATEGORY_ID = IN_ITEM_CATEGORY_ID
   ELSE I.ITEM_CATEGORY_ID = I.ITEM_CATEGORY_ID END)
  AND (CASE WHEN IN_WAREHOUSE_ID != -1 THEN CSI.WAREHOUSE_ID = IN_WAREHOUSE_ID
  ELSE CSI.WAREHOUSE_ID = CSI.WAREHOUSE_ID END)
  AND CS.CASH_SALE_TYPE_ID=5

 UNION ALL
-- Cash Sale - Wholesale
 SELECT 'CASH SALES' AS SOURCE, CONCAT('CS-W ', CS.CS_NUMBER) AS SEQUENCE_NO,
   CS.SALE_INVOICE_NO AS INVOICE_NO, QUANTITY,  AMOUNT
 FROM CASH_SALE_ITEM CSI
  INNER JOIN ITEM I ON I.ITEM_ID = CSI.ITEM_ID
  INNER JOIN CASH_SALE CS ON CS.CASH_SALE_ID = CSI.CASH_SALE_ID
  INNER JOIN COMPANY C ON C.COMPANY_ID = CS.COMPANY_ID
  INNER JOIN FORM_WORKFLOW FW ON FW.FORM_WORKFLOW_ID = CS.FORM_WORKFLOW_ID
  INNER JOIN WAREHOUSE W ON CSI.WAREHOUSE_ID = W.WAREHOUSE_ID
 WHERE IS_COMPLETE = 1
  AND C.COMPANY_ID = IN_COMPANY_ID
  AND I.STOCK_CODE = IN_STOCK_CODE
  AND CS.SALE_INVOICE_NO LIKE CONCAT('%', IN_INVOICE_NO, '%')
  AND (RECEIPT_DATE BETWEEN IN_DATE_FROM AND IN_DATE_TO)
  AND (CASE WHEN IN_ITEM_CATEGORY_ID != -1 THEN I.ITEM_CATEGORY_ID = IN_ITEM_CATEGORY_ID
   ELSE I.ITEM_CATEGORY_ID = I.ITEM_CATEGORY_ID END)
  AND (CASE WHEN IN_WAREHOUSE_ID != -1 THEN CSI.WAREHOUSE_ID = IN_WAREHOUSE_ID
   ELSE CSI.WAREHOUSE_ID = CSI.WAREHOUSE_ID END)
  AND CS.CASH_SALE_TYPE_ID=2
 UNION ALL
 -- Cash Sale - INDIVIDUAL SELECTION
 SELECT 'CASH SALES' AS SOURCE, CONCAT('CS-IS ', CS.CS_NUMBER) AS SEQUENCE_NO,
   CS.SALE_INVOICE_NO AS INVOICE_NO, QUANTITY,  AMOUNT
 FROM CASH_SALE_ITEM CSI
  INNER JOIN ITEM I ON I.ITEM_ID = CSI.ITEM_ID
  INNER JOIN CASH_SALE CS ON CS.CASH_SALE_ID = CSI.CASH_SALE_ID
  INNER JOIN COMPANY C ON C.COMPANY_ID = CS.COMPANY_ID
  INNER JOIN FORM_WORKFLOW FW ON FW.FORM_WORKFLOW_ID = CS.FORM_WORKFLOW_ID
  INNER JOIN WAREHOUSE W ON CSI.WAREHOUSE_ID = W.WAREHOUSE_ID
 WHERE IS_COMPLETE = 1
  AND C.COMPANY_ID = IN_COMPANY_ID
  AND I.STOCK_CODE = IN_STOCK_CODE
  AND CS.SALE_INVOICE_NO LIKE CONCAT('%', IN_INVOICE_NO, '%')
  AND (RECEIPT_DATE BETWEEN IN_DATE_FROM AND IN_DATE_TO)
  AND (CASE WHEN IN_ITEM_CATEGORY_ID != -1 THEN I.ITEM_CATEGORY_ID = IN_ITEM_CATEGORY_ID
   ELSE I.ITEM_CATEGORY_ID = I.ITEM_CATEGORY_ID END)
  AND (CASE WHEN IN_WAREHOUSE_ID != -1 THEN CSI.WAREHOUSE_ID = IN_WAREHOUSE_ID
   ELSE CSI.WAREHOUSE_ID = CSI.WAREHOUSE_ID END)
  AND CS.CASH_SALE_TYPE_ID=3
 UNION ALL
 -- Cash Sale - Consolidated POS
 SELECT 'CASH SALES' AS SOURCE, CONCAT('CS-POS ', CS.CS_NUMBER) AS SEQUENCE_NO,
   '' AS INVOICE_NO, QUANTITY,  AMOUNT
 FROM CASH_SALE_ITEM CSI
  INNER JOIN ITEM I ON I.ITEM_ID = CSI.ITEM_ID
  INNER JOIN CASH_SALE CS ON CS.CASH_SALE_ID = CSI.CASH_SALE_ID
  INNER JOIN COMPANY C ON C.COMPANY_ID = CS.COMPANY_ID
  INNER JOIN FORM_WORKFLOW FW ON FW.FORM_WORKFLOW_ID = CS.FORM_WORKFLOW_ID
  INNER JOIN WAREHOUSE W ON CSI.WAREHOUSE_ID = W.WAREHOUSE_ID
 WHERE IS_COMPLETE = 1
  AND C.COMPANY_ID = IN_COMPANY_ID
  AND I.STOCK_CODE = IN_STOCK_CODE
  AND (RECEIPT_DATE BETWEEN IN_DATE_FROM AND IN_DATE_TO)
  AND (CASE WHEN IN_ITEM_CATEGORY_ID != -1 THEN I.ITEM_CATEGORY_ID = IN_ITEM_CATEGORY_ID
   ELSE I.ITEM_CATEGORY_ID = I.ITEM_CATEGORY_ID END)
  AND (CASE WHEN IN_WAREHOUSE_ID != -1 THEN CSI.WAREHOUSE_ID = IN_WAREHOUSE_ID
   ELSE CSI.WAREHOUSE_ID = CSI.WAREHOUSE_ID END)
  AND CS.CASH_SALE_TYPE_ID=4

 UNION ALL

 -- Cash Sale - Processing
 SELECT 'CASH SALES' AS SOURCE, CONCAT('CS ', CS.CS_NUMBER) AS SEQUENCE_NO,
  CS.SALE_INVOICE_NO AS INVOICE_NO, QUANTITY,  AMOUNT
 FROM CASH_SALE_ITEM CSI
  INNER JOIN ITEM I ON I.ITEM_ID = CSI.ITEM_ID
  INNER JOIN CASH_SALE CS ON CS.CASH_SALE_ID = CSI.CASH_SALE_ID
  INNER JOIN COMPANY C ON C.COMPANY_ID = CS.COMPANY_ID
  INNER JOIN FORM_WORKFLOW FW ON FW.FORM_WORKFLOW_ID = CS.FORM_WORKFLOW_ID
  INNER JOIN WAREHOUSE W ON CSI.WAREHOUSE_ID = W.WAREHOUSE_ID
 WHERE IS_COMPLETE = 1
  AND C.COMPANY_ID = IN_COMPANY_ID
  AND I.STOCK_CODE = IN_STOCK_CODE
  AND CS.SALE_INVOICE_NO LIKE CONCAT('%', IN_INVOICE_NO, '%')
  AND (RECEIPT_DATE BETWEEN IN_DATE_FROM AND IN_DATE_TO)
  AND (CASE WHEN IN_ITEM_CATEGORY_ID != -1 THEN I.ITEM_CATEGORY_ID = IN_ITEM_CATEGORY_ID
   ELSE I.ITEM_CATEGORY_ID = I.ITEM_CATEGORY_ID END)
  AND (CASE WHEN IN_WAREHOUSE_ID != -1 THEN CSI.WAREHOUSE_ID = IN_WAREHOUSE_ID
  ELSE CSI.WAREHOUSE_ID = CSI.WAREHOUSE_ID END)
  AND CS.CASH_SALE_TYPE_ID = 6

 UNION ALL

-- Account Sale
 SELECT 'ACCOUNT SALES' AS SOURCE, CONCAT('AS ', SEQUENCE_NO),
  TRANSACTION_NUMBER AS INVOICE_NO, QUANTITY, (ASI.AMOUNT + COALESCE(ASI.VAT_AMOUNT, 0)) AS AMOUNT
 FROM ACCOUNT_SALE_ITEM ASI
  INNER JOIN ITEM I ON I.ITEM_ID = ASI.ITEM_ID
  INNER JOIN AR_TRANSACTION ART ON ART.AR_TRANSACTION_ID = ASI.AR_TRANSACTION_ID
  INNER JOIN COMPANY C ON C.COMPANY_ID = ART.COMPANY_ID
  INNER JOIN FORM_WORKFLOW FW ON FW.FORM_WORKFLOW_ID = ART.FORM_WORKFLOW_ID
  INNER JOIN WAREHOUSE W ON ASI.WAREHOUSE_ID = W.WAREHOUSE_ID
 WHERE IS_COMPLETE = 1
  AND C.COMPANY_ID = IN_COMPANY_ID
  AND I.STOCK_CODE = IN_STOCK_CODE
  AND TRANSACTION_NUMBER LIKE CONCAT('%', IN_INVOICE_NO, '%')
  AND (TRANSACTION_DATE BETWEEN IN_DATE_FROM AND IN_DATE_TO)
  AND AR_TRANSACTION_TYPE_ID = 4
  AND (CASE WHEN IN_ITEM_CATEGORY_ID != -1 THEN I.ITEM_CATEGORY_ID = IN_ITEM_CATEGORY_ID
   ELSE I.ITEM_CATEGORY_ID = I.ITEM_CATEGORY_ID END)
  AND (CASE WHEN IN_WAREHOUSE_ID != -1 THEN ASI.WAREHOUSE_ID = IN_WAREHOUSE_ID
   ELSE ASI.WAREHOUSE_ID = ASI.WAREHOUSE_ID END)

 UNION ALL

-- Account Sale - Customer Type
 SELECT 'ACCOUNT SALES' AS SOURCE, CONCAT('AS ', SEQUENCE_NO),
  TRANSACTION_NUMBER AS INVOICE_NO, QUANTITY, ASI.AMOUNT
 FROM ACCOUNT_SALE_ITEM ASI
  INNER JOIN ITEM I ON I.ITEM_ID = ASI.ITEM_ID
  INNER JOIN AR_TRANSACTION ART ON ART.AR_TRANSACTION_ID = ASI.AR_TRANSACTION_ID
  INNER JOIN COMPANY C ON C.COMPANY_ID = ART.COMPANY_ID
  INNER JOIN FORM_WORKFLOW FW ON FW.FORM_WORKFLOW_ID = ART.FORM_WORKFLOW_ID
  INNER JOIN WAREHOUSE W ON ASI.WAREHOUSE_ID = W.WAREHOUSE_ID
 WHERE IS_COMPLETE = 1
  AND C.COMPANY_ID = IN_COMPANY_ID
  AND I.STOCK_CODE = IN_STOCK_CODE
  AND TRANSACTION_NUMBER LIKE CONCAT('%', IN_INVOICE_NO, '%')
  AND (TRANSACTION_DATE BETWEEN IN_DATE_FROM AND IN_DATE_TO)
  AND AR_TRANSACTION_TYPE_ID = 12
  AND (CASE WHEN IN_ITEM_CATEGORY_ID != -1 THEN I.ITEM_CATEGORY_ID = IN_ITEM_CATEGORY_ID
   ELSE I.ITEM_CATEGORY_ID = I.ITEM_CATEGORY_ID END)
  AND (CASE WHEN IN_WAREHOUSE_ID != -1 THEN ASI.WAREHOUSE_ID = IN_WAREHOUSE_ID
   ELSE ASI.WAREHOUSE_ID = ASI.WAREHOUSE_ID END)

UNION ALL

-- Account Sale Prescription
 SELECT 'ACCOUNT SALES' AS SOURCE, CONCAT('AS/P ', SEQUENCE_NO),
  TRANSACTION_NUMBER AS INVOICE_NO, QUANTITY, ASI.AMOUNT
 FROM ACCOUNT_SALE_ITEM ASI
  INNER JOIN ITEM I ON I.ITEM_ID = ASI.ITEM_ID
  INNER JOIN AR_TRANSACTION ART ON ART.AR_TRANSACTION_ID = ASI.AR_TRANSACTION_ID
  INNER JOIN COMPANY C ON C.COMPANY_ID = ART.COMPANY_ID
  INNER JOIN FORM_WORKFLOW FW ON FW.FORM_WORKFLOW_ID = ART.FORM_WORKFLOW_ID
  INNER JOIN WAREHOUSE W ON ASI.WAREHOUSE_ID = W.WAREHOUSE_ID
 WHERE IS_COMPLETE = 1
  AND C.COMPANY_ID = IN_COMPANY_ID
  AND I.STOCK_CODE = IN_STOCK_CODE
  AND TRANSACTION_NUMBER LIKE CONCAT('%', IN_INVOICE_NO, '%')
  AND (TRANSACTION_DATE BETWEEN IN_DATE_FROM AND IN_DATE_TO)
  AND AR_TRANSACTION_TYPE_ID = 14
  AND (CASE WHEN IN_ITEM_CATEGORY_ID != -1 THEN I.ITEM_CATEGORY_ID = IN_ITEM_CATEGORY_ID
   ELSE I.ITEM_CATEGORY_ID = I.ITEM_CATEGORY_ID END)
  AND (CASE WHEN IN_WAREHOUSE_ID != -1 THEN ASI.WAREHOUSE_ID = IN_WAREHOUSE_ID
   ELSE ASI.WAREHOUSE_ID = ASI.WAREHOUSE_ID END)

 UNION ALL

 SELECT 'ACCOUNT SALES' AS SOURCE, CONCAT('AS-W ', SEQUENCE_NO),
  TRANSACTION_NUMBER AS INVOICE_NO, QUANTITY, ASI.AMOUNT
 FROM ACCOUNT_SALE_ITEM ASI
  INNER JOIN ITEM I ON I.ITEM_ID = ASI.ITEM_ID
  INNER JOIN AR_TRANSACTION ART ON ART.AR_TRANSACTION_ID = ASI.AR_TRANSACTION_ID
  INNER JOIN COMPANY C ON C.COMPANY_ID = ART.COMPANY_ID
  INNER JOIN FORM_WORKFLOW FW ON FW.FORM_WORKFLOW_ID = ART.FORM_WORKFLOW_ID
  INNER JOIN WAREHOUSE W ON ASI.WAREHOUSE_ID = W.WAREHOUSE_ID
 WHERE IS_COMPLETE = 1
  AND C.COMPANY_ID = IN_COMPANY_ID
  AND I.STOCK_CODE = IN_STOCK_CODE
  AND TRANSACTION_NUMBER LIKE CONCAT('%', IN_INVOICE_NO, '%')
  AND (TRANSACTION_DATE BETWEEN IN_DATE_FROM AND IN_DATE_TO)
  AND AR_TRANSACTION_TYPE_ID = 8
  AND (CASE WHEN IN_ITEM_CATEGORY_ID != -1 THEN I.ITEM_CATEGORY_ID = IN_ITEM_CATEGORY_ID
   ELSE I.ITEM_CATEGORY_ID = I.ITEM_CATEGORY_ID END)
  AND (CASE WHEN IN_WAREHOUSE_ID != -1 THEN ASI.WAREHOUSE_ID = IN_WAREHOUSE_ID
   ELSE ASI.WAREHOUSE_ID = ASI.WAREHOUSE_ID END)

  UNION ALL
-- ACCOUNT SALE - IS
 SELECT 'ACCOUNT SALES' AS SOURCE, CONCAT('AS-IS ', SEQUENCE_NO),
  TRANSACTION_NUMBER AS INVOICE_NO, QUANTITY, ASI.AMOUNT
 FROM ACCOUNT_SALE_ITEM ASI
  INNER JOIN ITEM I ON I.ITEM_ID = ASI.ITEM_ID
  INNER JOIN AR_TRANSACTION ART ON ART.AR_TRANSACTION_ID = ASI.AR_TRANSACTION_ID
  INNER JOIN COMPANY C ON C.COMPANY_ID = ART.COMPANY_ID
  INNER JOIN FORM_WORKFLOW FW ON FW.FORM_WORKFLOW_ID = ART.FORM_WORKFLOW_ID
  INNER JOIN WAREHOUSE W ON ASI.WAREHOUSE_ID = W.WAREHOUSE_ID
 WHERE IS_COMPLETE = 1
  AND C.COMPANY_ID = IN_COMPANY_ID
  AND I.STOCK_CODE = IN_STOCK_CODE
  AND TRANSACTION_NUMBER LIKE CONCAT('%', IN_INVOICE_NO, '%')
  AND (TRANSACTION_DATE BETWEEN IN_DATE_FROM AND IN_DATE_TO)
  AND AR_TRANSACTION_TYPE_ID = 10
  AND (CASE WHEN IN_ITEM_CATEGORY_ID != -1 THEN I.ITEM_CATEGORY_ID = IN_ITEM_CATEGORY_ID
   ELSE I.ITEM_CATEGORY_ID = I.ITEM_CATEGORY_ID END)
  AND (CASE WHEN IN_WAREHOUSE_ID != -1 THEN ASI.WAREHOUSE_ID = IN_WAREHOUSE_ID
   ELSE ASI.WAREHOUSE_ID = ASI.WAREHOUSE_ID END)

  UNION ALL

-- PAID IN ADVANCE DELIVERY
  SELECT 'PAID IN ADVANCE DELIVERY' AS SOURCE,
  CONCAT('PIAD', CAP_DEL.CAPD_NUMBER) AS SEQUENCE_NO , CAP_DEL.SALES_INVOICE_NO AS
  INVOICE_NO, CDI.QUANTITY, (CDI.AMOUNT + COALESCE(CDI.VAT_AMOUNT, 0)) AS AMOUNT
  FROM CAP_DELIVERY CAP_DEL
  INNER JOIN CAP_DELIVERY_ITEM CDI ON CDI.CAP_DELIVERY_ID = CAP_DEL.CAP_DELIVERY_ID
  INNER JOIN COMPANY C ON C.COMPANY_ID = CAP_DEL.COMPANY_ID
  INNER JOIN FORM_WORKFLOW FW ON FW.FORM_WORKFLOW_ID = CAP_DEL.FORM_WORKFLOW_ID
  INNER JOIN ITEM I ON I.ITEM_ID = CDI.ITEM_ID
  INNER JOIN WAREHOUSE W ON CDI.WAREHOUSE_ID = W.WAREHOUSE_ID
 WHERE IS_COMPLETE = 1
  AND C.COMPANY_ID = IN_COMPANY_ID
  AND I.STOCK_CODE = IN_STOCK_CODE
  AND SALES_INVOICE_NO LIKE CONCAT('%', IN_INVOICE_NO, '%')
  AND (DELIVERY_DATE BETWEEN IN_DATE_FROM AND IN_DATE_TO)
  AND (CASE WHEN IN_ITEM_CATEGORY_ID != -1 THEN I.ITEM_CATEGORY_ID = IN_ITEM_CATEGORY_ID
   ELSE I.ITEM_CATEGORY_ID = I.ITEM_CATEGORY_ID END)
  AND (CASE WHEN IN_WAREHOUSE_ID != -1 THEN CDI.WAREHOUSE_ID = IN_WAREHOUSE_ID
   ELSE CDI.WAREHOUSE_ID = CDI.WAREHOUSE_ID END)
  AND CAP_DEL.CUSTOMER_ADVANCE_PAYMENT_TYPE_ID = 1

UNION ALL

-- PAID IN ADVANCE DELIVERY - IS
  SELECT 'PAID IN ADVANCE DELIVERY - IS' AS SOURCE,
  CONCAT('PIAD-IS', CAP_DEL.CAPD_NUMBER) AS SEQUENCE_NO , CAP_DEL.SALES_INVOICE_NO AS
  INVOICE_NO, CDI.QUANTITY, CDI.AMOUNT FROM CAP_DELIVERY CAP_DEL
  INNER JOIN CAP_DELIVERY_ITEM CDI ON CDI.CAP_DELIVERY_ID = CAP_DEL.CAP_DELIVERY_ID
  INNER JOIN COMPANY C ON C.COMPANY_ID = CAP_DEL.COMPANY_ID
  INNER JOIN FORM_WORKFLOW FW ON FW.FORM_WORKFLOW_ID = CAP_DEL.FORM_WORKFLOW_ID
  INNER JOIN ITEM I ON I.ITEM_ID = CDI.ITEM_ID
  INNER JOIN WAREHOUSE W ON CDI.WAREHOUSE_ID = W.WAREHOUSE_ID
 WHERE IS_COMPLETE = 1
  AND C.COMPANY_ID = IN_COMPANY_ID
  AND I.STOCK_CODE = IN_STOCK_CODE
  AND SALES_INVOICE_NO LIKE CONCAT('%', IN_INVOICE_NO, '%')
  AND (DELIVERY_DATE BETWEEN IN_DATE_FROM AND IN_DATE_TO)
  AND (CASE WHEN IN_ITEM_CATEGORY_ID != -1 THEN I.ITEM_CATEGORY_ID = IN_ITEM_CATEGORY_ID
   ELSE I.ITEM_CATEGORY_ID = I.ITEM_CATEGORY_ID END)
  AND (CASE WHEN IN_WAREHOUSE_ID != -1 THEN CDI.WAREHOUSE_ID = IN_WAREHOUSE_ID
   ELSE CDI.WAREHOUSE_ID = CDI.WAREHOUSE_ID END)
  AND CAP_DEL.CUSTOMER_ADVANCE_PAYMENT_TYPE_ID = 3

UNION ALL

-- PAID IN ADVANCE DELIVERY - ACCOUNT SALE
  SELECT 'PAID IN ADVANCE DELIVERY - AS' AS SOURCE,
  CONCAT('PIAD-', CAP_DEL.CAPD_NUMBER) AS SEQUENCE_NO , CAP_DEL.SALES_INVOICE_NO AS
  INVOICE_NO, CDI.QUANTITY, CDI.AMOUNT FROM CAP_DELIVERY CAP_DEL
  INNER JOIN CAP_DELIVERY_ITEM CDI ON CDI.CAP_DELIVERY_ID = CAP_DEL.CAP_DELIVERY_ID
  INNER JOIN COMPANY C ON C.COMPANY_ID = CAP_DEL.COMPANY_ID
  INNER JOIN FORM_WORKFLOW FW ON FW.FORM_WORKFLOW_ID = CAP_DEL.FORM_WORKFLOW_ID
  INNER JOIN ITEM I ON I.ITEM_ID = CDI.ITEM_ID
  INNER JOIN WAREHOUSE W ON CDI.WAREHOUSE_ID = W.WAREHOUSE_ID
 WHERE IS_COMPLETE = 1
  AND C.COMPANY_ID = IN_COMPANY_ID
  AND I.STOCK_CODE = IN_STOCK_CODE
  AND SALES_INVOICE_NO LIKE CONCAT('%', IN_INVOICE_NO, '%')
  AND (DELIVERY_DATE BETWEEN IN_DATE_FROM AND IN_DATE_TO)
  AND (CASE WHEN IN_ITEM_CATEGORY_ID != -1 THEN I.ITEM_CATEGORY_ID = IN_ITEM_CATEGORY_ID
   ELSE I.ITEM_CATEGORY_ID = I.ITEM_CATEGORY_ID END)
  AND (CASE WHEN IN_WAREHOUSE_ID != -1 THEN CDI.WAREHOUSE_ID = IN_WAREHOUSE_ID
   ELSE CDI.WAREHOUSE_ID = CDI.WAREHOUSE_ID END)
  AND CAP_DEL.CUSTOMER_ADVANCE_PAYMENT_TYPE_ID = 4

UNION ALL

-- PAID IN ADVANCE DELIVERY - ACCOUNT SALE
  SELECT 'PAID IN ADVANCE DELIVERY - AS' AS SOURCE,
  CONCAT('PIAD-', CAP_DEL.CAPD_NUMBER) AS SEQUENCE_NO , CAP_DEL.SALES_INVOICE_NO AS
  INVOICE_NO, CDI.QUANTITY, CDI.AMOUNT FROM CAP_DELIVERY CAP_DEL
  INNER JOIN CAP_DELIVERY_ITEM CDI ON CDI.CAP_DELIVERY_ID = CAP_DEL.CAP_DELIVERY_ID
  INNER JOIN COMPANY C ON C.COMPANY_ID = CAP_DEL.COMPANY_ID
  INNER JOIN FORM_WORKFLOW FW ON FW.FORM_WORKFLOW_ID = CAP_DEL.FORM_WORKFLOW_ID
  INNER JOIN ITEM I ON I.ITEM_ID = CDI.ITEM_ID
  INNER JOIN WAREHOUSE W ON CDI.WAREHOUSE_ID = W.WAREHOUSE_ID
 WHERE IS_COMPLETE = 1
  AND C.COMPANY_ID = IN_COMPANY_ID
  AND I.STOCK_CODE = IN_STOCK_CODE
  AND SALES_INVOICE_NO LIKE CONCAT('%', IN_INVOICE_NO, '%')
  AND (DELIVERY_DATE BETWEEN IN_DATE_FROM AND IN_DATE_TO)
  AND (CASE WHEN IN_ITEM_CATEGORY_ID != -1 THEN I.ITEM_CATEGORY_ID = IN_ITEM_CATEGORY_ID
   ELSE I.ITEM_CATEGORY_ID = I.ITEM_CATEGORY_ID END)
  AND (CASE WHEN IN_WAREHOUSE_ID != -1 THEN CDI.WAREHOUSE_ID = IN_WAREHOUSE_ID
   ELSE CDI.WAREHOUSE_ID = CDI.WAREHOUSE_ID END)
  AND CAP_DEL.CUSTOMER_ADVANCE_PAYMENT_TYPE_ID = 5

) AS DIS;
END//
