-- Description: Stored procedure that will get the annual alphalist withholding taxes expanded


Delimiter //
DROP procedure IF EXISTS GET_ANNUAL_ALPHALIST_WT_EXPANDED;//
CREATE procedure GET_ANNUAL_ALPHALIST_WT_EXPANDED (IN IN_COMPANY_ID INT, IN IN_DIVISION_ID INT, IN IN_YEAR INT, IN SCHEDULE_ID INT, IN IN_LIMIT_FROM INT, IN IN_LIMIT_TO INT)

BEGIN
	SELECT ID, TIN, REGISTERED_NAME, LAST_NAME, FIRST_NAME, MIDDLE_NAME, ATC_CODE,
	SUM(INCOME_PAYMENT) AS INCOME_PAYMENT, TAX_RATE, SUM(TAX_AMOUNT) AS TAX_AMOUNT, SUPPLIER_ID FROM (
	SELECT ID, TIN, REGISTERED_NAME, LAST_NAME, FIRST_NAME, MIDDLE_NAME, ATC_CODE,
	SUM(INCOME_PAYMENT) AS INCOME_PAYMENT, TAX_RATE, TAX_AMOUNT AS TAX_AMOUNT, SUPPLIER_ID FROM (

	SELECT AP.AP_INVOICE_ID AS ID, S.TIN,
	IF(S.BUSINESS_CLASSIFICATION_ID=2,S.NAME,'') AS REGISTERED_NAME,
	IF(S.BUSINESS_CLASSIFICATION_ID=1,S.LAST_NAME,'') AS LAST_NAME,
	IF(S.BUSINESS_CLASSIFICATION_ID=1,S.FIRST_NAME,'') AS FIRST_NAME,
	IF(S.BUSINESS_CLASSIFICATION_ID=1,S.MIDDLE_NAME,'') AS MIDDLE_NAME,
	ATC.NAME AS ATC_CODE,
	(CASE WHEN AP.INVOICE_TYPE_ID BETWEEN 31 AND 36 THEN -SUM(SI.AMOUNT)
	ELSE SUM(SI.AMOUNT) END) AS INCOME_PAYMENT,
	WAS.VALUE AS TAX_RATE, (CASE WHEN AP.INVOICE_TYPE_ID BETWEEN 31 AND 36 THEN -AP.WT_AMOUNT
	ELSE AP.WT_AMOUNT END) AS TAX_AMOUNT, AP.SUPPLIER_ID
	FROM AP_INVOICE AP
	INNER JOIN OBJECT_TO_OBJECT OTO ON OTO.FROM_OBJECT_ID = AP.EB_OBJECT_ID
	INNER JOIN SERIAL_ITEM SI ON SI.EB_OBJECT_ID = OTO.TO_OBJECT_ID
	INNER JOIN WT_ACCOUNT_SETTING WAS ON WAS.WT_ACCOUNT_SETTING_ID = AP.WT_ACCOUNT_SETTING_ID
	INNER JOIN SUPPLIER S ON S.SUPPLIER_ID = AP.SUPPLIER_ID
	INNER JOIN BIR_ATC ATC ON ATC.BIR_ATC_ID = WAS.BIR_ATC_ID
	INNER JOIN FORM_WORKFLOW FW ON FW.FORM_WORKFLOW_ID = AP.FORM_WORKFLOW_ID
	WHERE FW.IS_COMPLETE=1 AND INVOICE_TYPE_ID IN (25,26,27,28,29,30,31,32,33,34,35,36)
	AND WAS.WT_TYPE_ID = 0 AND (OTO.OR_TYPE_ID=24001 OR OTO.OR_TYPE_ID=105 )
	AND AP.COMPANY_ID = IN_COMPANY_ID
	AND IF(IN_DIVISION_ID != -1, AP.DIVISION_ID = IN_DIVISION_ID, AP.DIVISION_ID != IN_DIVISION_ID )
	AND YEAR(AP.GL_DATE) = IN_YEAR
	AND (CASE WHEN SCHEDULE_ID = 4 THEN SI.TAX_TYPE_ID = 2
			WHEN SCHEDULE_ID = 3 THEN  SI.TAX_TYPE_ID != 2
			ELSE SI.TAX_TYPE_ID != SCHEDULE_ID END)
	GROUP BY AP.AP_INVOICE_ID
	-- Invoice Line
	UNION ALL

	SELECT AP.AP_INVOICE_ID AS ID, S.TIN,
	IF(S.BUSINESS_CLASSIFICATION_ID=2,S.NAME,'') AS REGISTERED_NAME,
	IF(S.BUSINESS_CLASSIFICATION_ID=1,S.LAST_NAME,'') AS LAST_NAME,
	IF(S.BUSINESS_CLASSIFICATION_ID=1,S.FIRST_NAME,'') AS FIRST_NAME,
	IF(S.BUSINESS_CLASSIFICATION_ID=1,S.MIDDLE_NAME,'') AS MIDDLE_NAME,
	ATC.NAME AS ATC_CODE,
	(CASE WHEN AP.INVOICE_TYPE_ID BETWEEN 31 AND 36 THEN -SUM(APL.AMOUNT)
	ELSE SUM(APL.AMOUNT) END) AS INCOME_PAYMENT,
	WAS.VALUE AS TAX_RATE,
	(CASE WHEN AP.INVOICE_TYPE_ID BETWEEN 31 AND 36 THEN -AP.WT_AMOUNT 
	  ELSE AP.WT_AMOUNT END)  AS TAX_AMOUNT, AP.SUPPLIER_ID
	FROM AP_INVOICE AP
	INNER JOIN AP_INVOICE_LINE APL ON APL.AP_INVOICE_ID = AP.AP_INVOICE_ID
	INNER JOIN WT_ACCOUNT_SETTING WAS ON WAS.WT_ACCOUNT_SETTING_ID = AP.WT_ACCOUNT_SETTING_ID
	INNER JOIN SUPPLIER S ON S.SUPPLIER_ID = AP.SUPPLIER_ID 
	INNER JOIN BIR_ATC ATC ON ATC.BIR_ATC_ID = WAS.BIR_ATC_ID
	INNER JOIN FORM_WORKFLOW FW ON FW.FORM_WORKFLOW_ID = AP.FORM_WORKFLOW_ID
	WHERE FW.IS_COMPLETE=1 AND INVOICE_TYPE_ID IN(25,26,27,28,29,30,31,32,33,34,35,36)
	AND WAS.WT_TYPE_ID = 0
	AND AP.COMPANY_ID = IN_COMPANY_ID
	AND IF(IN_DIVISION_ID != -1, AP.DIVISION_ID = IN_DIVISION_ID, AP.DIVISION_ID != IN_DIVISION_ID )
	AND YEAR(AP.GL_DATE) = IN_YEAR
	AND (CASE WHEN SCHEDULE_ID = 4 THEN APL.TAX_TYPE_ID = 2
			WHEN SCHEDULE_ID = 3 THEN  APL.TAX_TYPE_ID != 2
			ELSE APL.TAX_TYPE_ID != SCHEDULE_ID END)
	GROUP BY AP.AP_INVOICE_ID
	-- INVOICE GOODS
	UNION ALL

	SELECT AP.AP_INVOICE_ID AS ID, S.TIN,
	IF(S.BUSINESS_CLASSIFICATION_ID=2,S.NAME,'') AS REGISTERED_NAME,
	IF(S.BUSINESS_CLASSIFICATION_ID=1,S.LAST_NAME,'') AS LAST_NAME,
	IF(S.BUSINESS_CLASSIFICATION_ID=1,S.FIRST_NAME,'') AS FIRST_NAME,
	IF(S.BUSINESS_CLASSIFICATION_ID=1,S.MIDDLE_NAME,'') AS MIDDLE_NAME,
	ATC.NAME AS ATC_CODE,
	SUM((APG.UNIT_COST*APG.QUANTITY) - COALESCE(APG.VAT_AMOUNT,0) - COALESCE(APG.DISCOUNT,0)) AS INCOME_PAYMENT,
	WAS.VALUE AS TAX_RATE, (CASE WHEN AP.INVOICE_TYPE_ID BETWEEN 31 AND 36 THEN -AP.WT_AMOUNT
	ELSE AP.WT_AMOUNT END)  AS TAX_AMOUNT, AP.SUPPLIER_ID
	FROM AP_INVOICE AP
	INNER JOIN AP_INVOICE_GOODS APG ON APG.AP_INVOICE_ID = AP.AP_INVOICE_ID
	INNER JOIN WT_ACCOUNT_SETTING WAS ON WAS.WT_ACCOUNT_SETTING_ID = AP.WT_ACCOUNT_SETTING_ID
	INNER JOIN SUPPLIER S ON S.SUPPLIER_ID = AP.SUPPLIER_ID
	INNER JOIN BIR_ATC ATC ON ATC.BIR_ATC_ID = WAS.BIR_ATC_ID
	INNER JOIN FORM_WORKFLOW FW ON FW.FORM_WORKFLOW_ID = AP.FORM_WORKFLOW_ID
	WHERE FW.IS_COMPLETE=1 AND INVOICE_TYPE_ID IN (25,26,27,28,29,30)
	AND WAS.WT_TYPE_ID = 0
	AND AP.COMPANY_ID = IN_COMPANY_ID
	AND IF(IN_DIVISION_ID != -1, AP.DIVISION_ID = IN_DIVISION_ID, AP.DIVISION_ID != IN_DIVISION_ID )
	AND YEAR(AP.GL_DATE) = IN_YEAR
	AND (CASE WHEN SCHEDULE_ID = 4 THEN APG.TAX_TYPE_ID = 2
			WHEN SCHEDULE_ID = 3 THEN  APG.TAX_TYPE_ID != 2
			ELSE APG.TAX_TYPE_ID != SCHEDULE_ID END)
	GROUP BY AP.AP_INVOICE_ID

	UNION ALL

	SELECT AP.AP_INVOICE_ID AS ID, S.TIN,
	IF(S.BUSINESS_CLASSIFICATION_ID=2,S.NAME,'') AS REGISTERED_NAME,
	IF(S.BUSINESS_CLASSIFICATION_ID=1,S.LAST_NAME,'') AS LAST_NAME,
	IF(S.BUSINESS_CLASSIFICATION_ID=1,S.FIRST_NAME,'') AS FIRST_NAME,
	IF(S.BUSINESS_CLASSIFICATION_ID=1,S.MIDDLE_NAME,'') AS MIDDLE_NAME,
	ATC.NAME AS ATC_CODE,
	-(SUM((RI.UNIT_COST*RI.QUANTITY) - COALESCE(RI.VAT_AMOUNT,0) - COALESCE(RI.DISCOUNT,0))) AS INCOME_PAYMENT,
	WAS.VALUE AS TAX_RATE, (CASE WHEN AP.INVOICE_TYPE_ID BETWEEN 31 AND 36 THEN -AP.WT_AMOUNT
	  ELSE AP.WT_AMOUNT END)  AS TAX_AMOUNT, AP.SUPPLIER_ID
	FROM AP_INVOICE AP
	INNER JOIN R_RETURN_TO_SUPPLIER RTS ON RTS.AP_INVOICE_ID = AP.AP_INVOICE_ID
	INNER JOIN R_RETURN_TO_SUPPLIER_ITEM RI ON RI.AP_INVOICE_ID = RTS.AP_INVOICE_ID
	INNER JOIN WT_ACCOUNT_SETTING WAS ON WAS.WT_ACCOUNT_SETTING_ID = AP.WT_ACCOUNT_SETTING_ID
	INNER JOIN SUPPLIER S ON S.SUPPLIER_ID = AP.SUPPLIER_ID
	INNER JOIN BIR_ATC ATC ON ATC.BIR_ATC_ID = WAS.BIR_ATC_ID
	INNER JOIN FORM_WORKFLOW FW ON FW.FORM_WORKFLOW_ID = AP.FORM_WORKFLOW_ID
	 WHERE FW.IS_COMPLETE=1 AND INVOICE_TYPE_ID IN (31,32,33,34,35,36)
	AND WAS.WT_TYPE_ID = 0
	AND AP.COMPANY_ID = IN_COMPANY_ID
	AND IF(IN_DIVISION_ID != -1, AP.DIVISION_ID = IN_DIVISION_ID, AP.DIVISION_ID != IN_DIVISION_ID )
	AND YEAR(AP.GL_DATE) = IN_YEAR
	AND (CASE WHEN SCHEDULE_ID = 4 THEN RI.TAX_TYPE_ID = 2
			WHEN SCHEDULE_ID = 3 THEN  RI.TAX_TYPE_ID != 2
			ELSE RI.TAX_TYPE_ID != SCHEDULE_ID END)
	GROUP BY AP.AP_INVOICE_ID
	) AS INNRTBL GROUP BY ID

	UNION ALL

	SELECT AP.AP_INVOICE_ID AS ID, S.TIN,
	IF(S.BUSINESS_CLASSIFICATION_ID=2,S.NAME,'') AS REGISTERED_NAME,
	IF(S.BUSINESS_CLASSIFICATION_ID=1,S.LAST_NAME,'') AS LAST_NAME,
	IF(S.BUSINESS_CLASSIFICATION_ID=1,S.FIRST_NAME,'') AS FIRST_NAME,
	IF(S.BUSINESS_CLASSIFICATION_ID=1,S.MIDDLE_NAME,'') AS MIDDLE_NAME,
	ATC.NAME AS ATC_CODE,
	SUM(APL.AMOUNT) AS INCOME_PAYMENT,
	WAS.VALUE AS TAX_RATE, AP.WT_AMOUNT AS TAX_AMOUNT, AP.SUPPLIER_ID
	FROM AP_INVOICE AP
	INNER JOIN AP_LINE APL ON APL.AP_INVOICE_ID = AP.AP_INVOICE_ID
	INNER JOIN WT_ACCOUNT_SETTING WAS ON WAS.WT_ACCOUNT_SETTING_ID = AP.WT_ACCOUNT_SETTING_ID
	INNER JOIN SUPPLIER S ON S.SUPPLIER_ID = AP.SUPPLIER_ID
	INNER JOIN BIR_ATC ATC ON ATC.BIR_ATC_ID = WAS.BIR_ATC_ID
	INNER JOIN FORM_WORKFLOW FW ON FW.FORM_WORKFLOW_ID = AP.FORM_WORKFLOW_ID
	WHERE FW.IS_COMPLETE=1
	AND INVOICE_TYPE_ID IN (19,20,21,22,23,24,25,26,27,28,29,30,37,38,39,40,41,42,43,44,45,46,47,48)
	AND WAS.WT_TYPE_ID = 0
	AND AP.COMPANY_ID = IN_COMPANY_ID
	AND IF(IN_DIVISION_ID != -1, AP.DIVISION_ID = IN_DIVISION_ID, AP.DIVISION_ID != IN_DIVISION_ID )
	AND YEAR(AP.GL_DATE) = IN_YEAR
	AND (CASE WHEN SCHEDULE_ID = 4 THEN APL.TAX_TYPE_ID = 2
			WHEN SCHEDULE_ID = 3 THEN  APL.TAX_TYPE_ID != 2
			ELSE APL.TAX_TYPE_ID != SCHEDULE_ID END)
	GROUP BY AP.AP_INVOICE_ID
	)AS TBL GROUP BY SUPPLIER_ID, ATC_CODE ORDER BY ID ASC ;

END //