-- Description: Stored proceedure that will get the sales output report data.

Delimiter //
DROP procedure if exists GET_CAP_REGISTER;//
CREATE procedure GET_CAP_REGISTER (IN IN_COMPANY_ID INT, IN IN_DIVISION_ID INT, IN IN_AR_CUSTOMER_ID INT, IN IN_AR_CUSTOMER_ACCOUNT_ID INT,
	IN IN_DATE_FROM DATE, IN IN_DATE_TO DATE, IN IN_STATUS_ID INT, IN IN_LIMIT_FROM INT, IN IN_LIMIT_TO INT)
BEGIN

SELECT ID, SEQ_NO, DIVISION, DATE, CUSTOMER, CUSTOMER_ACCT, REFERENCE_NO, PO_NUMBER, AMOUNT, DELIVERY_AMT, STATUS, CANCELLATION_REMARKS,
COLLECTION_STATUS FROM (
	SELECT CAP.CUSTOMER_ADVANCE_PAYMENT_ID AS ID, CAP.CAP_NUMBER AS SEQ_NO, D.NAME AS DIVISION, CAP.RECEIPT_DATE AS DATE, 
	C.NAME AS CUSTOMER, CA.NAME AS CUSTOMER_ACCT, CONCAT('CAP ' , CAP.CAP_NUMBER) AS REFERENCE_NO, 
	CAP.PO_NUMBER AS PO_NUMBER, IF(FW.CURRENT_STATUS_ID = 4, 0,CAP.AMOUNT) AS AMOUNT, 0 AS DELIVERY_AMT, 
	FS.DESCRIPTION AS STATUS, IF(FW.CURRENT_STATUS_ID = 4, 
	(SELECT FWL.COMMENT FROM FORM_WORKFLOW_LOG FWL 
	WHERE FWL.FORM_WORKFLOW_ID = FW.FORM_WORKFLOW_ID AND FWL.FORM_STATUS_ID = 4) , '') AS CANCELLATION_REMARKS, '' AS COLLECTION_STATUS 
	FROM CUSTOMER_ADVANCE_PAYMENT CAP
	INNER JOIN AR_CUSTOMER C ON C.AR_CUSTOMER_ID = CAP.AR_CUSTOMER_ID 
	INNER JOIN DIVISION D ON CAP.DIVISION_ID = D.DIVISION_ID 
	INNER JOIN AR_CUSTOMER_ACCOUNT CA ON CA.AR_CUSTOMER_ACCOUNT_ID = CAP.AR_CUSTOMER_ACCOUNT_ID 
	INNER JOIN FORM_WORKFLOW FW ON FW.FORM_WORKFLOW_ID = CAP.FORM_WORKFLOW_ID 
	INNER JOIN FORM_STATUS FS ON FS.FORM_STATUS_ID = FW.CURRENT_STATUS_ID 
	WHERE CAP.EB_OBJECT_ID NOT IN (
		SELECT OTO.FROM_OBJECT_ID FROM AR_RECEIPT_LINE ARL
		INNER JOIN AR_RECEIPT ARR ON ARR.AR_RECEIPT_ID = ARL.AR_RECEIPT_ID
		INNER JOIN FORM_WORKFLOW FW1 ON FW1.FORM_WORKFLOW_ID = ARR.FORM_WORKFLOW_ID
		INNER JOIN OBJECT_TO_OBJECT OTO ON OTO.TO_OBJECT_ID = ARL.EB_OBJECT_ID
		WHERE FW1.CURRENT_STATUS_ID != 4
	)
	AND CAP.COMPANY_ID = IN_COMPANY_ID
	AND CAP.RECEIPT_DATE BETWEEN IN_DATE_FROM AND IN_DATE_TO
	AND IF(IN_DIVISION_ID != -1,  CAP.DIVISION_ID = IN_DIVISION_ID,  CAP.DIVISION_ID != IN_DIVISION_ID)
	AND IF(IN_AR_CUSTOMER_ID != -1, CAP.AR_CUSTOMER_ID = IN_AR_CUSTOMER_ID, CAP.AR_CUSTOMER_ID != IN_AR_CUSTOMER_ID)
	AND IF(IN_AR_CUSTOMER_ACCOUNT_ID != -1, CAP.AR_CUSTOMER_ACCOUNT_ID = IN_AR_CUSTOMER_ACCOUNT_ID, 
		CAP.AR_CUSTOMER_ACCOUNT_ID != IN_AR_CUSTOMER_ACCOUNT_ID )
	AND IF(IN_STATUS_ID != -1, FW.CURRENT_STATUS_ID = IN_STATUS_ID, FW.CURRENT_STATUS_ID != IN_STATUS_ID)
	
	UNION ALL
	
	SELECT CAP.CUSTOMER_ADVANCE_PAYMENT_ID AS ID, CAP.CAP_NUMBER AS SEQ_NO, D.NAME AS DIVISION, CAP.RECEIPT_DATE AS DATE, 
	C.NAME AS CUSTOMER, CA.NAME AS CUSTOMER_ACCT, CONCAT('CAP ' , CAP.CAP_NUMBER) AS REFERENCE_NO, 
	CAP.PO_NUMBER AS PO_NUMBER, IF(FW.CURRENT_STATUS_ID = 4, 0,CAP.AMOUNT) AS AMOUNT, 
	(SELECT COALESCE(SUM(ARL1.AMOUNT), 0) FROM AR_RECEIPT_LINE ARL1
		INNER JOIN AR_RECEIPT ARR1 ON ARR1.AR_RECEIPT_ID = ARL1.AR_RECEIPT_ID
		INNER JOIN FORM_WORKFLOW FW1 ON FW1.FORM_WORKFLOW_ID = ARR1.FORM_WORKFLOW_ID
		INNER JOIN OBJECT_TO_OBJECT OTO1 ON OTO1.TO_OBJECT_ID = ARL1.EB_OBJECT_ID
		WHERE FW1.CURRENT_STATUS_ID = 16
		AND OTO1.FROM_OBJECT_ID = CAP.EB_OBJECT_ID
		AND ARR1.AR_RECEIPT_ID <= ARR.AR_RECEIPT_ID) AS DELIVERY_AMT, 
	FS.DESCRIPTION AS STATUS, IF(FW.CURRENT_STATUS_ID = 4, 
	(SELECT FWL.COMMENT FROM FORM_WORKFLOW_LOG FWL 
	WHERE FWL.FORM_WORKFLOW_ID = FW.FORM_WORKFLOW_ID AND FWL.FORM_STATUS_ID = 4) , '') AS CANCELLATION_REMARKS, 
	ARR_FS.DESCRIPTION AS COLLECTION_STATUS
	FROM CUSTOMER_ADVANCE_PAYMENT CAP
	INNER JOIN AR_CUSTOMER C ON C.AR_CUSTOMER_ID = CAP.AR_CUSTOMER_ID 
	INNER JOIN DIVISION D ON CAP.DIVISION_ID = D.DIVISION_ID 
	INNER JOIN AR_CUSTOMER_ACCOUNT CA ON CA.AR_CUSTOMER_ACCOUNT_ID = CAP.AR_CUSTOMER_ACCOUNT_ID 
	INNER JOIN FORM_WORKFLOW FW ON FW.FORM_WORKFLOW_ID = CAP.FORM_WORKFLOW_ID 
	INNER JOIN FORM_STATUS FS ON FS.FORM_STATUS_ID = FW.CURRENT_STATUS_ID 
	INNER JOIN OBJECT_TO_OBJECT OTO ON OTO.FROM_OBJECT_ID = CAP.EB_OBJECT_ID
	INNER JOIN AR_RECEIPT_LINE ARL ON ARL.EB_OBJECT_ID = OTO.TO_OBJECT_ID
	INNER JOIN AR_RECEIPT ARR ON ARR.AR_RECEIPT_ID = ARL.AR_RECEIPT_ID
	INNER JOIN FORM_WORKFLOW ARR_FW ON ARR_FW.FORM_WORKFLOW_ID = ARR.FORM_WORKFLOW_ID
	INNER JOIN FORM_STATUS ARR_FS ON ARR_FS.FORM_STATUS_ID = ARR_FW.CURRENT_STATUS_ID
	WHERE ARR_FW.CURRENT_STATUS_ID != 4
	AND CAP.AMOUNT > (SELECT COALESCE(SUM(ARL.AMOUNT), 0) FROM AR_RECEIPT_LINE ARL
		INNER JOIN AR_RECEIPT ARR ON ARR.AR_RECEIPT_ID = ARL.AR_RECEIPT_ID
		INNER JOIN FORM_WORKFLOW FW1 ON FW1.FORM_WORKFLOW_ID = ARR.FORM_WORKFLOW_ID
		INNER JOIN OBJECT_TO_OBJECT OTO1 ON OTO1.TO_OBJECT_ID = ARL.EB_OBJECT_ID
		WHERE FW1.CURRENT_STATUS_ID = 16
		AND OTO1.FROM_OBJECT_ID = CAP.EB_OBJECT_ID
	)
	AND CAP.COMPANY_ID = IN_COMPANY_ID
	AND CAP.RECEIPT_DATE BETWEEN IN_DATE_FROM AND IN_DATE_TO
	AND IF(IN_DIVISION_ID != -1,  CAP.DIVISION_ID = IN_DIVISION_ID,  CAP.DIVISION_ID != IN_DIVISION_ID)
	AND IF(IN_AR_CUSTOMER_ID != -1, CAP.AR_CUSTOMER_ID = IN_AR_CUSTOMER_ID, CAP.AR_CUSTOMER_ID != IN_AR_CUSTOMER_ID)
	AND IF(IN_AR_CUSTOMER_ACCOUNT_ID != -1, CAP.AR_CUSTOMER_ACCOUNT_ID = IN_AR_CUSTOMER_ACCOUNT_ID, 
		CAP.AR_CUSTOMER_ACCOUNT_ID != IN_AR_CUSTOMER_ACCOUNT_ID )
	AND IF(IN_STATUS_ID != -1, FW.CURRENT_STATUS_ID = IN_STATUS_ID, FW.CURRENT_STATUS_ID != IN_STATUS_ID)
) AS CAP_REG_TBL ORDER BY DATE, CUSTOMER, CUSTOMER_ACCT, REFERENCE_NO;

END//
