-- Description: Stored procedure for retrieving data for certificate of final tax withheld at source


Delimiter //
DROP PROCEDURE IF EXISTS GET_FINAL_TAX_WITHHELD;
CREATE PROCEDURE GET_FINAL_TAX_WITHHELD(IN IN_COMPANY_ID INT, IN IN_DIVISION_ID INT, IN IN_YEAR INT, IN IN_MONTH_FROM INT, IN IN_MONTH_TO INT,
IN IN_BIR_ATC INT)

BEGIN

SELECT COLLECTION_MONTH, COLLECTION_DATE, CUSTOMER, OR_CR, NET, 2_3_0_7, 2_3_0_6, (GROSS_ITEM_NS + GROSS_SERVICE + GROSS_ITEM_S) AS GROSS FROM (

SELECT MONTHNAME(AR.DATE_RECEIVED) AS COLLECTION_MONTH, AR.DATE_RECEIVED AS COLLECTION_DATE,
	(CASE WHEN C.BUSINESS_CLASSIFICATION_ID = 2 THEN C.NAME
		WHEN C.BUSINESS_CLASSIFICATION_ID = 1 THEN concat(C.FIRST_NAME,' ', C.LAST_NAME)  END) AS CUSTOMER,
         NULL AS OR_CR, AR.AMOUNT AS NET,  AR.WT_AMOUNT AS 2_3_0_7, AR.WT_VAT_AMOUNT AS 2_3_0_6,
	COALESCE((SELECT SUM(ifnull(ARI.VAT_AMOUNT,0)+ARI.AMOUNT) FROM AR_INVOICE_ITEM ARI WHERE ARI.AR_INVOICE_ID = AR.AR_INVOICE_ID
	AND ARI.TAX_TYPE_ID = 9),0) AS GROSS_ITEM_NS,
    0 AS GROSS_SERVICE,
	COALESCE((SELECT SUM(SI.AMOUNT + SI.VAT_AMOUNT) FROM SERIAL_ITEM SI
		INNER JOIN OBJECT_TO_OBJECT O2O ON O2O.TO_OBJECT_ID = SI.EB_OBJECT_ID
		WHERE O2O.FROM_OBJECT_ID = AR.EB_OBJECT_ID 
		AND SI.TAX_TYPE_ID = 9 AND O2O.OR_TYPE_ID = 12006),0) AS GROSS_ITEM_S, (COALESCE((SELECT SUM(ifnull(ARI.VAT_AMOUNT,0)+ARI.AMOUNT) 
		FROM AR_INVOICE_ITEM ARI WHERE ARI.AR_INVOICE_ID = AR.AR_INVOICE_ID
	AND ARI.TAX_TYPE_ID = 9),0)+COALESCE((SELECT SUM(SI.AMOUNT + SI.VAT_AMOUNT) FROM SERIAL_ITEM SI
		INNER JOIN OBJECT_TO_OBJECT O2O ON O2O.TO_OBJECT_ID = SI.EB_OBJECT_ID
		WHERE O2O.FROM_OBJECT_ID = AR.EB_OBJECT_ID 
		AND SI.TAX_TYPE_ID = 9 AND O2O.OR_TYPE_ID = 12006),0)) AS GROSS,
	WT_VAT_AMOUNT FROM AR_INVOICE AR
INNER JOIN AR_CUSTOMER C ON C.AR_CUSTOMER_ID = AR.AR_CUSTOMER_ID
INNER JOIN FORM_WORKFLOW FW ON FW.FORM_WORKFLOW_ID = AR.FORM_WORKFLOW_ID
WHERE AR.COMPANY_ID = IN_COMPANY_ID
AND IF(IN_DIVISION_ID != -1, AR.DIVISION_ID = IN_DIVISION_ID, AR.DIVISION_ID != IN_DIVISION_ID )
AND YEAR(AR.DATE_RECEIVED) = IN_YEAR
AND MONTH(AR.DATE_RECEIVED) BETWEEN IN_MONTH_FROM AND IN_MONTH_TO
AND FW.IS_COMPLETE = 1
AND (AR.WT_AMOUNT  != 0 OR AR.WT_VAT_AMOUNT != 0)

UNION ALL

SELECT MONTHNAME(AR.DATE_RECEIVED) AS COLLECTION_MONTH, AR.DATE_RECEIVED AS COLLECTION_DATE,
	(CASE WHEN C.BUSINESS_CLASSIFICATION_ID = 2 THEN C.NAME
		WHEN C.BUSINESS_CLASSIFICATION_ID = 1 THEN concat(C.FIRST_NAME,' ', C.LAST_NAME)  END) AS CUSTOMER,
         NULL AS OR_CR, AR.AMOUNT AS NET,  AR.WT_AMOUNT AS 2_3_0_7, AR.WT_VAT_AMOUNT AS 2_3_0_6, 0 AS GROSS_ITEM_NS,
    COALESCE((SELECT SUM(ifnull(ARL.VAT_AMOUNT,0) + ARL.AMOUNT) FROM AR_INVOICE_LINE ARL
		WHERE ARL.AR_INVOICE_ID = AR.AR_INVOICE_ID
		AND ARL.TAX_TYPE_ID = 9),0) AS GROSS_SERVICE, 0 AS GROSS_ITEM_S, (COALESCE((SELECT SUM(ifnull(ARL.VAT_AMOUNT,0) + ARL.AMOUNT) 
		FROM AR_INVOICE_LINE ARL
		WHERE ARL.AR_INVOICE_ID = AR.AR_INVOICE_ID
		AND ARL.TAX_TYPE_ID = 9),0)) AS GROSS,
	WT_VAT_AMOUNT FROM AR_INVOICE AR
INNER JOIN AR_CUSTOMER C ON C.AR_CUSTOMER_ID = AR.AR_CUSTOMER_ID
INNER JOIN FORM_WORKFLOW FW ON FW.FORM_WORKFLOW_ID = AR.FORM_WORKFLOW_ID
WHERE AR.COMPANY_ID = IN_COMPANY_ID
AND IF(IN_DIVISION_ID != -1, AR.DIVISION_ID = IN_DIVISION_ID, AR.DIVISION_ID != IN_DIVISION_ID )
AND YEAR(AR.DATE_RECEIVED) = IN_YEAR
AND MONTH(AR.DATE_RECEIVED) BETWEEN IN_MONTH_FROM AND IN_MONTH_TO
AND FW.IS_COMPLETE = 1
AND (AR.WT_AMOUNT  != 0 OR AR.WT_VAT_AMOUNT != 0)

UNION ALL

SELECT MONTHNAME(ART.TRANSACTION_DATE) AS COLLECTION_MONTH, ART.TRANSACTION_DATE AS COLLECTION_DATE,
	(CASE WHEN C.BUSINESS_CLASSIFICATION_ID = 2 THEN C.NAME
		WHEN C.BUSINESS_CLASSIFICATION_ID = 1 THEN concat(C.FIRST_NAME,' ', C.LAST_NAME)  END) AS CUSTOMER,
         NULL AS OR_CR, ART.AMOUNT AS NET,  ART.WT_AMOUNT AS 2_3_0_7, ART.WT_VAT_AMOUNT AS 2_3_0_6, 0 AS GROSS_ITEM_NS,
    COALESCE((SELECT SUM(ASL.UP_AMOUNT) FROM AR_SERVICE_LINE ASL
		WHERE ASL.AR_TRANSACTION_ID = ART.AR_TRANSACTION_ID
		AND ASL.TAX_TYPE_ID = 9),0) AS GROSS_SERVICE, 0 AS GROSS_ITEM_S, (COALESCE((SELECT SUM(ASL.UP_AMOUNT) FROM AR_SERVICE_LINE ASL
		WHERE ASL.AR_TRANSACTION_ID = ART.AR_TRANSACTION_ID
		AND ASL.TAX_TYPE_ID = 9),0)) AS GROSS,
	WT_VAT_AMOUNT FROM AR_TRANSACTION ART
INNER JOIN AR_CUSTOMER C ON C.AR_CUSTOMER_ID = ART.CUSTOMER_ID
INNER JOIN FORM_WORKFLOW FW ON FW.FORM_WORKFLOW_ID = ART.FORM_WORKFLOW_ID
WHERE ART.COMPANY_ID = IN_COMPANY_ID
AND IF(IN_DIVISION_ID != -1, ART.DIVISION_ID = IN_DIVISION_ID, ART.DIVISION_ID != IN_DIVISION_ID)
AND YEAR(ART.TRANSACTION_DATE) = IN_YEAR
AND MONTH(ART.TRANSACTION_DATE) BETWEEN IN_MONTH_FROM AND IN_MONTH_TO
AND FW.IS_COMPLETE = 1
AND (ART.WT_AMOUNT  != 0 OR ART.WT_VAT_AMOUNT != 0)

UNION ALL

SELECT MONTHNAME(AM.RECEIPT_DATE) AS COLLECTION_MONTH, AM.RECEIPT_DATE AS COLLECTION_DATE,
	(CASE WHEN C.BUSINESS_CLASSIFICATION_ID = 2 THEN C.NAME
		WHEN C.BUSINESS_CLASSIFICATION_ID = 1 THEN concat(C.FIRST_NAME,' ', C.LAST_NAME)  END) AS CUSTOMER,
         NULL AS OR_CR, AM.AMOUNT AS NET,  AM.WT_AMOUNT AS 2_3_0_7, AM.WT_VAT_AMOUNT AS 2_3_0_6, 0 AS GROSS_ITEM_NS,
    COALESCE((SELECT SUM(AML.UP_AMOUNT) FROM AR_MISCELLANEOUS_LINE AML
		WHERE AML.AR_MISCELLANEOUS_ID = AM.AR_MISCELLANEOUS_ID
		AND AML.TAX_TYPE_ID = 9),0) AS GROSS_SERVICE, 0 AS GROSS_ITEM_S, (COALESCE((SELECT SUM(AML.UP_AMOUNT) FROM AR_MISCELLANEOUS_LINE AML
		WHERE AML.AR_MISCELLANEOUS_ID = AM.AR_MISCELLANEOUS_ID
		AND AML.TAX_TYPE_ID = 9),0)) AS GROSS,
	WT_VAT_AMOUNT FROM AR_MISCELLANEOUS AM
INNER JOIN AR_CUSTOMER C ON C.AR_CUSTOMER_ID = AM.AR_CUSTOMER_ID
INNER JOIN FORM_WORKFLOW FW ON FW.FORM_WORKFLOW_ID = AM.FORM_WORKFLOW_ID
WHERE AM.COMPANY_ID = IN_COMPANY_ID
AND IF(IN_DIVISION_ID != -1, AM.DIVISION_ID = IN_DIVISION_ID, AM.DIVISION_ID != IN_DIVISION_ID )
AND YEAR(AM.RECEIPT_DATE) = IN_YEAR
AND MONTH(AM.RECEIPT_DATE) BETWEEN IN_MONTH_FROM AND IN_MONTH_TO
AND FW.IS_COMPLETE = 1
AND (AM.WT_AMOUNT  != 0 OR AM.WT_VAT_AMOUNT != 0)

) AS TB1 WHERE GROSS != 0 ORDER BY COLLECTION_DATE;

END //