-- Description: Stored procedure that will get unposted forms within date range


Delimiter //
DROP PROCEDURE IF EXISTS GET_UNPOSTED_FORMS;
CREATE PROCEDURE GET_UNPOSTED_FORMS(IN IN_DATE_FROM date, IN IN_DATE_TO date)
BEGIN

SELECT SOURCE, ID, SEQUENCE_NO, REF_NUMBER, DATE FROM (
SELECT 'AP INVOICE' AS SOURCE, API.AP_INVOICE_ID AS ID,
CONCAT('API ', API.SEQUENCE_NO) AS SEQUENCE_NO,
CONCAT('Invoice No. ', API.INVOICE_NUMBER) AS REF_NUMBER,
API.GL_DATE AS DATE FROM AP_INVOICE API
INNER JOIN COMPANY C ON C.COMPANY_ID = API.COMPANY_ID
INNER JOIN FORM_WORKFLOW FW ON FW.FORM_WORKFLOW_ID = API.FORM_WORKFLOW_ID
WHERE FW.IS_COMPLETE = 0 AND FW.CURRENT_STATUS_ID != 4
AND API.GL_DATE BETWEEN IN_DATE_FROM AND IN_DATE_TO
AND API.INVOICE_TYPE_ID <= 4

UNION ALL

SELECT 'RECEIVING REPORT' AS SOURCE, API.AP_INVOICE_ID AS ID,
CONCAT('RR ', COALESCE(CONCAT(C.COMPANY_CODE,' ', API.SEQUENCE_NO), API.SEQUENCE_NO)) AS SEQUENCE_NO,
(CASE WHEN API.INVOICE_NUMBER != '' THEN CONCAT('SI No. ', API.INVOICE_NUMBER)
ELSE CONCAT('DR No. ', RR.DELIVERY_RECEIPT_NO) END) AS REF_NUMBER,
API.GL_DATE AS DATE FROM AP_INVOICE API
INNER JOIN R_RECEIVING_REPORT RR ON RR.AP_INVOICE_ID = API.AP_INVOICE_ID
INNER JOIN COMPANY C ON C.COMPANY_ID = RR.COMPANY_ID
INNER JOIN FORM_WORKFLOW FW ON FW.FORM_WORKFLOW_ID = API.FORM_WORKFLOW_ID
WHERE FW.IS_COMPLETE = 0 AND FW.CURRENT_STATUS_ID != 4
AND API.GL_DATE BETWEEN IN_DATE_FROM AND IN_DATE_TO
AND API.INVOICE_TYPE_ID = 5

UNION ALL

SELECT 'RETURN TO SUPPLIER' AS SOURCE, API.AP_INVOICE_ID AS ID, 
CONCAT('RTS ', API.SEQUENCE_NO) AS SEQUENCE_NO,
(CASE WHEN API.INVOICE_NUMBER != '' THEN CONCAT('Invoice No. ', API.INVOICE_NUMBER)
ELSE '' END) AS REF_NUMBER,
API.GL_DATE AS DATE FROM AP_INVOICE API
INNER JOIN R_RETURN_TO_SUPPLIER RTS ON RTS.AP_INVOICE_ID = API.AP_INVOICE_ID
INNER JOIN COMPANY C ON C.COMPANY_ID = RTS.COMPANY_ID
INNER JOIN FORM_WORKFLOW FW ON FW.FORM_WORKFLOW_ID = API.FORM_WORKFLOW_ID
WHERE FW.IS_COMPLETE = 0 AND FW.CURRENT_STATUS_ID != 4
AND API.GL_DATE BETWEEN IN_DATE_FROM AND IN_DATE_TO
AND API.INVOICE_TYPE_ID = 6

UNION ALL

SELECT 'RTS - EB' AS SOURCE, API.AP_INVOICE_ID AS ID,
CONCAT('RTS-EB ', API.SEQUENCE_NO) AS SEQUENCE_NO,
CONCAT('Invoice No. ', API.INVOICE_NUMBER) AS REF_NUMBER,
API.GL_DATE AS DATE FROM AP_INVOICE API
INNER JOIN R_RETURN_TO_SUPPLIER RTS ON RTS.AP_INVOICE_ID = API.AP_INVOICE_ID
INNER JOIN COMPANY C ON C.COMPANY_ID = RTS.COMPANY_ID
INNER JOIN FORM_WORKFLOW FW ON FW.FORM_WORKFLOW_ID = API.FORM_WORKFLOW_ID
WHERE FW.IS_COMPLETE = 0 AND FW.CURRENT_STATUS_ID != 4
AND API.GL_DATE BETWEEN IN_DATE_FROM AND IN_DATE_TO
AND API.INVOICE_TYPE_ID = 7

UNION ALL

SELECT 'RECEIVING REPORT - RM IS' AS SOURCE, API.AP_INVOICE_ID AS ID,
CONCAT('RR-RM IS ', API.SEQUENCE_NO) AS SEQUENCE_NO,
(CASE WHEN API.INVOICE_NUMBER != '' THEN CONCAT('SI No. ', API.INVOICE_NUMBER)
ELSE CONCAT('DR No. ', RR.DELIVERY_RECEIPT_NO) END) AS REF_NUMBER,
API.GL_DATE AS DATE FROM AP_INVOICE API
INNER JOIN R_RECEIVING_REPORT RR ON RR.AP_INVOICE_ID = API.AP_INVOICE_ID
INNER JOIN COMPANY C ON C.COMPANY_ID = RR.COMPANY_ID
INNER JOIN FORM_WORKFLOW FW ON FW.FORM_WORKFLOW_ID = API.FORM_WORKFLOW_ID
WHERE FW.IS_COMPLETE = 0 AND FW.CURRENT_STATUS_ID != 4
AND API.GL_DATE BETWEEN IN_DATE_FROM AND IN_DATE_TO
AND API.INVOICE_TYPE_ID = 8

UNION ALL

SELECT 'RECEIVING REPORT - RM P' AS SOURCE, API.AP_INVOICE_ID AS ID,
CONCAT('RR-RM P ', API.SEQUENCE_NO) AS SEQUENCE_NO,
CONCAT('SS No. ', API.INVOICE_NUMBER) AS REF_NUMBER,
API.GL_DATE AS DATE FROM AP_INVOICE API
INNER JOIN R_RECEIVING_REPORT RR ON RR.AP_INVOICE_ID = API.AP_INVOICE_ID
INNER JOIN COMPANY C ON C.COMPANY_ID = RR.COMPANY_ID
INNER JOIN FORM_WORKFLOW FW ON FW.FORM_WORKFLOW_ID = API.FORM_WORKFLOW_ID
WHERE FW.IS_COMPLETE = 0 AND FW.CURRENT_STATUS_ID != 4
AND API.GL_DATE BETWEEN IN_DATE_FROM AND IN_DATE_TO
AND API.INVOICE_TYPE_ID = 9

UNION ALL

SELECT 'AR TRANSACTION' AS SOURCE, ART.AR_TRANSACTION_ID AS ID,
CONCAT('ART ', ART.SEQUENCE_NO) AS SEQUENCE_NO,
CONCAT('Transaction No. ', ART.TRANSACTION_NUMBER) AS REF_NUMBER,
TRANSACTION_DATE AS DATE FROM AR_TRANSACTION ART
INNER JOIN COMPANY C ON C.COMPANY_ID = ART.COMPANY_ID
INNER JOIN FORM_WORKFLOW FW ON FW.FORM_WORKFLOW_ID = ART.FORM_WORKFLOW_ID
WHERE FW.IS_COMPLETE = 0 AND FW.CURRENT_STATUS_ID != 4
AND ART.TRANSACTION_DATE BETWEEN IN_DATE_FROM AND IN_DATE_TO
AND AR_TRANSACTION_TYPE_ID <= 3

UNION ALL

SELECT 'ACCOUNT SALES' AS SOURCE, ART.AR_TRANSACTION_ID AS ID,
CONCAT('AS ', ART.SEQUENCE_NO) AS SEQUENCE_NO,
'' AS REF_NUMBER, TRANSACTION_DATE AS DATE FROM AR_TRANSACTION ART
INNER JOIN COMPANY C ON C.COMPANY_ID = ART.COMPANY_ID
INNER JOIN FORM_WORKFLOW FW ON FW.FORM_WORKFLOW_ID = ART.FORM_WORKFLOW_ID
WHERE FW.IS_COMPLETE = 0 AND FW.CURRENT_STATUS_ID != 4
AND ART.TRANSACTION_DATE BETWEEN IN_DATE_FROM AND IN_DATE_TO
AND AR_TRANSACTION_TYPE_ID = 4

UNION ALL

SELECT 'ACCOUNT SALES RETURN' AS SOURCE, ART.AR_TRANSACTION_ID AS ID,
CONCAT('ASR ', ART.SEQUENCE_NO) AS SEQUENCE_NO,
'' AS REF_NUMBER, TRANSACTION_DATE AS DATE FROM AR_TRANSACTION ART
INNER JOIN COMPANY C ON C.COMPANY_ID = ART.COMPANY_ID
INNER JOIN FORM_WORKFLOW FW ON FW.FORM_WORKFLOW_ID = ART.FORM_WORKFLOW_ID
WHERE FW.IS_COMPLETE = 0 AND FW.CURRENT_STATUS_ID != 4
AND ART.TRANSACTION_DATE BETWEEN IN_DATE_FROM AND IN_DATE_TO
AND AR_TRANSACTION_TYPE_ID = 5

UNION ALL

SELECT 'ASR - EB' AS SOURCE, ART.AR_TRANSACTION_ID AS ID,
CONCAT('ASR-EB ', ART.SEQUENCE_NO) AS SEQUENCE_NO,
'' AS REF_NUMBER, TRANSACTION_DATE AS DATE FROM AR_TRANSACTION ART
INNER JOIN COMPANY C ON C.COMPANY_ID = ART.COMPANY_ID
INNER JOIN FORM_WORKFLOW FW ON FW.FORM_WORKFLOW_ID = ART.FORM_WORKFLOW_ID
WHERE FW.IS_COMPLETE = 0 AND FW.CURRENT_STATUS_ID != 4
AND ART.TRANSACTION_DATE BETWEEN IN_DATE_FROM AND IN_DATE_TO
AND AR_TRANSACTION_TYPE_ID = 7

UNION ALL

SELECT 'ACCOUNT SALES - WHOLESALE' AS SOURCE, ART.AR_TRANSACTION_ID AS ID,
CONCAT('AS-W ', ART.SEQUENCE_NO) AS SEQUENCE_NO,
'' AS REF_NUMBER, TRANSACTION_DATE AS DATE FROM AR_TRANSACTION ART
INNER JOIN COMPANY C ON C.COMPANY_ID = ART.COMPANY_ID
INNER JOIN FORM_WORKFLOW FW ON FW.FORM_WORKFLOW_ID = ART.FORM_WORKFLOW_ID
WHERE FW.IS_COMPLETE = 0 AND FW.CURRENT_STATUS_ID != 4
AND ART.TRANSACTION_DATE BETWEEN IN_DATE_FROM AND IN_DATE_TO
AND AR_TRANSACTION_TYPE_ID = 8

UNION ALL

SELECT 'ACCOUNT SALES RETURN - WHOLESALE' AS SOURCE, ART.AR_TRANSACTION_ID AS ID,
CONCAT('ASR-W ', ART.SEQUENCE_NO) AS SEQUENCE_NO,
'' AS REF_NUMBER, TRANSACTION_DATE AS DATE FROM AR_TRANSACTION ART
INNER JOIN COMPANY C ON C.COMPANY_ID = ART.COMPANY_ID
INNER JOIN FORM_WORKFLOW FW ON FW.FORM_WORKFLOW_ID = ART.FORM_WORKFLOW_ID
WHERE FW.IS_COMPLETE = 0 AND FW.CURRENT_STATUS_ID != 4
AND ART.TRANSACTION_DATE BETWEEN IN_DATE_FROM AND IN_DATE_TO
AND AR_TRANSACTION_TYPE_ID = 9

UNION ALL

SELECT 'ACCOUNT SALES - IS' AS SOURCE, ART.AR_TRANSACTION_ID AS ID,
CONCAT('AS-IS ', ART.SEQUENCE_NO) AS SEQUENCE_NO,
'' AS REF_NUMBER, TRANSACTION_DATE AS DATE FROM AR_TRANSACTION ART
INNER JOIN COMPANY C ON C.COMPANY_ID = ART.COMPANY_ID
INNER JOIN FORM_WORKFLOW FW ON FW.FORM_WORKFLOW_ID = ART.FORM_WORKFLOW_ID
WHERE FW.IS_COMPLETE = 0 AND FW.CURRENT_STATUS_ID != 4
AND ART.TRANSACTION_DATE BETWEEN IN_DATE_FROM AND IN_DATE_TO
AND AR_TRANSACTION_TYPE_ID = 10

UNION ALL

SELECT 'ACCOUNT SALES RETURN - IS' AS SOURCE, ART.AR_TRANSACTION_ID AS ID,
CONCAT('ASR-IS ', ART.SEQUENCE_NO) AS SEQUENCE_NO,
'' AS REF_NUMBER, TRANSACTION_DATE AS DATE FROM AR_TRANSACTION ART
INNER JOIN COMPANY C ON C.COMPANY_ID = ART.COMPANY_ID
INNER JOIN FORM_WORKFLOW FW ON FW.FORM_WORKFLOW_ID = ART.FORM_WORKFLOW_ID
WHERE FW.IS_COMPLETE = 0 AND FW.CURRENT_STATUS_ID != 4
AND ART.TRANSACTION_DATE BETWEEN IN_DATE_FROM AND IN_DATE_TO
AND AR_TRANSACTION_TYPE_ID = 11

UNION ALL

SELECT 'CASH SALES' AS SOURCE, CS.CASH_SALE_ID AS ID,
CONCAT('CS ', COALESCE(CONCAT(C.COMPANY_CODE,' ',CS.CS_NUMBER), CS.CS_NUMBER)) AS SEQUENCE_NO,
(CASE WHEN CS.SALE_INVOICE_NO != '' THEN 
CONCAT('SI No. ', CS.SALE_INVOICE_NO) ELSE '' END) AS REF_NUMBER,
RECEIPT_DATE AS DATE FROM CASH_SALE CS
INNER JOIN COMPANY C ON C.COMPANY_ID = CS.COMPANY_ID
INNER JOIN FORM_WORKFLOW FW ON FW.FORM_WORKFLOW_ID = CS.FORM_WORKFLOW_ID
WHERE FW.IS_COMPLETE = 0 AND FW.CURRENT_STATUS_ID != 4
AND CS.RECEIPT_DATE BETWEEN IN_DATE_FROM AND IN_DATE_TO
AND CS.CASH_SALE_TYPE_ID = 1

UNION ALL

SELECT 'CASH SALES - WHOLESALE' AS SOURCE, CS.CASH_SALE_ID AS ID, 
CONCAT('CS-W ', COALESCE(CONCAT(C.COMPANY_CODE,' ',CS.CS_NUMBER), CS.CS_NUMBER)) AS SEQUENCE_NO,
(CASE WHEN CS.SALE_INVOICE_NO != '' THEN 
CONCAT('SI No. ', CS.SALE_INVOICE_NO) ELSE '' END) AS REF_NUMBER,
RECEIPT_DATE AS DATE FROM CASH_SALE CS
INNER JOIN COMPANY C ON C.COMPANY_ID = CS.COMPANY_ID
INNER JOIN FORM_WORKFLOW FW ON FW.FORM_WORKFLOW_ID = CS.FORM_WORKFLOW_ID
WHERE FW.IS_COMPLETE = 0 AND FW.CURRENT_STATUS_ID != 4
AND CS.RECEIPT_DATE BETWEEN IN_DATE_FROM AND IN_DATE_TO
AND CS.CASH_SALE_TYPE_ID = 2

UNION ALL

SELECT 'CASH SALES - IS' AS SOURCE, CS.CASH_SALE_ID AS ID,
CONCAT('CS-IS ', COALESCE(CONCAT(C.COMPANY_CODE,' ',CS.CS_NUMBER), CS.CS_NUMBER)) AS SEQUENCE_NO,
(CASE WHEN CS.SALE_INVOICE_NO != '' THEN 
CONCAT('SI No. ', CS.SALE_INVOICE_NO) ELSE '' END) AS REF_NUMBER,
RECEIPT_DATE AS DATE FROM CASH_SALE CS
INNER JOIN COMPANY C ON C.COMPANY_ID = CS.COMPANY_ID
INNER JOIN FORM_WORKFLOW FW ON FW.FORM_WORKFLOW_ID = CS.FORM_WORKFLOW_ID
WHERE FW.IS_COMPLETE = 0 AND FW.CURRENT_STATUS_ID != 4
AND CS.RECEIPT_DATE BETWEEN IN_DATE_FROM AND IN_DATE_TO
AND CS.CASH_SALE_TYPE_ID = 3

UNION ALL

SELECT 'CASH SALES - CONSOLIDATED POS' AS SOURCE, CS.CASH_SALE_ID AS ID,
CONCAT('CS-POS ', COALESCE(CONCAT(C.COMPANY_CODE,' ',CS.CS_NUMBER), CS.CS_NUMBER)) AS SEQUENCE_NO,
'' AS REF_NUMBER, RECEIPT_DATE AS DATE FROM CASH_SALE CS
INNER JOIN COMPANY C ON C.COMPANY_ID = CS.COMPANY_ID
INNER JOIN FORM_WORKFLOW FW ON FW.FORM_WORKFLOW_ID = CS.FORM_WORKFLOW_ID
WHERE FW.IS_COMPLETE = 0 AND FW.CURRENT_STATUS_ID != 4
AND CS.RECEIPT_DATE BETWEEN IN_DATE_FROM AND IN_DATE_TO
AND CS.CASH_SALE_TYPE_ID = 4

UNION ALL

SELECT 'CASH SALES RETURN' AS SOURCE, CSR.CASH_SALE_RETURN_ID AS ID,
CONCAT('CSR ', COALESCE(CONCAT(C.COMPANY_CODE,' ',CSR.CSR_NUMBER), CSR.CSR_NUMBER)) AS SEQUENCE_NO,
(CASE WHEN CSR.SALE_INVOICE_NO != '' THEN
CONCAT('SI No. ', CSR.SALE_INVOICE_NO) ELSE '' END) AS REF_NUMBER,
DATE FROM CASH_SALE_RETURN CSR
INNER JOIN COMPANY C ON C.COMPANY_ID = CSR.COMPANY_ID
INNER JOIN FORM_WORKFLOW FW ON FW.FORM_WORKFLOW_ID = CSR.FORM_WORKFLOW_ID
WHERE FW.IS_COMPLETE = 0 AND FW.CURRENT_STATUS_ID != 4
AND CSR.DATE BETWEEN IN_DATE_FROM AND IN_DATE_TO
AND CSR.CASH_SALE_TYPE_ID = 1

UNION ALL

SELECT 'CASH SALES RETURN - WHOLESALE' AS SOURCE, CSR.CASH_SALE_RETURN_ID AS ID,
CONCAT('CSR-W ', COALESCE(CONCAT(C.COMPANY_CODE,' ',CSR.CSR_NUMBER), CSR.CSR_NUMBER)) AS SEQUENCE_NO,
(CASE WHEN CSR.SALE_INVOICE_NO != '' THEN
CONCAT('SI No. ', CSR.SALE_INVOICE_NO) ELSE '' END) AS REF_NUMBER,
DATE FROM CASH_SALE_RETURN CSR
INNER JOIN COMPANY C ON C.COMPANY_ID = CSR.COMPANY_ID
INNER JOIN FORM_WORKFLOW FW ON FW.FORM_WORKFLOW_ID = CSR.FORM_WORKFLOW_ID
WHERE FW.IS_COMPLETE = 0 AND FW.CURRENT_STATUS_ID != 4
AND CSR.DATE BETWEEN IN_DATE_FROM AND IN_DATE_TO
AND CSR.CASH_SALE_TYPE_ID = 2

UNION ALL

SELECT 'CASH SALES RETURN - IS' AS SOURCE, CSR.CASH_SALE_RETURN_ID AS ID,
CONCAT('CSR-IS ', COALESCE(CONCAT(C.COMPANY_CODE,' ',CSR.CSR_NUMBER), CSR.CSR_NUMBER)) AS SEQUENCE_NO,
(CASE WHEN CSR.SALE_INVOICE_NO != '' THEN
CONCAT('SI No. ', CSR.SALE_INVOICE_NO) ELSE '' END) AS REF_NUMBER,
DATE FROM CASH_SALE_RETURN CSR
INNER JOIN COMPANY C ON C.COMPANY_ID = CSR.COMPANY_ID
INNER JOIN FORM_WORKFLOW FW ON FW.FORM_WORKFLOW_ID = CSR.FORM_WORKFLOW_ID
WHERE FW.IS_COMPLETE = 0 AND FW.CURRENT_STATUS_ID != 4
AND CSR.DATE BETWEEN IN_DATE_FROM AND IN_DATE_TO
AND CSR.CASH_SALE_TYPE_ID = 3

UNION ALL

SELECT 'CUSTOMER ADVANCE PAYMENT' AS SOURCE, CAP.CUSTOMER_ADVANCE_PAYMENT_ID AS ID,
CONCAT('CAP ', CAP.CAP_NUMBER) AS SEQUENCE_NO,
(CASE WHEN CAP.SALE_INVOICE_NO != '' THEN
CONCAT('SI No. ', CAP.SALE_INVOICE_NO) ELSE '' END) AS REF_NUMBER,
RECEIPT_DATE AS DATE FROM CUSTOMER_ADVANCE_PAYMENT CAP
INNER JOIN COMPANY C ON C.COMPANY_ID = CAP.COMPANY_ID
INNER JOIN FORM_WORKFLOW FW ON FW.FORM_WORKFLOW_ID = CAP.FORM_WORKFLOW_ID
WHERE FW.IS_COMPLETE = 0 AND FW.CURRENT_STATUS_ID != 4
AND CAP.RECEIPT_DATE BETWEEN IN_DATE_FROM AND IN_DATE_TO
AND CAP.CUSTOMER_ADVANCE_PAYMENT_TYPE_ID = 1

UNION ALL

SELECT 'CUSTOMER ADVANCE PAYMENT - CENTRAL' AS SOURCE, CAP.CUSTOMER_ADVANCE_PAYMENT_ID AS ID,
CONCAT('CAP CENTRAL ', CAP.CAP_NUMBER) AS SEQUENCE_NO,
(CASE WHEN CAP.SALE_INVOICE_NO != '' THEN
CONCAT('SI No. ', CAP.SALE_INVOICE_NO) ELSE '' END) AS REF_NUMBER,
RECEIPT_DATE AS DATE FROM CUSTOMER_ADVANCE_PAYMENT CAP
INNER JOIN COMPANY C ON C.COMPANY_ID = CAP.COMPANY_ID
INNER JOIN FORM_WORKFLOW FW ON FW.FORM_WORKFLOW_ID = CAP.FORM_WORKFLOW_ID
WHERE FW.IS_COMPLETE = 0 AND FW.CURRENT_STATUS_ID != 4
AND CAP.RECEIPT_DATE BETWEEN IN_DATE_FROM AND IN_DATE_TO
AND CAP.CUSTOMER_ADVANCE_PAYMENT_TYPE_ID = 6

UNION ALL

SELECT 'CUSTOMER ADVANCE PAYMENT - NSB 3' AS SOURCE, CAP.CUSTOMER_ADVANCE_PAYMENT_ID AS ID,
CONCAT('CAP NSB 3 ', CAP.CAP_NUMBER) AS SEQUENCE_NO,
(CASE WHEN CAP.SALE_INVOICE_NO != '' THEN
CONCAT('SI No. ', CAP.SALE_INVOICE_NO) ELSE '' END) AS REF_NUMBER,
RECEIPT_DATE AS DATE FROM CUSTOMER_ADVANCE_PAYMENT CAP
INNER JOIN COMPANY C ON C.COMPANY_ID = CAP.COMPANY_ID
INNER JOIN FORM_WORKFLOW FW ON FW.FORM_WORKFLOW_ID = CAP.FORM_WORKFLOW_ID
WHERE FW.IS_COMPLETE = 0 AND FW.CURRENT_STATUS_ID != 4
AND CAP.RECEIPT_DATE BETWEEN IN_DATE_FROM AND IN_DATE_TO
AND CAP.CUSTOMER_ADVANCE_PAYMENT_TYPE_ID = 7

UNION ALL

SELECT 'CUSTOMER ADVANCE PAYMENT - NSB 4' AS SOURCE, CAP.CUSTOMER_ADVANCE_PAYMENT_ID AS ID,
CONCAT('CAP NSB 4 ', CAP.CAP_NUMBER) AS SEQUENCE_NO,
(CASE WHEN CAP.SALE_INVOICE_NO != '' THEN
CONCAT('SI No. ', CAP.SALE_INVOICE_NO) ELSE '' END) AS REF_NUMBER,
RECEIPT_DATE AS DATE FROM CUSTOMER_ADVANCE_PAYMENT CAP
INNER JOIN COMPANY C ON C.COMPANY_ID = CAP.COMPANY_ID
INNER JOIN FORM_WORKFLOW FW ON FW.FORM_WORKFLOW_ID = CAP.FORM_WORKFLOW_ID
WHERE FW.IS_COMPLETE = 0 AND FW.CURRENT_STATUS_ID != 4
AND CAP.RECEIPT_DATE BETWEEN IN_DATE_FROM AND IN_DATE_TO
AND CAP.CUSTOMER_ADVANCE_PAYMENT_TYPE_ID = 8

UNION ALL

SELECT 'CUSTOMER ADVANCE PAYMENT - NSB 5' AS SOURCE, CAP.CUSTOMER_ADVANCE_PAYMENT_ID AS ID,
CONCAT('CAP NSB 5 ', CAP.CAP_NUMBER) AS SEQUENCE_NO,
(CASE WHEN CAP.SALE_INVOICE_NO != '' THEN
CONCAT('SI No. ', CAP.SALE_INVOICE_NO) ELSE '' END) AS REF_NUMBER,
RECEIPT_DATE AS DATE FROM CUSTOMER_ADVANCE_PAYMENT CAP
INNER JOIN COMPANY C ON C.COMPANY_ID = CAP.COMPANY_ID
INNER JOIN FORM_WORKFLOW FW ON FW.FORM_WORKFLOW_ID = CAP.FORM_WORKFLOW_ID
WHERE FW.IS_COMPLETE = 0 AND FW.CURRENT_STATUS_ID != 4
AND CAP.RECEIPT_DATE BETWEEN IN_DATE_FROM AND IN_DATE_TO
AND CAP.CUSTOMER_ADVANCE_PAYMENT_TYPE_ID = 9

UNION ALL

SELECT 'CUSTOMER ADVANCE PAYMENT - NSB 8' AS SOURCE, CAP.CUSTOMER_ADVANCE_PAYMENT_ID AS ID,
CONCAT('CAP NSB 8 ', CAP.CAP_NUMBER) AS SEQUENCE_NO,
(CASE WHEN CAP.SALE_INVOICE_NO != '' THEN
CONCAT('SI No. ', CAP.SALE_INVOICE_NO) ELSE '' END) AS REF_NUMBER,
RECEIPT_DATE AS DATE FROM CUSTOMER_ADVANCE_PAYMENT CAP
INNER JOIN COMPANY C ON C.COMPANY_ID = CAP.COMPANY_ID
INNER JOIN FORM_WORKFLOW FW ON FW.FORM_WORKFLOW_ID = CAP.FORM_WORKFLOW_ID
WHERE FW.IS_COMPLETE = 0 AND FW.CURRENT_STATUS_ID != 4
AND CAP.RECEIPT_DATE BETWEEN IN_DATE_FROM AND IN_DATE_TO
AND CAP.CUSTOMER_ADVANCE_PAYMENT_TYPE_ID = 10

UNION ALL

SELECT 'CUSTOMER ADVANCE PAYMENT - NSB 8A' AS SOURCE, CAP.CUSTOMER_ADVANCE_PAYMENT_ID AS ID,
CONCAT('CAP NSB 8A ', CAP.CAP_NUMBER) AS SEQUENCE_NO,
(CASE WHEN CAP.SALE_INVOICE_NO != '' THEN
CONCAT('SI No. ', CAP.SALE_INVOICE_NO) ELSE '' END) AS REF_NUMBER,
RECEIPT_DATE AS DATE FROM CUSTOMER_ADVANCE_PAYMENT CAP
INNER JOIN COMPANY C ON C.COMPANY_ID = CAP.COMPANY_ID
INNER JOIN FORM_WORKFLOW FW ON FW.FORM_WORKFLOW_ID = CAP.FORM_WORKFLOW_ID
WHERE FW.IS_COMPLETE = 0 AND FW.CURRENT_STATUS_ID != 4
AND CAP.RECEIPT_DATE BETWEEN IN_DATE_FROM AND IN_DATE_TO
AND CAP.CUSTOMER_ADVANCE_PAYMENT_TYPE_ID = 11

UNION ALL

SELECT 'CUSTOMER ADVANCE PAYMENT-IS' AS SOURCE, CAP.CUSTOMER_ADVANCE_PAYMENT_ID AS ID,
CONCAT('CAP-IS ', CAP.CAP_NUMBER) AS SEQUENCE_NO,
(CASE WHEN CAP.SALE_INVOICE_NO != '' THEN
CONCAT('SI No. ', CAP.SALE_INVOICE_NO) ELSE '' END) AS REF_NUMBER,
RECEIPT_DATE AS DATE FROM CUSTOMER_ADVANCE_PAYMENT CAP
INNER JOIN COMPANY C ON C.COMPANY_ID = CAP.COMPANY_ID
INNER JOIN FORM_WORKFLOW FW ON FW.FORM_WORKFLOW_ID = CAP.FORM_WORKFLOW_ID
WHERE FW.IS_COMPLETE = 0 AND FW.CURRENT_STATUS_ID != 4
AND CAP.RECEIPT_DATE BETWEEN IN_DATE_FROM AND IN_DATE_TO
AND CAP.CUSTOMER_ADVANCE_PAYMENT_TYPE_ID = 3

UNION ALL

SELECT 'GENERAL LEDGER - CENTRAL' AS SOURCE, GL.GENERAL_LEDGER_ID AS ID,
CONCAT('JV CENTRAL ', GL.SEQUENCE_NO) AS SEQUENCE_NO,
'' AS REF_NUMBER, GL.GL_DATE AS DATE FROM GENERAL_LEDGER GL
INNER JOIN GL_ENTRY GLE ON GLE.GENERAL_LEDGER_ID = GL.GENERAL_LEDGER_ID
INNER JOIN ACCOUNT_COMBINATION AC ON AC.ACCOUNT_COMBINATION_ID = GLE.ACCOUNT_COMBINATION_ID
INNER JOIN COMPANY C ON C.COMPANY_ID = AC.COMPANY_ID
INNER JOIN FORM_WORKFLOW FW ON FW.FORM_WORKFLOW_ID = GL.FORM_WORKFLOW_ID
WHERE FW.IS_COMPLETE = 0 AND FW.CURRENT_STATUS_ID != 4
AND GL.GL_DATE BETWEEN IN_DATE_FROM AND IN_DATE_TO
AND GL.DIVISION_ID = 1
GROUP BY GL.GENERAL_LEDGER_ID

UNION ALL

SELECT 'GENERAL LEDGER - NSB 3' AS SOURCE, GL.GENERAL_LEDGER_ID AS ID,
CONCAT('JV NSB 3 ', GL.SEQUENCE_NO) AS SEQUENCE_NO,
'' AS REF_NUMBER, GL.GL_DATE AS DATE FROM GENERAL_LEDGER GL
INNER JOIN GL_ENTRY GLE ON GLE.GENERAL_LEDGER_ID = GL.GENERAL_LEDGER_ID
INNER JOIN ACCOUNT_COMBINATION AC ON AC.ACCOUNT_COMBINATION_ID = GLE.ACCOUNT_COMBINATION_ID
INNER JOIN COMPANY C ON C.COMPANY_ID = AC.COMPANY_ID
INNER JOIN FORM_WORKFLOW FW ON FW.FORM_WORKFLOW_ID = GL.FORM_WORKFLOW_ID
WHERE FW.IS_COMPLETE = 0 AND FW.CURRENT_STATUS_ID != 4
AND GL.GL_DATE BETWEEN IN_DATE_FROM AND IN_DATE_TO
AND GL.DIVISION_ID = 2
GROUP BY GL.GENERAL_LEDGER_ID

UNION ALL

SELECT 'GENERAL LEDGER - NSB 4' AS SOURCE, GL.GENERAL_LEDGER_ID AS ID,
CONCAT('JV NSB 4 ', GL.SEQUENCE_NO) AS SEQUENCE_NO,
'' AS REF_NUMBER, GL.GL_DATE AS DATE FROM GENERAL_LEDGER GL
INNER JOIN GL_ENTRY GLE ON GLE.GENERAL_LEDGER_ID = GL.GENERAL_LEDGER_ID
INNER JOIN ACCOUNT_COMBINATION AC ON AC.ACCOUNT_COMBINATION_ID = GLE.ACCOUNT_COMBINATION_ID
INNER JOIN COMPANY C ON C.COMPANY_ID = AC.COMPANY_ID
INNER JOIN FORM_WORKFLOW FW ON FW.FORM_WORKFLOW_ID = GL.FORM_WORKFLOW_ID
WHERE FW.IS_COMPLETE = 0 AND FW.CURRENT_STATUS_ID != 4
AND GL.GL_DATE BETWEEN IN_DATE_FROM AND IN_DATE_TO
AND GL.DIVISION_ID = 3
GROUP BY GL.GENERAL_LEDGER_ID

UNION ALL

SELECT 'GENERAL LEDGER - NSB 5' AS SOURCE, GL.GENERAL_LEDGER_ID AS ID,
CONCAT('JV NSB 5 ', GL.SEQUENCE_NO) AS SEQUENCE_NO,
'' AS REF_NUMBER, GL.GL_DATE AS DATE FROM GENERAL_LEDGER GL
INNER JOIN GL_ENTRY GLE ON GLE.GENERAL_LEDGER_ID = GL.GENERAL_LEDGER_ID
INNER JOIN ACCOUNT_COMBINATION AC ON AC.ACCOUNT_COMBINATION_ID = GLE.ACCOUNT_COMBINATION_ID
INNER JOIN COMPANY C ON C.COMPANY_ID = AC.COMPANY_ID
INNER JOIN FORM_WORKFLOW FW ON FW.FORM_WORKFLOW_ID = GL.FORM_WORKFLOW_ID
WHERE FW.IS_COMPLETE = 0 AND FW.CURRENT_STATUS_ID != 4
AND GL.GL_DATE BETWEEN IN_DATE_FROM AND IN_DATE_TO
AND GL.DIVISION_ID = 4
GROUP BY GL.GENERAL_LEDGER_ID

UNION ALL

SELECT 'GENERAL LEDGER - NSB 8' AS SOURCE, GL.GENERAL_LEDGER_ID AS ID,
CONCAT('JV NSB 8', GL.SEQUENCE_NO) AS SEQUENCE_NO,
'' AS REF_NUMBER, GL.GL_DATE AS DATE FROM GENERAL_LEDGER GL
INNER JOIN GL_ENTRY GLE ON GLE.GENERAL_LEDGER_ID = GL.GENERAL_LEDGER_ID
INNER JOIN ACCOUNT_COMBINATION AC ON AC.ACCOUNT_COMBINATION_ID = GLE.ACCOUNT_COMBINATION_ID
INNER JOIN COMPANY C ON C.COMPANY_ID = AC.COMPANY_ID
INNER JOIN FORM_WORKFLOW FW ON FW.FORM_WORKFLOW_ID = GL.FORM_WORKFLOW_ID
WHERE FW.IS_COMPLETE = 0 AND FW.CURRENT_STATUS_ID != 4
AND GL.GL_DATE BETWEEN IN_DATE_FROM AND IN_DATE_TO
AND GL.DIVISION_ID = 5
GROUP BY GL.GENERAL_LEDGER_ID

UNION ALL

SELECT 'GENERAL LEDGER - NSB 8A' AS SOURCE, GL.GENERAL_LEDGER_ID AS ID,
CONCAT('JV NSB 8A', GL.SEQUENCE_NO) AS SEQUENCE_NO,
'' AS REF_NUMBER, GL.GL_DATE AS DATE FROM GENERAL_LEDGER GL
INNER JOIN GL_ENTRY GLE ON GLE.GENERAL_LEDGER_ID = GL.GENERAL_LEDGER_ID
INNER JOIN ACCOUNT_COMBINATION AC ON AC.ACCOUNT_COMBINATION_ID = GLE.ACCOUNT_COMBINATION_ID
INNER JOIN COMPANY C ON C.COMPANY_ID = AC.COMPANY_ID
INNER JOIN FORM_WORKFLOW FW ON FW.FORM_WORKFLOW_ID = GL.FORM_WORKFLOW_ID
WHERE FW.IS_COMPLETE = 0 AND FW.CURRENT_STATUS_ID != 4
AND GL.GL_DATE BETWEEN IN_DATE_FROM AND IN_DATE_TO
AND GL.DIVISION_ID = 6
GROUP BY GL.GENERAL_LEDGER_ID

UNION ALL

SELECT 'OTHER RECEIPT - CENTRAL' AS SOURCE, ARM.AR_MISCELLANEOUS_ID AS ID,
CONCAT('OR CENTRAL ', ARM.SEQUENCE_NO) AS SEQUENCE_NO,
CONCAT('Receipt No. ', ARM.RECEIPT_NUMBER) AS REF_NUMBER, MATURITY_DATE AS DATE
FROM AR_MISCELLANEOUS ARM
INNER JOIN AR_CUSTOMER_ACCOUNT ACA ON ACA.AR_CUSTOMER_ACCOUNT_ID = ARM.AR_CUSTOMER_ACCOUNT_ID
INNER JOIN COMPANY C ON C.COMPANY_ID = ACA.COMPANY_ID
INNER JOIN FORM_WORKFLOW FW ON FW.FORM_WORKFLOW_ID = ARM.FORM_WORKFLOW_ID
WHERE FW.IS_COMPLETE = 0 AND FW.CURRENT_STATUS_ID != 4
AND ARM.MATURITY_DATE BETWEEN IN_DATE_FROM AND IN_DATE_TO
AND ARM.DIVISION_ID = 1

UNION ALL

SELECT 'OTHER RECEIPT - NSB 3' AS SOURCE, ARM.AR_MISCELLANEOUS_ID AS ID,
CONCAT('OR NSB 3 ', ARM.SEQUENCE_NO) AS SEQUENCE_NO,
CONCAT('Receipt No. ', ARM.RECEIPT_NUMBER) AS REF_NUMBER, MATURITY_DATE AS DATE
FROM AR_MISCELLANEOUS ARM
INNER JOIN AR_CUSTOMER_ACCOUNT ACA ON ACA.AR_CUSTOMER_ACCOUNT_ID = ARM.AR_CUSTOMER_ACCOUNT_ID
INNER JOIN COMPANY C ON C.COMPANY_ID = ACA.COMPANY_ID
INNER JOIN FORM_WORKFLOW FW ON FW.FORM_WORKFLOW_ID = ARM.FORM_WORKFLOW_ID
WHERE FW.IS_COMPLETE = 0 AND FW.CURRENT_STATUS_ID != 4
AND ARM.MATURITY_DATE BETWEEN IN_DATE_FROM AND IN_DATE_TO
AND ARM.DIVISION_ID = 2

UNION ALL

SELECT 'OTHER RECEIPT - NSB 4' AS SOURCE, ARM.AR_MISCELLANEOUS_ID AS ID,
CONCAT('OR NSB 4 ', ARM.SEQUENCE_NO) AS SEQUENCE_NO,
CONCAT('Receipt No. ', ARM.RECEIPT_NUMBER) AS REF_NUMBER, MATURITY_DATE AS DATE
FROM AR_MISCELLANEOUS ARM
INNER JOIN AR_CUSTOMER_ACCOUNT ACA ON ACA.AR_CUSTOMER_ACCOUNT_ID = ARM.AR_CUSTOMER_ACCOUNT_ID
INNER JOIN COMPANY C ON C.COMPANY_ID = ACA.COMPANY_ID
INNER JOIN FORM_WORKFLOW FW ON FW.FORM_WORKFLOW_ID = ARM.FORM_WORKFLOW_ID
WHERE FW.IS_COMPLETE = 0 AND FW.CURRENT_STATUS_ID != 4
AND ARM.MATURITY_DATE BETWEEN IN_DATE_FROM AND IN_DATE_TO
AND ARM.DIVISION_ID = 3

UNION ALL

SELECT 'OTHER RECEIPT - NSB 5' AS SOURCE, ARM.AR_MISCELLANEOUS_ID AS ID,
CONCAT('OR NSB 5 ', ARM.SEQUENCE_NO) AS SEQUENCE_NO,
CONCAT('Receipt No. ', ARM.RECEIPT_NUMBER) AS REF_NUMBER, MATURITY_DATE AS DATE
FROM AR_MISCELLANEOUS ARM
INNER JOIN AR_CUSTOMER_ACCOUNT ACA ON ACA.AR_CUSTOMER_ACCOUNT_ID = ARM.AR_CUSTOMER_ACCOUNT_ID
INNER JOIN COMPANY C ON C.COMPANY_ID = ACA.COMPANY_ID
INNER JOIN FORM_WORKFLOW FW ON FW.FORM_WORKFLOW_ID = ARM.FORM_WORKFLOW_ID
WHERE FW.IS_COMPLETE = 0 AND FW.CURRENT_STATUS_ID != 4
AND ARM.MATURITY_DATE BETWEEN IN_DATE_FROM AND IN_DATE_TO
AND ARM.DIVISION_ID = 4

UNION ALL

SELECT 'OTHER RECEIPT - NSB 8' AS SOURCE, ARM.AR_MISCELLANEOUS_ID AS ID,
CONCAT('OR NSB 8 ', ARM.SEQUENCE_NO) AS SEQUENCE_NO,
CONCAT('Receipt No. ', ARM.RECEIPT_NUMBER) AS REF_NUMBER, MATURITY_DATE AS DATE
FROM AR_MISCELLANEOUS ARM
INNER JOIN AR_CUSTOMER_ACCOUNT ACA ON ACA.AR_CUSTOMER_ACCOUNT_ID = ARM.AR_CUSTOMER_ACCOUNT_ID
INNER JOIN COMPANY C ON C.COMPANY_ID = ACA.COMPANY_ID
INNER JOIN FORM_WORKFLOW FW ON FW.FORM_WORKFLOW_ID = ARM.FORM_WORKFLOW_ID
WHERE FW.IS_COMPLETE = 0 AND FW.CURRENT_STATUS_ID != 4
AND ARM.MATURITY_DATE BETWEEN IN_DATE_FROM AND IN_DATE_TO
AND ARM.DIVISION_ID = 5

UNION ALL

SELECT 'OTHER RECEIPT - NSB 8A' AS SOURCE, ARM.AR_MISCELLANEOUS_ID AS ID,
CONCAT('OR NSB 8A ', ARM.SEQUENCE_NO) AS SEQUENCE_NO,
CONCAT('Receipt No. ', ARM.RECEIPT_NUMBER) AS REF_NUMBER, MATURITY_DATE AS DATE
FROM AR_MISCELLANEOUS ARM
INNER JOIN AR_CUSTOMER_ACCOUNT ACA ON ACA.AR_CUSTOMER_ACCOUNT_ID = ARM.AR_CUSTOMER_ACCOUNT_ID
INNER JOIN COMPANY C ON C.COMPANY_ID = ACA.COMPANY_ID
INNER JOIN FORM_WORKFLOW FW ON FW.FORM_WORKFLOW_ID = ARM.FORM_WORKFLOW_ID
WHERE FW.IS_COMPLETE = 0 AND FW.CURRENT_STATUS_ID != 4
AND ARM.MATURITY_DATE BETWEEN IN_DATE_FROM AND IN_DATE_TO
AND ARM.DIVISION_ID = 6

UNION ALL

SELECT 'PAID IN ADVANCE DELIVERY' AS SOURCE, CAPD.CAP_DELIVERY_ID AS ID,
CONCAT('PIAD ', COALESCE(CONCAT(C.COMPANY_CODE,' ',CAPD.CAPD_NUMBER), CAPD.CAPD_NUMBER)) AS SEQUENCE_NO,
(CASE WHEN CAPD.SALES_INVOICE_NO != '' THEN
CONCAT('SI No. ', CAPD.SALES_INVOICE_NO) ELSE '' END) AS REF_NUMBER, DELIVERY_DATE AS DATE
FROM CAP_DELIVERY CAPD
INNER JOIN COMPANY C ON C.COMPANY_ID = CAPD.COMPANY_ID
INNER JOIN FORM_WORKFLOW FW ON FW.FORM_WORKFLOW_ID = CAPD.FORM_WORKFLOW_ID
WHERE FW.IS_COMPLETE = 0 AND FW.CURRENT_STATUS_ID != 4
AND CAPD.DELIVERY_DATE BETWEEN IN_DATE_FROM AND IN_DATE_TO
AND CAPD.CUSTOMER_ADVANCE_PAYMENT_TYPE_ID = 1

UNION ALL

SELECT 'PAID IN ADVANCE DELIVERY - IS' AS SOURCE, CAPD.CAP_DELIVERY_ID AS ID,
CONCAT('PIAD-IS ', COALESCE(CONCAT(C.COMPANY_CODE,' ',CAPD.CAPD_NUMBER), CAPD.CAPD_NUMBER)) AS SEQUENCE_NO,
(CASE WHEN CAPD.SALES_INVOICE_NO != '' THEN
CONCAT('SI No. ', CAPD.SALES_INVOICE_NO) ELSE '' END) AS REF_NUMBER, DELIVERY_DATE AS DATE
FROM CAP_DELIVERY CAPD
INNER JOIN COMPANY C ON C.COMPANY_ID = CAPD.COMPANY_ID
INNER JOIN FORM_WORKFLOW FW ON FW.FORM_WORKFLOW_ID = CAPD.FORM_WORKFLOW_ID
WHERE FW.IS_COMPLETE = 0 AND FW.CURRENT_STATUS_ID != 4
AND CAPD.DELIVERY_DATE BETWEEN IN_DATE_FROM AND IN_DATE_TO
AND CAPD.CUSTOMER_ADVANCE_PAYMENT_TYPE_ID = 3

UNION ALL

SELECT 'PROCESSING REPORT' AS SOURCE, PR.PROCESSING_REPORT_ID AS ID,
CONCAT('PR-MR ', COALESCE(CONCAT(C.COMPANY_CODE,' ',PR.SEQUENCE_NO), PR.SEQUENCE_NO)) AS SEQUENCE_NO,
(CASE WHEN PR.REF_NUMBER != '' THEN
CONCAT('Ref. No. ', PR.REF_NUMBER) ELSE '' END) AS REF_NUMBER, DATE
FROM PROCESSING_REPORT PR
INNER JOIN COMPANY C ON C.COMPANY_ID = PR.COMPANY_ID
INNER JOIN FORM_WORKFLOW FW ON FW.FORM_WORKFLOW_ID = PR.FORM_WORKFLOW_ID
WHERE FW.IS_COMPLETE = 0 AND FW.CURRENT_STATUS_ID != 4
AND PR.DATE BETWEEN IN_DATE_FROM AND IN_DATE_TO
AND PR.PROCESSING_REPORT_TYPE_ID = 1

UNION ALL

SELECT 'PROCESSING REPORT' AS SOURCE, PR.PROCESSING_REPORT_ID AS ID, 
CONCAT('PR-MO ', COALESCE(CONCAT(C.COMPANY_CODE,' ',PR.SEQUENCE_NO), PR.SEQUENCE_NO)) AS SEQUENCE_NO,
(CASE WHEN PR.REF_NUMBER != '' THEN
CONCAT('Ref. No. ', PR.REF_NUMBER) ELSE '' END) AS REF_NUMBER, DATE
FROM PROCESSING_REPORT PR
INNER JOIN COMPANY C ON C.COMPANY_ID = PR.COMPANY_ID
INNER JOIN FORM_WORKFLOW FW ON FW.FORM_WORKFLOW_ID = PR.FORM_WORKFLOW_ID
WHERE FW.IS_COMPLETE = 0 AND FW.CURRENT_STATUS_ID != 4
AND PR.DATE BETWEEN IN_DATE_FROM AND IN_DATE_TO
AND PR.PROCESSING_REPORT_TYPE_ID = 2

UNION ALL

SELECT 'PROCESSING REPORT' AS SOURCE, PR.PROCESSING_REPORT_ID AS ID,
CONCAT('PR-PI ', COALESCE(CONCAT(C.COMPANY_CODE,' ',PR.SEQUENCE_NO), PR.SEQUENCE_NO)) AS SEQUENCE_NO,
(CASE WHEN PR.REF_NUMBER != '' THEN
CONCAT('Ref. No. ', PR.REF_NUMBER) ELSE '' END) AS REF_NUMBER, DATE
FROM PROCESSING_REPORT PR
INNER JOIN COMPANY C ON C.COMPANY_ID = PR.COMPANY_ID
INNER JOIN FORM_WORKFLOW FW ON FW.FORM_WORKFLOW_ID = PR.FORM_WORKFLOW_ID
WHERE FW.IS_COMPLETE = 0 AND FW.CURRENT_STATUS_ID != 4
AND PR.DATE BETWEEN IN_DATE_FROM AND IN_DATE_TO
AND PR.PROCESSING_REPORT_TYPE_ID = 3

UNION ALL

SELECT 'PROCESSING REPORT' AS SOURCE, PR.PROCESSING_REPORT_ID AS ID,
CONCAT('PR-PO ', COALESCE(CONCAT(C.COMPANY_CODE,' ',PR.SEQUENCE_NO), PR.SEQUENCE_NO)) AS SEQUENCE_NO,
(CASE WHEN PR.REF_NUMBER != '' THEN
CONCAT('Ref. No. ', PR.REF_NUMBER) ELSE '' END) AS REF_NUMBER, DATE
FROM PROCESSING_REPORT PR
INNER JOIN COMPANY C ON C.COMPANY_ID = PR.COMPANY_ID
INNER JOIN FORM_WORKFLOW FW ON FW.FORM_WORKFLOW_ID = PR.FORM_WORKFLOW_ID
WHERE FW.IS_COMPLETE = 0 AND FW.CURRENT_STATUS_ID != 4
AND PR.DATE BETWEEN IN_DATE_FROM AND IN_DATE_TO
AND PR.PROCESSING_REPORT_TYPE_ID = 4

UNION ALL

SELECT 'REPACKING - CENTRAL' AS SOURCE, RP.REPACKING_ID AS ID,
CONCAT('RC CENTRAL ', RP.R_NUMBER) AS SEQUENCE_NO,
'' AS REF_NUMBER, R_DATE AS DATE FROM REPACKING RP
INNER JOIN COMPANY C ON C.COMPANY_ID = RP.COMPANY_ID
INNER JOIN FORM_WORKFLOW FW ON FW.FORM_WORKFLOW_ID = RP.FORM_WORKFLOW_ID
WHERE FW.IS_COMPLETE = 0 AND FW.CURRENT_STATUS_ID != 4
AND RP.R_DATE BETWEEN IN_DATE_FROM AND IN_DATE_TO
AND RP.DIVISION_ID = 1

UNION ALL

SELECT 'REPACKING - NSB 3' AS SOURCE, RP.REPACKING_ID AS ID,
CONCAT('RC NSB 3 ', RP.R_NUMBER) AS SEQUENCE_NO,
'' AS REF_NUMBER, R_DATE AS DATE FROM REPACKING RP
INNER JOIN COMPANY C ON C.COMPANY_ID = RP.COMPANY_ID
INNER JOIN FORM_WORKFLOW FW ON FW.FORM_WORKFLOW_ID = RP.FORM_WORKFLOW_ID
WHERE FW.IS_COMPLETE = 0 AND FW.CURRENT_STATUS_ID != 4
AND RP.R_DATE BETWEEN IN_DATE_FROM AND IN_DATE_TO
AND RP.DIVISION_ID = 2

UNION ALL

SELECT 'REPACKING - NSB 4' AS SOURCE, RP.REPACKING_ID AS ID,
CONCAT('RC NSB 4 ', RP.R_NUMBER) AS SEQUENCE_NO,
'' AS REF_NUMBER, R_DATE AS DATE FROM REPACKING RP
INNER JOIN COMPANY C ON C.COMPANY_ID = RP.COMPANY_ID
INNER JOIN FORM_WORKFLOW FW ON FW.FORM_WORKFLOW_ID = RP.FORM_WORKFLOW_ID
WHERE FW.IS_COMPLETE = 0 AND FW.CURRENT_STATUS_ID != 4
AND RP.R_DATE BETWEEN IN_DATE_FROM AND IN_DATE_TO
AND RP.DIVISION_ID = 3

UNION ALL

SELECT 'REPACKING - NSB 5' AS SOURCE, RP.REPACKING_ID AS ID,
CONCAT('RC NSB 5 ', RP.R_NUMBER) AS SEQUENCE_NO,
'' AS REF_NUMBER, R_DATE AS DATE FROM REPACKING RP
INNER JOIN COMPANY C ON C.COMPANY_ID = RP.COMPANY_ID
INNER JOIN FORM_WORKFLOW FW ON FW.FORM_WORKFLOW_ID = RP.FORM_WORKFLOW_ID
WHERE FW.IS_COMPLETE = 0 AND FW.CURRENT_STATUS_ID != 4
AND RP.R_DATE BETWEEN IN_DATE_FROM AND IN_DATE_TO
AND RP.DIVISION_ID = 4

UNION ALL

SELECT 'REPACKING - NSB 8' AS SOURCE, RP.REPACKING_ID AS ID,
CONCAT('RC NSB 8 ', RP.R_NUMBER) AS SEQUENCE_NO,
'' AS REF_NUMBER, R_DATE AS DATE FROM REPACKING RP
INNER JOIN COMPANY C ON C.COMPANY_ID = RP.COMPANY_ID
INNER JOIN FORM_WORKFLOW FW ON FW.FORM_WORKFLOW_ID = RP.FORM_WORKFLOW_ID
WHERE FW.IS_COMPLETE = 0 AND FW.CURRENT_STATUS_ID != 4
AND RP.R_DATE BETWEEN IN_DATE_FROM AND IN_DATE_TO
AND RP.DIVISION_ID = 5

UNION ALL

SELECT 'REPACKING - NSB 8A' AS SOURCE, RP.REPACKING_ID AS ID,
CONCAT('RC NSB 8A ', RP.R_NUMBER) AS SEQUENCE_NO,
'' AS REF_NUMBER, R_DATE AS DATE FROM REPACKING RP
INNER JOIN COMPANY C ON C.COMPANY_ID = RP.COMPANY_ID
INNER JOIN FORM_WORKFLOW FW ON FW.FORM_WORKFLOW_ID = RP.FORM_WORKFLOW_ID
WHERE FW.IS_COMPLETE = 0 AND FW.CURRENT_STATUS_ID != 4
AND RP.R_DATE BETWEEN IN_DATE_FROM AND IN_DATE_TO
AND RP.DIVISION_ID = 6

UNION ALL

SELECT 'STOCK ADJUSTMENT IN - CENTRALA' AS SOURCE, SA.STOCK_ADJUSTMENT_ID AS ID,
CONCAT('SA-IN CENTRALA ', SA.SA_NUMBER) AS SEQUENCE_NO,
'' AS REF_NUMBER, SA_DATE AS DATE FROM STOCK_ADJUSTMENT SA
INNER JOIN COMPANY C ON C.COMPANY_ID = SA.COMPANY_ID
INNER JOIN FORM_WORKFLOW FW ON FW.FORM_WORKFLOW_ID = SA.FORM_WORKFLOW_ID
WHERE FW.IS_COMPLETE = 0 AND FW.CURRENT_STATUS_ID != 4
AND SA.SA_DATE BETWEEN IN_DATE_FROM AND IN_DATE_TO
AND SA.STOCK_ADJUSTMENT_CLASSIFICATION_ID = 5
GROUP BY SA.STOCK_ADJUSTMENT_ID

UNION ALL

SELECT 'STOCK ADJUSTMENT IN - NSB 3' AS SOURCE, SA.STOCK_ADJUSTMENT_ID AS ID,
CONCAT('SA-IN NSB 3 ', SA.SA_NUMBER) AS SEQUENCE_NO,
'' AS REF_NUMBER, SA_DATE AS DATE FROM STOCK_ADJUSTMENT SA
INNER JOIN COMPANY C ON C.COMPANY_ID = SA.COMPANY_ID
INNER JOIN FORM_WORKFLOW FW ON FW.FORM_WORKFLOW_ID = SA.FORM_WORKFLOW_ID
WHERE FW.IS_COMPLETE = 0 AND FW.CURRENT_STATUS_ID != 4
AND SA.SA_DATE BETWEEN IN_DATE_FROM AND IN_DATE_TO
AND SA.STOCK_ADJUSTMENT_CLASSIFICATION_ID = 6
GROUP BY SA.STOCK_ADJUSTMENT_ID

UNION ALL

SELECT 'STOCK ADJUSTMENT IN - NSB 4' AS SOURCE, SA.STOCK_ADJUSTMENT_ID AS ID,
CONCAT('SA-IN NSB 4 ', SA.SA_NUMBER) AS SEQUENCE_NO,
'' AS REF_NUMBER, SA_DATE AS DATE FROM STOCK_ADJUSTMENT SA
INNER JOIN COMPANY C ON C.COMPANY_ID = SA.COMPANY_ID
INNER JOIN FORM_WORKFLOW FW ON FW.FORM_WORKFLOW_ID = SA.FORM_WORKFLOW_ID
WHERE FW.IS_COMPLETE = 0 AND FW.CURRENT_STATUS_ID != 4
AND SA.SA_DATE BETWEEN IN_DATE_FROM AND IN_DATE_TO
AND SA.STOCK_ADJUSTMENT_CLASSIFICATION_ID = 7
GROUP BY SA.STOCK_ADJUSTMENT_ID

UNION ALL

SELECT 'STOCK ADJUSTMENT IN - NSB 5' AS SOURCE, SA.STOCK_ADJUSTMENT_ID AS ID,
CONCAT('SA-IN NSB 5 ', SA.SA_NUMBER) AS SEQUENCE_NO,
'' AS REF_NUMBER, SA_DATE AS DATE FROM STOCK_ADJUSTMENT SA
INNER JOIN COMPANY C ON C.COMPANY_ID = SA.COMPANY_ID
INNER JOIN FORM_WORKFLOW FW ON FW.FORM_WORKFLOW_ID = SA.FORM_WORKFLOW_ID
WHERE FW.IS_COMPLETE = 0 AND FW.CURRENT_STATUS_ID != 4
AND SA.SA_DATE BETWEEN IN_DATE_FROM AND IN_DATE_TO
AND SA.STOCK_ADJUSTMENT_CLASSIFICATION_ID = 8
GROUP BY SA.STOCK_ADJUSTMENT_ID

UNION ALL

SELECT 'STOCK ADJUSTMENT IN - NSB 8' AS SOURCE, SA.STOCK_ADJUSTMENT_ID AS ID,
CONCAT('SA-IN NSB 8 ', SA.SA_NUMBER) AS SEQUENCE_NO,
'' AS REF_NUMBER, SA_DATE AS DATE FROM STOCK_ADJUSTMENT SA
INNER JOIN COMPANY C ON C.COMPANY_ID = SA.COMPANY_ID
INNER JOIN FORM_WORKFLOW FW ON FW.FORM_WORKFLOW_ID = SA.FORM_WORKFLOW_ID
WHERE FW.IS_COMPLETE = 0 AND FW.CURRENT_STATUS_ID != 4
AND SA.SA_DATE BETWEEN IN_DATE_FROM AND IN_DATE_TO
AND SA.STOCK_ADJUSTMENT_CLASSIFICATION_ID = 9
GROUP BY SA.STOCK_ADJUSTMENT_ID

UNION ALL

SELECT 'STOCK ADJUSTMENT IN - NSB 8A' AS SOURCE, SA.STOCK_ADJUSTMENT_ID AS ID,
CONCAT('SA-IN NSB 8A ', SA.SA_NUMBER) AS SEQUENCE_NO,
'' AS REF_NUMBER, SA_DATE AS DATE FROM STOCK_ADJUSTMENT SA
INNER JOIN COMPANY C ON C.COMPANY_ID = SA.COMPANY_ID
INNER JOIN FORM_WORKFLOW FW ON FW.FORM_WORKFLOW_ID = SA.FORM_WORKFLOW_ID
WHERE FW.IS_COMPLETE = 0 AND FW.CURRENT_STATUS_ID != 4
AND SA.SA_DATE BETWEEN IN_DATE_FROM AND IN_DATE_TO
AND SA.STOCK_ADJUSTMENT_CLASSIFICATION_ID = 10
GROUP BY SA.STOCK_ADJUSTMENT_ID

UNION ALL

SELECT 'STOCK ADJUSTMENT OUT' AS SOURCE, SA.STOCK_ADJUSTMENT_ID AS ID, 
CONCAT('SA-OUT ', SA.SA_NUMBER) AS SEQUENCE_NO,
'' AS REF_NUMBER, SA_DATE AS DATE FROM STOCK_ADJUSTMENT SA
INNER JOIN COMPANY C ON C.COMPANY_ID = SA.COMPANY_ID
INNER JOIN FORM_WORKFLOW FW ON FW.FORM_WORKFLOW_ID = SA.FORM_WORKFLOW_ID
WHERE FW.IS_COMPLETE = 0 AND FW.CURRENT_STATUS_ID != 4
AND SA.SA_DATE BETWEEN IN_DATE_FROM AND IN_DATE_TO
AND SA.STOCK_ADJUSTMENT_CLASSIFICATION_ID = 2
GROUP BY SA.STOCK_ADJUSTMENT_ID

UNION ALL

SELECT 'STOCK ADJUSTMENT OUT - CENTRAL' AS SOURCE, SA.STOCK_ADJUSTMENT_ID AS ID, 
CONCAT('SA-OUT CENTRAL ', SA.SA_NUMBER) AS SEQUENCE_NO,
'' AS REF_NUMBER, SA_DATE AS DATE FROM STOCK_ADJUSTMENT SA
INNER JOIN COMPANY C ON C.COMPANY_ID = SA.COMPANY_ID
INNER JOIN FORM_WORKFLOW FW ON FW.FORM_WORKFLOW_ID = SA.FORM_WORKFLOW_ID
WHERE FW.IS_COMPLETE = 0 AND FW.CURRENT_STATUS_ID != 4
AND SA.SA_DATE BETWEEN IN_DATE_FROM AND IN_DATE_TO
AND SA.STOCK_ADJUSTMENT_CLASSIFICATION_ID = 11
GROUP BY SA.STOCK_ADJUSTMENT_ID

UNION ALL

SELECT 'STOCK ADJUSTMENT OUT - NSB 3' AS SOURCE, SA.STOCK_ADJUSTMENT_ID AS ID, 
CONCAT('SA-OUT NSB 3 ', SA.SA_NUMBER) AS SEQUENCE_NO,
'' AS REF_NUMBER, SA_DATE AS DATE FROM STOCK_ADJUSTMENT SA
INNER JOIN COMPANY C ON C.COMPANY_ID = SA.COMPANY_ID
INNER JOIN FORM_WORKFLOW FW ON FW.FORM_WORKFLOW_ID = SA.FORM_WORKFLOW_ID
WHERE FW.IS_COMPLETE = 0 AND FW.CURRENT_STATUS_ID != 4
AND SA.SA_DATE BETWEEN IN_DATE_FROM AND IN_DATE_TO
AND SA.STOCK_ADJUSTMENT_CLASSIFICATION_ID = 12
GROUP BY SA.STOCK_ADJUSTMENT_ID

UNION ALL

SELECT 'STOCK ADJUSTMENT OUT - NSB 4' AS SOURCE, SA.STOCK_ADJUSTMENT_ID AS ID, 
CONCAT('SA-OUT NSB 4 ', SA.SA_NUMBER) AS SEQUENCE_NO,
'' AS REF_NUMBER, SA_DATE AS DATE FROM STOCK_ADJUSTMENT SA
INNER JOIN COMPANY C ON C.COMPANY_ID = SA.COMPANY_ID
INNER JOIN FORM_WORKFLOW FW ON FW.FORM_WORKFLOW_ID = SA.FORM_WORKFLOW_ID
WHERE FW.IS_COMPLETE = 0 AND FW.CURRENT_STATUS_ID != 4
AND SA.SA_DATE BETWEEN IN_DATE_FROM AND IN_DATE_TO
AND SA.STOCK_ADJUSTMENT_CLASSIFICATION_ID = 13
GROUP BY SA.STOCK_ADJUSTMENT_ID

UNION ALL

SELECT 'STOCK ADJUSTMENT OUT - NSB 5' AS SOURCE, SA.STOCK_ADJUSTMENT_ID AS ID, 
CONCAT('SA-OUT NSB 5 ', SA.SA_NUMBER) AS SEQUENCE_NO,
'' AS REF_NUMBER, SA_DATE AS DATE FROM STOCK_ADJUSTMENT SA
INNER JOIN COMPANY C ON C.COMPANY_ID = SA.COMPANY_ID
INNER JOIN FORM_WORKFLOW FW ON FW.FORM_WORKFLOW_ID = SA.FORM_WORKFLOW_ID
WHERE FW.IS_COMPLETE = 0 AND FW.CURRENT_STATUS_ID != 4
AND SA.SA_DATE BETWEEN IN_DATE_FROM AND IN_DATE_TO
AND SA.STOCK_ADJUSTMENT_CLASSIFICATION_ID = 14
GROUP BY SA.STOCK_ADJUSTMENT_ID

UNION ALL

SELECT 'STOCK ADJUSTMENT OUT - NSB 8' AS SOURCE, SA.STOCK_ADJUSTMENT_ID AS ID, 
CONCAT('SA-OUT NSB 8 ', SA.SA_NUMBER) AS SEQUENCE_NO,
'' AS REF_NUMBER, SA_DATE AS DATE FROM STOCK_ADJUSTMENT SA
INNER JOIN COMPANY C ON C.COMPANY_ID = SA.COMPANY_ID
INNER JOIN FORM_WORKFLOW FW ON FW.FORM_WORKFLOW_ID = SA.FORM_WORKFLOW_ID
WHERE FW.IS_COMPLETE = 0 AND FW.CURRENT_STATUS_ID != 4
AND SA.SA_DATE BETWEEN IN_DATE_FROM AND IN_DATE_TO
AND SA.STOCK_ADJUSTMENT_CLASSIFICATION_ID = 15
GROUP BY SA.STOCK_ADJUSTMENT_ID

UNION ALL

SELECT 'STOCK ADJUSTMENT OUT - NSB 8A' AS SOURCE, SA.STOCK_ADJUSTMENT_ID AS ID, 
CONCAT('SA-OUT NSB 8A ', SA.SA_NUMBER) AS SEQUENCE_NO,
'' AS REF_NUMBER, SA_DATE AS DATE FROM STOCK_ADJUSTMENT SA
INNER JOIN COMPANY C ON C.COMPANY_ID = SA.COMPANY_ID
INNER JOIN FORM_WORKFLOW FW ON FW.FORM_WORKFLOW_ID = SA.FORM_WORKFLOW_ID
WHERE FW.IS_COMPLETE = 0 AND FW.CURRENT_STATUS_ID != 4
AND SA.SA_DATE BETWEEN IN_DATE_FROM AND IN_DATE_TO
AND SA.STOCK_ADJUSTMENT_CLASSIFICATION_ID = 16
GROUP BY SA.STOCK_ADJUSTMENT_ID

UNION ALL

SELECT 'TRANSFER RECEIPT' AS SOURCE, TR.R_TRANSFER_RECEIPT_ID AS ID,
CONCAT('TR ', COALESCE(CONCAT(C.COMPANY_CODE,' ',TR.TR_NUMBER), TR.TR_NUMBER)) AS SEQUENCE_NO,
(CASE WHEN TR.DR_NUMBER != '' THEN
CONCAT('DR No. ', TR.DR_NUMBER) ELSE '' END) AS REF_NUMBER, TR_DATE AS DATE
FROM R_TRANSFER_RECEIPT TR
INNER JOIN COMPANY C ON C.COMPANY_ID = TR.COMPANY_ID
INNER JOIN FORM_WORKFLOW FW ON FW.FORM_WORKFLOW_ID = TR.FORM_WORKFLOW_ID
WHERE FW.IS_COMPLETE = 0 AND FW.CURRENT_STATUS_ID != 4
AND TR.TR_DATE BETWEEN IN_DATE_FROM AND IN_DATE_TO
AND TR.TRANSFER_RECEIPT_TYPE_ID = 1

UNION ALL

SELECT 'TRANSFER RECEIPT - IS' AS SOURCE, TR.R_TRANSFER_RECEIPT_ID AS ID, 
CONCAT('TR-IS ', COALESCE(CONCAT(C.COMPANY_CODE,' ',TR.TR_NUMBER), TR.TR_NUMBER)) AS SEQUENCE_NO,
(CASE WHEN TR.DR_NUMBER != '' THEN
CONCAT('DR No. ', TR.DR_NUMBER) ELSE '' END) AS REF_NUMBER, TR_DATE AS DATE
FROM R_TRANSFER_RECEIPT TR
INNER JOIN COMPANY C ON C.COMPANY_ID = TR.COMPANY_ID
INNER JOIN FORM_WORKFLOW FW ON FW.FORM_WORKFLOW_ID = TR.FORM_WORKFLOW_ID
WHERE FW.IS_COMPLETE = 0 AND FW.CURRENT_STATUS_ID != 4
AND TR.TR_DATE BETWEEN IN_DATE_FROM AND IN_DATE_TO
AND TR.TRANSFER_RECEIPT_TYPE_ID = 2

UNION ALL

SELECT 'AP INVOICE - NON PO - CENTRAL' AS SOURCE, API.AP_INVOICE_ID AS ID,
CONCAT('API NPO CENTRAL ', API.SEQUENCE_NO) AS SEQUENCE_NO,
CONCAT('Invoice No. ', API.INVOICE_NUMBER) AS REF_NUMBER,
API.GL_DATE AS DATE FROM AP_INVOICE API
INNER JOIN COMPANY C ON C.COMPANY_ID = API.COMPANY_ID
INNER JOIN FORM_WORKFLOW FW ON FW.FORM_WORKFLOW_ID = API.FORM_WORKFLOW_ID
WHERE FW.IS_COMPLETE = 0 AND FW.CURRENT_STATUS_ID != 4
AND API.GL_DATE BETWEEN IN_DATE_FROM AND IN_DATE_TO
AND API.INVOICE_TYPE_ID = 19

UNION ALL
SELECT 'AP INVOICE - NON PO - NSB 3' AS SOURCE, API.AP_INVOICE_ID AS ID,
CONCAT('API NPO NSB 3 ', API.SEQUENCE_NO) AS SEQUENCE_NO,
CONCAT('Invoice No. ', API.INVOICE_NUMBER) AS REF_NUMBER,
API.GL_DATE AS DATE FROM AP_INVOICE API
INNER JOIN COMPANY C ON C.COMPANY_ID = API.COMPANY_ID
INNER JOIN FORM_WORKFLOW FW ON FW.FORM_WORKFLOW_ID = API.FORM_WORKFLOW_ID
WHERE FW.IS_COMPLETE = 0 AND FW.CURRENT_STATUS_ID != 4
AND API.GL_DATE BETWEEN IN_DATE_FROM AND IN_DATE_TO
AND API.INVOICE_TYPE_ID = 20

UNION ALL
SELECT 'AP INVOICE - NON PO - NSB 4' AS SOURCE, API.AP_INVOICE_ID AS ID,
CONCAT('API NPO NSB 4 ', API.SEQUENCE_NO) AS SEQUENCE_NO,
CONCAT('Invoice No. ', API.INVOICE_NUMBER) AS REF_NUMBER,
API.GL_DATE AS DATE FROM AP_INVOICE API
INNER JOIN COMPANY C ON C.COMPANY_ID = API.COMPANY_ID
INNER JOIN FORM_WORKFLOW FW ON FW.FORM_WORKFLOW_ID = API.FORM_WORKFLOW_ID
WHERE FW.IS_COMPLETE = 0 AND FW.CURRENT_STATUS_ID != 4
AND API.GL_DATE BETWEEN IN_DATE_FROM AND IN_DATE_TO
AND API.INVOICE_TYPE_ID = 21

UNION ALL
SELECT 'AP INVOICE - NON PO - NSB 5' AS SOURCE, API.AP_INVOICE_ID AS ID,
CONCAT('API NPO NSB 5 ', API.SEQUENCE_NO) AS SEQUENCE_NO,
CONCAT('Invoice No. ', API.INVOICE_NUMBER) AS REF_NUMBER,
API.GL_DATE AS DATE FROM AP_INVOICE API
INNER JOIN COMPANY C ON C.COMPANY_ID = API.COMPANY_ID
INNER JOIN FORM_WORKFLOW FW ON FW.FORM_WORKFLOW_ID = API.FORM_WORKFLOW_ID
WHERE FW.IS_COMPLETE = 0 AND FW.CURRENT_STATUS_ID != 4
AND API.GL_DATE BETWEEN IN_DATE_FROM AND IN_DATE_TO
AND API.INVOICE_TYPE_ID = 22

UNION ALL
SELECT 'AP INVOICE - NON PO - NSB 8' AS SOURCE, API.AP_INVOICE_ID AS ID,
CONCAT('API NPO NSB 8 ', API.SEQUENCE_NO) AS SEQUENCE_NO,
CONCAT('Invoice No. ', API.INVOICE_NUMBER) AS REF_NUMBER,
API.GL_DATE AS DATE FROM AP_INVOICE API
INNER JOIN COMPANY C ON C.COMPANY_ID = API.COMPANY_ID
INNER JOIN FORM_WORKFLOW FW ON FW.FORM_WORKFLOW_ID = API.FORM_WORKFLOW_ID
WHERE FW.IS_COMPLETE = 0 AND FW.CURRENT_STATUS_ID != 4
AND API.GL_DATE BETWEEN IN_DATE_FROM AND IN_DATE_TO
AND API.INVOICE_TYPE_ID = 23

UNION ALL
SELECT 'AP INVOICE - NON PO - NSB 8A' AS SOURCE, API.AP_INVOICE_ID AS ID,
CONCAT('API NPO NSB 8A ', API.SEQUENCE_NO) AS SEQUENCE_NO,
CONCAT('Invoice No. ', API.INVOICE_NUMBER) AS REF_NUMBER,
API.GL_DATE AS DATE FROM AP_INVOICE API
INNER JOIN COMPANY C ON C.COMPANY_ID = API.COMPANY_ID
INNER JOIN FORM_WORKFLOW FW ON FW.FORM_WORKFLOW_ID = API.FORM_WORKFLOW_ID
WHERE FW.IS_COMPLETE = 0 AND FW.CURRENT_STATUS_ID != 4
AND API.GL_DATE BETWEEN IN_DATE_FROM AND IN_DATE_TO
AND API.INVOICE_TYPE_ID = 24

UNION ALL
SELECT 'AP INVOICE GOODS/SERVICES - CENTRAL' AS SOURCE, API.AP_INVOICE_ID AS ID,
CONCAT('API G/S CENTRAL ', API.SEQUENCE_NO) AS SEQUENCE_NO,
CONCAT('Invoice No. ', API.INVOICE_NUMBER) AS REF_NUMBER,
API.GL_DATE AS DATE FROM AP_INVOICE API
INNER JOIN COMPANY C ON C.COMPANY_ID = API.COMPANY_ID
INNER JOIN FORM_WORKFLOW FW ON FW.FORM_WORKFLOW_ID = API.FORM_WORKFLOW_ID
WHERE FW.IS_COMPLETE = 0 AND FW.CURRENT_STATUS_ID != 4
AND API.GL_DATE BETWEEN IN_DATE_FROM AND IN_DATE_TO
AND API.INVOICE_TYPE_ID = 25

UNION ALL
SELECT 'AP INVOICE GOODS/SERVICES - NSB 3' AS SOURCE, API.AP_INVOICE_ID AS ID,
CONCAT('API G/S NSB 3 ', API.SEQUENCE_NO) AS SEQUENCE_NO,
CONCAT('Invoice No. ', API.INVOICE_NUMBER) AS REF_NUMBER,
API.GL_DATE AS DATE FROM AP_INVOICE API
INNER JOIN COMPANY C ON C.COMPANY_ID = API.COMPANY_ID
INNER JOIN FORM_WORKFLOW FW ON FW.FORM_WORKFLOW_ID = API.FORM_WORKFLOW_ID
WHERE FW.IS_COMPLETE = 0 AND FW.CURRENT_STATUS_ID != 4
AND API.GL_DATE BETWEEN IN_DATE_FROM AND IN_DATE_TO
AND API.INVOICE_TYPE_ID = 26

UNION ALL
SELECT 'AP INVOICE GOODS/SERVICES - NSB 4' AS SOURCE, API.AP_INVOICE_ID AS ID,
CONCAT('API G/S NSB 4 ', API.SEQUENCE_NO) AS SEQUENCE_NO,
CONCAT('Invoice No. ', API.INVOICE_NUMBER) AS REF_NUMBER,
API.GL_DATE AS DATE FROM AP_INVOICE API
INNER JOIN COMPANY C ON C.COMPANY_ID = API.COMPANY_ID
INNER JOIN FORM_WORKFLOW FW ON FW.FORM_WORKFLOW_ID = API.FORM_WORKFLOW_ID
WHERE FW.IS_COMPLETE = 0 AND FW.CURRENT_STATUS_ID != 4
AND API.GL_DATE BETWEEN IN_DATE_FROM AND IN_DATE_TO
AND API.INVOICE_TYPE_ID = 27

UNION ALL
SELECT 'AP INVOICE GOODS/SERVICES - NSB 5' AS SOURCE, API.AP_INVOICE_ID AS ID,
CONCAT('API G/S NSB 5 ', API.SEQUENCE_NO) AS SEQUENCE_NO,
CONCAT('Invoice No. ', API.INVOICE_NUMBER) AS REF_NUMBER,
API.GL_DATE AS DATE FROM AP_INVOICE API
INNER JOIN COMPANY C ON C.COMPANY_ID = API.COMPANY_ID
INNER JOIN FORM_WORKFLOW FW ON FW.FORM_WORKFLOW_ID = API.FORM_WORKFLOW_ID
WHERE FW.IS_COMPLETE = 0 AND FW.CURRENT_STATUS_ID != 4
AND API.GL_DATE BETWEEN IN_DATE_FROM AND IN_DATE_TO
AND API.INVOICE_TYPE_ID = 28

UNION ALL
SELECT 'AP INVOICE GOODS/SERVICES - NSB 8' AS SOURCE, API.AP_INVOICE_ID AS ID,
CONCAT('API G/S NSB 8 ', API.SEQUENCE_NO) AS SEQUENCE_NO,
CONCAT('Invoice No. ', API.INVOICE_NUMBER) AS REF_NUMBER,
API.GL_DATE AS DATE FROM AP_INVOICE API
INNER JOIN COMPANY C ON C.COMPANY_ID = API.COMPANY_ID
INNER JOIN FORM_WORKFLOW FW ON FW.FORM_WORKFLOW_ID = API.FORM_WORKFLOW_ID
WHERE FW.IS_COMPLETE = 0 AND FW.CURRENT_STATUS_ID != 4
AND API.GL_DATE BETWEEN IN_DATE_FROM AND IN_DATE_TO
AND API.INVOICE_TYPE_ID = 29

UNION ALL
SELECT 'AP INVOICE GOODS/SERVICES - NSB 8A' AS SOURCE, API.AP_INVOICE_ID AS ID,
CONCAT('API G/S NSB 8A ', API.SEQUENCE_NO) AS SEQUENCE_NO,
CONCAT('Invoice No. ', API.INVOICE_NUMBER) AS REF_NUMBER,
API.GL_DATE AS DATE FROM AP_INVOICE API
INNER JOIN COMPANY C ON C.COMPANY_ID = API.COMPANY_ID
INNER JOIN FORM_WORKFLOW FW ON FW.FORM_WORKFLOW_ID = API.FORM_WORKFLOW_ID
WHERE FW.IS_COMPLETE = 0 AND FW.CURRENT_STATUS_ID != 4
AND API.GL_DATE BETWEEN IN_DATE_FROM AND IN_DATE_TO
AND API.INVOICE_TYPE_ID = 30

UNION ALL
SELECT 'RETURN TO SUPPLIER - CENTRAL' AS SOURCE, API.AP_INVOICE_ID AS ID,
CONCAT('RTS CENTRAL ', API.SEQUENCE_NO) AS SEQUENCE_NO,
CONCAT('Invoice No. ', API.INVOICE_NUMBER) AS REF_NUMBER,
API.GL_DATE AS DATE FROM AP_INVOICE API
INNER JOIN COMPANY C ON C.COMPANY_ID = API.COMPANY_ID
INNER JOIN FORM_WORKFLOW FW ON FW.FORM_WORKFLOW_ID = API.FORM_WORKFLOW_ID
WHERE FW.IS_COMPLETE = 0 AND FW.CURRENT_STATUS_ID != 4
AND API.GL_DATE BETWEEN IN_DATE_FROM AND IN_DATE_TO
AND API.INVOICE_TYPE_ID = 31

UNION ALL
SELECT 'RETURN TO SUPPLIER - NSB 3' AS SOURCE, API.AP_INVOICE_ID AS ID,
CONCAT('RTS NSB 3 ', API.SEQUENCE_NO) AS SEQUENCE_NO,
CONCAT('Invoice No. ', API.INVOICE_NUMBER) AS REF_NUMBER,
API.GL_DATE AS DATE FROM AP_INVOICE API
INNER JOIN COMPANY C ON C.COMPANY_ID = API.COMPANY_ID
INNER JOIN FORM_WORKFLOW FW ON FW.FORM_WORKFLOW_ID = API.FORM_WORKFLOW_ID
WHERE FW.IS_COMPLETE = 0 AND FW.CURRENT_STATUS_ID != 4
AND API.GL_DATE BETWEEN IN_DATE_FROM AND IN_DATE_TO
AND API.INVOICE_TYPE_ID = 32

UNION ALL
SELECT 'RETURN TO SUPPLIER - NSB 4' AS SOURCE, API.AP_INVOICE_ID AS ID,
CONCAT('RTS NSB 4 ', API.SEQUENCE_NO) AS SEQUENCE_NO,
CONCAT('Invoice No. ', API.INVOICE_NUMBER) AS REF_NUMBER,
API.GL_DATE AS DATE FROM AP_INVOICE API
INNER JOIN COMPANY C ON C.COMPANY_ID = API.COMPANY_ID
INNER JOIN FORM_WORKFLOW FW ON FW.FORM_WORKFLOW_ID = API.FORM_WORKFLOW_ID
WHERE FW.IS_COMPLETE = 0 AND FW.CURRENT_STATUS_ID != 4
AND API.GL_DATE BETWEEN IN_DATE_FROM AND IN_DATE_TO
AND API.INVOICE_TYPE_ID = 33

UNION ALL
SELECT 'RETURN TO SUPPLIER - NSB 5' AS SOURCE, API.AP_INVOICE_ID AS ID,
CONCAT('RTS NSB 5 ', API.SEQUENCE_NO) AS SEQUENCE_NO,
CONCAT('Invoice No. ', API.INVOICE_NUMBER) AS REF_NUMBER,
API.GL_DATE AS DATE FROM AP_INVOICE API
INNER JOIN COMPANY C ON C.COMPANY_ID = API.COMPANY_ID
INNER JOIN FORM_WORKFLOW FW ON FW.FORM_WORKFLOW_ID = API.FORM_WORKFLOW_ID
WHERE FW.IS_COMPLETE = 0 AND FW.CURRENT_STATUS_ID != 4
AND API.GL_DATE BETWEEN IN_DATE_FROM AND IN_DATE_TO
AND API.INVOICE_TYPE_ID = 34

UNION ALL
SELECT 'RETURN TO SUPPLIER - NSB 8' AS SOURCE, API.AP_INVOICE_ID AS ID,
CONCAT('RTS NSB 8 ', API.SEQUENCE_NO) AS SEQUENCE_NO,
CONCAT('Invoice No. ', API.INVOICE_NUMBER) AS REF_NUMBER,
API.GL_DATE AS DATE FROM AP_INVOICE API
INNER JOIN COMPANY C ON C.COMPANY_ID = API.COMPANY_ID
INNER JOIN FORM_WORKFLOW FW ON FW.FORM_WORKFLOW_ID = API.FORM_WORKFLOW_ID
WHERE FW.IS_COMPLETE = 0 AND FW.CURRENT_STATUS_ID != 4
AND API.GL_DATE BETWEEN IN_DATE_FROM AND IN_DATE_TO
AND API.INVOICE_TYPE_ID = 35

UNION ALL
SELECT 'RETURN TO SUPPLIER - NSB 8A' AS SOURCE, API.AP_INVOICE_ID AS ID,
CONCAT('RTS NSB 8A ', API.SEQUENCE_NO) AS SEQUENCE_NO,
CONCAT('Invoice No. ', API.INVOICE_NUMBER) AS REF_NUMBER,
API.GL_DATE AS DATE FROM AP_INVOICE API
INNER JOIN COMPANY C ON C.COMPANY_ID = API.COMPANY_ID
INNER JOIN FORM_WORKFLOW FW ON FW.FORM_WORKFLOW_ID = API.FORM_WORKFLOW_ID
WHERE FW.IS_COMPLETE = 0 AND FW.CURRENT_STATUS_ID != 4
AND API.GL_DATE BETWEEN IN_DATE_FROM AND IN_DATE_TO
AND API.INVOICE_TYPE_ID = 36

UNION ALL
SELECT 'AP INVOICE - CONFIDENTIAL - CENTRAL' AS SOURCE, API.AP_INVOICE_ID AS ID,
CONCAT('APIC CENTRAL ', API.SEQUENCE_NO) AS SEQUENCE_NO,
CONCAT('Invoice No. ', API.INVOICE_NUMBER) AS REF_NUMBER,
API.GL_DATE AS DATE FROM AP_INVOICE API
INNER JOIN COMPANY C ON C.COMPANY_ID = API.COMPANY_ID
INNER JOIN FORM_WORKFLOW FW ON FW.FORM_WORKFLOW_ID = API.FORM_WORKFLOW_ID
WHERE FW.IS_COMPLETE = 0 AND FW.CURRENT_STATUS_ID != 4
AND API.GL_DATE BETWEEN IN_DATE_FROM AND IN_DATE_TO
AND API.INVOICE_TYPE_ID = 37

UNION ALL
SELECT 'AP INVOICE - CONFIDENTIAL - NSB 3' AS SOURCE, API.AP_INVOICE_ID AS ID,
CONCAT('APIC NSB 3 ', API.SEQUENCE_NO) AS SEQUENCE_NO,
CONCAT('Invoice No. ', API.INVOICE_NUMBER) AS REF_NUMBER,
API.GL_DATE AS DATE FROM AP_INVOICE API
INNER JOIN COMPANY C ON C.COMPANY_ID = API.COMPANY_ID
INNER JOIN FORM_WORKFLOW FW ON FW.FORM_WORKFLOW_ID = API.FORM_WORKFLOW_ID
WHERE FW.IS_COMPLETE = 0 AND FW.CURRENT_STATUS_ID != 4
AND API.GL_DATE BETWEEN IN_DATE_FROM AND IN_DATE_TO
AND API.INVOICE_TYPE_ID = 38

UNION ALL
SELECT 'AP INVOICE - CONFIDENTIAL - NSB 4' AS SOURCE, API.AP_INVOICE_ID AS ID,
CONCAT('APIC NSB 4 ', API.SEQUENCE_NO) AS SEQUENCE_NO,
CONCAT('Invoice No. ', API.INVOICE_NUMBER) AS REF_NUMBER,
API.GL_DATE AS DATE FROM AP_INVOICE API
INNER JOIN COMPANY C ON C.COMPANY_ID = API.COMPANY_ID
INNER JOIN FORM_WORKFLOW FW ON FW.FORM_WORKFLOW_ID = API.FORM_WORKFLOW_ID
WHERE FW.IS_COMPLETE = 0 AND FW.CURRENT_STATUS_ID != 4
AND API.GL_DATE BETWEEN IN_DATE_FROM AND IN_DATE_TO
AND API.INVOICE_TYPE_ID = 39

UNION ALL
SELECT 'AP INVOICE - CONFIDENTIAL - NSB 5' AS SOURCE, API.AP_INVOICE_ID AS ID,
CONCAT('APIC NSB 5 ', API.SEQUENCE_NO) AS SEQUENCE_NO,
CONCAT('Invoice No. ', API.INVOICE_NUMBER) AS REF_NUMBER,
API.GL_DATE AS DATE FROM AP_INVOICE API
INNER JOIN COMPANY C ON C.COMPANY_ID = API.COMPANY_ID
INNER JOIN FORM_WORKFLOW FW ON FW.FORM_WORKFLOW_ID = API.FORM_WORKFLOW_ID
WHERE FW.IS_COMPLETE = 0 AND FW.CURRENT_STATUS_ID != 4
AND API.GL_DATE BETWEEN IN_DATE_FROM AND IN_DATE_TO
AND API.INVOICE_TYPE_ID = 40

UNION ALL
SELECT 'AP INVOICE - CONFIDENTIAL - NSB 8' AS SOURCE, API.AP_INVOICE_ID AS ID,
CONCAT('APIC NSB 8 ', API.SEQUENCE_NO) AS SEQUENCE_NO,
CONCAT('Invoice No. ', API.INVOICE_NUMBER) AS REF_NUMBER,
API.GL_DATE AS DATE FROM AP_INVOICE API
INNER JOIN COMPANY C ON C.COMPANY_ID = API.COMPANY_ID
INNER JOIN FORM_WORKFLOW FW ON FW.FORM_WORKFLOW_ID = API.FORM_WORKFLOW_ID
WHERE FW.IS_COMPLETE = 0 AND FW.CURRENT_STATUS_ID != 4
AND API.GL_DATE BETWEEN IN_DATE_FROM AND IN_DATE_TO
AND API.INVOICE_TYPE_ID = 41

UNION ALL
SELECT 'AP INVOICE - CONFIDENTIAL - NSB 8A' AS SOURCE, API.AP_INVOICE_ID AS ID,
CONCAT('APIC NSB 8A ', API.SEQUENCE_NO) AS SEQUENCE_NO,
CONCAT('Invoice No. ', API.INVOICE_NUMBER) AS REF_NUMBER,
API.GL_DATE AS DATE FROM AP_INVOICE API
INNER JOIN COMPANY C ON C.COMPANY_ID = API.COMPANY_ID
INNER JOIN FORM_WORKFLOW FW ON FW.FORM_WORKFLOW_ID = API.FORM_WORKFLOW_ID
WHERE FW.IS_COMPLETE = 0 AND FW.CURRENT_STATUS_ID != 4
AND API.GL_DATE BETWEEN IN_DATE_FROM AND IN_DATE_TO
AND API.INVOICE_TYPE_ID = 42

UNION ALL
SELECT 'AP INVOICE - IMPORTATION - CENTRAL' AS SOURCE, API.AP_INVOICE_ID AS ID,
CONCAT('API I CENTRAL ', API.SEQUENCE_NO) AS SEQUENCE_NO,
CONCAT('Invoice No. ', API.INVOICE_NUMBER) AS REF_NUMBER,
API.GL_DATE AS DATE FROM AP_INVOICE API
INNER JOIN COMPANY C ON C.COMPANY_ID = API.COMPANY_ID
INNER JOIN FORM_WORKFLOW FW ON FW.FORM_WORKFLOW_ID = API.FORM_WORKFLOW_ID
WHERE FW.IS_COMPLETE = 0 AND FW.CURRENT_STATUS_ID != 4
AND API.GL_DATE BETWEEN IN_DATE_FROM AND IN_DATE_TO
AND API.INVOICE_TYPE_ID = 43

UNION ALL
SELECT 'AP INVOICE - IMPORTATION - NSB 3' AS SOURCE, API.AP_INVOICE_ID AS ID,
CONCAT('API I NSB 3 ', API.SEQUENCE_NO) AS SEQUENCE_NO,
CONCAT('Invoice No. ', API.INVOICE_NUMBER) AS REF_NUMBER,
API.GL_DATE AS DATE FROM AP_INVOICE API
INNER JOIN COMPANY C ON C.COMPANY_ID = API.COMPANY_ID
INNER JOIN FORM_WORKFLOW FW ON FW.FORM_WORKFLOW_ID = API.FORM_WORKFLOW_ID
WHERE FW.IS_COMPLETE = 0 AND FW.CURRENT_STATUS_ID != 4
AND API.GL_DATE BETWEEN IN_DATE_FROM AND IN_DATE_TO
AND API.INVOICE_TYPE_ID = 44

UNION ALL
SELECT 'AP INVOICE - IMPORTATION - NSB 4' AS SOURCE, API.AP_INVOICE_ID AS ID,
CONCAT('API I NSB 4 ', API.SEQUENCE_NO) AS SEQUENCE_NO,
CONCAT('Invoice No. ', API.INVOICE_NUMBER) AS REF_NUMBER,
API.GL_DATE AS DATE FROM AP_INVOICE API
INNER JOIN COMPANY C ON C.COMPANY_ID = API.COMPANY_ID
INNER JOIN FORM_WORKFLOW FW ON FW.FORM_WORKFLOW_ID = API.FORM_WORKFLOW_ID
WHERE FW.IS_COMPLETE = 0 AND FW.CURRENT_STATUS_ID != 4
AND API.GL_DATE BETWEEN IN_DATE_FROM AND IN_DATE_TO
AND API.INVOICE_TYPE_ID = 45

UNION ALL
SELECT 'AP INVOICE - IMPORTATION - NSB 5' AS SOURCE, API.AP_INVOICE_ID AS ID,
CONCAT('API I NSB 5 ', API.SEQUENCE_NO) AS SEQUENCE_NO,
CONCAT('Invoice No. ', API.INVOICE_NUMBER) AS REF_NUMBER,
API.GL_DATE AS DATE FROM AP_INVOICE API
INNER JOIN COMPANY C ON C.COMPANY_ID = API.COMPANY_ID
INNER JOIN FORM_WORKFLOW FW ON FW.FORM_WORKFLOW_ID = API.FORM_WORKFLOW_ID
WHERE FW.IS_COMPLETE = 0 AND FW.CURRENT_STATUS_ID != 4
AND API.GL_DATE BETWEEN IN_DATE_FROM AND IN_DATE_TO
AND API.INVOICE_TYPE_ID = 46

UNION ALL
SELECT 'AP INVOICE - IMPORTATION - NSB 8' AS SOURCE, API.AP_INVOICE_ID AS ID,
CONCAT('API I NSB 8 ', API.SEQUENCE_NO) AS SEQUENCE_NO,
CONCAT('Invoice No. ', API.INVOICE_NUMBER) AS REF_NUMBER,
API.GL_DATE AS DATE FROM AP_INVOICE API
INNER JOIN COMPANY C ON C.COMPANY_ID = API.COMPANY_ID
INNER JOIN FORM_WORKFLOW FW ON FW.FORM_WORKFLOW_ID = API.FORM_WORKFLOW_ID
WHERE FW.IS_COMPLETE = 0 AND FW.CURRENT_STATUS_ID != 4
AND API.GL_DATE BETWEEN IN_DATE_FROM AND IN_DATE_TO
AND API.INVOICE_TYPE_ID = 47

UNION ALL
SELECT 'AP INVOICE - IMPORTATION - NSB 8A' AS SOURCE, API.AP_INVOICE_ID AS ID,
CONCAT('API I  NSB 8A ', API.SEQUENCE_NO) AS SEQUENCE_NO,
CONCAT('Invoice No. ', API.INVOICE_NUMBER) AS REF_NUMBER,
API.GL_DATE AS DATE FROM AP_INVOICE API
INNER JOIN COMPANY C ON C.COMPANY_ID = API.COMPANY_ID
INNER JOIN FORM_WORKFLOW FW ON FW.FORM_WORKFLOW_ID = API.FORM_WORKFLOW_ID
WHERE FW.IS_COMPLETE = 0 AND FW.CURRENT_STATUS_ID != 4
AND API.GL_DATE BETWEEN IN_DATE_FROM AND IN_DATE_TO
AND API.INVOICE_TYPE_ID = 48

UNION ALL
SELECT 'RECEIVING REPORT - CENTRAL' AS SOURCE, API.AP_INVOICE_ID AS ID,
CONCAT('RR CENTRAL ', API.SEQUENCE_NO) AS SEQUENCE_NO,
CONCAT('Invoice No. ', API.INVOICE_NUMBER) AS REF_NUMBER,
API.GL_DATE AS DATE FROM AP_INVOICE API
INNER JOIN R_RECEIVING_REPORT RR ON RR.AP_INVOICE_ID = API.AP_INVOICE_ID
INNER JOIN COMPANY C ON C.COMPANY_ID = API.COMPANY_ID
INNER JOIN FORM_WORKFLOW FW ON FW.FORM_WORKFLOW_ID = API.FORM_WORKFLOW_ID
WHERE FW.IS_COMPLETE = 0 AND FW.CURRENT_STATUS_ID != 4
AND API.GL_DATE BETWEEN IN_DATE_FROM AND IN_DATE_TO
AND API.INVOICE_TYPE_ID = 13

UNION ALL
SELECT 'RECEIVING REPORT - NSB 3' AS SOURCE, API.AP_INVOICE_ID AS ID,
CONCAT('RR NSB 3 ', API.SEQUENCE_NO) AS SEQUENCE_NO,
CONCAT('Invoice No. ', API.INVOICE_NUMBER) AS REF_NUMBER,
API.GL_DATE AS DATE FROM AP_INVOICE API
INNER JOIN R_RECEIVING_REPORT RR ON RR.AP_INVOICE_ID = API.AP_INVOICE_ID
INNER JOIN COMPANY C ON C.COMPANY_ID = API.COMPANY_ID
INNER JOIN FORM_WORKFLOW FW ON FW.FORM_WORKFLOW_ID = API.FORM_WORKFLOW_ID
WHERE FW.IS_COMPLETE = 0 AND FW.CURRENT_STATUS_ID != 4
AND API.GL_DATE BETWEEN IN_DATE_FROM AND IN_DATE_TO
AND API.INVOICE_TYPE_ID = 14

UNION ALL
SELECT 'RECEIVING REPORT - NSB 4' AS SOURCE, API.AP_INVOICE_ID AS ID,
CONCAT('RR NSB 4 ', API.SEQUENCE_NO) AS SEQUENCE_NO,
CONCAT('Invoice No. ', API.INVOICE_NUMBER) AS REF_NUMBER,
API.GL_DATE AS DATE FROM AP_INVOICE API
INNER JOIN R_RECEIVING_REPORT RR ON RR.AP_INVOICE_ID = API.AP_INVOICE_ID
INNER JOIN COMPANY C ON C.COMPANY_ID = API.COMPANY_ID
INNER JOIN FORM_WORKFLOW FW ON FW.FORM_WORKFLOW_ID = API.FORM_WORKFLOW_ID
WHERE FW.IS_COMPLETE = 0 AND FW.CURRENT_STATUS_ID != 4
AND API.GL_DATE BETWEEN IN_DATE_FROM AND IN_DATE_TO
AND API.INVOICE_TYPE_ID = 15

UNION ALL
SELECT 'RECEIVING REPORT - NSB 5' AS SOURCE, API.AP_INVOICE_ID AS ID,
CONCAT('RR NSB 5 ', API.SEQUENCE_NO) AS SEQUENCE_NO,
CONCAT('Invoice No. ', API.INVOICE_NUMBER) AS REF_NUMBER,
API.GL_DATE AS DATE FROM AP_INVOICE API
INNER JOIN R_RECEIVING_REPORT RR ON RR.AP_INVOICE_ID = API.AP_INVOICE_ID
INNER JOIN COMPANY C ON C.COMPANY_ID = API.COMPANY_ID
INNER JOIN FORM_WORKFLOW FW ON FW.FORM_WORKFLOW_ID = API.FORM_WORKFLOW_ID
WHERE FW.IS_COMPLETE = 0 AND FW.CURRENT_STATUS_ID != 4
AND API.GL_DATE BETWEEN IN_DATE_FROM AND IN_DATE_TO
AND API.INVOICE_TYPE_ID = 16

UNION ALL
SELECT 'RECEIVING REPORT - NSB 8' AS SOURCE, API.AP_INVOICE_ID AS ID,
CONCAT('RR NSB 8 ', API.SEQUENCE_NO) AS SEQUENCE_NO,
CONCAT('Invoice No. ', API.INVOICE_NUMBER) AS REF_NUMBER,
API.GL_DATE AS DATE FROM AP_INVOICE API
INNER JOIN R_RECEIVING_REPORT RR ON RR.AP_INVOICE_ID = API.AP_INVOICE_ID
INNER JOIN COMPANY C ON C.COMPANY_ID = API.COMPANY_ID
INNER JOIN FORM_WORKFLOW FW ON FW.FORM_WORKFLOW_ID = API.FORM_WORKFLOW_ID
WHERE FW.IS_COMPLETE = 0 AND FW.CURRENT_STATUS_ID != 4
AND API.GL_DATE BETWEEN IN_DATE_FROM AND IN_DATE_TO
AND API.INVOICE_TYPE_ID = 17

UNION ALL
SELECT 'RECEIVING REPORT - NSB 8A' AS SOURCE, API.AP_INVOICE_ID AS ID,
CONCAT('RR NSB 8A ', API.SEQUENCE_NO) AS SEQUENCE_NO,
CONCAT('Invoice No. ', API.INVOICE_NUMBER) AS REF_NUMBER,
API.GL_DATE AS DATE FROM AP_INVOICE API
INNER JOIN R_RECEIVING_REPORT RR ON RR.AP_INVOICE_ID = API.AP_INVOICE_ID
INNER JOIN COMPANY C ON C.COMPANY_ID = API.COMPANY_ID
INNER JOIN FORM_WORKFLOW FW ON FW.FORM_WORKFLOW_ID = API.FORM_WORKFLOW_ID
WHERE FW.IS_COMPLETE = 0 AND FW.CURRENT_STATUS_ID != 4
AND API.GL_DATE BETWEEN IN_DATE_FROM AND IN_DATE_TO
AND API.INVOICE_TYPE_ID = 18

UNION ALL

SELECT 'AR TRANSACTION - CENTRAL' AS SOURCE, ART.AR_TRANSACTION_ID AS ID,
CONCAT('ART CENTRAL ', ART.SEQUENCE_NO) AS SEQUENCE_NO,
CONCAT('Transaction No. ', ART.TRANSACTION_NUMBER) AS REF_NUMBER,
TRANSACTION_DATE AS DATE FROM AR_TRANSACTION ART
INNER JOIN COMPANY C ON C.COMPANY_ID = ART.COMPANY_ID
INNER JOIN FORM_WORKFLOW FW ON FW.FORM_WORKFLOW_ID = ART.FORM_WORKFLOW_ID
WHERE FW.IS_COMPLETE = 0 AND FW.CURRENT_STATUS_ID != 4
AND ART.TRANSACTION_DATE BETWEEN IN_DATE_FROM AND IN_DATE_TO
AND AR_TRANSACTION_TYPE_ID = 17

UNION ALL

SELECT 'AR TRANSACTION - NSB 3' AS SOURCE, ART.AR_TRANSACTION_ID AS ID,
CONCAT('ART NSB 3 ', ART.SEQUENCE_NO) AS SEQUENCE_NO,
CONCAT('Transaction No. ', ART.TRANSACTION_NUMBER) AS REF_NUMBER,
TRANSACTION_DATE AS DATE FROM AR_TRANSACTION ART
INNER JOIN COMPANY C ON C.COMPANY_ID = ART.COMPANY_ID
INNER JOIN FORM_WORKFLOW FW ON FW.FORM_WORKFLOW_ID = ART.FORM_WORKFLOW_ID
WHERE FW.IS_COMPLETE = 0 AND FW.CURRENT_STATUS_ID != 4
AND ART.TRANSACTION_DATE BETWEEN IN_DATE_FROM AND IN_DATE_TO
AND AR_TRANSACTION_TYPE_ID = 18

UNION ALL

SELECT 'AR TRANSACTION - NSB 5' AS SOURCE, ART.AR_TRANSACTION_ID AS ID,
CONCAT('ART NSB 5 ', ART.SEQUENCE_NO) AS SEQUENCE_NO,
CONCAT('Transaction No. ', ART.TRANSACTION_NUMBER) AS REF_NUMBER,
TRANSACTION_DATE AS DATE FROM AR_TRANSACTION ART
INNER JOIN COMPANY C ON C.COMPANY_ID = ART.COMPANY_ID
INNER JOIN FORM_WORKFLOW FW ON FW.FORM_WORKFLOW_ID = ART.FORM_WORKFLOW_ID
WHERE FW.IS_COMPLETE = 0 AND FW.CURRENT_STATUS_ID != 4
AND ART.TRANSACTION_DATE BETWEEN IN_DATE_FROM AND IN_DATE_TO
AND AR_TRANSACTION_TYPE_ID = 19

UNION ALL

SELECT 'AR TRANSACTION - NSB 5' AS SOURCE, ART.AR_TRANSACTION_ID AS ID,
CONCAT('ART NSB 5 ', ART.SEQUENCE_NO) AS SEQUENCE_NO,
CONCAT('Transaction No. ', ART.TRANSACTION_NUMBER) AS REF_NUMBER,
TRANSACTION_DATE AS DATE FROM AR_TRANSACTION ART
INNER JOIN COMPANY C ON C.COMPANY_ID = ART.COMPANY_ID
INNER JOIN FORM_WORKFLOW FW ON FW.FORM_WORKFLOW_ID = ART.FORM_WORKFLOW_ID
WHERE FW.IS_COMPLETE = 0 AND FW.CURRENT_STATUS_ID != 4
AND ART.TRANSACTION_DATE BETWEEN IN_DATE_FROM AND IN_DATE_TO
AND AR_TRANSACTION_TYPE_ID = 20

UNION ALL

SELECT 'AR TRANSACTION - NSB 8' AS SOURCE, ART.AR_TRANSACTION_ID AS ID,
CONCAT('ART NSB 8 ', ART.SEQUENCE_NO) AS SEQUENCE_NO,
CONCAT('Transaction No. ', ART.TRANSACTION_NUMBER) AS REF_NUMBER,
TRANSACTION_DATE AS DATE FROM AR_TRANSACTION ART
INNER JOIN COMPANY C ON C.COMPANY_ID = ART.COMPANY_ID
INNER JOIN FORM_WORKFLOW FW ON FW.FORM_WORKFLOW_ID = ART.FORM_WORKFLOW_ID
WHERE FW.IS_COMPLETE = 0 AND FW.CURRENT_STATUS_ID != 4
AND ART.TRANSACTION_DATE BETWEEN IN_DATE_FROM AND IN_DATE_TO
AND AR_TRANSACTION_TYPE_ID = 21

UNION ALL

SELECT 'AR TRANSACTION - NSB 8A' AS SOURCE, ART.AR_TRANSACTION_ID AS ID,
CONCAT('ART NSB 8A ', ART.SEQUENCE_NO) AS SEQUENCE_NO,
CONCAT('Transaction No. ', ART.TRANSACTION_NUMBER) AS REF_NUMBER,
TRANSACTION_DATE AS DATE FROM AR_TRANSACTION ART
INNER JOIN COMPANY C ON C.COMPANY_ID = ART.COMPANY_ID
INNER JOIN FORM_WORKFLOW FW ON FW.FORM_WORKFLOW_ID = ART.FORM_WORKFLOW_ID
WHERE FW.IS_COMPLETE = 0 AND FW.CURRENT_STATUS_ID != 4
AND ART.TRANSACTION_DATE BETWEEN IN_DATE_FROM AND IN_DATE_TO
AND AR_TRANSACTION_TYPE_ID = 22
) AS TBL LIMIT 10;

END //