-- Description: Stored procedure that will get the monthly Alphalist of Payees

Delimiter //
DROP PROCEDURE IF EXISTS GET_MAP;//
CREATE PROCEDURE GET_MAP(IN IN_COMPANY_ID INT, IN IN_DIVISION_ID INT,
IN IN_YEAR INT, IN IN_MONTH INT, IN IN_LIMIT_FROM INT, IN IN_LIMIT_TO INT)

BEGIN

SELECT AI.SEQUENCE_NO, AC.TIN,
(CASE WHEN AC.BUSINESS_CLASSIFICATION_ID = 2 THEN AC.NAME WHEN AC.BUSINESS_CLASSIFICATION_ID = 1 THEN concat(AC.FIRST_NAME,' ', AC.LAST_NAME)  END) AS REGISTERED_NAME ,
BA.NAME, BA.DESCRIPTION, AI.AMOUNT, WS.VALUE, AI.WT_AMOUNT
FROM AR_INVOICE AI
INNER JOIN AR_CUSTOMER AC ON AI.AR_CUSTOMER_ID = AC.AR_CUSTOMER_ID
INNER JOIN WT_ACCOUNT_SETTING WS ON AI.WT_ACCOUNT_SETTING_ID = WS.WT_ACCOUNT_SETTING_ID
INNER JOIN BIR_ATC BA ON WS.BIR_ATC_ID = BA.BIR_ATC_ID
INNER JOIN FORM_WORKFLOW FW ON AI.FORM_WORKFLOW_ID = FW.FORM_WORKFLOW_ID
WHERE AI.COMPANY_ID = IN_COMPANY_ID
AND IF(IN_DIVISION_ID != -1, AI.COMPANY_ID = IN_DIVISION_ID, AI.COMPANY_ID != IN_DIVISION_ID)
AND MONTH(AI.DATE) = IN_MONTH
AND YEAR(AI.DATE) = IN_YEAR
AND FW.IS_COMPLETE = 1
ORDER BY AI.SEQUENCE_NO ASC;
END //