
-- Description: sql script in creating ACCOUNT_SALE table.
-- This table for account sales reference just like AS to AS-Order.

DROP TABLE IF EXISTS ACCOUNT_SALE;

CREATE TABLE `ACCOUNT_SALE` (
  `ACCOUNT_SALE_ID` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `FORM_WORKFLOW_ID` int(10) unsigned NOT NULL,
  `COMPANY_ID` int(10) unsigned NOT NULL,
  `AR_CUSTOMER_ID` int(10) unsigned NOT NULL,
  `AR_CUSTOMER_ACCOUNT_ID` int(10) unsigned NOT NULL,
  `PO_DATE` date NOT NULL,
  `PO_NUMBER` int(20) NOT NULL,
  `REMARKS` varchar(100) DEFAULT NULL,
  `EB_OBJECT_ID` int(10) unsigned DEFAULT NULL,
  `CREATED_BY` int(10) unsigned NOT NULL,
  `CREATED_DATE` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_BY` int(10) unsigned NOT NULL,
  `UPDATED_DATE` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  PRIMARY KEY (`ACCOUNT_SALE_ID`),
  KEY `FK_AS_COMPANY_ID` (`COMPANY_ID`),
  KEY `FK_AS_AR_CUSTOMER_ID` (`AR_CUSTOMER_ID`),
  KEY `FK_AS_AR_CUSTOMER_ACCOUNT_ID` (`AR_CUSTOMER_ACCOUNT_ID`),
  KEY `FK_AS_CREATED_BY` (`CREATED_BY`),
  KEY `FK_AS_UPDATED_BY` (`UPDATED_BY`),
  KEY `FK_AS_FORM_WORKFLOW_ID` (`FORM_WORKFLOW_ID`),
  KEY `FK_AS_EB_OBJECT_ID` (`EB_OBJECT_ID`),
  CONSTRAINT `FK_AS_EB_OBJECT_ID` FOREIGN KEY (`EB_OBJECT_ID`) REFERENCES `EB_OBJECT` (`EB_OBJECT_ID`),
  CONSTRAINT `FK_AS_COMPANY_ID` FOREIGN KEY (`COMPANY_ID`) REFERENCES `COMPANY` (`COMPANY_ID`),
  CONSTRAINT `FK_AS_CREATED_BY` FOREIGN KEY (`CREATED_BY`) REFERENCES `USER` (`USER_ID`),
  CONSTRAINT `FK_AS_FORM_WORKFLOW_ID` FOREIGN KEY (`FORM_WORKFLOW_ID`) REFERENCES `FORM_WORKFLOW` (`FORM_WORKFLOW_ID`),
  CONSTRAINT `FK_AS_AR_CUSTOMER_ACCOUNT_ID` FOREIGN KEY (`AR_CUSTOMER_ACCOUNT_ID`) REFERENCES `AR_CUSTOMER_ACCOUNT` (`AR_CUSTOMER_ACCOUNT_ID`),
  CONSTRAINT `FK_AS_AR_CUSTOMER_ID` FOREIGN KEY (`AR_CUSTOMER_ID`) REFERENCES `AR_CUSTOMER` (`AR_CUSTOMER_ID`),
  CONSTRAINT `FK_AS_UPDATED_BY` FOREIGN KEY (`UPDATED_BY`) REFERENCES `USER` (`USER_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;