
-- Description: sql script in creating ACCOUNT_SALES_PO_ITEM table.

DROP TABLE IF EXISTS ACCOUNT_SALES_PO_ITEM;

CREATE TABLE `ACCOUNT_SALES_PO_ITEM` (
  `ACCOUNT_SALES_PO_ITEM_ID` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `ACCOUNT_SALE_ID` int(10) unsigned NOT NULL,
  `ITEM_ID` int(10) unsigned NOT NULL,
  `QUANTITY` double DEFAULT '0',
  `EB_OBJECT_ID` int(10) unsigned DEFAULT NULL,
  `WAREHOUSE_ID` int(10) unsigned NOT NULL,
  PRIMARY KEY (`ACCOUNT_SALES_PO_ITEM_ID`),
  KEY `FK_ASPOI_ACCOUNT_SALE_ID` (`ACCOUNT_SALE_ID`),
  KEY `FK_ASPOI_ITEM_ID` (`ITEM_ID`),
  KEY `FK_ASPOI_WAREHOUSE_ID` (`WAREHOUSE_ID`),
  KEY `FK_ASPOI_EB_OBJECT_ID` (`EB_OBJECT_ID`),
  CONSTRAINT `FK_ASPOI_EB_OBJECT_ID` FOREIGN KEY (`EB_OBJECT_ID`) REFERENCES `EB_OBJECT` (`EB_OBJECT_ID`),
  CONSTRAINT `FK_ASPOI_ITEM_ID` FOREIGN KEY (`ITEM_ID`) REFERENCES `ITEM` (`ITEM_ID`),
  CONSTRAINT `FK_ASPOI_WAREHOUSE_ID` FOREIGN KEY (`WAREHOUSE_ID`) REFERENCES `WAREHOUSE` (`WAREHOUSE_ID`),
  CONSTRAINT `FK_ASPOI_ACCOUNT_SALE_ID` FOREIGN KEY (`ACCOUNT_SALE_ID`) REFERENCES `ACCOUNT_SALE` (`ACCOUNT_SALE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;