
-- Description: Sql script for creating ACCOUNT SALE ITEM table

DROP TABLE IF EXISTS ACCOUNT_SALE_ITEM;

CREATE TABLE `ACCOUNT_SALE_ITEM`(
  `ACCOUNT_SALE_ITEM_ID` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `REF_ACCOUNT_SALE_ITEM_ID` int(10) unsigned DEFAULT NULL,
  `AR_TRANSACTION_ID` int(10) unsigned NOT NULL,
  `EB_OBJECT_ID` int(10) unsigned DEFAULT NULL,
  `ITEM_ID` int(10) unsigned NOT NULL,
  `WAREHOUSE_ID` int(10) unsigned NOT NULL,
  `QUANTITY` double NOT NULL,
  `ITEM_SRP_ID` int(10) unsigned NOT NULL,
  `SRP` double NOT NULL,
  `ITEM_DISCOUNT_ID` int(10) unsigned DEFAULT NULL,
  `UNIT_COST` double NOT NULL DEFAULT '0',
  `DISCOUNT` double DEFAULT '0',
  `ITEM_ADD_ON_ID` int(10) unsigned DEFAULT NULL,
  `AMOUNT` double NOT NULL,
  PRIMARY KEY (`ACCOUNT_SALE_ITEM_ID`),
  KEY `FK_ACCOUNT_SALES_ITEM_AR_TRANSACTION_ID` (`AR_TRANSACTION_ID`),
  KEY `FK_ACCOUNT_SALES_ITEM_EB_OBJECT_ID` (`EB_OBJECT_ID`),
  KEY `FK_ACCOUNT_SALES_ITEM_ITEM_ID` (`ITEM_ID`),
  KEY `FK_ACCOUNT_SALES_ITEM_WAREHOUSE_ID` (`WAREHOUSE_ID`),
  KEY `FK_ACCOUNT_SALES_ITEM_ITEM_SRP_ID` (`ITEM_SRP_ID`),
  KEY `FK_ACCOUNT_SALES_ITEM_ITEM_DISCOUNT_ID` (`ITEM_DISCOUNT_ID`),
  KEY `FK_ACCOUNT_SALES_ITEM_ADD_ON_ID` (`ITEM_ADD_ON_ID`),
  CONSTRAINT `FK_ACCOUNT_SALES_ITEM_EB_OBJECT_ID` FOREIGN KEY (`EB_OBJECT_ID`) REFERENCES `EB_OBJECT` (`EB_OBJECT_ID`),
  CONSTRAINT `FK_ACCOUNT_SALES_ITEM_AR_TRANSACTION_ID` FOREIGN KEY (`AR_TRANSACTION_ID`) REFERENCES `AR_TRANSACTION` (`AR_TRANSACTION_ID`),
  CONSTRAINT `FK_ACCOUNT_SALES_ITEM_ITEM_ID` FOREIGN KEY (`ITEM_ID`) REFERENCES `ITEM` (`ITEM_ID`),
  CONSTRAINT `FK_ACCOUNT_SALES_ITEM_WAREHOUSE_ID` FOREIGN KEY (`WAREHOUSE_ID`) REFERENCES `WAREHOUSE` (`WAREHOUSE_ID`),
  CONSTRAINT `FK_ACCOUNT_SALES_ITEM_ITEM_SRP_ID` FOREIGN KEY (`ITEM_SRP_ID`) REFERENCES `ITEM_SRP` (`ITEM_SRP_ID`),
  CONSTRAINT `FK_ACCOUNT_SALES_ITEM_ITEM_DISCOUNT_ID` FOREIGN KEY (`ITEM_DISCOUNT_ID`) REFERENCES `ITEM_DISCOUNT` (`ITEM_DISCOUNT_ID`),
   CONSTRAINT `FK_ACCOUNT_SALES_ITEM_ADD_ON_ID` FOREIGN KEY (`ITEM_ADD_ON_ID`) REFERENCES `ITEM_ADD_ON` (`ITEM_ADD_ON_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;