
-- Description: Create script for BUSINESS_CLASSIFICATION table.

DROP TABLE IF EXISTS BUSINESS_CLASSIFICATION;
CREATE TABLE BUSINESS_CLASSIFICATION(
BUSINESS_CLASSIFICATION_ID int(10) unsigned NOT NULL AUTO_INCREMENT,
NAME varchar(20) NOT NULL,
ACTIVE tinyint(1) NOT NULL,
CREATED_BY INT(10) UNSIGNED NOT NULL,
CREATED_DATE timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
UPDATED_BY INT(10) UNSIGNED NOT NULL,
UPDATED_DATE timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
PRIMARY KEY (BUSINESS_CLASSIFICATION_ID),
KEY FK_BC_CREATED_BY (CREATED_BY),
KEY FK_BC_UPDATED_BY (UPDATED_BY),
CONSTRAINT FK_BC_CREATED_BY FOREIGN KEY (CREATED_BY) REFERENCES USER (USER_ID),
CONSTRAINT FK_BC_UPDATED_BY FOREIGN KEY (UPDATED_BY) REFERENCES USER (USER_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;