
-- Description: Create script for CAP_DELIVERY_TRANSACTION table.

DROP TABLE IF EXISTS CAP_DELIVERY_TRANSACTION;

CREATE TABLE CAP_DELIVERY_TRANSACTION (
CAP_DELIVERY_TRANSACTION_ID INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
CAP_DELIVERY_ID INT(10) UNSIGNED NOT NULL,
AR_TRANSACTION_ID INT(10) UNSIGNED NOT NULL,
PRIMARY KEY (CAP_DELIVERY_TRANSACTION_ID),
KEY FK_CAPDT_CAPD_ID (CAP_DELIVERY_ID),
KEY FK_CAPDT_ART_ID (AR_TRANSACTION_ID),
CONSTRAINT FK_CAPDT_CAPD_ID FOREIGN KEY (CAP_DELIVERY_ID) REFERENCES CAP_DELIVERY (CAP_DELIVERY_ID),
CONSTRAINT FK_CAPDT_ART_ID FOREIGN KEY (AR_TRANSACTION_ID) REFERENCES AR_TRANSACTION (AR_TRANSACTION_ID)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;