
-- Description: sql script in creating CASH_SALE_AR_LINE table.

DROP TABLE IF EXISTS CASH_SALE_AR_LINE;

CREATE TABLE `CASH_SALE_AR_LINE` (
  `CASH_SALE_AR_LINE_ID` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `CASH_SALE_ID` int(10) unsigned NOT NULL,
  `AR_LINE_SETUP_ID` int(10) unsigned NOT NULL,
  `EB_OBJECT_ID` int(10) unsigned DEFAULT NULL,
  `QUANTITY` double DEFAULT '0',
  `UNITOFMEASUREMENT_ID` int(10) unsigned DEFAULT NULL,
  `UP_AMOUNT` double DEFAULT '0',
  `AMOUNT` double DEFAULT '0',
  PRIMARY KEY (`CASH_SALE_AR_LINE_ID`),
  KEY `FK_CS_AL_CASH_SALE_ID` (`CASH_SALE_ID`),
  KEY `FK_CS_AL_AR_LINE_SETUP_ID` (`AR_LINE_SETUP_ID`),
  KEY `FK_CS_AL_EB_OBJECT_ID` (`EB_OBJECT_ID`),
  CONSTRAINT `FK_CS_AL_AR_LINE_SETUP_ID` FOREIGN KEY (`AR_LINE_SETUP_ID`) REFERENCES `AR_LINE_SETUP` (`AR_LINE_SETUP_ID`),
  CONSTRAINT `FK_CS_AL_CASH_SALE_ID` FOREIGN KEY (`CASH_SALE_ID`) REFERENCES `CASH_SALE` (`CASH_SALE_ID`),
  CONSTRAINT `FK_CS_AL_EB_OBJECT_ID` FOREIGN KEY (`EB_OBJECT_ID`) REFERENCES `EB_OBJECT` (`EB_OBJECT_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;