
-- Description: Sql script for creating CASH_SALE table

DROP TABLE IF EXISTS CASH_SALE;

CREATE TABLE `CASH_SALE` (
  `CASH_SALE_ID` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `CASH_SALE_TYPE_ID` int(10) unsigned DEFAULT '1',
  `CS_NUMBER` int(20) unsigned NOT NULL,
  `COMPANY_ID` int(10) unsigned NOT NULL,
  `AR_RECEIPT_TYPE_ID` int(10) unsigned NOT NULL,
  `REF_NUMBER` varchar(20) DEFAULT NULL,
  `AR_CUSTOMER_ID` int(10) unsigned NOT NULL,
  `AR_CUSTOMER_ACCOUNT_ID` int(10) unsigned NOT NULL,
  `SALE_INVOICE_NO` varchar(100) DEFAULT NULL,
  `RECEIPT_DATE` date NOT NULL,
  `MATURITY_DATE` date NOT NULL,
  `CASH` double NOT NULL,
  `FORM_WORKFLOW_ID` int(10) unsigned DEFAULT NULL,
  `EB_OBJECT_ID` int(10) unsigned DEFAULT NULL,
  `CREATED_BY` int(10) unsigned NOT NULL,
  `CREATED_DATE` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_BY` int(10) unsigned NOT NULL,
  `UPDATED_DATE` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  PRIMARY KEY (`CASH_SALE_ID`),
  KEY `FK_CASH_SALE_COMPANY_ID` (`COMPANY_ID`),
  KEY `FK_CASH_SALE_TYPE_ID` (`AR_RECEIPT_TYPE_ID`),
  KEY `FK_CASH_SALE_CUSTOMER_ID` (`AR_CUSTOMER_ID`),
  KEY `FK_CASH_SALE_CUSTOMER_ACCOUNT_ID` (`AR_CUSTOMER_ACCOUNT_ID`),
  KEY `FK_CASH_SALE_FORM_WORKFLOW_ID` (`FORM_WORKFLOW_ID`),
  KEY `FK_CASH_SALE_CREATED_BY` (`CREATED_BY`),
  KEY `FK_CASH_SALE_UPDATED_BY` (`UPDATED_BY`),
  KEY `FK_CASH_SALE_CS_TYPE_ID` (`CASH_SALE_TYPE_ID`),
  KEY `FK_CASH_SALE_EB_OBJECT_ID` (`EB_OBJECT_ID`),
  CONSTRAINT `FK_CASH_SALE_COMPANY_ID` FOREIGN KEY (`COMPANY_ID`) REFERENCES `COMPANY` (`COMPANY_ID`),
  CONSTRAINT `FK_CASH_SALE_CREATED_BY` FOREIGN KEY (`CREATED_BY`) REFERENCES `USER` (`USER_ID`),
  CONSTRAINT `FK_CASH_SALE_CS_TYPE_ID` FOREIGN KEY (`CASH_SALE_TYPE_ID`) REFERENCES `CASH_SALE_TYPE` (`CASH_SALE_TYPE_ID`),
  CONSTRAINT `FK_CASH_SALE_CUSTOMER_ACCOUNT_ID` FOREIGN KEY (`AR_CUSTOMER_ACCOUNT_ID`) REFERENCES `AR_CUSTOMER_ACCOUNT` (`AR_CUSTOMER_ACCOUNT_ID`),
  CONSTRAINT `FK_CASH_SALE_CUSTOMER_ID` FOREIGN KEY (`AR_CUSTOMER_ID`) REFERENCES `AR_CUSTOMER` (`AR_CUSTOMER_ID`),
  CONSTRAINT `FK_CASH_SALE_EB_OBJECT_ID` FOREIGN KEY (`EB_OBJECT_ID`) REFERENCES `EB_OBJECT` (`EB_OBJECT_ID`),
  CONSTRAINT `FK_CASH_SALE_FORM_WORKFLOW_ID` FOREIGN KEY (`FORM_WORKFLOW_ID`) REFERENCES `FORM_WORKFLOW` (`FORM_WORKFLOW_ID`),
  CONSTRAINT `FK_CASH_SALE_TYPE_ID` FOREIGN KEY (`AR_RECEIPT_TYPE_ID`) REFERENCES `AR_RECEIPT_TYPE` (`AR_RECEIPT_TYPE_ID`),
  CONSTRAINT `FK_CASH_SALE_UPDATED_BY` FOREIGN KEY (`UPDATED_BY`) REFERENCES `USER` (`USER_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;