
-- Description: Sql script for creating CUSTOMER_ADVANCE_PAYMENT_TYPE_TYPE table

DROP TABLE IF EXISTS CUSTOMER_ADVANCE_PAYMENT_TYPE;

CREATE TABLE CUSTOMER_ADVANCE_PAYMENT_TYPE (
 CUSTOMER_ADVANCE_PAYMENT_TYPE_ID int(10) unsigned NOT NULL AUTO_INCREMENT,
 NAME varchar(20) NOT NULL,
 ACTIVE tinyint(1) NOT NULL,
 CREATED_BY int(10) unsigned NOT NULL,
 CREATED_DATE timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
 UPDATED_BY int(10) unsigned NOT NULL,
 UPDATED_DATE timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
 PRIMARY KEY (CUSTOMER_ADVANCE_PAYMENT_TYPE_ID),
 KEY FK_CAP_TYPE_CREATED_BY (CREATED_BY),
 KEY FK_CAP_TYPE_UPDATED_BY (UPDATED_BY),
 CONSTRAINT FK_CAP_TYPE_CREATED_BY FOREIGN KEY (CREATED_BY) REFERENCES USER (USER_ID),
 CONSTRAINT FK_CAP_TYPE_UPDATED_BY FOREIGN KEY (UPDATED_BY) REFERENCES USER (USER_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
