
-- Description	: Create script for DRIVER table.

DROP TABLE IF EXISTS DRIVER;

CREATE TABLE DRIVER (
  DRIVER_ID int(10) unsigned NOT NULL AUTO_INCREMENT,
  COMPANY_ID int(10) unsigned NOT NULL,
  GENDER_ID int(10) unsigned NOT NULL,
  CIVIL_STATUS_ID int(10) unsigned NOT NULL,
  FIRST_NAME varchar(40) NOT NULL,
  MIDDLE_NAME varchar(40) DEFAULT NULL,
  LAST_NAME varchar(40) NOT NULL,
  BIRTH_DATE date NOT NULL,
  CONTACT_NO varchar(20) DEFAULT NULL,
  ADDRESS varchar(150) NOT NULL,
  ACTIVE tinyint(1) NOT NULL,
  CREATED_BY int(10) unsigned NOT NULL,
  CREATED_DATE timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UPDATED_BY int(10) unsigned NOT NULL,
  UPDATED_DATE timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  PRIMARY KEY (DRIVER_ID),
  KEY FK_DRIVER_COMPANY_ID (COMPANY_ID),
  KEY FK_DRIVER_GENDER_ID (GENDER_ID),
  KEY FK_DRIVER_CIVIL_STATUS_ID (CIVIL_STATUS_ID),
  KEY FK_DRIVER_CREATED_BY (CREATED_BY),
  KEY FK_DRIVER_UPDATED_BY (UPDATED_BY),
  CONSTRAINT FK_DRIVER_COMPANY_ID FOREIGN KEY (COMPANY_ID) REFERENCES COMPANY (COMPANY_ID),
  CONSTRAINT FK_DRIVER_GENDER_ID FOREIGN KEY (GENDER_ID) REFERENCES GENDER (GENDER_ID),
  CONSTRAINT FK_DRIVER_CIVIL_STATUS_ID FOREIGN KEY (CIVIL_STATUS_ID) REFERENCES CIVIL_STATUS (CIVIL_STATUS_ID),
  CONSTRAINT FK_DRIVER_CREATED_BY FOREIGN KEY (CREATED_BY) REFERENCES USER (USER_ID),
  CONSTRAINT FK_DRIVER_UPDATED_BY FOREIGN KEY (UPDATED_BY) REFERENCES USER (USER_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;