
-- Description: Insert values for ITEM_DISCOUNT_TYPE

SYSTEM echo 'Inserting ITEM_DISCOUNT_TYPE';
INSERT INTO ITEM_DISCOUNT_TYPE VALUES (1, 'Percentage');
INSERT INTO ITEM_DISCOUNT_TYPE VALUES (2, 'Amount');
INSERT INTO ITEM_DISCOUNT_TYPE VALUES (3, 'Quantity');