
-- Description: sql script in creating INVENTORY_ACCOUNT table.

DROP TABLE IF EXISTS INVENTORY_ACCOUNT;

CREATE TABLE `INVENTORY_ACCOUNT` (
  `INVENTORY_ACCOUNT_ID` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `COMPANY_ID` int(10) unsigned NOT NULL,
  `CASH_SALES_RM_ID` int(10) NOT NULL,
  `CUSTOMER_ADV_PAYMENT_RM_ID` int(10) NOT NULL,
  `ACTIVE` tinyint(1) NOT NULL,
  `CREATED_BY` int(10) unsigned NOT NULL,
  `CREATED_DATE` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_BY` int(10) unsigned NOT NULL,
  `UPDATED_DATE` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  PRIMARY KEY (`INVENTORY_ACCOUNT_ID`),
  KEY `FK_IA_CREATED_BY` (`CREATED_BY`),
  KEY `FK_IA_UPDATED_BY` (`UPDATED_BY`),
  KEY `FK_IA_COMPANY_ID` (`COMPANY_ID`),
  KEY `FK_IA_CASH_SALES_RM_ID` (`CASH_SALES_RM_ID`),
  KEY `FK_IA_CUSTOMER_ADV_PAYMENT_RM_ID` (`CUSTOMER_ADV_PAYMENT_RM_ID`),
  CONSTRAINT `FK_IA_CUSTOMER_ADV_PAYMENT_RM_ID` FOREIGN KEY (`CUSTOMER_ADV_PAYMENT_RM_ID`) REFERENCES `RECEIPT_METHOD` (`RECEIPT_METHOD_ID`),
  CONSTRAINT `FK_IA_CASH_SALES_RM_ID` FOREIGN KEY (`CASH_SALES_RM_ID`) REFERENCES `RECEIPT_METHOD` (`RECEIPT_METHOD_ID`),
  CONSTRAINT `FK_IA_COMPANY_ID` FOREIGN KEY (`COMPANY_ID`) REFERENCES `COMPANY` (`COMPANY_ID`),
  CONSTRAINT `FK_IA_CREATED_BY` FOREIGN KEY (`CREATED_BY`) REFERENCES `USER` (`USER_ID`),
  CONSTRAINT `FK_IA_UPDATED_BY` FOREIGN KEY (`UPDATED_BY`) REFERENCES `USER` (`USER_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
