
-- Description: SQL script in creating ITEM_CATEGORY table.

DROP TABLE IF EXISTS ITEM_CATEGORY;

CREATE TABLE `ITEM_CATEGORY` (
  `ITEM_CATEGORY_ID` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `NAME` varchar(50) NOT NULL,
  `ACTIVE` tinyint(1) DEFAULT '1',
  PRIMARY KEY (`ITEM_CATEGORY_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;