
-- Description: sql script in creating ITEM_BUYING_DISCOUNT table.

DROP TABLE IF EXISTS ITEM_BUYING_DISCOUNT;

CREATE TABLE `ITEM_BUYING_DISCOUNT` (
  `ITEM_BUYING_DISCOUNT_ID` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `ITEM_ID` int(10) unsigned NOT NULL,
  `ITEM_DISCOUNT_TYPE_ID` int(10) unsigned NOT NULL,
  `COMPANY_ID` int(10) unsigned NOT NULL,
  `NAME` varchar(50) NOT NULL,
  `VALUE` double  NOT NULL,
  `ACTIVE` tinyint(1) DEFAULT '1',
  PRIMARY KEY (`ITEM_BUYING_DISCOUNT_ID`),
  KEY `FK_IBD_ITEM` (`ITEM_ID`),
  KEY `FK_IBD_DISCOUNT_TYPE` (`ITEM_DISCOUNT_TYPE_ID`),
  KEY `FK_IBD_COMPANY` (`COMPANY_ID`),
  CONSTRAINT `FK_IBD_ITEM` FOREIGN KEY (`ITEM_ID`) REFERENCES `ITEM` (`ITEM_ID`),
  CONSTRAINT `FK_IBD_DISCOUNT_TYPE` FOREIGN KEY (`ITEM_DISCOUNT_TYPE_ID`) REFERENCES `ITEM_DISCOUNT_TYPE` (`ITEM_DISCOUNT_TYPE_ID`),
  CONSTRAINT `FK_IBD_COMPANY` FOREIGN KEY (`COMPANY_ID`) REFERENCES `COMPANY` (`COMPANY_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;