
-- Description: sql script in creating ITEM_DISCOUNT_TYPE table.

DROP TABLE IF EXISTS ITEM_DISCOUNT_TYPE;

CREATE TABLE `ITEM_DISCOUNT_TYPE` (
  `ITEM_DISCOUNT_TYPE_ID` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `NAME` varchar(20) NOT NULL,
  PRIMARY KEY (`ITEM_DISCOUNT_TYPE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;