
-- Description: sql script in creating ITEM_CONVERSION table.

DROP TABLE IF EXISTS ITEM_CONVERSION;

CREATE TABLE `ITEM_CONVERSION` (
  `ITEM_CONVERSION_ID` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `FORM_WORKFLOW_ID` int(10) unsigned DEFAULT NULL,
  `COMPANY_ID` int(10) unsigned NOT NULL,
  `WAREHOUSE_ID` int(10) unsigned NOT NULL,
  `EB_OBJECT_ID` int(10) unsigned DEFAULT NULL,
  `DATE` date NOT NULL,
  `ITEM_CONVERSION_NUMBER` int(20) NOT NULL,
  `REMARKS` varchar(100) DEFAULT NULL,
  `CREATED_BY` int(10) unsigned NOT NULL,
  `CREATED_DATE` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_BY` int(10) unsigned NOT NULL,
  `UPDATED_DATE` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  PRIMARY KEY (`ITEM_CONVERSION_ID`),
  KEY `FK_IC_FORM_WORKFLOW_ID` (`FORM_WORKFLOW_ID`),
  KEY `FK_IC_COMPANY_ID` (`COMPANY_ID`),
  KEY `FK_IC_WAREHOUSE_ID` (`WAREHOUSE_ID`),
  KEY `FK_IC_CREATED_BY` (`CREATED_BY`),
  KEY `FK_IC_UPDATED_BY` (`UPDATED_BY`),
  KEY `FK_IC_EB_OBJECT_ID` (`EB_OBJECT_ID`),
  CONSTRAINT `FK_IC_COMPANY_ID` FOREIGN KEY (`COMPANY_ID`) REFERENCES `COMPANY` (`COMPANY_ID`),
  CONSTRAINT `FK_IC_CREATED_BY` FOREIGN KEY (`CREATED_BY`) REFERENCES `USER` (`USER_ID`),
  CONSTRAINT `FK_IC_FORM_WORKFLOW_ID` FOREIGN KEY (`FORM_WORKFLOW_ID`) REFERENCES `FORM_WORKFLOW` (`FORM_WORKFLOW_ID`),
  CONSTRAINT `FK_IC_UPDATED_BY` FOREIGN KEY (`UPDATED_BY`) REFERENCES `USER` (`USER_ID`),
  CONSTRAINT `FK_IC_WAREHOUSE_ID` FOREIGN KEY (`WAREHOUSE_ID`) REFERENCES `WAREHOUSE` (`WAREHOUSE_ID`),
  CONSTRAINT `FK_IC_EB_OBJECT_ID` FOREIGN KEY (`EB_OBJECT_ID`) REFERENCES `EB_OBJECT` (`EB_OBJECT_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;