
-- Description: sql script in creating ITEM_BUYING_PRICE table.

DROP TABLE IF EXISTS ITEM_BUYING_PRICE;

CREATE TABLE `ITEM_BUYING_PRICE` (
  `ITEM_BUYING_PRICE_ID` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `ITEM_ID` int(10) unsigned NOT NULL,
  `COMPANY_ID` int(10) unsigned NOT NULL,
  `BUYING_PRICE` double  NOT NULL,
  `ACTIVE` tinyint(1) DEFAULT '1',
  PRIMARY KEY (`ITEM_BUYING_PRICE_ID`),
  KEY `FK_IBP_ITEM` (`ITEM_ID`),
  KEY `FK_IBP_COMPANY` (`COMPANY_ID`),
  CONSTRAINT `FK_IBP_ITEM` FOREIGN KEY (`ITEM_ID`) REFERENCES `ITEM` (`ITEM_ID`),
  CONSTRAINT `FK_IBP_COMPANY` FOREIGN KEY (`COMPANY_ID`) REFERENCES `COMPANY` (`COMPANY_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;