
-- Description: sql script in creating ITEM_ADD_ON_TYPE table.

DROP TABLE IF EXISTS ITEM_ADD_ON_TYPE;

CREATE TABLE `ITEM_ADD_ON_TYPE` (
  `ITEM_ADD_ON_TYPE_ID` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `NAME` varchar(20) NOT NULL,
  PRIMARY KEY (`ITEM_ADD_ON_TYPE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;