
-- Description: SQL script in creating ITEM table.

DROP TABLE IF EXISTS ITEM;

CREATE TABLE `ITEM` (
  `ITEM_ID` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `ITEM_CATEGORY_ID` int(10) unsigned NOT NULL,
  `UNIT_MEASUREMENT_ID` int(10) unsigned NOT NULL,
  `STOCK_CODE` varchar(50) NOT NULL,
  `DESCRIPTION` varchar(200) NOT NULL,
  `REORDERING_POINT` int(20) DEFAULT NULL,
  `INITIAL_UNIT_COST` double DEFAULT '0',
  `INITIAL_QUANTITY` double DEFAULT '0',
  `ACTIVE` tinyint(1) DEFAULT '1',
  `CREATED_BY` int(10) unsigned NOT NULL,
  `CREATED_DATE` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_BY` int(10) unsigned NOT NULL,
  `UPDATED_DATE` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  PRIMARY KEY (`ITEM_ID`),
  KEY `FK_ITEM_CATEGORY` (`ITEM_CATEGORY_ID`),
  KEY `FK_ITEM_CREATED_BY` (`CREATED_BY`),
  KEY `FK_ITEM__UPDATED_BY` (`UPDATED_BY`),
  KEY `FK_UNIT_OF_MEASURE` (`UNIT_MEASUREMENT_ID`),
  CONSTRAINT `FK_ITEM_CATEGORY` FOREIGN KEY (`ITEM_CATEGORY_ID`) REFERENCES `ITEM_CATEGORY` (`ITEM_CATEGORY_ID`),
  CONSTRAINT `FK_ITEM_CREATED_BY` FOREIGN KEY (`CREATED_BY`) REFERENCES `USER` (`USER_ID`),
  CONSTRAINT `FK_ITEM_UPDATED_BY` FOREIGN KEY (`UPDATED_BY`) REFERENCES `USER` (`USER_ID`),
  CONSTRAINT `FK_UNIT_OF_MEASURE` FOREIGN KEY (`UNIT_MEASUREMENT_ID`) REFERENCES `UNIT_MEASUREMENT` (`UNITOFMEASUREMENT_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE INDEX INDEX_ITEM on ITEM(STOCK_CODE, DESCRIPTION, UNIT_MEASUREMENT_ID, ITEM_CATEGORY_ID,ACTIVE);