
-- Description: sql script in creating ITEM_BUYING_ADD_ON table.

DROP TABLE IF EXISTS ITEM_BUYING_ADD_ON;

CREATE TABLE `ITEM_BUYING_ADD_ON` (
  `ITEM_BUYING_ADD_ON_ID` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `ITEM_ID` int(10) unsigned NOT NULL,
  `COMPANY_ID` int(10) unsigned NOT NULL,
  `NAME` varchar(50) NOT NULL,
  `VALUE` double  NOT NULL,
  `ACTIVE` tinyint(1) DEFAULT '1',
  PRIMARY KEY (`ITEM_BUYING_ADD_ON_ID`),
  KEY `FK_IBAO_ITEM` (`ITEM_ID`),
  KEY `FK_IBAO_COMPANY` (`COMPANY_ID`),
  CONSTRAINT `FK_IBAO_ITEM` FOREIGN KEY (`ITEM_ID`) REFERENCES `ITEM` (`ITEM_ID`),
  CONSTRAINT `FK_IBAO_COMPANY` FOREIGN KEY (`COMPANY_ID`) REFERENCES `COMPANY` (`COMPANY_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;