
-- Description	: Create table script for ITEM_WEIGHTED_AVERAGE

DROP TABLE IF EXISTS ITEM_WEIGHTED_AVERAGE;

CREATE TABLE ITEM_WEIGHTED_AVERAGE (
	ITEM_WEIGHTED_AVERAGE_ID INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
	WAREHOUSE_ID INT(10) UNSIGNED NOT NULL,
	ITEM_ID INT(10) UNSIGNED NOT NULL,
	QUANTITY DOUBLE DEFAULT 0,
	WEIGHTED_AVERAGE DOUBLE DEFAULT 0,
	CREATED_BY INT(10) UNSIGNED NOT NULL,
	CREATED_DATE TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
	UPDATED_BY INT(10) UNSIGNED NOT NULL,
	UPDATED_DATE TIMESTAMP NOT NULL DEFAULT '0000-00-00 00:00:00',
	PRIMARY KEY (ITEM_WEIGHTED_AVERAGE_ID),
	KEY FK_IWA_WAREHOUSE_ID (WAREHOUSE_ID),
	KEY FK_IWA_ITEM_ID (ITEM_ID),
	KEY FK_IWA_CREATED_BY (CREATED_BY),
	KEY FK_IWA_UPDATED_BY (UPDATED_BY),
	CONSTRAINT FK_IWA_WAREHOUSE_ID FOREIGN KEY (WAREHOUSE_ID) REFERENCES WAREHOUSE (WAREHOUSE_ID),
	CONSTRAINT FK_IWA_ITEM_ID FOREIGN KEY (ITEM_ID) REFERENCES ITEM (ITEM_ID),
	CONSTRAINT FK_IWA_CREATED_BY FOREIGN KEY (CREATED_BY) REFERENCES USER (USER_ID),
	CONSTRAINT FK_IWA_UPDATED_BY FOREIGN KEY (UPDATED_BY) REFERENCES USER (USER_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;