
-- Description: sql script in creating ITEM_ADD_ON table.

DROP TABLE IF EXISTS ITEM_ADD_ON;

CREATE TABLE `ITEM_ADD_ON` (
  `ITEM_ADD_ON_ID` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `ITEM_ADD_ON_TYPE_ID` int(10) unsigned DEFAULT '3',
  `ITEM_ID` int(10) unsigned NOT NULL,
  `COMPANY_ID` int(10) unsigned NOT NULL,
  `NAME` varchar(50) NOT NULL,
  `VALUE` double NOT NULL,
  `ACTIVE` tinyint(1) DEFAULT '1',
  PRIMARY KEY (`ITEM_ADD_ON_ID`),
  KEY `FK_AO_ITEM` (`ITEM_ID`),
  KEY `FK_AO_COMPANY` (`COMPANY_ID`),
  KEY `FK_AO_ADD_ON_TYPE_ID` (`ITEM_ADD_ON_TYPE_ID`),
  CONSTRAINT `FK_AO_ADD_ON_TYPE_ID` FOREIGN KEY (`ITEM_ADD_ON_TYPE_ID`) REFERENCES `ITEM_ADD_ON_TYPE` (`ITEM_ADD_ON_TYPE_ID`),
  CONSTRAINT `FK_AO_COMPANY` FOREIGN KEY (`COMPANY_ID`) REFERENCES `COMPANY` (`COMPANY_ID`),
  CONSTRAINT `FK_AO_ITEM` FOREIGN KEY (`ITEM_ID`) REFERENCES `ITEM` (`ITEM_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;