
-- Description	: Create script for PURCHASE_ORDER_LINE Table.

CREATE TABLE PURCHASE_ORDER_LINE (
	PURCHASE_ORDER_LINE_ID int(10) unsigned NOT NULL AUTO_INCREMENT,
	EB_OBJECT_ID int(10) unsigned DEFAULT NULL,
	R_PURCHASE_ORDER_ID int(10) unsigned NOT NULL,
	AP_LINE_SETUP_ID int(10) unsigned NOT NULL,
	UNITOFMEASUREMENT_ID int(10) unsigned DEFAULT NULL,
	QUANTITY double DEFAULT NULL,
	UP_AMOUNT double DEFAULT NULL,
	AMOUNT double NOT NULL,
	PRIMARY KEY (PURCHASE_ORDER_LINE_ID),
	KEY FK_PO_LINE_EB_OBJECT_ID (EB_OBJECT_ID),
	KEY FK_PO_LINE_PURCHASE_ORDER_ID (R_PURCHASE_ORDER_ID),
	KEY FK_PO_LINE_AP_LINE_SETUP_ID (AP_LINE_SETUP_ID),
	KEY FK_PO_LINE_UNITOFMEASUREMENT_ID (UNITOFMEASUREMENT_ID),
	CONSTRAINT FK_PO_LINE_EB_OBJECT_ID FOREIGN KEY (EB_OBJECT_ID) REFERENCES EB_OBJECT (EB_OBJECT_ID),
	CONSTRAINT FK_PO_LINE_PURCHASE_ORDER_ID FOREIGN KEY (R_PURCHASE_ORDER_ID) REFERENCES R_PURCHASE_ORDER (R_PURCHASE_ORDER_ID),
	CONSTRAINT FK_PO_LINE_AP_LINE_SETUP_ID FOREIGN KEY (AP_LINE_SETUP_ID) REFERENCES AP_LINE_SETUP (AP_LINE_SETUP_ID),
	CONSTRAINT FK_PO_LINE_UNITOFMEASUREMENT_ID FOREIGN KEY (UNITOFMEASUREMENT_ID) REFERENCES UNIT_MEASUREMENT (UNITOFMEASUREMENT_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE utf8_spanish_ci;
