
-- Description: sql script in creating R_PURCHASE_ORDER_ITEM table.

DROP TABLE IF EXISTS R_PURCHASE_ORDER_ITEM;

CREATE TABLE `R_PURCHASE_ORDER_ITEM` (
  `R_PURCHASE_ORDER_ITEM_ID` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `R_PURCHASE_ORDER_ID` int(10) unsigned NOT NULL,
  `ITEM_ID` int(10) unsigned NOT NULL,
  `QUANTITY` double DEFAULT '0',
  `UNIT_COST` double DEFAULT NULL,
  `EB_OBJECT_ID` int(10) unsigned DEFAULT NULL,
  PRIMARY KEY (`R_PURCHASE_ORDER_ITEM_ID`),
  KEY `FK_RPOI_PURCHASE_ORDER_ID` (`R_PURCHASE_ORDER_ID`),
  KEY `FK_RPOI_ITEM_ID` (`ITEM_ID`),
  KEY `FK_RPOI_EB_OBJECT_ID` (`EB_OBJECT_ID`),
  CONSTRAINT `FK_RPOI_EB_OBJECT_ID` FOREIGN KEY (`EB_OBJECT_ID`) REFERENCES `EB_OBJECT` (`EB_OBJECT_ID`),
  CONSTRAINT `FK_RPOI_ITEM_ID` FOREIGN KEY (`ITEM_ID`) REFERENCES `ITEM` (`ITEM_ID`),
  CONSTRAINT `FK_RPOI_PURCHASE_ORDER_ID` FOREIGN KEY (`R_PURCHASE_ORDER_ID`) REFERENCES `R_PURCHASE_ORDER` (`R_PURCHASE_ORDER_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;