
-- Description: sql script in creating R_RECEIVING_REPORT table.

DROP TABLE IF EXISTS R_RECEIVING_REPORT;

CREATE TABLE `R_RECEIVING_REPORT` (
  `R_RECEIVING_REPORT_ID` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `COMPANY_ID` int(10) unsigned NOT NULL,
  `WAREHOUSE_ID` int(10) unsigned NOT NULL,
  `AP_INVOICE_ID` int(10) unsigned DEFAULT NULL,
  `DIVISION_ID` int(10) unsigned DEFAULT NULL,
  `PO_NUMBER` varchar(100) DEFAULT NULL,
  `BMS_NUMBER` varchar(50) DEFAULT NULL,
  `DELIVERY_RECEIPT_NO` varchar(20) NOT NULL,
  `REMARKS` TEXT,
  `CREATED_BY` int(10) unsigned NOT NULL,
  `CREATED_DATE` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_BY` int(10) unsigned NOT NULL,
  `UPDATED_DATE` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  PRIMARY KEY (`R_RECEIVING_REPORT_ID`),
  KEY `FK_RRR_COMPANY_ID` (`COMPANY_ID`),
  KEY `FK_RRR_DIVISION_ID` (`DIVISION_ID`),
  KEY `FK_RRR_CREATED_BY` (`CREATED_BY`),
  KEY `FK_RRR_UPDATED_BY` (`UPDATED_BY`),
  KEY `FK_RRR_AP_INVOICE_ID` (`AP_INVOICE_ID`),
  CONSTRAINT `FK_RRR_AP_INVOICE_ID` FOREIGN KEY (`AP_INVOICE_ID`) REFERENCES `AP_INVOICE` (`AP_INVOICE_ID`),
  CONSTRAINT `FK_RRR_COMPANY_ID` FOREIGN KEY (`COMPANY_ID`) REFERENCES `COMPANY` (`COMPANY_ID`),
  CONSTRAINT `FK_RRR_DIVISION_ID` FOREIGN KEY (`DIVISION_ID`) REFERENCES `DIVISION` (`DIVISION_ID`),
  CONSTRAINT `FK_RRR_CREATED_BY` FOREIGN KEY (`CREATED_BY`) REFERENCES `USER` (`USER_ID`),
  CONSTRAINT `FK_RRR_UPDATED_BY` FOREIGN KEY (`UPDATED_BY`) REFERENCES `USER` (`USER_ID`),
  CONSTRAINT `FK_RRR_WAREHOUSE_ID` FOREIGN KEY (`WAREHOUSE_ID`) REFERENCES `WAREHOUSE` (`WAREHOUSE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;