
-- Description: sql script in creating RETAIL - TRANSFER_RECEIPT_ITEM table.

DROP TABLE IF EXISTS R_TRANSFER_RECEIPT_ITEM;

CREATE TABLE `R_TRANSFER_RECEIPT_ITEM` (
  `R_TRANSFER_RECEIPT_ITEM_ID` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `R_TRANSFER_RECEIPT_ID` int(10) unsigned NOT NULL,
  `EB_OBJECT_ID` int(10) unsigned DEFAULT NULL,
  `ITEM_ID` int(10) unsigned NOT NULL,
  `QUANTITY` double NOT NULL,
  `UNIT_COST` double NOT NULL DEFAULT '0',
  PRIMARY KEY (`R_TRANSFER_RECEIPT_ITEM_ID`),
  KEY `RTRI_RTRANSFER_RECEIPT_ID` (`R_TRANSFER_RECEIPT_ID`),
  KEY `RTRI_ITEM_ID` (`ITEM_ID`),
  KEY `RTRI_EB_OBJECT_ID` (`EB_OBJECT_ID`),
  CONSTRAINT `RTRI_EB_OBJECT_ID` FOREIGN KEY (`EB_OBJECT_ID`) REFERENCES `EB_OBJECT` (`EB_OBJECT_ID`),
  CONSTRAINT `RTRI_ITEM_ID` FOREIGN KEY (`ITEM_ID`) REFERENCES `ITEM` (`ITEM_ID`),
  CONSTRAINT `RTRI_RTRANSFER_RECEIPT_ID` FOREIGN KEY (`R_TRANSFER_RECEIPT_ID`) REFERENCES `R_TRANSFER_RECEIPT` (`R_TRANSFER_RECEIPT_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;