
-- Description: sql script in creating RETAIL - TRANSFER_RECEIPT table.

DROP TABLE IF EXISTS R_TRANSFER_RECEIPT;

CREATE TABLE `R_TRANSFER_RECEIPT` (
  `R_TRANSFER_RECEIPT_ID` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `FORM_WORKFLOW_ID` int(10) unsigned DEFAULT NULL,
  `EB_OBJECT_ID` int(10) unsigned DEFAULT NULL,
  `COMPANY_ID` int(10) unsigned NOT NULL,
  `WAREHOUSE_FROM_ID` int(10) unsigned NOT NULL,
  `TRANSFER_RECEIPT_TYPE_ID` int(10) unsigned DEFAULT NULL,
  `WAREHOUSE_TO_ID` int(10) unsigned NOT NULL,
  `TR_DATE` date NOT NULL,
  `DR_NUMBER` varchar(20) NOT NULL,
  `TR_NUMBER` int(20) NOT NULL,
  `CREATED_BY` int(10) unsigned NOT NULL,
  `CREATED_DATE` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_BY` int(10) unsigned NOT NULL,
  `UPDATED_DATE` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  PRIMARY KEY (`R_TRANSFER_RECEIPT_ID`),
  KEY `FK_RTR_FORM_WORKFLOW_ID` (`FORM_WORKFLOW_ID`),
  KEY `FK_RTR_COMPANY_ID` (`COMPANY_ID`),
  KEY `FK_RTR_FROM_ID` (`WAREHOUSE_FROM_ID`),
  KEY `FK_RTR_TO_ID` (`WAREHOUSE_TO_ID`),
  KEY `FK_RTR_CREATED_BY` (`CREATED_BY`),
  KEY `FK_RTR_UPDATED_BY` (`UPDATED_BY`),
  KEY `FK_RTR_TRANSFER_RECEIPT_TYPE_ID` (`TRANSFER_RECEIPT_TYPE_ID`),
  KEY `FK_RTR_EB_OBJECT_ID` (`EB_OBJECT_ID`),
  CONSTRAINT `FK_RTR_COMPANY_ID` FOREIGN KEY (`COMPANY_ID`) REFERENCES `COMPANY` (`COMPANY_ID`),
  CONSTRAINT `FK_RTR_CREATED_BY` FOREIGN KEY (`CREATED_BY`) REFERENCES `USER` (`USER_ID`),
  CONSTRAINT `FK_RTR_EB_OBJECT_ID` FOREIGN KEY (`EB_OBJECT_ID`) REFERENCES `EB_OBJECT` (`EB_OBJECT_ID`),
  CONSTRAINT `FK_RTR_FORM_WORKFLOW_ID` FOREIGN KEY (`FORM_WORKFLOW_ID`) REFERENCES `FORM_WORKFLOW` (`FORM_WORKFLOW_ID`),
  CONSTRAINT `FK_RTR_FROM_ID` FOREIGN KEY (`WAREHOUSE_FROM_ID`) REFERENCES `WAREHOUSE` (`WAREHOUSE_ID`),
  CONSTRAINT `FK_RTR_TO_ID` FOREIGN KEY (`WAREHOUSE_TO_ID`) REFERENCES `WAREHOUSE` (`WAREHOUSE_ID`),
  CONSTRAINT `FK_RTR_TRANSFER_RECEIPT_TYPE_ID` FOREIGN KEY (`TRANSFER_RECEIPT_TYPE_ID`) REFERENCES `TRANSFER_RECEIPT_TYPE` (`TRANSFER_RECEIPT_TYPE_ID`),
  CONSTRAINT `FK_RTR_UPDATED_BY` FOREIGN KEY (`UPDATED_BY`) REFERENCES `USER` (`USER_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;