
-- Description: sql script in creating REFERENCE_DOCUMENT table.

DROP TABLE IF EXISTS REFERENCE_DOCUMENT;

CREATE TABLE `REFERENCE_DOCUMENT` (
  `REFERENCE_DOCUMENT_ID` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `EB_OBJECT_ID` int(10) unsigned DEFAULT NULL,
  `DESCRIPTION` varchar(100) NOT NULL,
  `FILE_NAME` varchar(200) NOT NULL,
  `FILE_SIZE` double NOT NULL,
  `FILE` mediumblob NOT NULL,
  PRIMARY KEY (`REFERENCE_DOCUMENT_ID`),
  KEY `FK_RD_EB_OBJECT_ID` (`EB_OBJECT_ID`),
  CONSTRAINT `FK_RD_EB_OBJECT_ID` FOREIGN KEY (`EB_OBJECT_ID`)
	REFERENCES `EB_OBJECT` (`EB_OBJECT_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;