
-- Description	: SQL script that will create REPACKING_TYPE table

CREATE TABLE REPACKING_TYPE (
	REPACKING_TYPE_ID int(10) unsigned NOT NULL AUTO_INCREMENT,
	NAME varchar(100) NOT NULL,
	ACTIVE tinyint(1) DEFAULT 0,
	PRIMARY KEY (REPACKING_TYPE_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;