
-- Description	: SQL script in creating REPACKING_RAW_MATERIAL table.

DROP TABLE IF EXISTS REPACKING_RAW_MATERIAL;

CREATE TABLE REPACKING_RAW_MATERIAL (
	REPACKING_RAW_MATERIAL_ID int(10) unsigned NOT NULL AUTO_INCREMENT,
	EB_OBJECT_ID int(10) unsigned DEFAULT NULL,
	REPACKING_ID int(10) unsigned NOT NULL,
	ITEM_ID int(10) unsigned NOT NULL,
	QUANTITY double NOT NULL,
	UNIT_COST double DEFAULT '0',
	PRIMARY KEY (REPACKING_RAW_MATERIAL_ID),
	KEY FK_RRM_EB_OBJECT_ID (EB_OBJECT_ID),
	KEY FK_RRM_REPACKING_ID (REPACKING_ID),
	KEY FK_RRM_ITEM_ID (ITEM_ID),
	CONSTRAINT FK_RRM_EB_OBJECT_ID FOREIGN KEY (EB_OBJECT_ID) REFERENCES EB_OBJECT (EB_OBJECT_ID),
	CONSTRAINT FK_RRM_REPACKING_ID FOREIGN KEY (REPACKING_ID) REFERENCES REPACKING (REPACKING_ID),
	CONSTRAINT FK_RRM_ITEM_ID FOREIGN KEY (ITEM_ID) REFERENCES ITEM (ITEM_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;