
-- Description: sql script in creating REPACKING_ITEM table.

DROP TABLE IF EXISTS REPACKING_ITEM;

CREATE TABLE `REPACKING_ITEM` (
  `REPACKING_ITEM_ID` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `REPACKING_ID` int(10) unsigned NOT NULL,
  `EB_OBJECT_ID` int(10) unsigned DEFAULT NULL,
  `FROM_ITEM_ID` int(10) unsigned NOT NULL,
  `TO_ITEM_ID` int(10) unsigned NOT NULL,
  `QUANTITY` double NOT NULL,
  `UNIT_COST` double NOT NULL DEFAULT '0',
  `REPACKED_QUANTITY` double NOT NULL,
  `REPACKED_UNIT_COST` double NOT NULL DEFAULT '0',
  PRIMARY KEY (`REPACKING_ITEM_ID`),
  KEY `RPI_REPACKING_ID` (`REPACKING_ID`),
  KEY `RPI_FROM_ITEM_ID` (`FROM_ITEM_ID`),
  KEY `RPI_TO_ITEM_ID` (`TO_ITEM_ID`),
  KEY `RPI_EB_OBJECT_ID` (`EB_OBJECT_ID`),
  CONSTRAINT `RPI_FROM_ITEM_ID` FOREIGN KEY (`FROM_ITEM_ID`) REFERENCES `ITEM` (`ITEM_ID`),
  CONSTRAINT `RPI_REPACKING_ID` FOREIGN KEY (`REPACKING_ID`) REFERENCES `REPACKING` (`REPACKING_ID`),
  CONSTRAINT `RPI_TO_ITEM_ID` FOREIGN KEY (`TO_ITEM_ID`) REFERENCES `ITEM` (`ITEM_ID`),
  CONSTRAINT `RPI_EB_OBJECT_ID` FOREIGN KEY (`EB_OBJECT_ID`) REFERENCES `EB_OBJECT` (`EB_OBJECT_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
