
-- Description: SQL script in creating RRI_BAG_QUANTITY table.

DROP TABLE IF EXISTS RRI_BAG_QUANTITY;

CREATE TABLE RRI_BAG_QUANTITY (
  RRI_BAG_QUANTITY_ID int(10) unsigned NOT NULL AUTO_INCREMENT,
  EB_OBJECT_ID int(10) unsigned NOT NULL,
  QUANTITY double DEFAULT '0',
  BAG_QUANTITY double DEFAULT '0',
  NET_WEIGHT double DEFAULT '0',
  ACTIVE tinyint(1) DEFAULT '1',
  CREATED_BY int(10) unsigned NOT NULL,
  CREATED_DATE timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UPDATED_BY int(10) unsigned NOT NULL,
  UPDATED_DATE timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  PRIMARY KEY (RRI_BAG_QUANTITY_ID),
  KEY FK_RRIBQ_EB_OBJECT_ID (EB_OBJECT_ID),
  KEY FK_RRIBQ_CREATED_BY (CREATED_BY),
  KEY FK_RRIBQ_UPDATED_BY (UPDATED_BY),
  CONSTRAINT FK_RRIBQ_EB_OBJECT_ID FOREIGN KEY (EB_OBJECT_ID) REFERENCES EB_OBJECT (EB_OBJECT_ID),
  CONSTRAINT FK_RRIBQ_CREATED_BY FOREIGN KEY (CREATED_BY) REFERENCES USER (USER_ID),
  CONSTRAINT FK_RRIBQ_UPDATED_BY FOREIGN KEY (UPDATED_BY) REFERENCES USER (USER_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;