
-- Description: SQL script in creating RRI_BAG_DISCOUNT table.

DROP TABLE IF EXISTS RRI_BAG_DISCOUNT;

CREATE TABLE RRI_BAG_DISCOUNT (
	RRI_BAG_DISCOUNT_ID INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
	EB_OBJECT_ID INT(10) UNSIGNED NOT NULL,
	BAG_QUANTITY DOUBLE DEFAULT '0',
	DISCOUNT_QUANTITY DOUBLE DEFAULT '0',
	ACTIVE TINYINT(1) DEFAULT '1',
	CREATED_BY INT(10) unsigned NOT NULL,
	CREATED_DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	UPDATED_BY INT(10) unsigned NOT NULL,
	UPDATED_DATE TIMESTAMP NOT NULL DEFAULT '0000-00-00 00:00:00',
	PRIMARY KEY (RRI_BAG_DISCOUNT_ID),
	KEY FK_RRIBD_EB_OBJECT_ID (EB_OBJECT_ID),
	KEY FK_RRIBD_CREATED_BY (CREATED_BY),
	KEY FK_RRIBD_UPDATED_BY (UPDATED_BY),
	CONSTRAINT FK_RRIBD_EB_OBJECT_ID FOREIGN KEY (EB_OBJECT_ID) REFERENCES EB_OBJECT (EB_OBJECT_ID),
	CONSTRAINT FK_RRIBD_CREATED_BY FOREIGN KEY (CREATED_BY) REFERENCES USER (USER_ID),
	CONSTRAINT FK_RRIBD_UPDATED_BY FOREIGN KEY (UPDATED_BY) REFERENCES USER (USER_ID)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;