
-- Description: Create script for SERIAL_ITEM table.

DROP TABLE IF EXISTS `SERIAL_ITEM`;

CREATE TABLE `SERIAL_ITEM` (
  `SERIAL_ITEM_ID` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `EB_OBJECT_ID` int(10) unsigned DEFAULT NULL,
  `ITEM_ID` int(10) unsigned NOT NULL,
  `QUANTITY` double DEFAULT '1',
  `ITEM_SRP_ID` int(10) unsigned DEFAULT NULL,
  `SRP` double DEFAULT NULL,
  `UNIT_COST` double NOT NULL,
  `DISCOUNT` double DEFAULT 0,
  `ITEM_DISCOUNT_ID` int(10) unsigned DEFAULT NULL,
  `ITEM_ADD_ON_ID` int(10) unsigned DEFAULT NULL,
  `AMOUNT` double DEFAULT NULL,
  `WAREHOUSE_ID` int(10) unsigned NOT NULL,
  `SERIAL_NUMBER` varchar(50) NOT NULL,
  `ACTIVE` tinyint(1) NOT NULL,
  `CREATED_BY` int(10) unsigned NOT NULL,
  `CREATED_DATE` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_BY` int(10) unsigned NOT NULL,
  `UPDATED_DATE` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  PRIMARY KEY (`SERIAL_ITEM_ID`),
  KEY `FK_SI_EB_OBJECT_ID` (`EB_OBJECT_ID`),
  KEY `FK_SI_ITEM_ID` (`ITEM_ID`),
  KEY `FK_SI_CREATED_BY` (`CREATED_BY`),
  KEY `FK_SI_UPDATED_BY` (`UPDATED_BY`),
  KEY `FK_SI_WAREHOUSE_ID` (`WAREHOUSE_ID`),
  KEY `FK_SI_SRP_ID` (ITEM_SRP_ID),
  KEY `FK_SI_DISCOUNT_ID` (ITEM_DISCOUNT_ID),
  KEY `FK_SI_ADD_ON_ID` (ITEM_ADD_ON_ID),
  CONSTRAINT `FK_SI_EB_OBJECT_ID` FOREIGN KEY (`EB_OBJECT_ID`) REFERENCES `EB_OBJECT` (`EB_OBJECT_ID`),
  CONSTRAINT `FK_SI_ITEM_ID` FOREIGN KEY (`ITEM_ID`) REFERENCES `ITEM` (`ITEM_ID`),
  CONSTRAINT `FK_SI_CREATED_BY` FOREIGN KEY (`CREATED_BY`) REFERENCES `USER` (`USER_ID`),
  CONSTRAINT `FK_SI_WAREHOUSE_ID` FOREIGN KEY (`WAREHOUSE_ID`) REFERENCES `WAREHOUSE` (`WAREHOUSE_ID`),
  CONSTRAINT `FK_SI_SRP_ID` FOREIGN KEY (`ITEM_SRP_ID`) REFERENCES ITEM_SRP (`ITEM_SRP_ID`),
  CONSTRAINT `FK_SI_DISCOUNT_ID` FOREIGN KEY (ITEM_DISCOUNT_ID) REFERENCES ITEM_DISCOUNT (ITEM_DISCOUNT_ID),
  CONSTRAINT `FK_SI_ADD_ON_ID` FOREIGN KEY (`ITEM_ADD_ON_ID`) REFERENCES ITEM_ADD_ON (`ITEM_ADD_ON_ID`),
  CONSTRAINT `FK_SI_UPDATED_BY` FOREIGN KEY (`UPDATED_BY`) REFERENCES `USER` (`USER_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;