
-- Description: sql script in creating STOCK_ADJUSTMENT table.

DROP TABLE IF EXISTS STOCK_ADJUSTMENT;

CREATE TABLE `STOCK_ADJUSTMENT` (
  `STOCK_ADJUSTMENT_ID` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `STOCK_ADJUSTMENT_CLASSIFICATION_ID` int(10) unsigned DEFAULT NULL,
  `FORM_WORKFLOW_ID` int(10) unsigned DEFAULT NULL,
  `EB_OBJECT_ID` int(10) unsigned DEFAULT NULL,
  `COMPANY_ID` int(10) unsigned NOT NULL,
  `WAREHOUSE_ID` int(10) unsigned NOT NULL,
  `STOCK_ADJUSTMENT_TYPE_ID` int(10) unsigned NOT NULL,
  `SA_NUMBER` int(20) NOT NULL,
  `SA_DATE` date NOT NULL,
  `REMARKS` text,
  `CREATED_BY` int(10) unsigned NOT NULL,
  `CREATED_DATE` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_BY` int(10) unsigned NOT NULL,
  `UPDATED_DATE` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  PRIMARY KEY (`STOCK_ADJUSTMENT_ID`),
  KEY `FK_SA_FORM_WORKFLOW_ID` (`FORM_WORKFLOW_ID`),
  KEY `FK_SA_COMPANY_ID` (`COMPANY_ID`),
  KEY `FK_SA_WAREHOUSE_ID` (`WAREHOUSE_ID`),
  KEY `FK_SA_CREATED_BY` (`CREATED_BY`),
  KEY `FK_SA_UPDATED_BY` (`UPDATED_BY`),
  KEY `FK_SA_STOCK_ADJUSTMENT_CLASSIFICATION_ID` (`STOCK_ADJUSTMENT_CLASSIFICATION_ID`),
  CONSTRAINT `FK_SA_COMPANY_ID` FOREIGN KEY (`COMPANY_ID`) REFERENCES `COMPANY` (`COMPANY_ID`),
  CONSTRAINT `FK_SA_CREATED_BY` FOREIGN KEY (`CREATED_BY`) REFERENCES `USER` (`USER_ID`),
  CONSTRAINT `FK_SA_FORM_WORKFLOW_ID` FOREIGN KEY (`FORM_WORKFLOW_ID`) REFERENCES `FORM_WORKFLOW` (`FORM_WORKFLOW_ID`),
  CONSTRAINT `FK_SA_EB_OBJECT_ID` FOREIGN KEY (`EB_OBJECT_ID`) REFERENCES `EB_OBJECT` (`EB_OBJECT_ID`),
  CONSTRAINT `FK_SA_UPDATED_BY` FOREIGN KEY (`UPDATED_BY`) REFERENCES `USER` (`USER_ID`),
  CONSTRAINT `FK_SA_WAREHOUSE_ID` FOREIGN KEY (`WAREHOUSE_ID`) REFERENCES `WAREHOUSE` (`WAREHOUSE_ID`),
  CONSTRAINT `FK_SA_STOCK_ADJUSTMENT_CLASSIFICATION_ID` FOREIGN KEY (`STOCK_ADJUSTMENT_CLASSIFICATION_ID`)
    REFERENCES `STOCK_ADJUSTMENT_CLASSIFICATION` (`STOCK_ADJUSTMENT_CLASSIFICATION_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
