
-- Description: sql script in creating STOCK_ADJUSTMENT_CLASSIFICATION table

DROP TABLE IF EXISTS STOCK_ADJUSTMENT_CLASSIFICATION;

CREATE TABLE STOCK_ADJUSTMENT_CLASSIFICATION (
 STOCK_ADJUSTMENT_CLASSIFICATION_ID int(10) unsigned NOT NULL AUTO_INCREMENT,
 NAME varchar(100) NOT NULL,
 ACTIVE tinyint(1) NOT NULL,
 CREATED_BY int(10) unsigned NOT NULL,
 CREATED_DATE timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
 UPDATED_BY int(10) unsigned NOT NULL,
 UPDATED_DATE timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
 PRIMARY KEY (STOCK_ADJUSTMENT_CLASSIFICATION_ID),
 KEY FK_SAC_CREATED_BY (CREATED_BY),
 KEY FK_SAC_UPDATED_BY (UPDATED_BY),
 CONSTRAINT FK_SAC_CREATED_BY FOREIGN KEY (CREATED_BY) REFERENCES USER (USER_ID),
 CONSTRAINT FK_SAC_UPDATED_BY FOREIGN KEY (UPDATED_BY) REFERENCES USER (USER_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
