
-- Description: sql script in creating STOCK_ADJUSTMENT_TYPE table.

DROP TABLE IF EXISTS STOCK_ADJUSTMENT_TYPE;

CREATE TABLE `STOCK_ADJUSTMENT_TYPE` (
  `STOCK_ADJUSTMENT_TYPE_ID` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `ACCOUNT_COMBINATION_ID` int(10) unsigned DEFAULT NULL,
  `NAME` varchar(100) NOT NULL,
  `ACTIVE` tinyint(1) NOT NULL,
  `CREATED_BY` int(10) unsigned NOT NULL,
  `CREATED_DATE` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_BY` int(10) unsigned NOT NULL,
  `UPDATED_DATE` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  PRIMARY KEY (`STOCK_ADJUSTMENT_TYPE_ID`),
  KEY `FK_SAT_CREATED_BY` (`CREATED_BY`),
  KEY `FK_SAT_UPDATED_BY` (`UPDATED_BY`),
  KEY `FK_SAT_ACCOUNT_COMBI_ID` (`ACCOUNT_COMBINATION_ID`),
  CONSTRAINT `FK_SAT_ACCOUNT_COMBI_ID` FOREIGN KEY (`ACCOUNT_COMBINATION_ID`) REFERENCES `ACCOUNT_COMBINATION` (`ACCOUNT_COMBINATION_ID`),
  CONSTRAINT `FK_SAT_CREATED_BY` FOREIGN KEY (`CREATED_BY`) REFERENCES `USER` (`USER_ID`),
  CONSTRAINT `FK_SAT_UPDATED_BY` FOREIGN KEY (`UPDATED_BY`) REFERENCES `USER` (`USER_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;