
-- Description: sql script in creating STOCK_ADJUSTMENT_ITEM table.

DROP TABLE IF EXISTS STOCK_ADJUSTMENT_ITEM;

CREATE TABLE `STOCK_ADJUSTMENT_ITEM` (
  `STOCK_ADJUSTMENT_ITEM_ID` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `STOCK_ADJUSTMENT_ID` int(10) unsigned NOT NULL,
  `PO_NUMBER` varchar(20) DEFAULT NULL,
  `EB_OBJECT_ID` int(10) unsigned DEFAULT NULL,
  `ITEM_ID` int(10) unsigned NOT NULL,
  `QUANTITY` double NOT NULL,
  `UNIT_COST` double NOT NULL,
  PRIMARY KEY (`STOCK_ADJUSTMENT_ITEM_ID`),
  KEY `SAI_STOCK_ADJUSTMENT_ID` (`STOCK_ADJUSTMENT_ID`),
  KEY `SAI_ITEM_ID` (`ITEM_ID`),
  CONSTRAINT `SAI_ITEM_ID` FOREIGN KEY (`ITEM_ID`) REFERENCES `ITEM` (`ITEM_ID`),
  CONSTRAINT `SAI_STOCK_ADJUSTMENT_ID` FOREIGN KEY (`STOCK_ADJUSTMENT_ID`) REFERENCES `STOCK_ADJUSTMENT` (`STOCK_ADJUSTMENT_ID`),
  CONSTRAINT `SAI_EB_OBJECT_ID` FOREIGN KEY (`EB_OBJECT_ID`) REFERENCES `EB_OBJECT` (`EB_OBJECT_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;