
-- Description: sql script in creating TRANSFER_RECEIPT_TYPE table

DROP TABLE IF EXISTS TRANSFER_RECEIPT_TYPE;

CREATE TABLE TRANSFER_RECEIPT_TYPE (
 TRANSFER_RECEIPT_TYPE_ID int(10) unsigned NOT NULL AUTO_INCREMENT,
 NAME varchar(20) NOT NULL,
 ACTIVE tinyint(1) NOT NULL,
 CREATED_BY int(10) unsigned NOT NULL,
 CREATED_DATE timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
 UPDATED_BY int(10) unsigned NOT NULL,
 UPDATED_DATE timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
 PRIMARY KEY (TRANSFER_RECEIPT_TYPE_ID),
 KEY FK_TR_TYPE_CREATED_BY (CREATED_BY),
 KEY FK_TR_TYPE_UPDATED_BY (UPDATED_BY),
 CONSTRAINT FK_TR_TYPE_CREATED_BY FOREIGN KEY (CREATED_BY) REFERENCES USER (USER_ID),
 CONSTRAINT FK_TR_TYPE_UPDATED_BY FOREIGN KEY (UPDATED_BY) REFERENCES USER (USER_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;