
-- Description: SQL script in creating UNIT_MEASUREMENT table.

DROP TABLE IF EXISTS UNIT_MEASUREMENT;

CREATE TABLE `UNIT_MEASUREMENT` (
  `UNITOFMEASUREMENT_ID` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `NAME` varchar(20) NOT NULL,
  `ACTIVE` tinyint(1) NOT NULL,
  PRIMARY KEY (`UNITOFMEASUREMENT_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;