
-- Description: sql script in creating WAREHOUSE table.

DROP TABLE IF EXISTS WAREHOUSE;

CREATE TABLE WAREHOUSE (
	WAREHOUSE_ID int(10) unsigned NOT NULL AUTO_INCREMENT,
	COMPANY_ID int(10) unsigned NOT NULL,
	EB_OBJECT_ID int(10) unsigned DEFAULT NULL,
	NAME varchar(30) NOT NULL,
	ADDRESS varchar(50),
	ACTIVE tinyint(1) DEFAULT 1,
	CREATED_BY int(10) unsigned NOT NULL,
	CREATED_DATE timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
	UPDATED_BY int(10) unsigned NOT NULL,
	UPDATED_DATE timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
	PRIMARY KEY (WAREHOUSE_ID),
	KEY FK_WAREHOUSE_EB_OBJECT_ID (EB_OBJECT_ID),
	KEY FK_WAREHOUSE_CREATED_BY (CREATED_BY),
	KEY FK_WAREHOUSE_UPDATED_BY (UPDATED_BY),
	CONSTRAINT FK_WAREHOUSE_EB_OBJECT_ID FOREIGN KEY (EB_OBJECT_ID) REFERENCES EB_OBJECT (EB_OBJECT_ID),
	CONSTRAINT FK_WAREHOUSE_CREATED_BY FOREIGN KEY (CREATED_BY) REFERENCES USER (USER_ID),
	CONSTRAINT FK_WAREHOUSE_UPDATED_BY FOREIGN KEY (UPDATED_BY) REFERENCES USER (USER_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;