
-- Description: Sql script for creating WIP_SPECIAL_ORDER table

DROP TABLE IF EXISTS WIP_SPECIAL_ORDER;

CREATE TABLE `WIP_SPECIAL_ORDER` (
  `WIP_SPECIAL_ORDER_ID` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `AR_TRANSACTION_ID` int(10) unsigned NOT NULL,
  `COMPANY_ID` int(10) unsigned NOT NULL,
  `FORM_WORKFLOW_ID` int(10) unsigned DEFAULT NULL,
  `SEQUENCE_NUMBER` int(20) unsigned NOT NULL,
  `EB_OBJECT_ID` int(10) unsigned NOT NULL,
  `CREATED_BY` int(10) unsigned NOT NULL,
  `CREATED_DATE` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_BY` int(10) unsigned NOT NULL,
  `UPDATED_DATE` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  PRIMARY KEY (`WIP_SPECIAL_ORDER_ID`),
  KEY `FK_WIP_SO_SALE_ORDER_ID` (`AR_TRANSACTION_ID`),
  KEY `FK_WIP_SO_COMPANY_ID` (`COMPANY_ID`),
  KEY `FK_WIP_SO_FORM_WORKFLOW_ID` (`FORM_WORKFLOW_ID`),
  KEY `FK_WIP_SO_EB_OBJECT_ID` (`EB_OBJECT_ID`),
  KEY `FK_WIP_SO_CREATED_BY` (`CREATED_BY`),
  KEY `FK_WIP_SO_UPDATED_BY` (`UPDATED_BY`),
  CONSTRAINT `FK_WIP_AR_TRANSACTION_ID` FOREIGN KEY (`AR_TRANSACTION_ID`) REFERENCES `AR_TRANSACTION` (`AR_TRANSACTION_ID`),
  CONSTRAINT `FK_WIP_SO_COMPANY_ID` FOREIGN KEY (`COMPANY_ID`) REFERENCES `COMPANY` (`COMPANY_ID`),
  CONSTRAINT `FK_WIP_SO_CREATED_BY` FOREIGN KEY (`CREATED_BY`) REFERENCES `USER` (`USER_ID`),
  CONSTRAINT `FK_WIP_SO_EB_OBJECT_ID` FOREIGN KEY (`EB_OBJECT_ID`) REFERENCES `EB_OBJECT` (`EB_OBJECT_ID`),
  CONSTRAINT `FK_WIP_SO_FORM_WORKFLOW_ID` FOREIGN KEY (`FORM_WORKFLOW_ID`) REFERENCES `FORM_WORKFLOW` (`FORM_WORKFLOW_ID`),
  CONSTRAINT `FK_WIP_SO_UPDATED_BY` FOREIGN KEY (`UPDATED_BY`) REFERENCES `USER` (`USER_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;