
-- Description: sql script in creating WIPSO_OTHER_CHARGE table.

DROP TABLE IF EXISTS WIPSO_OTHER_CHARGE;

CREATE TABLE WIPSO_OTHER_CHARGE (
  WIPSO_OTHER_CHARGE_ID int(10) unsigned NOT NULL AUTO_INCREMENT,
  WIP_SPECIAL_ORDER_ID int(10) unsigned NOT NULL,
  AR_LINE_SETUP_ID int(10) unsigned NOT NULL,
  EB_OBJECT_ID int(10) unsigned DEFAULT NULL,
  QUANTITY double DEFAULT '0',
  UNITOFMEASUREMENT_ID int(10) unsigned DEFAULT NULL,
  UP_AMOUNT double DEFAULT '0',
  AMOUNT double DEFAULT '0',
  PRIMARY KEY (WIPSO_OTHER_CHARGE_ID),
  KEY FK_WIP_AL_LINE_PR_ID (WIP_SPECIAL_ORDER_ID),
  KEY FK_WIP_LINE_SETUP_ID (AR_LINE_SETUP_ID),
  KEY FK_WIP_LINE_EB_OBJECT_ID (EB_OBJECT_ID),
  CONSTRAINT FK_WIP_LINE_PR_ID FOREIGN KEY (WIP_SPECIAL_ORDER_ID) REFERENCES WIP_SPECIAL_ORDER (WIP_SPECIAL_ORDER_ID),
  CONSTRAINT FK_WIP_LINE_SETUP_ID FOREIGN KEY (AR_LINE_SETUP_ID) REFERENCES AR_LINE_SETUP (AR_LINE_SETUP_ID),
  CONSTRAINT FK_WIP_LINE_EB_OBJECT_ID FOREIGN KEY (EB_OBJECT_ID) REFERENCES EB_OBJECT (EB_OBJECT_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;