
-- Description: sql script in creating WIPSO_FINISHED_PRODUCT table.

DROP TABLE IF EXISTS WIPSO_FINISHED_PRODUCT;

CREATE TABLE WIPSO_FINISHED_PRODUCT (
 WIPSO_FINISHED_PRODUCT_ID int(10) unsigned NOT NULL AUTO_INCREMENT,
 WIP_SPECIAL_ORDER_ID int(10) unsigned NOT NULL,
 WAREHOUSE_ID int(10) unsigned NOT NULL,
 ITEM_ID int(10) unsigned NOT NULL,
 EB_OBJECT_ID int(10) unsigned DEFAULT NULL,
 QUANTITY double NOT NULL,
 UNIT_COST double DEFAULT '0',
 PRIMARY KEY (WIPSO_FINISHED_PRODUCT_ID),
 KEY FK_WIP_FP_SPECIAL_ORDER_ID (WIP_SPECIAL_ORDER_ID),
 KEY FK_WIP_FP_WAREHOUSE_ID (WAREHOUSE_ID),
 KEY FK_WIP_FP_ITEM_ID (ITEM_ID),
 KEY FK_WIP_FP_EB_OBJECT_ID (EB_OBJECT_ID),
 CONSTRAINT FK_WIP_FP_SPECIAL_ORDER_ID FOREIGN KEY (WIP_SPECIAL_ORDER_ID) REFERENCES WIP_SPECIAL_ORDER (WIP_SPECIAL_ORDER_ID),
 CONSTRAINT FK_WIP_FP_WAREHOUSE_ID FOREIGN KEY (WAREHOUSE_ID) REFERENCES WAREHOUSE (WAREHOUSE_ID),
 CONSTRAINT FK_WIP_FP_ITEM_ID FOREIGN KEY (ITEM_ID) REFERENCES ITEM (ITEM_ID),
 CONSTRAINT FK_WIP_FP_EB_OBJECT_ID FOREIGN KEY (EB_OBJECT_ID) REFERENCES EB_OBJECT (EB_OBJECT_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;