
-- Description: Sql script for creating WITHDRAWAL_SLIP_ITEM table

DROP TABLE IF EXISTS `WITHDRAWAL_SLIP_ITEM`;

CREATE TABLE `WITHDRAWAL_SLIP_ITEM` (
  `WITHDRAWAL_SLIP_ITEM_ID` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `ITEM_ID` int(10) unsigned NOT NULL,
  `QUANTITY` double NOT NULL,
  `UNIT_COST` double NOT NULL,
  `ACTIVE` tinyint(1) NOT NULL,
  `EB_OBJECT_ID` int(10) unsigned DEFAULT NULL,
  `CREATED_BY` int(10) unsigned NOT NULL,
  `CREATED_DATE` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_BY` int(10) unsigned NOT NULL,
  `UPDATED_DATE` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  PRIMARY KEY (`WITHDRAWAL_SLIP_ITEM_ID`),
  KEY `FK_WITHDRAWAL_SLIP_ITEM_EB_OBJECT_ID` (`EB_OBJECT_ID`),
  KEY `FK_WITHDRAWAL_SLIP_ITEM_ID` (`ITEM_ID`),
  KEY `FK_WITHDRAWAL_SLIP_ITEM_CREATED_BY` (`CREATED_BY`),
  KEY `FK_WITHDRAWAL_SLIP_ITEM_UPDATED_BY` (`UPDATED_BY`),
  CONSTRAINT `FK_WITHDRAWAL_SLIP_ITEM_EB_OBJECT_ID` FOREIGN KEY (EB_OBJECT_ID) REFERENCES EB_OBJECT (EB_OBJECT_ID),
  CONSTRAINT `FK_WITHDRAWAL_SLIP_ITEM_ID` FOREIGN KEY (`ITEM_ID`) REFERENCES `ITEM` (`ITEM_ID`),
  CONSTRAINT `FK_WITHDRAWAL_SLIP_ITEM_CREATED_BY` FOREIGN KEY (`CREATED_BY`) REFERENCES `USER` (`USER_ID`),
  CONSTRAINT `FK_WITHDRAWAL_SLIP_ITEM_UPDATED_BY` FOREIGN KEY (`UPDATED_BY`) REFERENCES `USER` (`USER_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;