
-- Description: Sql script for creating WITHDRAWAL_SLIP table

DROP TABLE IF EXISTS WITHDRAWAL_SLIP;

CREATE TABLE `WITHDRAWAL_SLIP` (
  `WITHDRAWAL_SLIP_ID` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `FORM_WORKFLOW_ID` int(10) unsigned DEFAULT NULL,
  `EB_OBJECT_ID` int(10) unsigned DEFAULT NULL,
  `PO_NUMBER` varchar(20) NOT NULL,
  `REMARKS` text NOT NULL,
  `DATE` DATE NOT NULL,
  `WS_NUMBER` int(20) unsigned DEFAULT NULL,
  `REQUESTER_NAME` VARCHAR(100) DEFAULT NULL,
  `CREATED_BY` int(10) unsigned NOT NULL,
  `CREATED_DATE` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_BY` int(10) unsigned NOT NULL,
  `UPDATED_DATE` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  PRIMARY KEY (`WITHDRAWAL_SLIP_ID`),
  KEY `FK_WITHDRAWAL_SLIP_FORM_WORKFLOW_ID` (`FORM_WORKFLOW_ID`),
  KEY `FK_WITHDRAWAL_SLIP_EB_OBJECT_ID` (`EB_OBJECT_ID`),
  KEY `FK_WITHDRAWAL_SLIP_CREATED_BY` (`CREATED_BY`),
  KEY `FK_WITHDRAWAL_SLIP_UPDATED_BY` (`UPDATED_BY`),
  CONSTRAINT `FK_WITHDRAWAL_SLIP_FORM_WORKFLOW_ID` FOREIGN KEY (FORM_WORKFLOW_ID) REFERENCES FORM_WORKFLOW (FORM_WORKFLOW_ID),
  CONSTRAINT `FK_WITHDRAWAL_SLIP_EB_OBJECT_ID` FOREIGN KEY (EB_OBJECT_ID) REFERENCES EB_OBJECT (EB_OBJECT_ID),
  CONSTRAINT `FK_WITHDRAWAL_SLIP_CREATED_BY` FOREIGN KEY (`CREATED_BY`) REFERENCES `USER` (`USER_ID`),
  CONSTRAINT `FK_WITHDRAWAL_SLIP_UPDATED_BY` FOREIGN KEY (`UPDATED_BY`) REFERENCES `USER` (`USER_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
