
-- Description: Sql script for creating AC_AR_LINE table

DROP TABLE IF EXISTS AC_AR_LINE;

CREATE TABLE AC_AR_LINE (
  AC_AR_LINE_ID int(10) unsigned NOT NULL AUTO_INCREMENT,
  EB_OBJECT_ID INT(10) UNSIGNED DEFAULT NULL,
  AR_RECEIPT_ID int(10) unsigned NOT NULL,
  AR_LINE_SETUP_ID int(10) unsigned NOT NULL,
  QUANTITY double DEFAULT '0',
  UNITOFMEASUREMENT_ID int(10) unsigned DEFAULT NULL,
  UP_AMOUNT double DEFAULT '0',
  AMOUNT double DEFAULT '0',
  PRIMARY KEY (AC_AR_LINE_ID),
  KEY FK_AC_AL_AR_RECEIPT_ID (AR_RECEIPT_ID),
  KEY FK_AC_AL_AR_LINE_SETUP_ID (AR_LINE_SETUP_ID),
  KEY FK_AC_AR_LINE_EB_OBJECT_ID (EB_OBJECT_ID),
  CONSTRAINT FK_AC_AL_AR_LINE_SETUP_ID
   FOREIGN KEY (AR_LINE_SETUP_ID)
   REFERENCES AR_LINE_SETUP (AR_LINE_SETUP_ID),
  CONSTRAINT FK_AC_AL_AR_RECEIPT_ID
   FOREIGN KEY (AR_RECEIPT_ID)
   REFERENCES AR_RECEIPT (AR_RECEIPT_ID),
  CONSTRAINT FK_AC_AR_LINE_EB_OBJECT_ID
   FOREIGN KEY (EB_OBJECT_ID)
   REFERENCES EB_OBJECT (EB_OBJECT_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;