
-- Description: sql script in creating ACCOUNT_TYPE table.

DROP TABLE IF EXISTS ACCOUNT_TYPE;

CREATE TABLE `ACCOUNT_TYPE` (
  `ACCOUNT_TYPE_ID` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `NAME` varchar(100) NOT NULL,
  `NORMAL_BALANCE_ID` int(10) unsigned NOT NULL,
  `EB_SL_KEY_ID` int(10) unsigned NOT NULL DEFAULT '1',
  `CONTRA_ACCOUNT` tinyint(1) NOT NULL,
  `ACTIVE` tinyint(1) NOT NULL,
  `CREATED_BY` int(10) unsigned NOT NULL,
  `CREATED_DATE` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_BY` int(10) unsigned NOT NULL,
  `UPDATED_DATE` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  PRIMARY KEY (`ACCOUNT_TYPE_ID`),
  KEY `FK_ACCOUNT_TYPE_NORMAL_BALANCE` (`NORMAL_BALANCE_ID`),
  KEY `FK_ACCOUNT_TYPE_CREATED_BY` (`CREATED_BY`),
  KEY `FK_ACCOUNT_TYPE_UPDATED_BY` (`UPDATED_BY`),
  KEY `FK_ACCOUNT_TYPE_EB_SL_KEY` (`EB_SL_KEY_ID`),
  CONSTRAINT `FK_ACCOUNT_TYPE_CREATED_BY` FOREIGN KEY (`CREATED_BY`) REFERENCES `USER` (`USER_ID`),
  CONSTRAINT `FK_ACCOUNT_TYPE_EB_SL_KEY` FOREIGN KEY (`EB_SL_KEY_ID`) REFERENCES `EB_SL_KEY` (`EB_SL_KEY_ID`),
  CONSTRAINT `FK_ACCOUNT_TYPE_NORMAL_BALANCE` FOREIGN KEY (`NORMAL_BALANCE_ID`) REFERENCES `NORMAL_BALANCE` (`NORMAL_BALANCE_ID`),
  CONSTRAINT `FK_ACCOUNT_TYPE_UPDATED_BY` FOREIGN KEY (`UPDATED_BY`) REFERENCES `USER` (`USER_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;