
-- Description: sql script in creating ACCOUNT_COMBINATION table.

DROP TABLE IF EXISTS ACCOUNT_COMBINATION;

CREATE TABLE `ACCOUNT_COMBINATION` (
  `ACCOUNT_COMBINATION_ID` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `COMPANY_ID` int(10) unsigned NOT NULL,
  `ACCOUNT_ID` int(10) unsigned NOT NULL,
  `DIVISION_ID` int(10) unsigned NOT NULL,
  `ACTIVE` tinyint(1) NOT NULL,
  `CREATED_BY` int(10) unsigned NOT NULL,
  `CREATED_DATE` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_BY` int(10) unsigned NOT NULL,
  `UPDATED_DATE` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  `EB_SL_KEY_ID` int(10) unsigned NOT NULL DEFAULT '1',
  PRIMARY KEY (`ACCOUNT_COMBINATION_ID`),
  KEY `FK_ACCOUNT_COMBINATION_COMPANY` (`COMPANY_ID`),
  KEY `FK_ACCOUNT_COMBINATION_ACCOUNT` (`ACCOUNT_ID`),
  KEY `FK_ACCOUNT_COMBINATION_DIVISION` (`DIVISION_ID`),
  KEY `FK_ACCOUNT_COMBINATION_CREATED_BY` (`CREATED_BY`),
  KEY `FK_ACCOUNT_COMBINATION_UPDATED_BY` (`UPDATED_BY`),
  KEY `EB_SL_KEY_ID` (`EB_SL_KEY_ID`),
  CONSTRAINT `ACCOUNT_COMBINATION_ibfk_1` FOREIGN KEY (`EB_SL_KEY_ID`) REFERENCES `EB_SL_KEY` (`EB_SL_KEY_ID`),
  CONSTRAINT `FK_ACCOUNT_COMBINATION_ACCOUNT` FOREIGN KEY (`ACCOUNT_ID`) REFERENCES `ACCOUNT` (`ACCOUNT_ID`),
  CONSTRAINT `FK_ACCOUNT_COMBINATION_COMPANY` FOREIGN KEY (`COMPANY_ID`) REFERENCES `COMPANY` (`COMPANY_ID`),
  CONSTRAINT `FK_ACCOUNT_COMBINATION_CREATED_BY` FOREIGN KEY (`CREATED_BY`) REFERENCES `USER` (`USER_ID`),
  CONSTRAINT `FK_ACCOUNT_COMBINATION_DIVISION` FOREIGN KEY (`DIVISION_ID`) REFERENCES `DIVISION` (`DIVISION_ID`),
  CONSTRAINT `FK_ACCOUNT_COMBINATION_UPDATED_BY` FOREIGN KEY (`UPDATED_BY`) REFERENCES `USER` (`USER_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;