
-- Description: SQL script in creating CHL_AP_INVOICE table

DROP TABLE IF EXISTS AP_INVOICE_WT;

CREATE TABLE AP_INVOICE_WT (
  AP_INVOICE_WT_ID int(10) unsigned NOT NULL AUTO_INCREMENT,
  AP_INVOICE_ID int(10) unsigned NOT NULL,
  WT_ACCOUNT_SETTING_ID int(10) unsigned NOT NULL,
  WT_AMOUNT double DEFAULT '0.0',
  PRIMARY KEY (AP_INVOICE_WT_ID),
  KEY FK_AIWT_AP_INVOICE_ID (AP_INVOICE_ID),
  KEY FK_AIWT_WT_ACCOUNT_SETTING_ID (WT_ACCOUNT_SETTING_ID),
  CONSTRAINT FK_AIWT_AP_INVOICE_ID FOREIGN KEY (AP_INVOICE_ID) REFERENCES AP_INVOICE (AP_INVOICE_ID),
  CONSTRAINT FK_AIWT_WT_ACCOUNT_SETTING_ID FOREIGN KEY (WT_ACCOUNT_SETTING_ID) REFERENCES WT_ACCOUNT_SETTING (WT_ACCOUNT_SETTING_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;