
-- Description	: SQL to create AP_INVOICE_GOODS table.

DROP TABLE IF EXISTS AP_INVOICE_GOODS;

CREATE TABLE AP_INVOICE_GOODS (
	AP_INVOICE_GOODS_ID INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
	AP_INVOICE_ID INT(10) UNSIGNED DEFAULT NULL,
	EB_OBJECT_ID INT(10) UNSIGNED DEFAULT NULL,
	ITEM_ID INT(10) UNSIGNED NOT NULL,
	QUANTITY DOUBLE NOT NULL,
	UNIT_COST DOUBLE NOT NULL,
	TAX_TYPE_ID INT(10) UNSIGNED DEFAULT NULL,
	VAT_AMOUNT DOUBLE DEFAULT '0',
	ITEM_DISCOUNT_TYPE_ID INT(10) UNSIGNED DEFAULT NULL,
	DISCOUNT_VALUE DOUBLE UNSIGNED DEFAULT NULL,
	DISCOUNT DOUBLE UNSIGNED DEFAULT NULL,
	PRIMARY KEY (AP_INVOICE_GOODS_ID),
	KEY FK_APIG_ITEM_ID (ITEM_ID),
	KEY FK_APIG_AP_INVOICE_ID (AP_INVOICE_ID),
	KEY FK_APIG_EB_OBJECT_ID (EB_OBJECT_ID),
	KEY FK_APIG_TAX_TYPE_ID (TAX_TYPE_ID),
	KEY FK_APIG_ITEM_DISCOUNT_TYPE_ID (ITEM_DISCOUNT_TYPE_ID),
	CONSTRAINT FK_APIG_AP_INVOICE_ID FOREIGN KEY (AP_INVOICE_ID) REFERENCES AP_INVOICE (AP_INVOICE_ID),
	CONSTRAINT FK_APIG_ITEM_DISCOUNT_TYPE_ID FOREIGN KEY (ITEM_DISCOUNT_TYPE_ID) REFERENCES ITEM_DISCOUNT_TYPE (ITEM_DISCOUNT_TYPE_ID),
	CONSTRAINT FK_APIG_TAX_TYPE_ID FOREIGN KEY (TAX_TYPE_ID) REFERENCES TAX_TYPE (TAX_TYPE_ID),
	CONSTRAINT FK_APIG_EB_OBJECT_ID FOREIGN KEY (EB_OBJECT_ID) REFERENCES EB_OBJECT (EB_OBJECT_ID),
	CONSTRAINT FK_APIG_ITEM_ID FOREIGN KEY (ITEM_ID) REFERENCES ITEM (ITEM_ID)
) ENGINE=INNODB DEFAULT CHARSET=UTF8;