
-- Description: sql script in creating AP_INVOICE_LINE table.

DROP TABLE IF EXISTS AP_INVOICE_LINE;

CREATE TABLE `AP_INVOICE_LINE` (
  `AP_INVOICE_LINE_ID` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `AP_INVOICE_ID` int(10) unsigned NOT NULL,
  `EB_OBJECT_ID` int(10) unsigned DEFAULT NULL,
  `AP_LINE_SETUP_ID` int(10) unsigned NOT NULL,
  `UNITOFMEASUREMENT_ID` int(10) unsigned DEFAULT NULL,
  `QUANTITY` double DEFAULT NULL,
  `UP_AMOUNT` double DEFAULT NULL,
  `AMOUNT` double NOT NULL,
  `PERCENTILE` DOUBLE DEFAULT NULL,
  PRIMARY KEY (`AP_INVOICE_LINE_ID`),
  KEY `FK_AP_IL_AP_INVOICE_ID` (`AP_INVOICE_ID`),
  KEY `FK_AP_IL_AP_LINE_SETUP_ID` (`AP_LINE_SETUP_ID`),
  KEY `FK_AP_IL_EB_OBJECT_ID` (`EB_OBJECT_ID`),
  CONSTRAINT `FK_AP_IL_EB_OBJECT_ID` FOREIGN KEY (`EB_OBJECT_ID`) REFERENCES `EB_OBJECT` (`EB_OBJECT_ID`),
  CONSTRAINT `FK_AP_IL_AP_INVOICE_ID` FOREIGN KEY (`AP_INVOICE_ID`) REFERENCES `AP_INVOICE` (`AP_INVOICE_ID`),
  CONSTRAINT `FK_AP_IL_AP_LINE_SETUP_ID` FOREIGN KEY (`AP_LINE_SETUP_ID`) REFERENCES `AP_LINE_SETUP` (`AP_LINE_SETUP_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
