
-- Description : Create script for AP_INVOICE_ITEM table.

DROP TABLE IF EXISTS AP_INVOICE_ITEM;

CREATE TABLE AP_INVOICE_ITEM (
	AP_INVOICE_ITEM_ID int(10) unsigned NOT NULL AUTO_INCREMENT,
	EB_OBJECT_ID int(10) unsigned DEFAULT NULL,
	AP_INVOICE_ID int(10) unsigned NOT NULL,
	AMOUNT double DEFAULT '0',
	ACTIVE tinyint(1) DEFAULT '1',
	PRIMARY KEY (AP_INVOICE_ITEM_ID),
	KEY FK_APII_AP_INVOICE_ID (AP_INVOICE_ID),
	KEY FK_APII_EB_OBJECT_ID (EB_OBJECT_ID),
	CONSTRAINT FK_APII_EB_OBJECT_ID FOREIGN KEY (EB_OBJECT_ID) REFERENCES EB_OBJECT (EB_OBJECT_ID),
	CONSTRAINT FK_APII_AP_INVOICE_ID FOREIGN KEY (AP_INVOICE_ID) REFERENCES AP_INVOICE (AP_INVOICE_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;