
-- Description: sql script in creating AP_LINE_SETUP table.

DROP TABLE IF EXISTS AP_LINE_SETUP;

CREATE TABLE `AP_LINE_SETUP` (
  `AP_LINE_SETUP_ID` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `NAME` varchar(100) NOT NULL,
  `ACTIVE` tinyint(1) NOT NULL,
  `ACCOUNT_COMBINATION_ID` int(10) unsigned NOT NULL,
  `CREATED_BY` int(10) unsigned NOT NULL,
  `CREATED_DATE` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_BY` int(10) unsigned NOT NULL,
  `UPDATED_DATE` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  PRIMARY KEY (`AP_LINE_SETUP_ID`),
  KEY `FK_AP_LINE_SETUP_ACCT_COMBI` (`ACCOUNT_COMBINATION_ID`),
  KEY `FK_AP_LINE_SETUP_CREATED_BY` (`CREATED_BY`),
  KEY `FK_AP_LINE_SETUP_UPDATED_BY` (`UPDATED_BY`),
  CONSTRAINT `FK_AP_LINE_SETUP_ACCT_COMBI` FOREIGN KEY (`ACCOUNT_COMBINATION_ID`) REFERENCES `ACCOUNT_COMBINATION` (`ACCOUNT_COMBINATION_ID`),
  CONSTRAINT `FK_AP_LINE_SETUP_CREATED_BY` FOREIGN KEY (`CREATED_BY`) REFERENCES `USER` (`USER_ID`),
  CONSTRAINT `FK_AP_LINE_SETUP_UPDATED_BY` FOREIGN KEY (`UPDATED_BY`) REFERENCES `USER` (`USER_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;