
-- Description: sql script in creating AP_LINE table.

DROP TABLE IF EXISTS AP_LINE;

CREATE TABLE AP_LINE (
       AP_LINE_ID int(10) unsigned NOT NULL AUTO_INCREMENT,
       AP_INVOICE_ID int(10) unsigned NOT NULL,
       ACCOUNT_COMBINATION_ID int(10) unsigned NOT NULL,
       EB_OBJECT_ID int(10) unsigned DEFAULT NULL,
       AMOUNT double NOT NULL,
       DESCRIPTION text,
       PRIMARY KEY (AP_LINE_ID),
       KEY FK_AP_LINE_AP_INVOICE_ID (AP_INVOICE_ID),
       KEY FK_AP_LINE_ACCOUNT_COMBINATION_ID (ACCOUNT_COMBINATION_ID),
       KEY FK_AP_LINE_EB_OBJECT_ID (EB_OBJECT_ID),
       CONSTRAINT FK_AP_LINE_INVOICE_ID FOREIGN KEY (AP_INVOICE_ID) REFERENCES AP_INVOICE (AP_INVOICE_ID),
       CONSTRAINT FK_AP_LINE_ACCOUNT_COMBINATION FOREIGN KEY (ACCOUNT_COMBINATION_ID) REFERENCES ACCOUNT_COMBINATION (ACCOUNT_COMBINATION_ID),
       CONSTRAINT FK_AP_LINE_EB_OBJECT_ID FOREIGN KEY (EB_OBJECT_ID) REFERENCES EB_OBJECT (EB_OBJECT_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;