
-- Description: sql script in creating AP_PAYMENT_INVOICE table.

DROP TABLE IF EXISTS AP_PAYMENT_INVOICE;

CREATE TABLE `AP_PAYMENT_INVOICE` (
  `AP_PAYMENT_INVOICE_ID` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `AP_PAYMENT_ID` int(10) unsigned NOT NULL,
  `AP_INVOICE_ID` int(10) unsigned NOT NULL,
  `PAID_AMOUNT` double DEFAULT '0',
  `EB_OBJECT_ID` int(10) unsigned DEFAULT NULL,
  `CREATED_BY` int(10) unsigned NOT NULL,
  `CREATED_DATE` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_BY` int(10) unsigned NOT NULL,
  `UPDATED_DATE` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  PRIMARY KEY (`AP_PAYMENT_INVOICE_ID`),
  KEY `FK_AP_PAYMENT_INVOICE_CREATED_BY` (`CREATED_BY`),
  KEY `FK_AP_PAYMENT_INVOICE_UPDATED_BY` (`UPDATED_BY`),
  KEY `FK_AP_PAYMENT_INVOICE_INVOICE_ID` (`AP_INVOICE_ID`),
  KEY `AP_PAYMENT_ID` (`AP_PAYMENT_ID`),
  KEY `FK_AP_PAYMENT_INVOICE_EB_OBJECT_ID` (`EB_OBJECT_ID`),
  CONSTRAINT `AP_PAYMENT_INVOICE_ibfk_1` FOREIGN KEY (`AP_PAYMENT_ID`) REFERENCES `AP_PAYMENT` (`AP_PAYMENT_ID`),
  CONSTRAINT `FK_AP_PAYMENT_INVOICE_CREATED_BY` FOREIGN KEY (`CREATED_BY`) REFERENCES `USER` (`USER_ID`),
  CONSTRAINT `FK_AP_PAYMENT_INVOICE_INVOICE_ID` FOREIGN KEY (`AP_INVOICE_ID`) REFERENCES `AP_INVOICE` (`AP_INVOICE_ID`),
  CONSTRAINT `FK_AP_PAYMENT_INVOICE_UPDATED_BY` FOREIGN KEY (`UPDATED_BY`) REFERENCES `USER` (`USER_ID`),
  CONSTRAINT `FK_AP_PAYMENT_INVOICE_EB_OBJECT_ID` FOREIGN KEY (`EB_OBJECT_ID`) REFERENCES `EB_OBJECT` (`EB_OBJECT_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;