
-- Description: sql script in creating AP_PAYMENT_LINE table.

DROP TABLE IF EXISTS AP_PAYMENT_LINE;

CREATE TABLE `AP_PAYMENT_LINE` (
  `AP_PAYMENT_LINE_ID` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `AP_PAYMENT_ID` int(10) unsigned NOT NULL,
  `AP_PAYMENT_LINE_TYPE_ID` int(10) unsigned NOT NULL,
  `PAID_AMOUNT` double DEFAULT '0',
  `EB_OBJECT_ID` int(10) unsigned DEFAULT NULL,
  `CURRENCY_RATE_VALUE` double DEFAULT 0,
  `CREATED_BY` int(10) unsigned NOT NULL,
  `CREATED_DATE` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_BY` int(10) unsigned NOT NULL,
  `UPDATED_DATE` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  PRIMARY KEY (`AP_PAYMENT_LINE_ID`),
  KEY `FK_AP_PAYMENT_LINE_CREATED_BY` (`CREATED_BY`),
  KEY `FK_AP_PAYMENT_LINE_UPDATED_BY` (`UPDATED_BY`),
  KEY `FK_AP_PAYMENT_LINE_AP_PAYMENT_ID` (`AP_PAYMENT_ID`),
  KEY `FK_AP_PAYMENT_LINE_LINE_TYPE_ID` (`AP_PAYMENT_LINE_TYPE_ID`),
  KEY `FK_AP_PAYMENT_LINE_EB_OBJECT_ID` (`EB_OBJECT_ID`),
  CONSTRAINT `FK_AP_PAYMENT_LINE_AP_PAYMENT_ID` FOREIGN KEY (`AP_PAYMENT_ID`) REFERENCES `AP_PAYMENT` (`AP_PAYMENT_ID`),
  CONSTRAINT `FK_AP_PAYMENT_LINE_LINE_TYPE_ID` FOREIGN KEY (`AP_PAYMENT_LINE_TYPE_ID`) REFERENCES `AP_PAYMENT_LINE_TYPE` (`AP_PAYMENT_LINE_TYPE_ID`),
  CONSTRAINT `FK_AP_PAYMENT_LINE_CREATED_BY` FOREIGN KEY (`CREATED_BY`) REFERENCES `USER` (`USER_ID`),
  CONSTRAINT `FK_AP_PAYMENT_LINE_UPDATED_BY` FOREIGN KEY (`UPDATED_BY`) REFERENCES `USER` (`USER_ID`),
  CONSTRAINT `FK_AP_PAYMENT_LINE_EB_OBJECT_ID` FOREIGN KEY (`EB_OBJECT_ID`) REFERENCES `EB_OBJECT` (`EB_OBJECT_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;