
-- Description: sql script in creating AR_CUSTOMER table.

DROP TABLE IF EXISTS AR_CUSTOMER;

CREATE TABLE `AR_CUSTOMER` (
  `AR_CUSTOMER_ID` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `EB_SL_KEY_ID` int(10) unsigned NOT NULL,
  `NAME` varchar(50) NOT NULL,
  `ADDRESS` varchar(150) NOT NULL,
  `CONTACT_NUMBER` varchar(20) DEFAULT NULL,
  `EMAIL_ADDRESS` varchar(50) DEFAULT NULL,
  `TIN` varchar(20) DEFAULT NULL,
  `MAX_AMOUNT` decimal(12,2) DEFAULT NULL,
  `EB_OBJECT_ID` int(10) unsigned DEFAULT NULL,
  `ACTIVE` tinyint(1) NOT NULL,
  `CREATED_BY` int(10) unsigned NOT NULL,
  `CREATED_DATE` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_BY` int(10) unsigned NOT NULL,
  `UPDATED_DATE` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  PRIMARY KEY (`AR_CUSTOMER_ID`),
  KEY `FK_CUSTOMER_EB_SL_KEY_ID` (`EB_SL_KEY_ID`),
  KEY `FK_CUSTOMER_EB_OBJECT_ID` (`EB_OBJECT_ID`),
  KEY `FK_CUSTOMER_CREATED_BY` (`CREATED_BY`),
  KEY `FK_CUSTOMER_UPDATED_BY` (`UPDATED_BY`),
  CONSTRAINT `FK_CUSTOMER_EB_SL_KEY_ID` FOREIGN KEY (`EB_SL_KEY_ID`) REFERENCES `EB_SL_KEY` (`EB_SL_KEY_ID`),
  CONSTRAINT `FK_CUSTOMER_EB_OBJECT_ID` FOREIGN KEY (`EB_OBJECT_ID`) REFERENCES `EB_OBJECT` (`EB_OBJECT_ID`),
  CONSTRAINT `FK_CUSTOMER_CREATED_BY` FOREIGN KEY (`CREATED_BY`) REFERENCES `USER` (`USER_ID`),
  CONSTRAINT `FK_CUSTOMER_UPDATED_BY` FOREIGN KEY (`UPDATED_BY`) REFERENCES `USER` (`USER_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
