
-- Description: sql script in creating AR_CUSTOMER_ACCOUNT table.

DROP TABLE IF EXISTS AR_CUSTOMER_ACCOUNT;

CREATE TABLE `AR_CUSTOMER_ACCOUNT` (
  `AR_CUSTOMER_ACCOUNT_ID` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `AR_CUSTOMER_ID` int(10) unsigned NOT NULL,
  `NAME` varchar(100) NOT NULL,
  `COMPANY_ID` int(10) unsigned NOT NULL,
  `DEFAULT_DEBIT_AC_ID` int(10) unsigned NOT NULL,
  `DEFAULT_AR_TRANSACTION_LINE_ID` int(10) unsigned DEFAULT NULL,
  `DEFAULT_WITHDRAWAL_SLIP_AC_ID` INT(10) UNSIGNED DEFAULT NULL,
  `TERM_ID` int(10) unsigned NOT NULL,
  `EB_OBJECT_ID` int(10) unsigned DEFAULT NULL,
  `ACTIVE` tinyint(1) NOT NULL,
  `CREATED_BY` int(10) unsigned NOT NULL,
  `CREATED_DATE` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_BY` int(10) unsigned NOT NULL,
  `UPDATED_DATE` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  PRIMARY KEY (`AR_CUSTOMER_ACCOUNT_ID`),
  KEY `FK_AR_CUST_ACCT_CUSTOMER` (`AR_CUSTOMER_ID`),
  KEY `FK_AR_CUST_ACCT_COMPANY` (`COMPANY_ID`),
  KEY `FK_AR_CUST_ACCT_DEFAULT_DEBIT_AC` (`DEFAULT_DEBIT_AC_ID`),
  KEY `FK_AR_CUST_ACCT_DEFAULT_AR_LINE` (`DEFAULT_AR_TRANSACTION_LINE_ID`),
  KEY `FK_AR_CUST_ACCT_TERM` (`TERM_ID`),
  KEY `FK_AR_CUST_ACCT_EB_OBJECT_ID` (`EB_OBJECT_ID`),
  KEY `FK_AR_CUST_ACCT_CREATED_BY` (`CREATED_BY`),
  KEY `FK_AR_CUST_ACCT_UPDATED_BY` (`UPDATED_BY`),
  CONSTRAINT `FK_AR_CUST_ACCT_ACCOUNT_TERM` FOREIGN KEY (`TERM_ID`) REFERENCES `TERM` (`TERM_ID`),
  CONSTRAINT `FK_AR_CUST_ACCT_EB_OBJECT_ID` FOREIGN KEY (`EB_OBJECT_ID`) REFERENCES `EB_OBJECT` (`EB_OBJECT_ID`),
  CONSTRAINT `FK_AR_CUST_ACCT_COMPANY_ID` FOREIGN KEY (`COMPANY_ID`) REFERENCES `COMPANY` (`COMPANY_ID`),
  CONSTRAINT `FK_AR_CUST_ACCT_CREATED_BY` FOREIGN KEY (`CREATED_BY`) REFERENCES `USER` (`USER_ID`),
  CONSTRAINT `FK_AR_CUST_ACCT_CUSTOMER` FOREIGN KEY (`AR_CUSTOMER_ID`) REFERENCES `AR_CUSTOMER` (`AR_CUSTOMER_ID`),
  CONSTRAINT `FK_AR_CUST_ACCT_DEFAULT_AR_LINE` FOREIGN KEY (`DEFAULT_AR_TRANSACTION_LINE_ID`) REFERENCES `AR_LINE_SETUP` (`AR_LINE_SETUP_ID`),
  CONSTRAINT `FK_AR_CUST_ACCT_DEFAULT_DEBIT_AC` FOREIGN KEY (`DEFAULT_DEBIT_AC_ID`) REFERENCES `ACCOUNT_COMBINATION` (`ACCOUNT_COMBINATION_ID`),
  CONSTRAINT `FK_AR_CUST_ACCT_UPDATED_BY` FOREIGN KEY (`UPDATED_BY`) REFERENCES `USER` (`USER_ID`),
  CONSTRAINT `FK_AR_CUST_ACCT_DEFAULT_WITHDRAWAL_SLIP_AC` FOREIGN KEY (`DEFAULT_WITHDRAWAL_SLIP_AC_ID`)
    REFERENCES `ACCOUNT_COMBINATION` (`ACCOUNT_COMBINATION_ID`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8;
