
-- Description: Sql script for creating AR_LINE table

DROP TABLE IF EXISTS AR_LINE;

CREATE TABLE AR_LINE (
       AR_LINE_ID int(10) unsigned NOT NULL AUTO_INCREMENT,
       AR_TRANSACTION_ID int(10) unsigned NOT NULL,
       AR_LINE_SETUP_ID int(10) unsigned NOT NULL,
       EB_OBJECT_ID int(10) unsigned,
       QUANTITY double DEFAULT '0',
       UNITOFMEASUREMENT_ID int(10) unsigned DEFAULT NULL,
       UP_AMOUNT double DEFAULT '0',
       AMOUNT double DEFAULT '0',
       PRIMARY KEY (AR_LINE_ID),
       KEY FK_AR_LINE_AR_TRANSACTION_ID (AR_TRANSACTION_ID),
       KEY FK_AR_LINE_AR_LINE_SETUP_ID (AR_LINE_SETUP_ID),
       KEY FK_AR_LINE_EB_OBJECT_ID (EB_OBJECT_ID),
       CONSTRAINT FK_AR_LINE_TRANSACTION_ID FOREIGN KEY (AR_TRANSACTION_ID) REFERENCES AR_TRANSACTION (AR_TRANSACTION_ID),
       CONSTRAINT FK_AR_LINE_EB_OBJECT_ID FOREIGN KEY (EB_OBJECT_ID) REFERENCES EB_OBJECT (EB_OBJECT_ID),
       CONSTRAINT FK_AR_LINE_AR_LINE_SETUP_ID FOREIGN KEY (AR_LINE_SETUP_ID) REFERENCES AR_LINE_SETUP (AR_LINE_SETUP_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;