
-- Description: Sql script in creating AR_MISCELLANEOUS table

DROP TABLE IF EXISTS AR_MISCELLANEOUS;

 CREATE TABLE `AR_MISCELLANEOUS` (
  `AR_MISCELLANEOUS_ID` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `EB_OBJECT_ID` int(10) unsigned DEFAULT NULL,
  `AR_MISCELLANEOUS_TYPE_ID` int(10) unsigned NOT NULL,
  `REF_NUMBER` varchar(20) DEFAULT NULL,
  `FORM_WORKFLOW_ID` int(10) unsigned DEFAULT NULL,
  `EB_SL_KEY_ID` int(10) unsigned NOT NULL,
  `SEQUENCE_NO` int(10) unsigned NOT NULL,
  `RECEIPT_METHOD_ID` int(10) DEFAULT NULL,
  `AR_CUSTOMER_ID` int(10) unsigned NOT NULL,
  `AR_CUSTOMER_ACCOUNT_ID` int(10) unsigned NOT NULL,
  `RECEIPT_NUMBER` varchar(100) NOT NULL,
  `RECEIPT_DATE` date NOT NULL,
  `MATURITY_DATE` date NOT NULL,
  `DESCRIPTION` text,
  `AMOUNT` double NOT NULL,
  `CREATED_BY` int(10) unsigned NOT NULL,
  `CREATED_DATE` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_BY` int(10) unsigned NOT NULL,
  `UPDATED_DATE` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  PRIMARY KEY (`AR_MISCELLANEOUS_ID`),
  KEY `FK_AR_MISCELLANEOUS_TYPE_ID` (`AR_MISCELLANEOUS_TYPE_ID`),
  KEY `FK_AR_MISCELLANEOUS_FORM_WORKFLOW_ID` (`FORM_WORKFLOW_ID`),
  KEY `FK_AR_MISCELLANEOUS_EB_SL_KEY_ID` (`EB_SL_KEY_ID`),
  KEY `FK_AR_MISCELLANEOUS_CUSTOMER_ID` (`AR_CUSTOMER_ID`),
  KEY `FK_AR_MISCELLANEOUS_CUSTOMER_ACCOUNT_ID` (`AR_CUSTOMER_ACCOUNT_ID`),
  KEY `FK_AR_MISCELLANEOUS_CREATED_BY` (`CREATED_BY`),
  KEY `FK_AR_MISCELLANEOUS_UPDATED_BY` (`UPDATED_BY`),
  KEY `FK_AR_MISCELLANEOUS_EB_OBJECT_ID` (`EB_OBJECT_ID`),
  CONSTRAINT `FK_AR_MISCELLANEOUS_CREATED_BY` FOREIGN KEY (`CREATED_BY`) REFERENCES `USER` (`USER_ID`),
  CONSTRAINT `FK_AR_MISCELLANEOUS_CUSTOMER_ACCOUNT_ID` FOREIGN KEY (`AR_CUSTOMER_ACCOUNT_ID`) REFERENCES `AR_CUSTOMER_ACCOUNT` (`AR_CUSTOMER_ACCOUNT_ID`),
  CONSTRAINT `FK_AR_MISCELLANEOUS_CUSTOMER_ID` FOREIGN KEY (`AR_CUSTOMER_ID`) REFERENCES `AR_CUSTOMER` (`AR_CUSTOMER_ID`),
  CONSTRAINT `FK_AR_MISCELLANEOUS_EB_SL_KEY_ID` FOREIGN KEY (`EB_SL_KEY_ID`) REFERENCES `EB_SL_KEY` (`EB_SL_KEY_ID`),
  CONSTRAINT `FK_AR_MISCELLANEOUS_FORM_WORKFLOW_ID` FOREIGN KEY (`FORM_WORKFLOW_ID`) REFERENCES `FORM_WORKFLOW` (`FORM_WORKFLOW_ID`),
  CONSTRAINT `FK_AR_MISCELLANEOUS_TYPE_ID` FOREIGN KEY (`AR_MISCELLANEOUS_TYPE_ID`) REFERENCES `AR_MISCELLANEOUS_TYPE` (`AR_MISCELLANEOUS_TYPE_ID`),
  CONSTRAINT `FK_AR_MISCELLANEOUS_UPDATED_BY` FOREIGN KEY (`UPDATED_BY`) REFERENCES `USER` (`USER_ID`),
  CONSTRAINT `FK_AR_MISCELLANEOUS_EB_OBJECT_ID` FOREIGN KEY (`EB_OBJECT_ID`) REFERENCES `EB_OBJECT` (`EB_OBJECT_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;