
-- Description	: Create script for AR_RECEIPT_ACCOUNT table.

DROP TABLE IF EXISTS AR_RECEIPT_ACCOUNT;

CREATE TABLE AR_RECEIPT_ACCOUNT (
	AR_RECEIPT_ACCOUNT_ID int(10) unsigned NOT NULL AUTO_INCREMENT,
	COMPANY_ID int(10) unsigned NOT NULL,
	DIVISION_ID int(10) unsigned DEFAULT NULL,
	RETENTION_AC_ID int(10) unsigned DEFAULT NULL,
	RECOUPMENT_AC_ID int(10) unsigned DEFAULT NULL,
	FOREIGN_EXCHANGE_GAIN_AC_ID int(10) unsigned NOT NULL,
	FOREIGN_EXCHANGE_LOSS_AC_ID int(10) unsigned NOT NULL,
	ACTIVE tinyint(1) DEFAULT '1',
	CREATED_BY int(10) unsigned NOT NULL,
	CREATED_DATE timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
	UPDATED_BY int(10) unsigned NOT NULL,
	UPDATED_DATE timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
	PRIMARY KEY (AR_RECEIPT_ACCOUNT_ID),
	KEY FK_ARRA_COMPANY_ID (COMPANY_ID),
	KEY FK_ARRA_DIVISION_ID (DIVISION_ID),
	KEY FK_ARRA_RETENTION_AC_ID (RETENTION_AC_ID),
	KEY FK_ARRA_RECOUPMENT_AC_ID (RECOUPMENT_AC_ID),
	KEY FK_ARRA_FOREIGN_EXCHANGE_GAIN_AC_ID (FOREIGN_EXCHANGE_GAIN_AC_ID),
	KEY FK_ARRA_FOREIGN_EXCHANGE_LOSS_AC_ID (FOREIGN_EXCHANGE_LOSS_AC_ID),
	KEY FK_ARRA_CREATED_BY (CREATED_BY),
	KEY FK_ARRA_UPDATED_BY (UPDATED_BY),
	CONSTRAINT FK_ARRA_COMPANY_ID FOREIGN KEY (COMPANY_ID) REFERENCES COMPANY (COMPANY_ID),
	CONSTRAINT FK_ARRA_DIVISION_ID FOREIGN KEY (DIVISION_ID) REFERENCES DIVISION (DIVISION_ID),
	CONSTRAINT FK_ARRA_RETENTION_AC_ID FOREIGN KEY (RETENTION_AC_ID) REFERENCES ACCOUNT_COMBINATION (ACCOUNT_COMBINATION_ID),
	CONSTRAINT FK_ARRA_RECOUPMENT_AC_ID FOREIGN KEY (RECOUPMENT_AC_ID) REFERENCES ACCOUNT_COMBINATION (ACCOUNT_COMBINATION_ID),
	CONSTRAINT FK_ARRA_FOREIGN_EXCHANGE_GAIN_AC_ID FOREIGN KEY (FOREIGN_EXCHANGE_GAIN_AC_ID) REFERENCES ACCOUNT_COMBINATION (ACCOUNT_COMBINATION_ID),
	CONSTRAINT FK_ARRA_FOREIGN_EXCHANGE_LOSS_AC_ID FOREIGN KEY (FOREIGN_EXCHANGE_LOSS_AC_ID) REFERENCES ACCOUNT_COMBINATION (ACCOUNT_COMBINATION_ID),
	CONSTRAINT FK_ARRA_CREATED_BY FOREIGN KEY (CREATED_BY) REFERENCES USER (USER_ID),
	CONSTRAINT FK_ARRA_UPDATED_BY FOREIGN KEY (UPDATED_BY) REFERENCES USER (USER_ID)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;