
-- Description: Sql script for creating AR_LINE table

DROP TABLE IF EXISTS AR_SERVICE_LINE;

CREATE TABLE AR_SERVICE_LINE (
		AR_SERVICE_LINE_ID int(10) unsigned NOT NULL AUTO_INCREMENT,
		AR_TRANSACTION_ID int(10) unsigned NOT NULL,
		SERVICE_SETTING_ID int(10) unsigned NOT NULL,
		EB_OBJECT_ID int(10) unsigned,
		QUANTITY double DEFAULT '0',
		UNITOFMEASUREMENT_ID int(10) unsigned DEFAULT NULL,
		UP_AMOUNT double DEFAULT '0',
		AMOUNT double DEFAULT '0',
		TAX_TYPE_ID int(10) unsigned DEFAULT NULL,
		VAT_AMOUNT double DEFAULT '0',
		DISCOUNT_TYPE_ID int(10) unsigned DEFAULT NULL,
		PRIMARY KEY (AR_SERVICE_LINE_ID),
		KEY FK_AR_SERVICE_LINE_AR_TRANSACTION_ID (AR_TRANSACTION_ID),
		KEY FK_AR_SERVICE_LINE_SERVICE_SETTING_ID (SERVICE_SETTING_ID),
		KEY FK_AR_SERVICE_LINE_EB_OBJECT_ID (EB_OBJECT_ID),
		KEY FK_AR_SERVICE_LINE_TAX_TYPE_ID (TAX_TYPE_ID),
		KEY FK_AR_SERVICE_LINE_DISCOUNT_TYPE_ID (DISCOUNT_TYPE_ID),
		CONSTRAINT FK_AR_SERVICE_LINE_AR_TRANSACTION_ID FOREIGN KEY (AR_TRANSACTION_ID) REFERENCES AR_TRANSACTION (AR_TRANSACTION_ID),
		CONSTRAINT FK_AR_SERVICE_LINE_EB_OBJECT_ID FOREIGN KEY (EB_OBJECT_ID) REFERENCES EB_OBJECT (EB_OBJECT_ID),
		CONSTRAINT FK_AR_SERVICE_LINE_SERVICE_SETTING_ID FOREIGN KEY (SERVICE_SETTING_ID) REFERENCES SERVICE_SETTING (SERVICE_SETTING_ID),
		CONSTRAINT FK_AR_SERVICE_LINE_TAX_TYPE_ID FOREIGN KEY (TAX_TYPE_ID) REFERENCES TAX_TYPE (TAX_TYPE_ID),
		CONSTRAINT FK_AR_SERVICE_LINE_DISCOUNT_TYPE_ID FOREIGN KEY (DISCOUNT_TYPE_ID) REFERENCES ITEM_DISCOUNT_TYPE (ITEM_DISCOUNT_TYPE_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;