
-- Description: sql script in creating BANK_ACCOUNT table.

DROP TABLE IF EXISTS BANK_ACCOUNT;

CREATE TABLE `BANK_ACCOUNT` (
  `BANK_ACCOUNT_ID` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `NAME` varchar(100) NOT NULL,
  `EB_SL_KEY_ID` int(10) unsigned NOT NULL,
  `COMPANY_ID` int(10) unsigned NOT NULL,
  `CASH_IN_BANK_ACCT_ID` int(10) unsigned NOT NULL,
  `CASH_RECEIPTS_CLEARING_ACCT_ID` int(10) unsigned NOT NULL,
  `CASH_PAYMENTS_CLEARING_ACCT_ID` int(10) unsigned NOT NULL,
  `CASH_RECEIPTS_PDC_ACCT_ID` int(10) unsigned DEFAULT NULL,
  `CASH_PAYMENTS_PDC_ACCT_ID` int(10) unsigned DEFAULT NULL,
  `ACTIVE` tinyint(1) NOT NULL,
  `CREATED_BY` int(10) unsigned NOT NULL,
  `CREATED_DATE` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_BY` int(10) unsigned NOT NULL,
  `UPDATED_DATE` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  PRIMARY KEY (`BANK_ACCOUNT_ID`),
  KEY `FK_BA_CREATED_BY` (`CREATED_BY`),
  KEY `FK_BA_UPDATED_BY` (`UPDATED_BY`),
  KEY `FK_BA_COMPANY_ID` (`COMPANY_ID`),
  KEY `FK_BA_CASH_IN` (`CASH_IN_BANK_ACCT_ID`),
  KEY `FK_BA_CASH_RECEIPTS` (`CASH_RECEIPTS_CLEARING_ACCT_ID`),
  KEY `FK_BA_CASH_PAYMENTS` (`CASH_PAYMENTS_CLEARING_ACCT_ID`),
  KEY `FK_BA_EB_SL_KEY_ID` (`EB_SL_KEY_ID`),
  KEY `FK_BA_CASH_RECEIPTS_PDC` (`CASH_RECEIPTS_PDC_ACCT_ID`),
  KEY `FK_BA_CASH_PAYMENTS_PDC` (`CASH_PAYMENTS_PDC_ACCT_ID`),
  CONSTRAINT `FK_BA_CASH_RECEIPTS_PDC` FOREIGN KEY (`CASH_RECEIPTS_PDC_ACCT_ID`) REFERENCES `ACCOUNT_COMBINATION` (`ACCOUNT_COMBINATION_ID`),
  CONSTRAINT `FK_BA_CASH_PAYMENTS_PDC` FOREIGN KEY (`CASH_PAYMENTS_PDC_ACCT_ID`) REFERENCES `ACCOUNT_COMBINATION` (`ACCOUNT_COMBINATION_ID`),
  CONSTRAINT `FK_BA_CASH_IN` FOREIGN KEY (`CASH_IN_BANK_ACCT_ID`) REFERENCES `ACCOUNT_COMBINATION` (`ACCOUNT_COMBINATION_ID`),
  CONSTRAINT `FK_BA_CASH_PAYMENTS` FOREIGN KEY (`CASH_PAYMENTS_CLEARING_ACCT_ID`) REFERENCES `ACCOUNT_COMBINATION` (`ACCOUNT_COMBINATION_ID`),
  CONSTRAINT `FK_BA_CASH_RECEIPTS` FOREIGN KEY (`CASH_RECEIPTS_CLEARING_ACCT_ID`) REFERENCES `ACCOUNT_COMBINATION` (`ACCOUNT_COMBINATION_ID`),
  CONSTRAINT `FK_BA_COMPANY_ID` FOREIGN KEY (`COMPANY_ID`) REFERENCES `COMPANY` (`COMPANY_ID`),
  CONSTRAINT `FK_BA_CREATED_BY` FOREIGN KEY (`CREATED_BY`) REFERENCES `USER` (`USER_ID`),
  CONSTRAINT `FK_BA_EB_SL_KEY_ID` FOREIGN KEY (`EB_SL_KEY_ID`) REFERENCES `EB_SL_KEY` (`EB_SL_KEY_ID`),
  CONSTRAINT `FK_BA_UPDATED_BY` FOREIGN KEY (`UPDATED_BY`) REFERENCES `USER` (`USER_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;