
-- Description: Create script for BUS_REG_TYPE table.

DROP TABLE IF EXISTS BUS_REG_TYPE;

CREATE TABLE BUS_REG_TYPE(
	BUS_REG_TYPE_ID int(10) unsigned NOT NULL AUTO_INCREMENT,
	NAME varchar(20) NOT NULL,
	PRIMARY KEY (BUS_REG_TYPE_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;