
-- Description: sql script in creating CHECKBOOK_TEMPLATE table.

DROP TABLE IF EXISTS CHECKBOOK_TEMPLATE;

CREATE TABLE CHECKBOOK_TEMPLATE (
	CHECKBOOK_TEMPLATE_ID int(10) unsigned NOT NULL AUTO_INCREMENT,
	NAME VARCHAR(50) NOT NULL,
	VIEWS_PROP_NAME VARCHAR(50) NOT NULL,
	MAX_CHAR_AMOUNT_IN_WORDS int(3) NOT NULL,
	MAX_CHAR_NAME int(3) NOT NULL,
	PRIMARY KEY (CHECKBOOK_TEMPLATE_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;