
-- Description: sql script in creating CHECKBOOK table.

DROP TABLE IF EXISTS CHECKBOOK;
CREATE TABLE `CHECKBOOK` (
  `CHECKBOOK_ID` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `BANK_ACCOUNT_ID` int(10) unsigned NOT NULL,
  `NAME` varchar(100) DEFAULT NULL,
  `CHECKBOOK_NO_FROM` decimal(20,0) DEFAULT NULL,
  `CHECKBOOK_NO_TO` decimal(20,0) DEFAULT NULL,
  `ACTIVE` tinyint(1) NOT NULL,
  `CREATED_BY` int(10) unsigned NOT NULL,
  `CREATED_DATE` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_BY` int(10) unsigned NOT NULL,
  `UPDATED_DATE` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  `CHECKBOOK_TEMPLATE_ID` int(10) unsigned DEFAULT NULL,
  PRIMARY KEY (`CHECKBOOK_ID`),
  KEY `FK_CHECKBOOK_CREATED_BY` (`CREATED_BY`),
  KEY `FK_CHECKBOOK_UPDATED_BY` (`UPDATED_BY`),
  KEY `FK_CHECKBOOK_BANK_ACCOUNT_ID` (`BANK_ACCOUNT_ID`),
  KEY `FK_CHECKBOOK_TEMPLATE_ID` (`CHECKBOOK_TEMPLATE_ID`),
  CONSTRAINT `FK_CHECKBOOK_BANK_ACCOUNT_ID` FOREIGN KEY (`BANK_ACCOUNT_ID`) REFERENCES `BANK_ACCOUNT` (`BANK_ACCOUNT_ID`),
  CONSTRAINT `FK_CHECKBOOK_CREATED_BY` FOREIGN KEY (`CREATED_BY`) REFERENCES `USER` (`USER_ID`),
  CONSTRAINT `FK_CHECKBOOK_TEMPLATE_ID` FOREIGN KEY (`CHECKBOOK_TEMPLATE_ID`) REFERENCES `CHECKBOOK_TEMPLATE` (`CHECKBOOK_TEMPLATE_ID`),
  CONSTRAINT `FK_CHECKBOOK_UPDATED_BY` FOREIGN KEY (`UPDATED_BY`) REFERENCES `USER` (`USER_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;