
-- Description	: SQL script in creating CURRENCY_RATE table

DROP TABLE IF EXISTS CURRENCY_RATE;
CREATE TABLE CURRENCY_RATE (
	CURRENCY_RATE_ID int(10) unsigned NOT NULL AUTO_INCREMENT,
	CURRENCY_ID int(10) unsigned NOT NULL,
	DATE timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
	RATE double NOT NULL,
	ACTIVE tinyint(1) NOT NULL,
	CREATED_BY int(10) unsigned NOT NULL,
	CREATED_DATE timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
	UPDATED_BY int(10) unsigned NOT NULL,
	UPDATED_DATE timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
	PRIMARY KEY (CURRENCY_RATE_ID),
	KEY FK_CURRENCY_RATE_CURRENCY_ID (CURRENCY_ID),
	KEY FK_CURRENCY_RATE_CREATED_BY (CREATED_BY),
	KEY FK_CURRENCY_RATE_UPDATED_BY (UPDATED_BY),
	CONSTRAINT FK_CURRENCY_RATE_CURRENCY_ID FOREIGN KEY (CURRENCY_ID) REFERENCES CURRENCY (CURRENCY_ID),
	CONSTRAINT FK_CURRENCY_RATE_CREATED_BY FOREIGN KEY (CREATED_BY) REFERENCES USER (USER_ID),
	CONSTRAINT FK_CURRENCY_RATE_UPDATED_BY FOREIGN KEY (UPDATED_BY) REFERENCES USER (USER_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

