
-- Description: Sql script in creating CUSTODIAN_ACCOUNT table.

DROP TABLE IF EXISTS CUSTODIAN_ACCOUNT;

CREATE TABLE CUSTODIAN_ACCOUNT (
	CUSTODIAN_ACCOUNT_ID int(10) unsigned NOT NULL AUTO_INCREMENT,
	CUSTODIAN_NAME varchar(100) NOT NULL,
	COMPANY_ID int(10) unsigned NOT NULL,
	CUSTODIAN_ACCOUNT_NAME varchar(100) NOT NULL,
	TERM_ID int(10) unsigned NOT NULL,
	ACTIVE tinyint(1) NOT NULL,
	CD_ACCOUNT_COMBINATION_ID int(10) unsigned NOT NULL,
	FD_ACCOUNT_COMBINATION_ID int(10) unsigned NOT NULL,
	CREATED_BY int(10) unsigned NOT NULL,
	CREATED_DATE timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
	UPDATED_BY int(10) unsigned NOT NULL,
	UPDATED_DATE timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
	PRIMARY KEY (CUSTODIAN_ACCOUNT_ID),
	KEY FK_CUSTODIAN_ACCOUNT_COMPANY_ID (COMPANY_ID),
	KEY FK_CUSTODIAN_ACCOUNT_TERM_ID (TERM_ID),
	KEY FK_CUSTODIAN_ACCOUNT_CD_AC_ID (CD_ACCOUNT_COMBINATION_ID),
	KEY FK_CUSTODIAN_ACCOUNT_FD_AC_ID (FD_ACCOUNT_COMBINATION_ID),
	KEY FK_CUSTODIAN_ACCOUNT_CREATED_BY (CREATED_BY),
	KEY FK_CUSTODIAN_ACCOUNT_UPDATED_BY (UPDATED_BY),
	CONSTRAINT FK_CUSTODIAN_ACCOUNT_COMPANY_ID FOREIGN KEY (COMPANY_ID) REFERENCES COMPANY (COMPANY_ID),
	CONSTRAINT FK_CUSTODIAN_ACCOUNT_TERM_ID FOREIGN KEY (TERM_ID) REFERENCES TERM (TERM_ID),
	CONSTRAINT FK_CUSTODIAN_ACCOUNT_CD_AC_ID FOREIGN KEY (CD_ACCOUNT_COMBINATION_ID) REFERENCES ACCOUNT_COMBINATION (ACCOUNT_COMBINATION_ID),
	CONSTRAINT FK_CUSTODIAN_ACCOUNT_FD_AC_ID FOREIGN KEY (FD_ACCOUNT_COMBINATION_ID) REFERENCES ACCOUNT_COMBINATION (ACCOUNT_COMBINATION_ID),
	CONSTRAINT FK_CUSTODIAN_ACCOUNT_CREATED_BY FOREIGN KEY (CREATED_BY) REFERENCES USER (USER_ID),
	CONSTRAINT FK_CUSTODIAN_ACCOUNT_UPDATED_BY FOREIGN KEY (UPDATED_BY) REFERENCES USER (USER_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
