
-- Description: SQL script in creating the DIVISION table.

DROP TABLE IF EXISTS DIVISION;

CREATE TABLE `DIVISION` (
  `DIVISION_ID` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `PARENT_DIVISION_ID` int(10) unsigned DEFAULT NULL,
  `EB_OBJECT_ID` int(10) unsigned DEFAULT NULL,
  `NUMBER` varchar(5) NOT NULL,
  `NAME` varchar(100) NOT NULL,
  `DESCRIPTION` varchar(200) NOT NULL,
  `ACTIVE` tinyint(1) NOT NULL,
  `CREATED_BY` int(10) unsigned NOT NULL,
  `CREATED_DATE` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_BY` int(10) unsigned NOT NULL,
  `UPDATED_DATE` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  `EB_SL_KEY_ID` int(10) unsigned NOT NULL DEFAULT '1',
  PRIMARY KEY (`DIVISION_ID`),
  KEY `FK_DIVISION_CREATED_BY` (`CREATED_BY`),
  KEY `FK_DIVISION_UPDATED_BY` (`UPDATED_BY`),
  KEY `EB_SL_KEY_ID` (`EB_SL_KEY_ID`),
  KEY `FK_DIVISION_EB_OBJECT_ID` (`EB_OBJECT_ID`),
  CONSTRAINT `DIVISION_ibfk_1` FOREIGN KEY (`EB_SL_KEY_ID`) REFERENCES `EB_SL_KEY` (`EB_SL_KEY_ID`),
  CONSTRAINT `FK_DIVISION_CREATED_BY` FOREIGN KEY (`CREATED_BY`) REFERENCES `USER` (`USER_ID`),
  CONSTRAINT `FK_DIVISION_UPDATED_BY` FOREIGN KEY (`UPDATED_BY`) REFERENCES `USER` (`USER_ID`),
  CONSTRAINT `FK_DIVISION_EB_OBJECT_ID` FOREIGN KEY (`EB_OBJECT_ID`) REFERENCES `EB_OBJECT` (`EB_OBJECT_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;