
-- Description: sql script in creating GENERAL_LEDGER table.

DROP TABLE IF EXISTS GENERAL_LEDGER;

CREATE TABLE `GENERAL_LEDGER` (
  `GENERAL_LEDGER_ID` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `EB_OBJECT_ID` int(10) unsigned DEFAULT NULL,
  `FORM_WORKFLOW_ID` int(10) unsigned DEFAULT NULL,
  `SEQUENCE_NO` int(10) unsigned NOT NULL,
  `GL_STATUS_ID` int(10) unsigned NOT NULL,
  `GL_ENTRY_SOURCE_ID` int(10) unsigned NOT NULL,
  `GL_DATE` date NOT NULL,
  `COMMENT` text,
  `CREATED_BY` int(10) unsigned NOT NULL,
  `CREATED_DATE` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_BY` int(10) unsigned NOT NULL,
  `UPDATED_DATE` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  PRIMARY KEY (`GENERAL_LEDGER_ID`),
  KEY `FK_GENERAL_LEDGER_STATUS` (`GL_STATUS_ID`),
  KEY `FK_GENERAL_LEDGER_ENTRY_SOURCE` (`GL_ENTRY_SOURCE_ID`),
  KEY `FK_GENERAL_LEDGER_CREATED_BY` (`CREATED_BY`),
  KEY `FK_GENERAL_LEDGER_UPDATED_BY` (`UPDATED_BY`),
  KEY `FK_AP_GENERAL_LEDGER_FORM_WORKFLOW_ID` (`FORM_WORKFLOW_ID`),
  KEY `FK_GENERAL_LEDGER_EB_OBJECT_ID` (`EB_OBJECT_ID`),
  CONSTRAINT `FK_AP_GENERAL_LEDGER_FORM_WORKFLOW_ID` FOREIGN KEY (`FORM_WORKFLOW_ID`) REFERENCES `FORM_WORKFLOW` (`FORM_WORKFLOW_ID`),
  CONSTRAINT `FK_GENERAL_LEDGER_CREATED_BY` FOREIGN KEY (`CREATED_BY`) REFERENCES `USER` (`USER_ID`),
  CONSTRAINT `FK_GENERAL_LEDGER_UPDATED_BY` FOREIGN KEY (`UPDATED_BY`) REFERENCES `USER` (`USER_ID`),
  CONSTRAINT `FK_GENERAL_LEDGER_EB_OBJECT_ID` FOREIGN KEY (`EB_OBJECT_ID`) REFERENCES `EB_OBJECT` (`EB_OBJECT_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;