
-- Description: sql script in creating GL_ENTRY table.

DROP TABLE IF EXISTS GL_ENTRY;

CREATE TABLE GL_ENTRY (
       GL_ENTRY_ID int(10) unsigned NOT NULL AUTO_INCREMENT,
       EB_OBJECT_ID int(10) unsigned DEFAULT NULL,
       GENERAL_LEDGER_ID int(10) unsigned NOT NULL,
       ACCOUNT_COMBINATION_ID int(10) unsigned NOT NULL,
       AMOUNT double NOT NULL,
       DESCRIPTION text,
       IS_DEBIT tinyint(1) NOT NULL,
       PRIMARY KEY (GL_ENTRY_ID),
       KEY FK_GL_ENTRY_GENERAL_LEDGER (GENERAL_LEDGER_ID),
       KEY FK_GL_ENTRY_ACCOUNT_COMBINATION (ACCOUNT_COMBINATION_ID),
       KEY FK_GL_ENTRY_EB_OBJECT_ID (EB_OBJECT_ID),
       CONSTRAINT FK_GL_ENTRY_GENERAL_LEDGER FOREIGN KEY (GENERAL_LEDGER_ID) REFERENCES GENERAL_LEDGER (GENERAL_LEDGER_ID),
       CONSTRAINT FK_GL_ENTRY_ACCOUNT_COMBINATION FOREIGN KEY (ACCOUNT_COMBINATION_ID) REFERENCES ACCOUNT_COMBINATION (ACCOUNT_COMBINATION_ID),
       CONSTRAINT FK_GL_ENTRY_EB_OBJECT_ID FOREIGN KEY (EB_OBJECT_ID) REFERENCES EB_OBJECT (EB_OBJECT_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;