
-- Description: sql script in creating GL_ENTRY_SOURCE table.

DROP TABLE IF EXISTS GL_ENTRY_SOURCE;

CREATE TABLE GL_ENTRY_SOURCE (
       GL_ENTRY_SOURCE_ID int(10) unsigned NOT NULL AUTO_INCREMENT,
       DESCRIPTION varchar(100) NOT NULL,
       PRIMARY KEY (GL_ENTRY_SOURCE_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;