
-- Description: Create script for INVOICE_IMPORTATION_DETAILS table.

DROP TABLE IF EXISTS INVOICE_IMPORTATION_DETAILS;
CREATE TABLE INVOICE_IMPORTATION_DETAILS (
	INVOICE_IMPORTATION_DETAILS_ID int(10) unsigned NOT NULL AUTO_INCREMENT,
	AP_INVOICE_ID int(10) unsigned NOT NULL,
	IMPORT_ENTRY_NO varchar(100) DEFAULT NULL,
	ASSESSMENT_RELEASE_DATE date DEFAULT NULL,
	REGISTERED_NAME varchar(100) DEFAULT NULL,
	IMPORTATION_DATE date DEFAULT NULL,
	COUNTRY_OF_ORIGIN varchar(100) DEFAULT NULL,
	TOTAL_LANDED_COST double DEFAULT 0,
	DUTIABLE_VALUE double DEFAULT 0,
	CHARGES_FROM_CUSTOM double DEFAULT 0,
	TAXABLE_IMPORT double DEFAULT 0,
	EXEMPT_IMPORT double DEFAULT 0,
	OR_NUMBER varchar(100) DEFAULT NULL,
	PAYMENT_DATE date DEFAULT NULL,
	PRIMARY KEY (INVOICE_IMPORTATION_DETAILS_ID),
	KEY FK_IID_AP_INVOICE_ID (AP_INVOICE_ID),
	CONSTRAINT FK_IID_AP_INVOICE_ID FOREIGN KEY (AP_INVOICE_ID) REFERENCES AP_INVOICE (AP_INVOICE_ID)
) Engine=InnoDB DEFAULT CHARSET=utf8;