
-- Description:  Create script for KEY_CODE table.

DROP TABLE IF EXISTS KEY_CODE;

CREATE TABLE KEY_CODE (
       KEY_CODE_ID int(10) unsigned NOT NULL AUTO_INCREMENT,
       KEY_CODE varchar(25) NOT NULL,
       USER_ID int(10) unsigned DEFAULT NULL,
       IS_USED tinyint(1) NOT NULL,
       ACTIVE tinyint(1) NOT NULL,
       CREATED_BY int(10) unsigned NOT NULL,
       CREATED_DATE timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
       UPDATED_BY int(10) unsigned NOT NULL,
       UPDATED_DATE timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
       PRIMARY KEY (KEY_CODE_ID),
       KEY FK_KEY_CODE_CREATED_BY (CREATED_BY),
       KEY FK_KEY_CODE_UPDATED_BY (UPDATED_BY),
       KEY FK_KEY_CODE_USER_ID (USER_ID),
       CONSTRAINT FK_KEY_CODE_CREATED_BY FOREIGN KEY (CREATED_BY) REFERENCES USER (USER_ID),
       CONSTRAINT FK_KEY_CODE_UPDATED_BY FOREIGN KEY (UPDATED_BY) REFERENCES USER (USER_ID),
       CONSTRAINT FK_KEY_CODE_USER_ID FOREIGN KEY (USER_ID) REFERENCES USER (USER_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
