
-- Description: sql script in creating LP_LINE table.

DROP TABLE IF EXISTS LP_LINE;

CREATE TABLE LP_LINE (
  LP_LINE_ID int(10) unsigned NOT NULL AUTO_INCREMENT,
  LOAN_PROCEEDS_ID int(10) unsigned NOT NULL,
  ACCOUNT_COMBINATION_ID int(10) unsigned NOT NULL,
  EB_OBJECT_ID int(10) unsigned DEFAULT NULL,
  AMOUNT double NOT NULL,
  DESCRIPTION text,
  TAX_TYPE_ID int(10) unsigned DEFAULT NULL,
  VAT_AMOUNT double DEFAULT '0',
  GROSS_AMOUNT double DEFAULT '0',
  PRIMARY KEY (LP_LINE_ID),
  KEY FK_LP_LINE_LOAN_PROCEEDS_ID (LOAN_PROCEEDS_ID),
  KEY FK_LP_LINE_ACCOUNT_COMBINATION_ID (ACCOUNT_COMBINATION_ID),
  KEY FK_LP_LINE_EB_OBJECT_ID (EB_OBJECT_ID),
  KEY FK_LP_LINE_TAX_TYPE_ID (TAX_TYPE_ID),
  CONSTRAINT FK_LP_LINE_ACCOUNT_COMBINATION FOREIGN KEY (ACCOUNT_COMBINATION_ID)
    REFERENCES ACCOUNT_COMBINATION (ACCOUNT_COMBINATION_ID),
  CONSTRAINT FK_LP_LINE_EB_OBJECT_ID FOREIGN KEY (EB_OBJECT_ID)
    REFERENCES EB_OBJECT (EB_OBJECT_ID),
  CONSTRAINT FK_LP_LINE_LOAN_PROCEEDS_ID FOREIGN KEY (LOAN_PROCEEDS_ID)
    REFERENCES LOAN_PROCEEDS (LOAN_PROCEEDS_ID),
  CONSTRAINT FK_LP_LINE_TAX_TYPE_ID FOREIGN KEY (TAX_TYPE_ID)
    REFERENCES TAX_TYPE (TAX_TYPE_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
