
-- Description: sql script in creating NORMAL_BALANCE table.

DROP TABLE IF EXISTS NORMAL_BALANCE;

CREATE TABLE NORMAL_BALANCE (
       NORMAL_BALANCE_ID int(10) unsigned NOT NULL AUTO_INCREMENT,
       NAME varchar(15) NOT NULL,
       PRIMARY KEY (NORMAL_BALANCE_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;