
-- Description: Sql script for creating PAYMENT_TYPE table

DROP TABLE IF EXISTS PAYMENT_TYPE;

CREATE TABLE PAYMENT_TYPE (
	PAYMENT_TYPE_ID INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
	NAME varchar(20) NOT NULL,
	CREATED_BY INT(10) UNSIGNED NOT NULL,
	CREATED_DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	UPDATED_BY INT(10) UNSIGNED NOT NULL,
	UPDATED_DATE TIMESTAMP NOT NULL DEFAULT '0000-00-00 00:00:00',
	PRIMARY KEY (PAYMENT_TYPE_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;