
-- Description: Sql script for creating PRODUCT_LINE table

DROP TABLE IF EXISTS PRODUCT_LINE;

CREATE TABLE PRODUCT_LINE (
	PRODUCT_LINE_ID int(10) unsigned NOT NULL AUTO_INCREMENT,
	MAIN_ITEM_ID int(10)  unsigned NOT NULL,
	MENU tinyint(1) NOT NULL,
	ACTIVE tinyint(1) NOT NULL,
	CREATED_BY int(10) unsigned NOT NULL,
	CREATED_DATE timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
	UPDATED_BY int(10) unsigned NOT NULL,
	UPDATED_DATE timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
	PRIMARY KEY (PRODUCT_LINE_ID),
	KEY FK_PRODUCT_LINE_MAIN_ITEM_ID (MAIN_ITEM_ID),
	KEY FK_PRODUCT_LINE_CREATED_BY (CREATED_BY),
	KEY FK_PRODUCT_LINE_UPDATED_BY (UPDATED_BY),
	CONSTRAINT FK_PRODUCT_LINE_MAIN_ITEM_ID FOREIGN KEY (MAIN_ITEM_ID) REFERENCES ITEM (ITEM_ID),
	CONSTRAINT FK_PRODUCT_LINE_CREATED_BY FOREIGN KEY (CREATED_BY) REFERENCES USER (USER_ID),
	CONSTRAINT FK_PRODUCT_LINE_UPDATED_BY FOREIGN KEY (UPDATED_BY) REFERENCES USER (USER_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;