
-- Description: Sql script for creating PRODUCT_LINE_ITEM table

DROP TABLE IF EXISTS PRODUCT_LINE_ITEM; 

CREATE TABLE PRODUCT_LINE_ITEM (
	PRODUCT_LINE_ITEM_ID int(10) unsigned NOT NULL AUTO_INCREMENT,
	PRODUCT_LINE_ID int(10) unsigned NOT NULL,
	ITEM_ID int(10) unsigned NOT NULL,
	QUANTITY double NOT NULL,
	PRIMARY KEY (PRODUCT_LINE_ITEM_ID),
	KEY FK_PDI_ITEM_ID (ITEM_ID),
	CONSTRAINT FK_PDI_ITEM_ID FOREIGN KEY (ITEM_ID) REFERENCES ITEM (ITEM_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;