
-- Description: sql script in creating RECEIPT_METHOD table.

DROP TABLE IF EXISTS RECEIPT_METHOD;

CREATE TABLE `RECEIPT_METHOD` (
  `RECEIPT_METHOD_ID` int(10) NOT NULL DEFAULT '0',
  `NAME` varchar(100) NOT NULL,
  `COMPANY_ID` int(10) unsigned NOT NULL,
  `DEBIT_ACCOUNT_COMBINATION_ID` int(10) unsigned DEFAULT NULL,
  `CREDIT_ACCOUNT_COMBINATION_ID` int(10) unsigned NOT NULL,
  `BANK_ACCOUNT_ID` int(10) unsigned DEFAULT NULL,
  `ACTIVE` tinyint(1) NOT NULL,
  `CREATED_BY` int(10) unsigned NOT NULL,
  `CREATED_DATE` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_BY` int(10) unsigned NOT NULL,
  `UPDATED_DATE` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  PRIMARY KEY (`RECEIPT_METHOD_ID`),
  KEY `FK_RM_CREATED_BY` (`CREATED_BY`),
  KEY `FK_RM_UPDATED_BY` (`UPDATED_BY`),
  KEY `FK_RM_COMPANY_ID` (`COMPANY_ID`),
  KEY `FK_RM_DEBIT_ACCOUNT_COMBINATION` (`DEBIT_ACCOUNT_COMBINATION_ID`),
  KEY `FK_RM_CREDIT_ACCOUNT_COMBINATION` (`CREDIT_ACCOUNT_COMBINATION_ID`),
  KEY `FK_RM_BANK_ACCOUNT` (`BANK_ACCOUNT_ID`),
  CONSTRAINT `FK_RM_BANK_ACCOUNT` FOREIGN KEY (`BANK_ACCOUNT_ID`) REFERENCES `BANK_ACCOUNT` (`BANK_ACCOUNT_ID`),
  CONSTRAINT `FK_RM_COMPANY_ID` FOREIGN KEY (`COMPANY_ID`) REFERENCES `COMPANY` (`COMPANY_ID`),
  CONSTRAINT `FK_RM_CREATED_BY` FOREIGN KEY (`CREATED_BY`) REFERENCES `USER` (`USER_ID`),
  CONSTRAINT `FK_RM_CREDIT_ACCOUNT_COMBINATION` FOREIGN KEY (`CREDIT_ACCOUNT_COMBINATION_ID`) REFERENCES `ACCOUNT_COMBINATION` (`ACCOUNT_COMBINATION_ID`),
  CONSTRAINT `FK_RM_DEBIT_ACCOUNT_COMBINATION` FOREIGN KEY (`DEBIT_ACCOUNT_COMBINATION_ID`) REFERENCES `ACCOUNT_COMBINATION` (`ACCOUNT_COMBINATION_ID`),
  CONSTRAINT `FK_RM_UPDATED_BY` FOREIGN KEY (`UPDATED_BY`) REFERENCES `USER` (`USER_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
