
-- Description	: SQL script in creating SALES_PERSONNEL table

DROP TABLE IF EXISTS SALES_PERSONNEL;
CREATE TABLE SALES_PERSONNEL (
	SALES_PERSONNEL_ID int(10) unsigned NOT NULL AUTO_INCREMENT,
	COMPANY_ID int(10) unsigned NOT NULL,
	NAME varchar(50) NOT NULL,
	CONTACT_NUMBER varchar(20) NOT NULL,
	ADDRESS text,
	ACTIVE tinyint(1) NOT NULL,
	CREATED_BY int(10) unsigned NOT NULL,
	CREATED_DATE timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
	UPDATED_BY int(10) unsigned NOT NULL,
	UPDATED_DATE timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
	PRIMARY KEY (SALES_PERSONNEL_ID),
	KEY FK_SALES_PERSONNEL_COMPANY_ID (COMPANY_ID),
	KEY FK_SALES_PERSONNEL_CREATED_BY (CREATED_BY),
	KEY FK_SALES_PERSONNEL_UPDATED_BY (UPDATED_BY),
	CONSTRAINT FK_SALES_PERSONNEL_COMPANY_ID FOREIGN KEY (COMPANY_ID) REFERENCES COMPANY (COMPANY_ID),
	CONSTRAINT FK_SALES_PERSONNEL_CREATED_BY FOREIGN KEY (CREATED_BY) REFERENCES USER (USER_ID),
	CONSTRAINT FK_SALES_PERSONNEL_UPDATED_BY FOREIGN KEY (UPDATED_BY) REFERENCES USER (USER_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;