
-- Description: sql script in creating SUPPLIER_ACCOUNT

DROP TABLE IF EXISTS SUPPLIER_ACCOUNT;

CREATE TABLE SUPPLIER_ACCOUNT (
       SUPPLIER_ACCOUNT_ID int(10) unsigned NOT NULL AUTO_INCREMENT,
       SUPPLIER_ID int(10) unsigned NOT NULL,
       NAME varchar(100) NOT NULL,
       COMPANY_ID int(10) unsigned NOT NULL,
       DEFAULT_DEBIT_AC_ID int(10) unsigned, -- AC- ACOUNT COMBINATION
       DEFAULT_CREDIT_AC_ID int(10) unsigned NOT NULL,
       TERM_ID int(10) unsigned NOT NULL,
       ACTIVE tinyint(1) NOT NULL,
       CREATED_BY int(10) unsigned NOT NULL,
       CREATED_DATE timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
       UPDATED_BY int(10) unsigned NOT NULL,
       UPDATED_DATE timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
       PRIMARY KEY (SUPPLIER_ACCOUNT_ID),
       KEY FK_SUPPLIER_ACCOUNT_SUPPLIER_ID (SUPPLIER_ID),
       KEY FK_SUPPLIER_ACCOUNT_COMPANY_ID (COMPANY_ID),
       KEY FK_SUPPLIER_ACCOUNT_DEFAULT_DEBIT_AC_ID (DEFAULT_DEBIT_AC_ID),
       KEY FK_SUPPLIER_ACCOUNT_DEFAULT_CREDIT_AC_ID (DEFAULT_CREDIT_AC_ID),
       KEY FK_SUPPLIER_ACCOUNT_TERM_ID (TERM_ID),
       KEY FK_SUPPLIER_ACCOUNT_CREATED_BY (CREATED_BY),
       KEY FK_SUPPLIER_ACCOUNT_UPDATED_BY (UPDATED_BY),
       CONSTRAINT FK_AR_SUPPLIER_EL_SL_KEY_ID FOREIGN KEY (SUPPLIER_ID) REFERENCES SUPPLIER (SUPPLIER_ID),
       CONSTRAINT FK_AR_SUPPLIER_COMPANY_ID FOREIGN KEY (COMPANY_ID) REFERENCES COMPANY (COMPANY_ID),
       CONSTRAINT FK_AR_SUPPLIER_DEFAULT_DEBIT_AC_ID FOREIGN KEY (DEFAULT_DEBIT_AC_ID) REFERENCES ACCOUNT_COMBINATION (ACCOUNT_COMBINATION_ID),
       CONSTRAINT FK_AR_SUPPLIER_DEFAULT_CREDIT_AC_ID FOREIGN KEY (DEFAULT_CREDIT_AC_ID) REFERENCES ACCOUNT_COMBINATION (ACCOUNT_COMBINATION_ID),
       CONSTRAINT FK_SUPPLIER_ACCOUNT_TERM_ID FOREIGN KEY (TERM_ID) REFERENCES TERM (TERM_ID),
       CONSTRAINT FK_AR_SUPPLIER_CREATED_BY FOREIGN KEY (CREATED_BY) REFERENCES USER (USER_ID),
       CONSTRAINT FK_AR_SUPPLIER_UPDATED_BY FOREIGN KEY (UPDATED_BY) REFERENCES USER (USER_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
