
-- Description: Sql script for creating SUPPLIER_ACCOUNT_SETTING table

CREATE TABLE SUPPLIER_ACCOUNT_SETTING (
  SUPPLIER_ACCOUNT_SETTING_ID int(10) unsigned NOT NULL AUTO_INCREMENT,
  SUPPLIER_ID int(10) unsigned NOT NULL,
  SUPPLIER_ACCOUNT_ID int(10) unsigned NOT NULL,
  NAME varchar(100) NOT NULL,
  DEFAULT_CREDIT_AC_ID int(10) unsigned NOT NULL,
  CREATED_BY int(10) unsigned NOT NULL,
  CREATED_DATE timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UPDATED_BY int(10) unsigned NOT NULL,
  UPDATED_DATE timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  PRIMARY KEY (SUPPLIER_ACCOUNT_SETTING_ID),
  KEY FK_SACCTS_SUPPLIER_ID (SUPPLIER_ID),
  KEY FK_SACCTS_SUPPLIER_ACCOUNT_ID (SUPPLIER_ACCOUNT_ID),
  KEY FK_SACCTS_DEFAULT_CREDIT_AC_ID (DEFAULT_CREDIT_AC_ID),
  KEY FK_SACCTS_CREATED_BY (CREATED_BY),
  KEY FK_SACCTS_UPDATED_BY (UPDATED_BY),
  CONSTRAINT FK_SACCTS_SUPPLIER_ID FOREIGN KEY (SUPPLIER_ID) REFERENCES SUPPLIER (SUPPLIER_ID),
  CONSTRAINT FK_SACCTS_SUPPLIER_ACCOUNT_ID FOREIGN KEY (SUPPLIER_ACCOUNT_ID) REFERENCES SUPPLIER_ACCOUNT (SUPPLIER_ACCOUNT_ID),
  CONSTRAINT FK_SACCTS_DEFAULT_CREDIT_AC_ID FOREIGN KEY (DEFAULT_CREDIT_AC_ID) REFERENCES ACCOUNT_COMBINATION (ACCOUNT_COMBINATION_ID),
  CONSTRAINT FK_SACCTS_CREATED_BY FOREIGN KEY (CREATED_BY) REFERENCES USER (USER_ID),
  CONSTRAINT FK_SACCTS_UPDATED_BY FOREIGN KEY (UPDATED_BY) REFERENCES USER (USER_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8