
-- Description: SQL script in creating the TIME_PERIOD table.

DROP TABLE IF EXISTS TIME_PERIOD;

CREATE TABLE TIME_PERIOD (
   TIME_PERIOD_ID INT(10) NOT NULL AUTO_INCREMENT,
   TIME_PERIOD_STATUS_ID INT(10) NOT NULL,
   NAME VARCHAR(50) NOT NULL,
   DATE_FROM DATE NOT NULL,
   DATE_TO DATE NOT NULL,
   CREATED_BY INT(10) UNSIGNED NOT NULL,
   CREATED_DATE TIMESTAMP NOT NULL,
   UPDATED_BY INT(10) UNSIGNED NOT NULL,
   UPDATED_DATE TIMESTAMP NOT NULL,
   PRIMARY KEY (TIME_PERIOD_ID),
   KEY FK_TP_CREATED_BY (CREATED_BY),
   KEY FK_TP_UPDATED_BY (UPDATED_BY),
   CONSTRAINT FK_TP_CREATED_BY FOREIGN KEY (CREATED_BY) REFERENCES USER (USER_ID),
   CONSTRAINT FK_TP_UPDATED_BY FOREIGN KEY (UPDATED_BY) REFERENCES USER (USER_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;