
-- Description: SQL script in creating the TIME_PERIOD_STATUS table.

DROP TABLE IF EXISTS TIME_PERIOD_STATUS;

CREATE TABLE TIME_PERIOD_STATUS (
   TIME_PERIOD_STATUS_ID INT(10) NOT NULL AUTO_INCREMENT,
   NAME VARCHAR(15),
   PRIMARY KEY (TIME_PERIOD_STATUS_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;