
-- Description: Sql script in creating USER_CUSTODIAN table.

DROP TABLE IF EXISTS USER_CUSTODIAN;

CREATE TABLE USER_CUSTODIAN (
	USER_CUSTODIAN_ID int(10) unsigned NOT NULL AUTO_INCREMENT,
	COMPANY_ID int(10) unsigned NOT NULL,
	DIVISION_ID int(10) unsigned NOT NULL,
	CUSTODIAN_ACCOUNT_ID int(10) unsigned NOT NULL,
	ACTIVE tinyint(1) NOT NULL,
	CREATED_BY int(10) unsigned NOT NULL,
	CREATED_DATE timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
	UPDATED_BY int(10) unsigned NOT NULL,
	UPDATED_DATE timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
	PRIMARY KEY (USER_CUSTODIAN_ID),
	KEY FK_USER_CUSTODIAN_COMPANY_ID (COMPANY_ID),
	KEY FK_USER_CUSTODIAN_DIVISION_ID (DIVISION_ID),
	KEY FK_USER_CUSTODIAN_CUSTODIAN_ACCOUNT_ID (CUSTODIAN_ACCOUNT_ID),
	KEY FK_USER_CUSTODIAN_CREATED_BY (CREATED_BY),
	KEY FK_USER_CUSTODIAN_UPDATED_BY (UPDATED_BY),
	CONSTRAINT FK_USER_CUSTODIAN_COMPANY_ID FOREIGN KEY (COMPANY_ID) REFERENCES COMPANY (COMPANY_ID),
	CONSTRAINT FK_USER_CUSTODIAN_DIVISION_ID FOREIGN KEY (DIVISION_ID) REFERENCES DIVISION (DIVISION_ID),
	CONSTRAINT FK_USER_CUSTODIAN_CUSTODIAN_ACCOUNT_ID FOREIGN KEY (CUSTODIAN_ACCOUNT_ID) REFERENCES CUSTODIAN_ACCOUNT (CUSTODIAN_ACCOUNT_ID),
	CONSTRAINT FK_USER_CUSTODIAN_CREATED_BY FOREIGN KEY (CREATED_BY) REFERENCES USER (USER_ID),
	CONSTRAINT FK_USER_CUSTODIAN_UPDATED_BY FOREIGN KEY (UPDATED_BY) REFERENCES USER (USER_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;