
-- Description: Sql script in creating USER_CUSTODIAN_LINES table.

DROP TABLE IF EXISTS USER_CUSTODIAN_LINES;

CREATE TABLE USER_CUSTODIAN_LINES (
	USER_CUSTODIAN_LINES_ID int(10) unsigned NOT NULL AUTO_INCREMENT,
	USER_CUSTODIAN_ID int(10) unsigned NOT NULL,
	USER_ID int(10) unsigned NOT NULL,
	PRIMARY KEY (USER_CUSTODIAN_LINES_ID),
	KEY FK_USER_CUSTODIAN_LINES_USER_CUSTODIAN_ID (USER_CUSTODIAN_ID),
	KEY FK_USER_CUSTODIAN_LINES_USER_ID (USER_ID),
	CONSTRAINT FK_USER_CUSTODIAN_LINES_USER_CUSTODIAN_ID FOREIGN KEY (USER_CUSTODIAN_ID) REFERENCES USER_CUSTODIAN (USER_CUSTODIAN_ID),
	CONSTRAINT FK_USER_CUSTODIAN_LINES_USER_ID FOREIGN KEY (USER_ID) REFERENCES USER (USER_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;