
-- Description	: Create script for VAT_ACCOUNT_SETUP table.

DROP TABLE IF EXISTS VAT_ACCOUNT_SETUP;

CREATE TABLE VAT_ACCOUNT_SETUP (
	VAT_ACCOUNT_SETUP_ID int(10) unsigned NOT NULL AUTO_INCREMENT,
	COMPANY_ID int(10) unsigned NOT NULL,
	DIVISION_ID int(10) unsigned DEFAULT NULL,
	INPUT_VAT_AC_ID int(10) unsigned NOT NULL,
	OUTPUT_VAT_AC_ID int(10) unsigned NOT NULL,
	ACTIVE tinyint(1) DEFAULT '1',
	CREATED_BY int(10) unsigned NOT NULL,
	CREATED_DATE timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
	UPDATED_BY int(10) unsigned NOT NULL,
	UPDATED_DATE timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
	PRIMARY KEY (VAT_ACCOUNT_SETUP_ID),
	KEY FK_VAS_COMPANY_ID (COMPANY_ID),
	KEY FK_VAS_DIVISION_ID (DIVISION_ID),
	KEY FK_VAS_INPUT_VAT_AC_ID (INPUT_VAT_AC_ID),
	KEY FK_VAS_OUTPUT_VAT_AC_ID (OUTPUT_VAT_AC_ID),
	KEY FK_VAS_CREATED_BY (CREATED_BY),
	KEY FK_VAS_UPDATED_BY (UPDATED_BY),
	CONSTRAINT FK_VAS_COMPANY_ID FOREIGN KEY (COMPANY_ID) REFERENCES COMPANY (COMPANY_ID),
	CONSTRAINT FK_VAS_DIVISION_ID FOREIGN KEY (DIVISION_ID) REFERENCES DIVISION (DIVISION_ID),
	CONSTRAINT FK_VAS_INPUT_VAT_AC_ID FOREIGN KEY (INPUT_VAT_AC_ID) REFERENCES ACCOUNT_COMBINATION (ACCOUNT_COMBINATION_ID),
	CONSTRAINT FK_VAS_OUTPUT_VAT_AC_ID FOREIGN KEY (OUTPUT_VAT_AC_ID) REFERENCES ACCOUNT_COMBINATION (ACCOUNT_COMBINATION_ID),
	CONSTRAINT FK_VAS_CREATED_BY FOREIGN KEY (CREATED_BY) REFERENCES USER (USER_ID),
	CONSTRAINT FK_VAS_UPDATED_BY FOREIGN KEY (UPDATED_BY) REFERENCES USER (USER_ID)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;