
-- Description: SQL script in creating the withholding tax account setting table

DROP TABLE IF EXISTS WT_ACCOUNT_SETTING;

CREATE TABLE WT_ACCOUNT_SETTING (
  WT_ACCOUNT_SETTING_ID int(10) unsigned NOT NULL AUTO_INCREMENT,
  COMPANY_ID int(10) unsigned NOT NULL,
  NAME varchar(50) NOT NULL,
  VALUE double NOT NULL,
  ACCOUNT_COMBINATION_ID int(10) unsigned NOT NULL,
  ACTIVE tinyint(1) DEFAULT '0',
  ORDER_ID int(3) unsigned NOT NULL,
  PRIMARY KEY (WT_ACCOUNT_SETTING_ID),
  KEY FK_WTAS_COMPANY_ID (COMPANY_ID),
  KEY FK_WTAS_ACCT_COMBI_ID (ACCOUNT_COMBINATION_ID),
  CONSTRAINT FK_WTAS_COMPANY_ID FOREIGN KEY (COMPANY_ID) REFERENCES COMPANY (COMPANY_ID),
  CONSTRAINT FK_WTAS_ACCT_COMBI_ID FOREIGN KEY (ACCOUNT_COMBINATION_ID) REFERENCES ACCOUNT_COMBINATION (ACCOUNT_COMBINATION_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;