
-- Description : Create script for FLEET_TOOL_CONDITION Table.

DROP TABLE IF EXISTS FLEET_TOOL_CONDITION;

CREATE TABLE FLEET_TOOL_CONDITION(
	FLEET_TOOL_CONDITION_ID INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
	EB_OBJECT_ID INT(10) UNSIGNED NOT NULL,
	ITEM_ID INT(10) UNSIGNED NOT NULL,
	TOOL_CONDITION TEXT,
	STATUS TINYINT(1) NOT NULL,
	ACTIVE TINYINT(1) NOT NULL,
	CREATED_BY INT(10) UNSIGNED NOT NULL,
	CREATED_DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	UPDATED_BY INT(10) UNSIGNED NOT NULL,
	UPDATED_DATE TIMESTAMP NOT NULL DEFAULT '0000-00-00 00:00:00',
	PRIMARY KEY (FLEET_TOOL_CONDITION_ID),
	KEY FK_FLEET_TOOL_CONDITION_EB_OBJECT_ID (EB_OBJECT_ID),
	KEY FK_FLEET_TOOL_CONDITION_ITEM_ID (ITEM_ID),
	KEY FK_FLEET_TOOL_CONDITION_CREATED_BY (CREATED_BY),
	KEY FK_FLEET_TOOL_CONDITION_UPDATED_BY (UPDATED_BY),
	CONSTRAINT FK_FLEET_TOOL_CONDITION_EB_OBJECT_ID FOREIGN KEY (EB_OBJECT_ID) REFERENCES EB_OBJECT (EB_OBJECT_ID),
	CONSTRAINT FK_FLEET_TOOL_CONDITION_ITEM_ID FOREIGN KEY (ITEM_ID) REFERENCES ITEM (ITEM_ID),
	CONSTRAINT FK_FLEET_TOOL_CONDITION_CREATED_BY FOREIGN KEY (CREATED_BY) REFERENCES USER (USER_ID),
	CONSTRAINT FK_FLEET_TOOL_CONDITION_UPDATED_BY FOREIGN KEY (UPDATED_BY) REFERENCES USER (USER_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;