
-- Description: Sql script for creating INCIDENT table

DROP TABLE IF EXISTS FLEET_CAPTAIN_MDM;

CREATE TABLE FLEET_CAPTAIN_MDM (
	FLEET_CAPTAIN_MDM_ID INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
	EB_OBJECT_ID INT(10) UNSIGNED NOT NULL,
	DATE DATE NOT NULL,
	NAME VARCHAR(100) NOT NULL,
	POSITION VARCHAR(100) NOT NULL,
	LICENSE_NO VARCHAR(100) DEFAULT NULL,
	LN_EXPIRATION_DATE DATE DEFAULT NULL,
	SEAMANS_BOOK VARCHAR(100) DEFAULT NULL,
	SB_EXPIRATION_DATE DATE DEFAULT NULL,
	FISHERIES VARCHAR(100) DEFAULT NULL,
	FL_EXPIRATION_DATE DATE DEFAULT NULL,
	PASSPORT VARCHAR(100) DEFAULT NULL,
	P_EXPIRATION_DATE DATE DEFAULT NULL,
	REMARKS TEXT,
	ACTIVE TINYINT(1) DEFAULT 1,
	CREATED_BY INT(10) UNSIGNED NOT NULL,
	CREATED_DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	UPDATED_BY INT(10) UNSIGNED NOT NULL,
	UPDATED_DATE TIMESTAMP NOT NULL DEFAULT '0000-00-00 00:00:00',
	PRIMARY KEY (FLEET_CAPTAIN_MDM_ID),
	KEY FK_FLEET_CAPTAIN_MDM_EB_OBJECT_ID (EB_OBJECT_ID),
	KEY FK_FLEET_CAPTAIN_MDM_CREATED_BY (CREATED_BY),
	KEY FK_FLEET_CAPTAIN_MDM_UPDATED_BY (UPDATED_BY),
	CONSTRAINT FK_FLEET_CAPTAIN_MDM_EB_OBJECT_ID FOREIGN KEY (EB_OBJECT_ID) REFERENCES EB_OBJECT (EB_OBJECT_ID),
	CONSTRAINT FK_FLEET_CAPTAIN_MDM_CREATED_BY FOREIGN KEY (CREATED_BY) REFERENCES USER (USER_ID),
	CONSTRAINT FK_FLEET_CAPTAIN_MDM_UPDATED_BY FOREIGN KEY (UPDATED_BY) REFERENCES USER (USER_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;