
-- Description: Sql script for creating FLEET_INSURANCE_PERMIT_RENEWAL table

DROP TABLE IF EXISTS FLEET_INSURANCE_PERMIT_RENEWAL;

CREATE TABLE `FLEET_INSURANCE_PERMIT_RENEWAL` (
  `FLEET_INSURANCE_PERMIT_RENEWAL_ID` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `REF_NO` varchar(20) DEFAULT NULL,
  `DESCRIPTION` varchar(100) DEFAULT NULL,
  `ISSUANCE_DATE` DATE DEFAULT NULL,
  `EXPIRATION_DATE` DATE DEFAULT NULL,
  `REMARKS` TEXT DEFAULT NULL,
  `ACTIVE` tinyint(1) NOT NULL,
  `EB_OBJECT_ID` int(10) unsigned DEFAULT NULL,
  `CREATED_BY` int(10) unsigned NOT NULL,
  `CREATED_DATE` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_BY` int(10) unsigned NOT NULL,
  `UPDATED_DATE` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  PRIMARY KEY (`FLEET_INSURANCE_PERMIT_RENEWAL_ID`),
  KEY `FK_FLEET_IPR_EB_OBJECT_ID` (`EB_OBJECT_ID`),
  KEY `FK_FLEET_IPR_CREATED_BY` (`CREATED_BY`),
  KEY `FK_FLEET_IPR_UPDATED_BY` (`UPDATED_BY`),
  CONSTRAINT `FK_FLEET_IPR_EB_OBJECT_ID` FOREIGN KEY (EB_OBJECT_ID) REFERENCES EB_OBJECT (EB_OBJECT_ID),
  CONSTRAINT `FK_FLEET_IPR_CREATED_BY` FOREIGN KEY (`CREATED_BY`) REFERENCES `USER` (`USER_ID`),
  CONSTRAINT `FK_FLEET_IPR_UPDATED_BY` FOREIGN KEY (`UPDATED_BY`) REFERENCES `USER` (`USER_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
