
-- Description: Create script for FLEET_DEFAULT_ACCOUNT Table.

CREATE TABLE FLEET_DEFAULT_ACCOUNT(
	FLEET_DEFAULT_ACCOUNT_ID int(10) unsigned NOT NULL AUTO_INCREMENT,
	ACCOUNT_ID int(10) unsigned NOT NULL,
	ACTIVE tinyint(1)  NOT NULL,
	PRIMARY KEY (FLEET_DEFAULT_ACCOUNT_ID),
	KEY FK_FDA_ACCOUNT (ACCOUNT_ID),
	CONSTRAINT FK_FDA_ACCOUNT FOREIGN KEY (ACCOUNT_ID) REFERENCES ACCOUNT (ACCOUNT_ID),
	KEY FK_FDA_CREATED_BY (CREATED_BY),
 	KEY FK_FDA_UPDATED_BY (UPDATED_BY),
	CREATED_BY int(10) unsigned NOT NULL,
 	CREATED_DATE timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  	UPDATED_BY int(10) unsigned NOT NULL,
  	UPDATED_DATE timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  	CONSTRAINT FK_FDA_CREATED_BY FOREIGN KEY (CREATED_BY) REFERENCES USER (USER_ID),
  	CONSTRAINT FK_FDA_UPDATED_BY FOREIGN KEY (UPDATED_BY) REFERENCES USER (USER_ID)
 ) ENGINE=InnoDB DEFAULT CHARSET=utf8;