
-- Description: Sql script for creating FLEET_MANNING_REQUIREMENT table

DROP TABLE IF EXISTS FLEET_MANNING_REQUIREMENT;

CREATE TABLE `FLEET_MANNING_REQUIREMENT` (
  `FLEET_MANNING_REQUIREMENT_ID` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `POSITION` varchar(50) DEFAULT NULL,
  `LICENSE` varchar(50) DEFAULT NULL,
  `NUMBER` varchar(50) DEFAULT NULL,
  `ACTIVE` tinyint(1) NOT NULL,
  `REMARKS` text DEFAULT NULL,
  `EB_OBJECT_ID` int(10) unsigned DEFAULT NULL,
  `CREATED_BY` int(10) unsigned NOT NULL,
  `CREATED_DATE` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_BY` int(10) unsigned NOT NULL,
  `UPDATED_DATE` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  PRIMARY KEY (`FLEET_MANNING_REQUIREMENT_ID`),
  KEY `FK_FLEET_MR_EB_OBJECT_ID` (`EB_OBJECT_ID`),
  KEY `FK_FLEET_MR__CREATED_BY` (`CREATED_BY`),
  KEY `FK_FLEET_MR__UPDATED_BY` (`UPDATED_BY`),
  CONSTRAINT `FK_FLEET_MR_EB_OBJECT_ID` FOREIGN KEY (EB_OBJECT_ID) REFERENCES EB_OBJECT (EB_OBJECT_ID),
  CONSTRAINT `FK_FLEET_MR__CREATED_BY` FOREIGN KEY (`CREATED_BY`) REFERENCES `USER` (`USER_ID`),
  CONSTRAINT `FK_FLEET_MR__UPDATED_BY` FOREIGN KEY (`UPDATED_BY`) REFERENCES `USER` (`USER_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;