
-- Description: Sql script for creating INCIDENT table

DROP TABLE IF EXISTS FLEET_INCIDENT;

CREATE TABLE FLEET_INCIDENT (
	FLEET_INCIDENT_ID INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
	EB_OBJECT_ID INT(10) UNSIGNED NOT NULL,
	DATE DATE NOT NULL,
	EMPLOYEE_NAME VARCHAR(100) NOT NULL,
	LOCATION VARCHAR(100) NOT NULL,
	CAUSE VARCHAR(100) NOT NULL,
	INSURANCE_CLAIMS VARCHAR(100) DEFAULT NULL,
	REMARKS TEXT,
	ACTIVE TINYINT(1) DEFAULT 1,
	CREATED_BY INT(10) UNSIGNED NOT NULL,
	CREATED_DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	UPDATED_BY INT(10) UNSIGNED NOT NULL,
	UPDATED_DATE TIMESTAMP NOT NULL DEFAULT '0000-00-00 00:00:00',
	PRIMARY KEY (FLEET_INCIDENT_ID),
	KEY FK_FLEET_INCIDENT_EB_OBJECT_ID (EB_OBJECT_ID),
	KEY FK_FLEET_INCIDENT_CREATED_BY (CREATED_BY),
	KEY FK_FLEET_INCIDENT_UPDATED_BY (UPDATED_BY),
	CONSTRAINT FK_FLEET_INCIDENT_EB_OBJECT_ID FOREIGN KEY (EB_OBJECT_ID) REFERENCES EB_OBJECT (EB_OBJECT_ID),
	CONSTRAINT FK_FLEET_INCIDENT_CREATED_BY FOREIGN KEY (CREATED_BY) REFERENCES USER (USER_ID),
	CONSTRAINT FK_FLEET_INCIDENT_UPDATED_BY FOREIGN KEY (UPDATED_BY) REFERENCES USER (USER_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;