
-- Description: Sql script for creating PREVENTIVE_MAINTENANCE_SCHEDULE table

DROP TABLE IF EXISTS PREVENTIVE_MAINTENANCE_SCHEDULE;

CREATE TABLE `PREVENTIVE_MAINTENANCE_SCHEDULE` (
  `PREVENTIVE_MAINTENANCE_SCHEDULE_ID` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `CHANGE_OIL_ENGINE` varchar(50) DEFAULT NULL,
  `OVERHAUL_ENGINE_MAIN` VARCHAR(50) DEFAULT NULL,
  `OVERHAUL_ENGINE_AUXILIARY` VARCHAR(50) DEFAULT NULL,
  `CHANGE_OIL_TRANSMISSION` varchar(50) DEFAULT NULL,
  `FILTER_FUEL` varchar(50) DEFAULT NULL,
  `FILTER_OIL` varchar(50) DEFAULT NULL,
  `FILTER_AIR` varchar(50) DEFAULT NULL,
  `FILTER_FANBELT` varchar(50) DEFAULT NULL,
  `NET` varchar(50) DEFAULT NULL,
  `ACTIVE` tinyint(1) NOT NULL,
  `IS_SCHEDULE` tinyint(1) NOT NULL,
  `EB_OBJECT_ID` int(10) unsigned DEFAULT NULL,
  `CREATED_BY` int(10) unsigned NOT NULL,
  `CREATED_DATE` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_BY` int(10) unsigned NOT NULL,
  `UPDATED_DATE` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  PRIMARY KEY (`PREVENTIVE_MAINTENANCE_SCHEDULE_ID`),
  KEY `FK_FLEET_PMS_EB_OBJECT_ID` (`EB_OBJECT_ID`),
  KEY `FK_FLEET_PMS_CREATED_BY` (`CREATED_BY`),
  KEY `FK_FLEET_PMS_UPDATED_BY` (`UPDATED_BY`),
  CONSTRAINT `FK_FLEET_PMS_EB_OBJECT_ID` FOREIGN KEY (EB_OBJECT_ID) REFERENCES EB_OBJECT (EB_OBJECT_ID),
  CONSTRAINT `FK_FLEET_PMS_CREATED_BY` FOREIGN KEY (`CREATED_BY`) REFERENCES `USER` (`USER_ID`),
  CONSTRAINT `FK_FLEET_PMS_UPDATED_BY` FOREIGN KEY (`UPDATED_BY`) REFERENCES `USER` (`USER_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;