
-- Description: Sql script for creating FLEET_DRY_DOCKING table

DROP TABLE IF EXISTS FLEET_DRY_DOCK;

CREATE TABLE FLEET_DRY_DOCK (
  FLEET_DRY_DOCK_ID INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  EB_OBJECT_ID INT(10) UNSIGNED DEFAULT NULL,
  DATE DATE DEFAULT NULL,
  CONTRACTOR VARCHAR(50) DEFAULT NULL,
  IS_ACTUAL TINYINT(1) DEFAULT NULL,
  ACTIVE TINYINT(1) NOT NULL,
  CREATED_BY INT(10) unsigned NOT NULL,
  CREATED_DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UPDATED_BY INT(10) unsigned NOT NULL,
  UPDATED_DATE TIMESTAMP NOT NULL DEFAULT '0000-00-00 00:00:00',
  PRIMARY KEY (FLEET_DRY_DOCK_ID),
  KEY FK_FLEET_DRY_DOCK_EB_OBJECT_ID (EB_OBJECT_ID),
  KEY FK_FLEET_DRY_DOCK_CREATED_BY (CREATED_BY),
  KEY FK_FLEET_DRY_DOCK_UPDATED_BY (UPDATED_BY),
  CONSTRAINT FK_FLEET_DRY_DOCK_EB_OBJECT_ID FOREIGN KEY (EB_OBJECT_ID) REFERENCES EB_OBJECT (EB_OBJECT_ID),
  CONSTRAINT FK_FLEET_DRY_DOCK_CREATED_BY FOREIGN KEY (CREATED_BY) REFERENCES USER (USER_ID),
  CONSTRAINT FK_FLEET_DRY_DOCK_UPDATED_BY FOREIGN KEY (UPDATED_BY) REFERENCES USER (USER_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;