
-- Description: Create script for FLEET_DRIVER Table.

CREATE TABLE FLEET_DRIVER(
	FLEET_DRIVER_ID INT(10) unsigned NOT NULL AUTO_INCREMENT,
	EB_OBJECT_ID INT(10) unsigned NOT NULL,
	DATE date default NULL,
	NAME varchar(100) NOT NULL,
	LICENSE_NO varchar(100) NOT NULL,
	EXPIRATION_DATE date default NULL,
	REMARKS text,
	ACTIVE tinyint(1) DEFAULT 1,
	PRIMARY KEY (FLEET_DRIVER_ID),
	CREATED_BY INT(10) UNSIGNED NOT NULL,
	CREATED_DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	UPDATED_BY INT(10) UNSIGNED NOT NULL,
	UPDATED_DATE TIMESTAMP NOT NULL DEFAULT '0000-00-00 00:00:00',
	KEY FK_FP_DRIVER_EB_OBJECT_ID (EB_OBJECT_ID),
	KEY FK_FP_CREATED_BY (CREATED_BY),
	KEY FK_FP_UPDATED_BY (UPDATED_BY),
	CONSTRAINT FK_FP_DRIVER_EB_OBJECT_ID FOREIGN KEY (EB_OBJECT_ID) REFERENCES EB_OBJECT (EB_OBJECT_ID),
	CONSTRAINT FK_FP_CREATED_BY FOREIGN KEY (CREATED_BY) REFERENCES USER (USER_ID),
	CONSTRAINT FK_FP_UPDATED_BY FOREIGN KEY (UPDATED_BY) REFERENCES USER (USER_ID)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;