
-- Description: Sql script for creating DIRECT_PAYMENT table

DROP TABLE IF EXISTS DIRECT_PAYMENT;

CREATE TABLE `DIRECT_PAYMENT` (
	`DIRECT_PAYMENT_ID` int(10) unsigned NOT NULL AUTO_INCREMENT,
	`INVOICE_NUMBER` varchar(100) DEFAULT NULL,
	`TERM_ID` int(10) unsigned DEFAULT NULL,
	`EB_OBJECT_ID` int(10) unsigned DEFAULT NULL,
	`AP_PAYMENT_ID` int(10) unsigned DEFAULT NULL,
	`DIRECT_PAYMENT_TYPE_ID` int(10) unsigned DEFAULT NULL,
	`DESCRIPTION` text,
	PRIMARY KEY (`DIRECT_PAYMENT_ID`),
	KEY `FK_DIRECT_PAYMENT_TERM_ID` (`TERM_ID`),
	KEY `FK_DIRECT_PAYMENT_AP_PAYMENT_ID` (`AP_PAYMENT_ID`),
	KEY `FK_DIRECT_PAYMENT_EB_OBJECT_ID` (`EB_OBJECT_ID`),
	KEY `FK_DIRECT_PAYMENT_TYPE_ID` (`DIRECT_PAYMENT_TYPE_ID`),
	CONSTRAINT `FK_DIRECT_PAYMENT_EB_OBJECT_ID` FOREIGN KEY (`EB_OBJECT_ID`) REFERENCES `EB_OBJECT` (`EB_OBJECT_ID`),
	CONSTRAINT `FK_DIRECT_PAYMENT_AP_PAYMENT_ID` FOREIGN KEY (`AP_PAYMENT_ID`) REFERENCES `AP_PAYMENT` (`AP_PAYMENT_ID`),
	CONSTRAINT `FK_DIRECT_PAYMENT_TERM_ID` FOREIGN KEY (`TERM_ID`) REFERENCES `TERM` (`TERM_ID`),
	CONSTRAINT `FK_DIRECT_PAYMENT_TYPE_ID` FOREIGN KEY (`DIRECT_PAYMENT_TYPE_ID`) REFERENCES `DIRECT_PAYMENT_TYPE` (`DIRECT_PAYMENT_TYPE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;