
-- Description: Add DISCOUNT_AC_ID and AMOUNT in AR_LINE_SETUP table

ALTER TABLE AR_LINE_SETUP ADD DISCOUNT_AC_ID int(10) unsigned DEFAULT NULL AFTER ACCOUNT_COMBINATION_ID ,
ADD CONSTRAINT FK_AR_LINE_SETUP_DISCOUNT_AC_ID FOREIGN KEY (DISCOUNT_AC_ID) REFERENCES ACCOUNT_COMBINATION (ACCOUNT_COMBINATION_ID);

ALTER TABLE AR_LINE_SETUP ADD AMOUNT double DEFAULT 0 AFTER DISCOUNT_AC_ID;