
-- Description	: Add SALES_ORDER_ID in DELIVERY_RECEIPT table

ALTER TABLE DELIVERY_RECEIPT ADD SALES_ORDER_ID int(10) unsigned DEFAULT NULL ,
ADD CONSTRAINT FK_DELIVERY_RECEIPT_SALES_ORDER_ID FOREIGN KEY (SALES_ORDER_ID) REFERENCES SALES_ORDER (SALES_ORDER_ID);
