
-- Description	: Add DATE_CLEARED in AP_PAYMENT table

ALTER TABLE AP_PAYMENT ADD COLUMN DIVISION_ID int(10) unsigned DEFAULT NULL,
ADD CONSTRAINT `FK_AP_PAYMENT_DIVISION_ID` FOREIGN KEY (`DIVISION_ID`) REFERENCES DIVISION (DIVISION_ID);

ALTER TABLE AP_PAYMENT ADD COLUMN CURRENCY_ID int(10) unsigned DEFAULT NULL,
ADD CONSTRAINT `FK_PAYMENT_CURRENCY_ID` FOREIGN KEY (`CURRENCY_ID`) REFERENCES CURRENCY (CURRENCY_ID);

ALTER TABLE AP_PAYMENT ADD COLUMN CURRENCY_RATE_ID int(10) unsigned DEFAULT NULL,
ADD CONSTRAINT `FK_PAYMENT_CURRENCY_RATE_ID` FOREIGN KEY (`CURRENCY_RATE_ID`) REFERENCES CURRENCY_RATE (CURRENCY_RATE_ID);

ALTER TABLE AP_PAYMENT ADD COLUMN CURRENCY_RATE_VALUE double DEFAULT 0;
ALTER TABLE AP_PAYMENT ADD COLUMN OFFICIAL_RECEIPT varchar(30) DEFAULT NULL;
ALTER TABLE AP_PAYMENT ADD COLUMN REMARKS TEXT;
ALTER TABLE AP_PAYMENT ADD COLUMN DATE_CLEARED DATE DEFAULT NULL;