
-- Description	: update CUSTOMER_ADVANCE_PAYMENT table

ALTER TABLE CUSTOMER_ADVANCE_PAYMENT ADD COLUMN DIVISION_ID INT(10) UNSIGNED DEFAULT NULL,
ADD CONSTRAINT FK_CUSTOMER_ADVANCE_PAYMENT_DIVISION_ID FOREIGN KEY (DIVISION_ID) REFERENCES DIVISION (DIVISION_ID);

ALTER TABLE CUSTOMER_ADVANCE_PAYMENT ADD COLUMN CURRENCY_ID INT(10) UNSIGNED DEFAULT NULL,
ADD CONSTRAINT FK_CUSTOMER_ADVANCE_PAYMENT_CURRENCY_ID FOREIGN KEY (CURRENCY_ID) REFERENCES CURRENCY (CURRENCY_ID);

ALTER TABLE CUSTOMER_ADVANCE_PAYMENT ADD COLUMN CURRENCY_RATE_ID INT(10) UNSIGNED DEFAULT NULL,
ADD CONSTRAINT FK_CUSTOMER_ADVANCE_PAYMENT_CURRENCY_RATE_ID FOREIGN KEY (CURRENCY_RATE_ID) REFERENCES CURRENCY_RATE (CURRENCY_RATE_ID);

ALTER TABLE CUSTOMER_ADVANCE_PAYMENT ADD COLUMN CURRENCY_RATE_VALUE DOUBLE DEFAULT '0';

ALTER TABLE CUSTOMER_ADVANCE_PAYMENT ADD COLUMN PO_NUMBER varchar(50) DEFAULT NULL;

ALTER TABLE CUSTOMER_ADVANCE_PAYMENT ADD COLUMN AMOUNT DOUBLE DEFAULT '0';

ALTER TABLE CUSTOMER_ADVANCE_PAYMENT MODIFY COLUMN AR_RECEIPT_TYPE_ID int(10) unsigned DEFAULT NULL;
ALTER TABLE CUSTOMER_ADVANCE_PAYMENT MODIFY COLUMN CASH DOUBLE DEFAULT NULL;
