
-- Description	: update AR_RECEIPT table

ALTER TABLE AR_RECEIPT ADD COLUMN DIVISION_ID INT(10) UNSIGNED DEFAULT NULL,
ADD CONSTRAINT FK_AR_RECEIPT_DIVISION_ID FOREIGN KEY (DIVISION_ID) REFERENCES DIVISION (DIVISION_ID);

ALTER TABLE AR_RECEIPT ADD COLUMN CURRENCY_ID INT(10) UNSIGNED DEFAULT NULL,
ADD CONSTRAINT FK_AR_RECEIPT_CURRENCY_ID FOREIGN KEY (CURRENCY_ID) REFERENCES CURRENCY (CURRENCY_ID);

ALTER TABLE AR_RECEIPT ADD COLUMN CURRENCY_RATE_ID INT(10) UNSIGNED DEFAULT NULL,
ADD CONSTRAINT FK_AR_RECEIPT_PAYMENT_CURRENCY_RATE_ID FOREIGN KEY (CURRENCY_RATE_ID) REFERENCES CURRENCY_RATE (CURRENCY_RATE_ID);

ALTER TABLE AR_RECEIPT ADD COLUMN CURRENCY_RATE_VALUE DOUBLE DEFAULT '0';

ALTER TABLE AR_RECEIPT ADD COLUMN RETENTION DOUBLE DEFAULT '0';

ALTER TABLE AR_RECEIPT ADD COLUMN RECOUPMENT DOUBLE DEFAULT '0';