
-- Description	: Add DR_REFERENCE_IDS and set to DELIVERY_RECEIPT_ID to default null in AR_INVOICE table

ALTER TABLE AR_INVOICE MODIFY COLUMN DELIVERY_RECEIPT_ID INT(10) UNSIGNED DEFAULT NULL;

ALTER TABLE AR_INVOICE ADD COLUMN DR_REFERENCE_IDS VARCHAR(100) DEFAULT NULL;