
-- Description	: Add ITEM_DISCOUNT_TYPE_ID in SERIAL_ITEM table

ALTER TABLE SERIAL_ITEM ADD COLUMN ITEM_DISCOUNT_TYPE_ID INT(10) UNSIGNED DEFAULT NULL,
ADD CONSTRAINT FK_SI_ITEM_DISCOUNT_TYPE_ID FOREIGN KEY (ITEM_DISCOUNT_TYPE_ID) REFERENCES ITEM_DISCOUNT_TYPE (ITEM_DISCOUNT_TYPE_ID);

ALTER TABLE SERIAL_ITEM ADD COLUMN DISCOUNT_VALUE DOUBLE DEFAULT 0;