
-- Description	: Update item add MANUFACTURER_PART_NO, PURCHASE_DESC, SALE_DESC, and MAX_ORDERING_POINT.

ALTER TABLE ITEM ADD COLUMN MANUFACTURER_PART_NO VARCHAR(50) DEFAULT NULL AFTER INITIAL_QUANTITY;
ALTER TABLE ITEM ADD COLUMN PURCHASE_DESC VARCHAR(100) DEFAULT NULL AFTER MANUFACTURER_PART_NO;
ALTER TABLE ITEM ADD COLUMN SALE_DESC VARCHAR(100) DEFAULT NULL AFTER PURCHASE_DESC;
ALTER TABLE ITEM ADD COLUMN MAX_ORDERING_POINT int(10) DEFAULT NULL AFTER SALE_DESC;