
-- Description: Add default account combination ids for and customer advances and retention in AR_CUSTOMER_ACCOUNT table

ALTER TABLE AR_CUSTOMER_ACCOUNT ADD DEFAULT_CUSTOMER_ADVANCES_AC_ID int(10) unsigned DEFAULT NULL AFTER DEFAULT_WITHDRAWAL_SLIP_AC_ID,
ADD CONSTRAINT FK_AR_CUST_ACCT_DEFAULT_CUST_ADVANCES FOREIGN KEY (DEFAULT_CUSTOMER_ADVANCES_AC_ID) REFERENCES ACCOUNT_COMBINATION (ACCOUNT_COMBINATION_ID);

ALTER TABLE AR_CUSTOMER_ACCOUNT ADD DEFAULT_RETENTION_AC_ID int(10) unsigned DEFAULT NULL AFTER DEFAULT_CUSTOMER_ADVANCES_AC_ID,
ADD CONSTRAINT FK_AR_CUST_ACCT_DEFAULT_CUST_RETENTION FOREIGN KEY (DEFAULT_RETENTION_AC_ID) REFERENCES ACCOUNT_COMBINATION (ACCOUNT_COMBINATION_ID);
