
-- Description	: Update Discount Type name.

UPDATE `ITEM_DISCOUNT_TYPE` SET `NAME`='%' WHERE `ITEM_DISCOUNT_TYPE_ID`='1';
UPDATE `ITEM_DISCOUNT_TYPE` SET `NAME`='Amt' WHERE `ITEM_DISCOUNT_TYPE_ID`='2';
UPDATE `ITEM_DISCOUNT_TYPE` SET `NAME`='Qty' WHERE `ITEM_DISCOUNT_TYPE_ID`='3';