
-- Description	: Add WORK_ORDER_ID to REQUISITION_FORM table

ALTER TABLE REQUISITION_FORM ADD COLUMN WORK_ORDER_ID INT(10) UNSIGNED DEFAULT NULL,
ADD CONSTRAINT FK_REQUISITION_FORM_WORK_ORDER_ID FOREIGN KEY (WORK_ORDER_ID) REFERENCES WORK_ORDER (WORK_ORDER_ID);