
-- Description: Create script for ACTION_NOTICE Table.

CREATE TABLE ACTION_NOTICE(
ACTION_NOTICE_ID INT(10) unsigned NOT NULL AUTO_INCREMENT,
NAME varchar(25) NOT NULL,
ACTIVE tinyint(1) DEFAULT '1',
CREATED_BY INT(10) unsigned NOT NULL,
CREATED_DATE timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
UPDATED_BY INT(10) unsigned NOT NULL,
UPDATED_DATE timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
PRIMARY KEY (ACTION_NOTICE_ID),
KEY FK_ACTION_NOTICE_CREATED_BY (CREATED_BY),
KEY FK_ACTION_NOTICE_UPDATED_BY (UPDATED_BY),
CONSTRAINT FK_ACTION_NOTICE_CREATED_BY FOREIGN KEY (CREATED_BY) REFERENCES USER (USER_ID),
CONSTRAINT FK_ACTION_NOTICE_UPDATED_BY FOREIGN KEY (UPDATED_BY) REFERENCES USER (USER_ID)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;