
-- Description: Script for creating BIOMETRIC_MODEL table.

SET FOREIGN_KEY_CHECKS = 0;
DROP TABLE IF EXISTS BIOMETRIC_MODEL;
SET FOREIGN_KEY_CHECKS = 1;

CREATE TABLE BIOMETRIC_MODEL (
 BIOMETRIC_MODEL_ID int(10) unsigned NOT NULL AUTO_INCREMENT,
 MODEL_NAME varchar(40) NOT NULL,
 ACTIVE tinyint(1) NOT NULL,
 CREATED_BY int(10) unsigned NOT NULL,
 CREATED_DATE timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
 UPDATED_BY int(10) unsigned NOT NULL,
 UPDATED_DATE TIMESTAMP NOT NULL DEFAULT '0000-00-00 00:00:00',
 PRIMARY KEY (BIOMETRIC_MODEL_ID),
 KEY FK_BIOMETRIC_MODEL_CREATED_BY (CREATED_BY),
 KEY FK_EMPLOYEE_UPDATED_BY (UPDATED_BY),
 CONSTRAINT FK_BIOMETRIC_MODEL_CREATED_BY FOREIGN KEY (CREATED_BY) REFERENCES USER (USER_ID),
 CONSTRAINT FK_BIOMETRIC_MODEL_UPDATED_BY FOREIGN KEY (UPDATED_BY) REFERENCES USER (USER_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;