
-- Description: Consolidated payroll update.

-- Payroll Time Sheet
ALTER TABLE PAYROLL_EMPLOYEE_TIMESHEET MODIFY COLUMN PAYROLL_ID int(10) unsigned DEFAULT NULL;
ALTER TABLE PAYROLL_EMPLOYEE_TIMESHEET ADD COLUMN TIME_SHEET_ID int(10) unsigned DEFAULT NULL AFTER PAYROLL_ID;
ALTER TABLE PAYROLL_EMPLOYEE_TIMESHEET ADD COLUMN LATE double(4, 2) DEFAULT NULL AFTER HOURS_WORKED;
ALTER TABLE PAYROLL_EMPLOYEE_TIMESHEET ADD COLUMN OVERTIME double(4, 2) DEFAULT NULL AFTER ADJUSTMENT;
ALTER TABLE PAYROLL_EMPLOYEE_TIMESHEET ADD COLUMN STATUS double(1, 0) DEFAULT NULL AFTER OVERTIME;

-- Payroll
ALTER TABLE PAYROLL ADD COLUMN TIME_SHEET_ID int(10) unsigned DEFAULT NULL AFTER EMPLOYEE_TYPE_ID;
ALTER TABLE PAYROLL ADD CONSTRAINT FK_PAYROLL_TIME_SHEET_ID FOREIGN KEY (TIME_SHEET_ID) REFERENCES TIME_SHEET (TIME_SHEET_ID);
ALTER TABLE PAYROLL DROP FOREIGN KEY FK_PAYROLL_BIOMETRIC_MODEL_ID;
ALTER TABLE PAYROLL MODIFY COLUMN BIOMETRIC_MODEL_ID int(10) unsigned DEFAULT NULL;

-- Payroll Employee Salary
ALTER TABLE PAYROLL_EMPLOYEE_SALARY ADD COLUMN NET_PAY double(12,2) DEFAULT NULL;