
-- Description: SQL script in creating DAILY_SHIFT_SCHEDULE_LINE table
DROP TABLE IF EXISTS DAILY_SHIFT_SCHEDULE_LINE;

CREATE TABLE `DAILY_SHIFT_SCHEDULE_LINE` (
  `DAILY_SHIFT_SCHEDULE_LINE_ID` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `DAILY_SHIFT_SCHEDULE_ID` INT(10) UNSIGNED NOT NULL,
  `EMPLOYEE_ID` INT(10) UNSIGNED NOT NULL,
  `EMPLOYEE_SHIFT_ID` INT(10) UNSIGNED NOT NULL,
  `DATE` date NOT NULL,
  PRIMARY KEY (`DAILY_SHIFT_SCHEDULE_LINE_ID`),
  KEY `FK_DSSL_DAILY_SHIFT_SCHEDULE_ID`(`DAILY_SHIFT_SCHEDULE_ID`),
  KEY `FK_DSSL_EMPLOYEE_ID`(`EMPLOYEE_ID`),
  KEY `FK_DSSL_EMPLOYEE_SHIFT_ID`(`EMPLOYEE_SHIFT_ID`),
  CONSTRAINT `FK_DSSL_DAILY_SHIFT_SCHEDULE_ID` FOREIGN KEY (`DAILY_SHIFT_SCHEDULE_ID`) REFERENCES `DAILY_SHIFT_SCHEDULE`(`DAILY_SHIFT_SCHEDULE_ID`),
  CONSTRAINT `FK_DSSL_EMPLOYEE_ID` FOREIGN KEY (`EMPLOYEE_ID`) REFERENCES `EMPLOYEE`(`EMPLOYEE_ID`),
  CONSTRAINT `FK_DSSL_EMPLOYEE_SHIFT_ID` FOREIGN KEY (`EMPLOYEE_SHIFT_ID`) REFERENCES `EMPLOYEE_SHIFT`(`EMPLOYEE_SHIFT_ID`)
) ENGINE = InnoDB DEFAULT CHARSET = utf8;