
-- Description: Create script for DOCUMENT_TYPE Table.

CREATE TABLE DOCUMENT_TYPE(
DOCUMENT_TYPE_ID INT(10) unsigned NOT NULL AUTO_INCREMENT,
NAME varchar(25) NOT NULL,
ACTIVE tinyint(1) DEFAULT '1',
CREATED_BY INT(10) unsigned NOT NULL,
CREATED_DATE timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
UPDATED_BY INT(10) unsigned NOT NULL,
UPDATED_DATE timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
PRIMARY KEY (DOCUMENT_TYPE_ID),
KEY FK_DOCUMENT_TYPE_CREATED_BY (CREATED_BY),
KEY FK_DOCUMENT_TYPE_UPDATED_BY (UPDATED_BY),
CONSTRAINT FK_DOCUMENT_TYPE_CREATED_BY FOREIGN KEY (CREATED_BY) REFERENCES USER (USER_ID),
CONSTRAINT FK_DOCUMENT_TYPE_UPDATED_BY FOREIGN KEY (UPDATED_BY) REFERENCES USER (USER_ID)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;