
-- Description: SQL script in creating the EMPLOYEE_SALARY_DETAIL table

SET FOREIGN_KEY_CHECKS = 0;
DROP TABLE IF EXISTS EMPLOYEE_SALARY_DETAILS;
SET FOREIGN_KEY_CHECKS = 1;

CREATE TABLE EMPLOYEE_SALARY_DETAILS (
  EMPLOYEE_SALARY_DETAIL_ID int(10) unsigned NOT NULL AUTO_INCREMENT,
  EMPLOYEE_ID int(10) unsigned NOT NULL,
  SALARY_TYPE_ID int(10) unsigned DEFAULT NULL,
  ECOLA double(12,2) DEFAULT '0.00',
  BASIC_SALARY double(12,2) NOT NULL,
  DAILY_SALARY double(12,2) NOT NULL,
  DE_MINIMIS double(12,2) DEFAULT '0.00',
  EXCLUDE_SSS tinyint(1) DEFAULT '0',
  EXCLUDE_PHIC tinyint(1) DEFAULT '0',
  EXCLUDE_WT tinyint(1) DEFAULT '0',
  EXCLUDE_HDMF tinyint(1) DEFAULT '0',
  SSS double(12,2) DEFAULT '0.00',
  SSS_ADDITIONAL double(12,2) DEFAULT '0.00',
  PHILHEALTH double(12,2) DEFAULT '0.00',
  PAG_IBIG double(12,2) DEFAULT '0.00',
  PAG_IBIG_ADDITIONAL double(12,2) DEFAULT '0.00',
  OTHER_DEDUCTION double(12,2) DEFAULT '0.00',
  BONUS double(12,2) DEFAULT '0.00',
  PRIMARY KEY (EMPLOYEE_SALARY_DETAIL_ID),
  KEY FK_ESD_EMPLOYEE_ID (EMPLOYEE_ID),
  KEY FK_ESD_SALARY_DETAIL_ID (SALARY_TYPE_ID),
  CONSTRAINT FK_ESD_EMPLOYEE_ID FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEE (EMPLOYEE_ID),
  CONSTRAINT FK_ESD_SALARY_DETAIL_ID FOREIGN KEY (SALARY_TYPE_ID) REFERENCES SALARY_TYPE (SALARY_TYPE_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;