
-- Description: Script for creating employee shift table.

SET FOREIGN_KEY_CHECKS = 0;
DROP TABLE IF EXISTS EMPLOYEE_SHIFT;
SET FOREIGN_KEY_CHECKS = 1;

CREATE TABLE EMPLOYEE_SHIFT (
  EMPLOYEE_SHIFT_ID int(10) unsigned NOT NULL AUTO_INCREMENT,
  NAME varchar(50) NOT NULL,
  COMPANY_ID int(10) unsigned NOT NULL,
  FIRST_HALF_SHIFT_START varchar(5) NOT NULL,
  FIRST_HALF_SHIFT_END varchar(5) DEFAULT NULL,
  SECOND_HALF_SHIFT_START varchar(5) DEFAULT NULL,
  SECOND_HALF_SHIFT_END varchar(5) NOT NULL,
  ALLOWABLE_BREAK double DEFAULT NULL,
  LATE_MULTIPLIER double DEFAULT NULL,
  NIGHT_SHIFT tinyint(1) NOT NULL,
  DAY_OFF tinyint(1) DEFAULT 0,
  DAILY_WORKING_HOURS double(4,2) NOT NULL,
  CREATED_BY int(10) unsigned NOT NULL,
  CREATED_DATE timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UPDATED_BY int(10) unsigned NOT NULL,
  UPDATED_DATE timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  ACTIVE tinyint(1) NOT NULL,
  PRIMARY KEY (EMPLOYEE_SHIFT_ID),
  KEY FK_ES_COMPANY_ID (COMPANY_ID),
  KEY FK_ES_CREATED_BY (CREATED_BY),
  KEY FK_ES_UPDATED_BY (UPDATED_BY),
  CONSTRAINT FK_ES_COMPANY_ID FOREIGN KEY (COMPANY_ID) REFERENCES COMPANY (COMPANY_ID),
  CONSTRAINT FK_ES_CREATED_BY FOREIGN KEY (CREATED_BY) REFERENCES USER (USER_ID),
  CONSTRAINT FK_ES_UPDATED_BY FOREIGN KEY (UPDATED_BY) REFERENCES USER (USER_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;