
-- Description: Create script for ACTION_NOTICE Table.

CREATE TABLE EMPLOYEE_DOCUMENT(
	EMPLOYEE_DOCUMENT_ID INT(10) unsigned NOT NULL AUTO_INCREMENT,
	SEQUENCE_NO int(10) unsigned NOT NULL,
	COMPANY_ID INT(10) UNSIGNED DEFAULT 1,
	EMPLOYEE_ID INT(10) unsigned NOT NULL,
	DOCUMENT_TYPE_ID INT(10) unsigned NOT NULL,
	DATE date  NOT NULL,
	REMARKS text  NOT NULL,
	FORM_WORKFLOW_ID INT(10) unsigned NOT NULL,
	EB_OBJECT_ID INT(10) unsigned NOT NULL,
	CREATED_BY INT(10) unsigned NOT NULL,
	CREATED_DATE timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
	UPDATED_BY INT(10) unsigned NOT NULL,
	UPDATED_DATE timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
	PRIMARY KEY (EMPLOYEE_DOCUMENT_ID),
	KEY FK_EMPLOYEE_DOCUMENT_EMPLOYEE_ID (EMPLOYEE_ID),
	KEY FK_EMPLOYEE_DOCUMENT_TYPE_ID (DOCUMENT_TYPE_ID),
	KEY FK_EMPLOYEE_DOCUMENT_FW_ID (FORM_WORKFLOW_ID),
	KEY FK_EMPLOYEE_DOCUMENT_EB_OBJECT_ID (EB_OBJECT_ID),
	KEY FK_EMPLOYEE_DOCUMENT_CREATED_BY (CREATED_BY),
	KEY FK_EMPLOYEE_DOCUMENT_UPDATED_BY (UPDATED_BY),
	KEY FK_EMPLOYEE_DOCUMENT_COMPANY_ID (COMPANY_ID),
	CONSTRAINT FK_EMPLOYEE_DOCUMENT_EMPLOYEE_ID FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEE (EMPLOYEE_ID),
	CONSTRAINT FK_EMPLOYEE_DOCUMENT_TYPE_ID FOREIGN KEY (DOCUMENT_TYPE_ID) REFERENCES DOCUMENT_TYPE (DOCUMENT_TYPE_ID),
	CONSTRAINT FK_EMPLOYEE_DOCUMENT_FW_ID FOREIGN KEY (FORM_WORKFLOW_ID) REFERENCES FORM_WORKFLOW (FORM_WORKFLOW_ID),
	CONSTRAINT FK_EMPLOYEE_DOCUMENT_EB_OBJECT_ID FOREIGN KEY (EB_OBJECT_ID) REFERENCES EB_OBJECT (EB_OBJECT_ID),
	CONSTRAINT FK_EMPLOYEE_DOCUMENT_CREATED_BY FOREIGN KEY (CREATED_BY) REFERENCES USER (USER_ID),
	CONSTRAINT FK_EMPLOYEE_DOCUMENT_UPDATED_BY FOREIGN KEY (UPDATED_BY) REFERENCES USER (USER_ID),
	CONSTRAINT FK_EMPLOYEE_DOCUMENT_COMPANY_ID FOREIGN KEY (COMPANY_ID) REFERENCES COMPANY (COMPANY_ID)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;