
-- Description: Create script for EMPLOYEE_REQUEST table.

DROP TABLE IF EXISTS EMPLOYEE_REQUEST;

CREATE TABLE EMPLOYEE_REQUEST (
	EMPLOYEE_REQUEST_ID int(10) unsigned NOT NULL AUTO_INCREMENT,
	SEQUENCE_NO int(10) unsigned NOT NULL,
	FORM_WORKFLOW_ID int(10) unsigned DEFAULT NULL,
	EB_OBJECT_ID int(10) unsigned DEFAULT NULL,
	REQUEST_TYPE_ID int(10) unsigned DEFAULT NULL,
	COMPANY_ID int(10) unsigned NOT NULL,
	EMPLOYEE_ID int(10) unsigned NOT NULL,
	DATE date NOT NULL,
	CREATED_BY int(10) unsigned NOT NULL,
	CREATED_DATE timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
	UPDATED_BY int(10) unsigned NOT NULL,
	UPDATED_DATE timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
	PRIMARY KEY (EMPLOYEE_REQUEST_ID),
	KEY FK_ER_FORM_WORKFLOW_ID (FORM_WORKFLOW_ID),
	KEY FK_ER_EB_OBJECT_ID (EB_OBJECT_ID),
	KEY FK_ER_REQUEST_TYPE_ID (REQUEST_TYPE_ID),
	KEY FK_ER_COMPANY_ID (COMPANY_ID),
	KEY FK_ER_EMPLOYEE_ID (EMPLOYEE_ID),
	KEY FK_ER_CREATED_BY (CREATED_BY),
	KEY FK_ER_UPDATED_BY (UPDATED_BY),
	CONSTRAINT FK_ER_FORM_WORKFLOW_ID FOREIGN KEY (FORM_WORKFLOW_ID) REFERENCES FORM_WORKFLOW (FORM_WORKFLOW_ID),
	CONSTRAINT FK_ER_EB_OBJECT_ID FOREIGN KEY (EB_OBJECT_ID) REFERENCES EB_OBJECT (EB_OBJECT_ID),
	CONSTRAINT FK_ER_REQUEST_TYPE_ID FOREIGN KEY (REQUEST_TYPE_ID) REFERENCES REQUEST_TYPE (REQUEST_TYPE_ID),
	CONSTRAINT FK_ER_COMPANY_ID FOREIGN KEY (COMPANY_ID) REFERENCES COMPANY (COMPANY_ID),
	CONSTRAINT FK_ER_EMPLOYEE_ID FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEE (EMPLOYEE_ID),
	CONSTRAINT FK_ER_CREATED_BY FOREIGN KEY (CREATED_BY) REFERENCES USER (USER_ID),
	CONSTRAINT FK_ER_UPDATED_BY FOREIGN KEY (UPDATED_BY) REFERENCES USER (USER_ID)
) Engine=InnoDB DEFAULT CHARSET=utf8;