
-- Description: Create script for EMPLOYEE_SIBLING Table.

CREATE TABLE EMPLOYEE_SIBLING(
	EMPLOYEE_SIBLING_ID INT(10) unsigned NOT NULL AUTO_INCREMENT,
	EMPLOYEE_ID INT(10) unsigned NOT NULL,
	NAME varchar(100) NOT NULL,
	AGE INT(2) unsigned NOT NULL,
	CIVIL_STATUS_ID INT(10) unsigned NOT NULL,
	OCCUPATION varchar(100) DEFAULT NULL,
	PRIMARY KEY (EMPLOYEE_SIBLING_ID),
	KEY FK_EMPLOYEE_SIBLING_EMPLOYEE_ID (EMPLOYEE_ID),
	KEY FK_EMPLOYEE_SIBLING_CS_ID (CIVIL_STATUS_ID),
	CONSTRAINT FK_EMPLOYEE_SIBLING_EMPLOYEE_ID FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEE (EMPLOYEE_ID),
	CONSTRAINT FK_EMPLOYEE_SIBLING_CS_ID FOREIGN KEY (CIVIL_STATUS_ID) REFERENCES CIVIL_STATUS (CIVIL_STATUS_ID)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;