
-- Description: Create script for EMPLOYEE_CHILDREN Table.

CREATE TABLE EMPLOYEE_CHILDREN(
	EMPLOYEE_CHILDREN_ID INT(10) unsigned NOT NULL AUTO_INCREMENT,
	EMPLOYEE_ID INT(10) unsigned NOT NULL,
	NAME varchar(100) NOT NULL,
	BIRTH_DATE date NOT NULL,
	PRIMARY KEY (EMPLOYEE_CHILDREN_ID),
	KEY FK_EMPLOYEE_CHILDREN_EMPLOYEE_ID (EMPLOYEE_ID),
	CONSTRAINT FK_EMPLOYEE_CHILDREN_EMPLOYEE_ID FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEE (EMPLOYEE_ID)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;