
-- Description: Script for creating employee status table.

DROP TABLE IF EXISTS EMPLOYEE_STATUS;

CREATE TABLE EMPLOYEE_STATUS (
	EMPLOYEE_STATUS_ID int(10) unsigned NOT NULL AUTO_INCREMENT,
	NAME VARCHAR(25) NOT NULL,
	DESCRIPTION varchar(150) NOT NULL,
	ACTIVE tinyint(1) NOT NULL,
	CREATED_BY int(10) unsigned NOT NULL,
	CREATED_DATE timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
	UPDATED_BY int(10) unsigned NOT NULL,
	UPDATED_DATE timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
	PRIMARY KEY (EMPLOYEE_STATUS_ID),
	KEY FK_EMP_STAT_CREATED_BY (CREATED_BY),
	KEY FK_EMP_STAT_UPDATED_BY (UPDATED_BY),
	CONSTRAINT FK_EMP_STAT_CREATED_BY FOREIGN KEY (CREATED_BY) REFERENCES USER (USER_ID),
	CONSTRAINT FK_EMP_STAT_UPDATED_BY FOREIGN KEY (UPDATED_BY) REFERENCES USER (USER_ID)
) ENGINE = InnoDB DEFAULT CHARSET = utf8;