
-- Description: Create script for EMPLOYEE_DEDUCTION Table.

CREATE TABLE EMPLOYEE_DEDUCTION (
  EMPLOYEE_DEDUCTION_ID int(10) unsigned NOT NULL AUTO_INCREMENT,
  PAYROLL_ID int(10) unsigned NOT NULL,
  EMPLOYEE_ID int(10) unsigned NOT NULL,
  DEDUCTION_TYPE_ID int(10) unsigned NOT NULL,
  AMOUNT double DEFAULT NULL,
  PAID_AMOUNT double DEFAULT NULL,
  FROM_DEDUCTION_FORM tinyint(1) DEFAULT NULL,
  ACTIVE tinyint(1) DEFAULT 1,
  EB_OBJECT_ID int(10) unsigned DEFAULT NULL,
  PRIMARY KEY (EMPLOYEE_DEDUCTION_ID),
  KEY FK_EED_PAYROLL_ID (PAYROLL_ID),
  KEY FK_EED_EMPLOYEE_ID (EMPLOYEE_ID),
  KEY FK_EED_DEDUCTION_TYPE_ID (DEDUCTION_TYPE_ID),
  KEY FK_EMPLOYEE_DEDUCTION_EB_OBJECT_ID (EB_OBJECT_ID),
  CONSTRAINT FK_EED_PAYROLL_ID FOREIGN KEY (PAYROLL_ID) REFERENCES PAYROLL (PAYROLL_ID),
  CONSTRAINT FK_EED_EMPLOYEE_ID FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEE (EMPLOYEE_ID),
  CONSTRAINT FK_EED_DEDUCTION_TYPE_ID FOREIGN KEY (DEDUCTION_TYPE_ID) REFERENCES DEDUCTION_TYPE (DEDUCTION_TYPE_ID),
  CONSTRAINT FK_EMPLOYEE_DEDUCTION_EB_OBJECT_ID FOREIGN KEY (EB_OBJECT_ID) REFERENCES EB_OBJECT (EB_OBJECT_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;