
-- Description: Create script for EMPLOYEE_RELATIVE Table.

CREATE TABLE EMPLOYEE_RELATIVE(
	EMPLOYEE_RELATIVE_ID INT(10) unsigned NOT NULL AUTO_INCREMENT,
	EMPLOYEE_ID INT(10) unsigned NOT NULL,
	NAME varchar(100) NOT NULL,
	POSITION varchar(50) DEFAULT NULL,
	RELATIONSHIP varchar(50) DEFAULT NULL,
	PRIMARY KEY (EMPLOYEE_RELATIVE_ID),
	KEY FK_EMPLOYEE_RELATIVE_EMPLOYEE_ID (EMPLOYEE_ID),
	CONSTRAINT FK_EMPLOYEE_RELATIVE_EMPLOYEE_ID FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEE (EMPLOYEE_ID)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;