
-- Description: Create script for EMPLOYEE_CIVIL_QUERY Table.

CREATE TABLE EMPLOYEE_CIVIL_QUERY(
	EMPLOYEE_CIVIL_QUERY_ID INT(10) unsigned NOT NULL AUTO_INCREMENT,
	EMPLOYEE_ID INT(10) unsigned NOT NULL,
	ADMINISTRATIVE_INVESTIGATION tinyint(1) DEFAULT '0',
	ADMIN_INVES_DETAIL varchar(250) DEFAULT NULL,
	CRIME_CONVICTED tinyint(1) DEFAULT '0',
	CRIME_CONVICTED_DETAIL varchar(250) DEFAULT NULL,
	USED_PROHIBITED_DRUG tinyint(1) DEFAULT '0',
	PRIMARY KEY (EMPLOYEE_CIVIL_QUERY_ID),
	KEY FK_ECQ_EMPLOYEE_ID (EMPLOYEE_ID),
	CONSTRAINT FK_ECQ_EMPLOYEE_ID FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEE (EMPLOYEE_ID)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;