
-- Description: Create script for EMPLOYEE_LEAVE_CREDIT Table.

DROP TABLE IF EXISTS EMPLOYEE_LEAVE_CREDIT;

CREATE TABLE EMPLOYEE_LEAVE_CREDIT(
EMPLOYEE_LEAVE_CREDIT_ID INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
EB_OBJECT_ID INT(10) UNSIGNED DEFAULT NULL,
FORM_WORKFLOW_ID INT(10) UNSIGNED NOT NULL,
COMPANY_ID INT(10) UNSIGNED NOT NULL,
TYPE_OF_LEAVE_ID INT(10) UNSIGNED NOT NULL,
SEQUENCE_NO INT(10) UNSIGNED NOT NULL,
DATE DATE NOT NULL,
REMARKS TEXT DEFAULT NULL,
CREATED_BY INT(10) UNSIGNED NOT NULL,
CREATED_DATE timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
UPDATED_BY INT(10) UNSIGNED NOT NULL,
UPDATED_DATE timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
PRIMARY KEY (EMPLOYEE_LEAVE_CREDIT_ID),
KEY FK_EMPLOYEE_LEAVE_CREDIT_EB_OBJECT_ID (EB_OBJECT_ID),
KEY FK_EMPLOYEE_LEAVE_CREDIT_FORM_WORKFLOW_ID (FORM_WORKFLOW_ID),
KEY FK_EMPLOYEE_LEAVE_CREDIT_COMPANY_ID (COMPANY_ID),
KEY FK_EMPLOYEE_LEAVE_CREDIT_TYPE_OF_LEAVE_ID (TYPE_OF_LEAVE_ID),
KEY FK_EMPLOYEE_LEAVE_CREDIT_CREATED_BY (CREATED_BY),
KEY FK_EMPLOYEE_LEAVE_CREDIT_UPDATED_BY (UPDATED_BY),
CONSTRAINT FK_EMPLOYEE_LEAVE_CREDIT_EB_OBJECT_ID FOREIGN KEY (EB_OBJECT_ID) REFERENCES EB_OBJECT (EB_OBJECT_ID),
CONSTRAINT FK_EMPLOYEE_LEAVE_CREDIT_FORM_WORKFLOW_ID FOREIGN KEY (FORM_WORKFLOW_ID) REFERENCES FORM_WORKFLOW (FORM_WORKFLOW_ID),
CONSTRAINT FK_EMPLOYEE_LEAVE_CREDIT_COMPANY_ID FOREIGN KEY (COMPANY_ID) REFERENCES COMPANY (COMPANY_ID),
CONSTRAINT FK_EMPLOYEE_LEAVE_CREDIT_TYPE_OF_LEAVE_ID FOREIGN KEY (TYPE_OF_LEAVE_ID) REFERENCES TYPE_OF_LEAVE (TYPE_OF_LEAVE_ID),
CONSTRAINT FK_EMPLOYEE_LEAVE_CREDIT_CREATED_BY FOREIGN KEY (CREATED_BY) REFERENCES USER (USER_ID),
CONSTRAINT FK_EMPLOYEE_LEAVE_CREDIT_UPDATED_BY FOREIGN KEY (UPDATED_BY) REFERENCES USER (USER_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;