
-- Description: Create script for EMPLOYEE_SEMINAR_ATTENDED

DROP TABLE IF EXISTS EMPLOYEE_SEMINAR_ATTENDED;

CREATE TABLE EMPLOYEE_SEMINAR_ATTENDED (
	EMPLOYEE_SEMINAR_ATTENDED_ID int(10) unsigned NOT NULL AUTO_INCREMENT,
	EB_OBJECT_ID int(10) unsigned DEFAULT NULL,
	COURSE_TITLE varchar(150) NOT NULL,
	COMPANY_AGENCY varchar(150) NOT NULL,
	INCLUSIVE_DATE varchar(50) NOT NULL,
	ACTIVE tinyint(1) NOT NULL,
	PRIMARY KEY (EMPLOYEE_SEMINAR_ATTENDED_ID),
	KEY FK_ESA_EB_OBJECT_ID (EB_OBJECT_ID),
	CONSTRAINT FK_ESA_EB_OBJECT_ID FOREIGN KEY (EB_OBJECT_ID) REFERENCES EB_OBJECT (EB_OBJECT_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;