
-- Description: Create script for EMPLOYEE_EMPLOYEMENT_QUERY Table.

CREATE TABLE EMPLOYEE_EMPLOYEMENT_QUERY(
	EMPLOYEE_EMPLOYEMENT_QUERY_ID INT(10) unsigned NOT NULL AUTO_INCREMENT,
	EMPLOYEE_ID INT(10) unsigned NOT NULL,
	PREV_EMPLOYED tinyint(1) DEFAULT '0',
	SEPARATION_REASON varchar(250) DEFAULT NULL,
	DIAGNOSED_WITH_DISEASE tinyint(1) DEFAULT '0',
	DISEASE_DETAIL varchar(250) DEFAULT NULL,
	IDENTIFYING_MARK varchar(250) DEFAULT NULL,
	EMERGENCY_CONTACT varchar(250) NOT NULL,
	PRIMARY KEY (EMPLOYEE_EMPLOYEMENT_QUERY_ID),
	KEY FK_EEQ_EMPLOYEE_ID (EMPLOYEE_ID),
	CONSTRAINT FK_EEQ_EMPLOYEE_ID FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEE (EMPLOYEE_ID)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;