
-- Description: Create script for EMPLOYEE_NATIONAL_COMPETENCIES

DROP TABLE IF EXISTS EMPLOYEE_NATIONAL_COMPETENCY;

CREATE TABLE EMPLOYEE_NATIONAL_COMPETENCY (
	EMPLOYEE_NATIONAL_COMPETENCY_ID int(10) unsigned NOT NULL AUTO_INCREMENT,
	EB_OBJECT_ID int(10) unsigned DEFAULT NULL,
	DESCRIPTION varchar(100) NOT NULL,
	ACTIVE tinyint(1) NOT NULL,
	PRIMARY KEY (EMPLOYEE_NATIONAL_COMPETENCY_ID),
	KEY FK_ENC_EB_OBJECT_ID (EB_OBJECT_ID),
	CONSTRAINT FK_ENC_EB_OBJECT_ID FOREIGN KEY (EB_OBJECT_ID) REFERENCES EB_OBJECT (EB_OBJECT_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;