
-- Description: Create script for EMPLOYEE_EDUCATIONAL_ATTAINMENT Table.

DROP TABLE IF EXISTS EMPLOYEE_EDUCATIONAL_ATTAINMENT;

CREATE TABLE EMPLOYEE_EDUCATIONAL_ATTAINMENT(
	EMPLOYEE_EDUCATIONAL_ATTAINMENT_ID INT(10) unsigned NOT NULL AUTO_INCREMENT,
	EDUCATIONAL_ATTAINMENT_TYPE_ID int(10) unsigned NOT NULL,
	EMPLOYEE_ID INT(10) unsigned NOT NULL,
	ELEMENTARY_SCHOOL varchar(100) DEFAULT NULL,
	ELEMENTARY_YEAR int(4) DEFAULT NULL,
	ELEMENTARY_COURSE varchar(100) DEFAULT NULL,
	HS_SCHOOL varchar(100) DEFAULT NULL,
	HS_YEAR int(4) DEFAULT NULL,
	HS_COURSE varchar(100) DEFAULT NULL,
	COLLEGE_SCHOOL varchar(100) DEFAULT NULL,
	COLLEGE_YEAR int(4) DEFAULT NULL,
	COLLEGE_COURSE varchar(100) DEFAULT NULL,
	POST_GRAD_SCHOOL varchar(100) DEFAULT NULL,
	POST_GRAD_YEAR int(4) DEFAULT NULL,
	POST_GRAD_COURSE varchar(100) DEFAULT NULL,
	VOCATIONAL_SCHOOL varchar(100) DEFAULT NULL,
	VOCATIONAL_YEAR int(4) DEFAULT NULL,
	VOCATIONAL_COURSE varchar(100) DEFAULT NULL,
	VOCATIONAL_ADDRESS varchar(200) DEFAULT NULL,
	ELEMENTARY_ADDRESS varchar(200) DEFAULT NULL,
	HS_ADDRESS varchar(200) DEFAULT NULL,
	COLLEGE_ADDRESS varchar(200) DEFAULT NULL,
	POST_GRAD_ADDRESS varchar(200) DEFAULT NULL,
	EMPLOYEE_SKILLS varchar(250) DEFAULT NULL,
	PRIMARY KEY (EMPLOYEE_EDUCATIONAL_ATTAINMENT_ID),
	KEY FK_EEA_EMPLOYEE_ID (EMPLOYEE_ID),
	KEY FK_EEA_EDUCATIONAL_ATTAINMENT_TYPE_ID(EDUCATIONAL_ATTAINMENT_TYPE_ID),
	CONSTRAINT FK_EEA_EMPLOYEE_ID FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEE (EMPLOYEE_ID),
	CONSTRAINT FK_EEA_EDUCATIONAL_ATTAINMENT_TYPE_ID FOREIGN KEY (EDUCATIONAL_ATTAINMENT_TYPE_ID) REFERENCES EDUCATIONAL_ATTAINMENT_TYPE (EDUCATIONAL_ATTAINMENT_TYPE_ID)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;