
-- Description: Create script for FORM_DEDUCTION_TYPE Table.

DROP TABLE IF EXISTS FORM_DEDUCTION_TYPE;

CREATE TABLE FORM_DEDUCTION_TYPE(
FORM_DEDUCTION_TYPE_ID INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
NAME VARCHAR(20) NOT NULL,
ACTIVE TINYINT(1) NOT NULL,
CREATED_BY INT(10) UNSIGNED NOT NULL,
CREATED_DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
UPDATED_BY INT(10) UNSIGNED NOT NULL,
UPDATED_DATE TIMESTAMP NOT NULL DEFAULT '0000-00-00 00:00:00',
PRIMARY KEY (FORM_DEDUCTION_TYPE_ID),
KEY FK_FORM_DEDUCTION_TYPE_CREATED_BY (CREATED_BY),
KEY FK_FORM_DEDUCTION_TYPE_UPDATED_BY (UPDATED_BY),
CONSTRAINT FK_FORM_DEDUCTION_TYPE_CREATED_BY FOREIGN KEY (CREATED_BY) REFERENCES USER (USER_ID),
CONSTRAINT FK_FORM_DEDUCTION_TYPE_UPDATED_BY FOREIGN KEY (UPDATED_BY) REFERENCES USER (USER_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;