
-- Description: Create script for FORM_DEDUCTION Table.

DROP TABLE IF EXISTS FORM_DEDUCTION;

CREATE TABLE FORM_DEDUCTION(
FORM_DEDUCTION_ID INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
EB_OBJECT_ID INT(10) UNSIGNED DEFAULT NULL,
FORM_WORKFLOW_ID INT(10) UNSIGNED NOT NULL,
FORM_DEDUCTION_TYPE_ID INT(10) UNSIGNED NOT NULL,
COMPANY_ID INT(10) UNSIGNED NOT NULL,
EMPLOYEE_ID INT(10) UNSIGNED NOT NULL,
DIVISION_ID INT(10) UNSIGNED NOT NULL,
DEDUCTION_TYPE_ID INT(10) UNSIGNED NOT NULL,
SEQUENCE_NO INT(10) UNSIGNED NOT NULL,
FORM_DATE DATE NOT NULL,
START_DATE DATE NOT NULL,
REMARKS TEXT DEFAULT NULL,
CREATED_BY INT(10) UNSIGNED NOT NULL,
CREATED_DATE timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
UPDATED_BY INT(10) UNSIGNED NOT NULL,
UPDATED_DATE timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
PRIMARY KEY(FORM_DEDUCTION_ID),
KEY FK_FORM_DEDUCTION_EB_OBJECT_ID (EB_OBJECT_ID),
KEY FK_FORM_DEDUCTION_FORM_WORKFLOW_ID (FORM_WORKFLOW_ID),
KEY FK_FORM_DEDUCTION_FORM_DEDUCTION_TYPE_ID (FORM_DEDUCTION_TYPE_ID),
KEY FK_FORM_DEDUCTION_COMPANY_ID(COMPANY_ID),
KEY FK_FORM_DEDUCTION_EMPLOYEE_ID(EMPLOYEE_ID),
KEY FK_FORM_DEDUCTION_DIVISION_ID (DIVISION_ID),
KEY FK_FORM_DEDUCTION_DEDUCTION_TYPE_ID (DEDUCTION_TYPE_ID),
KEY FK_FORM_DEDUCTION_CREATED_BY (CREATED_BY),
KEY FK_FORM_DEDUCTION_UPDATED_BY (UPDATED_BY),
CONSTRAINT FK_FORM_DEDUCTION_EB_OBJECT_ID FOREIGN KEY (EB_OBJECT_ID) REFERENCES EB_OBJECT (EB_OBJECT_ID),
CONSTRAINT FK_FORM_DEDUCTION_FORM_WORKFLOW_ID FOREIGN KEY (FORM_WORKFLOW_ID) REFERENCES FORM_WORKFLOW (FORM_WORKFLOW_ID),
CONSTRAINT FK_FORM_DEDUCTION_FORM_DEDUCTION_TYPE_ID FOREIGN KEY (FORM_DEDUCTION_TYPE_ID) REFERENCES FORM_DEDUCTION_TYPE (FORM_DEDUCTION_TYPE_ID),
CONSTRAINT FK_FORM_DEDUCTION_COMPANY_ID FOREIGN KEY (COMPANY_ID) REFERENCES COMPANY (COMPANY_ID),
CONSTRAINT FK_FORM_DEDUCTION_EMPLOYEE_ID FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEE (EMPLOYEE_ID),
CONSTRAINT FK_FORM_DEDUCTION_DIVISION_ID FOREIGN KEY (DIVISION_ID) REFERENCES DIVISION (DIVISION_ID),
CONSTRAINT FK_FORM_DEDUCTION_DEDUCTION_TYPE_ID FOREIGN KEY (DEDUCTION_TYPE_ID) REFERENCES DEDUCTION_TYPE (DEDUCTION_TYPE_ID),
CONSTRAINT FK_FORM_DEDUCTION_CREATED_BY FOREIGN KEY (CREATED_BY) REFERENCES USER (USER_ID),
CONSTRAINT FK_FORM_DEDUCTION_UPDATED_BY FOREIGN KEY (UPDATED_BY) REFERENCES USER (USER_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;