
-- Description: SQL script in creating HOLIDAY_SETTING table
DROP TABLE IF EXISTS HOLIDAY_SETTING;

CREATE TABLE `HOLIDAY_SETTING` (
  `HOLIDAY_SETTING_ID` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `COMPANY_ID` INT(10) UNSIGNED NOT NULL,
  `HOLIDAY_TYPE_ID` INT(10) UNSIGNED DEFAULT NULL,
  `NAME` VARCHAR(50) NOT NULL,
  `DATE` DATE NOT NULL,
  `ACTIVE` TINYINT(1) NOT NULL,
  `CREATED_BY` INT(10) UNSIGNED NOT NULL,
  `CREATED_DATE` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_BY` INT(10) UNSIGNED NOT NULL,
  `UPDATED_DATE` TIMESTAMP NOT NULL DEFAULT '0000-00-00 00:00:00',
  PRIMARY KEY (`HOLIDAY_SETTING_ID`),
  KEY `FK_HS_COMPANY_ID`(`COMPANY_ID`),
  KEY `FK_HS_HOLIDAY_TYPE_ID`(`HOLIDAY_TYPE_ID`),
  KEY `FK_HS_CREATED_BY`(`CREATED_BY`),
  KEY `FK_HS_UPDATED_BY`(`UPDATED_BY`),
  CONSTRAINT `FK_HS_COMPANY_ID` FOREIGN KEY (`COMPANY_ID`) REFERENCES `COMPANY`(`COMPANY_ID`),
  CONSTRAINT `FK_HS_HOLIDAY_TYPE_ID` FOREIGN KEY (`HOLIDAY_TYPE_ID`) REFERENCES `HOLIDAY_TYPE`(`HOLIDAY_TYPE_ID`),
  CONSTRAINT `FK_HS_CREATED_BY` FOREIGN KEY (`CREATED_BY`) REFERENCES `USER`(`USER_ID`),
  CONSTRAINT `FK_HS_UPDATED_BY` FOREIGN KEY (`UPDATED_BY`) REFERENCES `USER`(`USER_ID`)
) ENGINE = InnoDB DEFAULT CHARSET = utf8;