
-- Description: SQL script in creating HOLIDAY_TYPE table
DROP TABLE IF EXISTS HOLIDAY_TYPE;

CREATE TABLE HOLIDAY_TYPE (
	HOLIDAY_TYPE_ID INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
	NAME VARCHAR(25) NOT NULL,
	DESCRIPTION varchar(100) NOT NULL,
	ACTIVE tinyint(1) NOT NULL,
	CREATED_BY int(10) unsigned NOT NULL,
	CREATED_DATE timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
	UPDATED_BY int(10) unsigned NOT NULL,
	UPDATED_DATE timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
	PRIMARY KEY (HOLIDAY_TYPE_ID),
	KEY FK_HT_CREATED_BY (CREATED_BY),
	KEY FK_HT_UPDATED_BY (UPDATED_BY),
	CONSTRAINT FK_HT_CREATED_BY FOREIGN KEY (CREATED_BY) REFERENCES USER (USER_ID),
	CONSTRAINT FK_HT_UPDATED_BY FOREIGN KEY (UPDATED_BY) REFERENCES USER (USER_ID)
) ENGINE = InnoDB DEFAULT CHARSET = utf8;