
-- Description: SQL script in creating the MONTHLY_SHIFT_SCHEDULE table

CREATE TABLE `MONTHLY_SHIFT_SCHEDULE` (
  `MONTHLY_SHIFT_SCHEDULE_ID` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `COMPANY_ID` int(10) unsigned NOT NULL,
  `PAYROLL_TIME_PERIOD_ID` int(10) unsigned NOT NULL,
  `PAYROLL_TIME_PERIOD_SCHEDULE_ID` int(2) unsigned NOT NULL,
  `ACTIVE` tinyint(1) NOT NULL DEFAULT '1',
  `CREATED_BY` int(10) unsigned NOT NULL,
  `CREATED_DATE` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_BY` int(10) unsigned NOT NULL,
  `UPDATED_DATE` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  PRIMARY KEY (`MONTHLY_SHIFT_SCHEDULE_ID`),
  KEY `FK_MONTHLY_SHIFT_SCHEDULE_CREATED_BY` (`CREATED_BY`),
  KEY `FK_MONTHLY_SHIFT_SCHEDULE_UPDATED_BY` (`UPDATED_BY`),
  KEY `FK_MONTHLY_SHIFT_SCHEDULE_COMPANY_ID` (`COMPANY_ID`),
  KEY `FK_MONTHLY_SHIFT_SCHEDULE_PAYROLL_TIME_PERIOD_ID` (`PAYROLL_TIME_PERIOD_ID`),
  KEY `FK_MONTHLY_SHIFT_SCHEDULE_PAYROLL_TIME_PERIOD_SCHEDULE_ID` (`PAYROLL_TIME_PERIOD_SCHEDULE_ID`),
  CONSTRAINT `FK_MONTHLY_SHIFT_SCHEDULE_COMPANY_ID` FOREIGN KEY (`COMPANY_ID`) REFERENCES `COMPANY` (`COMPANY_ID`),
  CONSTRAINT `FK_MONTHLY_SHIFT_SCHEDULE_CREATED_BY` FOREIGN KEY (`CREATED_BY`) REFERENCES `USER` (`USER_ID`),
  CONSTRAINT `FK_MONTHLY_SHIFT_SCHEDULE_PAYROLL_TIME_PERIOD_ID` FOREIGN KEY (`PAYROLL_TIME_PERIOD_ID`) REFERENCES `PAYROLL_TIME_PERIOD` (`PAYROLL_TIME_PERIOD_ID`),
  CONSTRAINT `FK_MONTHLY_SHIFT_SCHEDULE_PAYROLL_TIME_PERIOD_SCHEDULE_ID` FOREIGN KEY (`PAYROLL_TIME_PERIOD_SCHEDULE_ID`) REFERENCES `PAYROLL_TIME_PERIOD_SCHEDULE` (`PAYROLL_TIME_PERIOD_SCHEDULE_ID`),
  CONSTRAINT `FK_MONTHLY_SHIFT_SCHEDULE_UPDATED_BY` FOREIGN KEY (`UPDATED_BY`) REFERENCES `USER` (`USER_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;