
-- Description: Create script for OVERTIME_DETAIL table.

CREATE TABLE OVERTIME_DETAIL (
	OVERTIME_DETAIL_ID int(10) unsigned NOT NULL AUTO_INCREMENT,
	EMPLOYEE_REQUEST_ID int(10) unsigned NOT NULL,
	OVERTIME_DATE date NOT NULL,
	START_TIME varchar(5) NOT NULL,
	END_TIME varchar(5) NOT NULL,
	OVERTIME_HOURS double(4,2) NOT NULL,
	PURPOSE TEXT,
	PRIMARY KEY (OVERTIME_DETAIL_ID),
	KEY FK_OD_EMPLOYEE_REQUEST_ID (EMPLOYEE_REQUEST_ID),
	CONSTRAINT FK_OD_EMPLOYEE_REQUEST_ID FOREIGN KEY (EMPLOYEE_REQUEST_ID) REFERENCES EMPLOYEE_REQUEST (EMPLOYEE_REQUEST_ID)
) Engine=InnoDB DEFAULT CHARSET=utf8;