
-- Description: SQL script in creating the PAYROLL_TIME_PERIOD_SCHEDULE table

CREATE TABLE `PAYROLL_TIME_PERIOD_SCHEDULE` (
  `PAYROLL_TIME_PERIOD_SCHEDULE_ID` int(10) unsigned NOT NULL,
  `PAYROLL_TIME_PERIOD_ID` int(10) unsigned NOT NULL,
  `NAME` varchar(25) NOT NULL,
  `DATE_FROM` date NOT NULL,
  `DATE_TO` date NOT NULL,
  `COMPUTE_CONTRIBUTIONS` tinyint(1) NOT NULL,
  PRIMARY KEY (`PAYROLL_TIME_PERIOD_SCHEDULE_ID`),
  KEY `FK_PAYROLL_TIME_PERIOD_ID_` (`PAYROLL_TIME_PERIOD_ID`),
  CONSTRAINT `FK_PAYROLL_TIME_PERIOD_ID` FOREIGN KEY (`PAYROLL_TIME_PERIOD_ID`) REFERENCES `PAYROLL_TIME_PERIOD` (`PAYROLL_TIME_PERIOD_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
