
-- Description: Script for creating PAYROLL_EMPLOYEE_TIMESHEET table.

SET FOREIGN_KEY_CHECKS = 0;
DROP TABLE IF EXISTS PAYROLL_EMPLOYEE_TIMESHEET;
SET FOREIGN_KEY_CHECKS = 1;

CREATE TABLE PAYROLL_EMPLOYEE_TIMESHEET (
  PAYROLL_EMPLOYEE_TIMESHEET_ID int(10) unsigned NOT NULL AUTO_INCREMENT,
  PAYROLL_ID int(10) unsigned DEFAULT NULL,
  TIME_SHEET_ID int(10) unsigned DEFAULT NULL,
  EMPLOYEE_ID int(10) unsigned NOT NULL,
  EB_OBJECT_ID int(10) unsigned DEFAULT NULL,
  DATE date NOT NULL,
  HOURS_WORKED double(19, 4) NOT NULL,
  LATE double(19, 4) DEFAULT 0,
  ADJUSTMENT double(19, 4) DEFAULT 0,
  OVERTIME double(19, 4) DEFAULT 0,
  STATUS double(1, 0) DEFAULT NULL,
  UNDERTIME DOUBLE(19, 4) DEFAULT 0,
  STATUS_LABEL VARCHAR(5) DEFAULT NULL,
  PRIMARY KEY (PAYROLL_EMPLOYEE_TIMESHEET_ID),
  KEY FK_PET_EMPLOYEE_ID (EMPLOYEE_ID),
  KEY FK_PET_EB_OBJECT_ID (EB_OBJECT_ID),
  CONSTRAINT FK_PET_EMPLOYEE_ID FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEE (EMPLOYEE_ID),
  CONSTRAINT FK_PET_EB_OBJECT_ID FOREIGN KEY (EB_OBJECT_ID) REFERENCES EB_OBJECT (EB_OBJECT_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;