
-- Description: SQL script in creating the PAYROLL table

SET FOREIGN_KEY_CHECKS = 0;
DROP TABLE IF EXISTS PAYROLL;
SET FOREIGN_KEY_CHECKS = 1;

CREATE TABLE PAYROLL (
  PAYROLL_ID int(10) unsigned NOT NULL AUTO_INCREMENT,
  PAYROLL_TIME_PERIOD_ID int(10) unsigned DEFAULT NULL,
  PAYROLL_TIME_PERIOD_SCHEDULE_ID int(10) unsigned DEFAULT NULL,
  FORM_WORKFLOW_ID int(10) unsigned NOT NULL,
  COMPANY_ID int(10) unsigned NOT NULL,
  DIVISION_ID int(10) unsigned DEFAULT NULL,
  EMPLOYEE_TYPE_ID int(10) unsigned NOT NULL,
  TIME_SHEET_ID int(10) unsigned DEFAULT NULL,
  SEQUENCE_NO int(10) NOT NULL,
  DATE date NOT NULL,
  EB_OBJECT_ID int(10) unsigned NOT NULL,
  BIOMETRIC_MODEL_ID int(10) unsigned DEFAULT NULL,
  CREATED_BY int(10) unsigned NOT NULL,
  CREATED_DATE timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UPDATED_BY int(10) unsigned NOT NULL,
  UPDATED_DATE timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  PRIMARY KEY (PAYROLL_ID),
  KEY FK_PAYROLL_FORM_WORKFLOW_ID (FORM_WORKFLOW_ID),
  KEY FK_PAYROLL_COMPANY_ID (COMPANY_ID),
  KEY FK_PAYROLL_EMPLOYEE_TYPE_ID (EMPLOYEE_TYPE_ID),
  KEY FK_PAYROLL_EB_OBJECT_ID (EB_OBJECT_ID),
  KEY FK_PAYROLL_CREATED_BY (CREATED_BY),
  KEY FK_PAYROLL_UPDATED_BY (UPDATED_BY),
  KEY FK_PTP_PAYROLL (PAYROLL_TIME_PERIOD_ID),
  KEY FK_PTPS_PAYROLL (PAYROLL_TIME_PERIOD_SCHEDULE_ID),
  KEY FK_PAYROLL_DIVISION_ID (DIVISION_ID),
  KEY FK_PAYROLL_TIME_SHEET_ID (TIME_SHEET_ID),
  CONSTRAINT FK_PAYROLL_COMPANY_ID FOREIGN KEY (COMPANY_ID) REFERENCES COMPANY (COMPANY_ID),
  CONSTRAINT FK_PAYROLL_CREATED_BY FOREIGN KEY (CREATED_BY) REFERENCES USER (USER_ID),
  CONSTRAINT FK_PAYROLL_DIVISION_ID FOREIGN KEY (DIVISION_ID) REFERENCES DIVISION (DIVISION_ID),
  CONSTRAINT FK_PAYROLL_EB_OBJECT_ID FOREIGN KEY (EB_OBJECT_ID) REFERENCES EB_OBJECT (EB_OBJECT_ID),
  CONSTRAINT FK_PAYROLL_EMPLOYEE_TYPE_ID FOREIGN KEY (EMPLOYEE_TYPE_ID) REFERENCES EMPLOYEE_TYPE (EMPLOYEE_TYPE_ID),
  CONSTRAINT FK_PAYROLL_FORM_WORKFLOW_ID FOREIGN KEY (FORM_WORKFLOW_ID) REFERENCES FORM_WORKFLOW (FORM_WORKFLOW_ID),
  CONSTRAINT FK_PAYROLL_UPDATED_BY FOREIGN KEY (UPDATED_BY) REFERENCES USER (USER_ID),
  CONSTRAINT FK_PTPS_PAYROLL FOREIGN KEY (PAYROLL_TIME_PERIOD_SCHEDULE_ID) REFERENCES PAYROLL_TIME_PERIOD_SCHEDULE (PAYROLL_TIME_PERIOD_SCHEDULE_ID),
  CONSTRAINT FK_PTP_PAYROLL FOREIGN KEY (PAYROLL_TIME_PERIOD_ID) REFERENCES PAYROLL_TIME_PERIOD (PAYROLL_TIME_PERIOD_ID),
  CONSTRAINT FK_PAYROLL_TIME_SHEET_ID FOREIGN KEY (TIME_SHEET_ID) REFERENCES TIME_SHEET (TIME_SHEET_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;