
-- Description: Create script for PERSONNEL_ACTION_NOTICE table.

DROP TABLE IF EXISTS PERSONNEL_ACTION_NOTICE;

CREATE TABLE PERSONNEL_ACTION_NOTICE (
	PERSONNEL_ACTION_NOTICE_ID int(10) unsigned NOT NULL AUTO_INCREMENT,
	SEQUENCE_NO int(10) unsigned NOT NULL,
	FORM_WORKFLOW_ID int(10) unsigned DEFAULT NULL,
	EB_OBJECT_ID int(10) unsigned DEFAULT NULL,
	COMPANY_ID int(10) unsigned NOT NULL,
	EMPLOYEE_ID int(10) unsigned NOT NULL,
	ACTION_NOTICE_ID int(10) unsigned NOT NULL,
	DATE date NOT NULL,
	JUSTIFICATION TEXT,
	CREATED_BY int(10) unsigned NOT NULL,
	CREATED_DATE timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
	UPDATED_BY int(10) unsigned NOT NULL,
	UPDATED_DATE timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
	PRIMARY KEY (PERSONNEL_ACTION_NOTICE_ID),
	KEY FK_PAN_FORM_WORKFLOW_ID (FORM_WORKFLOW_ID),
	KEY FK_PAN_EB_OBJECT_ID (EB_OBJECT_ID),
	KEY FK_PAN_COMPANY_ID (COMPANY_ID),
	KEY FK_PAN_EMPLOYEE_ID (EMPLOYEE_ID),
    KEY FK_PAN_ACTION_NOTICE_ID (ACTION_NOTICE_ID),
	KEY FK_PAN_CREATED_BY (CREATED_BY),
	KEY FK_PAN_UPDATED_BY (UPDATED_BY),
	CONSTRAINT FK_PAN_FORM_WORKFLOW_ID FOREIGN KEY (FORM_WORKFLOW_ID) REFERENCES FORM_WORKFLOW (FORM_WORKFLOW_ID),
	CONSTRAINT FK_PAN_EB_OBJECT_ID FOREIGN KEY (EB_OBJECT_ID) REFERENCES EB_OBJECT (EB_OBJECT_ID),
	CONSTRAINT FK_PAN_COMPANY_ID FOREIGN KEY (COMPANY_ID) REFERENCES COMPANY (COMPANY_ID),
	CONSTRAINT FK_PAN_EMPLOYEE_ID FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEE (EMPLOYEE_ID),
    CONSTRAINT FK_PAN_ACTION_NOTICE_ID FOREIGN KEY (ACTION_NOTICE_ID) REFERENCES ACTION_NOTICE (ACTION_NOTICE_ID),
	CONSTRAINT FK_PAN_CREATED_BY FOREIGN KEY (CREATED_BY) REFERENCES USER (USER_ID),
	CONSTRAINT FK_PAN_UPDATED_BY FOREIGN KEY (UPDATED_BY) REFERENCES USER (USER_ID)
) Engine=InnoDB DEFAULT CHARSET=utf8;