
-- Description : SQL script in creating TIME_SHEET_HEADER table.

DROP TABLE IF EXISTS TIME_SHEET_HEADER;

CREATE TABLE TIME_SHEET_HEADER (
	TIME_SHEET_HEADER_ID int(10) unsigned NOT NULL AUTO_INCREMENT,
	TIME_SHEET_ID int(10) unsigned NOT NULL,
	BIOMETRIC_MODEL_ID int(10) unsigned NOT NULL,
	PRIMARY KEY (TIME_SHEET_HEADER_ID),
	KEY FK_TSH_ID (TIME_SHEET_ID),
	KEY FK_TSH_BIOMETRIC_MODEL_ID (BIOMETRIC_MODEL_ID),
	CONSTRAINT FK_TSH_ID FOREIGN KEY (TIME_SHEET_ID) REFERENCES TIME_SHEET (TIME_SHEET_ID), 
	CONSTRAINT FK_TSH_BIOMETRIC_MODEL_ID FOREIGN KEY (BIOMETRIC_MODEL_ID) REFERENCES BIOMETRIC_MODEL (BIOMETRIC_MODEL_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;