
-- Description	: Create script for AP_INVOICE_ACCOUNT table.

DROP TABLE IF EXISTS AP_INVOICE_ACCOUNT;

CREATE TABLE AP_INVOICE_ACCOUNT (
	AP_INVOICE_ACCOUNT_ID int(10) unsigned NOT NULL AUTO_INCREMENT,
	COMPANY_ID int(10) unsigned NOT NULL,
	DIVISION_ID int(10) unsigned DEFAULT NULL,
	ACCOUNT_COMBINATION_ID int(10) unsigned NOT NULL,
	DISCOUNT_AC_ID int(10) unsigned NOT NULL,
	ACTIVE tinyint(1) DEFAULT '1',
	CREATED_BY int(10) unsigned NOT NULL,
	CREATED_DATE timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
	UPDATED_BY int(10) unsigned NOT NULL,
	UPDATED_DATE timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
	PRIMARY KEY (AP_INVOICE_ACCOUNT_ID),
	KEY FK_AIA_COMPANY_ID (COMPANY_ID),
	KEY FK_AIA_DIVISION_ID (DIVISION_ID),
	KEY FK_AIA_AC_ID (ACCOUNT_COMBINATION_ID),
	KEY FK_AIA_DISCOUNT_AC_ID (DISCOUNT_AC_ID),
	KEY FK_AIA_CREATED_BY (CREATED_BY),
	KEY FK_AIA_UPDATED_BY (UPDATED_BY),
	CONSTRAINT FK_AIA_COMPANY_ID FOREIGN KEY (COMPANY_ID) REFERENCES COMPANY (COMPANY_ID),
	CONSTRAINT FK_AIA_DIVISION_ID FOREIGN KEY (DIVISION_ID) REFERENCES DIVISION (DIVISION_ID),
	CONSTRAINT FK_AIA_AC_ID FOREIGN KEY (ACCOUNT_COMBINATION_ID) REFERENCES ACCOUNT_COMBINATION (ACCOUNT_COMBINATION_ID),
	CONSTRAINT FK_AIA_DISCOUNT_AC_ID FOREIGN KEY (DISCOUNT_AC_ID) REFERENCES ACCOUNT_COMBINATION (ACCOUNT_COMBINATION_ID),
	CONSTRAINT FK_AIA_CREATED_BY FOREIGN KEY (CREATED_BY) REFERENCES USER (USER_ID),
	CONSTRAINT FK_AIA_UPDATED_BY FOREIGN KEY (UPDATED_BY) REFERENCES USER (USER_ID)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;