
-- Description	: Create script for AR_INVOICE_ACCOUNT table.

DROP TABLE IF EXISTS AR_INVOICE_ACCOUNT;

CREATE TABLE AR_INVOICE_ACCOUNT (
	AR_INVOICE_ACCOUNT_ID int(10) unsigned NOT NULL AUTO_INCREMENT,
	COMPANY_ID int(10) unsigned NOT NULL,
	DIVISION_ID int(10) unsigned DEFAULT NULL,
	RETENTION_AC_ID int(10) unsigned NOT NULL,
	WT_VAT_GOODS_AC_ID int(10) unsigned NOT NULL,
	WT_VAT_SERVICE_AC_ID int(10) unsigned NOT NULL,
	DEFAULT_DISC_AC_ID int(10) unsigned NOT NULL,
	RECOUPMENT_AC_ID int(10) unsigned NOT NULL,
	ACTIVE tinyint(1) DEFAULT '1',
	CREATED_BY int(10) unsigned NOT NULL,
	CREATED_DATE timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
	UPDATED_BY int(10) unsigned NOT NULL,
	UPDATED_DATE timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
	PRIMARY KEY (AR_INVOICE_ACCOUNT_ID),
	KEY FK_ARIA_COMPANY_ID (COMPANY_ID),
	KEY FK_ARIA_DIVISION_ID (DIVISION_ID),
	KEY FK_ARIA_RETENTION_AC_ID (RETENTION_AC_ID),
	KEY FK_ARIA_WT_VAT_GOODS_AC_ID (WT_VAT_GOODS_AC_ID),
	KEY FK_ARIA_WT_VAT_SERVICE_AC_ID (WT_VAT_SERVICE_AC_ID),
	KEY FK_ARIA_DEFAULT_DISC_AC_ID (DEFAULT_DISC_AC_ID),
	KEY FK_ARIA_RECOUPMENT_AC_ID (RECOUPMENT_AC_ID),
	KEY FK_ARIA_CREATED_BY (CREATED_BY),
	KEY FK_ARIA_UPDATED_BY (UPDATED_BY),
	CONSTRAINT FK_ARIA_COMPANY_ID FOREIGN KEY (COMPANY_ID) REFERENCES COMPANY (COMPANY_ID),
	CONSTRAINT FK_ARIA_DIVISION_ID FOREIGN KEY (DIVISION_ID) REFERENCES DIVISION (DIVISION_ID),
	CONSTRAINT FK_ARIA_RETENTION_AC_ID FOREIGN KEY (RETENTION_AC_ID) REFERENCES ACCOUNT_COMBINATION (ACCOUNT_COMBINATION_ID),
	CONSTRAINT FK_ARIA_WT_VAT_GOODS_AC_ID FOREIGN KEY (WT_VAT_GOODS_AC_ID) REFERENCES ACCOUNT_COMBINATION (ACCOUNT_COMBINATION_ID),
	CONSTRAINT FK_ARIA_WT_VAT_SERVICE_AC_ID FOREIGN KEY (WT_VAT_SERVICE_AC_ID) REFERENCES ACCOUNT_COMBINATION (ACCOUNT_COMBINATION_ID),
	CONSTRAINT FK_ARIA_RECOUPMENT_AC_ID FOREIGN KEY (RECOUPMENT_AC_ID) REFERENCES ACCOUNT_COMBINATION (ACCOUNT_COMBINATION_ID),
	CONSTRAINT FK_ARIA_DEFAULT_DISC_AC_ID FOREIGN KEY (DEFAULT_DISC_AC_ID) REFERENCES ACCOUNT_COMBINATION (ACCOUNT_COMBINATION_ID),
	CONSTRAINT FK_ARIA_CREATED_BY FOREIGN KEY (CREATED_BY) REFERENCES USER (USER_ID),
	CONSTRAINT FK_ARIA_UPDATED_BY FOREIGN KEY (UPDATED_BY) REFERENCES USER (USER_ID)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;