
-- Description	: Create script for CUSTOMER_ADVANCE_PAYMENT_ACCOUNT table.

DROP TABLE IF EXISTS CUSTOMER_ADVANCE_PAYMENT_ACCOUNT;

CREATE TABLE CUSTOMER_ADVANCE_PAYMENT_ACCOUNT (
	CUSTOMER_ADVANCE_PAYMENT_ACCOUNT_ID int(10) unsigned NOT NULL AUTO_INCREMENT,
	COMPANY_ID int(10) unsigned NOT NULL,
	DIVISION_ID int(10) unsigned DEFAULT NULL,
	DEFAULT_CREDIT_AC_ID int(10) unsigned NOT NULL,
	ACTIVE tinyint(1) DEFAULT '1',
	CREATED_BY int(10) unsigned NOT NULL,
	CREATED_DATE timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
	UPDATED_BY int(10) unsigned NOT NULL,
	UPDATED_DATE timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
	PRIMARY KEY (CUSTOMER_ADVANCE_PAYMENT_ACCOUNT_ID),
	KEY FK_CAPA_COMPANY_ID (COMPANY_ID),
	KEY FK_CAPA_DIVISION_ID (DIVISION_ID),
	KEY FK_CAPA_DEFAULT_CREDIT_AC_ID (DEFAULT_CREDIT_AC_ID),
	KEY FK_CAPA_CREATED_BY (CREATED_BY),
	KEY FK_CAPA_UPDATED_BY (UPDATED_BY),
	CONSTRAINT FK_CAPA_COMPANY_ID FOREIGN KEY (COMPANY_ID) REFERENCES COMPANY (COMPANY_ID),
	CONSTRAINT FK_CAPA_DIVISION_ID FOREIGN KEY (DIVISION_ID) REFERENCES DIVISION (DIVISION_ID),
	CONSTRAINT FK_CAPA_DEFAULT_CREDIT_AC_ID FOREIGN KEY (DEFAULT_CREDIT_AC_ID) REFERENCES ACCOUNT_COMBINATION (ACCOUNT_COMBINATION_ID),
	CONSTRAINT FK_CAPA_CREATED_BY FOREIGN KEY (CREATED_BY) REFERENCES USER (USER_ID),
	CONSTRAINT FK_CAPA_UPDATED_BY FOREIGN KEY (UPDATED_BY) REFERENCES USER (USER_ID)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;