
-- Description : JYEI extension table for withdrawal slip.

DROP TABLE IF EXISTS JYEI_WITHDRAWAL_SLIP;

CREATE TABLE JYEI_WITHDRAWAL_SLIP (
	JYEI_WITHDRAWAL_SLIP_ID int(10) unsigned NOT NULL AUTO_INCREMENT,
	WITHDRAWAL_SLIP_ID int(10) unsigned NOT NULL,
	REQUISITION_TYPE_ID int(10) unsigned NOT NULL,
	WITHDRAWN_BY varchar(100) DEFAULT NULL,
	PRIMARY KEY (JYEI_WITHDRAWAL_SLIP_ID),
	KEY FK_JWS_WITHDRAWAL_SLIP_ID (WITHDRAWAL_SLIP_ID),
	KEY FK_JWS_REQUISITION_TYPE_ID (REQUISITION_TYPE_ID),
	CONSTRAINT FK_JWS_WITHDRAWAL_SLIP_ID FOREIGN KEY (WITHDRAWAL_SLIP_ID) REFERENCES WITHDRAWAL_SLIP (WITHDRAWAL_SLIP_ID),
	CONSTRAINT FK_JWS_REQUISITION_TYPE_ID FOREIGN KEY (REQUISITION_TYPE_ID) REFERENCES REQUISITION_TYPE (REQUISITION_TYPE_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;