
-- Description	: Create script for OTHER_CHARGES_LINE table.

DROP TABLE IF EXISTS OTHER_CHARGES_LINE;

CREATE TABLE OTHER_CHARGES_LINE (
	OTHER_CHARGES_LINE_ID int(10) unsigned NOT NULL AUTO_INCREMENT,
	AP_LINE_SETUP_ID int(10) unsigned NOT NULL,
	EB_OBJECT_ID int(10) unsigned NOT NULL,
	UNITOFMEASUREMENT_ID int(10) DEFAULT NULL,
	QUANTITY double DEFAULT NULL,
	UP_AMOUNT double DEFAULT NULL,
	AMOUNT double NOT NULL,
	PRIMARY KEY (OTHER_CHARGES_LINE_ID),
	KEY FK_OCL_AP_LINE_SETUP_ID (AP_LINE_SETUP_ID),
	KEY FK_OCL_EB_OBJECT_ID (EB_OBJECT_ID),
	CONSTRAINT FK_OCL_AP_LINE_SETUP_ID FOREIGN KEY (AP_LINE_SETUP_ID) REFERENCES AP_LINE_SETUP (AP_LINE_SETUP_ID),
	CONSTRAINT FK_OCL_EB_OBJECT_ID FOREIGN KEY (EB_OBJECT_ID) REFERENCES EB_OBJECT (EB_OBJECT_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;