
-- Description: Sql script for creating PETTY_CASH_VOUCHER_LIQUIDATION_LINE table

DROP TABLE IF EXISTS PETTY_CASH_VOUCHER_LIQUIDATION_LINE;

CREATE TABLE PETTY_CASH_VOUCHER_LIQUIDATION_LINE (
	PETTY_CASH_VOUCHER_LIQUIDATION_LINE_ID int(10) unsigned NOT NULL AUTO_INCREMENT,
	PETTY_CASH_VOUCHER_LIQUIDATION_ID int(10) unsigned NOT NULL,
	EB_OBJECT_ID int(10) unsigned DEFAULT NULL,
	PCV_DATE date NOT NULL,
	BMS_NUMBER varchar(50) DEFAULT NULL,
	OR_NUMBER varchar(50) NOT NULL,
	ACCOUNT_COMBINATION_ID int(10) unsigned NOT NULL,
	SUPPLIER_ID int(10) unsigned NOT NULL,
	DESCRIPTION text,
	UNITOFMEASUREMENT_ID int(10) unsigned DEFAULT NULL,
	QUANTITY double DEFAULT NULL,
	UP_AMOUNT double DEFAULT NULL,
	TAX_TYPE_ID int(10) unsigned DEFAULT NULL,
	VAT_AMOUNT double DEFAULT '0',
	AMOUNT double NOT NULL,
	PRIMARY KEY (PETTY_CASH_VOUCHER_LIQUIDATION_LINE_ID),
	KEY FK_PCVL_EB_OBJECT_ID (EB_OBJECT_ID),
	KEY FK_PCVL_ACCOUNT_COMBINATION_ID (ACCOUNT_COMBINATION_ID),
	KEY FK_PCVL_PETTY_CASH_VOUCHER_LIQUIDATION_ID (PETTY_CASH_VOUCHER_LIQUIDATION_ID),
	KEY FK_PCVL_SUPPLIER_ID (SUPPLIER_ID),
	KEY FK_PCVL_TAX_TYPE_ID (TAX_TYPE_ID),
	CONSTRAINT FK_PCVL_EB_OBJECT_ID FOREIGN KEY (EB_OBJECT_ID) REFERENCES EB_OBJECT (EB_OBJECT_ID),
	CONSTRAINT FK_PCVL_ACCOUNT_COMBINATION_ID FOREIGN KEY (ACCOUNT_COMBINATION_ID) REFERENCES ACCOUNT_COMBINATION (ACCOUNT_COMBINATION_ID),
	CONSTRAINT FK_PCVL_PETTY_CASH_VOUCHER_LIQUIDATION_ID FOREIGN KEY (PETTY_CASH_VOUCHER_LIQUIDATION_ID) REFERENCES PETTY_CASH_VOUCHER_LIQUIDATION (PETTY_CASH_VOUCHER_LIQUIDATION_ID),
	CONSTRAINT FK_PCVL_SUPPLIER_ID FOREIGN KEY (SUPPLIER_ID) REFERENCES SUPPLIER (SUPPLIER_ID),
	CONSTRAINT FK_PCVL_TAX_TYPE_ID FOREIGN KEY (TAX_TYPE_ID) REFERENCES TAX_TYPE (TAX_TYPE_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;