
-- Description	: Create script for PROJECT_RETENTION_LINE table.

DROP TABLE IF EXISTS PROJECT_RETENTION_LINE;

CREATE TABLE PROJECT_RETENTION_LINE (
	PROJECT_RETENTION_LINE_ID int(10) unsigned NOT NULL AUTO_INCREMENT,
	PROJECT_RETENTION_ID int(10) unsigned NOT NULL,
	EB_OBJECT_ID int(10) unsigned DEFAULT NULL,
	TAX_TYPE_ID int(10) unsigned DEFAULT NULL,
	UP_AMOUNT double DEFAULT 0,
	AMOUNT double DEFAULT 0,
	VAT_AMOUNT double DEFAULT 0,
	CURRENCY_RATE_VALUE double DEFAULT 0,
	PRIMARY KEY (PROJECT_RETENTION_LINE_ID),
	KEY FK_PRL_PROJECT_RETENTION_ID (PROJECT_RETENTION_ID),
	KEY FK_PRL_EB_OBJECT_ID (EB_OBJECT_ID),
	KEY FK_PRL_TAX_TYPE_ID (TAX_TYPE_ID),
	CONSTRAINT FK_PRL_PROJECT_RETENTION_ID FOREIGN KEY (PROJECT_RETENTION_ID) REFERENCES PROJECT_RETENTION (PROJECT_RETENTION_ID),
	CONSTRAINT FK_PRL_EB_OBJECT_ID FOREIGN KEY (EB_OBJECT_ID) REFERENCES EB_OBJECT (EB_OBJECT_ID),
	CONSTRAINT FK_PRL_TAX_TYPE_ID FOREIGN KEY (TAX_TYPE_ID) REFERENCES TAX_TYPE (TAX_TYPE_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;