
-- Description: Create script for PROJECT Table.
DROP TABLE IF EXISTS PROJECT;

CREATE TABLE PROJECT (
	PROJECT_ID int(10) unsigned NOT NULL AUTO_INCREMENT,
	NAME varchar(50) NOT NULL,
	ACTIVE tinyint(1) NOT NULL,
	CREATED_BY int(10) unsigned NOT NULL,
	CREATED_DATE timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
	UPDATED_BY int(10) unsigned NOT NULL,
	UPDATED_DATE timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
	PRIMARY KEY (PROJECT_ID),
	KEY FK_PROJECT_CREATED_BY (CREATED_BY),
	KEY FK_PROJECT_UPDATED_BY (UPDATED_BY),
	CONSTRAINT FK_PROJECT_CREATED_BY FOREIGN KEY (CREATED_BY) REFERENCES USER (USER_ID),
	CONSTRAINT FK_PROJECT_UPDATED_BY FOREIGN KEY (UPDATED_BY) REFERENCES USER (USER_ID)
)ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE utf8_spanish_ci;