
-- Description : Create script for PURCHASE_REQUISITION_ITEM table.

DROP TABLE IF EXISTS PURCHASE_REQUISITION_ITEM;

CREATE TABLE PURCHASE_REQUISITION_ITEM (
	PURCHASE_REQUISITION_ITEM_ID int(10) unsigned NOT NULL AUTO_INCREMENT,
	PURCHASE_REQUISITION_ID int(10) unsigned NOT NULL,
	EB_OBJECT_ID int(10) unsigned DEFAULT NULL,
	ITEM_ID int(10) unsigned NOT NULL,
	QUANTITY double NOT NULL,
	UNIT_COST double DEFAULT 0,
	PRIMARY KEY (PURCHASE_REQUISITION_ITEM_ID),
	KEY FK_PRI_PR_ID (PURCHASE_REQUISITION_ID),
	KEY FK_PRI_EB_OBJECT_ID (EB_OBJECT_ID),
	KEY FK_PRI_ITEM_ID (ITEM_ID),
	CONSTRAINT FK_PRI_PR_ID FOREIGN KEY (PURCHASE_REQUISITION_ID) REFERENCES REQUISITION_FORM (REQUISITION_FORM_ID),
	CONSTRAINT FK_PRI_EB_OBJECT_ID FOREIGN KEY (EB_OBJECT_ID) REFERENCES EB_OBJECT (EB_OBJECT_ID),
	CONSTRAINT FK_PRI_ITEM_ID FOREIGN KEY (ITEM_ID) REFERENCES ITEM (ITEM_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;