
-- Description : Create script for REQUISITION_FORM_ITEM table.
DROP TABLE IF EXISTS REQUISITION_FORM_ITEM;

CREATE TABLE REQUISITION_FORM_ITEM (
	REQUISITION_FORM_ITEM_ID int(10) unsigned NOT NULL AUTO_INCREMENT,
	EB_OBJECT_ID int(10) unsigned NOT NULL,
	WAREHOUSE_ID int(10) unsigned DEFAULT NULL,
	ITEM_ID int(10) unsigned NOT NULL,
	QUANTITY double NOT NULL,
	UNIT_COST double DEFAULT 0,
	PRIMARY KEY (REQUISITION_FORM_ITEM_ID),
	KEY FK_REQUISITION_FORM_ITEM_EB_OBJECT_ID (EB_OBJECT_ID),
	KEY FK_REQUISITION_FORM_ITEM_WAREHOUSE_ID (WAREHOUSE_ID),
	KEY FK_REQUISITION_FORM_ITEM_ITEM_ID (ITEM_ID),
	CONSTRAINT FK_REQUISITION_FORM_ITEM_EB_OBJECT_ID FOREIGN KEY (EB_OBJECT_ID) REFERENCES EB_OBJECT (EB_OBJECT_ID),
	CONSTRAINT FK_REQUISITION_FORM_ITEM_WAREHOUSE_ID FOREIGN KEY (WAREHOUSE_ID) REFERENCES WAREHOUSE (WAREHOUSE_ID),
	CONSTRAINT FK_REQUISITION_FORM_ITEM_ITEM_ID FOREIGN KEY (ITEM_ID) REFERENCES ITEM (ITEM_ID)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;