
-- Description	: Create script for SUPPLIER_ADV_PAYMENT_ACCOUNT table.

DROP TABLE IF EXISTS SUPPLIER_ADV_PAYMENT_ACCOUNT;

CREATE TABLE SUPPLIER_ADV_PAYMENT_ACCOUNT (
	SUPPLIER_ADV_PAYMENT_ACCOUNT_ID int(10) unsigned NOT NULL AUTO_INCREMENT,
	COMPANY_ID int(10) unsigned NOT NULL,
	DIVISION_ID int(10) unsigned NOT NULL,
	ACCOUNT_COMBINATION_ID int(10) unsigned NOT NULL,
	ACTIVE tinyint(1) DEFAULT '1',
	CREATED_BY int(10) unsigned NOT NULL,
	CREATED_DATE timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
	UPDATED_BY int(10) unsigned NOT NULL,
	UPDATED_DATE timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
	PRIMARY KEY (SUPPLIER_ADV_PAYMENT_ACCOUNT_ID),
	KEY FK_SAPA_COMPANY_ID (COMPANY_ID),
	KEY FK_SAPA_DIVISION_ID (DIVISION_ID),
	KEY FK_SAPA_AC_ID (ACCOUNT_COMBINATION_ID),
	KEY FK_SAPA_CREATED_BY (CREATED_BY),
	KEY FK_SAPA_UPDATED_BY (UPDATED_BY),
	CONSTRAINT FK_SAPA_COMPANY_ID FOREIGN KEY (COMPANY_ID) REFERENCES COMPANY (COMPANY_ID),
	CONSTRAINT FK_SAPA_DIVISION_ID FOREIGN KEY (DIVISION_ID) REFERENCES DIVISION (DIVISION_ID),
	CONSTRAINT FK_SAPA_AC_ID FOREIGN KEY (ACCOUNT_COMBINATION_ID) REFERENCES ACCOUNT_COMBINATION (ACCOUNT_COMBINATION_ID),
	CONSTRAINT FK_SAPA_CREATED_BY FOREIGN KEY (CREATED_BY) REFERENCES USER (USER_ID),
	CONSTRAINT FK_SAPA_UPDATED_BY FOREIGN KEY (UPDATED_BY) REFERENCES USER (USER_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;