
-- Description	: A create script that will create WORK_ORDER_INSTRUCTION table

DROP TABLE IF EXISTS WORK_ORDER_INSTRUCTION;

CREATE TABLE WORK_ORDER_INSTRUCTION (
	WORK_ORDER_INSTRUCTION_ID int(10) unsigned NOT NULL AUTO_INCREMENT,
	WORK_ORDER_ID int(10) unsigned NOT NULL,
	EB_OBJECT_ID int(10) unsigned DEFAULT NULL,
	WORK_INSTRUCTION TEXT,
	PRIMARY KEY (WORK_ORDER_INSTRUCTION_ID),
	KEY FK_WO_IN_WORK_ORDER_ID (WORK_ORDER_ID),
	KEY FK_WO_IN_EB_OBJECT_ID (EB_OBJECT_ID),
	CONSTRAINT FK_WO_IN_WORK_ORDER_ID FOREIGN KEY (WORK_ORDER_ID) REFERENCES WORK_ORDER (WORK_ORDER_ID),
	CONSTRAINT FK_WO_IN_EB_OBJECT_ID FOREIGN KEY (EB_OBJECT_ID) REFERENCES EB_OBJECT (EB_OBJECT_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;