
-- Description	: Create script for WORK_ORDER

DROP TABLE IF EXISTS WORK_ORDER;

CREATE TABLE WORK_ORDER (
	WORK_ORDER_ID int(10) unsigned NOT NULL AUTO_INCREMENT,
	SALES_ORDER_ID int(10) unsigned DEFAULT NULL,
	REFERENCE_WORK_ORDER_ID int(10) unsigned DEFAULT NULL,
	FORM_WORKFLOW_ID int(10) unsigned NOT NULL,
	EB_OBJECT_ID int(10) unsigned DEFAULT NULL,
	SEQUENCE_NO int(10) unsigned NOT NULL,
	COMPANY_ID int(10) unsigned NOT NULL,
	AR_CUSTOMER_ID int(10) unsigned NOT NULL,
	AR_CUSTOMER_ACCOUNT_ID int(10) unsigned NOT NULL,
	DATE date NOT NULL,
	TARGET_END_DATE date NOT NULL,
	WORK_DESCRIPTION text DEFAULT NULL,
	CREATED_BY INT(10) UNSIGNED NOT NULL,
	CREATED_DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	UPDATED_BY INT(10) UNSIGNED NOT NULL,
	UPDATED_DATE TIMESTAMP NOT NULL DEFAULT '0000-00-00 00:00:00',
	PRIMARY KEY (WORK_ORDER_ID),
	KEY FK_WO_SALES_ORDER_ID (SALES_ORDER_ID),
	KEY FK_WO_REFERENCE_WORK_ORDER_ID (REFERENCE_WORK_ORDER_ID),
	KEY FK_WO_FORM_WORKFLOW_ID (FORM_WORKFLOW_ID),
	KEY FK_WO_EB_OBJECT_ID (EB_OBJECT_ID),
	KEY FK_WO_COMPANY_ID (COMPANY_ID),
	KEY FK_WO_CS_ID (AR_CUSTOMER_ID),
	KEY FK_WO_CS_ACCT_ID (AR_CUSTOMER_ACCOUNT_ID),
	KEY FK_WO_CREATED_BY (CREATED_BY),
	KEY FK_WO_UPDATED_BY (UPDATED_BY),
	CONSTRAINT FK_WO_SALES_ORDER_ID FOREIGN KEY (SALES_ORDER_ID) REFERENCES SALES_ORDER (SALES_ORDER_ID),
	CONSTRAINT FK_WO_REFERENCE_WORK_ORDER_ID FOREIGN KEY (REFERENCE_WORK_ORDER_ID) REFERENCES WORK_ORDER (WORK_ORDER_ID),
	CONSTRAINT FK_WO_FORM_WORKFLOW_ID FOREIGN KEY (FORM_WORKFLOW_ID) REFERENCES FORM_WORKFLOW (FORM_WORKFLOW_ID),
	CONSTRAINT FK_WO_EB_OBJECT_ID FOREIGN KEY (EB_OBJECT_ID) REFERENCES EB_OBJECT (EB_OBJECT_ID),
	CONSTRAINT FK_WO_COMPANY_ID FOREIGN KEY (COMPANY_ID) REFERENCES COMPANY (COMPANY_ID),
	CONSTRAINT FK_WO_CS_ID FOREIGN KEY (AR_CUSTOMER_ID) REFERENCES AR_CUSTOMER (AR_CUSTOMER_ID),
	CONSTRAINT FK_WO_CS_ACCT_ID FOREIGN KEY (AR_CUSTOMER_ACCOUNT_ID) REFERENCES AR_CUSTOMER_ACCOUNT (AR_CUSTOMER_ACCOUNT_ID),
	CONSTRAINT FK_WO_CREATED_BY FOREIGN KEY (CREATED_BY) REFERENCES USER (USER_ID),
	CONSTRAINT FK_WO_UPDATED_BY FOREIGN KEY (UPDATED_BY) REFERENCES USER (USER_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;