
-- Description: Create script for Civil Status Table.

DROP TABLE IF EXISTS CIVIL_STATUS;

CREATE TABLE CIVIL_STATUS(
 CIVIL_STATUS_ID INT(10) unsigned NOT NULL AUTO_INCREMENT,
 NAME varchar(10),
 ACTIVE tinyint(1) NOT NULL,
 CREATED_BY INT(10) unsigned NOT NULL,
 CREATED_DATE timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
 UPDATED_BY INT(10) unsigned NOT NULL,
 UPDATED_DATE timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
 PRIMARY KEY (CIVIL_STATUS_ID),
 KEY FK_CIVIL_STATUS_CREATED_BY (CREATED_BY),
 KEY FK_CIVIL_STATUS_UPDATED_BY (UPDATED_BY),
 CONSTRAINT FK_CIVIL_STATUS_CREATED_BY FOREIGN KEY (CREATED_BY) REFERENCES USER (USER_ID),
 CONSTRAINT FK_CIVIL_STATUS_UPDATED_BY FOREIGN KEY (UPDATED_BY) REFERENCES USER (USER_ID)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;