
-- Description: SQL script in creating COMPANY table.

DROP TABLE IF EXISTS COMPANY;

CREATE TABLE `COMPANY` (
  `COMPANY_ID` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `EB_OBJECT_ID` int(10) unsigned DEFAULT NULL,
  `NUMBER` varchar(5) NOT NULL,
  `NAME` varchar(100) NOT NULL,
  `ADDRESS` varchar(200) NOT NULL,
  `TIN` varchar(15) DEFAULT NULL,
  `CONTACT_NUMBER` varchar(20) DEFAULT NULL,
  `EMAIL_ADDRESS` varchar(50) DEFAULT NULL,
  `ACTIVE` tinyint(1) NOT NULL,
  `LOGO` varchar(50) DEFAULT NULL,
  `CREATED_BY` int(10) unsigned DEFAULT NULL,
  `CREATED_DATE` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_BY` int(10) unsigned DEFAULT NULL,
  `UPDATED_DATE` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  `EB_SL_KEY_ID` int(10) unsigned NOT NULL DEFAULT '1',
  `COMPANY_CODE` VARCHAR(10),
  PRIMARY KEY (`COMPANY_ID`),
  KEY `EB_SL_KEY_ID` (`EB_SL_KEY_ID`),
  KEY `FK_COMPANY_EB_OBJECT_ID` (`EB_OBJECT_ID`),
  CONSTRAINT `COMPANY_ibfk_1` FOREIGN KEY (`EB_SL_KEY_ID`) REFERENCES `EB_SL_KEY` (`EB_SL_KEY_ID`),
  CONSTRAINT `FK_COMPANY_EB_OBJECT_ID` FOREIGN KEY (`EB_OBJECT_ID`) REFERENCES `EB_OBJECT` (`EB_OBJECT_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
