
-- Description: SQL script in creating COMPANY_PRODUCT table.

DROP TABLE IF EXISTS COMPANY_PRODUCT;

CREATE TABLE `COMPANY_PRODUCT` (
  `COMPANY_PRODUCT_ID` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `COMPANY_ID` int(10) unsigned NOT NULL,
  `CODE` int(10) unsigned NOT NULL,
  `CREATED_BY` int(10) unsigned NOT NULL,
  `CREATED_DATE` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_BY` int(10) unsigned NOT NULL,
  `UPDATED_DATE` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  PRIMARY KEY (`COMPANY_PRODUCT_ID`),
  KEY `FK_COMPANY_ID` (`COMPANY_ID`),
  CONSTRAINT `FK_COMPANY_ID` FOREIGN KEY (`COMPANY_ID`) REFERENCES `COMPANY` (`COMPANY_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;