
-- Description: sql script in creating EL_CLIENT_INFO. 
DROP TABLE IF EXISTS EB_CLIENT_INFO;

CREATE TABLE EB_CLIENT_INFO (
       EB_CLIENT_INFO_ID int(10) unsigned NOT NULL AUTO_INCREMENT,
       NAME varchar(100) NOT NULL,
       ADDRESS varchar(150) NOT NULL,
       CONTACT_INFO varchar(15) NOT NULL,
       EMAIL_ADDRESS varchar(100) NOT NULL,
       CREATED_BY int(10) unsigned NOT NULL,
       CREATED_DATE timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
       UPDATED_BY int(10) unsigned NOT NULL,
       UPDATED_DATE timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
       PRIMARY KEY (EB_CLIENT_INFO_ID),
       KEY FK_EB_CLIENT_INFO_CREATED_BY (CREATED_BY),
       KEY FK_EB_CLIENT_INFO_UPDATED_BY (UPDATED_BY),
       CONSTRAINT FK_EB_CLIENT_INFO_CREATED_BY FOREIGN KEY (CREATED_BY) REFERENCES USER (USER_ID),
       CONSTRAINT FK_EB_CLIENT_INFO_UPDATED_BY FOREIGN KEY (UPDATED_BY) REFERENCES USER (USER_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;