
-- Description: sql script in creating EL_SL_KEY(Elasticbooks Service Lease key). 
DROP TABLE IF EXISTS EB_SL_KEY;

CREATE TABLE EB_SL_KEY (
       EB_SL_KEY_ID int(10) unsigned NOT NULL AUTO_INCREMENT,
       START_DATE timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
       END_DATE timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
       EB_CLIENT_INFO_ID  int(10) unsigned NOT NULL,
       CREATED_BY int(10) unsigned NOT NULL,
       CREATED_DATE timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
       UPDATED_BY int(10) unsigned NOT NULL,
       UPDATED_DATE timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
       ACTIVE tinyint(1) NOT NULL,
       PRIMARY KEY (EB_SL_KEY_ID),
       KEY FK_EB_CLIENT_INFO_ID_EL_SL_KEY_ID (EB_CLIENT_INFO_ID),
       KEY FK_EB_SL_KEY_CREATED_BY (CREATED_BY),
       KEY FK_EB_SL_KEY_UPDATED_BY (UPDATED_BY),
       CONSTRAINT FK_EB_CLIENT_INFO_ID_EL_SL_KEY_ID FOREIGN KEY (EB_CLIENT_INFO_ID) REFERENCES EB_CLIENT_INFO (EB_CLIENT_INFO_ID),
       CONSTRAINT FK_EB_SL_KEY_CREATED_BY FOREIGN KEY (CREATED_BY) REFERENCES USER (USER_ID),
       CONSTRAINT FK_EB_SL_KEY_UPDATED_BY FOREIGN KEY (UPDATED_BY) REFERENCES USER (USER_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;