
-- Description: SQL script in creating MF_ACCESS_RIGHT table.

DROP TABLE IF EXISTS UG_MF_ACCESS_RIGHT;

CREATE TABLE `UG_MF_ACCESS_RIGHT` (
  `UG_MF_ACCESS_RIGHT_ID` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `USER_GROUP_ID` int(10) unsigned NOT NULL,
  `MODULE_CODE_ID` int(10) unsigned NOT NULL,
  `ACCESS_RIGHT_FLAG` int(10) unsigned NOT NULL,
  `CREATED_BY` int(10) unsigned NOT NULL,
  `CREATED_DATE` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_BY` int(10) unsigned NOT NULL,
  `UPDATED_DATE` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  PRIMARY KEY (`UG_MF_ACCESS_RIGHT_ID`) USING BTREE,
  KEY `FK_UG_MF_MODULE_CODE_ID` (`MODULE_CODE_ID`),
  KEY `FK_UG_MF_USER_GROUP_ID` (`USER_GROUP_ID`),
  CONSTRAINT `FK_UG_MF_USER_GROUP_ID` FOREIGN KEY (`USER_GROUP_ID`) REFERENCES `USER_GROUP` (`USER_GROUP_ID`),
  CONSTRAINT `FK_UG_MF_MODULE_CODE_ID` FOREIGN KEY (`MODULE_CODE_ID`) REFERENCES `MODULE_CODE` (`MODULE_CODE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;