
-- Description: sql script in creating USER_GROUP table
-- TODO: update the foreign key.

DROP TABLE IF EXISTS USER_GROUP;

CREATE TABLE `USER_GROUP` (
  `USER_GROUP_ID` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `NAME` varchar(50) NOT NULL,
  `DESCRIPTION` varchar(150) DEFAULT NULL,
  `ACTIVE` tinyint(1) NOT NULL,
  `CREATED_BY` int(10) DEFAULT NULL,
  `CREATED_DATE` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_BY` int(10) DEFAULT NULL,
  `UPDATED_DATE` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  PRIMARY KEY (`USER_GROUP_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;