
-- Description: sql script in creating User Company table

DROP TABLE IF EXISTS `USER_COMPANY`;

CREATE TABLE `USER_COMPANY` (
  `USER_COMPANY_ID` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `USER_ID` int(10) unsigned NOT NULL,
  `COMPANY_ID` int(10) unsigned NOT NULL,
  `USER_COMPANY_HEAD_ID` int(10) unsigned DEFAULT NULL,
  `ACTIVE` tinyint(1) DEFAULT NULL,
  `CREATED_BY` int(10) DEFAULT NULL,
  `CREATED_DATE` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_BY` int(10) DEFAULT NULL,
  `UPDATED_DATE` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  PRIMARY KEY (`USER_COMPANY_ID`),
  KEY `FK_USER_COMPANY_USER` (`USER_ID`),
  KEY `FK_USER_COMPANY_COMPANY` (`COMPANY_ID`),
  KEY `FK_USER_COMPANY_USER_COMPANY_HEAD_ID` (`USER_COMPANY_HEAD_ID`),
  CONSTRAINT `FK_USER_COMPANY_COMPANY` FOREIGN KEY (`COMPANY_ID`) REFERENCES `COMPANY` (`COMPANY_ID`),
  CONSTRAINT `FK_USER_COMPANY_USER` FOREIGN KEY (`USER_ID`) REFERENCES `USER` (`USER_ID`),
  CONSTRAINT `FK_USER_COMPANY_USER_COMPANY_HEAD_ID` FOREIGN KEY (`USER_COMPANY_HEAD_ID`) 
   REFERENCES `USER_COMPANY_HEAD` (`USER_COMPANY_HEAD_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;