
-- Description: sql script in creating User table

DROP TABLE IF EXISTS USER;

CREATE TABLE `USER` (
  `USER_ID` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `USER_NAME` varchar(20) NOT NULL,
  `PASSWORD` blob,
  `FIRST_NAME` varchar(40) NOT NULL,
  `LAST_NAME` varchar(40) NOT NULL,
  `MIDDLE_NAME` varchar(40) NOT NULL,
  `BIRTH_DATE` date NOT NULL,
  `CONTACT_NUMBER` varchar(20) NOT NULL,
  `EMAIL_ADDRESS` varchar(50) DEFAULT NULL,
  `ADDRESS` varchar(150) NOT NULL,
  `USER_GROUP_ID` int(10) unsigned NOT NULL,
  `POSITION_ID` int(10) unsigned DEFAULT NULL,
  `COMPANY_ID` int(10) unsigned NOT NULL,
  `EB_OBJECT_ID` int(10) unsigned DEFAULT NULL,
  `CREATED_BY` int(10) DEFAULT NULL,
  `CREATED_DATE` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_BY` int(10) DEFAULT NULL,
  `UPDATED_DATE` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  `ACTIVE` tinyint(1) NOT NULL,
  `EB_SL_KEY_ID` int(10) unsigned NOT NULL DEFAULT '0',
  PRIMARY KEY (`USER_ID`),
  KEY `FK_USER_USER_GROUP` (`USER_GROUP_ID`),
  KEY `FK_USER_COMPANY_ID` (`COMPANY_ID`),
  KEY `EB_SL_KEY_ID` (`EB_SL_KEY_ID`),
  KEY `FK_USER_POSITION_ID` (`POSITION_ID`),
  KEY `FK_USER_EB_OBJECT_ID` (`EB_OBJECT_ID`),
  CONSTRAINT `FK_USER_COMPANY_ID` FOREIGN KEY (`COMPANY_ID`) REFERENCES `COMPANY` (`COMPANY_ID`),
  CONSTRAINT `FK_USER_POSITION_ID` FOREIGN KEY (`POSITION_ID`) REFERENCES `POSITION` (`POSITION_ID`),
  CONSTRAINT `USER_ibfk_1` FOREIGN KEY (`EB_SL_KEY_ID`) REFERENCES `EB_SL_KEY` (`EB_SL_KEY_ID`),
  CONSTRAINT `FK_USER_EB_OBJECT_ID` FOREIGN KEY (`EB_OBJECT_ID`) REFERENCES `EB_OBJECT` (`EB_OBJECT_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;