
-- Description: sql script in creating User Company Head table

DROP TABLE IF EXISTS `USER_COMPANY_HEAD`;

CREATE TABLE `USER_COMPANY_HEAD` (
  `USER_COMPANY_HEAD_ID` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `ACTIVE` tinyint DEFAULT 0,
  `CREATED_BY` int(10) unsigned DEFAULT NULL,
  `CREATED_DATE` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_BY` int(10) unsigned DEFAULT NULL,
  `UPDATED_DATE` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  PRIMARY KEY (`USER_COMPANY_HEAD_ID`),
  KEY `FK_USER_COMP_CREATED_BY` (`CREATED_BY`),
  KEY `FK_USER_COMP_UPDATED_BY` (`UPDATED_BY`),
  CONSTRAINT `FK_USER_COMP_CREATED_BY` FOREIGN KEY (`CREATED_BY`) REFERENCES `USER` (`USER_ID`),
  CONSTRAINT `FK_USER_COMP_UPDATED_BY` FOREIGN KEY (`UPDATED_BY`) REFERENCES `USER` (`USER_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;