
-- Description	: Consolidated inscert script for creditable withholding tax data.

source ~/CMS/src/eulap/eb/conf/db/update/update_wtax_acct_setting_add_creditable_08_25_2020_14_01.sql

INSERT INTO EB_OBJECT(OBJECT_TYPE_ID, CREATED_BY, CREATED_DATE) VALUES (132, 1, NOW());
INSERT INTO EB_OBJECT(OBJECT_TYPE_ID, CREATED_BY, CREATED_DATE) VALUES (132, 1, NOW());
INSERT INTO EB_OBJECT(OBJECT_TYPE_ID, CREATED_BY, CREATED_DATE) VALUES (132, 1, NOW());
INSERT INTO EB_OBJECT(OBJECT_TYPE_ID, CREATED_BY, CREATED_DATE) VALUES (132, 1, NOW());
INSERT INTO EB_OBJECT(OBJECT_TYPE_ID, CREATED_BY, CREATED_DATE) VALUES (132, 1, NOW());
INSERT INTO EB_OBJECT(OBJECT_TYPE_ID, CREATED_BY, CREATED_DATE) VALUES (132, 1, NOW());
INSERT INTO EB_OBJECT(OBJECT_TYPE_ID, CREATED_BY, CREATED_DATE) VALUES (132, 1, NOW());

INSERT INTO ACCOUNT (NUMBER, ACCOUNT_NAME, DESCRIPTION, ACCOUNT_TYPE_ID, RELATED_ACCOUNT_ID, EB_OBJECT_ID, ACTIVE, CREATED_BY, CREATED_DATE, UPDATED_BY, UPDATED_DATE, EB_SL_KEY_ID)
VALUES ('6021500000', 'CWT 1% - WI 158/WC 158', 'CWT 1% - WI 158/WC 158', 1, NULL, (SELECT EB_OBJECT_ID FROM EB_OBJECT WHERE OBJECT_TYPE_ID = 132 LIMIT 7, 1), 1, 1, NOW(), 1, NOW(), 1),
('6021600000', 'CWT 1% - WI 630/WC 630', 'CWT 1% - WI 630/WC 630', 1, NULL, (SELECT EB_OBJECT_ID FROM EB_OBJECT WHERE OBJECT_TYPE_ID = 132 LIMIT 8, 1), 1, 1, NOW(), 1, NOW(), 1),
('6021700000', 'CWT 2% - WI 120/WC 120', 'CWT 2% - WI 120/WC 120', 1, NULL, (SELECT EB_OBJECT_ID FROM EB_OBJECT WHERE OBJECT_TYPE_ID = 132 LIMIT 9, 1), 1, 1, NOW(), 1, NOW(), 1),
('6021800000', 'CWT 2% - WI 160/WC 160', 'CWT 2% - WI 160/WC 160', 1, NULL, (SELECT EB_OBJECT_ID FROM EB_OBJECT WHERE OBJECT_TYPE_ID = 132 LIMIT 10, 1), 1, 1, NOW(), 1, NOW(), 1),
('6021900000', 'CWT 5% - WI 100/WC 100', 'CWT 5% - WI 100/WC 100', 1, NULL, (SELECT EB_OBJECT_ID FROM EB_OBJECT WHERE OBJECT_TYPE_ID = 132 LIMIT 11, 1), 1, 1, NOW(), 1, NOW(), 1),
('6022000000', 'CWT 10% - WI 010/WC 010', 'CWT 10% - WI 010/WC 010', 1, NULL, (SELECT EB_OBJECT_ID FROM EB_OBJECT WHERE OBJECT_TYPE_ID = 132 LIMIT 12, 1), 1, 1, NOW(), 1, NOW(), 1),
('6022100000', 'CWT 15% - WI 011/WC 011', 'CWT 15% - WI 011/WC 011', 1, NULL, (SELECT EB_OBJECT_ID FROM EB_OBJECT WHERE OBJECT_TYPE_ID = 132 LIMIT 13, 1), 1, 1, NOW(), 1, NOW(), 1);

INSERT INTO ACCOUNT_COMBINATION (COMPANY_ID, ACCOUNT_ID, DIVISION_ID, ACTIVE, CREATED_BY, CREATED_DATE, UPDATED_BY, UPDATED_DATE, EB_SL_KEY_ID)
VALUES (1, (SELECT ACCOUNT_ID FROM ACCOUNT WHERE EB_OBJECT_ID = (SELECT EB_OBJECT_ID FROM EB_OBJECT WHERE OBJECT_TYPE_ID = 132 LIMIT 7, 1)), 1, 1, 1, NOW(), 1, NOW(), 1),
(1, (SELECT ACCOUNT_ID FROM ACCOUNT WHERE EB_OBJECT_ID = (SELECT EB_OBJECT_ID FROM EB_OBJECT WHERE OBJECT_TYPE_ID = 132 LIMIT 8, 1)), 1, 1, 1, NOW(), 1, NOW(), 1),
(1, (SELECT ACCOUNT_ID FROM ACCOUNT WHERE EB_OBJECT_ID = (SELECT EB_OBJECT_ID FROM EB_OBJECT WHERE OBJECT_TYPE_ID = 132 LIMIT 9, 1)), 1, 1, 1, NOW(), 1, NOW(), 1),
(1, (SELECT ACCOUNT_ID FROM ACCOUNT WHERE EB_OBJECT_ID = (SELECT EB_OBJECT_ID FROM EB_OBJECT WHERE OBJECT_TYPE_ID = 132 LIMIT 10, 1)), 1, 1, 1, NOW(), 1, NOW(), 1),
(1, (SELECT ACCOUNT_ID FROM ACCOUNT WHERE EB_OBJECT_ID = (SELECT EB_OBJECT_ID FROM EB_OBJECT WHERE OBJECT_TYPE_ID = 132 LIMIT 11, 1)), 1, 1, 1, NOW(), 1, NOW(), 1),
(1, (SELECT ACCOUNT_ID FROM ACCOUNT WHERE EB_OBJECT_ID = (SELECT EB_OBJECT_ID FROM EB_OBJECT WHERE OBJECT_TYPE_ID = 132 LIMIT 12, 1)), 1, 1, 1, NOW(), 1, NOW(), 1),
(1, (SELECT ACCOUNT_ID FROM ACCOUNT WHERE EB_OBJECT_ID = (SELECT EB_OBJECT_ID FROM EB_OBJECT WHERE OBJECT_TYPE_ID = 132 LIMIT 13, 1)), 1, 1, 1, NOW(), 1, NOW(), 1);

INSERT INTO WT_ACCOUNT_SETTING VALUES (8, 1, 'CWT 1% - WI 158 / WC 158', 1, (SELECT ACCOUNT_COMBINATION_ID FROM ACCOUNT_COMBINATION WHERE COMPANY_ID = 1 AND ACCOUNT_ID = (SELECT ACCOUNT_ID FROM ACCOUNT WHERE EB_OBJECT_ID = (SELECT EB_OBJECT_ID FROM EB_OBJECT WHERE OBJECT_TYPE_ID = 132 LIMIT 7, 1))), 1, 1, 1),
(9, 1, 'CWT 1% - WI 630 / WC 630', 1, (SELECT ACCOUNT_COMBINATION_ID FROM ACCOUNT_COMBINATION WHERE COMPANY_ID = 1 AND ACCOUNT_ID = (SELECT ACCOUNT_ID FROM ACCOUNT WHERE EB_OBJECT_ID = (SELECT EB_OBJECT_ID FROM EB_OBJECT WHERE OBJECT_TYPE_ID = 132 LIMIT 8, 1))), 1, 2, 1),
(10, 1, 'CWT 2% - WI 120 / WC 120', 2, (SELECT ACCOUNT_COMBINATION_ID FROM ACCOUNT_COMBINATION WHERE COMPANY_ID = 1 AND ACCOUNT_ID = (SELECT ACCOUNT_ID FROM ACCOUNT WHERE EB_OBJECT_ID = (SELECT EB_OBJECT_ID FROM EB_OBJECT WHERE OBJECT_TYPE_ID = 132 LIMIT 9, 1))), 1, 3, 1),
(11, 1, 'CWT 2% - WI 160 / WC 160', 2, (SELECT ACCOUNT_COMBINATION_ID FROM ACCOUNT_COMBINATION WHERE COMPANY_ID = 1 AND ACCOUNT_ID = (SELECT ACCOUNT_ID FROM ACCOUNT WHERE EB_OBJECT_ID = (SELECT EB_OBJECT_ID FROM EB_OBJECT WHERE OBJECT_TYPE_ID = 132 LIMIT 10, 1))), 1, 4, 1),
(12, 1, 'CWT 5% - WI 100 / WC 100', 5, (SELECT ACCOUNT_COMBINATION_ID FROM ACCOUNT_COMBINATION WHERE COMPANY_ID = 1 AND ACCOUNT_ID = (SELECT ACCOUNT_ID FROM ACCOUNT WHERE EB_OBJECT_ID = (SELECT EB_OBJECT_ID FROM EB_OBJECT WHERE OBJECT_TYPE_ID = 132 LIMIT 11, 1))), 1, 5, 1),
(13, 1, 'CWT 10% - WI 010 / WC 010', 10, (SELECT ACCOUNT_COMBINATION_ID FROM ACCOUNT_COMBINATION WHERE COMPANY_ID = 1 AND ACCOUNT_ID = (SELECT ACCOUNT_ID FROM ACCOUNT WHERE EB_OBJECT_ID = (SELECT EB_OBJECT_ID FROM EB_OBJECT WHERE OBJECT_TYPE_ID = 132 LIMIT 12, 1))), 1, 6, 1),
(14, 1, 'CWT 15% - WI 011 / WC 011', 15, (SELECT ACCOUNT_COMBINATION_ID FROM ACCOUNT_COMBINATION WHERE COMPANY_ID = 1 AND ACCOUNT_ID = (SELECT ACCOUNT_ID FROM ACCOUNT WHERE EB_OBJECT_ID = (SELECT EB_OBJECT_ID FROM EB_OBJECT WHERE OBJECT_TYPE_ID = 132 LIMIT 13, 1))), 1, 7, 1);