
-- Description: Insert script to convert SALES ORDER data to AR_TRANSACTION. 

INSERT INTO AR_TRANSACTION(FORM_WORKFLOW_ID, EB_OBJECT_ID, EB_SL_KEY_ID, SEQUENCE_NO, AR_TRANSACTION_TYPE_ID,
COMPANY_ID, CUSTOMER_ID, CUSTOMER_ACCOUNT_ID, TERM_ID, TRANSACTION_NUMBER, TRANSACTION_DATE, GL_DATE, DUE_DATE,
DESCRIPTION, AMOUNT, CREATED_BY, CREATED_DATE, UPDATED_BY, UPDATED_DATE)
SELECT FORM_WORKFLOW_ID, EB_OBJECT_ID, 1, SO_NUMBER, 15, COMPANY_ID, AR_CUSTOMER_ID, AR_CUSTOMER_ACCOUNT_ID,
TERM_ID, CONCAT('SO ', SO_NUMBER), DATE, DATE,DUE_DATE, DESCRIPTION, TOTAL, CREATED_BY, CREATED_DATE, 
UPDATED_BY, UPDATED_DATE
FROM SALES_ORDER;