
-- Description	: Consolidated script that will update withholding VAT accounts and implementation

DROP TABLE IF EXISTS AR_INVOICE_ACCOUNT;

CREATE TABLE AR_INVOICE_ACCOUNT (
	AR_INVOICE_ACCOUNT_ID int(10) unsigned NOT NULL AUTO_INCREMENT,
	COMPANY_ID int(10) unsigned NOT NULL,
	DIVISION_ID int(10) unsigned DEFAULT NULL,
	RETENTION_AC_ID int(10) unsigned NOT NULL,
	WT_VAT_GOODS_AC_ID int(10) unsigned NOT NULL,
	WT_VAT_SERVICE_AC_ID int(10) unsigned NOT NULL,
	DEFAULT_DISC_AC_ID int(10) unsigned NOT NULL,
	RECOUPMENT_AC_ID int(10) unsigned NOT NULL,
	ACTIVE tinyint(1) DEFAULT '1',
	CREATED_BY int(10) unsigned NOT NULL,
	CREATED_DATE timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
	UPDATED_BY int(10) unsigned NOT NULL,
	UPDATED_DATE timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
	PRIMARY KEY (AR_INVOICE_ACCOUNT_ID),
	KEY FK_ARIA_COMPANY_ID (COMPANY_ID),
	KEY FK_ARIA_DIVISION_ID (DIVISION_ID),
	KEY FK_ARIA_RETENTION_AC_ID (RETENTION_AC_ID),
	KEY FK_ARIA_WT_VAT_GOODS_AC_ID (WT_VAT_GOODS_AC_ID),
	KEY FK_ARIA_WT_VAT_SERVICE_AC_ID (WT_VAT_SERVICE_AC_ID),
	KEY FK_ARIA_DEFAULT_DISC_AC_ID (DEFAULT_DISC_AC_ID),
	KEY FK_ARIA_RECOUPMENT_AC_ID (RECOUPMENT_AC_ID),
	KEY FK_ARIA_CREATED_BY (CREATED_BY),
	KEY FK_ARIA_UPDATED_BY (UPDATED_BY),
	CONSTRAINT FK_ARIA_COMPANY_ID FOREIGN KEY (COMPANY_ID) REFERENCES COMPANY (COMPANY_ID),
	CONSTRAINT FK_ARIA_DIVISION_ID FOREIGN KEY (DIVISION_ID) REFERENCES DIVISION (DIVISION_ID),
	CONSTRAINT FK_ARIA_RETENTION_AC_ID FOREIGN KEY (RETENTION_AC_ID) REFERENCES ACCOUNT_COMBINATION (ACCOUNT_COMBINATION_ID),
	CONSTRAINT FK_ARIA_WT_VAT_GOODS_AC_ID FOREIGN KEY (WT_VAT_GOODS_AC_ID) REFERENCES ACCOUNT_COMBINATION (ACCOUNT_COMBINATION_ID),
	CONSTRAINT FK_ARIA_WT_VAT_SERVICE_AC_ID FOREIGN KEY (WT_VAT_SERVICE_AC_ID) REFERENCES ACCOUNT_COMBINATION (ACCOUNT_COMBINATION_ID),
	CONSTRAINT FK_ARIA_RECOUPMENT_AC_ID FOREIGN KEY (RECOUPMENT_AC_ID) REFERENCES ACCOUNT_COMBINATION (ACCOUNT_COMBINATION_ID),
	CONSTRAINT FK_ARIA_DEFAULT_DISC_AC_ID FOREIGN KEY (DEFAULT_DISC_AC_ID) REFERENCES ACCOUNT_COMBINATION (ACCOUNT_COMBINATION_ID),
	CONSTRAINT FK_ARIA_CREATED_BY FOREIGN KEY (CREATED_BY) REFERENCES USER (USER_ID),
	CONSTRAINT FK_ARIA_UPDATED_BY FOREIGN KEY (UPDATED_BY) REFERENCES USER (USER_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO ACCOUNT (NUMBER, ACCOUNT_NAME, DESCRIPTION, ACCOUNT_TYPE_ID, PARENT_ACCOUNT_ID, ACTIVE, CREATED_BY, CREATED_DATE, UPDATED_BY, UPDATED_DATE, EB_SL_KEY_ID) VALUES ('3001061001', 'WV010; 5%', 'WV010; 5%', (SELECT ACCOUNT_TYPE_ID FROM ACCOUNT_TYPE WHERE NAME='Current Assets'), NULL, 1, 1, NOW(), 1, NOW(), 1);

UPDATE ACCOUNT SET NUMBER='3001061002', ACCOUNT_NAME='WV020; 5%' WHERE ACCOUNT_ID = 337;

INSERT INTO ACCOUNT_COMBINATION (COMPANY_ID, ACCOUNT_ID, DIVISION_ID, ACTIVE, CREATED_BY, CREATED_DATE, UPDATED_BY, UPDATED_DATE)
SELECT 1, (SELECT ACCOUNT_ID FROM ACCOUNT WHERE NUMBER = '3001061001'), D.DIVISION_ID, 1, 1, NOW(), 1, NOW()
FROM DIVISION D WHERE D.DIVISION_ID IN (1, 2, 3, 4, 5, 6);

INSERT INTO AR_INVOICE_ACCOUNT (COMPANY_ID, DIVISION_ID, RETENTION_AC_ID, WT_VAT_GOODS_AC_ID, WT_VAT_SERVICE_AC_ID, DEFAULT_DISC_AC_ID, RECOUPMENT_AC_ID, ACTIVE, CREATED_BY, CREATED_DATE, UPDATED_BY, UPDATED_DATE)
VALUES (1, 1, (SELECT AC.ACCOUNT_COMBINATION_ID FROM ACCOUNT_COMBINATION AC WHERE AC.DIVISION_ID = 1 AND AC.ACCOUNT_ID = 336),
(SELECT AC.ACCOUNT_COMBINATION_ID FROM ACCOUNT_COMBINATION AC WHERE AC.DIVISION_ID = 1 AND AC.ACCOUNT_ID = (SELECT ACCOUNT_ID FROM ACCOUNT WHERE NUMBER = '3001061001')),
(SELECT AC.ACCOUNT_COMBINATION_ID FROM ACCOUNT_COMBINATION AC WHERE AC.DIVISION_ID = 1 AND AC.ACCOUNT_ID = 337),
(SELECT AC.ACCOUNT_COMBINATION_ID FROM ACCOUNT_COMBINATION AC WHERE AC.DIVISION_ID = 1 AND AC.ACCOUNT_ID = 341),
(SELECT AC.ACCOUNT_COMBINATION_ID FROM ACCOUNT_COMBINATION AC WHERE AC.DIVISION_ID = 1 AND AC.ACCOUNT_ID = 335), 1, 1, NOW(), 1, NOW()),
(1, 2, (SELECT AC.ACCOUNT_COMBINATION_ID FROM ACCOUNT_COMBINATION AC WHERE AC.DIVISION_ID = 2 AND AC.ACCOUNT_ID = 336),
(SELECT AC.ACCOUNT_COMBINATION_ID FROM ACCOUNT_COMBINATION AC WHERE AC.DIVISION_ID = 2 AND AC.ACCOUNT_ID = (SELECT ACCOUNT_ID FROM ACCOUNT WHERE NUMBER = '3001061001')),
(SELECT AC.ACCOUNT_COMBINATION_ID FROM ACCOUNT_COMBINATION AC WHERE AC.DIVISION_ID = 2 AND AC.ACCOUNT_ID = 337),
(SELECT AC.ACCOUNT_COMBINATION_ID FROM ACCOUNT_COMBINATION AC WHERE AC.DIVISION_ID = 2 AND AC.ACCOUNT_ID = 341),
(SELECT AC.ACCOUNT_COMBINATION_ID FROM ACCOUNT_COMBINATION AC WHERE AC.DIVISION_ID = 2 AND AC.ACCOUNT_ID = 335), 1, 1, NOW(), 1, NOW()),
(1, 3, (SELECT AC.ACCOUNT_COMBINATION_ID FROM ACCOUNT_COMBINATION AC WHERE AC.DIVISION_ID = 3 AND AC.ACCOUNT_ID = 336),
(SELECT AC.ACCOUNT_COMBINATION_ID FROM ACCOUNT_COMBINATION AC WHERE AC.DIVISION_ID = 3 AND AC.ACCOUNT_ID = (SELECT ACCOUNT_ID FROM ACCOUNT WHERE NUMBER = '3001061001')),
(SELECT AC.ACCOUNT_COMBINATION_ID FROM ACCOUNT_COMBINATION AC WHERE AC.DIVISION_ID = 3 AND AC.ACCOUNT_ID = 337),
(SELECT AC.ACCOUNT_COMBINATION_ID FROM ACCOUNT_COMBINATION AC WHERE AC.DIVISION_ID = 3 AND AC.ACCOUNT_ID = 341),
(SELECT AC.ACCOUNT_COMBINATION_ID FROM ACCOUNT_COMBINATION AC WHERE AC.DIVISION_ID = 3 AND AC.ACCOUNT_ID = 335), 1, 1, NOW(), 1, NOW()),
(1, 4, (SELECT AC.ACCOUNT_COMBINATION_ID FROM ACCOUNT_COMBINATION AC WHERE AC.DIVISION_ID = 4 AND AC.ACCOUNT_ID = 336),
(SELECT AC.ACCOUNT_COMBINATION_ID FROM ACCOUNT_COMBINATION AC WHERE AC.DIVISION_ID = 4 AND AC.ACCOUNT_ID = (SELECT ACCOUNT_ID FROM ACCOUNT WHERE NUMBER = '3001061001')),
(SELECT AC.ACCOUNT_COMBINATION_ID FROM ACCOUNT_COMBINATION AC WHERE AC.DIVISION_ID = 4 AND AC.ACCOUNT_ID = 337),
(SELECT AC.ACCOUNT_COMBINATION_ID FROM ACCOUNT_COMBINATION AC WHERE AC.DIVISION_ID = 4 AND AC.ACCOUNT_ID = 341),
(SELECT AC.ACCOUNT_COMBINATION_ID FROM ACCOUNT_COMBINATION AC WHERE AC.DIVISION_ID = 4 AND AC.ACCOUNT_ID = 335), 1, 1, NOW(), 1, NOW()),
(1, 5, (SELECT AC.ACCOUNT_COMBINATION_ID FROM ACCOUNT_COMBINATION AC WHERE AC.DIVISION_ID = 5 AND AC.ACCOUNT_ID = 336),
(SELECT AC.ACCOUNT_COMBINATION_ID FROM ACCOUNT_COMBINATION AC WHERE AC.DIVISION_ID = 5 AND AC.ACCOUNT_ID = (SELECT ACCOUNT_ID FROM ACCOUNT WHERE NUMBER = '3001061001')),
(SELECT AC.ACCOUNT_COMBINATION_ID FROM ACCOUNT_COMBINATION AC WHERE AC.DIVISION_ID = 5 AND AC.ACCOUNT_ID = 337),
(SELECT AC.ACCOUNT_COMBINATION_ID FROM ACCOUNT_COMBINATION AC WHERE AC.DIVISION_ID = 5 AND AC.ACCOUNT_ID = 341),
(SELECT AC.ACCOUNT_COMBINATION_ID FROM ACCOUNT_COMBINATION AC WHERE AC.DIVISION_ID = 5 AND AC.ACCOUNT_ID = 335), 1, 1, NOW(), 1, NOW()),
(1, 6, (SELECT AC.ACCOUNT_COMBINATION_ID FROM ACCOUNT_COMBINATION AC WHERE AC.DIVISION_ID = 6 AND AC.ACCOUNT_ID = 336),
(SELECT AC.ACCOUNT_COMBINATION_ID FROM ACCOUNT_COMBINATION AC WHERE AC.DIVISION_ID = 6 AND AC.ACCOUNT_ID = (SELECT ACCOUNT_ID FROM ACCOUNT WHERE NUMBER = '3001061001')),
(SELECT AC.ACCOUNT_COMBINATION_ID FROM ACCOUNT_COMBINATION AC WHERE AC.DIVISION_ID = 6 AND AC.ACCOUNT_ID = 337),
(SELECT AC.ACCOUNT_COMBINATION_ID FROM ACCOUNT_COMBINATION AC WHERE AC.DIVISION_ID = 6 AND AC.ACCOUNT_ID = 341),
(SELECT AC.ACCOUNT_COMBINATION_ID FROM ACCOUNT_COMBINATION AC WHERE AC.DIVISION_ID = 6 AND AC.ACCOUNT_ID = 335), 1, 1, NOW(), 1, NOW());