
-- Description: Drop AP_INVOICE_STATUS_ID column in AP_INVOICE table

ALTER TABLE AP_INVOICE
 DROP COLUMN AP_INVOICE_STATUS_ID,
 DROP FOREIGN KEY FK_AP_INVOICE_STATUS;

DROP TABLE AP_INVOICE_STATUS;
