
-- Description: Update script to add PROCESSING_REPORT_TYPE_ID in PROCESSING_REPORT table.

ALTER TABLE PROCESSING_REPORT ADD PROCESSING_REPORT_TYPE_ID int(10) unsigned DEFAULT 1 AFTER PROCESSING_REPORT_ID,
 ADD CONSTRAINT FK_MPR_PROCESSING_TYPE_ID FOREIGN KEY (PROCESSING_REPORT_TYPE_ID) REFERENCES PROCESSING_REPORT_TYPE (PROCESSING_REPORT_TYPE_ID);
 