
-- Description: Add EB_OJBECT_ID in R_TRANSFER_RECEIPT_ITEM table

ALTER TABLE R_TRANSFER_RECEIPT_ITEM ADD EB_OBJECT_ID int(10) unsigned DEFAULT NULL AFTER R_TRANSFER_RECEIPT_ID,
ADD CONSTRAINT RTRI_EB_OBJECT_ID FOREIGN KEY (EB_OBJECT_ID) REFERENCES EB_OBJECT (EB_OBJECT_ID);