
-- Description	: Add TAX_TYPE_ID in PURCHASE_ORDER_LINE table

ALTER TABLE PURCHASE_ORDER_LINE ADD COLUMN TAX_TYPE_ID INT(10) UNSIGNED DEFAULT NULL,
ADD CONSTRAINT FK_PO_LINE_TAX_TYPE_ID FOREIGN KEY (TAX_TYPE_ID) REFERENCES TAX_TYPE (TAX_TYPE_ID);

ALTER TABLE PURCHASE_ORDER_LINE ADD COLUMN VAT_AMOUNT DOUBLE DEFAULT 0;