
-- Description	: Update script that will add LOAN_CHARGE_TYPE_ID column to AP_LINE table

ALTER TABLE AP_LINE ADD COLUMN LOAN_CHARGE_TYPE_ID INT(10) UNSIGNED DEFAULT NULL,
ADD CONSTRAINT FK_AP_LINE_LOAN_CHARGE_TYPE_ID FOREIGN KEY (LOAN_CHARGE_TYPE_ID) REFERENCES LOAN_CHARGE_TYPE (LOAN_CHARGE_TYPE_ID);