
-- Description : Script to add ITEM_SRP column on DIVISION_ID table.

ALTER TABLE ITEM_SRP ADD DIVISION_ID INT(10) UNSIGNED DEFAULT NULL AFTER COMPANY_ID,
ADD CONSTRAINT FK_SRP_DIVISION FOREIGN KEY (DIVISION_ID) REFERENCES DIVISION (DIVISION_ID);