
-- Description	: Add TAX_TYPE_ID and VAT_AMOUNT in ACCOUNT_SALE_ITEM table.

ALTER TABLE ACCOUNT_SALE_ITEM ADD COLUMN TAX_TYPE_ID INT(10) UNSIGNED DEFAULT NULL,
ADD CONSTRAINT FK_ACCOUNT_SALES_ITEM_TAX_TYPE_ID FOREIGN KEY (TAX_TYPE_ID) REFERENCES TAX_TYPE (TAX_TYPE_ID);

ALTER TABLE ACCOUNT_SALE_ITEM ADD COLUMN VAT_AMOUNT DOUBLE DEFAULT 0;