
-- Description: Add EB_OJBECT_ID in AR_CUSTOMER_ACCOUNT table

ALTER TABLE AR_CUSTOMER_ACCOUNT ADD EB_OBJECT_ID int(10) unsigned DEFAULT NULL AFTER TERM_ID,
ADD CONSTRAINT FK_AR_CUST_ACCT_EB_OBJECT_ID FOREIGN KEY (EB_OBJECT_ID) REFERENCES EB_OBJECT (EB_OBJECT_ID);

INSERT INTO OBJECT_TYPE VALUES (103, 'AR_CUSTOMER_ACCOUNT', 'AR_CUSTOMER_ACCOUNT', 'eulap.eb.service.ArCustomerAcctService', 1, 1, NOW(), 1, NOW());