
-- Description: Add CUSTOMER_TYPE_ID and PROJECT in AR_CUSTOMER table

ALTER TABLE AR_CUSTOMER ADD CUSTOMER_TYPE_ID int(10) unsigned DEFAULT NULL,
ADD CONSTRAINT FK_CUSTOMER_CUSTOMER_TYPE_ID FOREIGN KEY (CUSTOMER_TYPE_ID) REFERENCES CUSTOMER_TYPE (CUSTOMER_TYPE_ID);

ALTER TABLE AR_CUSTOMER ADD PROJECT tinyint(1) DEFAULT '0';