
-- Description: Drop AP_PAYMENT_STATUS_ID column in AP_PAYMENT table

ALTER TABLE AP_PAYMENT
 DROP COLUMN AP_PAYMENT_STATUS_ID,
 DROP FOREIGN KEY FK_AP_PAYMENT_PAYMENT_STATUS_ID;

DROP TABLE AP_PAYMENT_STATUS;