
-- Description: Add EB_OJBECT_ID in AP_INVOICE_LINE table

ALTER TABLE AP_INVOICE_LINE ADD COLUMN EB_OBJECT_ID int(10) unsigned DEFAULT NULL AFTER AP_INVOICE_ID,
ADD CONSTRAINT FK_AP_IL_EB_OBJECT_ID FOREIGN KEY (EB_OBJECT_ID) REFERENCES EB_OBJECT (EB_OBJECT_ID);