
-- Description: Add EB_OJBECT_ID in DIVISION table.

ALTER TABLE DIVISION ADD EB_OBJECT_ID int(10) unsigned DEFAULT NULL AFTER DIVISION_ID,
ADD CONSTRAINT FK_DIVISION_EB_OBJECT_ID FOREIGN KEY (EB_OBJECT_ID) REFERENCES EB_OBJECT (EB_OBJECT_ID);