
-- Description: Add CASH_SALE_TYPE_ID in CASH_SALE_RETURN table.

-- Default value is 1 (Retail Type)
ALTER TABLE CASH_SALE_RETURN ADD CASH_SALE_TYPE_ID int(10) unsigned DEFAULT 1 AFTER CASH_SALE_RETURN_ID,
 ADD CONSTRAINT FK_CSR_CS_TYPE_ID FOREIGN KEY (CASH_SALE_TYPE_ID)
 REFERENCES CASH_SALE_TYPE (CASH_SALE_TYPE_ID);
