
-- Description : Script to add columns on AR_TRANSACTION table.

ALTER TABLE AR_TRANSACTION ADD DIVISION_ID INT(10) UNSIGNED DEFAULT NULL AFTER COMPANY_ID,
ADD CONSTRAINT FK_AR_TRANSACTION_DIVISION_ID FOREIGN KEY (DIVISION_ID) REFERENCES DIVISION (DIVISION_ID);

ALTER TABLE AR_TRANSACTION ADD CURRENCY_ID INT(10) UNSIGNED DEFAULT NULL AFTER DESCRIPTION,
ADD CONSTRAINT FK_AR_TRANSACTION_CURRENCY_ID FOREIGN KEY (CURRENCY_ID) REFERENCES CURRENCY (CURRENCY_ID);

ALTER TABLE AR_TRANSACTION ADD CURRENCY_RATE_ID INT(10) UNSIGNED DEFAULT NULL AFTER CURRENCY_ID,
ADD CONSTRAINT FK_AR_TRANSACTION_CURRENCY_RATE_ID FOREIGN KEY (CURRENCY_RATE_ID) REFERENCES CURRENCY_RATE (CURRENCY_RATE_ID);

ALTER TABLE AR_TRANSACTION ADD CURRENCY_RATE_VALUE double DEFAULT 0 AFTER CURRENCY_RATE_ID;

ALTER TABLE AR_TRANSACTION ADD COLUMN WT_VAT_AMOUNT double DEFAULT 0 AFTER WT_AMOUNT;

ALTER TABLE AR_TRANSACTION ADD TRANSACTION_CLASSIFICATION_ID INT(10) UNSIGNED DEFAULT NULL,
ADD CONSTRAINT FK_AR_TRANSACTION_TRANSACTION_CLASSIFICATION_ID FOREIGN KEY (TRANSACTION_CLASSIFICATION_ID) REFERENCES TRANSACTION_CLASSIFICATION (TRANSACTION_CLASSIFICATION_ID);