
-- Description: Add STOCK_ADJUSTMENT_CLASSIFICATION_ID in STOCK_ADJUSTMENT table

ALTER TABLE STOCK_ADJUSTMENT ADD STOCK_ADJUSTMENT_CLASSIFICATION_ID int(10) unsigned DEFAULT NULL AFTER STOCK_ADJUSTMENT_ID,
ADD CONSTRAINT FK_SA_STOCK_ADJUSTMENT_CLASSIFICATION_ID FOREIGN KEY (STOCK_ADJUSTMENT_CLASSIFICATION_ID) 
REFERENCES STOCK_ADJUSTMENT_CLASSIFICATION (STOCK_ADJUSTMENT_CLASSIFICATION_ID);