
-- Description : Update script to add EB_OBJECT_ID on AR_MISCELLANEOUS_LINE Table.

ALTER TABLE AR_MISCELLANEOUS_LINE ADD EB_OBJECT_ID INT(10) unsigned DEFAULT NULL AFTER AR_MISCELLANEOUS_ID,
ADD CONSTRAINT FK_AR_MISCELLANEOUS_LINE_EB_OBJECT_ID FOREIGN KEY (EB_OBJECT_ID) REFERENCES EB_OBJECT (EB_OBJECT_ID);