
-- Description : Script to add PAYROLL_EMPLOYEE_TIMESHEET_ID column as foreign key on  EMPLOYEE_DTR table .

ALTER TABLE EMPLOYEE_DTR ADD COLUMN PAYROLL_EMPLOYEE_TIMESHEET_ID INT(10) UNSIGNED NULL AFTER LOCATION_ID,
ADD CONSTRAINT FK_EDRT_PAYROLL_EMPLOYEE_TIMESHEET_ID FOREIGN KEY (PAYROLL_EMPLOYEE_TIMESHEET_ID) REFERENCES PAYROLL_EMPLOYEE_TIMESHEET (PAYROLL_EMPLOYEE_TIMESHEET_ID);