
-- Description: Add EB_OJBECT_ID in AP_INVOICE table

ALTER TABLE AP_INVOICE ADD EB_OBJECT_ID int(10) unsigned DEFAULT NULL AFTER FORM_WORKFLOW_ID,
ADD CONSTRAINT FK_AP_INVOICE_EB_OBJECT_ID FOREIGN KEY (EB_OBJECT_ID) REFERENCES EB_OBJECT (EB_OBJECT_ID);