
-- Description: Add EB_OJBECT_ID in GENERAL_LEDGER and gl entry table

ALTER TABLE GENERAL_LEDGER ADD EB_OBJECT_ID int(10) unsigned DEFAULT NULL AFTER GENERAL_LEDGER_ID,
ADD CONSTRAINT FK_GENERAL_LEDGER_EB_OBJECT_ID FOREIGN KEY (EB_OBJECT_ID) REFERENCES EB_OBJECT (EB_OBJECT_ID);

ALTER TABLE GL_ENTRY ADD EB_OBJECT_ID int(10) unsigned DEFAULT NULL AFTER GL_ENTRY_ID,
ADD CONSTRAINT FK_GL_ENTRY_EB_OBJECT_ID FOREIGN KEY (EB_OBJECT_ID) REFERENCES EB_OBJECT (EB_OBJECT_ID);