
-- Description: Add TRANSFER_RECEIPT_TYPE_ID in R_TRANSFER_RECEIPT table

ALTER TABLE R_TRANSFER_RECEIPT ADD TRANSFER_RECEIPT_TYPE_ID int(10) unsigned DEFAULT NULL AFTER WAREHOUSE_FROM_ID,
ADD CONSTRAINT FK_RTR_TRANSFER_RECEIPT_TYPE_ID FOREIGN KEY (TRANSFER_RECEIPT_TYPE_ID) REFERENCES TRANSFER_RECEIPT_TYPE (TRANSFER_RECEIPT_TYPE_ID);