
-- Description	: Add BANK_ID and ACCOUNT_NUMBER in BANK_ACCOUNT table

ALTER TABLE BANK_ACCOUNT ADD COLUMN BANK_ID INT(10) UNSIGNED DEFAULT NULL;

ALTER TABLE BANK_ACCOUNT ADD COLUMN ACCOUNT_NUMBER VARCHAR(50) DEFAULT NULL;