
-- Description: Add EB_OJBECT_ID in R_RECEIVING_REPORT_RM_ITEM table

ALTER TABLE R_RECEIVING_REPORT_RM_ITEM ADD COLUMN EB_OBJECT_ID int(10) unsigned DEFAULT NULL AFTER R_RECEIVING_REPORT_ITEM_ID,
 ADD CONSTRAINT FK_RMI_EB_OBJECT_ID FOREIGN KEY (EB_OBJECT_ID) REFERENCES EB_OBJECT (EB_OBJECT_ID);