
-- Description	: Add TAX_TYPE_ID in R_RETURN_TO_SUPPLIER_ITEM table

ALTER TABLE R_RETURN_TO_SUPPLIER_ITEM ADD COLUMN TAX_TYPE_ID INT(10) UNSIGNED DEFAULT NULL,
ADD CONSTRAINT FK_RRTSI_TAX_TYPE_ID FOREIGN KEY (TAX_TYPE_ID) REFERENCES TAX_TYPE (TAX_TYPE_ID);

ALTER TABLE R_RETURN_TO_SUPPLIER_ITEM ADD COLUMN VAT_AMOUNT DOUBLE DEFAULT 0;