
-- Description: Add EB_OJBECT_ID in AR_TRANSACTION table

ALTER TABLE AR_TRANSACTION ADD EB_OBJECT_ID int(10) unsigned DEFAULT NULL AFTER FORM_WORKFLOW_ID,
ADD CONSTRAINT FK_AR_TRANSACTION_EB_OBJECT_ID FOREIGN KEY (EB_OBJECT_ID) REFERENCES EB_OBJECT (EB_OBJECT_ID);