
-- Description: Add EB_OJBECT_ID in R_TRANSFER_RECEIPT table

ALTER TABLE R_TRANSFER_RECEIPT ADD EB_OBJECT_ID int(10) unsigned DEFAULT NULL AFTER FORM_WORKFLOW_ID,
ADD CONSTRAINT FK_RTR_EB_OBJECT_ID FOREIGN KEY (EB_OBJECT_ID) REFERENCES EB_OBJECT (EB_OBJECT_ID);