
-- Description: Add EB_OJBECT_ID in AR_LINE table

ALTER TABLE AR_LINE ADD EB_OBJECT_ID int(10) unsigned DEFAULT NULL AFTER AR_LINE_SETUP_ID,
ADD CONSTRAINT FK_AR_LINE_EB_OBJECT_ID FOREIGN KEY (EB_OBJECT_ID) REFERENCES EB_OBJECT (EB_OBJECT_ID);