
-- Description: Add Column EMPLOYEE_SHIFT_ID.

ALTER TABLE EMPLOYEE_PROFILE ADD COLUMN EMPLOYEE_SHIFT_ID INT(10) UNSIGNED AFTER EB_OBJECT_ID;
ALTER TABLE EMPLOYEE_PROFILE
ADD CONSTRAINT FK_EMPLOYEE_PROFILE_EMPLOYEE_SHIFT_ID FOREIGN KEY (EMPLOYEE_SHIFT_ID) 
REFERENCES EMPLOYEE_SHIFT (EMPLOYEE_SHIFT_ID);