
-- Description: Add EB_OJBECT_ID in STOCK_ADJUSTMENT table

ALTER TABLE STOCK_ADJUSTMENT ADD EB_OBJECT_ID int(10) unsigned DEFAULT NULL AFTER FORM_WORKFLOW_ID,
ADD CONSTRAINT FK_SA_EB_OBJECT_ID FOREIGN KEY (EB_OBJECT_ID) REFERENCES EB_OBJECT (EB_OBJECT_ID);