
-- Description: Add EB_OJBECT_ID in Account table

ALTER TABLE ACCOUNT ADD EB_OBJECT_ID int(10) unsigned DEFAULT NULL AFTER RELATED_ACCOUNT_ID,
ADD CONSTRAINT FK_ACCOUNT_EB_OBJECT_ID FOREIGN KEY (EB_OBJECT_ID) REFERENCES EB_OBJECT (EB_OBJECT_ID);

INSERT INTO OBJECT_TYPE VALUES (100, 'ACCOUNT', 'ACCOUNT', 'eulap.eb.service.AccountService', 1, 1, NOW(), 1, NOW());