
-- Description: Updated CHECKBOOK_TEMPLATE rename the METRO BANK - LONG to METRO BANK PERSONAL - LONG

UPDATE CHECKBOOK_TEMPLATE SET NAME='METRO BANK PERSONAL - LONG' WHERE CHECKBOOK_TEMPLATE_ID = 14;