
-- Description	: Add TAX_TYPE_ID in CAP_DELIVERY_AR_LINE table

ALTER TABLE CAP_DELIVERY_AR_LINE ADD COLUMN TAX_TYPE_ID INT(10) UNSIGNED DEFAULT NULL,
ADD CONSTRAINT FK_CAP_DELIVERY_AR_LINE_TAX_TYPE_ID FOREIGN KEY (TAX_TYPE_ID) REFERENCES TAX_TYPE (TAX_TYPE_ID);

ALTER TABLE CAP_DELIVERY_AR_LINE ADD COLUMN VAT_AMOUNT DOUBLE DEFAULT 0;