
-- Description : Script to add DELIVERY_RECEIPT_LINE column on PERCENTILE table.

ALTER TABLE DELIVERY_RECEIPT_LINE ADD DESCRIPTION TEXT;
ALTER TABLE DELIVERY_RECEIPT_LINE ADD PERCENTILE DOUBLE DEFAULT '0';
ALTER TABLE DELIVERY_RECEIPT_LINE ADD COLUMN SERVICE_SETTING_ID INT(10) UNSIGNED DEFAULT NULL,
ADD CONSTRAINT FK_DRL_SERVICE_SETTING_ID FOREIGN KEY (SERVICE_SETTING_ID) REFERENCES SERVICE_SETTING (SERVICE_SETTING_ID);