
-- Description: Add EB_OJBECT_ID in WAREHOUSE table

ALTER TABLE WAREHOUSE ADD EB_OBJECT_ID int(10) unsigned DEFAULT NULL AFTER COMPANY_ID,
ADD CONSTRAINT FK_WAREHOUSE_EB_OBJECT_ID FOREIGN KEY (EB_OBJECT_ID) REFERENCES EB_OBJECT (EB_OBJECT_ID);

INSERT INTO OBJECT_TYPE VALUES (98, 'WAREHOUSE', 'WAREHOUSE', 'eulap.eb.service.WarehouseService', 1, 1, NOW(), 1, NOW());