
-- Description: Add REF_CASH_SALE_RETURN_ITEM_ID in CASH_SALE_RETURN_ITEM tables.

ALTER TABLE CASH_SALE_RETURN_ITEM ADD REF_CASH_SALE_RETURN_ITEM_ID int(10) unsigned DEFAULT NULL AFTER CASH_SALE_ITEM_ID,
ADD CONSTRAINT FK_CSRI_REF_CASH_SALE_RETURN_ITEM_ID FOREIGN KEY (REF_CASH_SALE_RETURN_ITEM_ID)
REFERENCES CASH_SALE_RETURN_ITEM (CASH_SALE_RETURN_ITEM_ID);