
-- Description : Script to add EB_OBJECT_ID column on AC_AR_LINE table.

ALTER TABLE AC_AR_LINE ADD EB_OBJECT_ID INT(10) UNSIGNED DEFAULT NULL AFTER AC_AR_LINE_ID,
ADD CONSTRAINT FK_AC_AR_LINE_EB_OBJECT_ID FOREIGN KEY (EB_OBJECT_ID) REFERENCES EB_OBJECT (EB_OBJECT_ID);