
-- Description: Add EB_OJBECT_ID in PAYROLL_EMPLOYEE_SALARY table

ALTER TABLE PAYROLL_EMPLOYEE_SALARY ADD EB_OBJECT_ID int(10) unsigned DEFAULT NULL AFTER EMPLOYEE_ID,
ADD CONSTRAINT FK_PES_EB_OBJECT_ID FOREIGN KEY (EB_OBJECT_ID) REFERENCES EB_OBJECT (EB_OBJECT_ID);
