
-- Description	: SQL script that will add REPACKING_TYPE_ID to repacking table table

ALTER TABLE REPACKING ADD REPACKING_TYPE_ID int(10) unsigned DEFAULT NULL,
ADD CONSTRAINT FK_RP_TYPE_ID FOREIGN KEY (REPACKING_TYPE_ID) REFERENCES REPACKING_TYPE (REPACKING_TYPE_ID);