
-- Description: Drop FK_CAPD_CUSTOMER_ADVANCE_PAYMENT_ID and modify CUSTOMER_ADVANCE_PAYMENT_ID to save NULL.

ALTER TABLE CAP_DELIVERY
DROP FOREIGN KEY FK_CAPD_CUSTOMER_ADVANCE_PAYMENT_ID;

ALTER TABLE CAP_DELIVERY
MODIFY CUSTOMER_ADVANCE_PAYMENT_ID int(10) unsigned DEFAULT NULL;