
-- Description: Update scripts to set UNIT_COST column to NOT NULL


ALTER TABLE CASH_SALE_ITEM MODIFY UNIT_COST double NOT NULL DEFAULT 0;
ALTER TABLE CASH_SALE_RETURN_ITEM MODIFY UNIT_COST double NOT NULL DEFAULT 0;
ALTER TABLE ACCOUNT_SALE_ITEM MODIFY UNIT_COST double NOT NULL DEFAULT 0;
ALTER TABLE R_TRANSFER_RECEIPT_ITEM MODIFY UNIT_COST double NOT NULL DEFAULT 0;
ALTER TABLE R_RETURN_TO_SUPPLIER_ITEM MODIFY UNIT_COST double NOT NULL DEFAULT 0;
ALTER TABLE REPACKING_ITEM MODIFY UNIT_COST double NOT NULL DEFAULT 0;
ALTER TABLE REPACKING_ITEM MODIFY REPACKED_UNIT_COST double NOT NULL DEFAULT 0;
