
-- Description: Change the Foreign Key to Ar Transaction Id.

ALTER TABLE WIP_SPECIAL_ORDER 
DROP FOREIGN KEY FK_WIP_SO_SALE_ORDER_ID,
CHANGE SALES_ORDER_ID AR_TRANSACTION_ID INT(10) UNSIGNED NOT NULL,
ADD CONSTRAINT FK_WIP_AR_TRANSACTION_ID FOREIGN KEY (AR_TRANSACTION_ID)
REFERENCES AR_TRANSACTION (AR_TRANSACTION_ID);