
-- Description	: Add TAX_TYPE_ID in R_PURCHASE_ORDER_ITEM table

ALTER TABLE R_PURCHASE_ORDER_ITEM ADD COLUMN TAX_TYPE_ID INT(10) UNSIGNED DEFAULT NULL,
ADD CONSTRAINT FK_RPOI_TAX_TYPE_ID FOREIGN KEY (TAX_TYPE_ID) REFERENCES TAX_TYPE (TAX_TYPE_ID);

ALTER TABLE R_PURCHASE_ORDER_ITEM ADD COLUMN VAT_AMOUNT DOUBLE DEFAULT 0;