
-- Description: Add EB_OJBECT_ID in AP_PAYMENT table

ALTER TABLE AP_PAYMENT ADD EB_OBJECT_ID int(10) unsigned DEFAULT NULL AFTER AP_PAYMENT_ID,
ADD CONSTRAINT FK_AP_PAYMENT_EB_OBJECT_ID FOREIGN KEY (EB_OBJECT_ID) REFERENCES EB_OBJECT (EB_OBJECT_ID);