
-- Description	: Add WT_ACCOUNT_SETTING_ID and WT_AMOUNT in CUSTOMER_ADVANCE_PAYMENT table

ALTER TABLE CUSTOMER_ADVANCE_PAYMENT ADD COLUMN WT_ACCOUNT_SETTING_ID INT(10) UNSIGNED DEFAULT NULL,
ADD CONSTRAINT FK_CUSTOMER_ADVANCE_PAYMENT_WT_ACCOUNT_SETTING_ID FOREIGN KEY (WT_ACCOUNT_SETTING_ID)
REFERENCES WT_ACCOUNT_SETTING (WT_ACCOUNT_SETTING_ID);

ALTER TABLE CUSTOMER_ADVANCE_PAYMENT ADD COLUMN WT_AMOUNT DOUBLE DEFAULT 0;