
-- Description: Add EB_OJBECT_ID in COMPANY table and insert company object type to OBJECT_TYPE table.

ALTER TABLE COMPANY ADD EB_OBJECT_ID int(10) unsigned DEFAULT NULL AFTER COMPANY_ID,
ADD CONSTRAINT FK_COMPANY_EB_OBJECT_ID FOREIGN KEY (EB_OBJECT_ID) REFERENCES EB_OBJECT (EB_OBJECT_ID);
