
-- Description : Script to add PAYMENT_TYPE_ID column in AP_PAYMENT table.

ALTER TABLE AP_PAYMENT ADD COLUMN PAYMENT_TYPE_ID INT(10) UNSIGNED DEFAULT NULL,
ADD CONSTRAINT FK_PAYMENT_TYPE_ID FOREIGN KEY (PAYMENT_TYPE_ID) REFERENCES PAYMENT_TYPE (PAYMENT_TYPE_ID);