
-- Description: Add EB_OJBECT_ID in AP_LINE table

ALTER TABLE AP_LINE ADD EB_OBJECT_ID int(10) unsigned DEFAULT NULL AFTER ACCOUNT_COMBINATION_ID,
ADD CONSTRAINT FK_AP_LINE_EB_OBJECT_ID FOREIGN KEY (EB_OBJECT_ID) REFERENCES EB_OBJECT (EB_OBJECT_ID);
