
-- Description : Script to add columns on SALES_ORDER table.

ALTER TABLE SALES_ORDER ADD DIVISION_ID INT(10) unsigned NOT NULL AFTER COMPANY_ID,
ADD CONSTRAINT FK_SO_DIVISION_ID FOREIGN KEY (DIVISION_ID) REFERENCES DIVISION (DIVISION_ID);

ALTER TABLE SALES_ORDER ADD DELIVERY_DATE date DEFAULT NULL AFTER DATE;

ALTER TABLE SALES_ORDER ADD SO_TYPE_ID INT(10) unsigned NOT NULL AFTER DELIVERY_DATE,
ADD CONSTRAINT FK_SO_SO_TYPE_ID FOREIGN KEY (SO_TYPE_ID) REFERENCES SO_TYPE (SO_TYPE_ID);

ALTER TABLE SALES_ORDER ADD PO_NUMBER varchar(50) DEFAULT NULL AFTER SO_TYPE_ID;

ALTER TABLE SALES_ORDER ADD TERM_ID INT(10) unsigned NOT NULL AFTER AR_CUSTOMER_ACCOUNT_ID,
ADD CONSTRAINT FK_SO_TERM_ID FOREIGN KEY (TERM_ID) REFERENCES TERM (TERM_ID);

ALTER TABLE SALES_ORDER ADD REMARKS text AFTER SHIP_TO;

ALTER TABLE SALES_ORDER ADD CURRENCY_ID INT(10) unsigned NOT NULL AFTER REMARKS,
ADD CONSTRAINT FK_SO_CURRENCY_ID FOREIGN KEY (CURRENCY_ID) REFERENCES CURRENCY (CURRENCY_ID);

ALTER TABLE SALES_ORDER ADD CURRENCY_RATE_ID INT(10) unsigned DEFAULT NULL AFTER CURRENCY_ID,
ADD CONSTRAINT FK_SO_CURRENCY_RATE_ID FOREIGN KEY (CURRENCY_RATE_ID) REFERENCES CURRENCY_RATE (CURRENCY_RATE_ID);

ALTER TABLE SALES_ORDER ADD CURRENCY_RATE_VALUE double DEFAULT 0 AFTER CURRENCY_RATE_ID;