
-- Description: Add EB_OJBECT_ID in ACCOUNT_SALE_ITEM table

ALTER TABLE ACCOUNT_SALE_ITEM ADD EB_OBJECT_ID int(10) unsigned DEFAULT NULL AFTER AR_TRANSACTION_ID,
ADD CONSTRAINT FK_ACCOUNT_SALES_ITEM_EB_OBJECT_ID FOREIGN KEY (EB_OBJECT_ID) REFERENCES EB_OBJECT (EB_OBJECT_ID);