
-- Description: Add EB_OJBECT_ID in STOCK_ADJUSTMENT_ITEM table

ALTER TABLE STOCK_ADJUSTMENT_ITEM ADD EB_OBJECT_ID int(10) unsigned DEFAULT NULL AFTER STOCK_ADJUSTMENT_ID,
ADD CONSTRAINT SAI_EB_OBJECT_ID FOREIGN KEY (EB_OBJECT_ID) REFERENCES EB_OBJECT (EB_OBJECT_ID);