
-- Description: Add EB_OJBECT_ID in Ar Customer table

ALTER TABLE AR_CUSTOMER ADD EB_OBJECT_ID int(10) unsigned DEFAULT NULL AFTER MAX_AMOUNT,
ADD CONSTRAINT FK_CUSTOMER_EB_OBJECT_ID FOREIGN KEY (EB_OBJECT_ID) REFERENCES EB_OBJECT (EB_OBJECT_ID);

INSERT INTO OBJECT_TYPE VALUES (99, 'AR_CUSTOMER', 'AR_CUSTOMER', 'eulap.eb.service.ArCustomerService', 1, 1, NOW(), 1, NOW());