
-- Description : Script to add EB_OBJECT_ID column on ACCOUNT_SALES_PO_ITEM table.

ALTER TABLE ACCOUNT_SALES_PO_ITEM ADD WAREHOUSE_ID INT(10) UNSIGNED DEFAULT NULL AFTER EB_OBJECT_ID,
ADD CONSTRAINT FK_ASPOI_WAREHOUSE_ID FOREIGN KEY (WAREHOUSE_ID) REFERENCES WAREHOUSE (WAREHOUSE_ID);