
-- Description : Script to add columns on STOCK_ADJUSTMENT table.

ALTER TABLE STOCK_ADJUSTMENT ADD DIVISION_ID INT(10) unsigned DEFAULT NULL AFTER COMPANY_ID,
ADD CONSTRAINT FK_STOCK_ADJUSTMENT_DIVISION_ID FOREIGN KEY (DIVISION_ID) REFERENCES DIVISION (DIVISION_ID);

ALTER TABLE STOCK_ADJUSTMENT ADD BMS_NUMBER varchar(50) DEFAULT NULL;

ALTER TABLE STOCK_ADJUSTMENT ADD CURRENCY_ID INT(10) unsigned DEFAULT NULL,
ADD CONSTRAINT FK_STOCK_ADJUSTMENT_CURRENCY_ID FOREIGN KEY (CURRENCY_ID) REFERENCES CURRENCY (CURRENCY_ID);

ALTER TABLE STOCK_ADJUSTMENT ADD CURRENCY_RATE_ID INT(10) unsigned DEFAULT NULL AFTER CURRENCY_ID,
ADD CONSTRAINT FK_STOCK_ADJUSTMENT_CURRENCY_RATE_ID FOREIGN KEY (CURRENCY_RATE_ID) REFERENCES CURRENCY_RATE (CURRENCY_RATE_ID);

ALTER TABLE STOCK_ADJUSTMENT ADD CURRENCY_RATE_VALUE double DEFAULT 0 AFTER CURRENCY_RATE_ID;