
-- Description	: Add PO_NUMBER in STOCK_ADJUSTMENT_ITEM & SERIAL_ITEM table

ALTER TABLE STOCK_ADJUSTMENT_ITEM ADD COLUMN PO_NUMBER varchar(20) DEFAULT NULL;

ALTER TABLE SERIAL_ITEM ADD COLUMN PO_NUMBER varchar(20) DEFAULT NULL;