
-- Description	: SQL script that will update DELIVERY_RECEIPT_NO max characters in R_RECEIVING_REPORT table

ALTER TABLE R_RECEIVING_REPORT MODIFY COLUMN DELIVERY_RECEIPT_NO VARCHAR(100) DEFAULT NULL;