
-- Description	: Add TAX_TYPE_ID and VAT_AMOUNT in AC_AR_LINE table

ALTER TABLE AC_AR_LINE ADD COLUMN TAX_TYPE_ID INT(10) UNSIGNED DEFAULT NULL,
ADD CONSTRAINT FK_AC_AL_TAX_TYPE_ID FOREIGN KEY (TAX_TYPE_ID) REFERENCES TAX_TYPE (TAX_TYPE_ID);

ALTER TABLE AC_AR_LINE ADD COLUMN VAT_AMOUNT DOUBLE DEFAULT 0;