
-- Description: Add EB_OJBECT_ID in AP_PAYMENT_INVOICE table

ALTER TABLE AP_PAYMENT_INVOICE ADD EB_OBJECT_ID int(10) unsigned DEFAULT NULL AFTER PAID_AMOUNT,
ADD CONSTRAINT FK_AP_PAYMENT_INVOICE_EB_OBJECT_ID FOREIGN KEY (EB_OBJECT_ID) REFERENCES EB_OBJECT (EB_OBJECT_ID);
