
-- Description: Add CUSTOMER_ADVANCE_PAYMENT_TYPE_ID in CUSTOMER_ADVANCE_PAYMENT table.

-- Default value is 1 (Retail Type)
ALTER TABLE CUSTOMER_ADVANCE_PAYMENT ADD CUSTOMER_ADVANCE_PAYMENT_TYPE_ID int(10) unsigned 
DEFAULT 1 AFTER CUSTOMER_ADVANCE_PAYMENT_ID, 
ADD CONSTRAINT FK_CUSTOMER_ADVANCE_PAYMENT_CAP_TYPE_ID 
FOREIGN KEY (CUSTOMER_ADVANCE_PAYMENT_TYPE_ID) 
REFERENCES CUSTOMER_ADVANCE_PAYMENT_TYPE (CUSTOMER_ADVANCE_PAYMENT_TYPE_ID);
