
-- Description : Script to add withholding tax columns on DELIVERY_RECEIPT table.

ALTER TABLE DELIVERY_RECEIPT ADD WT_ACCOUNT_SETTING_ID INT(10) unsigned DEFAULT NULL,
ADD CONSTRAINT FK_DR_WT_ACCOUNT_SETTING_ID FOREIGN KEY (WT_ACCOUNT_SETTING_ID) REFERENCES WT_ACCOUNT_SETTING (WT_ACCOUNT_SETTING_ID);
ALTER TABLE DELIVERY_RECEIPT ADD WT_AMOUNT double DEFAULT '0';
ALTER TABLE DELIVERY_RECEIPT ADD WT_VAT_AMOUNT double DEFAULT '0';