
--	Description: Add EB_OJBECT_ID column for CASH_SALE_RETURN_AR_LINE table

ALTER TABLE CASH_SALE_RETURN_AR_LINE ADD COLUMN EB_OBJECT_ID INT(10) UNSIGNED DEFAULT NULL AFTER CASH_SALE_RETURN_AR_LINE_REF_ID,
ADD CONSTRAINT FK_CSR_AL_EB_OBJECT_ID FOREIGN KEY (EB_OBJECT_ID) REFERENCES EB_OBJECT (EB_OBJECT_ID);