
-- Description	: Update script that will add GROSS_AMOUT, TAX_TYPE_ID, and AP_LINE column to AP_LINE table

ALTER TABLE AP_LINE ADD COLUMN TAX_TYPE_ID INT(10) UNSIGNED DEFAULT NULL,
ADD CONSTRAINT FK_AP_LINE_TAX_TYPE_ID FOREIGN KEY (TAX_TYPE_ID) REFERENCES TAX_TYPE (TAX_TYPE_ID);

ALTER TABLE AP_LINE ADD COLUMN VAT_AMOUNT DOUBLE DEFAULT 0;

ALTER TABLE AP_LINE ADD COLUMN GROSS_AMOUNT DOUBLE DEFAULT 0;