
-- Description	: Update script to new column for PAYROLL_EMPLOYEE_SALARY table

ALTER TABLE PAYROLL_EMPLOYEE_SALARY ADD COLUMN ADJUSTMENT DOUBLE(12,2) DEFAULT NULL;
ALTER TABLE PAYROLL_EMPLOYEE_SALARY ADD COLUMN DAYS DOUBLE(12,2) DEFAULT NULL;
ALTER TABLE PAYROLL_EMPLOYEE_SALARY ADD COLUMN DAILY_SALARY DOUBLE(12,2) DEFAULT NULL;