
-- Description: Update script to add ITEM_ADD_ON_TYPE_ID in ITEM_ADD_ON table.

ALTER TABLE ITEM_ADD_ON ADD ITEM_ADD_ON_TYPE_ID int(10) unsigned DEFAULT 3 AFTER ITEM_ADD_ON_ID,
 ADD CONSTRAINT FK_AO_ADD_ON_TYPE_ID FOREIGN KEY (ITEM_ADD_ON_TYPE_ID) REFERENCES ITEM_ADD_ON_TYPE (ITEM_ADD_ON_TYPE_ID);