
-- Description: Add EB_OJBECT_ID in R_PURCHASE_ORDER_ITEM table

ALTER TABLE R_PURCHASE_ORDER_ITEM ADD EB_OBJECT_ID int(10) unsigned DEFAULT NULL AFTER QUANTITY,
ADD CONSTRAINT FK_RPOI_EB_OBJECT_ID FOREIGN KEY (EB_OBJECT_ID) REFERENCES EB_OBJECT (EB_OBJECT_ID);