
-- Description: Add EB_OJBECT_ID in USER table

ALTER TABLE USER ADD EB_OBJECT_ID int(10) unsigned DEFAULT NULL AFTER COMPANY_ID,
ADD CONSTRAINT FK_USER_EB_OBJECT_ID FOREIGN KEY (EB_OBJECT_ID) REFERENCES EB_OBJECT (EB_OBJECT_ID);
