
-- Description: Update script to add COMPANY_ID column in EMPLOYEE_DOCUMENT TABLE.

ALTER TABLE EMPLOYEE_DOCUMENT ADD COLUMN `COMPANY_ID` INT(10) UNSIGNED DEFAULT 1 AFTER SEQUENCE_NO,
ADD CONSTRAINT `FK_EMPLOYEE_DOCUMENT_COMPANY_ID` FOREIGN KEY (`COMPANY_ID`) REFERENCES `COMPANY` (`COMPANY_ID`);