
-- Description	: Add BARCODE, WAREHOUSE_ID, and ITEM_VAT_TYPE_ID in ITEM table

ALTER TABLE ITEM ADD BARCODE varchar(15) DEFAULT NULL;

ALTER TABLE ITEM ADD ITEM_VAT_TYPE_ID int(10) unsigned DEFAULT NULL,
ADD CONSTRAINT FK_ITEM_VAT_TYPE_ID FOREIGN KEY (ITEM_VAT_TYPE_ID) REFERENCES ITEM_VAT_TYPE (ITEM_VAT_TYPE_ID);