
-- Description	: Update fleet profile Add Column DRIVER_ID.

ALTER TABLE FLEET_PROFILE ADD COLUMN DRIVER_ID INT(10) UNSIGNED DEFAULT NULL AFTER DRIVER,
ADD CONSTRAINT FK_FLEET_PROFILE_DRIVER_ID FOREIGN KEY (DRIVER_ID)
REFERENCES DRIVER (DRIVER_ID);