
-- Description: Add EB_OJBECT_ID in Cash sale and cash sale item table

ALTER TABLE CASH_SALE_ITEM ADD EB_OBJECT_ID int(10) unsigned DEFAULT NULL AFTER CASH_SALE_ID,
ADD CONSTRAINT FK_CSI_EB_OBJECT_ID FOREIGN KEY (EB_OBJECT_ID) REFERENCES EB_OBJECT (EB_OBJECT_ID);

ALTER TABLE CASH_SALE ADD EB_OBJECT_ID int(10) unsigned DEFAULT NULL AFTER FORM_WORKFLOW_ID,
ADD CONSTRAINT FK_CASH_SALE_EB_OBJECT_ID FOREIGN KEY (EB_OBJECT_ID) REFERENCES EB_OBJECT (EB_OBJECT_ID);

ALTER TABLE CASH_SALE_AR_LINE ADD EB_OBJECT_ID int(10) unsigned DEFAULT NULL AFTER AR_LINE_SETUP_ID,
ADD CONSTRAINT FK_CS_AL_EB_OBJECT_ID FOREIGN KEY (EB_OBJECT_ID) REFERENCES EB_OBJECT (EB_OBJECT_ID);