
-- Description: Add CUSTOMER_ADVANCE_PAYMENT_TYPE_ID in CAP_DELIVERY table.

-- Default value is 1 (Retail Type)
ALTER TABLE CAP_DELIVERY ADD CUSTOMER_ADVANCE_PAYMENT_TYPE_ID int(10) unsigned 
DEFAULT 1 AFTER CUSTOMER_ADVANCE_PAYMENT_ID, 
ADD CONSTRAINT FK_CAPD_CAP_TYPE_ID 
FOREIGN KEY (CUSTOMER_ADVANCE_PAYMENT_TYPE_ID) 
REFERENCES CUSTOMER_ADVANCE_PAYMENT_TYPE (CUSTOMER_ADVANCE_PAYMENT_TYPE_ID);
