
-- Description: Add EB_OJBECT_ID in AR_MISCELLANEOUS table

ALTER TABLE AR_MISCELLANEOUS ADD EB_OBJECT_ID int(10) unsigned DEFAULT NULL AFTER AR_MISCELLANEOUS_ID,
ADD CONSTRAINT FK_AR_MISCELLANEOUS_EB_OBJECT_ID FOREIGN KEY (EB_OBJECT_ID) REFERENCES EB_OBJECT (EB_OBJECT_ID);