
-- Description	: Add ITEM_DISCOUNT_TYPE_ID in R_RETURN_TO_SUPPLIER_ITEM table

ALTER TABLE R_RETURN_TO_SUPPLIER_ITEM ADD COLUMN ITEM_DISCOUNT_TYPE_ID INT(10) UNSIGNED DEFAULT NULL,
ADD CONSTRAINT FK_RRTSI_ITEM_DISCOUNT_TYPE_ID FOREIGN KEY (ITEM_DISCOUNT_TYPE_ID) REFERENCES ITEM_DISCOUNT_TYPE (ITEM_DISCOUNT_TYPE_ID);

ALTER TABLE R_RETURN_TO_SUPPLIER_ITEM ADD COLUMN DISCOUNT_VALUE DOUBLE DEFAULT 0;

ALTER TABLE R_RETURN_TO_SUPPLIER_ITEM ADD COLUMN DISCOUNT DOUBLE DEFAULT 0;