
-- Description : Script to add DELIVERY_RECEIPT column on DIVISION_ID table.

ALTER TABLE DELIVERY_RECEIPT 
ADD DIVISION_ID INT(10) UNSIGNED DEFAULT NULL,
ADD CURRENCY_ID INT(10) UNSIGNED DEFAULT NULL,
ADD CURRENCY_RATE_ID INT(10) UNSIGNED DEFAULT NULL,
ADD SALES_PERSONNEL_ID INT(10) UNSIGNED DEFAULT NULL,
ADD CURRENCY_RATE_VALUE double DEFAULT 0,
ADD PO_NUMBER varchar(50) DEFAULT NULL,
ADD DR_REF_NUMBER varchar(50) DEFAULT NULL,
ADD CONSTRAINT FK_DR_DIVISION_ID FOREIGN KEY (DIVISION_ID) REFERENCES DIVISION (DIVISION_ID),
ADD CONSTRAINT FK_DR_CURRENCY_ID FOREIGN KEY (CURRENCY_ID) REFERENCES CURRENCY (CURRENCY_ID),
ADD CONSTRAINT FK_DR_CURRENCY_RATE_ID FOREIGN KEY (CURRENCY_RATE_ID) REFERENCES CURRENCY_RATE (CURRENCY_RATE_ID),
ADD CONSTRAINT FK_DR_SALES_PERSONNEL_ID FOREIGN KEY (SALES_PERSONNEL_ID) REFERENCES SALES_PERSONNEL (SALES_PERSONNEL_ID);
