
-- Description: Add EB_OJBECT_ID in R_RECEIVING_REPORT_ITEM table

ALTER TABLE R_RECEIVING_REPORT_ITEM ADD EB_OBJECT_ID int(10) unsigned DEFAULT NULL AFTER UNIT_COST,
ADD CONSTRAINT FK_RRRI_EB_OBJECT_ID FOREIGN KEY (EB_OBJECT_ID) REFERENCES EB_OBJECT (EB_OBJECT_ID);