
-- Description	: Add FILE_PATH column and update FILE column to default null

ALTER TABLE REFERENCE_DOCUMENT ADD COLUMN FILE_PATH VARCHAR(100) DEFAULT NULL;

ALTER TABLE REFERENCE_DOCUMENT MODIFY COLUMN FILE MEDIUMBLOB DEFAULT NULL;
