
-- Description: Add EB_OJBECT_ID in CAP_DELIVERY and related tables

-- Paid in Advance Delivery
ALTER TABLE CAP_DELIVERY ADD EB_OBJECT_ID int(10) unsigned DEFAULT NULL AFTER FORM_WORKFLOW_ID,
ADD CONSTRAINT FK_CAPD_EB_OBJECT_ID FOREIGN KEY (EB_OBJECT_ID) REFERENCES EB_OBJECT (EB_OBJECT_ID);

-- Items
ALTER TABLE CAP_DELIVERY_ITEM ADD EB_OBJECT_ID int(10) unsigned DEFAULT NULL AFTER CAP_DELIVERY_ID,
ADD CONSTRAINT FK_CAPDI_EB_OBJECT_ID FOREIGN KEY (EB_OBJECT_ID) REFERENCES EB_OBJECT (EB_OBJECT_ID);

-- Other Charges
ALTER TABLE CAP_DELIVERY_AR_LINE ADD EB_OBJECT_ID int(10) unsigned DEFAULT NULL AFTER CAP_DELIVERY_ID,
ADD CONSTRAINT FK_CAPD_AL_EB_OBJECT_ID FOREIGN KEY (EB_OBJECT_ID) REFERENCES EB_OBJECT (EB_OBJECT_ID);
