
-- Description: Add EB_OJBECT_ID in REPACKING table

ALTER TABLE REPACKING ADD EB_OBJECT_ID int(10) unsigned DEFAULT NULL AFTER FORM_WORKFLOW_ID,
ADD CONSTRAINT FK_RP_EB_OBJECT_ID FOREIGN KEY (EB_OBJECT_ID) REFERENCES EB_OBJECT (EB_OBJECT_ID);