
-- Description : Script to add column on DIVISION_ID table.

ALTER TABLE REPACKING ADD DIVISION_ID INT(10) unsigned DEFAULT NULL AFTER COMPANY_ID,
ADD CONSTRAINT FK_RP_DIVISION_ID FOREIGN KEY (DIVISION_ID) REFERENCES DIVISION (DIVISION_ID);