
-- Description	: Add TAX_TYPE_ID and VAT_AMOUNT in STOCK_ADJUSTMENT_ITEM table

ALTER TABLE STOCK_ADJUSTMENT_ITEM ADD COLUMN TAX_TYPE_ID INT(10) UNSIGNED DEFAULT NULL,
ADD CONSTRAINT SAI_TAX_TYPE_ID FOREIGN KEY (TAX_TYPE_ID) REFERENCES TAX_TYPE (TAX_TYPE_ID);

ALTER TABLE STOCK_ADJUSTMENT_ITEM ADD COLUMN VAT_AMOUNT DOUBLE DEFAULT 0;