
-- Description : Script to add columns on SUPPLIER table.

ALTER TABLE SUPPLIER ADD BUSINESS_CLASSIFICATION_ID INT(10) UNSIGNED DEFAULT NULL AFTER SUPPLIER_ID,
ADD CONSTRAINT FK_SUPPLIER_BUSINESS_CLASSIFICATION_ID FOREIGN KEY (BUSINESS_CLASSIFICATION_ID) REFERENCES BUSINESS_CLASSIFICATION (BUSINESS_CLASSIFICATION_ID);

ALTER TABLE SUPPLIER MODIFY ADDRESS varchar(150) DEFAULT NULL;
ALTER TABLE SUPPLIER
ADD FIRST_NAME varchar(50) DEFAULT NULL AFTER NAME,
ADD LAST_NAME varchar(50) DEFAULT NULL AFTER FIRST_NAME,
ADD MIDDLE_NAME varchar(50) DEFAULT NULL AFTER LAST_NAME,
ADD STREET_BRGY varchar(150) DEFAULT NULL AFTER ADDRESS,
ADD CITY_PROVINCE varchar(150) DEFAULT NULL AFTER STREET_BRGY;