
-- Description	: Update script to add new columns to GENERAL_LEDGER table

ALTER TABLE GENERAL_LEDGER ADD COLUMN CURRENCY_ID INT(10) UNSIGNED DEFAULT NULL,
ADD CONSTRAINT FK_GENERAL_LEDGER_CURRENCY_ID FOREIGN KEY (CURRENCY_ID) REFERENCES CURRENCY (CURRENCY_ID);

ALTER TABLE GENERAL_LEDGER ADD COLUMN CURRENCY_RATE_ID INT(10) UNSIGNED DEFAULT NULL,
ADD CONSTRAINT FK_GENERAL_LEDGER_PAYMENT_CURRENCY_RATE_ID FOREIGN KEY (CURRENCY_RATE_ID) REFERENCES CURRENCY_RATE (CURRENCY_RATE_ID);

ALTER TABLE GENERAL_LEDGER ADD COLUMN CURRENCY_RATE_VALUE DOUBLE DEFAULT '0';