
-- Description	: Create script for AR_INVOICE_ITEM

DROP TABLE IF EXISTS AR_INVOICE_ITEM;

CREATE TABLE AR_INVOICE_ITEM (
	AR_INVOICE_ITEM_ID int(10) unsigned NOT NULL AUTO_INCREMENT,
	AR_INVOICE_ID int(10) unsigned NOT NULL,
	EB_OBJECT_ID int(10) unsigned DEFAULT NULL,
	WAREHOUSE_ID int(10) unsigned NOT NULL,
	ITEM_ID int(10) unsigned NOT NULL,
	QUANTITY double NOT NULL,
	ITEM_SRP_ID int(10) unsigned DEFAULT NULL,
	SRP double DEFAULT '0',
	UNIT_COST double NOT NULL,
	DISCOUNT double DEFAULT 0,
	TAX_TYPE_ID int(10) unsigned DEFAULT NULL,
	VAT_AMOUNT double DEFAULT '0',
	AMOUNT double DEFAULT '0',
	ITEM_DISCOUNT_ID int(10) unsigned DEFAULT NULL,
	ITEM_ADD_ON_ID int(10) unsigned DEFAULT NULL,
	ITEM_DISCOUNT_TYPE_ID int(10) unsigned DEFAULT NULL,
	DISCOUNT_VALUE double DEFAULT '0',
	PRIMARY KEY (AR_INVOICE_ITEM_ID),
	KEY FK_ARII_AR_INVOICE_ID (AR_INVOICE_ID),
	KEY FK_ARII_EB_OBJECT_ID (EB_OBJECT_ID),
	KEY FK_ARII_WAREHOUSE_ID (WAREHOUSE_ID),
	KEY FK_ARII_ITEM_ID (ITEM_ID),
	KEY FK_ARII_ITEM_SRP_ID (ITEM_SRP_ID),
	KEY FK_ARII_TAX_TYPE_ID (TAX_TYPE_ID),
	KEY FK_ARII_ITEM_DISCOUNT_ID (ITEM_DISCOUNT_ID),
	KEY FK_ARII_ITEM_ADD_ON_ID (ITEM_ADD_ON_ID),
	KEY FK_ARII_ITEM_DISCOUNT_TYPE_ID (ITEM_DISCOUNT_TYPE_ID),
	CONSTRAINT FK_ARII_AR_INVOICE_ID FOREIGN KEY (AR_INVOICE_ID) REFERENCES AR_INVOICE (AR_INVOICE_ID),
	CONSTRAINT FK_ARII_EB_OBJECT_ID FOREIGN KEY (EB_OBJECT_ID) REFERENCES EB_OBJECT (EB_OBJECT_ID),
	CONSTRAINT FK_ARII_WAREHOUSE_ID FOREIGN KEY (WAREHOUSE_ID) REFERENCES WAREHOUSE (WAREHOUSE_ID),
	CONSTRAINT FK_ARII_ITEM_ID FOREIGN KEY (ITEM_ID) REFERENCES ITEM (ITEM_ID),
	CONSTRAINT FK_ARII_ITEM_SRP_ID FOREIGN KEY (ITEM_SRP_ID) REFERENCES ITEM_SRP (ITEM_SRP_ID),
	CONSTRAINT FK_ARII_TAX_TYPE_ID FOREIGN KEY (TAX_TYPE_ID) REFERENCES TAX_TYPE (TAX_TYPE_ID),
	CONSTRAINT FK_ARII_ITEM_DISCOUNT_ID FOREIGN KEY (ITEM_DISCOUNT_ID) REFERENCES ITEM_DISCOUNT (ITEM_DISCOUNT_ID),
	CONSTRAINT FK_ARII_ITEM_ADD_ON_ID FOREIGN KEY (ITEM_ADD_ON_ID) REFERENCES ITEM_ADD_ON (ITEM_ADD_ON_ID),
	CONSTRAINT FK_ARII_ITEM_DISCOUNT_TYPE_ID FOREIGN KEY (ITEM_DISCOUNT_TYPE_ID) REFERENCES ITEM_DISCOUNT_TYPE (ITEM_DISCOUNT_TYPE_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;