
-- Description	: Create script for AR_RECEIPT_ADVANCE_PAYMENT

DROP TABLE IF EXISTS AR_RECEIPT_ADVANCE_PAYMENT;

CREATE TABLE AR_RECEIPT_ADVANCE_PAYMENT (
	AR_RECEIPT_ADVANCE_PAYMENT_ID int(10) unsigned NOT NULL AUTO_INCREMENT,
	EB_OBJECT_ID int(10) unsigned DEFAULT NULL,
	AR_RECEIPT_ID int(10) unsigned NOT NULL,
	CUSTOMER_ADVANCE_PAYMENT_ID int(10) unsigned NOT NULL,
	PRIMARY KEY (AR_RECEIPT_ADVANCE_PAYMENT_ID),
	KEY FK_ARRAP_EB_OBJECT_ID (EB_OBJECT_ID),
	KEY FK_ARRAP_AR_RECEIPT_ID (AR_RECEIPT_ID),
	KEY FK_ARRAP_CAP_ID (CUSTOMER_ADVANCE_PAYMENT_ID),
	CONSTRAINT FK_ARRAP_EB_OBJECT_ID FOREIGN KEY (EB_OBJECT_ID) REFERENCES EB_OBJECT (EB_OBJECT_ID),
	CONSTRAINT FK_ARRAP_AR_RECEIPT_ID FOREIGN KEY (AR_RECEIPT_ID) REFERENCES AR_RECEIPT (AR_RECEIPT_ID),
	CONSTRAINT FK_ARRAP_CAP_ID FOREIGN KEY (CUSTOMER_ADVANCE_PAYMENT_ID) REFERENCES CUSTOMER_ADVANCE_PAYMENT (CUSTOMER_ADVANCE_PAYMENT_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;