
-- Description	: A create script that will create AUTHORITY_TO_WITHDRAW table

DROP TABLE IF EXISTS AUTHORITY_TO_WITHDRAW;

CREATE TABLE AUTHORITY_TO_WITHDRAW (
	AUTHORITY_TO_WITHDRAW_ID int(10) unsigned NOT NULL AUTO_INCREMENT,
	FORM_WORKFLOW_ID int(10) unsigned DEFAULT NULL,
	SEQUENCE_NO int(10) unsigned NOT NULL,
	EB_OBJECT_ID int(10) unsigned DEFAULT NULL,
	COMPANY_ID int(10) unsigned NOT NULL,
	SALES_ORDER_ID int(10) unsigned NOT NULL,
	AR_CUSTOMER_ID int(10) unsigned NOT NULL,
	AR_CUSTOMER_ACCOUNT_ID int(10) unsigned NOT NULL,
	REMARKS text,
	CREATED_BY int(10) unsigned NOT NULL,
	CREATED_DATE timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
	UPDATED_BY int(10) unsigned NOT NULL,
	UPDATED_DATE timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
	DATE date DEFAULT NULL,
	PRIMARY KEY (AUTHORITY_TO_WITHDRAW_ID),
	KEY FK_ATW_FORM_WORKFLOW_ID (FORM_WORKFLOW_ID),
	KEY FK_ATW_EB_OBJECT_ID (EB_OBJECT_ID),
	KEY FK_ATW_SALES_ORDER_ID (SALES_ORDER_ID),
	KEY FK_ATW_COMPANY_ID (COMPANY_ID),
	KEY FK_ATW_AR_CUSTOMER_ID (AR_CUSTOMER_ID),
	KEY FK_ATW_AR_CUSTOMER_ACCOUNT_ID (AR_CUSTOMER_ACCOUNT_ID),
	KEY FK_ATW_CREATED_BY (CREATED_BY),
	KEY FK_ATW_UPDATED_BY (UPDATED_BY),
	CONSTRAINT FK_ATW_FORM_WORKFLOW_ID FOREIGN KEY (FORM_WORKFLOW_ID) REFERENCES FORM_WORKFLOW (FORM_WORKFLOW_ID),
	CONSTRAINT FK_ATW_EB_OBJECT_ID FOREIGN KEY (EB_OBJECT_ID) REFERENCES EB_OBJECT (EB_OBJECT_ID),
	CONSTRAINT FK_ATW_SALES_ORDER_ID FOREIGN KEY (SALES_ORDER_ID) REFERENCES SALES_ORDER (SALES_ORDER_ID),
	CONSTRAINT FK_ATW_COMPANY_ID FOREIGN KEY (AR_CUSTOMER_ID) REFERENCES AR_CUSTOMER (AR_CUSTOMER_ID),
	CONSTRAINT FK_ATW_AR_CUSTOMER_ID FOREIGN KEY (COMPANY_ID) REFERENCES COMPANY (COMPANY_ID),
	CONSTRAINT FK_ATW_AR_CUSTOMER_ACCOUNT_ID FOREIGN KEY (AR_CUSTOMER_ACCOUNT_ID) REFERENCES AR_CUSTOMER_ACCOUNT (AR_CUSTOMER_ACCOUNT_ID),
	CONSTRAINT FK_ATW_CREATED_BY FOREIGN KEY (CREATED_BY) REFERENCES USER (USER_ID),
	CONSTRAINT FK_ATW_UPDATED_BY FOREIGN KEY (UPDATED_BY) REFERENCES USER (USER_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;