
-- Description	: A create script that will create AUTHORITY_TO_WITHDRAW_ITEM table

DROP TABLE IF EXISTS AUTHORITY_TO_WITHDRAW_ITEM;

CREATE TABLE AUTHORITY_TO_WITHDRAW_ITEM (
	AUTHORITY_TO_WITHDRAW_ITEM_ID int(10) unsigned NOT NULL AUTO_INCREMENT,
	AUTHORITY_TO_WITHDRAW_ID int(10) unsigned NOT NULL,
	EB_OBJECT_ID int(10) unsigned DEFAULT NULL,
	WAREHOUSE_ID int(10) unsigned NOT NULL,
	ITEM_ID int(10) unsigned NOT NULL,
	QUANTITY double DEFAULT 0,
	PRIMARY KEY (AUTHORITY_TO_WITHDRAW_ITEM_ID),
	KEY FK_ATWI_AUTHORITY_TO_WITHDRAW_ID (AUTHORITY_TO_WITHDRAW_ID),
	KEY FK_ATWI_EB_OBJECT_ID (EB_OBJECT_ID),
	KEY FK_ATWI_WAREHOUSE_ID (WAREHOUSE_ID),
	KEY FK_ATWI_ITEM_ID (ITEM_ID),
	CONSTRAINT FK_ATWI_AUTHORITY_TO_WITHDRAW_ID FOREIGN KEY (AUTHORITY_TO_WITHDRAW_ID) REFERENCES AUTHORITY_TO_WITHDRAW (AUTHORITY_TO_WITHDRAW_ID),
	CONSTRAINT FK_ATWI_EB_OBJECT_ID FOREIGN KEY (EB_OBJECT_ID) REFERENCES EB_OBJECT (EB_OBJECT_ID),
	CONSTRAINT FK_ATWI_WAREHOUSE_ID FOREIGN KEY (WAREHOUSE_ID) REFERENCES WAREHOUSE (WAREHOUSE_ID),
	CONSTRAINT FK_ATWI_ITEM_ID FOREIGN KEY (ITEM_ID) REFERENCES ITEM (ITEM_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;