
-- Description : Create sql script for CUSTODIAN_ACCOUNT_SUPPLIER.

DROP TABLE IF EXISTS CUSTODIAN_ACCOUNT_SUPPLIER;

CREATE TABLE CUSTODIAN_ACCOUNT_SUPPLIER (
  CUSTODIAN_ACCOUNT_SUPPLIER_ID int(10) unsigned NOT NULL AUTO_INCREMENT,
  CUSTODIAN_ACCOUNT_ID int(10) unsigned NOT NULL,
  SUPPLIER_ID int(10) unsigned NOT NULL,
  SUPPLIER_ACCOUNT_ID int(10) unsigned NOT NULL,
  CREATED_BY int(10) unsigned NOT NULL,
  CREATED_DATE timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  UPDATED_BY int(10) unsigned NOT NULL,
  UPDATED_DATE timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  PRIMARY KEY (CUSTODIAN_ACCOUNT_SUPPLIER_ID),
  KEY FK_CUSTODIAN_ACCOUNT_SUPPLIER_CUSTODIAN_ACCOUNT_ID (CUSTODIAN_ACCOUNT_ID),
  KEY FK_CUSTODIAN_ACCOUNT_SUPPLIER_SUPPLIER_ID (SUPPLIER_ID),
  KEY FK_CUSTODIAN_ACCOUNT_SUPPLIER_SUPPLIER_ACCOUNT_ID (SUPPLIER_ACCOUNT_ID),
  KEY FK_CUSTODIAN_ACCOUNT_SUPPLIER_CREATED_BY (CREATED_BY),
  KEY FK_CUSTODIAN_ACCOUNT_SUPPLIER_UPDATED_BY (UPDATED_BY),
  CONSTRAINT FK_CUSTODIAN_ACCOUNT_SUPPLIER_CUSTODIAN_ACCOUNT_ID FOREIGN KEY (CUSTODIAN_ACCOUNT_ID) REFERENCES CUSTODIAN_ACCOUNT (CUSTODIAN_ACCOUNT_ID),
  CONSTRAINT FK_CUSTODIAN_ACCOUNT_SUPPLIER_SUPPLIER_ID FOREIGN KEY (SUPPLIER_ID) REFERENCES SUPPLIER (SUPPLIER_ID),
  CONSTRAINT FK_CUSTODIAN_ACCOUNT_SUPPLIER_SUPPLIER_ACCOUNT_ID FOREIGN KEY (SUPPLIER_ACCOUNT_ID) REFERENCES SUPPLIER_ACCOUNT (SUPPLIER_ACCOUNT_ID),
  CONSTRAINT FK_CUSTODIAN_ACCOUNT_SUPPLIER_CREATED_BY FOREIGN KEY (CREATED_BY) REFERENCES USER (USER_ID),
  CONSTRAINT FK_CUSTODIAN_ACCOUNT_SUPPLIER_UPDATED_BY FOREIGN KEY (UPDATED_BY) REFERENCES USER (USER_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;