
-- Description	: A create script that will create DELIVERY_RECEIPT_LINE table

DROP TABLE IF EXISTS DELIVERY_RECEIPT_LINE;

CREATE TABLE DELIVERY_RECEIPT_LINE (
	DELIVERY_RECEIPT_LINE_ID int(10) unsigned NOT NULL AUTO_INCREMENT,
	DELIVERY_RECEIPT_ID int(10) unsigned NOT NULL,
	EB_OBJECT_ID int(10) unsigned DEFAULT NULL,
	SERVICE_SETTING_ID int(10) unsigned NOT NULL,
	DESCRIPTION TEXT,
	GROSS_AMOUNT double DEFAULT '0',
	DISCOUNT_TYPE_ID int(10) unsigned DEFAULT NULL,
	DISCOUNT_VALUE double DEFAULT '0',
	DISCOUNT double DEFAULT '0',
	TAX_TYPE_ID int(10) unsigned DEFAULT NULL,
	VAT_AMOUNT double DEFAULT '0',
	AMOUNT double DEFAULT '0',
	QUANTITY double DEFAULT '0',
	PERCENTILE double DEFAULT '0',
	UP_AMOUNT double DEFAULT '0',
	UNITOFMEASUREMENT_ID int(10) unsigned DEFAULT NULL,
	PRIMARY KEY (DELIVERY_RECEIPT_LINE_ID),
	KEY FK_DRL_DELIVERY_RECEIPT_ID (DELIVERY_RECEIPT_ID),
	KEY FK_DRL_EB_OBJECT_ID (EB_OBJECT_ID),
	KEY FK_DRL_SERVICE_SETTING_ID (SERVICE_SETTING_ID),
	KEY FK_DRL_DISCOUNT_TYPE_ID (DISCOUNT_TYPE_ID),
	KEY FK_DRL_TAX_TYPE_ID (TAX_TYPE_ID),
	CONSTRAINT FK_DRL_DELIVERY_RECEIPT_ID FOREIGN KEY (DELIVERY_RECEIPT_ID) REFERENCES DELIVERY_RECEIPT (DELIVERY_RECEIPT_ID),
	CONSTRAINT FK_DRL_EB_OBJECT_ID FOREIGN KEY (EB_OBJECT_ID) REFERENCES EB_OBJECT (EB_OBJECT_ID),
	CONSTRAINT FK_DRL_DISCOUNT_TYPE_ID FOREIGN KEY (DISCOUNT_TYPE_ID) REFERENCES ITEM_DISCOUNT_TYPE (ITEM_DISCOUNT_TYPE_ID),
	CONSTRAINT FK_DRL_SERVICE_SETTING_ID FOREIGN KEY (SERVICE_SETTING_ID) REFERENCES SERVICE_SETTING (SERVICE_SETTING_ID),
	CONSTRAINT FK_DRL_TAX_TYPE_ID FOREIGN KEY (TAX_TYPE_ID) REFERENCES TAX_TYPE (TAX_TYPE_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;