
-- Description	: Create script for DELIVERY_RECEIPT_ITEM

DROP TABLE IF EXISTS DELIVERY_RECEIPT_ITEM;

CREATE TABLE DELIVERY_RECEIPT_ITEM (
	DELIVERY_RECEIPT_ITEM_ID int(10) unsigned NOT NULL AUTO_INCREMENT,
	DELIVERY_RECEIPT_ID int(10) unsigned NOT NULL,
	EB_OBJECT_ID int(10) unsigned DEFAULT NULL,
	WAREHOUSE_ID int(10) unsigned NOT NULL,
	ITEM_ID int(10) unsigned NOT NULL,
	QUANTITY double NOT NULL,
	ITEM_SRP_ID int(10) unsigned DEFAULT NULL,
	SRP double DEFAULT '0',
	UNIT_COST double NOT NULL,
	DISCOUNT double DEFAULT 0,
	TAX_TYPE_ID int(10) unsigned DEFAULT NULL,
	VAT_AMOUNT double DEFAULT '0',
	AMOUNT double DEFAULT '0',
	ITEM_DISCOUNT_ID int(10) unsigned DEFAULT NULL,
	ITEM_ADD_ON_ID int(10) unsigned DEFAULT NULL,
	ITEM_DISCOUNT_TYPE_ID int(10) unsigned DEFAULT NULL,
	DISCOUNT_VALUE double DEFAULT '0',
	PRIMARY KEY (DELIVERY_RECEIPT_ITEM_ID),
	KEY FK_DRI_DELIVERY_RECEIPT_ID (DELIVERY_RECEIPT_ID),
	KEY FK_DRI_EB_OBJECT_ID (EB_OBJECT_ID),
	KEY FK_DRI_WAREHOUSE_ID (WAREHOUSE_ID),
	KEY FK_DRI_ITEM_ID (ITEM_ID),
	KEY FK_DRI_ITEM_SRP_ID (ITEM_SRP_ID),
	KEY FK_DRI_TAX_TYPE_ID (TAX_TYPE_ID),
	KEY FK_DRI_ITEM_DISCOUNT_ID (ITEM_DISCOUNT_ID),
	KEY FK_DRI_ITEM_ADD_ON_ID (ITEM_ADD_ON_ID),
	KEY FK_DRI_ITEM_DISCOUNT_TYPE_ID (ITEM_DISCOUNT_TYPE_ID),
	CONSTRAINT FK_DRI_DELIVERY_RECEIPT_ID FOREIGN KEY (DELIVERY_RECEIPT_ID) REFERENCES DELIVERY_RECEIPT (DELIVERY_RECEIPT_ID),
	CONSTRAINT FK_DRI_EB_OBJECT_ID FOREIGN KEY (EB_OBJECT_ID) REFERENCES EB_OBJECT (EB_OBJECT_ID),
	CONSTRAINT FK_DRI_WAREHOUSE_ID FOREIGN KEY (WAREHOUSE_ID) REFERENCES WAREHOUSE (WAREHOUSE_ID),
	CONSTRAINT FK_DRI_ITEM_ID FOREIGN KEY (ITEM_ID) REFERENCES ITEM (ITEM_ID),
	CONSTRAINT FK_DRI_ITEM_SRP_ID FOREIGN KEY (ITEM_SRP_ID) REFERENCES ITEM_SRP (ITEM_SRP_ID),
	CONSTRAINT FK_DRI_TAX_TYPE_ID FOREIGN KEY (TAX_TYPE_ID) REFERENCES TAX_TYPE (TAX_TYPE_ID),
	CONSTRAINT FK_DRI_ITEM_DISCOUNT_ID FOREIGN KEY (ITEM_DISCOUNT_ID) REFERENCES ITEM_DISCOUNT (ITEM_DISCOUNT_ID),
	CONSTRAINT FK_DRI_ITEM_ADD_ON_ID FOREIGN KEY (ITEM_ADD_ON_ID) REFERENCES ITEM_ADD_ON (ITEM_ADD_ON_ID),
	CONSTRAINT FK_DRI_ITEM_DISCOUNT_TYPE_ID FOREIGN KEY (ITEM_DISCOUNT_TYPE_ID) REFERENCES ITEM_DISCOUNT_TYPE (ITEM_DISCOUNT_TYPE_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;