
-- Description	: SQL script that will create DELIVERY_RECEIPT_TYPE table

CREATE TABLE DELIVERY_RECEIPT_TYPE (
	DELIVERY_RECEIPT_TYPE_ID int(10) unsigned NOT NULL AUTO_INCREMENT,
	NAME varchar(50) NOT NULL,
	ACTIVE tinyint(1) NOT NULL,
	PRIMARY KEY (DELIVERY_RECEIPT_TYPE_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;