
-- Description : Create sql script for DIVISION_PROJECT.

DROP TABLE IF EXISTS DIVISION_PROJECT;

CREATE TABLE DIVISION_PROJECT (
  DIVISION_PROJECT_ID int(10) unsigned NOT NULL AUTO_INCREMENT,
  DIVISION_ID int(10) unsigned NOT NULL,
  PROJECT_ID int(10) unsigned NOT NULL,
  CREATED_BY int(10) unsigned NOT NULL,
  CREATED_DATE timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  UPDATED_BY int(10) unsigned NOT NULL,
  UPDATED_DATE timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  PRIMARY KEY (DIVISION_PROJECT_ID),
  KEY FK_DIVISION_PROJECT_DIV_ID (DIVISION_ID),
  KEY FK_DIVISION_PROJECT_PROJ_ID (PROJECT_ID),
  KEY FK_DIVISION_PROJECT_CREATED_BY (CREATED_BY),
  KEY FK_DIVISION_PROJECT_UPDATED_BY (UPDATED_BY),
  CONSTRAINT FK_DIVISION_PROJECT_DIV_ID FOREIGN KEY (DIVISION_ID) REFERENCES DIVISION (DIVISION_ID),
  CONSTRAINT FK_DIVISION_PROJECT_PROJ_ID FOREIGN KEY (PROJECT_ID) REFERENCES AR_CUSTOMER (AR_CUSTOMER_ID),
  CONSTRAINT FK_DIVISION_PROJECT_CREATED_BY FOREIGN KEY (CREATED_BY) REFERENCES USER (USER_ID),
  CONSTRAINT FK_DIVISION_PROJECT_UPDATED_BY FOREIGN KEY (UPDATED_BY) REFERENCES USER (USER_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;