
-- Description	: SQL script that will create LOAN_PROCEED_TYPE table

DROP TABLE IF EXISTS LOAN_PROCEEDS_TYPE;

CREATE TABLE LOAN_PROCEEDS_TYPE (
	LOAN_PROCEEDS_TYPE_ID int(10) unsigned NOT NULL AUTO_INCREMENT,
	NAME varchar(50) NOT NULL,
	ACTIVE tinyint(1) NOT NULL,
	PRIMARY KEY (LOAN_PROCEEDS_TYPE_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;