
-- Description	: SQL script that will create PROJECT_RETENTION_TYPE table

DROP TABLE IF EXISTS PROJECT_RETENTION_TYPE;

CREATE TABLE PROJECT_RETENTION_TYPE (
	PROJECT_RETENTION_TYPE_ID int(10) unsigned NOT NULL AUTO_INCREMENT,
	NAME varchar(50) NOT NULL,
	ACTIVE tinyint(1) NOT NULL,
	PRIMARY KEY (PROJECT_RETENTION_TYPE_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;