
-- Description	: A create script that will create SALES_QUOTATION_ITEM table

DROP TABLE IF EXISTS SALES_QUOTATION_ITEM;

CREATE TABLE SALES_QUOTATION_ITEM (
	SALES_QUOTATION_ITEM_ID int(10) unsigned NOT NULL AUTO_INCREMENT,
	SALES_QUOTATION_ID int(10) unsigned NOT NULL,
	EB_OBJECT_ID int(10) unsigned DEFAULT NULL,
	ITEM_ID int(10) unsigned NOT NULL,
	QUANTITY double DEFAULT '0',
	GROSS_AMOUNT double DEFAULT '0',
	TAX_TYPE_ID int(10) unsigned DEFAULT NULL,
	VAT_AMOUNT double DEFAULT '0',
	AMOUNT double DEFAULT '0',
	ITEM_DISCOUNT_TYPE_ID int(10) unsigned DEFAULT NULL,
	DISCOUNT_VALUE double DEFAULT '0',
	DISCOUNT double DEFAULT '0',
	MEMO text,
	PRIMARY KEY (SALES_QUOTATION_ITEM_ID),
	KEY FK_SQI_SALES_QUOTATION_ID (SALES_QUOTATION_ID),
	KEY FK_SQI_EB_OBJECT_ID (EB_OBJECT_ID),
	KEY FK_SQI_ITEM_ID (ITEM_ID),
	KEY FK_SQI_ITEM_DISCOUNT_TYPE_ID (ITEM_DISCOUNT_TYPE_ID),
	CONSTRAINT FK_SQI_SALES_QUOTATION_ID FOREIGN KEY (SALES_QUOTATION_ID) REFERENCES SALES_QUOTATION (SALES_QUOTATION_ID),
	CONSTRAINT FK_SQI_EB_OBJECT_ID FOREIGN KEY (EB_OBJECT_ID) REFERENCES EB_OBJECT (EB_OBJECT_ID),
	CONSTRAINT FK_SQI_ITEM_ID FOREIGN KEY (ITEM_ID) REFERENCES ITEM (ITEM_ID),
	CONSTRAINT FK_SQI_ITEM_DISCOUNT_TYPE_ID FOREIGN KEY (ITEM_DISCOUNT_TYPE_ID) REFERENCES ITEM_DISCOUNT_TYPE (ITEM_DISCOUNT_TYPE_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;