
-- Description	: Add repacking item from and to amount column

ALTER TABLE REPACKING_ITEM ADD COLUMN FROM_AMOUNT DOUBLE DEFAULT 0;
ALTER TABLE REPACKING_ITEM ADD COLUMN TO_AMOUNT DOUBLE DEFAULT 0;

UPDATE REPACKING_ITEM SET FROM_AMOUNT = ROUND((QUANTITY * UNIT_COST), 2);
UPDATE REPACKING_ITEM SET TO_AMOUNT = ROUND((REPACKED_QUANTITY * REPACKED_UNIT_COST), 2);