
-- Description : Update script that will balance the trial balance of NSB 

-- AP Invoice
UPDATE AP_INVOICE SET WT_AMOUNT = '71.87' WHERE (AP_INVOICE_ID = '2253');

UPDATE AP_INVOICE SET WT_AMOUNT = '78.12' WHERE (AP_INVOICE_ID = '6323');

UPDATE AP_INVOICE SET WT_AMOUNT = '15.62' WHERE (AP_INVOICE_ID = '4742');

UPDATE AP_INVOICE SET WT_AMOUNT = '135.62' WHERE (AP_INVOICE_ID = '3994');

UPDATE AP_INVOICE SET WT_AMOUNT = '6.67' WHERE (AP_INVOICE_ID = '5636');

UPDATE AP_INVOICE SET WT_AMOUNT = '296.62' WHERE (AP_INVOICE_ID = '2251');

UPDATE AP_INVOICE SET WT_AMOUNT = '30.62' WHERE (AP_INVOICE_ID = '5496');

UPDATE AP_INVOICE SET AMOUNT = ROUND(AMOUNT, 2);
UPDATE AP_INVOICE SET WT_AMOUNT = ROUND(WT_AMOUNT, 2);
UPDATE AP_LINE SET AMOUNT = ROUND(AMOUNT, 2);
UPDATE AP_LINE SET VAT_AMOUNT = ROUND(VAT_AMOUNT, 2);

-- AP Invoice goods and Services
ALTER TABLE AP_INVOICE_GOODS 
ADD COLUMN AMOUNT DOUBLE NOT NULL DEFAULT 0 AFTER DISCOUNT;

-- ask client about this
update AP_INVOICE set AMOUNT = (ROUND(AMOUNT,2));
UPDATE AP_INVOICE_GOODS set AMOUNT = ROUND((UNIT_COST * QUANTITY),2);
UPDATE AP_INVOICE_GOODS set VAT_AMOUNT = ROUND(((UNIT_COST * QUANTITY)*1.12)-(UNIT_COST * QUANTITY),2) where VAT_AMOUNT is not null AND AP_INVOICE_GOODS_ID != 723;
update AP_INVOICE_LINE set AMOUNT = ROUND(AMOUNT,2);
update AP_INVOICE_LINE set VAT_AMOUNT = ROUND(VAT_AMOUNT,2) WHERE VAT_AMOUNT IS NOT NULL;

UPDATE AP_INVOICE SET AMOUNT = 14124.03 WHERE AP_INVOICE_ID = 2349;
UPDATE AP_INVOICE SET WT_AMOUNT = 84.88 WHERE AP_INVOICE_ID = 9069;
UPDATE AP_INVOICE SET WT_AMOUNT = 178.12 WHERE AP_INVOICE_ID = 7776;
UPDATE AP_INVOICE SET WT_AMOUNT = 15.62 WHERE AP_INVOICE_ID = 8216;

update AP_INVOICE_GOODS set AMOUNT = 703.12 where AP_INVOICE_GOODS_ID=305;
update AP_INVOICE_GOODS set AMOUNT = 421.87 where AP_INVOICE_GOODS_ID=722;
update AP_INVOICE_GOODS set AMOUNT = 534.38 where AP_INVOICE_GOODS_ID=723;
update AP_INVOICE_GOODS set VAT_AMOUNT = 64.12 where AP_INVOICE_GOODS_ID=723;
update AP_INVOICE_GOODS set AMOUNT = 2651.79 where AP_INVOICE_GOODS_ID=850;
update AP_INVOICE_GOODS set AMOUNT = 3339.29 where AP_INVOICE_GOODS_ID=853;
update AP_INVOICE_GOODS set AMOUNT = 3339.29 where AP_INVOICE_GOODS_ID=856;
update AP_INVOICE_GOODS set AMOUNT = 3339.29 where AP_INVOICE_GOODS_ID=858;
update AP_INVOICE_GOODS set VAT_AMOUNT = 1.12 where AP_INVOICE_GOODS_ID=910;
update AP_INVOICE_GOODS set AMOUNT = 2661.05 where AP_INVOICE_GOODS_ID=178;

-- AR Transaction
UPDATE AR_TRANSACTION SET AMOUNT = ROUND(AMOUNT,2);
UPDATE AR_TRANSACTION SET WT_AMOUNT = ROUND(WT_AMOUNT,2);
UPDATE AR_TRANSACTION SET WT_VAT_AMOUNT = ROUND(WT_VAT_AMOUNT,2);
UPDATE AR_SERVICE_LINE set AMOUNT = ROUND(AMOUNT,2);
UPDATE AR_SERVICE_LINE set VAT_AMOUNT = ROUND(VAT_AMOUNT,2);

UPDATE AR_SERVICE_LINE AR_LINE SET AMOUNT  =  ROUND(AMOUNT + (SELECT VARIANCE FROM (
	SELECT AR_TRANSACTION_ID, ROUND(TOTAL_HEADER,2) - ROUND((LINE_AMOUNT + LINE_VAT_AMOUNT),2) AS VARIANCE  FROM (
	SELECT AR_TRANSACTION_ID,AMOUNT, WT_VAT_AMOUNT, WT_AMOUNT,(AMOUNT+ WT_VAT_AMOUNT+ WT_AMOUNT) AS TOTAL_HEADER, 
	coalesce((SELECT SUM(AMOUNT) FROM AR_SERVICE_LINE ASL WHERE ART.AR_TRANSACTION_ID = ASL.AR_TRANSACTION_ID),0) AS LINE_AMOUNT,
	coalesce((SELECT SUM(VAT_AMOUNT) FROM AR_SERVICE_LINE ASL WHERE ART.AR_TRANSACTION_ID = ASL.AR_TRANSACTION_ID),0)AS LINE_VAT_AMOUNT
	FROM AR_TRANSACTION ART) AS T1 WHERE ROUND(TOTAL_HEADER,2) != ROUND((LINE_AMOUNT + LINE_VAT_AMOUNT),2)) AS T1 WHERE T1.AR_TRANSACTION_ID=AR_LINE.AR_TRANSACTION_ID),2)
    WHERE AR_LINE.AR_TRANSACTION_ID IN (SELECT AR_TRANSACTION_ID FROM (
		SELECT AR_TRANSACTION_ID, ROUND(TOTAL_HEADER,2) - ROUND((LINE_AMOUNT + LINE_VAT_AMOUNT),2) AS VARIANCE  FROM (
		SELECT AR_TRANSACTION_ID,AMOUNT, WT_VAT_AMOUNT, WT_AMOUNT,(AMOUNT+ WT_VAT_AMOUNT+ WT_AMOUNT) AS TOTAL_HEADER, 
		coalesce((SELECT SUM(AMOUNT) FROM AR_SERVICE_LINE ASL WHERE ART.AR_TRANSACTION_ID = ASL.AR_TRANSACTION_ID),0) AS LINE_AMOUNT,
		coalesce((SELECT SUM(VAT_AMOUNT) FROM AR_SERVICE_LINE ASL WHERE ART.AR_TRANSACTION_ID = ASL.AR_TRANSACTION_ID),0)AS LINE_VAT_AMOUNT
	FROM AR_TRANSACTION ART) AS T1 WHERE ROUND(TOTAL_HEADER,2) != ROUND((LINE_AMOUNT + LINE_VAT_AMOUNT),2)) AS T1);


-- AR INVOICE
UPDATE AR_INVOICE SET AMOUNT = ROUND(AMOUNT,2);
UPDATE AR_INVOICE SET WT_AMOUNT = ROUND(WT_AMOUNT,2);
UPDATE AR_INVOICE SET WT_VAT_AMOUNT = ROUND(WT_VAT_AMOUNT,2);
UPDATE AR_INVOICE_LINE SET AMOUNT = ROUND(AMOUNT,2);
UPDATE AR_INVOICE_LINE SET VAT_AMOUNT = ROUND(VAT_AMOUNT,2);
UPDATE AR_INVOICE_ITEM SET AMOUNT = ROUND(AMOUNT,2);
UPDATE AR_INVOICE_ITEM SET VAT_AMOUNT = ROUND(VAT_AMOUNT,2);

update AR_INVOICE ARI set AMOUNT = ROUND(AMOUNT - (select VARIANCE from (
SELECT AR_INVOICE_ID,ROUND(TOTAL_HEADER,2),ROUND(TOTAL_LINE,2),VARIANCE, (SELECT COUNT(*) FROM AR_INVOICE_ITEM AII WHERE T1.AR_INVOICE_ID=AII.AR_INVOICE_ID) AS ITEM_COUNT, 
(SELECT COUNT(*) FROM AR_INVOICE_LINE AIL WHERE T1.AR_INVOICE_ID=AIL.AR_INVOICE_ID) AS SERVICE_COUNT,
(select COUNT(*) from AR_RECEIPT_LINE ARL
INNER JOIN OBJECT_TO_OBJECT OO on OO.TO_OBJECT_ID = ARL.EB_OBJECT_ID
WHERE OO.FROM_OBJECT_ID = T1.EB_OBJECT_ID) AR_RECEIPT_LINE_COUNT
  FROM (
		SELECT AR_INVOICE_ID, EB_OBJECT_ID, TOTAL_HEADER, ((LINE_AMOUNT_ITEM-LINE_DISCOUNT_ITEM) + LINE_VAT_AMOUNT_ITEM + (LINE_AMOUNT_LINE-LINE_DISCOUNT_LINE) + LINE_VAT_LINE) AS TOTAL_LINE,
        ROUND(TOTAL_HEADER,2) - ROUND(((LINE_AMOUNT_ITEM-LINE_DISCOUNT_ITEM) + LINE_VAT_AMOUNT_ITEM + (LINE_AMOUNT_LINE-LINE_DISCOUNT_LINE) + LINE_VAT_LINE),2) AS VARIANCE   FROM (
		SELECT AR_INVOICE_ID, EB_OBJECT_ID, AMOUNT, WT_VAT_AMOUNT, WT_AMOUNT,ABS((AMOUNT+ WT_VAT_AMOUNT+ WT_AMOUNT-coalesce(RETENTION,0))) AS TOTAL_HEADER, 
		coalesce((SELECT SUM(AMOUNT) FROM AR_INVOICE_ITEM AII WHERE ARI.AR_INVOICE_ID = AII.AR_INVOICE_ID),0) AS LINE_AMOUNT_ITEM,
        coalesce((SELECT SUM(DISCOUNT) FROM AR_INVOICE_ITEM AII WHERE ARI.AR_INVOICE_ID = AII.AR_INVOICE_ID),0) AS LINE_DISCOUNT_ITEM,
		coalesce((SELECT SUM(VAT_AMOUNT) FROM AR_INVOICE_ITEM AII WHERE ARI.AR_INVOICE_ID = AII.AR_INVOICE_ID),0)AS LINE_VAT_AMOUNT_ITEM,
        coalesce((SELECT SUM(AMOUNT) FROM AR_INVOICE_LINE AII WHERE ARI.AR_INVOICE_ID = AII.AR_INVOICE_ID),0) AS LINE_AMOUNT_LINE,
        coalesce((SELECT SUM(DISCOUNT) FROM AR_INVOICE_LINE AII WHERE ARI.AR_INVOICE_ID = AII.AR_INVOICE_ID),0) AS LINE_DISCOUNT_LINE,
        coalesce((SELECT SUM(VAT_AMOUNT) FROM AR_INVOICE_LINE AII WHERE ARI.AR_INVOICE_ID = AII.AR_INVOICE_ID),0) AS LINE_VAT_LINE
	FROM AR_INVOICE ARI 
    INNER JOIN FORM_WORKFLOW FW ON FW.FORM_WORKFLOW_ID = ARI.FORM_WORKFLOW_ID
    WHERE FW.CURRENT_STATUS_ID != 4 AND CURRENCY_RATE_ID != 1
    ) AS T1 WHERE ROUND(TOTAL_HEADER,2) != ROUND(((LINE_AMOUNT_ITEM-LINE_DISCOUNT_ITEM) + LINE_VAT_AMOUNT_ITEM + (LINE_AMOUNT_LINE-LINE_DISCOUNT_LINE) + LINE_VAT_LINE),2)) T1 )
    t2 where t2.AR_INVOICE_ID=ARI.AR_INVOICE_ID),2)
WHERE ARI.AR_INVOICE_ID IN (select AR_INVOICE_ID from (
SELECT AR_INVOICE_ID,ROUND(TOTAL_HEADER,2),ROUND(TOTAL_LINE,2),VARIANCE, (SELECT COUNT(*) FROM AR_INVOICE_ITEM AII WHERE T1.AR_INVOICE_ID=AII.AR_INVOICE_ID) AS ITEM_COUNT, 
(SELECT COUNT(*) FROM AR_INVOICE_LINE AIL WHERE T1.AR_INVOICE_ID=AIL.AR_INVOICE_ID) AS SERVICE_COUNT,
(select COUNT(*) from AR_RECEIPT_LINE ARL
INNER JOIN OBJECT_TO_OBJECT OO on OO.TO_OBJECT_ID = ARL.EB_OBJECT_ID
WHERE OO.FROM_OBJECT_ID = T1.EB_OBJECT_ID) AR_RECEIPT_LINE_COUNT
  FROM (
		SELECT AR_INVOICE_ID, EB_OBJECT_ID, TOTAL_HEADER, ((LINE_AMOUNT_ITEM-LINE_DISCOUNT_ITEM) + LINE_VAT_AMOUNT_ITEM + (LINE_AMOUNT_LINE-LINE_DISCOUNT_LINE) + LINE_VAT_LINE) AS TOTAL_LINE,
        ROUND(TOTAL_HEADER,2) - ROUND(((LINE_AMOUNT_ITEM-LINE_DISCOUNT_ITEM) + LINE_VAT_AMOUNT_ITEM + (LINE_AMOUNT_LINE-LINE_DISCOUNT_LINE) + LINE_VAT_LINE),2) AS VARIANCE   FROM (
		SELECT AR_INVOICE_ID, EB_OBJECT_ID, AMOUNT, WT_VAT_AMOUNT, WT_AMOUNT,ABS((AMOUNT+ WT_VAT_AMOUNT+ WT_AMOUNT-coalesce(RETENTION,0))) AS TOTAL_HEADER, 
		coalesce((SELECT SUM(AMOUNT) FROM AR_INVOICE_ITEM AII WHERE ARI.AR_INVOICE_ID = AII.AR_INVOICE_ID),0) AS LINE_AMOUNT_ITEM,
        coalesce((SELECT SUM(DISCOUNT) FROM AR_INVOICE_ITEM AII WHERE ARI.AR_INVOICE_ID = AII.AR_INVOICE_ID),0) AS LINE_DISCOUNT_ITEM,
		coalesce((SELECT SUM(VAT_AMOUNT) FROM AR_INVOICE_ITEM AII WHERE ARI.AR_INVOICE_ID = AII.AR_INVOICE_ID),0)AS LINE_VAT_AMOUNT_ITEM,
        coalesce((SELECT SUM(AMOUNT) FROM AR_INVOICE_LINE AII WHERE ARI.AR_INVOICE_ID = AII.AR_INVOICE_ID),0) AS LINE_AMOUNT_LINE,
        coalesce((SELECT SUM(DISCOUNT) FROM AR_INVOICE_LINE AII WHERE ARI.AR_INVOICE_ID = AII.AR_INVOICE_ID),0) AS LINE_DISCOUNT_LINE,
        coalesce((SELECT SUM(VAT_AMOUNT) FROM AR_INVOICE_LINE AII WHERE ARI.AR_INVOICE_ID = AII.AR_INVOICE_ID),0) AS LINE_VAT_LINE
	FROM AR_INVOICE ARI 
    INNER JOIN FORM_WORKFLOW FW ON FW.FORM_WORKFLOW_ID = ARI.FORM_WORKFLOW_ID
    WHERE FW.CURRENT_STATUS_ID != 4 AND CURRENCY_RATE_ID != 1
    ) AS T1 WHERE ROUND(TOTAL_HEADER,2) != ROUND(((LINE_AMOUNT_ITEM-LINE_DISCOUNT_ITEM) + LINE_VAT_AMOUNT_ITEM + (LINE_AMOUNT_LINE-LINE_DISCOUNT_LINE) + LINE_VAT_LINE),2)) T1 )
    t2);

UPDATE AR_RECEIPT_LINE SET AMOUNT = 7552.08 WHERE AR_RECEIPT_LINE_ID=2040;
UPDATE AR_RECEIPT_LINE SET AMOUNT = 6293.39 WHERE AR_RECEIPT_LINE_ID=2041;
UPDATE AR_RECEIPT_LINE SET AMOUNT = 78632.93 WHERE AR_RECEIPT_LINE_ID=1291;

-- Check if this is already paid when running in the production db. 
update AR_INVOICE set AMOUNT = 1654830.35 where AR_INVOICE_ID = 1383;

-- Account collection
UPDATE AR_RECEIPT_LINE SET AMOUNT = ROUND(AMOUNT, 2);
UPDATE AR_RECEIPT SET AMOUNT = ROUND(AMOUNT, 2) WHERE AR_RECEIPT_ID IN (79, 153);

-- RECIEPT METHOD with different bank account division
-- 	AR NSB3 UB 132530002924
-- AR BDO 004310024362
-- LP NSB3 UB10303000335

UPDATE AP_INVOICE SET AMOUNT=-8671.87 WHERE AP_INVOICE_ID=10057;
UPDATE AP_INVOICE SET AMOUNT=8671.87 WHERE AP_INVOICE_ID=10058;
UPDATE AP_INVOICE SET AMOUNT=5619.37 WHERE AP_INVOICE_ID=9859;
UPDATE AP_INVOICE SET AMOUNT=901.87 WHERE AP_INVOICE_ID=12587;
UPDATE AP_INVOICE SET AMOUNT=901.87 WHERE AP_INVOICE_ID=12590;
UPDATE AP_INVOICE SET AMOUNT=-3399.37 WHERE AP_INVOICE_ID=10107;
UPDATE AP_INVOICE SET AMOUNT=3399.37 WHERE AP_INVOICE_ID=10109;
UPDATE AP_INVOICE_GOODS SET AMOUNT=2678.57 WHERE AP_INVOICE_GOODS_ID=2020;
UPDATE AP_INVOICE_LINE SET AMOUNT=1330.53 WHERE AP_INVOICE_LINE_ID=7112;
UPDATE AP_PAYMENT_LINE SET PAID_AMOUNT = ROUND(PAID_AMOUNT, 2) WHERE AP_PAYMENT_ID=4493;
UPDATE AP_PAYMENT_LINE SET PAID_AMOUNT = ROUND(PAID_AMOUNT, 2) WHERE AP_PAYMENT_ID=4505;
UPDATE AP_PAYMENT_LINE SET PAID_AMOUNT = 5619.37 WHERE AP_PAYMENT_LINE_ID=8138;
UPDATE AP_PAYMENT_LINE SET PAID_AMOUNT = 901.87 WHERE AP_PAYMENT_LINE_ID=8434;
UPDATE AP_PAYMENT_LINE SET PAID_AMOUNT = 901.87 WHERE AP_PAYMENT_LINE_ID=8435;
UPDATE AR_INVOICE_LINE SET AMOUNT = 190350 WHERE AR_INVOICE_LINE_ID=876;
UPDATE AR_INVOICE_LINE SET AMOUNT = 571500 WHERE AR_INVOICE_LINE_ID=2173;
UPDATE AP_INVOICE SET AMOUNT=117.77 WHERE AP_INVOICE_ID=9892;

UPDATE RECEIPT_METHOD SET BANK_ACCOUNT_ID = 21 WHERE RECEIPT_METHOD_ID = 2;

UPDATE RECEIPT_METHOD SET BANK_ACCOUNT_ID = 20 WHERE RECEIPT_METHOD_ID = 4;

UPDATE AP_INVOICE_GOODS SET VAT_AMOUNT = 28.12 WHERE AP_INVOICE_GOODS_ID = 1794;
UPDATE AP_INVOICE_GOODS SET AMOUNT = 2678.57 WHERE AP_INVOICE_GOODS_ID = 2020;
UPDATE AP_INVOICE_LINE SET AMOUNT = 16.78 WHERE AP_INVOICE_LINE_ID = 5062;
UPDATE AR_INVOICE SET WT_AMOUNT=765, AMOUNT=37485 WHERE AR_INVOICE_ID = 1719;

-- wrong receipt method
-- LP NSB5 UB103030003351

