
-- Description	: Add loan proceed amount column

ALTER TABLE LOAN_PROCEEDS ADD COLUMN LOAN_PROCEED_AMOUNT DOUBLE DEFAULT 0;

CREATE TABLE TMP_TBL
SELECT *, ROUND(AMOUNT-WT_AMOUNT-TOTAL_GROSS_AMOUNT, 2) AS LOAN_PROCEED_AMOUNT FROM (
SELECT LP.LOAN_PROCEEDS_ID, LP.DIVISION_ID, LP.SEQUENCE_NO, LP.AMOUNT, LP.WT_AMOUNT,
COALESCE((SELECT SUM(LPL.AMOUNT + COALESCE(LPL.VAT_AMOUNT, 0)) 
FROM LP_LINE LPL WHERE LPL.LOAN_PROCEEDS_ID = LP.LOAN_PROCEEDS_ID), 0) AS TOTAL_GROSS_AMOUNT
FROM LOAN_PROCEEDS LP
INNER JOIN FORM_WORKFLOW FW ON FW.FORM_WORKFLOW_ID = LP.FORM_WORKFLOW_ID
WHERE FW.CURRENT_STATUS_ID != 4
) AS TBL;

UPDATE LOAN_PROCEEDS LP
INNER JOIN TMP_TBL TT ON TT.LOAN_PROCEEDS_ID = LP.LOAN_PROCEEDS_ID
SET LP.LOAN_PROCEED_AMOUNT = TT.LOAN_PROCEED_AMOUNT;

DROP TABLE IF EXISTS TMP_TBL;